### ISSUE TITLE
Conditional compilation for CustomEquality

### ISSUE THREAD

**Issue by dmbarbour** [fsharp/fslang-suggestions#1007]
Conditional compilation for equality and comparison should work with CustomEquality and CustomComparison. Not sure exactly how this should be expressed. One idea is to use a more general solution for conditional compilation based on type constraints:

    type FTList<'a> =
        val V : FingerTree<Atom<'a>>
        when 'a : equality
            override x.GetHashCode() = ...
            override x.Equals(yobj) = ...
            interface System.IEquatable<FTList<'a>> = ...

## Use Case

I'm implementing a list view of a 2-3 finger-tree, called FTList. The advantage of FTList over traditional lists is O(1) push and pop to both ends, O(log(min(M,N))) append and splitAt. However, the underlying tree structure is history-dependent, i.e. whether a branch has two or three children will depend on the order of push, pop, split, append, etc.

I can add CustomEquality and CustomComparison for `FTList<'a>` to support equality on the list view, but this forces me to add the `when 'a:comparison` constraint. This is inconsistent with, for example, the List<'a> type, where equality and comparison depend upon the type 'a. 

I have searched for solutions and discovered EqualityConditionalOn and ComparisonConditionalOn, but these work only with implicit structural equality implementations. For CustomEquality, these do nothing at all because EqualityConditionalOn won't erase the explicit overrides or IEquatable interface.

For now, I can just accept the 'comparison constraint, but stumbling on this makes me miss Haskell typeclasses.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

Ability to model value views that abstract structure, such as a list view of a finger-tree.

The disadvantages of making this adjustment to F# are ...

Someone needs to think hard about how to make it work and fit nicely into the F# style.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XL

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
Yes this is reasonable, unless there are technical details I have forgotten.

**Comment by TysonMN** [comment]
I am not sure I follow.  Can you give a small amount of example code?  Because of my lack of understanding, I am unsure which of the following would be best.
 1. Code that compiles now, but you don't want to compile.
2. Code that doesn't compile now, but you do want to compile.
3. Code that compiles now and behaves in a certain way, and you want it to continue to compile but behave in a different way.

Maybe that code fragment you gave was meant to be such an example.  If so, which of those three is it?

**Comment by dmbarbour** [comment]
Current Status: Whether `List<'a>` (which uses default equality) has equality is contingent on `'a`, but whether my `FTList<'a>` (which uses custom equality) has equality cannot be contingent on `'a` due to existing limitations of F#. Similar for comparison. 

I suggest fixing this inconsistency. Unclear where or why more detail is required, at least from me. 

The details of FTList<'a> are certainly extraneous. It's sufficient to know it needs custom equality. I proposed a viable syntax for conditional compilation, but you could easily use something else - that isn't a detail I care about. Implementation details are entirely outside the scope of my suggestion.
