### ISSUE TITLE
Printf format as binary number

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1008]
# Printf format as binary number

I propose we allow `printf "%B" 10` which outputs `1010`.

The existing way of approaching this problem in F# is going through `Convert.ToString(..., 2)` which is not needed for bases 8 and 16.

This is arguably used more than base 8.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Convenience
2. Consistency, as the standard bases (2, 8, 10, 16) should receive the same treatment.
3. Conciseness

The disadvantages of making this adjustment to F# are that this brings multiple ways to do the same thing, but then `%o` and `%x`/`%X` exist.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
Seems reasonable.  You might want to check with OCaml since our printf design largely aligns with that

**Comment by Happypig375** [comment]
https://stackoverflow.com/questions/39962412/why-is-b-deprecated-in-printf `%b` is deprecated and `%B` is recommended for booleans, and there was an attempt to redefine `%b` for binary numbers but got rejected.

**Comment by jackfoxy** [comment]
This would be a useful formatter, but %B having a different function than %b would be confusing. I can't think of another letter that would be intuitive. Maybe %t (for two)? Or if the parser could handle it %2?

**Comment by Happypig375** [comment]
@jackfoxy `%a` and `%A` already do two different things. Same for `%o` and `%O`.

**Comment by Happypig375** [comment]
Also `%t` is already defined.

**Comment by jackfoxy** [comment]
Darn it, I was looking at an obsolete reference. The problems with searching for documentation...

**Comment by Happypig375** [comment]
@jackfoxy These have been in F# since 1.0. Are you looking at the right language?

**Comment by jackfoxy** [comment]
Nope, looked at the first (or at least most prominent) result of a Bing search for "F# printf".
I've long been of the opinion MS does a poor job of optimizing Bing searches into their own tech documentation. 
In this case what I got was https://www.c-sharpcorner.com/article/printing-and-formatting-outputs-in-fsharp/ which to someone in a hurry (me) looked like a reliable source from its layout.

**Comment by Happypig375** [comment]
Ah yes, c-sharpcorner.com, the website deemed as low quality by the C# subreddit.

**Comment by baronfel** [comment]
For reference, a quick search for "F# printf" got me the official docs for printf specifiers in the language: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/plaintext-formatting#format-specifiers-for-printf

**Comment by Happypig375** [comment]
@jackfoxy `%2` won't work either because it's a width specifier like in `%2d`.

**Comment by Happypig375** [comment]
Closing as implemented in https://github.com/dotnet/fsharp/pull/11603
