### ISSUE TITLE
Assigning to tuples of assignables

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1011]
# Assigning to tuples of assignables

I propose we support assigning to tuples of assignables.

```fs
type A() =
    member val B = [||] with get, set
    [<DefaultValue>] val mutable C : int
    member this.D = &this.B.[0]

let mutable a = A()
a <- A()
a.B <- [|1|]
a.C <- 2
a.D <- 3
(a, a.B, a.C, a.D) <- A(), [|1|], 2, 3 // error FS3228: The address of a value returned from the expression cannot be used at this point. This is to ensure the address of the local value does not escape its scope.
```

The existing way of approaching this problem in F# is assigning separately which makes short code longer.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Consistency with C#

The disadvantage of making this adjustment to F# is that this improves readability of mutations which may go against the preference of immutability.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by jwosty** [comment]
I wonder if this should be abstracted to allow the left hand side of a mutation statement to be any pattern, just like let bindings? For example:

```
type SingleCaseDU = SingleCaseDU of int
let mutable value: int = 42
let update (value': SingleCaseDU) =
    (SingleCaseDU value) <- value'
    value'
```

**Comment by dsyme** [comment]
We won't do this, it's complexifying part of the language in a way that doesn't generalize or really fit with other available concepts
