### ISSUE TITLE
Simplified parameter null validation code

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1014]
I propose we add a new function to simplify parameter null validation code.
```fs
checkNullArg arg
```
That's it!

Example usage:
```fs
let length (array: _[]) =
     checkNullArg array
     array.Length
```

Here will be the secret sauce in FSharp.Core:
```fs
[<AutoOpen; AbstractClass; Sealed>] 
type CheckNullArg =
    static member checkNullArg (argument, [<System.Runtime.CompilerServices.CallerArgumentExpression "argument";
                                            System.Runtime.InteropServices.Optional;
                                            System.Runtime.InteropServices.DefaultParameterValue "">] argumentName : string) =
        if isNull argument then nullArg argumentName
```

This will work by building on [CallerArgumentExpression](https://github.com/fsharp/fslang-suggestions/issues/966). 

The existing way of approaching this problem in F# is [defining this function yourself](https://github.com/dotnet/fsharp/search?q=checkNonNull) or writing the long code every time:
```fs
if isNull argument then nullArg(nameof argument)
```

Compared to the [C# equivalent of this feature](https://github.com/dotnet/csharplang/issues/2145), this does not introduce new syntax (`!`), is much easier to understand (`!` after the argument name itself?), and also makes the intention really explicit without the `!` being too easy to miss.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Convenience
2. Consistency with C#
3. Reduction of boilerplate which hinders reading

The disadvantage of making this adjustment to F# is that this is one more way to do the same thing, but is considerably simpler.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: [CallerArgumentExpression](https://github.com/fsharp/fslang-suggestions/issues/966)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
Open questions:
- Should this be marked `inline`?
- FSharp.Core calls this function `checkNonNull` without the symmetry with `nullArg`. Should this be the name instead?
- Do we need the `System.Runtime.InteropServices.DefaultParameterValue ""`? Will this interfere with nullable reference type analysis in the future?

**Comment by charlesroddie** [comment]
Similarly to https://github.com/fsharp/fslang-suggestions/issues/883 , this needs to be considered in the context of https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md .

Then your example becomes:
```fsharp
let length (array: 'a[]) =
    // don't need a null check here since the function conveys that it expects a non-null argument
    array.Length

// or

let length (array: ('a[])?) =
    match array with
    | Null -> nullArg(nameof argument)
    | NonNull a -> a.Length
```

**Comment by Happypig375** [comment]
@charlesroddie Not really. Like in C# with nullable reference types, the argument itself is nonnullable but it defends against users with nullable reference type analysis disabled.

**Comment by En3Tho** [comment]
It would be nice if ActivePatterns could use this too.

Ideally :
``` fsharp
let (|NotNull|) (obj, [<Optional; DefaultParameterValue(null); CallerArgumentExpression("argument")>] description) = ArgumentNullException.ThrowIfNull(obj, description); obj
let nullCheckingCode (NotNull parameter: string) = printfn $"{parameter}"
```

For now it doesn't work. It would be fun if ActivePatterns could support optional parameters like these.
Today NotNull pattern works with single parameter but there is no way to pass proper argument name there.

**Comment by En3Tho** [comment]
@dsyme Do you think it's possible or reasonable to do with active patterns? I think it's a completely different proposal (like supporting optional parameters in active patterns) but it would be nice if you could take a small look at example above and say if you like the idea at all

**Comment by dsyme** [comment]
>  @dsyme Do you think it's possible or reasonable to do with active patterns? I think it's a completely different proposal (like supporting optional parameters in active patterns) but it would be nice if you could take a small look at example above and say if you like the idea at all

I'm not really sold on doing either of these in FSharp.Core.  I don't really mind how people program it up in user code assuming CallerArgumentExpression is avaialble.

**Comment by dsyme** [comment]
Closing per my comment above
