### ISSUE TITLE
Constructing a record with `yield` keyword

### ISSUE THREAD

**Issue by Alkasai** [fsharp/fslang-suggestions#1016]
# Constructing a record with `yield` keyword

Currently to update a field or number of fields you can construct a record by form another record and modifying just the fields that you need:
``` fsharp
{ foo with
    X = fooX
    Y = fooY
    Z = fooZ }
```

However, if you need to update fields only if a condition is satisfied it becomes a bit verbose:
``` fsharp
{ foo with
    X = fooX
    Y = if blah then fooY else foo.Y
    Z = if blah then fooZ else foo.Z }
```

It would be nice to be able to use a `yield` keyword in this case:
``` fsharp
{ foo with
    X = fooX
    if blah then
        yield (Y = fooY)
        yield (Z = fooZ) }
```
OR
``` fsharp
{ foo with
    X = fooX
    if blahY then
        yield (Y = fooY)
    if blahZ then
        yield (Z = fooZ) }
```

## Pros and Cons 

Pros:
- This would make some record constructions less verbose.

Cons:
- Not sure what syntax would be, since we are trying to mix `yield` with and assignment operator

---
_Note: this was originally posted here https://github.com/dotnet/fsharp/issues/11616, moving it to the correct place._

---
Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
We have implicit yields. Drop the yields!

**Comment by Alkasai** [comment]
So what would it look like without yields?

**Comment by Happypig375** [comment]
```fs
{ foo with
    X = fooX
    if blahY then
        Y = fooY
    if blahZ then
        Z = fooZ }
```

**Comment by Alkasai** [comment]
> The verbose version is much better IMO. If you are thinking of creating new records as "updating" then perhaps there is the wrong construct chosen here and mutable fields are desired.

Perhaps, I personally prefer staying away from mutability. But I guess it would be a good alternative here.

**Comment by Alkasai** [comment]
> The verbose version is much better IMO. If you are thinking of creating new records as "updating" then perhaps there is the wrong construct chosen here and mutable fields are desired.

Perhaps, I personally prefer staying away from mutability. But I guess it would be a good alternative here.

**Comment by thinkbeforecoding** [comment]
The suggestion #1049 could be a more functional version of this.

**Comment by Happypig375** [comment]
With #1049
```fs
{ foo with
    X = fooX
    Y _ when blahY = fooY
    Z _ when blahZ = fooZ }

**Comment by dsyme** [comment]
I'll close this out. 

There's some kind of interesting merging of object expressions and computation expressions here, but it doesn't make a whole lot of sense for F# as it is today.
