### ISSUE TITLE
Tuples on the left side of use bindings, and library helpers to ensure correct init/disposal of multiple expensive disposables

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1019]
https://github.com/fsharp/fslang-suggestions/issues/881#issuecomment-853807713

> People do make mistakes when creating and disposing multiple resources. For example, in the proposed RFC you wrote, sample code like this:
> 
>     static member Dispose((a:#System.IDisposable, b:#System.IDisposable)) =
>         a.Dispose()
>         b.Dispose()
> This is wrong - if the first `Dispose` raises an exception, the second `Dispose` never happens. It's important to write this correctly.
> 
> Other mistakes also happen, notably
> 
>     use x, y = Dispose2 (AllocateBigThing1(), AllocateBigThing2())
> Here if `AllocateBigThing2()` raises an exception then the resources of `AllocateBigThing1()` are never released except via a finalizer. This is hard to avoid and really requires a well-written `AllocateTwoBigThings()` or generic `Disposable2`
> 
>     use x, y = Disposable2 (fun () -> AllocateBigThing1()) (fun () -> AllocateBigThing2())
> or
> 
>     use x, y = Disposable2 AllocateBigThing1 AllocateBigThing2
> C# does bake in language support and codegen to allow multiple resource binding. I think this is the problem that needs solving - making it simpler to allocate and dispose multiple resources correctly.
> 
> I'm not opposed to solving this problem in language/library, e.g. allowing a tuple on the left, with appropriate correct library helpers. However I see no real gain in allowing more complex patterns on the left (even if they happen to be allowed in computation expressions) - because it's not the problem that needs solving, and kind of makes things worse by obfuscating the actual problem.
> 
> Also note `using (fun pat -> ...)` can already be used for an arbitary pattern.
> 

The existing way of approaching this problem in F# is writing possibly erroneous disposals by yourself.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Correctness
2. Convenience
3. Consistency with C#

The disadvantages of making this adjustment to F# are that this may complicate the language by introducing more special rules to `use` bindings.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Frassle** [comment]
It would be nice if this could handle the case of mixed tuples of disposables. We often have functions that return multiple results where one of the results is a plain value and the other is some disposable thing (like `int * IDisposable`) it would be really convenient if we could bind these once but have use semantics kick in for the disposable.
```
// Currently we have to do this
let (x, y) = some_function ()
use y = y

// It would be nice to just do
use (x, y) = some_function()
```

I'd still expect `use (x, y)` to error if none of the items were disposable.

**Comment by Happypig375** [comment]
@dsyme Thoughts on that one?

**Comment by dsyme** [comment]
> It would be nice if this could handle the case of mixed tuples of disposables. 

This would really be a rethinking of the `use` construct to change to a type-directed translation of the construct. It's not a bad thing in itself and the problem is an annoying one to solve. One problem is it makes it tricky to get equivalence with `use` in computation expressions, which use a syntactic translation.

**Comment by charlesroddie** [comment]
I would find it very strange that `use x` takes an `x` which is not `IDisposable`. At the very least it would use a new name. As a very niche case it would ordinarily be up to users to define their own constructs, which they can do already (e.g. as below). So I don't think anything is needed in FSharp.Core.

```fsharp
let using2<'a,'b,'c when 'a:>IDisposable and 'b:>IDisposable> (f:'a * 'b -> 'c) (x:'a, y:'b) =
    let z = f(x, y)
    (x:>IDisposable).Dispose()
    (y:>IDisposable).Dispose()
    z
```

**Comment by Happypig375** [comment]
@charlesroddie You fell straight into the trap described by the third paragraph of the quote.

> This is wrong - if the first `Dispose` raises an exception, the second `Dispose` never happens. It's important to write this correctly.

**Comment by dsyme** [comment]
This originated from a comment of mine.  

On reflection, I think we just can't justify complexifying F# to deal with this case.  The user just has to do the work to program the allocation of the combination of resources as returning a single IDisposable, and if an exception happens in that creation still cleaning up.
