### ISSUE TITLE
Allow digit separators after 0b, 0o, and 0x but before the digits

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1020]
# Allow digit separators after 0b, 0o, and 0x but before the digits

I propose we allow digit separators after 0b, 0o, and 0x but before the digits.
```fs
let x = 0b_1010_0000
let y = 0x_1234_abcd
let z = 0o_1234_4321
```
[C# already implemented this in 7.2.](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.2/leading-separator.md)

The existing way of approaching this problem in F# is to resist your stylistic preferences.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency with C#
1. Freedom of expression
1. Inclusivity!

The disadvantages of making this adjustment to F# are (none).

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: https://github.com/dotnet/roslyn/issues/12680

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
@dsyme Instead of "niche", this is more like a very small improvement. Why not label this as a "good first issue" instead for new contributors? It's a net gain imo.

**Comment by dsyme** [comment]
I'll reopen of someone submits RFC and implementation :)
