### ISSUE TITLE
Covariant return types

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1023]
# Covariant return types

I propose we implement covariant return types in F#, equivalent to [the C# 9.0 feature](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/covariant-returns).

```fs
type [<AbstractClass>] A() = abstract Clone : unit -> A
type B() =
    inherit A()
    override _.Clone() = B()
let b : B = B().Clone()
```
The above code will be valid after https://github.com/dotnet/fsharp/pull/10884 is implemented. However, we cannot enable this feature as-is before merging that because covariant return types depend on .NET 5. An alternative could be:

```fs
type [<AbstractClass>] A() = abstract Clone : unit -> A
type B() =
    inherit A()
    [<CovariantReturn>]
    override _.Clone() = B()
let b : B = B().Clone()
```
or
```fs
type [<AbstractClass>] A() = abstract Clone : unit -> A
type B() =
    inherit A()
    override _.Clone() :[<Covariant>]_ = B()
let b : B = B().Clone()
```
or
```fs
type [<AbstractClass>] A() = abstract Clone : unit -> A
type B() =
    inherit A()
    override _.Clone() : B = B() // Explicit type annotation needed
let b : B = B().Clone()
```

The existing way of approaching this problem in F# is to expose another overridable method with a different name and the derived type.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency with C#
2. Convenience by reusing the same overridable method but with a derived type
3. Conciseness in that we don't have to duplicate methods as we go down the inheritance chain.

The disadvantage of making this adjustment to F# is that this may be too object-oriented for the deign of F#.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
This feature means that `B.Clone()` returns a `B`, while `(B:>A).Clone()` returns an `A`? And it's a way for OO developers to avoid writing two methods `type B() ... member _.CloneB() = ... override t.Clone = t.CloneB():>A`?

I read [the thread](https://github.com/dotnet/csharplang/issues/49) for the C# language suggestion but was no wiser at the end about what the feature is for.

**Comment by cartermp** [comment]
@charlesroddie it's a feature that a lot of C# developers seemed to cheer for when released. But since the value of this feature is in the context of inheritance-oriented code, I think it's likely to be less valuable to routine F# programming scenarios.

That said, my view of routine F# programming could also be a bit limited. Happy to hear about a scenario or two where this would simplify F# programming.

**Comment by Happypig375** [comment]
@charlesroddie Your description is correct.

**Comment by charlesroddie** [comment]
Hopefully F# can ignore this. It seems unlikely that we would be forced to use these things in order to consume common .net libraries.

**Comment by dsyme** [comment]
I'm with @charlesroddie  - this sort of thing flowing in from OO fairy land is just best ignored, because it endlessly complicates the mental model of the F# programmer.
