### ISSUE TITLE
try/with in seq expressions

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1027]
# try/with in seq expressions

[C# is looking to allow yielding values in try/catch blocks in iterator methods.](https://github.com/dotnet/csharplang/issues/2949)
> As [recently noted by C# users](https://github.com/dotnet/csharplang/discussions/765#issuecomment-552612460), the existing restriction that you cannot yield a value in the body of a try block with a catch clause is one that interferes with reasonable code refactoring. The restriction does not make the compiler any easier. Rather it was added to align with the conceptual model that the caller's loop is logically "called" at the point of the `yield`. But that is not how people think of the construct, and the restriction has little value. We propose to remove it.

I propose we also allow this in F#.
```fs
let i =
    seq {
        try // error FS0796: 'try'/'with' cannot be used within sequence expressions
            yield 1
        with _ ->
            yield 2
    }
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency with C#
2. Conciseness
3. Convenience

The disadvantage of making this adjustment to F# is that this may be an already-made design decision?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
We should always have lifted this restriction in F# - it's quite possible in other computation expressions for example.

**Comment by kerams** [comment]
This is finished.

**Comment by vzarytovskii** [comment]
Link to RFC: https://github.com/fsharp/fslang-design/pull/726
