### ISSUE TITLE
Printf format for hex-formatted floating-point numbers

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1028]
# Printf format for hex-formatted floating-point numbers

F# has hex-formatted floating-point numbers in source.
```fs
let ``2.33`` = 0x4002_a3d7_0a3d_70a4LF
```

But there is no reverse where we can get hex-formats from floating-point numbers! I propose we add:
```fs
printfn "%lf" ``2.33`` // 4002a3d70a3d70a4
printfn "%LF" ``2.33`` // 4002A3D70A3D70A4
```

The existing way of approaching this problem in F# is:
```fs
System.BitConverter.GetBytes ``2.33`` |> (if System.BitConverter.IsLittleEndian then Array.rev else id) |> System.BitConverter.ToString |> String.filter ((<>) '-') |> printfn "%s" // %LF
System.BitConverter.GetBytes ``2.33`` |> (if System.BitConverter.IsLittleEndian then Array.rev else id) |> System.BitConverter.ToString |> String.filter ((<>) '-') |> String.map System.Char.ToLowerInvariant |> printfn "%s" // %lf
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency
2. Convenience when learning about floating-point representations
3. Conciseness

The disadvantage of making this adjustment to F# is that this may be of too little use to be included inside FSharp.Core. Then again, `lf` and `LF` suffixes exist, so they are of some use, especially when learning about floating-point representations.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
Better not to add to printf especially something so niche. Already overloaded with complexity. Perhaps post a snip on FSSnip in case anyone wants to use the code?

**Comment by dsyme** [comment]
I agree this is too niche.
