### ISSUE TITLE
Non-local open directives

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1029]
[Global-scoped using directives](https://github.com/dotnet/csharplang/blob/main/proposals/GlobalUsingDirective.md) are being added to C# 10. This will [remove common `open`s at the top of files](https://github.com/dotnet/csharplang/issues/3428).

We could just port this to F# verbatim
```fs
global open System
```
```fs
Console.WriteLine "x" // No opens needed
```
but since F# has a strict file order, these directives won't actually be global, instead they act more like the accessibility of `internal`, being visible only in files coming after the current one:
```fs
Console.WriteLine "x" // error FS0039: The value, namespace, type or module 'Console' is not defined.
```
```fs
open internal System
```
```fs
Console.WriteLine "y" // Ok!
```
This can also be widened to `open public` which are just `open internal` with an additional auto-generated assembly-level `[<AutoOpen>]`:
```fs
namespace N
open internal System.Runtime.CompilerServices
module M =
    [<AbstractClass; Sealed; Extension>]
    type C =
        [<Extension>]
        static member E(obj _) = ()
open type public M.C // Automatically generates [<assembly: AutoOpen "N.M.C">] do ()
```
And we can also have modules that open other namespaces:
```fs
module internal N.Shortcuts
open internal System
open internal System.Runtime.CompilerServices
open internal System.Text.RegularExpressions
open System.Collections // private by default
type seqEnumerator<'T> = System.Collections.Generic.IEnumerator<'T>
type seq = IEnumerable
type seqEnumerator = IEnumerator
open type public System.Linq.Enumerable // If module was public, this will be automatically opened when referenced by other assemblies as well
```
```fs
namespace N.Core
open N.Shortcuts // Brings everything in
```
Ditto for namespaces and types.

The existing way of approaching this problem in F# is to keep a rather long list of `open`s on top of each file. Since F# [won't have namespace aliases directly](https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-6323201-aliases-for-namespaces.md), long namespaces will continue to be typed.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency with C#
2. Conciseness
3. Convenience

The disadvantage of making this adjustment to F# is that just like C#'s global using directives, non-local open directives should also not be spammed everywhere to reduce complexity.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by BentTranberg** [comment]
My intuition says this could get messy in F#, which unlike C# has (in principle) one-pass parsing (or whatever the correct term is). I fear that moving a file within a project can much more easily cause havoc if this feature is much relied on. Not that I totally object - I like the basic idea - but perhaps it would be better to only have this feature in the project file. Then it would also be very easy to implement.

My comment is about the `global open`, and not the `internal` and `public` stuff.

**Comment by Happypig375** [comment]
Use case: https://discordapp.com/channels/196693847965696000/196695876054286336/852218588370305065

crunchable — Today at 00:12
is there a way to re-export all functions from one module to another?  Let's say I have a module A and a module B, and I want to include all the functions from module C into A and B.  Is there a way to do that without using a let binding for each function?

Happypig375 — Today at 00:13
1. Module aliasing module Name = AnotherName
2. Open directives open Module
Either way works

crunchable — Today at 00:14
I think I didn't explain well.  I want module A and B to both expose functions from C in their API
so in A and B I'm currently doing an 
open C
let Test = Test
to get the functions from C exported from A and B
this is for a DSL so at the end of the day I only want to be importing A or B into a script
Not a huge issue as it's not a huge deal to just import C (which is holding common scripting function) into my scripts, just trying to be more succinct for the purposes of the DSL

Happypig375 — Today at 00:19
Hmmm... Rewriting to static members and inheritance could work?

crunchable — Today at 00:20
ah yeah good suggestion, could do that

Happypig375 — Today at 00:21
Just today I wrote a suggestion surrounding this https://github.com/fsharp/fslang-suggestions/issues/1029

crunchable — Today at 00:22
looks like there was a feature request at one time to do what I want:  https://github.com/fsharp/fslang-suggestions/issues/223

Happypig375 — Today at 00:24
Hmmmmmmmmmmmmmmmm

crunchable — Today at 00:24
yeah I see, Ocaml has an include keyword which does exactly that

**Comment by Happypig375** [comment]
Also related: https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-5688199-allow-re-exporting-from-modules.md

> ### Comment by Don Syme on 6/20/2014 8:58:00 AM
>
> Hi all, I generally have a negative predisposition to this feature from my experiences. For example, I've watched some OCaml programmers make a compete mess with it. In the scenarios I've seen, people have been trying to use the feature to achieve mixin-like software engineering composition - though the feature is very limited for this purpose. However, I haven't really seen them succeed with this in any way that looked convincing - and indeed they created code that was very hard to understand even in its basic shape and APIs. I suppose this means I have a general negative predisposition to mixin features (except perhaps traits), since you have to "execute" the mixins to understand the resulting generated API. It seems wrong for F#. F# code (apart from provided APIs) doesn't generally have this property. For F# software engineering APIs - modules and object types - F# code has a "what you see is what you get" property, at least with regard to named items in the modules and object types. Could you point us to examples of OCaml code that uses this in what you regard as very positive ways? Thanks Don
> ### Comment by Don Syme on 9/16/2014 7:34:00 AM
> 
> One particular concern not mentioned before is that type identity (i.e. the exact module where a type was originally defined) would still be visible after the re-export. That is, a signature couldn't hide that fact that a type ultimately came from Impl1 or Impl2 (because in .NET compiled code types have a full path)

**Comment by cartermp** [comment]
Some of the motivation for doing this in C# is a bit different than in F# I think. Since you need to `using` several namespaces to really do anything useful in C# (printing to the console, working with generic collections, etc.) it makes a lot of sense to move in this direction.

For F# I don't think we have a similar place where we're coming from. There is certainly some utility here, like getting access to all of `System.String` and `System.IO` and others. But a lot of routine F# programming doesn't even need a single namespace opened.

I guess this is a roundabout way of me saying I'm sort of on the fence here. I think it's useful. But I don't really know how useful.

**Comment by NinoFloris** [comment]
Eh what?

Not sure if you've done enough aspnet core development 😅
Our Program.fs has 60 lines of opens, asp.net, extensions, system, our own things. Now that's an exceptional file granted, but even something simple as our GCP logger which is about 150 lines has ~20 opens. I checked and I'd say it's about 50/50 whether a file has under or over 15 opens, and if it does it's mostly the usual suspects.

Example of the Logger:
```fs
open Crowded.Common
open System.Collections.Generic
open System.Diagnostics
open System.Globalization
open System.Runtime.CompilerServices
open System.Text
open System.Text.Encodings.Web
open System
open System.IO
open System.Text.Json
open Microsoft.AspNetCore.Http
open Microsoft.Extensions.Logging
open Microsoft.Extensions.Logging.Abstractions
open Microsoft.Extensions.Logging.Console
open Microsoft.Extensions.Options
open Microsoft.Extensions.DependencyInjection
open Microsoft.AspNetCore.Http.Extensions
```

**Comment by BentTranberg** [comment]
I often cut down considerably on the number of opens by e.g. only doing an `open System`, and then `IO.Directory.CreateDirectory` and `IO.File.ReadLines` and so on. Or it could be a single `open Microsoft.Extensions` for everything below that. It's not always practical I admit, but I don't like having opens for just one or a very few cases.

**Comment by BentTranberg** [comment]
Would be nice if on mouse over we could see how many uses each `open` had.

**Comment by Happypig375** [comment]
https://github.com/dotnet/fsharp/issues/11669

**Comment by dsyme** [comment]
If we did something to reduce the number of `open`, I think it would be to allow `global open XYZ` but require that they be the first things in the compilation order.

So I will close this in favour of https://github.com/fsharp/fslang-suggestions/issues/1096
