### ISSUE TITLE
Allow [<DefaultValue>] on member val auto-properties

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#103]
**Submitted by Reed Adams on 4/25/2016 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

This is specifically motivated by my issues with using Entity Framework and how it initializes ``DbSet<'T>`` elements. There might be other applications. In order to correctly interact with EF in C# I may use:

```
public DbSet<RecType> Records { get; set }
```

To accomplish the same thing in F# I must;

```
[<DefaultValue>]
let mutable private _Records: DbSet<RecType>
member x.Records with get() = x._Records and set value = x._Records <- value
```

Not doing so causes the EF wire-ups to be lost when the regular member init-assign is called.
I believe that it would be beneficial to allow the following:
```
[<DefaultValue>]
member val Records: DbSet<RecType> with get, set
```

This would remove a good deal of boilerplate code and more expressively describe what's going on.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13584294)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13584294-allow-[-defaultvalue-]-on-member-val-auto-propert.md#comments)

**Comment by dsyme** [comment]
This seems a bit corner case, given only the few votes from UV and the one known use case.

Closing until more evidence that this is essential is provided.
