### ISSUE TITLE
Add operator (or revamp (!)) to work with op_Implicit

### ISSUE THREAD

**Issue by cmeeren** [fsharp/fslang-suggestions#1037]
It can currently be somewhat painful in F# to deal with (C#) APIs that make heavy use of `op_Implicit`. For example:

```f#
headers.CacheControl <- CacheControlHeaderValue.Parse(StringSegment "private, immutable, max-age=604800")
headers.ContentType <- MediaTypeHeaderValue.Parse(StringSegment contentType)
```

In the above, C# would allow you to pass the strings without calling the `StringSegment ` constructor, since `StringSegment` has an implicit conversion from `string`. However, F# requires us to explicitly call the `StringSegment` constructor. (Other APIs may be even more cumbersome, e.g. if they don't have a constructor and rely exclusively on `op_Implicit`, you would have to type `StringSegment.op_Implicit`).

I propose that we redefine the `(!)` operator like this:

```f#
let inline (!) (x: ^a) : ^b =
    ((^a or ^b): (static member op_Implicit: ^a -> ^b) x)
```

For backwards compatibility with the current usage of dereferencing ref cells, we could add an implicit conversion from from `'a ref` to `'a`.

Another operator could of course also be used.

## Pros and Cons 

This operator would then allow us to do:

```f#
headers.CacheControl <- CacheControlHeaderValue.Parse(!"private, immutable, max-age=604800")
headers.ContentType <- MediaTypeHeaderValue.Parse(!contentType)
```

Furthermore, I have the habit of defining `op_Implicit` for my single-case DUs, to easily "unwrap" them (as well as "wrap" them for the types that don't require any validation). The `(!)` operator makes my DTO mapping code more readable, since it removes unimportant noise (safe transformations):

```f#
let toDto commentId (a: Attachment) : Dtos.CommentAttachment =
  {
    AttachmentId = !a.Id
    CommentId = !commentId
    FileId = !a.File
    Filename = !a.Filename
    NumBytes = a.NumBytes
    CreatedAt = a.CreatedAt
  }
```

Instead of:

```f#
let toDto commentId (a: Attachment) : Dtos.CommentAttachment =
  {
    AttachmentId = a.Id |> AttachmentId.toInt
    CommentId = commentId |> CommentId.toInt
    FileId = a.File |> FileId.toInt
    Filename = a.Filename.value
    NumBytes = a.NumBytes
    CreatedAt = a.CreatedAt
  }
```

Regardless of the use-case, I can't immediately think of any disadvantages. AFAIK it's backwards compatible, and it's more flexible, while still being explicit.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by baronfel** [comment]
How does this suggestions interact with the widening mechanism proposed in this [nearly-complete RFC](https://www.github.com/fsharp/fslang-design/tree/main/RFCs%2FFS-1093-additional-conversions.md)? At a quick glance I think your first example would not be solved, but your second might be.

**Comment by cmeeren** [comment]
Oh, I wasn't aware of that RFC (I just searched this repo for `op_Implicit`).

As I understand the RFC, it would solve everything here. Both my examples would work, just remove the `!` and they'd be correct. Closing this issue, then. Feel free to reopen or continue discussion if you think I'm mistaken.
