### ISSUE TITLE
Better support for complex numbers

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1043]
# Better support for complex numbers

F# has numeric literal suffixes for almost all numeric types, including the 8 types of fixed-size integers, 2 types of native integers, 1 type of arbitrary-sized integer, and 3 types of floating-point numbers. However, the cousin of `bigint` in `System.Numerics`, `Complex` doesn’t get much love.

I propose we make this possible:
```fs
let a = 1+0i
let b = 1.2+2i
let c = sqrt(3-2.4i)
```
How does this work? First, FSharp.Core will define a `NumericLiterali` (like the existing `NumericLiteralI` for `bigint`s) with a `FromFloat` is used (https://github.com/fsharp/fslang-suggestions/issues/445):
```fs
type complex = System.Numerics.Complex
/// i stands for imaginary
module NumericLiterali =
    let FromZero() = complex.Zero
    let FromOne() = complex.ImaginaryOne
    let FromInt32 (x: int32) = complex(0., float x)
    let FromInt64 (x: int64) = complex(0., float x)
    let FromFloat (x:float) = complex(0., x)
```
This makes the example code equivalent to
```fs
type complex = System.Numerics.Complex
let a = 1+complex.Zero
let b = 1.2+complex(0., float 2)
let c = sqrt(3-complex(0., 2.4))
```
Next, we apply the rule of implicit `int32 -> float` as added by https://github.com/dotnet/fsharp/pull/10884:
```fs
type complex = System.Numerics.Complex
let a = float 1+complex.Zero
let b = 1.2+complex(0., float 2)
let c = sqrt(float 3-complex(0., 2.4))
```
Now we arrive at currently compilable code.

The existing way of approaching this problem in F# is to `open System.Numerics` and awkwardly call the constructor despite not having to do this for its cousin `bigint`. F# tries to compete in the data science and scripting space, but the competitors Python and Julia both have complex number literals built-in:
https://docs.python.org/3/library/cmath.html
`b = 1.2 + 2j`
https://docs.julialang.org/en/v1/manual/complex-and-rational-numbers/
`b = 1.2 + 2im`
We should be on-par with them as well.

All these operators for `complex` are supported fine currently:
```fs
let a = System.Numerics.Complex.One
acos a
asin a
atan a
cos a
sin a
tan a
exp a
log a
log10 a
-a
a + a
a - a
a * a
a / a
a ** a
sinh a
cosh a
tanh a
sqrt a
```
But these error:
```fs
abs a
LanguagePrimitives.GenericZero<System.Numerics.Complex>
LanguagePrimitives.GenericOne<System.Numerics.Complex>
```
For `abs`, since the `Abs` of `complex` returns `float` which is a different type from `complex`, this may need its own function called `absc` (`c` for `complex`, just like `f` for `float32`. The generic ones and zeros should be fixed as well.

For consistency with `nan`/`nanf` and `infinity`/`infinityf`, `nanc` and `infinityc` should be added as well.

Maybe `conj` and `polar` can be added as well for completeness?

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Competitiveness with other data science languages
4. Consistency with other numeric types

The disadvantages of making this adjustment to F# are that this is another thing to learn. However, these convenience features are already available for existing numeric types other than `complex`. Why leave this out?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions:
https://github.com/fsharp/fslang-suggestions/issues/445 - Extend custom numeric types to support floating point literals
https://github.com/fsharp/fslang-suggestions/issues/849 - FS-1093 Additional type directed conversions

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
I assume `1. + Complex(0.,1.)` depends on https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1043-extension-members-for-operators-and-srtp-constraints.md

**Comment by Happypig375** [comment]
@charlesroddie 
No, it doesn't.
https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAOgDkBXPBAJwEsBjCAWAChgFsUBDFAXhQEYCUAahQBhGHjgsAHgAoADAQA0/AJRA==

**Comment by charlesroddie** [comment]
That's odd, works in SharpLab but not on my VS:
![image](https://user-images.githubusercontent.com/19760720/126049339-dd15210a-ee44-486a-aa0d-bfe9d678fd66.png)
That means the current syntax is not far from the standard mathematical syntax as above (assuming you are willing to sacrifice a bit of performance with extra operations, which this suggestion does assume).

```fsharp
open System.Numerics
let I = Complex.ImaginaryOne // most horrible thing in .Net complex numbers is this name: in no sense is I a "One"
let x = 5. + 4.*I
```

Allowing more numeric literal types and using one for complex numbers is fine IMO.

I don't think we are going to allow `0+Complex.Zero` if we don't allow `0+0.`. The latter won't happen surely? Are you suggesting it is related to https://github.com/dotnet/fsharp/pull/10884 ?

**Comment by Happypig375** [comment]
@charlesroddie
It uses this overload added in .NET Core 3.0. https://docs.microsoft.com/en-us/dotnet/api/system.numerics.complex.add?view=net-5.0#System_Numerics_Complex_Add_System_Double_System_Numerics_Complex_

> The latter won't happen surely? Are you suggesting it is related to dotnet/fsharp#10884 ?

That PR will introduce an overload resolution rule of `int32 -> float64`, along with `int32 -> int64`. Based on the wording of the RFC, I think this is enabled. This makes `int32` literals act more like generic number literals.

**Comment by charlesroddie** [comment]
> Based on the wording of the RFC, I think this is enabled.

Apparently it will be possible after this RFC with user-defined overloads of (+):
https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1043-extension-members-for-operators-and-srtp-constraints.md#widening-to-specific-type

**Comment by dsyme** [comment]
Programming with complex numbers is just super-rare in practice.  I can't see us baking in support for this into the core of F# - programming with these is quite possible using helper functions and so on.
