### ISSUE TITLE
explicitly apply function instead of Partial and Parameterized Active Patterns

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1046]
I propose we use explicit apply function instead of Partial and Parameterized Active Patterns.

The syntax is:
```F#
match input with
| into function_expr return result_pattern -> to use result_pattern

```
`into` and `return` is keyword, just for demo. for example:

```F#
let muln n inp = if inp % n = 0 then Some(inp / n) else None

let example x =
    match x with
    | into muln 3 return y -> printf "%d" y
    | _ -> failwith ""
```

The existing way of approaching this problem in F# is ...

```F#
let (|MulN|_|) n inp = if inp % n = 0 then Some(inp / n) else None

let example x =
    match x with
    | MulN 3 y -> printf "%d" y
    | _ -> failwith ""
```

## Pros and Cons 

The advantages of making this adjustment to F# are ...

- Programmers will find it more intuitive.
- You do not have to open the module where the pattern definition is located.
- Pattern definitions are just normal value definitions and can be reused in other situations.
- You don't have to comply with pattern matching naming rules.

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
```fs
let (|Into|_|) f x = f x

let muln n inp = if inp % n = 0 then Some(inp / n) else None 
let example x =
    match x with
    | Into (muln 3) y -> printf "%d" y
    | _ -> failwith ""
```

**Comment by xp44mm** [comment]
@Happypig375 Your implementation code is simple and tricky. How I didn't realize it!

**Comment by dsyme** [comment]
Closing this out as the example covers a technique to achieve this sufficiently
