### ISSUE TITLE
Additions to collections for insert/update/ remove (List, Map etc.)

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#1047]
RFC here: https://github.com/fsharp/fslang-design/blob/main/preview/FS-1113-insert-remove-update-functions.md

1. Add functions to List, Array, Seq, Map to improve them as workhorse functional collections
2. Add `Keys` property to Map
3. Add members to List, Map, Set to align their design more with the patterns used by ImmutableCollections.

I propose we add the following:
Here's what I've concluded:

```fsharp
module List =
    /// Return a new list with the item at a given index removed
    /// If the index is outside the range of the list then it is ignored.
    val removeAt: index: int -> source: 'T list -> 'T list

    /// Return a new list with the number of items starting at a given index removed.
    /// If index is outside 0..source.Length-1 then it is ignored.
    val removeManyAt: index: int -> count: int -> source: 'T list -> 'T list

    /// Return a new list with the item at a given index set to the new value. If 
    /// index is outside 0..source.Length-1 an exception is raised.
    val updateAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Return a new list with a new item inserted before the given index.The index may be source.Length to
    /// include extra elements at the end of the list. If 
    /// index is outside 0..source.Length an exception is raised.
    val insertAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Return a new list with new items inserted before the given index. The index may be source.Length to
    /// include extra elements at the end of the list. 
    /// If index is outside 0..source.Length  an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T list -> 'T list

module Array =
    /// Return a new array with the item at a given index removed
    /// If the index is outside the range of the array then it is ignored.
    val removeAt: index: int -> source: 'T[] -> 'T[]

    /// Return a new array with the number of items starting at a given index removed.
    /// If an implied item index is outside the range of the array then it is ignored.
    val removeManyAt: index: int -> count: int -> source: 'T[] -> 'T[]

    /// Return a new array with the item at a given index set to the new value. If 
    /// index is outside 0..source.Length-1 an exception is raised.
    val updateAt: index: int -> value: 'T -> source: 'T[] -> 'T[]

    /// Return a new array with a new item inserted before the given index. The index may be source.Length to
    /// include extra elements at the end of the array. If 
    /// index is outside 0..source.Length than source.Length an exception is raised.
    val insertAt: index: int -> value: 'T -> source: 'T[] -> 'T[]

    /// Return a new array with new items inserted before the given index. The index may be source.Length to
    /// include extra elements at the end of the array.   If index is outside 0..source.Length an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T[] -> 'T[]

module Seq =
    /// Return a new ssequence which, when iterated, will have the item at a given index removed
    /// If the index is outside the range of valid indexes for the sequence then it is ignored.
    val removeAt: index: int -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will have the given count of items starting at a given index removed.
    /// If any implied item index is outside the range of valid indexes for the sequence then it is ignored.
    val removeManyAt: index: int -> count: int -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will return the given item for the given index, and
    /// otherwise return the items from source. If index is below zero an exception is raised immediately.
    /// If the index is beyond the range on the source sequence the update is ignored.
    val updateAt: index: int -> value: 'T -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, includes a new item inserted before the given index. The index may be source.Length to
    /// include extra elements at the end of the sequence. If 
    /// index is outside 0..source.Length than source.Length an exception is raised.
    val insertAt: index: int -> value: 'T -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will include additional items given by values, starting
    /// at the given index. The index may be source.Length to
    /// include extra elements at the end of the sequence. 
    /// If index is outside 0..source.Length an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: seq<'T> -> seq<'T>
```

I changed to use `ManyAt` etc. since `Range` should best be reserved to take Range type. In retrospect I think `mapAt` and `mapManyAt` are overkill for this PR, they don't make the cut for FSharp.Core.  We'd have to ask "why not `collectAt`, `filterAt`, `chooseAt` etc., I've no good answer. I will mark this as approved with `mapAt` and `mapManyAt` removed

- Note that for Seq the operations potentially involve managing state as the sequence
unfolds to remap indexes appropriately.  

- Note that for Array the operations would not mutate, they would be treating Array as a functional collection.

For Map we have some choices since there are existing functions that do the above. 
We could consider including functions with the right names for consistency, however `insertItem` makes no sense
```fsharp
    /// Same as map.Add
    /// Set an item at a given index. 
    val setItem: key: 'Key -> value: 'Value -> source: source: Map<'Key, ;Value> -> Map<'Key, ;Value>

    /// Remove an item at a given index
    val removeItem: key: 'Key -> source: Map<'Key, ;Value> -> Map<'Key, ;Value>

    /// Modify the item at the given index. 
    val mapItem: key: 'Key -> modifier: ('Value -> 'Value)  -> source: Map<'Key, ;Value> -> Map<'Key, ;Value>
```
For Map we should also add:
```fsharp
    val keys: source: Map<'Key, ;Value> -> ICollection<'Key>

    type Map<'Key, ;Value> with
        member Keys: ICollection<'Key>
```

Separately we should also consider adding members to align the design with with ImmutableDictionary as much as possible. THis could be a separate RFC.

The existing way of approaching this problem in F# is adding the above as post-hoc extensions.

## Pros and Cons 

The advantages of making this adjustment to F# are it makes programming with functional collections simpler

The disadvantages of making this adjustment to F# are more things in FSharp.Core.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by gusty** [comment]
I think for functions taking an index as parameter we can use the `At` suffix instead of `Item`, actually `insertItem` is normally called `AddAt`.

Also `mapItem` is a bit unusual in this set of functions, to be consistent with the other names it should be called `update` instead of `map`. So I suggest `updateAt`.

**Comment by Happypig375** [comment]
I'd like range versions too! Currently I can mutate arrays with ranges
```fs
let a = [|0..9|]
a.[7..^1] <- [|8; 7|]
a // [|0; 1; 2; 3; 4; 5; 6; 8; 7; 9|]
```
And I'd like to see immutable analogies.

**Comment by charlesroddie** [comment]
> for Array the operations would not mutate

The naming doesn't match this.
`removeItem`, `setItem`, `insertItem` convey mutation.
`withoutItem`, `withReplacedItem`, `withExtraItem` would be more accurate.

With these names the only thing that suggets non-mutation is that they would return objects of the same type rather than `unit`, but in .Net some methods mutate an object and then return it unfortunately, so the signature doesn't convey information.

**Comment by dsyme** [comment]
> The naming doesn't match this. removeItem, setItem, insertItem convey mutation.

It's tricky.  I mean "append" implies mutation.  We've always really relied on the return of an array or unit to indicate mutation or not.

> I think for functions taking an index as parameter we can use the At suffix instead of Item, actually insertItem is normally called AddAt.

I did think about this (and we do use At in `List.splitAt`).  In ImmutableCollections the indexed setter instance method is uniformly called SetItem.  And `item` is already there in FSharp.Core as the indexed getter 

That said I do like

```
    /// Remove an item at a given index
    val removeAt: index: int -> source: 'T list -> 'T list

    /// Remove the given number of items at a given index
    val removeRange: index: int -> count: int -> source: 'T list -> 'T list

    /// Set an item at a given index. The index may also be -1 or source.Length to increase the size of the list
    val setAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Set the items starting at a given index. The index may also be -1 or source.Length to increase the size of the list
    val setRange: index: int -> values:seq< 'T> -> source: 'T list -> 'T list

    /// Insert an item before the given index. The index may be 0 or source.Length 
    val insertAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Insert items before the given index. The index may be 0 or source.Length 
    val insertRange: index: int -> values: seq<'T> -> source: 'T list -> 'T list

    /// Modify the item at the given index. 
    val mapAt: index: int -> modifier: ('T -> 'T)  -> source: 'T list -> 'T list

    /// Modify the item at the given index. 
    val mapRange: start: int -> count: int -> modifier: ('T -> 'T)  -> source: 'T list -> 'T list
```

> Also mapItem is a bit unusual in this set of functions, to be consistent with the other names it should be called update instead of map. So I suggest updateAt.

Not so sure about this.  `updateAt` would imply `setAt` to me.  Any particular reason to not use `mapAt` and `mapRange`?  They seem to do what's on the tin.  Is it because it's `'T -> 'T`?

**Comment by Happypig375** [comment]
Is it possible to incorporate #1044 so I can write `[|0..9|] |> Array.setRange (2..^1) [|2; 3; 4|]`?

**Comment by uxsoft** [comment]
I love this, lack of these basic functions was a major inconvenience for me

**Comment by gusty** [comment]
> Not so sure about this. updateAt would imply setAt to me. Any particular reason to not use mapAt and mapRange? They seem to do what's on the tin. Is it because it's 'T -> 'T?

Not really, maybe I'm influenced by lens terminology where `set` takes the item as parameter and `update` a mapping function.

**Comment by dsyme** [comment]
> Is it possible to incorporate #1044 so I can write [|0..9|] |> Array.setRange (2..^1) [|2; 3; 4|]?

It's separate, this is not a goal of this PR.  But we should consider the ramification of multiple representation of ranges (start+length, Range) w.r.t. to the fact that these are module-defined functions that can't be overloaded

**Comment by dsyme** [comment]
It's possible we should use `removeManyAt` and so on, since `Range` should perhaps be reserved to take Range type.

```fsharp
    /// Remove an item at a given index
    val removeAt: index: int -> source: 'T list -> 'T list

    /// Remove the given number of items at a given index
    val removeManyAt: index: int -> count: int -> source: 'T list -> 'T list

    /// Set an item at a given index. The index may also be -1 or source.Length to increase the size of the list
    val setAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Set the items starting at a given index. The index may also be -1 or source.Length to increase the size of the list
    val setManyAt: index: int -> values:seq< 'T> -> source: 'T list -> 'T list

    /// Insert an item before the given index. The index may be 0 or source.Length 
    val insertAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Insert items before the given index. The index may be 0 or source.Length 
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T list -> 'T list

```

I guess we'd have to ask "why not `collectAt`, `filterAt`, `chooseAt` etc., I've no good answer except I've never needed them.  This mapes me think `mapAt` and `mapManyAt` are overkill for this PR, they don't make the cut for FSharp.Core. 

I will mark this as approved with `mapAt` and `mapManyAt` removed

**Comment by Happypig375** [comment]
What about `Array2D`, `Array3D`, `Array4D`?

**Comment by dsyme** [comment]
> What about Array2D, Array3D, Array4D?

No, they don't even have most other collection functions (collect etc.)

**Comment by Happypig375** [comment]
But they won't be added?

**Comment by dsyme** [comment]
> But they won't be added?

No

**Comment by charlesroddie** [comment]
> It's tricky. I mean "append" implies mutation. We've always really relied on the return of an array or unit to indicate mutation or not.

Of the words here, `set` (as a verb) seems extremely suggestive of mutation, not far off `mutate`! Is there any precedent for `set` for something that isn't mutable in a F# or any functional language? F# has `with` in the context of records so that is why I thought `with` is better.

**Comment by Kavignon** [comment]
Which collection(s) have already been reserved by dedicated people for the implementation? Also, where can we find the implementation details so that we can implement something similar for F#? Finally, what sort of performance testing do you wish to find in the PRs and how extensive should those benchmarks be? @dsyme

**Comment by dsyme** [comment]
> Of the words here, set (as a verb) seems extremely suggestive of mutation, not far off mutate! Is there any precedent for set for something that isn't mutable in a F# or any functional language? 

Yes, you are correct.  I think `with` has too many meanings in FSharp.Core to be right.  Maybe `updateAt` instead of `setAt`?

```fsharp
module List =
    /// Return a new list with the item at a given index removed
    /// If the index is outside the range of the list then it is ignored.
    val removeAt: index: int -> source: 'T list -> 'T list

    /// Return a new list with the number of items starting at a given index removed.
    /// If an implied item index is outside the range of the list then it is ignored.
    val removeManyAt: index: int -> count: int -> source: 'T list -> 'T list

    /// Return a new list with the item at a given index set to the new value. The index may also be -1 or source.Length to return a new list with increased size. If 
    /// index is below -1 or greater than source.Length an exception is raised.
    val updateAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Return a new list with the items starting at a given index set to the new values. The index may also be -count or source.Length to return a new list with increased size, where count is the number of elements
    /// in values. If index is below -count or greater than source.Length an exception is raised.
    val updateManyAt: index: int -> values:seq< 'T> -> source: 'T list -> 'T list

    /// Return a new list with a new item inserted before the given index. The index may be 0 or source.Length to
    /// return a new list with increased size.   If 
    /// index is below 0 or greater than source.Length an exception is raised.
    val insertAt: index: int -> value: 'T -> source: 'T list -> 'T list

    /// Return a new list with new items inserted before the given index. The index may be 0 or source.Length to
    /// return a new list with increased size.   If index is below 0 or greater
    /// than source.Length an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T list -> 'T list

module Array =
    /// Return a new array with the item at a given index removed
    /// If the index is outside the range of the array then it is ignored.
    val removeAt: index: int -> source: 'T[] -> 'T[]

    /// Return a new array with the number of items starting at a given index removed.
    /// If an implied item index is outside the range of the array then it is ignored.
    val removeManyAt: index: int -> count: int -> source: 'T[] -> 'T[]

    /// Return a new array with the item at a given index set to the new value. The index may also be -1 or source.Length to return a new array with increased size. If 
    /// index is below -1 or greater than source.Length an exception is raised.
    val updateAt: index: int -> value: 'T -> source: 'T[] -> 'T[]

    /// Return a new array with the items starting at a given index set to the new values. The index may also be -count or source.Length to return a new array with increased size, where count is the number of elements
    /// in values. If index is below -count or greater than source.Length an exception is raised.
    val updateManyAt: index: int -> values:seq< 'T> -> source: 'T[] -> 'T[]

    /// Return a new array with a new item inserted before the given index. The index may be 0 or source.Length to
    /// return a new array with increased size.   If 
    /// index is below 0 or greater than source.Length an exception is raised.
    val insertAt: index: int -> value: 'T -> source: 'T[] -> 'T[]

    /// Return a new array with new items inserted before the given index. The index may be 0 or source.Length to
    /// return a new list with increased size.   If index is below 0 or greater
    /// than source.Length an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T[] -> 'T[]

module Seq =
    /// Return a new ssequence which, when iterated, will have the item at a given index removed
    /// If the index is outside the range of valid indexes for the sequence then it is ignored.
    val removeAt: index: int -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will have the given count of items starting at a given index removed.
    /// If any implied item index is outside the range of valid indexes for the sequence then it is ignored.
    val removeManyAt: index: int -> count: int -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will return the given item for the given index, and otherwise return the items from source. The index may also be -1 or source.Length to return a new sequence with increased size. If 
    /// index is below -1 or greater than source.Length an exception is raised.
    val updateAt: index: int -> value: 'T -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will return the given items for count items starting at the index.  The index may also be -count or the length of source to return a new sequence with increased size, where count is the number of elements
    /// in values. If index is below -count or greater than source.Length an exception is raised.
    val updateManyAt: index: int -> values:seq< 'T> -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will include an additional item at the given index. The index may be 0 or the length of source to
    /// return a new sequence with increased size.   If 
    /// index is below 0 or greater than the length of source an exception is raised.
    val insertAt: index: int -> value: 'T -> source: seq<'T> -> seq<'T>

    /// Return a new sequence which, when iterated, will include additional items given by values, starting at the given index. The index may be 0 or source.Length to
    /// return a new list with increased size.   If index is below 0, or greater
    /// than the length of source, then an exception is raised.
    val insertManyAt: index: int -> values: seq<'T> -> source: seq<'T> -> seq<'T>
```

**Comment by dsyme** [comment]
> Which collection(s) have already been reserved by dedicated people for the implementation? 

None so far!  Feel free to start a PR to dotnet/fsharp with even just basic implementations, and some testing, and we can jointly iterate.

> Also, where can we find the implementation details so that we can implement something similar for F#? 

I think everything you need is in list.fs, seq.fs and array.fs


> Finally, what sort of performance testing do you wish to find in the PRs and how extensive should those benchmarks be? 

Add to `tests/benchmarkfs/MicroPerf` and we can iterate. 2-3 benchmarks per function seem appropriate (tiny collection, start of large collection, near end of large collection) though perhaps more for the ones that have slightly different modalities

**Comment by isaacabraham** [comment]
At the risk of further bike shedding: insert of `setAt` etc., what about `replaceAt` ?

**Comment by uxsoft** [comment]
I started looking into this to see if it's something I can do (https://github.com/uxsoft/fsharp/tree/feature/additions-to-immutable-collections) and I have a few questions:

- updateManyAt: "The index may also be -count or source.Length to return a new array with increased size, where the count is the number of elements in values."
    - I'd be interested in understanding some examples where this is the desired behavior. Also, the function is called updateManyAt but it can also insert. Would it make sense to have two functions, one updateManyAt strictly only updates, and upsertManyAt which can update or insert?
 - Personally, I never updated immutable collections based on the index, more often the case is for me that I'm searching for an item with Id. Would be worth to add an overload which takes a predicate? For example List.update (fun i -> i.Id = id) value?
 - Another possibly useful overload related to the above scenario could be elmish/react inspired. When updating, sometimes it's useful to have a function instead of value. For example: List.update (fun i -> i.Id = id) (fun prevState -> { prevState with Value = newValue }

What do you think?

**Comment by charlesroddie** [comment]
> Would you want to be able to set at -1 and source.Length?

Regardless of whether it's `updateAt` or `replaceAt`, it shouldn't have behaviour where it changes the length for two magic numbers and keeps it the same for others. You may be thinking of a sequence as consecutive `Some`s in an infinite sequence of `'T options` indexed by the integers Z, but 1. that's not a conventional approach to sequences and I would guess an example where it is useful would be quirky and hard to find, 2. it would require very different apis, where `updateAt` takes a `'T option` and whether it is Some or None can be toggled at both ends, and where the sequences are indexed and not zero-based.

**Comment by IltaySaeedi** [comment]
> Personally, I never updated immutable collections based on the index, more often the case is for me that I'm searching for an item with Id. Would be worth to add an overload which takes a predicate? For example List.update (fun i -> i.Id = id) value?

If id of items in the list is not unique this overload may update all items with same id.
I create a gist to demonstrate this situation

https://gist.github.com/IltaySaeedi/79db593976c2953a5bd1a728d6ca078c

**Comment by uxsoft** [comment]
You're right, but I'm not sure I get your point. The user passes in the predicate and how the function works is very transparent. We can make it very clear in the documentation that it updates all the values where the predicate is true.

**Comment by IltaySaeedi** [comment]
I wanted to show a situation that I cannot trust to updateManyAt with predict function because I should always be aware of input that I pass unlike other two functions that always gave me the right answer.

I am not expert and that was an example maybe updateManyAt with predict function is necessary and it is not good in my case.

**Comment by Happypig375** [comment]
@uxsoft Your `List.update` with a predicate is just a `List.map` with an `if`.

**Comment by dsyme** [comment]
@uxsoft's PR is here: https://github.com/dotnet/fsharp/pull/11888

**Comment by dsyme** [comment]
@charlesroddie argues against the suggested behaviour of setAt etc. for -1 and collection.Length

I checked System.Collections.Immutable and @charlesroddie is correct - there is no special case for these to enlarge the collection.  SO we shuold do the same.  I'll adjust the spec up above
```
#r "nuget: System.Collections.Immutable"

open System.Collections.Immutable

let v = ImmutableArray.Create(1,2)

v.SetItem(2,4)
// gives System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
```

**Comment by dsyme** [comment]
> Personally, I never updated immutable collections based on the index, more often the case is for me that I'm searching for an item with Id. Would be worth to add an overload which takes a predicate? For example `List.update (fun i -> i.Id = id)` value?

I guess a logical naming is as follows, however `removeBy` is `filter >> not` and `updateBy` is very close to `List.pick (fun x -> if ... then Some newValue else None)` and `insertBy` is a little unusual and unlikely to be used.

It feels like a findIndex follows by updateAt/removeAt/insertAt is adequate?

```fsharp
module List =
    val removeBy: comparer ('T -> bool) -> source: 'T list -> 'T list

    val updateBy: comparer:('T -> bool) -> value: 'T -> source: 'T list -> 'T list

    val insertBy: comparer: ('T -> bool) -> value: 'T -> source: 'T list -> 'T list
```

**Comment by dsyme** [comment]
> When updating, sometimes it's useful to have a function instead of value. For example: List.update (fun i -> i.Id = id) (fun prevState -> { prevState with Value = newValue }

Use this was in the original suggest, e.g.
```
module List =

    val mapAt: index: int -> updater:('T -> 'T) -> source: 'T list -> 'T list
```
or
```
module List =

    val updateWith: selector: ('T -> bool) -> updater:('T -> 'T) -> source: 'T list -> 'T list
```
or
```
module List =

    val updateWith: updater:('T -> 'T option) -> source: 'T list -> 'T list
```

However these are generally either identical or simple combinations of existing functions like `List.choose` and don't feel that compelling to me?

**Comment by dsyme** [comment]
I'd like to get a read on the `insertMany` etc.  Are they worth it?  All of them?  Please vote thumbs-up/thumbs-down

**Comment by Swoorup** [comment]
Thoughts on adding functions of `ListSet` such as subtract? I have found them to be handy
https://github.com/dotnet/fsharp/blob/8a62ed9c3d/src/fsharp/lib.fs#L150-L180

**Comment by uxsoft** [comment]
@dsyme I looked at adding the map functions but it seems to me like they already exist

val setItem: key: 'Key -> value: 'Value -> source: source: Map<'Key, ;Value> -> Map<'Key, ;Value>
There is already Map.add

/// Remove an item at a given index
val removeItem: key: 'Key -> source: Map<'Key, ;Value> -> Map<'Key, ;Value>
There is already Map.remove

/// Modify the item at the given index. 
val mapItem: key: 'Key -> modifier: ('Value -> 'Value)  -> source: Map<'Key, ;Value> -> Map<'Key, ;Value>
There is already Map.Change which is slightly different. The modifier is Option<'Value> -> Option<'Value>

**Comment by dsyme** [comment]
> @dsyme I looked at adding the map functions but it seems to me like they already exist

Yes, that's reasonable.

> There is already Map.change which is slightly different. 

I'd actually forgotten this precedent, which didn't get an RFC and just a suggestion

* Implementation: https://github.com/dotnet/fsharp/pull/6876
* Suggestion: https://github.com/fsharp/fslang-suggestions/issues/742

**Comment by dsyme** [comment]
This RFC proposes `List.removeAt`, `List.updateAt`, `List.insertAt` which are non-controversial.  It also proposes `List.insertManyAt`, `List.removeManyAt`, `List.updateManyAt`

Please vote on the inclusion of the ManyAt functions in FSharp.Core:
* 👎 for none
* 👍 for all `List.insertManyAt`, `List.removeManyAt`, `List.updateManyAt`
* 😄 for just `List.insertManyAt` and `List.removeManyAt` (but not `List.updateManyAt`)
* 🎉  for just `List.insertManyAt` (but not `List.removeManyAt` or `List.updateManyAt`)

```fsharp
    val insertManyAt: index: int -> values: seq<'T> -> source: 'T list -> 'T list

    val removeManyAt: index: int -> count: int -> source: 'T list -> 'T list

    val updateManyAt: index: int -> values:seq< 'T> -> source: 'T list -> 'T list
```

(re-running this vote with more options than earlier)

**Comment by dsyme** [comment]
Regarding these:

> Should `Map.keys` return `ICollection<'Key>` or `'Key seq`?

This is tricky.  

* Ideally `Keys` should support .Contains in `O(log(n))` time without copying the collection
* However .NET `ImmutableSortedDictionary<'Key,'Value>` has a `Keys` property that returns `IEnumerable<'Key>` so there is precedent
* .NET 5.0 has a [`IReadOnlySet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlyset-1?view=net-5.0) but we can't use that at .NET Standard 2.0 dependency level
* The current `Map` implementation contains two cases where it can possibly be improved to avoid copying, though no solution is perfect here

```fsharp
        // REVIEW: this implementation could avoid copying the Values to an array 
        member m.Keys = ([| for kvp in m -> kvp.Key |] :> ICollection<'Key>)

        // REVIEW: this implementation could avoid copying the Values to an array 
        member m.Values = ([| for kvp in m -> kvp.Value |] :> ICollection<'Value>)
```

Given this, I suppose `IEnumerable<'Key>` (that is `seq<'Key>`) is appropriate but I feel very uneasy about it.  `table.Keys.Contains(3)` being waaaay slower than `table.ContainsKey(3)` is just such a coding trap.

> If we're adding `Keys` for map, what about `Values`?

Yes, this should be added with type `seq<'Value>`.  However given the above it's possible Keys and Values should be done separately to the other updates.

**Comment by NinoFloris** [comment]
>Given this, I suppose IEnumerable<'Key> (that is seq<'Key>) is appropriate but I feel very uneasy about it. table.Keys.Contains(3) being waaaay slower than table.ContainsKey(3) is just such a coding trap.

As long as you follow the types it makes sense, seq from .Keys is O(n) for contains (leaving manual or jit specialization out of it) so I wouldn't have a hard time explaining this mistake to a beginner.

**Comment by baronfel** [comment]
> .NET 5.0 has a IReadOnlySet<T> but we can't use that at .NET Standard 2.0 dependency level

There is a .Net Standard 2.1 version of FSharp.Core now, so should this be taken into consideration?

**Comment by dsyme** [comment]
> There is a .Net Standard 2.1 version of FSharp.Core now, so should this be taken into consideration?

Yes, though IReadOnlySet isn't in that.  Also strictly speaking Keys could return an IReadOnlySortedSet.... which doesn't exist anywhere....

**Comment by uxsoft** [comment]
> Regarding these:
> 
> > Should `Map.keys` return `ICollection<'Key>` or `'Key seq`?
> 
> This is tricky.
> 
> * Ideally `Keys` should support .Contains in `O(log(n))` time without copying the collection
> * However .NET `ImmutableSortedDictionary<'Key,'Value>` has a `Keys` property that returns `IEnumerable<'Key>` so there is precedent
> * .NET 5.0 has a [`IReadOnlySet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlyset-1?view=net-5.0) but we can't use that at .NET Standard 2.0 dependency level
> * The current `Map` implementation contains two cases where it can possibly be improved to avoid copying, though no solution is perfect here
> 
> ```fsharp
>         // REVIEW: this implementation could avoid copying the Values to an array 
>         member m.Keys = ([| for kvp in m -> kvp.Key |] :> ICollection<'Key>)
> 
>         // REVIEW: this implementation could avoid copying the Values to an array 
>         member m.Values = ([| for kvp in m -> kvp.Value |] :> ICollection<'Value>)
> ```
> 
> Given this, I suppose `IEnumerable<'Key>` (that is `seq<'Key>`) is appropriate but I feel very uneasy about it. `table.Keys.Contains(3)` being waaaay slower than `table.ContainsKey(3)` is just such a coding trap.
> 
> > If we're adding `Keys` for map, what about `Values`?
> 
> Yes, this should be added with type `seq<'Value>`. However given the above it's possible Keys and Values should be done separately to the other updates.

Looking at the Dictionary<T>, it returns an ICollection<T>, but instead of copying they solve this by having a custom ICollection<T> implementation where it just refers to the parent dictionary.

What if I'd do it the same way? 

One benefit I see is that it would also simplify the interface implementations of map because they'd be the same type

**Comment by dsyme** [comment]
> Looking at the Dictionary, it returns an ICollection, but instead of copying they solve this by having a custom ICollection implementation (KeyCollection) where it just refers to the parent dictionary. What if I'd do it the same way?

Yes returning an `ICollection<'Key>` seems reasonable to me (though not a new KeyCollection type except internally). It's not ideal but at least gives constant time membership test without copying.

Note there's an ICollection implementation in `src\fsharp\FSharp.Core\fslib-extra-pervasives.fs`

> One benefit I see is that it would also simplify the interface implementations of map because they'd be the same type

Yes, so Map's `IDictionary<Key,Value>.Keys` returns this same thing

**Comment by uxsoft** [comment]
@dsyme I just added the Keys and Values ICollection implementation, these are my open questions:

-  Do you want me to add the Map.setItem, removeItem, mapItem even though they are basically just one-line shortcuts to already existing methods? 
- Do you still want me to come up with the benchmarks?
- Final decision on the manyAt function removal

**Comment by JordanMarr** [comment]
I was really hoping to see the following `Map` helpers in this list of new helpers:

* `Map.ofListBy`
* `Map.ofArrayBy`
* `Map.ofSeqBy`

Creating a map usually requires two steps: 1) mapping to a `'Key,'Value` tuple and 2) calling `Map.ofList`:

```F#
type Person = { Id: int; Name: string }
let people = 
        [ { Id = 1; Name = "Person1" }
          { Id = 2; Name = "Person2" }
          { Id = 3; Name = "Person3" } ]

let personLookup = 
        people
        |> List.map (fun p -> p.Id, p)
        |> Map.ofList
```

Proposed change with `Map.ofListBy` would be a one-liner (similar to existing C# `ToDictionary(p => p.Id)` overload):

```F#
let personLookup = people |> Map.ofListBy (fun p -> p.Id)
```

I think this is common enough to warrant the additional functions.

**Comment by dsyme** [comment]
> Do you want me to add the Map.setItem, removeItem, mapItem even though they are basically just one-line shortcuts to already existing methods?

No

> Do you still want me to come up with the benchmarks?

Yes, we need them, though you can ask someone else to help provide them

> Final decision on the manyAt function removal

Include `insertManyAt` and `removeManyAt` but remove `updateManyAt`

Thanks!

**Comment by dsyme** [comment]
> I was really hoping to see the following Map helpers in this list of new helpers:

These are reasonable, though perhaps could be a single `Map.createBy` or `Map.initBy` (taking an IEnumerable). Multiplying out the functions doesn't seem quite right.

**Comment by dsyme** [comment]
RFC is here: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1113-insert-remove-update-functions.md
