### ISSUE TITLE
Field update syntax for Records  

### ISSUE THREAD

**Issue by thinkbeforecoding** [fsharp/fslang-suggestions#1049]
# Field update syntax for record

I propose we implement an update syntax for records. We can update records using the { x with .. } syntax, but it is quickly quite verbose.
I propose the following syntax:
```
type Average =
    { Total: int
      Count: int }

let add value avg =
   { avg with
        Total t = t + value
        Count c = c + 1 }
```
This is especially convenient when dealing with nested records and the RFC https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1049-nested-record-field--copy-and-update-expression.md :
```
{ x with FirstLevel.SecondLevel.ThridLevel value = value + 1 }
vs
{ x with FirstLevel.SecondLevel.ThridLevel = x.FirstLevel.SecondLevel.ThridLevel + 1 }
```

The existing way of approaching this problem in F# is to access the field from the input object:

```
type Average =
    { Total: int
      Count: int }

let add value avg =
   { avg with
        Total = avg.Total + value
        Count = avg.Count + 1 }
```

## Pros and Cons 

The advantages of making this adjustment to F# are simpler code for immutable constructs.. reduce the temptation to use lenses 😁

The disadvantages of making this adjustment to F# are a new syntax, added complexity in the compiler

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: 
 https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1049-nested-record-field--copy-and-update-expression.md

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by thinkbeforecoding** [comment]
An alternative could be:
```
{ x with Field as f = f+1 }
```

Of course for short fields name, the advantage is small, but for long Domain related field names, its quickly a win.

**Comment by pblasucci** [comment]
I actually like the `as binding` version a bit better... but in either case, would you imagine all the regular decomposition goodness being allowed as part of the binding?

**Comment by thinkbeforecoding** [comment]
That would be neat. Like if it's a tuple:
```
{ x with Field (t, u) = t+1,u-1}
```

And it could even be partial (to make it simpler than suggestion with yields) :
```
{ x with OptionalField (Some v) = Some (v+1)} 
```

Property keeps same value if it doesn't match.
```
{ x with List (_ :: tail) = tail}
```

Just keeps empty list as is.

**Comment by Happypig375** [comment]
Treating it as a nested pattern, interesting

**Comment by thinkbeforecoding** [comment]
The general pattern would be:
```
{ x with Field matchExpr = expr}
```
Translated to:
```
{ x with Field =
        match x.Field with
        | matchExpr -> expr
        | _ -> x.Field}
```
When matchExpr is total, the _ clause is dead code and can be discarded.


And, in a way, the classic syntax would be equivalent to:

```
{ x with Field _ = expr}
```

**Comment by pblasucci** [comment]
The longer I look at this, the more I think it's a very worthwhile bit of sugar. :100:

**Comment by Alkasai** [comment]
It can also play nicely with my suggestion on conditional updates https://github.com/fsharp/fslang-suggestions/issues/1016

**Comment by thinkbeforecoding** [comment]
Yes, I think the syntax here is close to what already exists.
If we implement it using a true match clause we could even use guards:
```
{ x with Field v when v > 0 = v-1 }
```

**Comment by thinkbeforecoding** [comment]
> I actually like the `as binding` version a bit better... but in either case, would you imagine all the regular decomposition goodness being allowed as part of the binding? 

The  version with 'as' is nice also but a bit longer. 
However, it would fit with the #1025 suggestion in a way...

**Comment by Happypig375** [comment]
@thinkbeforecoding The `as` is only needed for type tests. Here we match on a property, akin to DUs or active patterns.

**Comment by thinkbeforecoding** [comment]
Yes, and an extra keyword is not necessary since there is no ambiguity.

**Comment by krauthaufen** [comment]
Thinking about beginners I think the `as` version is way less alienating and overall clearer, since it sort of tells you what's happening without the need to look it up somewhere...
Generally speaking I like the idea and I've been annoyed by this countless times but nonetheless I think things like this (implicit yields, auto-nullable conversions, implicit conversions for literals, etc.) make an otherwise super-simple language really hard to explain.
I guess I'm just saying simplicity (to me) is/was one of F#'s core benefits over languages like C# where feature-creep nowadays makes it really hard to read programs due to tons of special-cases and custom syntax for lots of things.

**Comment by thinkbeforecoding** [comment]
Yes the idea is to just bind a name to the value. So that it is not a special syntax, in f#, you can already write things like
```
let (Some v) = x
let (a, b) = y
```
And
```
let a = x
```
is just a special case of it, catch-all matching with a name.

So there is no irregularity here, just the possibility to bind the value of the field to use it in the expression.

**Comment by krauthaufen** [comment]
I see your point but consider someone in the future being annoyed by `{ Field = fun a b -> ... }` who would likely come up with something very similar. I understand that this is sound and will totally be a cool feature for F# nerds that follow discussions like this one.
I'm just saying this syntax (without as at least) does not make it explicit that this is a pattern-context and it raises F#'s entry barrier another bit.

**Comment by charlesroddie** [comment]
The stated advantage is "simpler code for immutable constructs". Actually "shorter, but more complex and obfuscated" is more accurate. Take the snippets posted:

```fsharp
let add value avg =
   { avg with
        Total = avg.Total + value
        Count = avg.Count + 1 }

let add value avg =
   { avg with
        Total t = t + value
        Count c = c + 1 }
```

In both cases you have `avg` so you need to understand that. The first snippet defines the new total `Total =` as `avg.Total + value`. This is extremely simple.

The second snippet has syntax **`Total t = ` where `Total` is describing the new total and `t` is the binding for the old total**. This is extremely confusing and irregular. `= f(t)` again refers to the new total.

In general the there is no need for syntactic sugar for expressions of the type `x.Prop <- f(x.Prop)` since "saving writing Prop twice" is not a significant benefit. And syntax like `x.Prop oldValue <- f(oldValue)` would be a terrible alternative.

**Comment by krauthaufen** [comment]
Another idea could be generating  lenses for record types in fsc with get/set/update functionality.

We would even have a syntax for these, since `MyRecord.Field` is not valid outside of record constructions at the moment we coul just use it for accessing the lenses like

```fsharp
old
|> MyRecord.Field .= newValue
|> MyRecord.Other.Update(fun a -> a + 1)
```

What do you think? (Details to be worked out)

**Comment by dsyme** [comment]
For context, lenses suggestion was here  #379 

@charlesroddie How do you feel about the `as` version?  It seems more reasonable?

```
let add value avg =
   { avg with
        Total = avg.Total + value
        Count = avg.Count + 1 }

let add value avg =
   { avg with
        Total as t = t + value
        Count as c = c + 1 }
```

**Comment by thinkbeforecoding** [comment]
As proposed before, using 'as' this could be a pattern on the right, like already possible in match since last version.

**Comment by charlesroddie** [comment]
> For context, lenses suggestion was here  #379 
> 
> @charlesroddie How do you feel about the `as` version?  It seems more reasonable?
> 
> ```
> let add value avg =
>    { avg with
>         Total = avg.Total + value
>         Count = avg.Count + 1 }
> 
> let add value avg =
>    { avg with
>         Total as t = t + value
>         Count as c = c + 1 }
> ```
> 

Addition of `as` doesn't make a substantive difference. In each case `t` binds to `Total`. In each case there is an illogical equation t=t+value. I suspect a reason some people like this request is the failure to disambiguate old and new. If you write `oldTotal` instead of `t` as a clarification it's clear that this update syntax doesn't make sense.

A more logical syntax (which I still don't support as it's not needed) would be `with t+value replacing Total t`.

**Comment by krauthaufen** [comment]
Overall wouldn't it just be cleaner to have some syntax for applying functions to record fields? 

`{ avg with Total °= fun v -> v+1 }`

**Comment by zanaptak** [comment]
Possible to consider new keyword to emphasize the binding is not representing the actual updated property?
```
Total was t = t + value
Total previously t = t + value
```

**Comment by Happypig375** [comment]
```fs
    { avg with
        Total t <- t + value
        Count c <- c + 1 }
```
If we use the assignment operator `<-`, everything becomes clear.

**Comment by kerams** [comment]
> In general the there is no need for syntactic sugar for expressions of the type x.Prop <- f(x.Prop) since "saving writing Prop twice" is not a significant benefit.

The main benefit I see here is that you wouldn't get a chance to reference a different field (of the same type) on the right hand side by accident. Copying update lines and then manually changing field names is especially prone to this, but you could make the same mistake while typing out the update as usual - `Count = avg.Total + 1`.

**Comment by thinkbeforecoding** [comment]
@kerams , the idea is not only to avoid typos, but to enable deconstruction:
```
{ x with Point (x,y) -> (x+1, y+1) }  
```
for instance using @Tarmil suggestion.

**Comment by Happypig375** [comment]
@kerams We could also allow that, but creates two ways of doing to same thing.

**Comment by Happypig375** [comment]
`with` indicates immutability.

**Comment by dsyme** [comment]
I've taken a look at this and discussed with @vzarytovskii and will close this as something we're not going to do.

The feature doesn't occur in other languages with record syntax, and the specific choice to allow naming of the `x.F` field of the record is just one of many things you might want to name.  Also it will interact badly with other suggestions like allowing nested update.
