### ISSUE TITLE
dotnet fsi should have the ability to save script to file

### ISSUE THREAD

**Issue by cnmade** [fsharp/fslang-suggestions#1050]
The dotnet fsi can load script from disk. but no command save the session into a file.

```

#load "file-name.fsx"
```

How about provided us the ability to save pure scripts into a file ,with some like

```
#saveto "file-new-name.fsx"
```

The old file-name.fsx content may like

```f#
let s = 16
```

the new file-new-name.fsx may like

```f#
let s = 16
let it = s * 1024
```

**Comment by dsyme** [comment]
Is there a use case for this feature that doesn't involve the user typing into the REPL Standard Input?

* In F# we prefer the send-to-interactive model, where you start in a script and edit it and use Alt-Enter to execute fragments.

* Alternatively if you want to create a document use .NET Interactive notebooks.

* So we simply don't encourage you to ever type into the REPL Standard Input, and don't want to encourage that

**Comment by cnmade** [comment]
@dsyme Hello, The write to file just like Syntactic sugar， Some times we using REPL to quick diagnose or make a proto , and if we finish some dirty works. how to quick save our workspace code . 

The old way , write code in file, then compile it ,and run , not good as fast as REPL.

REPL is better way some times.
I love F#, and I suggest this because it really can help some one who using F# to make these works.

1. For teach or tutorial purpose.
2. Doing some research 
3. Doing some quick diagnose
4. Make a proto
5. Try something not normal.

Any time, if we want .we can quickly save REPL code into a file on my disk.

**Comment by cnmade** [comment]
What am i talking about. it was nothing new. @dsyme   

http://www.sbcl.org/manual/#Function-sb_002dext-save_002dlisp_002dand_002ddie

It exists here for long long time ago.

**Comment by dsyme** [comment]
Hi @cnmade,  


For all of the above use-cases I'd still recommend open-file-in-VS Code and Alt-Enter.  It's always better as a way to create a document.  

    code foo.fsx

then edit and Alt-Enter?  Isn't it always better for all of the use cases above?  Is that workflow not working for you somehow?

I know the old systems supported this :) And we have discussed it before.  But we always came to the conclusion that editing a real file in a real editor was always better for anything where you're ultimately producing a document.

Thanks!
Don

**Comment by cnmade** [comment]
Ok, fine.
