### ISSUE TITLE
Add Seq.splitBy, Seq.splitAt & Seq.tryHeadTail

### ISSUE THREAD

**Issue by amieres** [fsharp/fslang-suggestions#1059]
# Add Seq.splitBy, Seq.splitAt & Seq.tryHeadTail

I propose we add functions to `Seq` module that allow to split and process sequences without having to rescan or cache the source sequence.

I created my own implementation which can be found here:
https://gist.github.com/amieres/7bbab116211305fd2ea56d2a168865dc
and here: http://fssnip.net/84n

Here is a case where a solution like this is needed:

````
// The following example uses Seq.splitBy and Seq.tryHeadTail 
// twice to split the input file first in 2 and then into several pieces
// collecting the output file names in the first section and the content in the subsequent pieces
// it can split a huge 2.2GB file into several subfiles without having to rescan the file
// or cache in memory any portions of the file apart from the current line

// the first Seq.tryHeadTail operates on a seq<seq<string>>. Because of the nested seq it must use 2
// separate functions to process first the head and then the tail without backtracking,
// the result from the first function is passed to the second:
//     |> Seq.tryHeadTail (fun head -> ...; filelist) (fun filelist tail -> ...)

// the second Seq.tryHeadTail operates on a seq<string>, because it is not nested seqs it can be called simply:
//     |> Seq.tryHeadTail id (fun head tail -> ...)

open System.IO

let splitFile path file =
    File.ReadLines file
    //|> Seq.mapi    (fun i v -> printfn "%d -> %s" i v; v)
    |> Seq.skip 1 
    |> Seq.splitBy    (fun l    -> l.EndsWith "---*/") Seq.SplitByOption.IncludeInSecond
    |> Seq.tryHeadTail(fun head ->
        let filelist = head |> Seq.map (fun s-> s.Split('.') |> Seq.last) |> Seq.toArray
        for file in filelist do printfn "file: %A" file
        printfn "--------"
        filelist
    ) (fun filelist tail ->
        tail
        |> Seq.collect id
        |> Seq.splitBy (fun l -> l.EndsWith " rows affected)" || l = "(1 row affected)") Seq.SplitByOption.IncludeInFirst
        |> Seq.map (Seq.skip 1)
        |> Seq.iteri(fun i s ->
            if i < filelist.Length then
                s 
                |> Seq.tryHeadTail id (fun head tail -> 
                    printfn "%s => %s" filelist.[i] head
                    File.WriteAllLines(path + filelist.[i] + ".rpt", Seq.append [head] tail) 
                )
                |> Option.defaultValue ()
        )
    )
    |> Option.defaultValue ()
````

Notice how this code allows to process the input file as a proper stream, without backtracking or caching.

### Seq.splitBy

This is the signature of `Seq.splitBy`:
````
val splitBy: 
   f    : 'a -> bool        ->
   opt  : Seq.SplitByOption ->
   input: seq<'a>           
       -> seq<seq<'a>>
 Straight scan through is efficient, reusing seqs causes rescan from beginning
Generic parameters
'a is string
````
it has a parameter for handling the "splitting" element (i.e. the element for which the predicate is `true`):
````
type SplitByOption = Exclude | IncludeInFirst | IncludeInSecond
````
This allows the developer to keep and examine the "splitting" element or discard it.
I feel this is missing in other functions like `Seq.takeWhile` where when the condition changes sometimes it is necessary to have the element that stopped the sequence, if any.

### Seq.tryHeadTail
This is the signature of `Seq.tryHeadTail`:
````
val tryHeadTail: 
   fhead: 'a -> 'b            ->
   ftail: 'b -> seq<'a> -> 'c ->
   s    : seq<'a>             
       -> 'c option
Generic parameters
'a is seq<string>
'b is string []
'c is unit
````
It separates processing the head from the tail. This is specially important when doing nested seqs  `seq<seq<'a>>` like the
ones produced by `Seq.splitBy` and `Seq.splitAt`. In order to ensure no backtracking the elements must be processed in order.

## Currently

Currently we have no way to process a large sequence without rescanning or caching elements.
To avoid rescanning the source we can use `Seq.cache` or `Seq.toArray` or `Seq.toList` this allows caching the values in memory. This is not always convenient as some sequences maybe too large to hold in memory.

An alternative to caching is to rescan the data from the source, using `Seq.skip`, `Seq.take`, `Seq.pick`, `Seq.find` and other variants of these functions.
The downside is that reprocessing implied in recalculating the elements in the sequence slows down the execution for large sequences.

## Pros and Cons 

The advantages of making this adjustment to F# are fast and efficient processing of large/infinite sequences.

The disadvantages of making this adjustment to F# are the implementation is not simple. It requires deep knowledge of the `seq` implementation. My implementation may be improved upon and needs more testing. In particular it only call `Dispose()` after fully processing a seq. This may be detrimental when sequences are not processed to the end.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  M

Related suggestions: (put links to related suggestions here)

Here is a similar suggestion although more limited in scope:
https://github.com/fsharp/fslang-suggestions/issues/922

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
There is already a splitAt present

A `tryHeadAndTail` is not such a bad idea but it is also very easy to write, or do an explicit match

I'm going to close this as the main suggestions `splitBy` just doesn't look like something we want in FSharp.Core

**Comment by amieres** [comment]
Is there a splitAt for Seq ?

I know there is one for List and Array but I can't find one for Seq.

Using List or Array requires loading the whole sequence in memory which makes it impractical for large or infinite sequences. 

A naïve implementation can be easily done by simply restarting the sequence from the start but it is inefficient for large sequences like the example in the original post:

    let splitAt n (s:_ seq) = (Seq.truncate n s,  Seq.skip n s)

    [1..3]
    |> Seq.map (fun i -> printfn "item: %d" i ; i)
    |> splitAt 2
    |> printfn "%A" 

    (* output
    item: 1
    item: 2
    item: 1
    item: 2
    item: 3
    (seq [1; 2], seq [3])
    *)

The purpose of the suggestion is to give `Seq` the ability to process large or infinite sequences in an efficient way.
