### ISSUE TITLE
Seq.transpose [ RFC FS-1042]

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#106]
**Submitted by James Ashwell on 5/3/2016 12:00:00 AM**  
**14 votes on UserVoice prior to migration**  

It would be nice to have a function that transposes sequences:

``` fsharp
[ [ 00; 01; 02;... ]; [ 10; 11; 12;... ]; [ 20; 21; 22;... ];... ]
```

to

``` fsharp
[ [ 00; 10; 20;... ]; [ 01; 11; 21;... ]; [02; 12; 22;... ];... ]
```

This is particularly useful when dealing with infinite x infinite sequences, where you want to iterate over the 'outer group' first.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13721676)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13721676-seq-transpose.md#comments)

**Comment by dsyme** [comment]
Marking as approved in principle

**Comment by PatrickMcDonald** [comment]
PR Created: microsoft/visualfsharp#4020

**Comment by dsyme** [comment]
RFC: RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1042-add-seq-transpose.md

**Comment by PatrickMcDonald** [comment]
This one is complete and can be closed
