### ISSUE TITLE
using `[>_]` to define an expression as a unary function

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1063]
# using `[>_]` to define an expression as a unary function

I propose we use `[>_]` to define an expression as a unary function. for example

```F#
[1;2;3]
|> List.map [>2*_+3]
|> List.map [>_.ToString()]
```
where `[>` is the open limiter. `]` is the close limiter. and they cannot contain another nested `[>_]`.

Underscores in this context represent the only input parameter for the unary function.

The existing way of approaching this problem in F# is 

```F#
[1;2;3]
|> List.map (fun x -> 2*x+3)
|> List.map (fun x -> x.ToString())
```
## Pros and Cons 

The advantages of making this adjustment to F# are that It's a syntax sugar that saves some tapping on the keyboard.

The disadvantages of making this adjustment to F# are that it is just Icing on the cake.

**Comment by dsyme** [comment]
I think this is best made as an additional suggestion the the discussion in #506
