### ISSUE TITLE
Support type annotation based on expression's type

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#107]
**Submitted by Gauthier Segay on 5/9/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

It would be helpful to have type annotation made of the type of another expression:

``` fsharp
let a = 1
let b : typeofexpr<a> = 2
```

this type of type annotation exists in Oracle SQL database (tablename.column_name%type) and [is implemented in jai language](https://www.youtube.com/watch?v=iVN3LLf4wMg). I believe it is also possible to do similar thing with C++ templates.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13785189)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13785189-support-type-annotation-based-on-expression-s-typ.md#comments)

**Comment by dsyme** [comment]
This is an interesting suggestion, especially in the context of F# type providers.
