### ISSUE TITLE
Support more annotations in interface and function type declarations

### ISSUE THREAD

**Issue by En3Tho** [fsharp/fslang-suggestions#1072]
# Title of Suggestion

I propose we enrich interface and function type declarations with an ability to specify names of return values and unify behaviour between interface and function type declarations:

``` fsharp
type IncrementFunc = param: int -> oldAndIncremented: (int * int)

type IncrementDelegate = delegate of param: int -> oldAndIncremented: (int * int)

type IIncrementor =
    abstract IDoSomething: param: int -> oldAndIncremented: (int * int)
```

The existing way of approaching this problem in F# is ...
Currently what is allowed: 
``` fsharp
type IncrementFunc = int -> (int * int) // function types do not support specifying names and all

type IncrementDelegate = delegate of param: int -> (int * int) //  delegate types support specifying parameter names but not for return values

type ISomeInterface =
    abstract IDoSomething: param: int -> (int * int) // interfaces support specifying parameter names but not for return values  
```

## Pros and Cons 

The advantages of making this adjustment to F# are ...

The ability to specify names of return values to clarify what exactly is expected to be returned. Unify declaration syntax and capabilties.

The disadvantages of making this adjustment to F# are ...

None... ?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
Usually we specify return value names inside the method name itself or in XML documentation.

**Comment by xperiandri** [comment]
Why do you need to name return value?

**Comment by xperiandri** [comment]
What about ValueTuple items naming on return like in C#?

**Comment by En3Tho** [comment]
@xperiandri It's generally very helpful to annotate return values especially when working with legacy code where full blown refactoring is not possible, eg incremental one is better. Also there are sometimes results which are better annotated as just return values, e.g. deleteUser function type or interface method be annotated that it specifically returns oldUser value. Making new type "OldUser" for the sake of signature clarity is not really desireable, it litters the code.

Also I believe it can help with reading signatures with tooltips only, e.g. you don't have to F12 to understand what is returned, it's in the tooltip.

Mostly it's about overall consistently and working with legacy incremental refactorings plus an annotation if return value is quirky/ambiguous.

**Comment by dsyme** [comment]
I'm not in favour of this - an anonymous record can be used for example
