### ISSUE TITLE
Add Result<'a> = Result<'a, exn> to make Result easier to use.

### ISSUE THREAD

**Issue by Seng-Jik** [fsharp/fslang-suggestions#1076]
# Add Result<'a> = Result<'a, exn> to make Result easier to use.

I propose we can add Result<'a> = Result<'a, exn> to easier to use.

```fsharp
type Result<'a> = Result<'a, exn>
```

The existing way of approaching this problem in F# is define it manual.

## Pros and Cons 

The advantages of making this adjustment to F# is Result<'a, 'e> most used in Result<'a, exn> to process exceptions in monadic style, 'e is exn in most cases, so Result<'a> is easier to use in most cases.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
You should write anonymous unions instead of `exn`.

**Comment by dsyme** [comment]
@Happypig375 

> You should write anonymous unions instead of exn.

If I understand you, you want `Result<FooException | BarException>`.   That can cause a lot of wrapping/unwrapping of results as more exception types are added.

**Comment by Happypig375** [comment]
@dsyme

The idea is to write `Result<int, exn>` as `Result<int>`.

**Comment by Happypig375** [comment]
@dsyme

The idea is to write `Result<int, exn>` as `Result<int>`, where `exn` is the error type.

**Comment by Seng-Jik** [comment]
> anonymous unions

Is "anonymous unions" means Choice<'a> ?
Sometimes we just want to process exception explicitly, like this:

```fsharp
let a = async {
    try return Ok (mayThrowsException ())
    with e -> return (Error e)
}
```

**Comment by pblasucci** [comment]
@Happypig375, there are a lot of times where errors are better modeled by an _open_ hierarchy (as opposed to the _closed_ hierarchy of unions, whether anonymous or otherwise). In those circumstances, `exn` is often a quite reasonable base type -- especially when your failure modes will have to account for (C#) components behaving exceptionally anyway. So, I imagine this suggestion is aimed at those circumstances, rather than the finite error states of a domain model (where using `FSharpResult'2` with a union of failures seems a better fit).

**Comment by En3Tho** [comment]
I second to using exceptions as "Error" case. DU break so easily when composition is involved. Not to mention that exceptions are by nature like error information containers. You are free to choose whether to do some corrective actions here and now or to pass it to the caller. Free to choose whether to enrich it with stack trace or just pass as a simple "message". It's very easy to model a simple model of main base exceptions for the rest based services.

Anonymous unions are great and they will be a perfect addition to this system allowing to declare proper interfaces, functions etc using combineable exceptions and not DU's.

**Comment by MaxWilson** [comment]
Wouldn't this make Result ambiguous if you did it in the same namespace? E.g. you could no longer say 

```
let a = Result.Error "You did something wrong"
```

Instead you'd have to give type arguments to Result, e.g. Result<'a, string>.Error "you did this wrong". I find this quite verbose.

**Comment by dsyme** [comment]
Yes, `Result.Error` becomes ambiguous, so this is actually a breaking change (or would need bespoke compiler work to make it not a breaking change)

`Error` does not become ambiguous:


```
> type Result<'a> = Result<'a, exn>
- ;;
[<Struct>]
type Result<'a> = Result<'a,exn>

> Result.Error "a";;

  Result.Error "a";;
  ^^^^^^^^^^^^

stdin(3,1): error FS1124: Multiple types exist called 'Result', taking different numbers of generic parameters. Provide a type instantiation to disambiguate the type resolution, e.g. 'Result<_>'.

> Error "a";;
val it : Result<'a,string>
```

**Comment by dbrattli** [comment]
I think this is called `Try` in some other languages e.g Scala so it could be added as `Try` to F# as well as a simpler `Result` type.
