### ISSUE TITLE
Support for named arguments to curried functions

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#108]
**Submitted by Bartosz Sypytkowski on 5/18/2016 12:00:00 AM**  
**25 votes on UserVoice prior to migration**  

The idea here is to add support for labeled arguments in curried functions. This could allow to extend things like partial application to depend not only on arguments order, and also to introduce default argument values in curried functions (now it's possible only in F# type methods).
This feature is supported already in ML languages like OCaml or FB Reason.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13887384)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13887384-support-for-named-curried-functions.md#comments)

**Comment by dsyme** [comment]
We decided against this in F# 2.0/3.0.  There were good reasons for this: among other things, the OCaml syntax is unwieldy when there is a fair amount of object/member programming going on as well. 

The design policy is not to revisit issues like this where we have already made a firm decision, unless there is a significant change in circumstance.  So I'll close this for now.
