### ISSUE TITLE
Try Catch and Throw

### ISSUE THREAD

**Issue by jkone27** [fsharp/fslang-suggestions#1087]
**currently throw and catch keyword are not used in F#**

currently ``throw`` and ``catch`` keywords are not used in F#, could make people transitioning from other langs easier for exception handling by aliasing some keywords

**Create keywords aliases for try/catch statement**

If there was a way to alias catch = with within a try/with expression and throw=raise (in general), that could help developers transitioning and reckognize what code does, even without ML or F# background

```
try
//...
catch ex -> //alias of with ex
     //..     
     throw // or throw ex or throw new MyException(), alias of raise

```

**Describe alternatives you've considered**

The alternative is to keep using raise and try/with

## Pros and Cons 

The advantages of making this adjustment to F# are devs coming from non-F# background might understand more easilly the exception handling parts (easier to understand)

The disadvantages of making this adjustment to F# are : we will have 2 ways to say the same thing (redundant)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S/M ? (i have no idea really here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [?] This is not a breaking change to the F# language design 
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by smoothdeveloper** [comment]
It feels a bit like "we'd like to using instead of open for namespaces" when one comes from C# or python (using or import).

Those choices are arbitrary and I believe `raise` is from OCaml, I prefer to only have `raise` rather than mix of `raise` and `throw`.

The things that make it harder to C# developers are some tricks with overload resolution on OO heavy API, or simply figuring out how the type inference and annotations work and having `throw` as an option won't change this picture in my opinion.
