### ISSUE TITLE
Expand Array and List pattern matching to include variable length space/amount of elements between beginning and end

### ISSUE THREAD

**Issue by Angr1st** [fsharp/fslang-suggestions#1099]
# Array and List pattern matching extension: variable length space/amount of elements between beginning and end

I propose we expand the pattern matching capabilities for Lists and Array to allow matching on the beginning and end of a list or array. Using the '..' notation to specify an arbitrary large space/amount of elements between the first and last part of the pattern.

- There can only be a maximum of one occurence of the '..' for each pattern. 
- The hole/space needs to be filled with at least one element otherwise it won't match.

```
let exampleList = [1; 2; 3; 4; 5]

match exampleList with
| [] -> printfn "Empty List"
| [1; 2; ..; 3; 4; 5] -> () //does not match as there are no elements between 2 and 3
| [1;..;4;5] -> printfn "matches!"
...

let exampleArray = [|1; 2; 3; 4; 5|]

match exampleArray with
| [||] -> printfn "Empty Array"
| [|1: ..: 3; ..; 5|] // Invalid pattern as there is more than one occurence of the '..' 
| [|1;2;..;5|] -> printfn "matches!"
...
```

The existing way of approaching this problem in F# is creating an active pattern. 

```
open FSharpPlus
let inline compare elementsFromTotal pattern =
    elementsFromTotal
    |> zip pattern
    |> map (fun (a,b) -> a = b)
    |> fold (&&) true

/// Supplying empty patterns for start and ending always matches except if total is also empty
let (|ArrayStartsEndsWith|_|) (start:'T[]) (ending:'T[]) (total:'T[]) =
  let lengthStart = start.Length
  let lengthEnd = ending.Length
  let isLengthStartZero = lengthStart = 0
  let isLengthEndZero = lengthEnd = 0
  let minimumLength = lengthStart + lengthEnd + 1
  if total.Length < minimumLength && total.Length <> 0 && not isLengthStartZero && not isLengthEndZero then
    None
  else
    match isLengthStartZero , isLengthEndZero  with
    | false, false ->
        let firstElementsFromTotal = total.[0..(lengthStart - 1)]
        let lastElementsFromTotal = total.[^(lengthEnd - 1)..^0]

        let matchesStart =
            firstElementsFromTotal
            |> compare start

        let matchesEnding =
            lastElementsFromTotal
            |> compare ending

        if matchesStart && matchesEnding then
            Some true
        else
            None

    | false, true ->
        let firstElementsFromTotal = total.[0..(lengthStart - 1)]
        
        let matchesStart =
            firstElementsFromTotal
            |> compare start

        if matchesStart then
            Some true
        else
            None
    | true, false ->
        let lastElementsFromTotal = total.[^(lengthEnd - 1)..^0]
        
        let matchesEnding =
            lastElementsFromTotal
            |> compare ending

        if matchesEnding then
            Some true
        else
            None
    | true, true -> Some true
```

## Pros and Cons 

The advantages of making this adjustment to F# are 
- less active patterns
- improved default pattern matching capabilities

The disadvantages of making this adjustment to F# are additional complexity in the language and the compiler.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
M/L (I have no clue. Hopefully someone with more experience working on the fsharp compiler can make an improved estimate)
Related suggestions: #27 <- because it is also related to pattern matching on arrays.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it. (I am unsure because #27 was declined.) 

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
https://github.com/fsharp/fslang-suggestions/issues/968#issuecomment-764636595

**Comment by Happypig375** [comment]
```fs
let (|ArrayStartsEndsWith|_|) (start:'T[]) (ending:'T[]) (total:'T[]) =
    if total[..start.Length-1] = start && total[^ending.Length-1..] = ending then Some () else None
    
match [||], [|0..9|] with
| ArrayStartsEndsWith [||] [||], ArrayStartsEndsWith [|0; 1; 2|] [|8; 9|] -> printfn "Expected"
| _ -> failwith "Not here"
```

**Comment by Angr1st** [comment]
@Happypig375  what you mean to say is that Don already said that something like this has no chance of being accepted in the first place. 

I feel kind of stupid not thinking about equality of arrays directly and having 50 lines replaced with 1 but thank you for pointing that out 👍

**Comment by Happypig375** [comment]
You're welcome
