### ISSUE TITLE
Add `bool` operator to perform explicit type conversions

### ISSUE THREAD

**Issue by vincentremond** [fsharp/fslang-suggestions#1102]
# Add `bool` operator to perform explicit type conversions

I propose we add a `bool` operator like there is already [`int` operator](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/prim-types.fs#L4327), [`float` operator](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/prim-types.fs#L4420), [`string` operator](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/prim-types.fs#L4509), etc.

Examples :
``` F#
let myBoolValue1 : bool = "true" |> bool
let myBoolValue2 : bool = true |> string |> bool
```

The existing way of approaching this problem in F# is using `System.Convert.ToBoolean` or to recreate a function doing the same thing.

## Pros and Cons 

The advantages of making this adjustment to F# are :
* adding consistency when performing an explicit type conversion
* making learning F# easier (I was confused why I could do `|> int` but not `|> bool`)

The disadvantages of making this adjustment to F# are :
* making developpers not aware of potential runtime errors.  
For example this `"Hello world" |> bool` would throw a `System.FormatException` at runtime.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here) n/a

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
This feels like a "hmmm, I guess I don't see a reason not to have this" sort of thing. Any objections from anyone?

**Comment by jl0pd** [comment]
If it's only for strings, then I don't see benefit over `System.Boolean.Parse`, which is slightly shorter than `System.Convert.ToBoolean`. This code is fine enough `let bool (str: string) = System.Boolean.Parse str`, or you can use currying to make very short version `"zxc" |> (=) "true"`

Bool operator would be more useful if it could be used same way as in C/C++ or python where developers write code this way:
```
int a = 0;
if (a) { ... }

char[] s = null;
if (s) { ... }
```

But it encourage laziness, you should be more explicit at what you're doing. In first case check against 0: `if (a != 0)`, in second check against null `if (s != null)`. Implicit conversions reduce type safety and people start to use [Yoda-conditions](https://en.wikipedia.org/wiki/Yoda_conditions). Even if conversion is explicit, there's always a better way to convert value to bool.

**Comment by dsyme** [comment]
> This feels like a "hmmm, I guess I don't see a reason not to have this" sort of thing. Any objections from anyone?

Even if this wasn't a breaking change I think I'd be cautious.  Some people might expect `bool null` or `bool ""` to return `false` for example. It's just not very intuitive to have it only return `true` for `"True"` and `"true"`, and immediately raises internationalization questions (as does `string true` but let's not make a bad problem worse...).  

Using `bool.Parse` with all its docs, examples and options seems more reliable.

**Comment by Happypig375** [comment]
@dsyme Can we also allow `int.Parse` for consistency? This is just like how `String` can simultaneously be a type and a module pending disambiguation.

**Comment by dsyme** [comment]
That would be a broader change, something along the lines "for a.b, if 'a' resolves to a value where resolving 'b' would fail, then search to resolve 'a.b' via a type/module". Currently if something resolves to a value we don't search further. 


Such a rule could perhaps be restricted to cases where "a" resolves to a function-typed value, since these support very little dot notation. 

However adding such a rule has consequences for source compact under changes in libraries, so needs careful consideration.

In truth we've likely made breaking changes when adding top level values that have the same names as types - but what's done is done

**Comment by Swoorup** [comment]
I would certainly dislike having more non-total functions in the std library.

**Comment by piaste** [comment]
> I would certainly dislike having more non-total functions in the std library.

+1

I also think that boolean string representation are far more varied than int or even float representation. Int representation is pretty universal (Arabic numbers), floats vary with culture but at least it's typically _one_ representation per culture, with non-semantic variations within the same culture such as absence/presence of decimal separators.

Within the same en-US culture, bools may be found represented as :

 - "0" vs. "1"
 - "0" vs. any other number
 - "false" vs "true"
 - "FALSE" vs "TRUE"
 - null or "" vs. "any non-empty string"
 - "no" vs "yes" (hello YAML!)
 - "off" vs "on" (hello YAML _again_)
 - "" vs "✓"
 - "" vs "X"

To be fair, all the above applies to `bool.Parse` as well, but at least when you dot-notate into it you get to see the existence of `FalseString` and `TrueString`.

![image](https://user-images.githubusercontent.com/12280683/145386478-28b192e5-c38d-41ee-90f6-bd7d45c40b63.png)

There is also more of an expectation of totality from a F# core function, as @Swoorup pointed out. I think I would prefer a slightly different but total implementation such as "the string 'true' evaluates to true and anything else as false" over simply aliasing Boolean.Parse.

**Comment by dsyme** [comment]
I will close this 

I think a "bool" operator in the Fable/JS world would have to act much like "truthiness" in JavaScript - so empty string, null, 0 etc. etc. would all go to "false".  Without that behaviour introducing such an operator just feels really risky and obfuscating, adding more subtlety to what such an operator would do.

Even in the F#/,NET world I would always have to look up the spec of such an operator.
