### ISSUE TITLE
Auto implement or syntax sugar partial active recognizers for FullActivePatterns

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsharp/fslang-suggestions#1106]
I propose we add a way to reference individual branches of a partial active pattern for use as functions. This will provide a way to treat branches of a Full Active Pattern as a first class function.

The existing way of approaching this problem
```fs
// setup
let (|NullString|EmptyString|Whitespace|ValueString) = function | null -> NullString | "" -> EmptyString | x when String.IsNullOrWhitespace x -> Whitespace x | x -> ValueString x
```
manual code to be written without this feature:
```fs
  let asWhitepace x = match x with | Whitespace v -> Some v | _ -> None
  let asValueString x = match x with | ValueString v -> Some v | _ -> None
```

proposed syntax consumption (full active patterns would imply/generate/allow-you-to-desugar partial active patterns)

```fs
let asWhitespace x = (|Whitespace|_|) x
let asValueString x = (|ValueString|_|) x
```
which could also be used as an alternative in piping without having to create a non-pattern function to do the same thing

```fs
text |> Option.map (|ValueString|_|) 
```
without having to write the `asValueString` function above.

## Pros and Cons 

The advantages of making this adjustment to F# are less typing, less code that adds nothing but noise and hides the intent.
It would enable mexx's idea in https://github.com/fsharp/fslang-suggestions/issues/611#issuecomment-332529197

The disadvantages of making this adjustment to F# are 
 - potential conflicts with #766 (which could be handled by shadowing just like records and other things that are last-imported-or-in-scope-is-auto-selected)
 - potential conflicts with #1041 

## Extra information

Estimated cost (S)

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
I'm not in favour of this as it just seems too corner case.  Asking people to be explicit about the different selectors is not a bad thing.
