### ISSUE TITLE
Provide escape hatch for automatic generalization

### ISSUE THREAD

**Issue by chkn** [fsharp/fslang-suggestions#1107]
I propose we provide an escape hatch for automatic generalization. In particular, the compiler seems to ignore `obj` type annotations, resulting in undesired generalization that makes it difficult to design APIs that can be used without type annotations.

For example:

```fsharp
type Thing1 = Thing1
type Thing2 = Thing2

type Style = Bold | Italic

type Styled = Styled of obj * Style

module Style =
    let inline set style (thing: obj) = Styled(thing, style)

let bold = Style.set Bold // error: value restriction, but shouldn't be generic in the first place

let boldItalic = // compiles due to `thing1` binding below, but inferred type is Thing1 -> Styled
    Style.set Bold >>
    Style.set Italic

let thing1 = boldItalic Thing1 // ok

let thing2 = boldItalic Thing2 // error: expected to have type 'Thing2' but here has type 'Thing1'

```

What should be a simple and straightforward API becomes difficult to use due to the automatic generalization of the `obj` parameters. If the compiler respected the type annotations and didn't try to make things generic, the API would be much more ergonomical.

For another example, I believe the same phenomena is causing the unexpected overload resolution failure in this issue: https://github.com/dotnet/fsharp/issues/12537

---

The existing way of approaching this problem in F# is to put the onus on the consumer of the API to add additional type annotations:

```fsharp
let bold: obj -> _ = Style.set Bold

let boldItalic: obj -> _ =
    Style.set Bold >>
    Style.set Italic
```

These extra annotations add noise to the code and make it more difficult to design ergonomical libraries that are intuitive for F# beginners.

## Pros and Cons 

The advantages of making this adjustment to F# are removing extra type annotations and making it easier to design intuitive APIs.

Some ideas for possible approaches:

- Ideally, we could simply change the automatic generalization behavior to respect an explicit `obj` type annotation and not try to generalize it. But this might be a breaking change.
- Maybe we can backtrack in the case of a value restriction and not generalize. This would fix the `bold` case and wouldn't be a breaking change (since that wouldn't have compiled before anyway), but wouldn't help the `boldItalic` case, where the compiler is avoiding the value restriction by specializing it (ironically, this results in more specialized code than if the compiler had just left it as `obj` in the first place :p).
- We could add an attribute to disable the auto-generalization in a backward-compatible way: 

```fsharp
let inline set style ([<DoNotGeneralize>] thing: obj) = Styled(thing, style)
```
The disadvantage would be that this would be yet another esoteric attribute that in turn makes the language less intuitive for beginners. But hopefully, such a mechanism could be used by library authors to in turn deliver more intuitive APIs.

Perhaps there are other options that I didn't consider.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): L

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
> In particular, the compiler seems to ignore obj type annotations, resulting in undesired generalization that makes it difficult to design APIs that can be used without type annotations.

This is true, but it's part of a subtle set of tradeoff desciions made in F# 1.0 about both allowing `obj` programming while also allowing implicit upcasting when calling methods and automatic generalization.  

I don't see us making adjustments here - it's just part of the resolution for how these features combine.

**Comment by chkn** [comment]
> This is true, but it's part of a subtle set of tradeoff desciions made in F# 1.0 about both allowing `obj` programming while also allowing implicit upcasting when calling methods and automatic generalization.

@dsyme Well in the time since F# 1.0, we've gotten https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1093-additional-conversions.md .. .so perhaps it is less of a concern?

In any case, we don't need to change the default behavior, as that would probably be a breaking change, but it would be nice to provide _some_ way for library authors to craft APIs that can be consumed without cryptic value restriction errors when type annotations are not provided by the end user.

**Comment by gusty** [comment]
If #819 is done it would also provide an escape hatch for this case.
