### ISSUE TITLE
Make module-defined functions callable as class extension methods

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#111]
**Submitted by trek42 on 5/27/2016 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

Sometimes it's more convenient and succint to call a function using dot-notation (i.e., class method) than calling module functions with pipeline, yet module function is easier to be composed. I propose the compiler automatically generate class extension methods from module functions, based on a new attribute "CallByInstance" Example:

``` fsharp
namespace Namespace
// .fsi
module List =
    val map: ('T -> 'U) -> [<CallByInstance>] list<'T> -> list<'U>
```

Compiler will automatically generate an extension method of list<'U>, in the _containing_ namespace, i.e.,

``` fsharp
namespace Namespace

module List = ...

// Automatically generated:
[<AutoOpen>]
module ListExtension_map =
    type List<'U> with
        member this.map f list = List.map f list this
```

This allows the following syntax:

``` fsharp
[1;2;3] |> List.map ((+) 1) // as usual
[1;2;3].map ((+) 1) // call the extension method with dot-notation.
```

Notes:
1. The extension method is a curried member function. (We don't change the curried parameters to tuple).
2. Similarly we don't change the function name (e.g., no "map" => "Map" thing).
3. We don't need to open module "List" for the extension method. Anywhere "List.map" is accessible, "[1;2;3].map" is also accessible.
4. You can label multiple parameters of a function as [<CallByInstance>], as long as their types are different.
5. Since we require explicitly marking the allowed parameters, there is no compatibility issue. Users can choose to use this feature judiciously.
Finally, this is related to /archive/suggestion-5663326-syntax-for-turning-properties-into-functions, but in a reverse way (i.e., turn a module function to a method). My personal view is we need both.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/14277294)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-14277294-make-module-function-callable-as-class-extension.md#comments)

**Comment by dsyme** [comment]
This is related to #1073

**Comment by dsyme** [comment]
Closing as we're not going to do this feature like this.  If anything we would do it explicitly via #1073
