### ISSUE TITLE
Resolve value restrictions on subtypable arguments automatically

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1113]
I propose we let this compile:
```fs
type A() = inherit System.Collections.Generic.List<int>()
let f (_: string) (_: A) = ()
let g = f "a" // error FS0030: Value restriction
let f' (_: string) (_: seq<int>) = ()
let g' = f' "a" // error FS0030: Value restriction
```
With the implementation of
- https://github.com/dotnet/fsharp/pull/10884

, the automatic generalization here is no longer helpful since, without generalisation, upcasts are inserted instead automatically. We should default to the declared type instead while keeping the error in case the flexible type `#` is specified because it indicates generalisation.

The existing way of approaching this problem in F# is
```fs
let g: A -> _ = f "a"
let g': _ seq -> _ = f "a"
```
```fs
let g x = f "a" x
let g' x = f "a" x
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Consistency with sealed type arguments

The disadvantage of making this adjustment to F# is more usages of FS-1093 outside of C#-interop.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions:
- https://github.com/dotnet/fsharp/issues/6509
- https://github.com/dotnet/fsharp/issues/1161
- https://github.com/dotnet/fsharp/issues/1199
- https://github.com/fsharp/fslang-suggestions/issues/1107 (This suggestion does not go the path of requiring an argument at the function.)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
Yes, this is a great opportunity for simplification. If `x: 'a` and `f:'a->'b` then `f x:'b`.

What is the remaining value of flexible types after FS-1093?

**Comment by dsyme** [comment]
TBH the actual suggestion here (involving partial application) seems to corner case to justify.  Note this works:

```fsharp
type A() = inherit System.Collections.Generic.List<int>()
let f (_: string) (_: A) = ()
let g = f
```
In the case of `f "a"` it's tru the partial application/value-restriction does interfere in the process by which flexiblity is added on use of `f` (called decondensation and condensation in the F# spec). However there are technical differences between how that process works compared to FS-1093, and we can't remove either mechanism.

> What is the remaining value of flexible types after FS-1093?

@charlesroddie Mainly in nested positions, e.g. `option<#SomeBaseType>` (you could argue we should have covariance instead)

**Comment by cartermp** [comment]
I would love to see a non-contrived example of where this trips people up. As much as I'm a fan of not needing to do things based on what's "obvious", is this a problem in reality?

**Comment by WhiteBlackGoose** [comment]
I personally needed it when I was making functions with seq argument at the end. E. g. when I was making my dummy html-generating DSL, I wrote something like this:
```fs
let tagFromSeq name (contents : string seq) =
    let inner = contents |> String.concat "\n"
    $"<{name}>{inner}</{name}>"
```
which now makes perfect sense to define tags like that:
```fs
let html = tagFromSeq "html"
let h1 = tagFromSeq "h1"
...
etc
```
But with this issue I had to write this instead:
```fs
let html contents = tagFromSeq "html" contents
let h1 contents = tagFromSeq "h1" contents
```
So, missing a truly great opportuinity to use curried functions in F#.

**Comment by dsyme** [comment]
> So, missing a truly great opportuinity to use curried functions in F#.

TBH the recommendation is always to make the argument explicit for top-level definitions and members.  This is because debugging, doc generation and so on are all improved.

**Comment by WhiteBlackGoose** [comment]
Okay.... but it could be not top-level too, right? And for some very simple functions, like html tags, it doesn't really need debugging, does it?

**Comment by dsyme** [comment]
> Okay.... but it could be not top-level too, right? And for some very simple functions, like html tags, it doesn't really need debugging, does it?

> Okay.... but it could be not top-level too, right?

Yes, though those are not subject to the value restriction.

> And for some very simple functions, like html tags, it doesn't really need debugging, does it?

I do see your point, and people do like to compute functions like this at the top level, but the restriction is just hard to lift without creating more corner cases.

**Comment by WhiteBlackGoose** [comment]
I see, thanks

**Comment by dsyme** [comment]
I'm closing this per my comment here: https://github.com/fsharp/fslang-suggestions/issues/1113#issuecomment-1031754762
