### ISSUE TITLE
Interop with C# method with optional argument and params

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1120]
This case happened to me when I was using `FluentAssertions`, when I try to call a C# method that receives the first argument with a default value and a second params argument I can't omit both parameters.

E.g:
```cs 
    public class Class1
    {
        public static string Foo(string something = "", params object[] args) => 
            string.Format(something, args);
    }

```
If I try to use this method in F# I expected to be able to call it in this way:

```fsharp
 let result1 = Class1.Foo()
```
But this gives me an error :
```
Error FS0501: 
The member or object constructor 'Foo' takes 2 argument(s) but is here given 0. 
The required signature is 'Class1.Foo(?something: string, [<System.ParamArray>] args: obj[]) : string'.
```

So, to make it work  I need to pass the first argument explicitly which I would expect to be optional :

```fsharp
 let result1 = Class1.Foo("")
```

## Pros and Cons 

I don't know if this is bt design, but is very confusing and made the interop harder and noisy in some cases.

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by baronfel** [comment]
This _may_ have been addressed in https://github.com/dotnet/fsharp/issues/12515 - where default arguments were being factored into the logic. It's worth testing though.

**Comment by edgarfgp** [comment]
Consider closing this as has been implemented by https://github.com/dotnet/fsharp/pull/16688
