### ISSUE TITLE
write only once undefined value

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1121]
I propose we introduce a kind of variable that use undefined placeholder as initialized value, it is allowed to write/change its value to a determined immutable value once. And, until then, it is not allowed to read it.

The existing way of approaching this problem in F# is 

In F# language, we set a id's value when it is allocated and leave it immutable.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

The specified position can be occupied first, before the value is determined. And keep the memory safe. You can delineate more memory space than the minimum needed, placing variables in a more global position.

The disadvantages of making this adjustment to F# are 

Errors may be delayed until run time, rather than being solved at compile time.

## Extra information

Usage:

```F#
// example 1:
let arr = Array.undefinedCreate 100

// example 2:
let allocListNode head = { head = head; tail = undefined }

let a = allocListNode 1
let b = allocListNode 2
a.tail |> ignore // fail because undefined value is write-only.
a.tail <- b // ok! write it, change the value to a defined value.
a.tail |> ignore // ok! now, it is a defined value, which is a normal immutable value.
a.tail <- a.tail // fail because now, it is a defined value, which is a normal immutable value.
let c = allocListNode 3
b.tail <- c
```

**Comment by WhiteBlackGoose** [comment]
Honestly... I don't see much of profit, but on the other hand, it gives some "surprise" to users that fields of a returned object are inaccessible. Also, there's a million of uncovered corner cases, for starters, how would you design this behaviour:
```fs
let allocListNode head =
    if head > 2 then { head = head; tail = undefined }
    else { head = head; tail = [] }

let a = allocListNode 1
a.tail <- b // ok or not ok?
```

Imo your showcase is well solvable by partial application.

**Comment by xp44mm** [comment]
compiler will generate next code to determine action:
```F#
try a.tail <- b with _ -> failwith "'a.tail' is immutable"
```

**Comment by WhiteBlackGoose** [comment]
That implies that property `tail` will also need a private flag which shows if it's initialized, and if it's false for reading or true for writing, throw, right?

But then it becomes a runtime error *and* perf regression...

**Comment by xp44mm** [comment]
That's a matter of concrete implementation, there are many methods, I believe experts will weigh it.

**Comment by xp44mm** [comment]
Performance shouldn't have much of an impact, i.e., that is:

- If the program reads undefined, then it will throw an exception.
- If the program writes to the immutable, then it will throw an exception.

**Comment by xp44mm** [comment]
Performance shouldn't have much of an impact, i.e., that is:

- If the program reads `undefined`, then it will throw an exception.
- If the program writes to the `immutable`, then it will throw an exception.

**Comment by abelbraaksma** [comment]
If I understand your proposal correctly, you'd want some kind of built-in support for what you can already do by using property setters/getters, right? I.e., some kind of shortcut for the following code:

```f#
type WriteOnlyEx<'T>() =
    [<DefaultValue()>]
    val mutable private value: Option<'T>
    member this.Value 
        with get() =
            match this.value with
            | None -> raise (new Exception "Property not yet set")
            | Some x -> x
        and set v =
            match this.value with
            | Some _ -> raise (new Exception "Property is write-once, and has already been set")
            | None -> this.value <- Some v

module WriteOnlyTest =
    let x = WriteOnlyEx<int>()
    printfn "Value: %A" x.Value         // error, property not yet set
    x.Value <- 42                       // fine
    printfn "Value set to: %A" x.Value  // ok
    x.Value <- 0                        // error, can only set once.
```

I don't think this should be built-in behavior as it can only be checked during runtime (otherwise we'd need flow analysis). A type in F# kinda has this behavior, `Lazy<'T>`, but that uses a read-only property, so it is not quite the same. But perhaps code like the above can be used for your use-cases.

**Comment by xp44mm** [comment]
The `WriteOnlyEx` can help avoid programming errors, but the original idea of this issue is that once the data structure is built, the data structure self just is immutable value.

**Comment by abelbraaksma** [comment]
@xp44mm, indeed. Since the variable is private, that's exactly what this does, it's immutable. I know it's wrapped in a class. What you're suggesting is the variable assignment itself, which is like a late binding let variable. But like I said, that cannot be enforced. There is, however, the construct of `val`, but that only applies to classes and the late binding must happen in the constructor.

**Comment by dsyme** [comment]
I understand that languages with a lot of mutation can benefit from this.  However it doesn't look reasonable for F# code, where explicit mutation is much rarer.
