### ISSUE TITLE
Allow read access to records, but private construction 

### ISSUE THREAD

**Issue by brianberns** [fsharp/fslang-suggestions#1122]
In order to support input validation, I think it would be useful to declare a type whose fields can be accessed, but which cannot be directly created by users. 

## Problem

We often need to validate input when constructing a value of a particular type. For example, let's say we want a type that represents positive floating-point numbers:

```fsharp
type PosFloat =
    {
        Value : float
    }

module PosFloat =

    let add x y =
        {
            Value = x.Value + y.Value
        }
```

(Note that this could be represented by either a record or a discriminated union. I've chosen to use a record type here, but the same discussion applies equally to DUs.)

We could then use this type as follows:

```fsharp
let x = { Value = 1.0 }
let y = { Value = 2.0 }
PosFloat.add x y |> printfn "%A"   // { Value = 3.0 }
```

We want to make invalid states unrepresentable, so we need to prevent code like this:

```fsharp
let bad = { Value = -1.0 }
```

To do this, we make the fields private and provide a `create` function instead:

```fsharp
type PosFloat =
    private {
        Value : float
    }

module PosFloat =

    let create value =
        if value <= 0.0 then failwith "Must be positive"
        {
            Value = value
        }

    let add x y =
        create (x.Value + y.Value)

let x = PosFloat.create 1.0
let y = PosFloat.create 2.0
PosFloat.add x y |> printfn "%A"   // { Value = 3.0 }

let bad = PosFloat.create -1.0   // System.Exception: Must be positive
```

But now users can't access the internal value themselves:

```fsharp
module MyModule =
    let mult x y =
        PosFloat.create (x.Value * y.Value)   // The union cases or fields of the type 'PosFloat' are not accessible from this code location
```

How can we fix this?

## Workaround

One approach is to provide a separate member for accessing the internal value:

```fsharp
type PosFloat =
    private {
        _Value : float
    }
    with member this.Value = this._Value

module PosFloat =

    let create value =
        if value <= 0.0 then failwith "Must be positive"
        {
            _Value = value
        }

    let add x y =
        create  (x._Value + y._Value)
```

But this has some major disadvantages:

* We had to rename the private field to avoid conflicting with the name of the public member.
* Users lose automatic type inference, so have to explicitly annotate uses of the type, which is potentially a lot of extra typing:

```fsharp
module MyModule =

    let badMult x y =
        PosFloat.create (x.Value * y.Value)   // ERROR: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object.

    let mult (x : PosFloat) (y : PosFloat) =
        PosFloat.create (x.Value * y.Value)
```

## Proposal

I think it would be useful to declare a type whose fields can be accessed, but which cannot be directly created by users. Something like this:

```fsharp
type PosFloat =
    protected {
        Value : float
    }
```

I've used `protected` here, but feel free to substitute another keyword of your choice. Users would then be able to access the `Value` field but not able to use it to construct a value of the type:

```fsharp
let x = { Value = 1.0 }   // prohibited
printfn "%A" y.Value      // allowed
```

Again, note that the same proposal applies to discriminated keywords:

```fsharp
type PosFloat = protected Value of float
```

## Pros and Cons 

The advantages of making this adjustment to F# are developers have a low-friction way to validate input when constructing F# records and discriminated unions.

The disadvantages of making this adjustment to F# are it requires a keyword, which is another thing that developers have to remember.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): Small. It's a single keyword that's easily parsed and enforced.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
Related: #810

**Comment by Frassle** [comment]
`protected` already has a meaning in the context of the CLR so I'd think it quite confusing to use that same word for this different concept.

**Comment by charlesroddie** [comment]
> Users lose automatic type inference, so have to explicitly annotate uses of the type, which is potentially a lot of extra typing:

The fact that `let add x y = ... x.Value + y.Value ` compiles is a bug in type inference, since possessing a member `Value` does not imply that something is a `PosFloat`. It's a guess not an logical inference. So the fact that a type annotation is required here is a benefit not a disadvantage.

I would recommend
```fsharp
[<Struct>]
type PosFloat private (value:float) =
    member _.Value = value
    static member Create(value:float) =
        if value <= 0. then failwith "Mut be positive" else PosFloat(value)
```

**Comment by brianberns** [comment]
> `protected` already has a meaning in the context of the CLR so I'd think it quite confusing to use that same word for this different concept.

I'm not attached to the particular keyword. I chose `protected` because it's already reserved by F#, but not used anywhere. We could instead use another existing keyword, such as `get`, or invent a new one, such as `readonly`.

**Comment by brianberns** [comment]
> The fact that `let add x y = ... x.Value + y.Value ` compiles is a bug in type inference, since possessing a member `Value` does not imply that something is a `PosFloat`.

That's the expected behavior for records and discriminated unions, not a bug. I think this behavior is crucial to writing clean F# code.

> I would recommend ... `[<Struct>]` ...

Having to fall back to low-level code like this is exactly what I'm proposing we should avoid for such a basic use case.

**Comment by acowlikeobject** [comment]
At our (my) company, we recently moved our "domain-heavy" code from Python to F#.  Overall, we've been very happy with our decision.

But, for a language whose selling points are correctness and conciseness, the absence of one obvious, simple way of creating constrained types is baffling.  We've repeatedly felt the need for ["destruct but don't construct" access](https://github.com/fsharp/fslang-suggestions/issues/810#issuecomment-564496622).

Scott Wlaschin shows a few ways [to do this](https://gist.github.com/swlaschin/54cfff886669ccab895a).  Everything there is a compromise, and has felt like a kludgy trick to newcomers; you give up the ergonomics of records and discriminated unions (a huge part of why we enjoy F#), or haven't really forced use of your validating constructor, or write tediously duplicative code in active patterns (which are limited to seven cases; not enough when making a large domain-specific DU "read only").

We'd dearly love to see something like this.

**Comment by brianberns** [comment]
Thank you for those links. Using active patterns to access the fields is an interesting idea, but still seems like a clunky workaround, rather than a long-term solution. Scott Wlaschin mentions that signature files can be used to solve this, but I don't see how that would work either. There really doesn't seem to be any good way to do this yet in F# with algebraic data types (i.e. records and DU's).

**Comment by cartermp** [comment]
Just a note:

> Small. It's a single keyword that's easily parsed and enforced.

This is probably not accurate. This amounts to a new kind of access modifier, which is not an easy thing to add and carefully consider the design for. It's not just this, but it's carefully considering all the domain modeling scenarios, understanding which feels appropriate to bring into the core language or not, good diagnostics, and ensuring tooling behaves correctly. Parsing a keyword is just a very small part of this.

Personally, I don't see this as being particularly valuable. This kind of flexibility around construction and visibility is exactly what objects provide, and @charlesroddie's suggestion is what I would do if I needed "read but not construct" permissions on a type. Since this is already supported by objects and structs in F# today, I don't think it's terribly important to bring into DUs and records.

**Comment by cartermp** [comment]
> Forcing users of my code to write `(x : PosFloat)` every time they want to access `Value` gets old quickly

There are also two other things to consider:

* F# code very often tends towards type annotations or parameters to functions or methods over time, especially in a public signature
* When used in pipelines, there is often little need to add a type annotation

**Comment by heronbpv** [comment]
Since the possibility of bringing stronger information-hiding concepts to DUs/Records seems to be too far, how about going in a different direction?
How hard would it be to bring some, or even better all, of the pattern matching capabilities enjoyed by DU and Records to F# objects instead?
I reckon they do lag behind in this area, but by how much?

**Comment by dsyme** [comment]
Also related is

1. Can record types be revealed with only members in the signature, see #1153
2. Can record types optionally reveal only the ability to access the record (e.g. pattern matching), and not construct in the signature

Ideally anything in this area would follow the same rules we use for access control.  However It's surprisingly hard to find remotely satisfying ways of declaraing this distiction in capabilities:

For the "can I create the record" then this is reasonable:

```fsharp
type PosFloat =
    {
        private new
        Value : float
    }
```
But what of restricting the ability to access it?  Do we allow access controls on the members?
```fsharp
type PosFloat =
    {
        private Value : float
    }
```

Perhaps this is reasonable - though it's not clear if you could do this:
```fsharp
type PosFloat =
    {
        public new
        private Value : float
    }
```
That is construct but don't touch.


Anyway I guess `private new` is a reasonable kind of feature addition, what do you think?

**Comment by acowlikeobject** [comment]
Enforcing a private constructor on the entire type (but leaving the ability to destruct public) with a `private new` and `internal new` would already be incredibly useful.  Member-level access control seems more complex and could be addressed later?

@dsyme Could this also be available on discriminated unions?  Again, hugely useful.  Current workarounds (eg, hiding cases with `private` and making them available via active patterns) have poor ergonomics.

**Comment by dsyme** [comment]
@acowlikeobject Yes, in theory.  What syntax?  And would it be per-union-case or not?  Per-union-case construction is the capability logicall corresponding to the `New*` static methods.

```fsharp
type Union =
    | internal new A of string 
    | internal new B of int 
```

Or this, doing all at once
```fsharp
type Union =
    internal new
    | A of string 
    | B of int 
```

The former is heading to a more complete state (access controls that correspond to the individual capabilities implied by the generated code for unions and records), the latter is simpler.

**Comment by dsyme** [comment]
Note attributes could also be used to prevent an expensive proliferation of new syntax. However that means accessibility becomes an awkward mix of attributes and keywords. Neither is ideal

**Comment by aneumann-cdlx** [comment]
> @acowlikeobject Yes, in theory. What syntax? And would it be per-union-case or not? Per-union-case construction is the capability logicall corresponding to the `New*` static methods.
> 
> ```fsharp
> type Union =
>     | private new A of string 
>     | private new B of int 
> ```

I'm definitely wading into the deeper end of the language pool than I ought to but if you will pardon me jumping in...I like per-union-case construction over per-union construction.

It appears to more closely track common cases when creating constrained types. You can add validation members [just like this](https://gist.github.com/swlaschin/54cfff886669ccab895a?permalink_comment_id=1450776#gistcomment-1450776) just like we have in the past of course, but the bonus here is that you no longer have to maintain two types, both of which are just parts of one domain entity in various stages of its lifecycle.

1. a public creatable unvalidated type (that then must be applied to a certain function to create the next type)
2. a private create validated type

Stealing some code from the linked example, we get an entire unvalidated->validated constrained type in just the type declaration.

```type EmailAddress = 
    | Unvalidated of string
    | private new Validated of string
    static member private isValid (value: string) =
        // Validation code goes here
        true
    static member Validate(address: string) =
        if EmailAddress.isValid address then
            Validated address
        else
            Unvalidated address
    member this.Value =
        match this with 
        | Unvalidated value -> value
        | Validated value -> value
```

Now any functions that want to take only valid emails can just pattern match on a given EmailAddress to see if the union case is Validated or not. We no longer need a separate (private create) ValidatedEmail type to make the illegal state unrepresentable.

**Comment by acowlikeobject** [comment]
> @acowlikeobject Yes, in theory. What syntax? And would it be per-union-case or not? Per-union-case construction is the capability logicall corresponding to the `New*` static methods.


@dsyme I'd vote for simplicity and have `private new` at the type-level.  (If you squint enough, it's analogous to type-level `private new` for records?)

DUs are fantastic for modeling state machines, where you want to inspect state in several places (public destruction), but control transitions (private construction).

I'm not sure case-level control adds much in those use cases.  You'd probably end up marking all or all-but-initial cases as private.  On the other hand, it feels pretty natural to have a type-level `private new` and force use of an event handler to effect state transitions.

But obviously, you can accomplish strictly more with case-level control, so I'd still be thrilled if that's what landed.  It just seems to use up the complexity budget for not a lot of additional value?

@aneumann-cdlx I'd say `create` and `value` functions work well enough for private DUs with binary `Unvalidated` and `Validated` cases.  You don't destructure much with those types anyway.  If you have an initial `Unvalidated` case and several validated cases, then it starts to look a lot like the state machine pattern above.

**Comment by SilkyFowl** [comment]
@dsyme I also agree with @acowlikeobject. `private new` is very exciting, I'd love to see it happen, although I think it would be useful to be able to control the case level of the DU.

@acowlikeobject If this feature is realized, pattern matching will be very easy, so combining it with `Result<'t,'error>` etc. may be a viable option, as shown below.

```fsharp
type EmailAddress = 
    private new
    | EmailAddress of string
    static member private isValid (value: string) =
        // Validation code goes here
        true

    static member TryCreate(address: string) :Result<EmailAddress,string>=
        if EmailAddress.isValid address then
            Ok (EmailAddress address)
        else
            Error address

    static member TryCreateWith onError (address: string) :Result<EmailAddress,'error>=
        if EmailAddress.isValid address then
            Ok (EmailAddress address)
        else
            Error (onError address)
```

Personally, I think it would be good to combine it with the Static Interface proposed in the following Issue.

- #1151 

```fsharp
type IValidatable<'dto,'t> =
    abstract static member Validate :('t -> 'validated) -> ('dto -> 'validated) -> 'dto -> 'validated

module Validatable =
    let validate<'Validatable when 'Validatable :> IValidatable<'dto,'t>> onValie onInvalid value =
        'Validatable.Validate onValid onInvalid value

    let create<'Validatable> x =
        validate<'Validatable> id (failwithf "Invalid: %A") x

    let createResult<'Validatable> x =
        validate<'Validatable> Ok Error x

    let createOpt<'Validatable> x =
        validate<'Validatable> Some (fun _ -> None) x

type EmailAddress = 
    private new
    | EmailAddress of string
    static member private isValid (value: string) =
        // Validation code goes here
        true

    interface IValidatable<string,EmailAddress> with
        static member Validate onValid onInvalid address =
            if EmailAddress.isValid address then
                onValid (EmailAddress address)
            else
                onInvalid address

type PosFloat =
    {
        private new
        Value : float
    }
    interface IValidatable<float,PosFloat> with
        static member Validate onValid onInvalid value =
            if value <= 0.0 then
                onValid {Value = value}
            else
                onInvalid value
```
