### ISSUE TITLE
Result module parity with Options

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1123]
# Result module parity with Options

I propose we add
```
get
isOk
isError
defaultValue
defaultWith
count
fold
foldBack
exists
forall
contains
iter
toArray
toList
toSeq
toOption
toValueOption
```
to the `Result` module to have parity with `Option` and `ValueOption` modules.

The existing way of approaching this problem in F# is falling back to match expressions.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Convenience
2. Conciseness
3. Consistency

The disadvantages of making this adjustment to F# are more functions needed to learn.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions:
- no orElse/orElseWith/(flatten/map2/map3) because combining Errors are ambiguous: https://github.com/fsharp/fslang-suggestions/issues/650

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
Also, do we want a version of some or most of these that works on the error instead of the result? Considering that there is already a `mapError`.

**Comment by theprash** [comment]
@pblasucci Maybe off topic, but I think it would be even more valuable to deprecate option's `.Value` property because that's way too easy to use.

**Comment by dsyme** [comment]
The original suggestion looks entirely reasonable, I'll mark it as approved.  I agree with omitting Result.get.  We can consider Option.get in a separate suggestion

> Also, do we want a version of some or most of these that works on the error instead of the result? Considering that there is already a mapError.

I think not.

**Comment by charlesroddie** [comment]
### Good
```
isOk
isError
defaultValue
defaultWith
toOption
toValueOption
```
### Seq-like, unclear why only Oks chosen

These assume that `Result<'T,'U>` is essentially an 'IEnumerable<'T>'. It is not clear why it is the OK values that are enumerated and not the Error ones.

Solutions:
1. Append Ok to all these names
2. Don't do anything and require the user to do r.ToOption |> Option.iter or r.ToSeq etc..
3. Have `Result<'T,'U>` implement `IEnumerable<'T>`. This doesn't deal with the problem but removes the need to have these methods and the associated inconsistency of doing seq-like things but not being a seq.
```
count
forall
toSeq
contains
fold
exists
iter
toArray
toList
```

###Bad
```
get
foldBack
```

**Comment by TheAngryByrd** [comment]
When adding this, I would want us to consider adding [InlineIfLambda](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1098-inline-if-lambda.md) attribute to appropriate parameters.  [This discussion](https://github.com/fsharp/fslang-design/discussions/656#discussioncomment-2205863) suggests putting it in Option/ValueOption and I'd assume we'd want the same for Result for the same reasons.  I implemented [this recently in FsToolkit.ErrorHandling](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/166#issuecomment-1040338192) and the performance/SharpLap really speak to why I think it would be worth doing in FSharp.Core.

**Comment by uxsoft** [comment]
I started with the RFC here:
https://github.com/fsharp/fslang-design/pull/667

**Comment by cartermp** [comment]
@gusty would you like to make a PR to the RFC? I generally agree

**Comment by gusty** [comment]
Done, thank you both for the quick feedback.

**Comment by edgarfgp** [comment]
@vzarytovskii I think this can be closed now that has been implemented :). Might be worth adding Option, ValueOption, Result to be eligible to use ```[<InlineIfLambda>]``` as part of as  https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1115-InlineIfLambda-in-FSharp-Core.md as @TheAngryByrd suggested?

**Comment by dsyme** [comment]
The implementation is here: https://github.com/dotnet/fsharp/pull/13326
