### ISSUE TITLE
Warn when a try can't catch an exception due to tasks

### ISSUE THREAD

**Issue by pbiggar** [fsharp/fslang-suggestions#1126]
# Warn when a try/with would allow an exception in a Task slip through

With a naive reading of the following code, you would expect the result to be `5`:

```
open System.Threading.Tasks
let failInTask () : Task<int> = task { return (raise (System.Exception("exception"))) }

let mainRaises () : Task<int> =
  task {
    let! result =
      try
        failInTask ()
      with
      | _ -> Task.FromResult 5
    return result
  }
mainRaises() // Raises an exception 
```

However, the `try` does not actually catch the exception. You need to do this instead:

```
open System.Threading.Tasks

let mainDoesntRaise () : Task<int> =
  task {
    let! result =
      task {
        try
          return! failInTask ()
        with
        | _ -> return 5
      }
    return result
  }

mainDoesntRaise () // Here you'll actually get 5
```

I propose we warn when a `try` block returns a task in which it will not catch an exception raised.

## Pros and Cons 

The advantages of adding a warning is that it's a very easy mistake to make and a very difficult mistake to understand.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

XS - check a syntax construct and a type, feels very doable.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
I suppose this is a request for analysis of things that cannot throw an exception, leading to a code suggestion on `try cannotFail() with _ -> ()` that `cannotFail() cannot throw an exception so this code simplifies to cannotFail()`?

That ideally depends on https://github.com/fsharp/fslang-design/blob/main/tooling/FST-1033-analyzers.md and should be very doable if restricted to very simple things (like creating a task) where it only needs to look at the first level of the expression tree.

**Comment by pbiggar** [comment]
> I suppose this is a request for analysis of things that cannot throw an exception, leading to a code suggestion on `try cannotFail() with _ -> ()` that `cannotFail() cannot throw an exception so this code simplifies to cannotFail()`?

I might be wrong but this doesn't seem to match the description.

 
> That ideally depends on https://github.com/fsharp/fslang-design/blob/main/tooling/FST-1033-analyzers.md and should be very doable if restricted to very simple things (like creating a task) where it only needs to look at the first level of the expression tree.

I suppose the difference is that what you're describing is an XXL project while the warning I described above is XS-sized.

**Comment by smoothdeveloper** [comment]
I am a bit remote from the details around task and how the exception may propagate, the behaviour feels it goes a bit against "principle of least surprise" from "code with issue" and "fixed code" standpoint.

I assume sadly, it would be breaking change if the initial code would be to do what the second does, but I'd like to better understand the underpinnings.

Regarding the overall request for warnings, I don't know how much a headache it can be deterministically matched against the untyped AST, in case it applies to any CE, but it requires the typechecked output if it is to be applying to the `task` CE that ships in FSharp.Core.

@pbiggar FYI, AFAIU the analysers framework has been shipping and is used in ionide (it may be convenient route, and you can integrate it with command line for CI as well), I think it will make a come back in more tooling once work in FCS is undertaken and the API is likely to be inspired from it, once it becomes supported feature of FCS.

If you've played with FCS, and figure out a pattern to identify the faulty code, it is mostly what it boils down to, whether it becomes an analyser or a warning right in F# compiler / tooling later on.

**Comment by charlesroddie** [comment]
> I might be wrong but this doesn't seem to match the description.

> I propose we warn when a try block returns a task in which it will not catch an exception raised.

Well the description doesn't work as worded as @bartelink noted, since it would also warn on the perfectly good code:

```fsharp
open System.Threading.Tasks
let failOutsideTask () : Task<int> =
    raise (System.Exception("exception"))
    task { return 0 }

let mainRaises () : Task<int> =
  task {
    let! result =
      try
        failOutsideTask ()
      with
      | _ -> Task.FromResult 5
    return result
  }
```

**Comment by Tarmil** [comment]
@charlesroddie Is that something anyone ever needs? Catching exceptions in the preparation of a task but not in the task itself? And even if you do, the code still looks like it's intended to catch exceptions in the task, and would benefit from being more explicit about what is actually caught.

I'm not sure about a warning, but at least a lint on `let! x = try` in CEs would make sense IMO.

**Comment by dsyme** [comment]
It's an interesting and subtle case.  Hard to see where the warning or lint should be though - perhaps on `task { ... taskExpr... }` instead of `task { ... return! taskExpr ... }` .

Or perhaps on use of any control syntax on right of `let! v = ...`

**Comment by dsyme** [comment]
I'll close this for the reasons above.
