### ISSUE TITLE
Allow undentaion of patterns when match expression is on binding line

### ISSUE THREAD

**Issue by bisen2** [fsharp/fslang-suggestions#1128]
# Allow undentaion of patterns when match expression is on binding line

I propose we allow patterns to be indented only one level past the binding when the match begins on the same line as the binding. For example, this function currently does not compile but would with this suggestion:
```fs
let f1 xs = match xs with // Error FS3118: Incomplete value or function definition
    | [] -> () // Warning FS0058: Possible incorrect indentation
    | _ -> () // Warning FS0058: Possible incorrect indentation
    0 // Error FS0010: Unxpected integer literal in binding
```

The existing way of approaching this problem in F# is to indent the patterns to the same position as the `match` keyword or to move the `match` keyword to a new line
```fs
// Indentation level is sensitive to name changes
let f2 xs = match xs with
            | [] -> ()
            | _ -> ()
            0
// Requires a new line
let f3 xs =
    match xs with
    | [] -> ()
    | _ -> ()
    0
```

## Pros and Cons 

The advantages of making this adjustment to F# are that it removes a common stumbling block for people learning the language.

The disadvantages of making this adjustment to F# are ...

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: This suggestion is similar in spirit to those collected in [RFC FS-1108](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1108-undentation-frenzy.md)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
I think this is a good change -- my hope is that some day automatic code formatting with make issues like this go away, but in the meantime there should be no surprises.

**Comment by charlesroddie** [comment]
Newline is better. In any situation with `let f(x) = code...`, `code` should create an offside rule (or, if one isn't possible because of backwards compat, an analyzer warning).

**Comment by dsyme** [comment]
I agree with @charlesroddie here

In general we won't add new undentations for code that doesn't follow the style guidelines (using multiline `match` on same line as `let` doesn't follow the guidelines)

**Comment by dsyme** [comment]
Closing out for reason mentioned above.
