### ISSUE TITLE
Introduce `???` as a shortcut for `raise (NotImplementedException())`

### ISSUE THREAD

**Issue by Swoorup** [fsharp/fslang-suggestions#1132]
# Title of Suggestion

I propose we introduce `???` as a placeholder for `raise <| NotImplementedException()`

The existing way of approaching this problem in F# is using `raise <| NotImplementedException()`

## Pros and Cons 

The advantages of making this adjustment to F# are:

* Faster prototyping. 
* Encouraging consistency around not implemented codepaths.

The disadvantages of making this adjustment to F# are 

* Yet one more way to do the same thing.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: 
* Got this inspiration from Scala

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by bartelink** [comment]
Have you considered `failwith "TODO"` or perhaps some helper like `let notImpl () = raise <| NotImplementedException()`, or perhaps some other trick leaning on `op_implicit` to trigger a throw.
(I don't object to the general concept of such a placeholder, but having baroque syntax such as `???` feels about as elegant as having a `!!` operator IMO)

**Comment by Happypig375** [comment]
```fs
open System
type A =
    static member (!!!) = raise (NotImplementedException())
open type A

let a: int = (!!!)
```

**Comment by dsyme** [comment]
Other suggestions that have cropped up over the years:
```fsharp
let nyi<'T> : 'T = raise (System.NotImplementedException())
let ugh<'T> : 'T = raise (System.NotImplementedException())
let lol<'T> : 'T = raise (System.NotImplementedException())

let f1() : int = nyi
let f2() : int = ugh
let f3() : int = lol
```

**Comment by xperiandri** [comment]
Let's force int to C# first 😄

**Comment by dsyme** [comment]
Closing as we're not going to specifically add any of these, especially as they are one line helper functions, and quite instructive for the user to write.
