### ISSUE TITLE
Support for TypeProvider nested types with static parameters

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#114]
**Submitted by Jason Kleban on 6/2/2016 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

Please support TypeProviders providing nested types with static parameters. This would be valuable for metaprogramming similar to how static parameterized method support is valuable compared to the language without them. It would allow a fluent-like construction of types and partially make up for the non-variable length static parameters on a single type. See https://github.com/fsharp/FSharpLangDesign/issues/88

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/14558223)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-14558223-support-for-typeprovider-nested-types-with-static.md#comments)

**Comment by dsyme** [comment]
Closing this old suggestion.  Support for provided methods with static parameters is related to this and was added in F# 4.0
