### ISSUE TITLE
Why doesn't the F# language have the `Either` type?

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1141]
Why doesn't the F# language have the Either type, 

```F#
type Either<'a,'b> =
    | Left of 'a
    | Right of 'b
```

Are there another alternative way to it?

**Comment by TheJayMann** [comment]
F# core library does not have a type explicitly called `Either`, with members named `Left` and `Right`, it does have essentially the same functionality in the type `Choice`, with the members `Choice1Of2` and `Choice2Of2`, as well as other versions of the `Choice` type that allow up to seven different choices.

Also, given that in other languages which use `Either` type typically use it for error handling, where one choice is used for the desired result, and the other is used for the error result, F# has a more semantically named type called `Result`, with an `Ok` choice, and an `Error` choice.

**Comment by RonaldSchlenker** [comment]
This is not a suggestion, but a question, and a better place for this might be stackoverflow or similar places.

**Comment by cartermp** [comment]
Will close, since this is more of a Q&A type deal.
