### ISSUE TITLE
Add Active Patterns for doing String Comparison

### ISSUE THREAD

**Issue by michaeloyer** [fsharp/fslang-suggestions#1148]
# Title of Suggestion

I propose we add Active Patterns for the String Comparers in the `System.StringComparer` class to the F# BCL.

```
open System

// IgnoreCase default, just name it InvariantCultureIgnoreCase or use CurrentCultureIgnoreCase instead?
[<return:Struct>]
let (|IgnoreCase|_|) compareTo input = 
    if StringComparer.InvariantCultureIgnoreCase.Equals(input, compareTo) then
        ValueSome input 
    else
        ValueNone

[<return:Struct>]
let (|CurrentCultureIgnoreCase|_|) compareTo input = 
    if StringComparer.CurrentCultureIgnoreCase.Equals(input, compareTo) then
        ValueSome input 
    else
        ValueNone

// Additional Active Patterns for OriginalIgnoreCase, InvariantCulture, CurrentCulture, and Ordinal

match "SomeText" with
| IgnoreCase "sometext" text -> $"Case ignored, original casing: {text}"
| _ -> "Not a match"

// val it: string = "Case ignored, original casing: SomeText"
```

The existing way of approaching this problem in F# using string comparisons outside of `match` expressions.

## Pros and Cons 

The advantages of making this adjustment to F# are 
* Having a native way for comparing strings in `match` expressions
* Use of `return:Struct` make this very cheap to use

The disadvantages of making this adjustment to F# are 
* Heavier use of Active Patterns which gets away from simple F#
* Adding additional BCL functionality just for the sake of convenience rather than new features.

## Extra information

I can't decide if it's worth having ValueSome return the input text or not. On one hand it's not strictly necessary, on the other in some cases it could be nice to have if you use the `function` keyword or you put some form of expression between `match ... with`.

The `IgnoreCase` Active Pattern looks nice, but is pretty ambiguous which comparer you may be using, so may not be overall worth having.

Estimated cost (XS, S, M, L, XL, XXL):  XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ x ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ x ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x ] This is not a breaking change to the F# language design
* [ x ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
These can be written by the user very easily, so won't go in the standard library.

Users who will be able to find and understand these will always be advanced enough that they can write the active pattern easily enough in their own code.

**Comment by dsyme** [comment]
Closing as we won't add these to FSharp.Core

**Comment by michaeloyer** [comment]
Ah, that is a shame. I think the reasons for closing are sensible. I have a some counter points to those reasons why I think this suggestion would still be worth considering. I'm happy to make those points, but I'd rather save everyone the time if you are 100% against the idea. Either way thank you for taking the time to respond to this suggestion.
