### ISSUE TITLE
kprintf with delayed string construction

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#116]
# kprintf with delayed string construction [14750064] #

**Submitted by mk on 6/8/2016 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

Currently kprintf and friends take in a continuation function and a StringFormat and return a curried function that when applied builds the string.
It would be nice for logging frameworks to have an overload where the continuation does not build the string rather provides a delayed function to build the string.
That way I can do something like:
let public logWithFormat logLevel logFormat =
kprintf (fun stringBuilder -> if logLevel > currentLoggingLevel then sprintf "%s" (stringBuilder())) logFormat

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/14750064)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-14750064-kprintf-with-delayed-string-construction.md#comments)

**Comment by dsyme** [comment]
Closing as this seems too corner-case, and could be done in a library (since printf is really just a library)
