### ISSUE TITLE
Shorter single Union Case syntax

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1164]
Single union cases are common to distinguish basic types from domain-specific types.  So, I would like to propose a syntax to not repeat the type name and the type constructor if they are the same

So:

```fsharp 
type PersonId of Guid
```
as same as 

```fsharp
type PersonId =  PersonId of Guid
```

## Pros and Cons 

The advantages of making this adjustment to F# are removing a bit of repetition

The disadvantages of making this adjustment to F# is to have a other way to define type

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 🤷🏾

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by bartelink** [comment]
>closed this as completed

@cartermp There's been recent meticulous re-closing of issues in this repo - suggest changing the close reason to duplicate to align with that...

**Comment by cartermp** [comment]
I added a duplicate label. There's no way to close an issue as a duplicate with the UI, so the label's the best we have here.

**Comment by bartelink** [comment]
Was more referring to avoiding closing it with an outcome of `completed` when that wasn't the outcome. I'm not sure what the exact dividing line is between `not-planned` or other classifications is though e.g. 1082 1118

(There was a flurry of notifications based on Don doing a pile of similar reclassifications a few weeks back).
