### ISSUE TITLE
Support mixed F# and C# projects in order to extend F# usage

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#117]
# Support mixed F# and C# projects in order to extend F# usage [14795655] #

**Submitted by zjv on 6/13/2016 12:00:00 AM**  
**121 votes on UserVoice prior to migration**  

Support mixing F# and C# source files in the same project in order to support a gradual move to F# for new users/organisations and to support cases where tooling is oriented at C# (F# not supported)
For instance I could use this feature to slowly move a C# project to F# one class at the time. Another example would be to use C# tooling to generate web infrastructure like ASP.NET 5 controllers (because F# does not currently have templates for this) and then call directly into F# from those.
P.S. Other languages that F# compares to like Scala already supported mixed projects

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/14795655)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-14795655-support-mixed-f-and-c-projects-in-order-to-exte.md#comments)

**Comment by dsyme** [comment]
This is a tooling suggestion, it is out of scope for the language design itself
