### ISSUE TITLE
Is it possible to add an operator to the core library that apply a function for each case of the `DU` 

### ISSUE THREAD

**Issue by GratianPlume** [fsharp/fslang-suggestions#1178]
I have some code like following:
```fsharp
   type Hero =
      | AH
      | GM
      | NT
      member inline this.Conver x =
         match this with
         | AH -> x &&& 1 <<< 2
         | GM 
         | NT -> x ||| ~~~(1 <<< 2)

      member inline this.Multiple x =
         match this with
         | AH 
         | GM -> x * 5
         | NT -> x * 7


   let foo x (h: Hero) = h.Conver x + h.Multiple x
```
foo function will not be optimized.
it compiles to (display as C#):
```c#
public static int foo(int x, Hero h)
{
	int num;
	switch (h.Tag)
	{
	default:
		num = (x & 1) << 2;
		break;
	case 1:
	case 2:
		num = x | -5;
		break;
	}
	return num + h.Tag switch
	{
		2 => x * 7, 
		_ => x * 5, 
	};
}
```
and then I add an `Isolate` method to `Hero`, let each case of `Hero` go their separate ways. All codes are as follows:

```f#
   type Hero =
      | AH
      | GM
      | NT
      member inline this.Conver x =
         match this with
         | AH -> x &&& 1 <<< 2
         | GM 
         | NT -> x ||| ~~~(1 <<< 2)

      member inline this.Multiple x =
         match this with
         | AH 
         | GM -> x * 5
         | NT -> x * 7

      member inline this.Isolate([<InlineIfLambda>]cont) =
         match this with
         | AH -> cont AH
         | GM -> cont GM
         | NT -> cont NT

   let inline foo x (h: Hero) = h.Conver x + h.Multiple x

   let foo2 x (h: Hero)  = h.Isolate (foo x)
```
Among them, the foo2 function gets the ultimate optimization, it compiles to (display as C#):
```c#
public static int foo2(int x, Hero h)
{
	return h.Tag switch
	{
		1 => (x | -5) + x * 5, 
		2 => (x | -5) + x * 7, 
		_ => ((x & 1) << 2) + x * 5, 
	};
}
```
I think this is a good paradigm for optimizing the application of function composition for distinguishable union types(and boolean),
 but writing the `Isolate` method is tedious, and will obviously increase the amount of user code in the compiled result.

So I hope F# provides a standard operator to apply a function separately for each case of `DU`

## Pros and Cons 

The advantages of making this adjustment to F# are ...
Provides an optimized guidance and support

The disadvantages of making this adjustment to F# are ...
No disadvantages

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by LyndonGingerich** [comment]
Why an operator rather than a library function?

Did you know that you can make your own operator? For example:
```F#
let (<*>) du f = du.Isolate f
let foo f x h = h <*> f x
```

**Comment by LyndonGingerich** [comment]
Do people often want to optimize performance of combining matches on a DU? I doubt it's worth an addition to the core library. Have you thought of publishing your own library?

**Comment by RonaldSchlenker** [comment]
I find it hard to give an apropriate answer to the proposal, because
* there is nothing proposed
* there is no question asked (if it would be a question, the "discussion" section would be the place to go)
* the example is not understandable

Here are some thoughts that might help:

1. The `isolate` method does nothing useful. It is redundant and can be removed.

2. For clearing things up, it could help to not use instance members, but just use simple functions over data. In this case:

```fsharp
type Hero =
    | AH
    | GM
    | NT

module Hero =
    let convert x =
        function
        | AH -> x &&& 1 <<< 2
        | GM 
        | NT -> x ||| ~~~(1 <<< 2)

    let multiple x =
        function
        | AH
        | GM -> x * 5
        | NT -> x * 7

let foo x h = Hero.convert x h + Hero.multiple x h
let foo2 x h = foo x h
```

3. This is very general, but might help: DUs should be used when there is a well-known set of distinct cases, where "distinct" means that each case must be treated in a different way from a usage perspective. If, from a usage perspective, the cases don't matter, that object polymorphism might be the tool of choice (means: in C#/F#, use an interface or abstract class to abstract the API from the implementation).

**Comment by voronoipotato** [comment]
Yeah I also don't think we should be blindly encouraging tight coupling between behaviors and data. It's what leads to a lot of pain when it comes time to test or augment existing code. It's definitely not free and in my opinion should be done only when the advantages clearly outweigh the pain.

**Comment by GratianPlume** [comment]
> Why an operator rather than a library function?
> 
> Did you know that you can make your own operator? For example:
> 
> ```fsharp
> let (<*>) du f = du.Isolate f
> let foo2 f x h = h <*> f x
> ```

I mean, the user does not need to implement the Isolate method manually, the compiler automatically provides

**Comment by GratianPlume** [comment]
> 3. This is very general, but might help: DUs should be used when there is a well-known set of distinct cases, where "distinct" means that each case must be treated in a different way from a usage perspective. If, from a usage perspective, the cases don't matter, that object polymorphism might be the tool of choice (means: in C#/F#, use an interface or abstract class to abstract the API from the implementation).

I think my approach is precisely to keep the polymorphic interface while optimizing the internals

**Comment by RonaldSchlenker** [comment]
> Is it possible to add an operator to the core library that apply a function for each case of the DU

The key point is to understand that the mentioned „operator“ is completely redundant - it’s in the end just function application. There is no need to match each case and pass each case to a function, because that function gets a ‚Hero‘ - and has to match the cases itself.

**Comment by GratianPlume** [comment]
> > Is it possible to add an operator to the core library that apply a function for each case of the DU
> 
> The key point is to understand that the mentioned „operator“ is completely redundant - it’s in the end just function application. There is no need to match each case and pass each case to a function, because that function gets a ‚Hero‘ - and has to match the cases itself.

No, it's needed. It causes the branches of a non-inlined function to generate refined code.
What I want the operator to achieve is to collect the optimization results for each branch

**Comment by RonaldSchlenker** [comment]
So, this suggestion is about 

1. the inlining strategy of the compiler, and
2. the only purpose of the proposed operator is for providing more control of the inlining process to the programmer?

I was so free and create [this GIST](https://gist.github.com/RonaldSchlenker/b47c8195e7800370e071e5c8a3978af8#file-test-fs) from your code, just for playing with it. It's not necessary having instance members. It's possible to just have module functions, and using the "isolate"-trick to tweak inlining.

I can't tell the reason why the compiler inlins in case of "isolate", and not in a generalized case. Maybe it's just a coincidence of whatever criteria met or not met; I don't know the internals of the compiler.

If there's a need to specify a hint for the compiler to run a more aggressive inlining strategy, IMHO an operator might not be a good solution. An attribute or a compiler switch might be better.

**Comment by LyndonGingerich** [comment]
> I mean, the user does not need to implement the Isolate method manually, the compiler automatically provides

I know that's what you are suggesting. I'm suggesting that this optimization is not worth an addition to the API. I don't think that everyone would want to use an operator like that. They might also want an operator with the same symbols to mean something else. If it's added to the core libraries, everyone has to know about it whether they use it or not. If it's published with another library or left for the user to define, those who wish can use it and those who don't can ignore it.

> If there's a need to specify a hint for the compiler to run a more aggressive inlining strategy, IMHO an operator might not be a good solution. An attribute or a compiler switch might be better.

I like this idea. When users want to increase performance using language features, they will probably check the attributes before the operators.

**Comment by cartermp** [comment]
@GratianPlume Do you have an example where there's a real-world performance gain for your solution? I ask because even though the use of `InlineIfLambda` does inline the operation, it doesn't necessarily mean better performance on the .NET runtime. The JIT may inline certain things, making any up-front inlining the compiler does moot.

**Comment by GratianPlume** [comment]
> @GratianPlume Do you have an example where there's a real-world performance gain for your solution? I ask because even though the use of `InlineIfLambda` does inline the operation, it doesn't necessarily mean better performance on the .NET runtime. The JIT may inline certain things, making any up-front inlining the compiler does moot.
> 
> (I suspect there is a performance gain since it's one less `switch` in decompiled C# code, but decompiled C# code <> compiled IL)

```
   type Hero =
      | AH
      | GM
      | NT
      member inline this.Conver x =
         match this with
         | AH -> x &&& 1 <<< 2
         | GM 
         | NT -> x ||| ~~~(1 <<< 2)

      member inline this.Multiple x =
         match this with
         | AH 
         | GM -> x * 5
         | NT -> x * 7

      member inline this.Isolate([<InlineIfLambda>]cont) =
         match this with
         | AH -> cont AH
         | GM -> cont GM
         | NT -> cont NT

   let inline foo x (h: Hero) = h.Conver x + h.Multiple x

   [<Struct; IsReadOnly>]
   type Hero2 =
      | AH
      | GM
      | NT
      member inline this.Conver x =
         match this with
         | AH -> x &&& 1 <<< 2
         | GM 
         | NT -> x ||| ~~~(1 <<< 2)

      member inline this.Multiple x =
         match this with
         | AH 
         | GM -> x * 5
         | NT -> x * 7

   let inline foo3 x (h: Hero2) = h.Conver x + h.Multiple x

   type Test() =
      
      let heros =[|Hero.AH; Hero.GM; Hero.NT|]
      let hero2s =[|Hero2.AH; Hero2.GM; Hero2.NT|]

      [<Benchmark>]
      member __.FooForIsolate () =
         let mutable result = 0
         for x in 0 .. 9999999 do 
            for y in heros do
               result <- result + y.Isolate (foo x)
         result

      [<Benchmark>]
      member __.FooForStruct () =
         let mutable result = 0
         for x in 0 .. 9999999 do 
            for y in hero2s do
               result <- result + foo3 x y
         result

      [<Benchmark>]
      member __.FooForStandard () =
         let mutable result = 0
         for x in 0 .. 9999999 do 
            for y in heros do
               result <- result + foo x y
         result
```
![75VY$L{Q{99DYL$5XL_~S E](https://user-images.githubusercontent.com/5526875/194532519-6e4c9a37-27a1-4874-915b-7127d1c3d6fe.png)

**Comment by GratianPlume** [comment]
> Is this suggestion about
> 
> 1. the inlining strategy of the compiler, and
> 2. the only purpose of the proposed operator is for providing more control of the inlining process to the programmer?
> 
> I was so free and create [this GIST](https://gist.github.com/RonaldSchlenker/b47c8195e7800370e071e5c8a3978af8#file-test-fs) from your code, just for playing with it. It's not necessary having instance members. It's possible to just have module functions, and using the "isolate"-trick to tweak inlining.
> 
> I can't tell the reason why the compiler inlins in case of "isolate", and not in a generalized case. Maybe it's just a coincidence of whatever criteria met or not met; I don't know the internals of the compiler.
> 
> If there's a need to specify a hint for the compiler to run a more aggressive inlining strategy, IMHO an operator might not be a good solution. An attribute or a compiler switch might be better.

It feels that the granularity is too coarse, whether it use compiler parameters or attributes. It is not conducive to the user to fine-tune control.

For example, in some expressions, it is obviously impossible to optimize some variables after expansion, and the user does not want to expand the implementation. But some other variables in the expression need to be expanded.

**Comment by dsyme** [comment]
@GratianPlume `Isolate` is a facinating performance trick using `InlineIfLambda` - it's like `Smash into Cases and Optimize for each` , impressive burn🔥🔥 

However that said I don't see us defining it by default for DUs - there's a huge variety of generic code that can be auto-generated over DUs and the need would be endless.   Even comparison/equality/hash is wild enough to bake into the language and a cause of never-ending niggles. 

I guess today we'd recommend using a code generation tool.
