### ISSUE TITLE
 `=$`, `=+`, `=-` not convenient 

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1179]
I propose we ... 
It's not convenient to follow an equal sign with some symbols Especially **unary operators**.
```f#
let a = {|w=$"";x=+1;y=-1|}
Assert.True(-1=-1)
```
Two consecutive symbols `=$`, `=+`, `=-` will be considered as one operator. It is recommended to delete these unary operators to avoid counterintuitive.

The existing way of approaching this problem in F# is to split by spaces.
```f#
let a = {|w= $"";x= +1;y= -1|}
Assert.True(-1= -1)
```

## Pros and Cons 

The advantages of making this adjustment to F# are ...

The disadvantages of making this adjustment to F# are ...

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
It is unfortunate that = is allowed to start an operator, for this reason. However we are stuck with it, and the best improvement from here would be to add "Perhaps you are missing a space." to the error message.

**Comment by charlesroddie** [comment]
It is unfortunate that = is allowed to start an operator, for this reason. However we are stuck with it, and the best improvement from here would be to add "Perhaps you are missing a space." to the error message. This can be added whenever the "undefined operator" string starts with a defined operator.

**Comment by LyndonGingerich** [comment]
This is a breaking change for anyone who has defined an operator starting with `=`.

**Comment by xp44mm** [comment]
As long as the equal sign is not followed by a unary operator, most problems can be avoided. For example, binary operators `==`, `=&`, `=@` will not have any problems.

**Comment by Happypig375** [comment]
@xp44mm `&` can also be a unary operator. It takes a variable by reference, converting it to a `byref<'T>`.

**Comment by LyndonGingerich** [comment]
> As long as the equal sign is not followed by a unary operator, most problems can be avoided. For example, the equal sign is followed by binary operators `==`, `=&`, `=@` will not have any problems.

Fair, but that's still four too many breaking changes.

**Comment by xp44mm** [comment]
@Happypig375 Nevertheless, it is possible as long as the unary operator is not syntactically preceded by an equal sign `=`.

**Comment by abelbraaksma** [comment]
> The existing way of approaching this problem in F# is to split by spaces.

True. The existing way is that operators *must* be separated by spaces. Apart from improving error messages there’s nothing that can be done here. Check the F# spec for why this is necessary to allow deterministic tokenization.

**Comment by cartermp** [comment]
I think we can consider this just a compiler error shortcoming and file it over in https://github.com/dotnet/fsharp

It is unfortunate that this declaration:

```fsharp
let a = {|w=$"";x=1;y=1|}
```

Produces these errors:

```
error FS0035: This construct is deprecated: '$' is not permitted as a character in operator names and is reserved for future use
error FS0010: Unexpected infix operator in binding
error FS0605: Unmatched '{|'
error FS0010: Unexpected symbol '|}' in binding. Expected incomplete structured construct at or before this point or other token.
error FS0035: This construct is deprecated: '$' is not permitted as a character in operator names and is reserved for future use
error FS0010: Unexpected infix operator in binding
error FS0605: Unmatched '{|'
error FS0010: Unexpected symbol '|}' in binding. Expected incomplete structured construct at or before this point or other token.
```

And that should probably be improved.
