### ISSUE TITLE
Warning FS0035 on access of DU case defined with RequireQualifiedAccess in opened module of same name

### ISSUE THREAD

**Issue by LyndonGingerich** [fsharp/fslang-suggestions#1180]
I would like to be able to use the following code without warnings:

```F#
module Foo =
  [<RequireQualifiedAccess>]
  type Foo =
    | Bar
    | Baz

open Foo // Open directive is not required by the code and can be safely removed
let x = Foo.Bar // This construct is deprecated: The union type for union case 'Bar' was defined with the RequireQualifiedAccessAttribute. Include the name of the union type ('Foo') in the name you are using.
```

Apparently, the compiler sees the qualifier `Foo` as referring to the module, despite the module already having been opened.

It seems intuitive to me that the `open` should open the module, then the qualifier refer to the type name. I suggest that the compiler be modified to work this way. (An affirmation that the current behavior is intended would also suffice.)

I can workaround by creating case aliases, but they seem to me like ugly, needless boilerplate, so I don't wish to use them.

## Pros and Cons 

The advantages of making this adjustment to F# are:
- Easier use of `RequireQualifiedAccess`

The disadvantages of making this adjustment to F# are:
- Unknown. I don't think this could break anyone's code.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
The suggestion has merit theoretically, but a better solution would be to recommend that types or module do not have the same names as enclosing types or modules. C# seems to have this restriction and it's good.

> I would like to be able to use the following code without warnings:

Do you have a reason for doing that, aside from testing the consistency of the compiler? Wouldn't deleting `module Foo =` improve the code?

**Comment by LyndonGingerich** [comment]
> Wouldn't deleting `module Foo =` improve the code?

Often, such modules are the files that hold the types. I tend to name each file after the primary data type it holds. Why is this a bad idea?

**Comment by LyndonGingerich** [comment]
The use of `[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]` on the containing module does not successfully work around the issue.

**Comment by charlesroddie** [comment]
> Often, such modules are the files that hold the types. I tend to name each file (and file-level module) after the primary data type it holds. Why is this a bad idea?

It's getting into workaround territory, but you can use a `namespace Foo` at the file-level, with an inner module (outside the type) if you need any direct let bindings. Does that work?

**Comment by LyndonGingerich** [comment]
> It's getting into workaround territory, but you can use a namespace Foo at the file-level, with an inner module (outside the type) if you need any direct let bindings. Does that work?

I don't think it's worth that much restructuring to me.

**Comment by jl0pd** [comment]
It doesn't make life easier not for developer, nor for consumer. Can you explain why this pattern is better than following?

```fsharp
namespace MyNamespace.Models

type MyModel = ...

module MyModel =
    let create x y z = ...
    let doThing model = ...
```

> I don't think it's worth that much restructuring to me.

But it worth to change language.

**Comment by LyndonGingerich** [comment]
> Can you explain why this pattern is better than following?

I just want to use the language's intended default behavior. If I have
```F#
[<RequireQualifiedAccess>]
type Foo =
  | Bar of int
```
, then I should be able to write `Foo.Bar 1` anywhere I can access the type. I shouldn't have to use helpers, either like the workaround in my original post or like your suggestion.

**Comment by LyndonGingerich** [comment]
@jl0pd I think you may have misread my original post. I'll edit it and try to make it clearer.

**Comment by LyndonGingerich** [comment]
Regardless of whether modules should be named after their primary types, compilation should not break arbitrarily and unintentionally when a developer does so. I don't think that this behavior was intended by the F# language designers. It could easily confuse newbies and it forces workarounds for a legitimate coding pattern.

**Comment by cartermp** [comment]
I will consider this to be a part of https://github.com/fsharp/fslang-suggestions/issues/907

It will need to be considered for any design of the feature.
