### ISSUE TITLE
Allow static let bindings in union, record, struct, non-incremental-class types

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#1182]
I propose we allow `static let` bindings in a wider range of type definitions:

```fsharp
type T =
    static let f _ = ()

type AB = 
    | A
    | B of int
    static let b0 = B 0
    static let b1 = B 1
    static member B0 = b0
    static member B1 = b1
```

Currently `static let` bindings are only allowed in types with incremental constructors.  This restriction makes sense for `let` bindings but not `static let` bindings.  They should be allowed in all nominal type definitions including stucts etc. 

There are many situations where this results in an artificial need for a module or class-type-holding-statics

## Pros and Cons 

The advantages of making this adjustment to F# are regularity, simplicity, fewer restrictions.

The disadvantages of making this adjustment to F# are needs to be implemented

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
I have done an implementation of this to prototype stage.  I will write the RFC

**Comment by Xyncgas** [comment]
Does this mean active pattern can be put in static member too

**Comment by edgarfgp** [comment]
This is done by https://github.com/dotnet/fsharp/pull/15343
