### ISSUE TITLE
Allow static members in interfaces

### ISSUE THREAD

**Issue by gusty** [fsharp/fslang-suggestions#1191]
I propose we allow static members in interfaces.
The CLR supports this, C# has this feature enabled since C# 8.0 and I see no reason why keep forbidding it in F#.

The existing way of approaching this problem in F# is inexistent, we have to code the interface in C#, however this approach has number of limitations, namely we can't add specific F# constructs to this interface.

## Pros and Cons 

The advantages of making this adjustment to F# are that we'll be able to declare static members in interfaces, which will be compiled as part of it, see https://jeremybytes.blogspot.com/2019/12/c-8-interfaces-static-members.html 

This will play well together with #1151 so well that I thought it was going to be part of it. Also it will be possible to have static constraints resolving to interface static methods (ie: factory methods), right now it works but the only way to code the interface is in C#.

The disadvantages of making this adjustment to F# are that it's work, but I don't think it's too much work, basically we'll have to remove the checks that prevents writing it and make sure it's properly generated.

## Extra information

Estimated cost XS: 

Related suggestions: #1151 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
Yes, this should be allowed

I guess the existing approach is to define static extension methods or a module of the same name

**Comment by abelbraaksma** [comment]
Great to hear that! @gusty, do you consider making an RFC for this? If so, can you link it here?

**Comment by gusty** [comment]
I [wrote it already[(https://github.com/fsharp/fslang-design/pull/709) just needs to be accepted and merged.

**Comment by dsyme** [comment]
Now we need an implementation :) RFC is here: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1128-allow-static-members-in-interfaces.md

**Comment by kerams** [comment]
This is done.

**Comment by gusty** [comment]
Thanks @kerams well done !

**Comment by jl0pd** [comment]
@bmitc, you need to use preview language version:
```fsharp
> dotnet fsi --langversion:preview

Microsoft (R) F# Interactive version 12.5.0.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> [<Interface>]
- type ITesting =
-     static member Testing x = x
- ;;
type ITesting =
  static member Testing: x: 'a -> 'a

>
```
