### ISSUE TITLE
nativeptr<'T> should support comparison

### ISSUE THREAD

**Issue by roboz0r** [fsharp/fslang-suggestions#1194]
Suggestion is to have `nativeptr<'T>` support `comparison`. Probably it should also support all other interfaces of [`nativeint`](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-7.0)

The current workaround is to cast `nativeptr<'T>` to `nativeint` when storing in e.g. a `Set`.

## Pros and Cons 

The advantages of making this adjustment to F# are you aren't required to throw away type information to store pointers in a collection. 

The disadvantages of making this adjustment to F# are it's work.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS or S?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
It seems that C# supports these out of the box, so I think it makes sense to support this. See: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators.

Though I think that many of the other interfaces may be problematic in F#, at least until we have a way to deal with all these static interfaces. Though I guess we could add a bunch of them in a functional way at least by extending the surface area of the `NativeInterop.NativePtr` functions? For instance, useful could be `NativePtr.incr` and `NativePtr.decr` and perhaps an `add` and `subtract` function that takes an `int`?

**Comment by roboz0r** [comment]
Probably this should be split into two parts. 

1. The [.NET 6 interfaces](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)
    - [IComparable](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable?view=net-6.0) 
    - [IComparable](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable-1?view=net-6.0)<[IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)> 
    - [IEquatable](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-6.0)<[IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)> 
    - [IFormattable](https://learn.microsoft.com/en-us/dotnet/api/system.iformattable?view=net-6.0)
    - [ISerializable](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=net-6.0) 
    - [ISpanFormattable](https://learn.microsoft.com/en-us/dotnet/api/system.ispanformattable?view=net-6.0)
2. The [.NET 7 interfaces](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-7.0)

**Comment by jl0pd** [comment]
Allowing `nativeptr<T>` to satisfy `comparison` constraint still won't allow it to be used inside `Set<T>` because pointers cannot be used as generic arguments (limitation of runtime, see ECMA-335 II.9.4)

**Comment by roboz0r** [comment]
@jl0pd This is very surprising to me as I'm running code right now which stores pointers in a `HashSet<nativeptr<myStruct>>`. A previous version of the code was also working with `Set<nativeint>`.

**Comment by jl0pd** [comment]
Surprisingly F# erases `nativeptr<T>` when it's used inside generic, but keeps pointer type when it's used as plain type:

```fsharp

// return type is HashSet<IntPtr>
let set () : System.Collections.Generic.HashSet<nativeptr<int>> = Unchecked.defaultof<_>

// return type is int*
let ptr () : nativeptr<int> = Unchecked.defaultof<_>
```

**Comment by abelbraaksma** [comment]
That looks like a bug to me. Having pointers in a collection seems wrong to me and extremely unstable. If pinned, it's gonna be disastrous, if not pinned even more so. They have no place in heap-allocated objects. If you do need them (let's say store some pointer to an unmanaged object) you can always store it as a native int.

**Comment by abelbraaksma** [comment]
> Probably this should be split into two parts.

Implementing the interfaces isn't going to be easy, as afaik, F# Core has to remain compatible with .NET Standard 2.0. And, unless I'm mistaken, these interfaces aren't available there, and there's strong reluctance to move to a multi-versioned F# Core.

_(I'm just repeating what I recall from a previous discussion a similar proposal I made myself, but things may have changed meanwhile)_

**Comment by vzarytovskii** [comment]
> Probably this should be split into two parts. 
> 
> 1. The [.NET 6 interfaces](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)
>     - [IComparable](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable?view=net-6.0) 
>     - [IComparable](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable-1?view=net-6.0)<[IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)> 
>     - [IEquatable](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-6.0)<[IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)> 
>     - [IFormattable](https://learn.microsoft.com/en-us/dotnet/api/system.iformattable?view=net-6.0)
>     - [ISerializable](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=net-6.0) 
>     - [ISpanFormattable](https://learn.microsoft.com/en-us/dotnet/api/system.ispanformattable?view=net-6.0)
> 2. The [.NET 7 interfaces](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-7.0)

We won't do it, likely, since we are targeting netstandard2.0

**Comment by roboz0r** [comment]
> We won't do it, likely, since we are targeting netstandard2.0 

Fair enough. I was mostly trying to avoid doing the cast and wasn't aware of all this background. I thought it would be a straight-forward addition.

> Having pointers in a collection seems wrong to me and extremely unstable.

My use case is to support [xlAsyncReturn](https://learn.microsoft.com/en-us/office/client-developer/excel/xlasyncreturn) via an unmanaged delegate. 

```
[<UnmanagedFunctionPointer(CallingConvention.StdCall)>]
type internal Excel12vDelegate = delegate of xlfn:int * count:int * ppOpers:nativeptr<nativeptr<xlOper12>> * pOperRes:nativeptr<xlOper12> -> xlRetCode
```

I'm keeping the pointers in a `HashSet` as Excel may cancel the computation at any time. My async code checks that the pointer is still in the `HashSet` before returning via the `delegate`. In this case the pointer originates from unmanaged memory but there is a mix of unmanaged and .NET pointers crossing that boundary. I'm making extensive use of pinned arrays so the heap doesn't get corrupted.

**Comment by roboz0r** [comment]
> capture it through closures

This is exactly what I'm doing. The consumer side interface reduces to `nativeptr<_> -> (Async<_> -> unit)`. It seems to be stable with 10k+ parallel calls so I'm going to call that good enough.

**Comment by dsyme** [comment]
Can you use `NativePtr.toNativeInt` and compare the integers?

**Comment by dsyme** [comment]
> The current workaround is to cast nativeptr<'T> to nativeint when storing in e.g. a Set.

I see, you've listed that workaround.  To me this is adequate.

**Comment by dsyme** [comment]
Closing this out as the workaround is adequate.
