### ISSUE TITLE
Stronger typing system

### ISSUE THREAD

**Issue by Xyncgas** [fsharp/fslang-suggestions#1196]
Can we please have something like this
```
module Implementations =
    module GroupA =
        let jobA model =
            Complexity : 2
            let : Operations :byte[] = GenerateRandomOperations()
            Apply <| Operations <| model
        let jobB source =
            Latency : GetRandomLatency()
            Map <| source
    module GroupB =
        let jobA model =
            Complexity : 3
            let : Operations :byte[] = GenerateRandomOperations()
            Apply <| Operations <| model
        let jobB source =
            Latency : GetRandomLatency()
            Map <| source

module Controler =
    type Mapper = Source -> Mapped
    type Transformer = Model -> Model
    let Job_A_B source model =
        let mapper :seq<Mapper>= Mapper <- (Implementations.GroupA * Implementations.GroupB)
        mapper |> Seq.MinBy(fun f -> f.Complexity) |> Seq.MinBy(fun f -> f.Operations)
        let transformer :seq<Transformer>= Transformer <- (Implementations.GroupA * Implementations.GroupB)
        transformer |> Seq.MinBy(fun f -> f.Latency)
        ((mapper <| source), (transformer <| model))
```
Build the function, run the function, continue building further.

In this example, there's two ways to write meta datas, one is in the notation of (MetaName : Value) the other way is (let : MetaDataName = Value). They are inter-exchangable ideally speaking, but I can see 'let :' is used for dynamic evaluations only. Meanwhile their values can be used in the function itself as shown

Which function to use is decided at compilation, if functions unchanged (unless it has dynamic meta data like 'Operations') we can build minimally, functions are the first class citizens.

**Comment by vzarytovskii** [comment]
I'm struggling to understand the actual suggestion here.

Could you please expand on it more?

**Comment by Xyncgas** [comment]
further considering If the meta datas appears to be in a loop, I think it should be evaluated dynamically.
regardless this is pretty cool

**Comment by Xyncgas** [comment]
> Could you please expand it a bit and add more higher lever description and more examples?

Yes sir.

If you look at line 23, it's something we don't have right now, it has an use of the operator (<-, ->) in combination of a group of modules that're grouped using the '*' operator, like other compose types but on modules

If you look at line 12, we have a variable being given a value through a (MetaData : Value) syntax, we don't have this now too

if you look at line 5, line 24, you see a variable is being given value not through (let a = b) but (let : a = b), we don't have this now, then we are able to see this value, because it's put into the meta data, therefore later we can select which function is less complex based on the operations that they have

All these things we don't have, is part of a stronger typing system, that I think we should have, the principle is doing these work still in compilation instead via .NET reflection, that's why I think we can't do (Operation : byte[]) only (let : Operation :byte[] = bytes) although we can. There're many more things to consider but all the obstacles might have a reasonable solution when we get to it and I think it's worth approaching to see a future of using F# in succinct, robust, and performant way.

Because this gotta be cool!

**Comment by Xyncgas** [comment]
This proposal makes the typing system stronger because it allows us to put & use more information with types, therefore influencing our logics during compilation

**Comment by dsyme** [comment]
@Xyncgas Thanks for the proposal. I'm also struggling to see the technical thing being suggested here, so I will close this, thanks.
