### ISSUE TITLE
Add `Dispose` method to `MailboxProcessor`

### ISSUE THREAD

**Issue by bmitc** [fsharp/fslang-suggestions#1198]
The `MailboxProcessor` class implements `IDisposable` but does not provide a `Dispose` method. To properly dispose of a `MailboxProcessor`, users need to cast such as this:

```fsharp
(mailboxProcessor :> IDisposable).Dispose()
```

I propose simply adding a `Dispose` method to `MailboxProcessor`.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

1. Better discovery. There are two ways to create a `MailbxoProcessor`.
    1. Directly using the constructor. For example,
       ```fsharp
       // Binding with `use`, `Dispose` will be called automatically
       use mailboxProcessor = new MailboxProcessor<unit>(fun inbox -> ...)

       // Binding with `let`, users need to manually call `Dispose` by doing the above mentioned cast
       let mailboxProcessor = new MailboxProcessor<unit>(fun inbox -> ...)
       ...
       (mailboxProcessor :> IDisposable).Dispose()
       ```
       Note that in these cases, F# will generate a warning if the `new` keyword is not used, which lets users know that `MailboxProcessor` implements `IDisposable`.

    2. Using the `Start` method:
       ```fsharp
       let mailboxProcessor = MailboxProcessor<Unit>.Start(fun inbox -> ...)
       ```
       In this case, there is no indication that `MailboxProcessor` implements `IDisposable` since a static method is used to create and start it. Adding a `Dispose` method to the class would provide a discoverability aspect since the method will be listed by intellisense.

2. More convenience. I don't like having to manually cast objects every time I just want them disposed. `MailboxProcessor`s are often created in situations where `use` can't be used, either when the `MailboxProcessor<_>.Start` method is used, or when a `MailboxProcessor` is created with a `let` binding in a class' constructor.

The disadvantages of making this adjustment to F# are ...

There are no downsides. This change would be completely backwards compatible with existing code since it only adds the following code to `MailboxProcessor`:

```fsharp
    member x.Dispose () =
        (x :> IDisposable).Dispose()
```

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

These are some related issues that address keeping the `new` keyword warning on constructors for `IDisposable` classes and asking how to dispose a `MailboxProcessor`.

* https://github.com/dotnet/fsharp/issues/7707
* https://github.com/fsharp/fslang-suggestions/issues/124

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

I could implement this with no problem.

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by bartelink** [comment]
Is there prior art on other things in FSharp.Control that implement IDisposable?

I did a quick search for BCL stuff and e.g. FileStream inherits from Stream, which has a public `Dispose()`, but there's also a `Close()` on that, so that's arguably a wart that should not be there. 

Putting a wart onto this type doesn't make sense unless there is significant prior art, so I'd like to see some more analysis on this before considering doing this as a one-off.

In the general case, Disposables tend to be handled via `use` et al and the associated ownership management conventions, so any solution should work equally for those others cases of IDisposable in either BCL or FSharp.Core things. 

The other thing that springs to mind is that anything that suggests/pushes toward manual lifecycle management is not necessarily a good thing (if autocomplete starts showing Dispose on MBP, then people might not even pause to consider using `use` and/or implementing Disposable in the container. I'd also bet that you'll meet places where the presence of an easy `Dispose` without a cast might lead to having code where Disposal that should be in a `finally` block gets overlooked.)

And a question if proceeding: Are there sibling types around MBP that should also have the same applied to them?

**Comment by debugnik** [comment]
@bartelink `Stream.Close` is the wart, as it existed before `IDisposable` and is now just a dummy intermediary in the usual [dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern). Almost all C#/VB.NET code implements `Dispose` as a public method, as well as most other interface methods, really; F#'s the odd one out without.

**Comment by bartelink** [comment]
>Almost all C#/[VB.NET](http://vb.net/) code implements Dispose ... as well as most other interface methods, really; F#'s the odd one out without implicit implementations or a shorthand.

@debugnik that may well be true, but an issue in this repo is much stronger and thus more actionable and likely to actually happen if it's had research done on it beyond people's gut feel, _with citations to justify that_. The ideal would be a survey of the BCL, `FSharp.Core` and/or `FSharp.Control` things.

The article you link _almost_ states that it's a requirement to also expose `Dispose()` as public. [CA1063: Implement IDisposable correctly](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063) is much more definitive. Based on that, It does appear that the interface is out of step with .NET conventions.

However I'd add the proviso that if this is going to happen for this single instance, it should happen on a more general basis - i.e. it should only be done if anything in `FSharp.Control` that implements `IDisposable` is going to gain the same treatment (with the possible exception of things that implement `IDisposable` for internal reasons foisted on them by some deprecated Component interfaces or stuff of that ilk). In other words, I'd still question doing this only for this case if that makes this the only `type` in `FSharp.Control` / `FSharp.Core` that has a public `Dispose()`.

I've only extremely rarely run into normal usage of stuff in `FSharp.Core` requiring an explicit `Dispose()`; by far the most common pattern in F# is yielding an `IDisposable` as a token as something with a lifetime is started [which is a less safe construct in a lang that doesn't require you to `ignore` return values you don't use].

In this case it does still seem that the correct general usage is to either:
1. `use` the result of the `MailboxProcessor.Start()` method
2. have something hold the reference to the MBP, and have that Dispose it as part of its lifetime management - in that case, having to do a cast to the interface is far less ugly as it's an implementation detail.

**Comment by bmitc** [comment]
As mentioned in the original post, it is very common to use a `MailboxProcessor` in scenarios in which `use` is not available.

* If you create and start with `MailboxProcessor.Start`, you cannot use `use` in any scenario. This is in fact so common that I didn't even realize `MailboxProcessor` implemented `IDisposable` until recently. Off the top of my head, I don't think it's disposed of correctly in many books and examples. It isn't in *Expert F# 4.0*, for example.
* It is often the case to wrap a `MailboxProcessor` with a class, as described in *Expert F# 4.0* on page 303. You usually construct the `MailboxProcessor` or call `MailboxProcessor.Start` in the class constructor. `use` bindings are not allowed here.
    ```fsharp
    type MailboxWrapper () =
        let mailbox = new MailboxProcessor(fun inbox -> ...)
    ```
    or
    ```fsharp
    type MailboxWrapper () =
        let mailbox = MailboxProcessor.Start(fun inbox -> ...)
    ```
    In the first and second cases, `use` cannot be used. In the first case, the warning encouraging the `new` keyword to be used is the only indication `MailboxProcessor` implements `IDisposable`. In the second case, which I would argue is more common, there is no indication `MailboxProcessor` implements `IDisposable`. Having a `Dispose` method would make this more clear, discoverable, and convenient.

It's for these reasons alone, again as stated in the original post, that I think it should be added. You can encourage automatic handling all you want, but the most common use cases of `MailboxProcessor` dictate that you cannot use automatic disposal. Furthermore, it's a trivial change with no backwards compatibility issue. I also believe it's common for .NET `IDisposable` types to implement `Dispose`. It is rare to need to cast to `IDisposable`, in my experience.

In terms of addressing this issue in other areas of the codebase, I think that's well beyond the scope of this suggested change.

**Comment by cartermp** [comment]
Note that the rarity you mention is just that F# doesn't do implicit interface implementations. MailboxProcessor already implements the IDisposable interface. That's why the cast works today. So this is really a, "should we expose the interface implementation implicitly" question.

**Comment by pblasucci** [comment]
Anecdotally, defining a small helper function (ex: `val inline dispose : #IDisposable -> unit`) has always worked very well for me. Though you do have to remember to call it 😅.

**Comment by bartelink** [comment]
Thanks for taking the time to be more explicit.

>use bindings are not allowed here.

I get that there is no `use` in a `type`, but as alluded to in my post, in that case you're on the hook for doing a proper impl of the Dispose pattern anyway.

>  `let mailbox = MailboxProcessor.Start`

I'd suggest that's a bad idea - you don't want an `Async.Start` (triggered internally by MBP.Start) as a side effect of constructing a wrapper

I agree that having `Start` return something that you're responsible for disposing is not very discoverable (in github.com/jet, `Start` methods only return an `IDisposable` to make that beyond obvious; in general if nothing is actually started, then a constructor is used, which triggers the normal warnings/thinking on the part of the user)

>Having a Dispose method would make this more clear, discoverable, and convenient.

I agree only with the convenient piece here. Relying on people to read the method list is about as reliable as assuming they'll read the implemented interfaces list (I'd argue that in general an experience dev will be on the lookout for IDisposable if there's a sense that a Task, handle or memory is involved)

>You can do this, but within a let binding block, but it is a rare use case I think.

Agreed. IME a more common case is to have a supervisor method (called Run, Pump, Handle, Execute etc) which starts lots of things and then waits for them to finish and maps the outcome to something useful. In some cases when doing that, you might have a `try`-`finally` to cover some messy cases where you might `Dispose()`s things explicitly. If I can't use `use _ = x.Start()` or similar to make that foolproof, I sometimes do
`use _ = { new IDisposable with member _.Dispose() = <custom logic> }`, (akin to the `defer` mechanism in some languages).

Mainstream cases where you'd `Dispose` proactively (as opposed to in exception paths), are cases where you want to release resources. For those, you'd need to do the cast (but you still want a `finally` or a `use` in the picture?)

In short, I still don't see the poster child common usage where the obvious best thing is to call `Dispose()` on the MBP.

>I also believe it's common for .NET IDisposable types to implement Dispose. It is rare to need to cast to IDisposable, in my experience.

I have no objection to public `Dispose`s going on Disposable things as part of following an established convention. But the high order bit is the IDisposable semantics and everything uniformly either having it or not having it, more than the presence of a public `Dispose` that you can call without a cast.

In other words, if the BCL has public Dispose in 99/100 cases, FSharp.Core has it in 0/20 cases, then having this issue move us from 1 to 20 is for me not worth doing given there's an established workaround (but the missing one in the BCL would be a no-brainer bugfix PR and/or is not possible based on the CA rule I cited.).

**Comment by bartelink** [comment]
>The idea is that the user of the class need not know that the class contains an underlying asynchronous process. 

My quibble is with a ctor doing `Async.Start` or equivalent - Stuff I'm aware of that do things like that have `Start` in the name of the method. No different to a ctor not opening a file - let it own the file handle, but have a method to trigger the effects.

Pushback re putting Dispose in one place you noticed is that it makes that inconsistent with everything else. `fslang-suggestions` is not about quick debate free bugfixes - you'd can file an issue on dotnet/fsharp for that and follow up with a PR the next day if nobody says "it's that way for a reason".

>There aren't any other types like MailboxProcessor in F#

I was thinking of Mailbox. But my point is that a bit more research is called for - there are not very many public Dispose methods in dotnet/fsharp, and there are a lot of IDisposable impls.

I'm not going to go further into to/fro on whether or not MBP or other things require or should require calling a public `Dispose` - you believe it's common; I've suggested that there are lots of ways in which one can avoid having explicit `Dispose` calls. I accept that they sometimes happen somewhere, but IME they are rare (and IMO should be rarer than they are).

>I would say that I have rarely seen MailboxProcessor actually disposed in examples. I would argue that not having a public Dispose and MailboxProcessor.Start being the common way to create and start them is the major reason why.

Bottom line is there are orthogonal concerns:
- how to Dispose when `use` isn't in play but you ended up with an MBP that you're unwilling/unable to cast
- figuring out it's even Disposable and that you own the instance yielded by `Start`. Arguably helped by people spotting that this [potentially single] type has a Dispose.
- managing lifetimes of the MBP and/or MB instances including correct teardown for a given app type and/or supervision structure

For me the clearest way for this to proceed is to attack the whole problem:-
0. the Dispose pattern mandates a `public Dispose()`; most F# stuff doesn't follow that (to be verified). All BCL stuff does (to be verified)
1. Fix that in the F# libs
2. Possibly provide clearer guidance in the MS docs and other materials about not forgetting to put in the `public Dispose`

If you're looking at the smaller scale problem and bothered by the broader discussions, the quicker solutions are:
1. use the workaround that everyone uses
2. log a bug in dotnet/fsharp and a PR to add it if nobody objects

I'll try to stop spamming now; I get your position. I won't lose sleep if the quick fix happens, but I believe special casing just this is as likely to do harm as good. And I'm delighted you've raised the issue and engaged in a constructive debate; I appreciate this probably just feels like a random person has decided to waste your time today ;)

**Comment by bmitc** [comment]
@bartelink `Mailbox` is not an exported/public type.

**Comment by dsyme** [comment]
I'm fine with an explicit Dispose in the public methods.

**Comment by bmitc** [comment]
This was implemented in https://github.com/dotnet/fsharp/pull/14929.
