### ISSUE TITLE
Unprioritized arithmetic operators

### ISSUE THREAD

**Issue by AvnonAsaf** [fsharp/fslang-suggestions#1199]
I propose to add a list of unprioritized arithmetic operators that are always evaluated from left to right.
My proposed operators should look and behave like the following code:

let inline ( |>+ ) a b = a + b
let inline ( |>- ) a b = a - b
let inline ( |>* ) a b = a * b 
let inline ( |>/ ) a b = a / b 

those operators would enable writing code like the following:
3
|>+ 5
|>* 2
|>/ 4
|>- 1
|> printfn "%i"

There are 2 existing ways of approaching this problem in F#:

1. If the order of the parameters to the operator doesn't matter,
we use the operator as a function and pipe the first value to it.
like this:
     value1 |> (*operator*)  value2

2. If the order of the parameters does matter we pipe the first parameter to an anonymous function that wraps the operator.
like this:
    value1 |> fun *variable* -> *variable* *operator* *value2*

## Pros and Cons 

The advantages of making this adjustment to F# are:

- It integrates very well with the beloved pipe operator, you can use the operator in the middle of a piped expression.
- It removes unnecessary anonymous functions and unnecessary naming.
- It is more succinct in both cases.
- It covers all use cases rather than only symmetrical arithmetic operators.

The disadvantages of making this adjustment to F# are more code in the standard library,
and that if a library is using one of the newly defined symbols it will might break their program.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
While I’ve entertained the idea in the past (and it can be useful), the operator precedence rules are clearly stated, which means such overloads can only be created without backward compat issues using those rules. Like using a leading`^` for instance, which is ugly, hence I don’t use these anymore.

**Comment by AvnonAsaf** [comment]
> While I’ve entertained the idea in the past (and it can be useful), the operator precedence rules are clearly stated, which means such overloads can only be created without backward compat issues using those rules. Like using a leading`^` for instance, which is ugly, hence I don’t use these anymore.

I don't think I anderstand the problem. from what I anderstad the precedence is determined by the first charecter in the operator (exept in a case of a dot), and in all of the operators I definde the first character is '|', so I don't anderstend whats wrong.
can you send an example in which the operators are not working as expected?

**Comment by cartermp** [comment]
So I think the answer here is likely to be a no, mostly since mathematical operator precedence is so well-understood and offering up a different way to chain together math operations will be so different from everything else. It's also much more verbose code.

**Comment by abelbraaksma** [comment]
@AvnonAsaf I apologise, I read poorly. I thought you wanted different precedence for piping and or back piping. I see now that’s not the case. That’s what you get for trying to understand things late at night 😅

**Comment by dsyme** [comment]
Agreed with @cartermp - this isn't something we'll add to F#, for the reasons he mentions
