### ISSUE TITLE
Allow class member to accept bound value of type unit without piping

### ISSUE THREAD

**Issue by LyndonGingerich** [fsharp/fslang-suggestions#1208]
For consistency, I propose that members be allowed to take single bound parameters of type `unit` without using piping operators such as `|>`.

Sample code for illustration (also included in attached sample solution at the bottom of the post):
```fsharp
type MyClass() =
    member _.Unit() = ()

let myClass = MyClass()

let unit = ()

let unit1 = myClass.Unit()
let unit2 = myClass.Unit unit // FS0501: The member or object constructor 'Unit' takes 0 argument(s) but is here given 1. The required signature is 'member MyClass.Unit: unit -> unit'.
let unit3 = unit |> myClass.Unit
```

The existing way of approaching this problem in F# is:
- Passing `unit` explicitly rather than binding it (as developers should anyway), as in `unit1`
- Piping bound `unit` values into members using `|>` or `<|`

## Pros and Cons 

The advantages of making this adjustment to F# are:
- Less surprise
- Greater consistency

The disadvantages of making this adjustment to F# are:
- Low number of expected use cases

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

[UnitMember.zip](https://github.com/fsharp/fslang-suggestions/files/10016322/UnitMember.zip)

**Comment by kerams** [comment]
Related to https://github.com/dotnet/fsharp/issues/14194.

There's a dissonance between what `x.Method ()` means in F# conceptually (passing in one argument of type unit), and how it is represented in .NET (calling a method with no arguments).

**Comment by LyndonGingerich** [comment]
@kerams #1208 and #14194 look like duplicates with different workarounds to me. Should we combine them? I could close this issue and post a workaround to the other.

**Comment by kerams** [comment]
It's not for me to decide:)
