### ISSUE TITLE
 [Question] How to reduce Async<unit[]>

### ISSUE THREAD

**Issue by Xyncgas** [fsharp/fslang-suggestions#1210]
if I map a sequence to a bunch async operations
```F#
async{
    let! k = MySeq |> Seq.Map ( fun x -> *async operation*) |> Async.Parallel
    return ()
}
```
I get Async<unit[]>, so I had to use let! instead of do!, and I had to return () instead of just leaving do! in place

normally I get Seq.iter I can use, but I can't here because I want to actually run the asyn operation in parallel
It's not like there is Seq.iterASync

what do you guys do

**Comment by GratianPlume** [comment]
`Async.Ignore`

**Comment by bartelink** [comment]
`|> Async.Ignore<unit []>` (to avoid surprises and get a compiler error when you change the async op to yield a non-`unit` value)

**Comment by Xyncgas** [comment]
Thanks

**Comment by Xyncgas** [comment]
is the program compiled running in .NET smart enough to not create an array of unit?

**Comment by baronfel** [comment]
@Xyncgas this board is for explicit language suggestions only. It is not your personal Q&A site. This level of question should be raised at channels like StackOverflow, the FSSF Forums, or any number of other avenues.

I'm going to close this as a result. Please do continue to raise concrete language suggestions here in the future.
