### ISSUE TITLE
Allow attributes on `let` bindings in nested functions.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/fslang-suggestions#1214]
I propose we allow attributes on `let` bindings in nested functions.

The existing way of approaching this problem in F# is by moving the function outside. An example of attribute one would need to add is trimming annotations

## Pros and Cons 

The advantages of making this adjustment to F# are simpler and more encapsulated code.

The disadvantages of making this adjustment to F# are 🤷🏻‍♂️

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: _Not found_

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
Related: https://github.com/fsharp/fslang-suggestions/issues/984

These two suggestions should probably be considered as one.

**Comment by charlesroddie** [comment]
> trimming annotations

These are not needed unless you are working outside of type systems, e.g. reflection. F# should make it less convenient to do that (e.g. via warnings that must be disabled), not more!

**Comment by Happypig375** [comment]
-> https://github.com/fsharp/fslang-suggestions/issues/848

**Comment by teo-tsirpanis** [comment]
Thanks @Happypig375, closing as duplicate.

**Comment by richardcox13** [comment]
It is a real shame this is not planned.

Just wanted to add `[<TailCall>]` to an inner function, where that inner function can only be called from within the containing function (which uses the recursive inner as part of more processing).

**Comment by T-Gro** [comment]
In general, it does not make sense to allow all attributes.

For a curated list of typecheck-time attributes, where the implementation would ensure they are applied with the right semantics, this https://github.com/fsharp/fslang-suggestions/issues/848#issuecomment-2659378725 can work.

(i.e. reduce this suggestion from a general feature into a specialized wish "I want TailCall on inner let")
