### ISSUE TITLE
Remove warning for new keyword on IDisposable

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#124]
# Remove warning for new keyword on IDisposable [15257796]

**Submitted by Isaac Abraham on 7/18/2016 12:00:00 AM**  
**5 votes on UserVoice prior to migration**  

The only time I ever use the new keyword is on Disposables, and even then only to silence the compiler warnings. I'm not sure what purpose the warning serves either, because you can still forget to bind the disposable with the use keyword instead of with let. What's more annoying is that it prevents you from effective pipelining.
Could this be removed from the next F# release, or perhaps replaced with a warning if you bind a Disposable with let instead of use?

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15257796)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15257796-remove-warning-for-new-keyword-on-idisposable.md#comments)

**Comment by dsyme** [comment]
For me it feels that this warning still has a role to play.  For beginners, disposability can all to easily be ignored.

**Comment by charlesroddie** [comment]
Visual F# is getting more colourful, and I wonder if colour could improve on / substitute for `new` in helping to identify IDisposables.
Currently:
```fsharp
type T() =
    interface IDisposable with member t.Dispose() = ()

let f() = new T()

let x = T() // warning
let y = new T() // no warning
let z = f() // no warning, could be dangerous
```
Suggestion for color:
x, y, and z should be given an IDisposable identifier color.
T() should be given an IDisposable type color.

**Comment by realvictorprm** [comment]
This is a great idea :thinking_face:, shouldn't be that difficult to add.

**Comment by cartermp** [comment]
@charlesroddie Colorization for disposable types is already implemented for F# - it just has the same default as C#:

<img width="744" alt="screen shot 2018-03-23 at 8 04 29 am" src="https://user-images.githubusercontent.com/6309070/37836877-ea8afb88-2e70-11e8-8fa2-c80bc69e4043.png">

Here's what your sample looks like today if I change it to hot pink:

<img width="640" alt="screen shot 2018-03-23 at 8 07 29 am" src="https://user-images.githubusercontent.com/6309070/37836996-482190d6-2e71-11e8-974d-6ccf172d9fca.png">

**Comment by matthid** [comment]
@cartermp I think he means the identifiers not the types...

**Comment by charlesroddie** [comment]
@cartermp Thanks for info. We could just use that color to color both types and identifiers.

**Comment by cartermp** [comment]
See here: https://github.com/Microsoft/visualfsharp/issues/4618

**Comment by dsyme** [comment]
Closing per my original comment:

>  For me it feels that this warning still has a role to play. For beginners, disposability can all to easily be ignored.
