### ISSUE TITLE
Support for ValueTask state machine computation expression

### ISSUE THREAD

**Issue by thinkbeforecoding** [fsharp/fslang-suggestions#1244]
I propose we implement a valuetask computation expression in a similar way it has been done for task.

The existing way of approaching this problem in F# is to use the task {} computation expression and wrap it in a task. However, the advantage of ValueTask is that it doesn't necessarily allocate a task when the result can be computed synchronously.

## Pros and Cons 

The advantages of making this adjustment to F# are:
* More efficient and faster code
* Far lower memory impact
* No need for wrapping Task in ValueTask (which is not easy to get right and is verbose)
* More straightforward in case of libraries and frameworks that use ValueTask

The disadvantages of making this adjustment to F# are :
* A new ValueTaskBuilder implementation quite similar to TaskBuilder.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: N/A

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by vzarytovskii** [comment]
I personally think it will be confusing for users, why is whole chunk of API (whole ValueTask builder) is missing in ns20 (sincle `AsyncValueTaskMethodBuilder` is ns21 only).

**Comment by Daniel-Svensson** [comment]
> I personally think it will be confusing for users, why is whole chunk of API (whole ValueTask builder) is missing in ns20 (sincle `AsyncValueTaskMethodBuilder` is ns21 only).

Is there something missing in System.Threading.Tasks.Extensions nuget package that would give problems with f# (it works well with c# for ns2.0, even ns1.0+ is still supported)

**Comment by vzarytovskii** [comment]
> > I personally think it will be confusing for users, why is whole chunk of API (whole ValueTask builder) is missing in ns20 (sincle `AsyncValueTaskMethodBuilder` is ns21 only).
> 
> 
> 
> Is there something missing in System.Threading.Tasks.Extensions nuget package that would give problems with f# (it works well with c# for ns2.0, even ns1.0+ is still supported)

We don't have (and not planning to have) any dependencies in the core library, without proper design for either introducing them (including source build) or separating core library into "core" part without dependencies and additions, or even some other unexplored option.

**Comment by abelbraaksma** [comment]
I thought this was currently available in some NuGet libraries, no? Perhaps we should close this as `Not planned`, as I don't see this happening anytime soon (re: ns20 vs ns21 issue).

EDIT: yep: https://github.com/TheAngryByrd/IcedTasks has a `valueTask` CE.

**Comment by voronoipotato** [comment]
They have it and they're also seemingly positive about it being adopted, perhaps we should consult them about what they think?

**Comment by vzarytovskii** [comment]
> Perhaps we should close this as `Not planned`

yes, I  think it makes sense to close it now until we have a better story for such big differences in the public surface area for different targets.
