### ISSUE TITLE
allow compiler directive to switch off inlining

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#125]
# allow compiler directive to switch off inlining [15332553] #

**Submitted by Steven Taylor on 7/22/2016 12:00:00 AM**  
**8 votes on UserVoice prior to migration**  

to get around debugging issues with the inline macro device, this pattern creaps into the code base (taken from FsPickler):
```fsharp
#if DEBUG
let writeBoundedSequence
#else
let inline writeBoundedSequence
#endif
```
It would be nice to be able to turn off the effect of the inline keyword for files and entire projects while compiling for debugging purposes. Also, optionally setting ignore inline for code executed in an interactive session would be useful too.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15332553)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15332553-allow-compiler-directive-to-switch-off-inlining.md#comments)

**Comment by dsyme** [comment]
Per the comments on the original submission, this is not as easy as it looks.  See that discussion for why we're closing this.
