### ISSUE TITLE
Allow CustomOperation without explicity name

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1250]
Would be great to have some convention for `CE` custom operations name, sometimes (when using overload) is very repetitive to reuse the same name on each. Also is not uncommon to have the operator name as a derivation of the method name

So:
```fs
type FooBuilder() =
    [<CustomOperation("bar")>]
    member _.Bar(state) = state
```
Would be the same as 

```fs
type FooBuilder() =
    [<CustomOperation>]
    member _.bar(state) = state
```

## Pros and Cons 

The advantages of making this adjustment to F# are simplify some custom CE use cases

The disadvantages of making this adjustment to F# are:
- to have class member name case, not in PascalCase 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): ?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
This seems too minor to consider.  CustomOperations aren't that common :)

**Comment by Happypig375** [comment]
@dsyme But the implementation is simple as well, it's an easy item for external contributors

**Comment by dsyme** [comment]
@Happypig375 OK, yes, it's true, it's reasonable.

**Comment by vzarytovskii** [comment]
Do we want to allow only lower-cased members for implicit custom operations, or any?

**Comment by edgarfgp** [comment]
I think this can be closed as completed by https://github.com/dotnet/fsharp/pull/16475 ? 
cc @vzarytovskii

**Comment by vzarytovskii** [comment]
> I think this can be closed as completed by https://github.com/dotnet/fsharp/pull/16475 ? 
> 
> cc @vzarytovskii 

Yeah, thanks for keeping an eye on it!
