### ISSUE TITLE
Copy data between records of different types

### ISSUE THREAD

**Issue by Lanayx** [fsharp/fslang-suggestions#1251]
I propose we add ability to use **with** syntax with different types to copy large portions of fields between records. There is an [old declined suggestion](https://github.com/fsharp/fslang-suggestions/issues/291) which was declined for an unclear reason, this issue is an idea revival. I can see several use-cases

1) Decorate a record with new fields
```fsharp
type A = {
    X: int
}
type B = {
    X: int
    Y: string
}
let a = { X = 1 }
let b = { a with Y = "2" }
```
2) Partially use one record to create another

```fsharp
type A = {
    X: int
    Z: int
}
type B = {
    X: int
    Y: string
}
let a = { X = 1; Z = 3 }
let b = { a with Y = "2" }
```

3) Using multiple records to construct a record
```fsharp
type A = {
    X: int
    Y: int
}
type B = {
    Z: int
}
type C = {
    X: int
    Y: int
    Z: int
    Extra: string
}
let a = { X = 1; Y = 2 }
let b = { Z = 3 }
let c = {
    a; b with Extra = "four"
}
```

The existing way of approaching this problem in F# is copying all fields manually (which creates a lot of boilerplate) or using smth like Automapper (which is not compile-time safe) or using anonymous records (which are rarely applicable for business domains)

Suggestion is also influenced by javascript spread operator, for example

```javascript
const obj1 = { foo: "bar", x: 42 };
const obj2 = { foo: "baz", y: 13 };

const clonedObj = { ...obj1 };
// { foo: "bar", x: 42 }

const mergedObj = { ...obj1, ...obj2 };
// { foo: "baz", x: 42, y: 13 }
```

## Pros and Cons 

The advantages of making this adjustment to F# are: simplifying DTO conversion in complex business domains, endorsing record-based programming, avoiding using runtime errors when using automapper

The disadvantages of making this adjustment to F# are: more work for compiler, IDE support

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M (not sure)

Related suggestions: (put links to related suggestions here)
https://github.com/fsharp/fslang-suggestions/issues/291

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by kerams** [comment]
If you use the syntax of the standard copy-and-update, how will the compiler know that you intended to remap a record onto a different type, and didn't just make a mistake? Similar problems would arise when type of the original expression is inferred.

**Comment by Lanayx** [comment]
I think that the following algorithm should apply
1) Try infer the record type by explicit fields. If no explicit fields are present like `let c = { a; b }` then the type annotation is required.
2) If the target record type is found, get all other required implicit fields and try to match them with the fields from the referenced record
3) If fields don't match - display error with all the fields that were not matched

That being said I don't mind a new spread operator if making it work with **with** operator is impossible , for example
```fsharp
type A = {
    X: int
}
type B = {
    Y: string
    Z: string
}
type C = {
    X: int
    Y: string
    Z: string
}
let a = { X = 1 }
let b = { Y = "2"; Z = "3" }
let c: C = { ...a; ...b }
```

I'm also referencing https://github.com/fsharp/fslang-suggestions/issues/1245 since the case of building single record from two records and single object expression from two values should have similar syntax for consistency.

**Comment by dsyme** [comment]
Thoughts on spread operator in object expressions here: https://github.com/fsharp/fslang-suggestions/issues/1245#issuecomment-1463911009

**Comment by dsyme** [comment]
I added thoughts on a spread operator here: https://github.com/fsharp/fslang-suggestions/issues/1253

**Comment by dsyme** [comment]
Closing in favour of https://github.com/fsharp/fslang-suggestions/issues/1253
