### ISSUE TITLE
Enable record inheritance

### ISSUE THREAD

**Issue by Lanayx** [fsharp/fslang-suggestions#1254]
**DISCLAIMER**:  I know that inheritance is bad, but please read the rest of the suggestion

This is a revival an [old declined issue ](https://github.com/fsharp/fslang-suggestions/issues/70), but single inheritance only and with more reasons to do it

I've found the following reasons that record inheritance would be useful to have
1) C# records now have inheritance and for easy interop and general understanding we can add it as well
2) F# is no longer functional first language, but a multiparadigm language, just like C#, so inheritance is one of it's essential techniques, I personally use interface inheritance at work every day
3) There are certain use cases of records that are simply unresolvable without inheritance and require fallback to classes:
- If there is a set of common fields between records (and this set can't be extracted to another record for any reason) currently those fields should be duplicated. It becomes even more prominent when those fields are attribute-decorated
- If there is a set of attributes to be assigned to many similar records (like DTO), those should be duplicated
- If there is a set of common methods on records (like ToString), those should be duplicated
- If there is a record exposed in library and someone wants to extend it - it should be duplicated
- Data protocol can implement inheritance, so records are unable to express this

So basically instead of simply not allowing inheritance we can say - use it carefully, only where appropriate

The existing way of approaching this problem in F# is to do either duplication, or composition (if possible), or fallback to classes.

Possible implementations:

- Just remove sealed attribute from existing records
- Support attribute similar to Struct, for example `[<AllowInheritance>]`
- Create special syntax for such inheritable records

## Pros and Cons 

The advantages of making this adjustment to F# are - to handle issues raised above

The disadvantages of making this adjustment to F# are:
- Value semantics can be broken, e.g. the comparison order might be broken. If a = b it won't mean that b = a
- Mindset has to change. Up until now having records not allowing inheritance was a cornerstone that might be reconsidered

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here) https://github.com/fsharp/fslang-suggestions/issues/70

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by LyndonGingerich** [comment]
> There are certain use cases of records that are simply unresolvable without inheritance and require fallback to classes:
> - If there is a set of common fields between records (and this set can't be extracted to another record for any reason) currently those fields should be duplicated. It becomes even more prominent when those fields are attribute-decorated
> - If there is a set of attributes to be assigned to many similar records (like DTO), those should be duplicated

What would keep a sub-record from being extracted? I think that's the usual solution to both these cases (satisfying [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)).

> - If there is a record exposed in library and someone wants to extend it - it should be duplicated

Why should the library record be duplicated rather than reused?

> This is not a breaking change to the F# language design

> Value semantics can be broken, e.g. the comparison order might be broken. If a = b it won't mean that b = a

Did you mean to check that box? It sounds to me as though you're saying that this would be a breaking change.

>  This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

> Mindset has to change. Up until now having records not allowing inheritance was a cornerstone that might be reconsidered

"Changing mindset" sounds a lot like "already been decided" to me, particularly considering Don Syme's comment on the original issue:

> Note this is effectively multiple class inheritance and is not implementable withing the constraints of the .NET type system (since records are ultimately classes). And singe inheritance is a poor substitute which is better not added alone.
> Closing for the above reason

**Comment by Lanayx** [comment]
> What would keep a sub-record from being extracted?

For example, this is DTO for some framework like EntityFramework or Serilog, where all the fields should be at the top level and subrecords are not allowed. Sometimes there are fields that have to be added everywhere, for example I like to add CreatedAt and UpdatedAt fields to every database table, which would require each record having those fields at the top level

> Why should the library record be duplicated rather than reused?

Same reason - records are not only used for domain modeling. I often use them to map to data contracts (OpenApi, protobuf etc) where schema is defined, set of fields is defined and new fields can only be added at the top level (for example this is exactly what happens in Pulsar.Client library)

> Did you mean to check that box? It sounds to me as though you're saying that this would be a breaking change.

No, since existing code doesn't use inheritance so even if we go with the first option - allowing inheritance by default - no existing code will break

> "Changing mindset" sounds a lot like "already been decided" to me, particularly considering Don Syme's comment on the original issue:

Yes, it was declined seven years ago, but things have changed - more people have started using F# at work, some patterns have emerged and some conditions change - for example C# records do allow inheritance. 

I would refer to SRTP as a similar example - overusing it will be pain, but it still exists and is useful pattern in some particular scenarios

**Comment by izackhub** [comment]
Is there a possibility to instead opt for a more highlevel approach that is taken care of by the compiler instead? I have been testing out many programming languages, F# is by far my absolut favorite, but there are some features I have come across that would really be practical, especially with a strict type system like F#'s. 
1 such feature is 'Type inclusion' in it's current form in the Ballerina Lanaguage. 

```
type Person record {|
    string name;
    int age;
|};

type Student record {|
    int studentId;
    string code;
|};

// The `PartTimeStudent` record has all the fields of `Person` and `Student`.
type PartTimeStudent record {|
    *Person;
    *Student;
    // Overrides the `code` field in `Student`.
    string:Char code;
|};
```
here, the fields of the Person and Student are effectively spread into the PartTimeStudent record. Using a copy mechanism overcomes the inheritance problem and rather just trasnparently add the fields the same way it's currently done by duplicating the fields in the eyes of the compiler.

I have run into 2 situations where I ended up duplicating almost exact keys of a type, because 1 of the types had 1 extra field or the type 1 of the 1o fields in a record type differred for 1 2types. 1 being used to bind form data that had a checkbox, the other was only to make it a real boolean for the document database.

**Comment by brianrourkeboll** [comment]
@izackhub see the spread operator suggestion #1253.

**Comment by izackhub** [comment]
@brianrourkeboll Thanks you very much pointing that out. 
Certainly a very interessing proposal and 1 step in the practical usage direction. The proposal seem to work on the values only, rather than also on the typed level like type inclusion I mentioned.

**Comment by brianrourkeboll** [comment]
@izackhub

> The proposal seem to work on the values only, rather than also on the typed level like type inclusion I mentioned.

It does actually bring up types:

> ### Types?
> 
> How about type syntax? e.g.
> 
> ```fsharp
> type A = {
>     X: int
>     Y: int
> }
> type B = {
>     Z: int
> }
> type C = {
>     ...A;
>     ...B;
>     Extra: string
> }
> let a = { X = 1; Y = 2 }
> let b = { Z = 3 }
> let c = { ...a; ...b Extra = "four" }
> ```

Also look under the headers for "interface implementations" and "object expressions."

**Comment by izackhub** [comment]
@brianrourkeboll Oh yeah, I completly scrolled pass that. Forget interessting, this would be incredibly amazing. Thanks again.

**Comment by 0samaHaider** [comment]
In inheritance, when we inherit one class from another, the properties of the base class are automatically constructed. However, in records, we need to initialize all the properties of the base record in the derived record. This increases syntax complexity. If we are reinitializing the properties of the base record in the derived record, then code reusability does not occur. That's why I guess we should use classes for inheritance, not records.

**Comment by abelbraaksma** [comment]
Indeed, as mentioned here when this was originally closed: https://github.com/fsharp/fslang-suggestions/issues/1254#issuecomment-1507086569
