### ISSUE TITLE
Generic units of measure

### ISSUE THREAD

**Issue by reinux** [fsharp/fslang-suggestions#1257]
I think one of the reasons for low adoption of Units of Measure might have to do with the inability to use different units of the same kind. This discourages its use in physics and graphics and finance/commerce libraries, where it would otherwise be the most useful.

For example, should a `pressure` function be

```
let pressure (force: float<newton>) (area: float<m*m>) : float<pascal>= ...
```

or should it be

```
let pressure (force: float<pound>) (area: float<in * in>) : float<psi> = ...
```

Or what about when the scales are so disparate that the differences in units matters elsewhere in the code, e.g. between meters and light years?

It may be useful to be able to say something like:

```
[<Measure>]
type ly inherit length
[<Measure>]
type cm inherit length

let hypotenuse (a: float<'l>) (b: float<'l>) : float<'l> when 'l :> length =
  ...

hypotenuse 3<ly> 5<ly>

hypotenuse 3<cm> 5<cm>
```

## Cons
It may be difficult to predict when a function could be used for different kinds of units. For example, the Pythagorean theorem is specifically useful in Euclidean space, but trigonometric functions, many which are taught in school using visual aids, in fact see usage well beyond just distances and lengths. Either the implementer would have to be very aware of the function's mathematical shape, or the consumer would have to do some awkward type conversions up front.

That said, it might almost always be enough to simply advise library authors to forego units of measure for mathematical and geometric functions, and to use them in physics and graphics libraries. If, say, a concept emerging from physics turns out to have application in finance, it will usually be analogized as a phenomenon of physics anyway, so the conceptual overhead should usually be minimal.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by roboz0r** [comment]
What you describe is already possible. It just takes rigorous application of the generic measures:

```fs
[<Measure>]
type kg
[<Measure>]
type m
[<Measure>]
type s
[<Measure>]
type N = kg * m / s^2

[<Measure>]
type Pa = kg / m / s^2
// 'L = Length
//'M = Mass
//'T = Time
let pressure (force: float<'L * 'M / 'T^2>) (area: float<'L^2> ) = force / area

(pressure 2.0<N> 3.0<m^2>) + 10.0<Pa>


[<Measure>]
type lb
[<Measure>]
type inch
[<Measure>]
type G
[<Measure>]
type lbf = lb * G

[<Measure>]
type psi = lbf / inch^2

(pressure 2.0<lbf> 3.0<inch^2>) + 10.0<psi>
```

**Comment by 1eyewonder** [comment]
Agreed on what roboz0r said. I have already implemented a library here for those interested in the scientific/engineering units of measure: https://github.com/1eyewonder/Fs.Units which follows the pattern shown above.

**Comment by reinux** [comment]
Wow, can't believe I missed that. My bad!
