### ISSUE TITLE
Support isNull when querying the built-in SQL type providers

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#128]
**Submitted by Loic Denuziere on 8/2/2016 12:00:00 AM**  
**5 votes on UserVoice prior to migration**  

Right now the query expression-to-LINQ translation doesn't support queries such as `query { for x in table do where (isNull x.Field) }`. Instead we have to use `where (x.Field = null)`. That's quite inconsistent: in normal (non-query) code, `isNull` is advised, but in query code, we can't use it.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15511989)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15511989-support-isnull-when-querying-the-built-in-sql-typ.md#comments)

**Comment by dsyme** [comment]
This is too corner-case: there is a way to do what's needed.  It's in the nature of LINQ queries to only accept a very restricted subset of expression forms.
