### ISSUE TITLE
Allow specifying lambdas return type

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1297]
Allowing specifying the explicit return type of lambdas is something that can't be done and could be useful in some cases and it is also something that should be supported to be paired with `let` functions.

One case is dealing with implicit return types

```fsharp
open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Http.HttpResults
open type TypedResults

let handler n : Results<Ok, BadRequest> = // ok
    if n % 2 = 0 then Ok() else BadRequest()

let handler2: int -> Results<Ok, BadRequest> = // ok 
    fun n -> if n % 2 = 0 then Ok() else BadRequest()

let handler3 = // do not compile
    fun (n: int) : Results<Ok, BadRequest> -> if n % 2 = 0 then Ok() else BadRequest()
```

## Pros and Cons 

**The advantages of making this adjustment to F# are**: 
- Homogenous type def between function definitions
- Less friction for newcomers

**The disadvantages of making this adjustment to F# are** ...
- N/A

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  ?

**Related suggestions:** (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
Gonna tag this as `probably not` -- while in theory it could be nice to have the return type definition closer to the parameters, this doesn't seem worth doing:

- Two different ways to specify the return type
- The use case for doing it inline is...really not that prominent IMO. Most people don't specify return types anyways, let alone on lambdas that just overcomplicate function signatures (e.g., function with no parameters that returns a lambda with a parameter), nor do they tend to do this for lambdas passed as a parameter to a function or method.

**Comment by vzarytovskii** [comment]
Closing down all `probably not` issues, until there's another consideration about it.
