### ISSUE TITLE
Use of the `_.Property` shorthand in delegates

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1308]
I propose we enable to use of the new `_.Property` shorthand for accessor within `Func<>` and `Expression<Func<>>` as normal lambdas

```fs
["foo"; "42"; ""] |> List.map _.Length // [3; 2; 0]

open System.Linq
["foo"; "42"; ""].Select(_.Length) // fail
```

**The existing way of approaching this problem in F# is**:

Using normal lambdas

```fs
["foo"; "42"; ""].Select(fun s -> s.Length) 
```

## Pros and Cons 

**The advantages of making this adjustment to F# are** : make the syntax consistent 

**The disadvantages of making this adjustment to F# are** : N/A

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  

**Related suggestions:** 
https://github.com/fsharp/fslang-suggestions/issues/506

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [x] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [x] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by lucasteles** [comment]
cc @vzarytovskii

**Comment by Happypig375** [comment]
`["foo"; "42"; ""].Select(_.Length)` :x:
`["foo"; "42"; ""].Select _.Length` ✔️

**Comment by lucasteles** [comment]
@Happypig375 I believe both should work, the first is important to not break the fluent chain

`["foo"; "42"; ""].Select(_.Length).Where(isEven)`

**Comment by Happypig375** [comment]
@lucasteles only needed when there is a fluent chain.

**Comment by cmeeren** [comment]
This already has an issue, marked approved-in-principle: 506

**Comment by Happypig375** [comment]
@cmeeren This is for any delegate, not F# function types.

**Comment by cmeeren** [comment]
Yes, I definitely second this.

**Comment by T-Gro** [comment]
This was done as part of https://github.com/dotnet/fsharp/pull/16339  (it is in main, not yet in the released product)
The following three syntax options of doing the same now work, does it cover all of this suggestion?

```fsharp
open System.Linq
let _ = [""; ""; ""].Select(fun x -> x.Length)
let _ = [""; ""; ""].Select(_.Length)
let _ = [""; ""; ""].Select _.Length

```

**Comment by cmeeren** [comment]
From what I can see, this would fix the issue, though I'm not the OP.

**Comment by abelbraaksma** [comment]
Works like a charm (in `main`)!

![image](https://github.com/fsharp/fslang-suggestions/assets/16015770/3ab3f739-9d03-45ba-84fa-71d548525889)
