### ISSUE TITLE
Allow lower-case DU cases when [<RequireQualifiedAccess>] is specified

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#131]
**Submitted by Alex Corrado on 8/24/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

Currently, it is not allowed to declare DU cases with lower-case letters. For instance, this is not allowed:

``` fsharp
type Foo =
    | foo
    | bar
    | baz
    // etc...
```

This yields: `error FS0053: Discriminated union cases and exception labels must be uppercase identifiers` As I understand it, this is to prevent ambiguity in pattern matching between matching a union case and binding to an identifier. However, this is not an issue if the `[<RequireQualifiedAccess>]` attribute is specified on the DU. Therefore, I propose we allow lower-case cases in this case.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15801949)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15801949-allow-lower-case-du-cases-when-[-requirequalified.md#comments)

**Comment by dsyme** [comment]
This is an entirely reasonable suggestion.  Although it only has one vote, it has obvious utility.  Marking as approved in principle (though it is not high priority)

**Comment by vasily-kirichenko** [comment]
And it's very easy to implement.
