### ISSUE TITLE
Private section in modules

### ISSUE THREAD

**Issue by dark-valkyrix** [fsharp/fslang-suggestions#1322]
**I propose we** add a new way to declare private elements in modules like this :
```
module AwesomeModule=
<--  private -->
    type PrivateType=
        ...

    let PrivateFunc=
        fun (p: PrivateType) ->
            ...

<-- public -->
    let PublicType=
        ...

    let PublicFunc=
        fun (p: float) ->
            let (z: InternalType)=
                ... (something that depends on p)
            match PrivateFunc z with
            | ... -> (...): PublicType
            | _ -> (...): PublicType
```

**The existing way of approaching this problem in F# is** by declaring each private element with the keyword ```private```, which can be cumbersome and can easily break beautiful indentations.

## Pros and Cons 

**The advantages of making this adjustment to F# are** mostly esthetic with the possibility to better organize a big module file.

**The disadvantages of making this adjustment to F# are** some work for great guys who provide great tools.

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  S

**Related suggestions:** (not found)

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [X] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [X] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by brianrourkeboll** [comment]
I often use private submodules to address this, e.g.:

```fsharp
module OuterModule =
    // Anything inside of InnerModule is automatically in scope
    // within OuterModule but invisible outside of it.
    // Only the submodule itself needs the private keyword.
    [<AutoOpen>]
    module private InnerModule =
        type T = …
        let g x = …

    // These are public but can make use of anything in InnerModule.
    type U = …
    let f x = …
```

or

```fsharp
module OuterModule =
    // Only the submodule itself needs the private keyword.
    module private Impl =
        type T = …
        let g x = …

    // Explicitly bring the private inner module into scope.
    // This can be useful if you have multiple such inner modules
    // and want to make use of shadowing, etc.
    open Impl

    // These are public but can make use of anything in InnerModule.
    type U = …
    let f x = …
```

**Comment by dark-valkyrix** [comment]
Thanks, that's a great way to organize big modules!
I guess I will close the suggestion.
