### ISSUE TITLE
Additional keywords for return & yield : ret & yet

### ISSUE THREAD

**Issue by dark-valkyrix** [fsharp/fslang-suggestions#1328]
**I propose we** add additional keywords for `return` (`ret`) and `yield` (`yet`) like this :
```fsharp
    let! x= async {
        let! a= ...
        let! b= ...
        ...
        ret z
    }
```

Which gives better formatting than this :
```fsharp
    let! x= async {
        let! a= ...
        let! b= ...
        ...
        return z
    }
```

## Pros and Cons 

**The advantages of making this adjustment to F# are** purely aesthetics.

**The disadvantages of making this adjustment to F# are** breaking changes for existing code with those literals.

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  XS ?

**Related suggestions:** (put links to related suggestions here)

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [X] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [X] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by vzarytovskii** [comment]
That would be a breaking change.

**Comment by vzarytovskii** [comment]
I will go ahead and put "probably not", @dsyme @cartermp feel free to chime in if think otherwise :)

**Comment by drhumlen** [comment]
`yield` can already be implicit which is even shorter than `yet`.

And I _much_ rather see `return` become implicit in the future rather than a slightly shorter word. That would fit more with how every other function works
