### ISSUE TITLE
Impement auto notification

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#133]
# Impement auto notification [15915808] #

**Submitted by Ivan J. Simongauz on 9/3/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

Impement auto notification chages for classes and records when implemented INotifyPropertyChanged or custom.
type A() =
let achaged name old new =
PropertyChanged(this, name)
member B : int 3 with get and set and notifyby achanged

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15915808)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15915808-impement-auto-notification.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 2.0 and we decided against it. Closing per policy not to revisit issues already considered and decided against, unless circumstances have changed.
