### ISSUE TITLE
Compile interpolated strings properly for better performance

### ISSUE THREAD

**Issue by charlesroddie** [fsharp/fslang-suggestions#1346]
The code

```fsharp
let world = "world"
let helloWorld = $"hello {world}" compiles to

```

Currently compiles to (see SharpLab)
```csharp
object[] array = new object[1];
array[0] = "world";
PrintfModule.PrintFormatToStringThen(new PrintfFormat<string, Unit, string, string, string>("Hello %P()", array, null));
```

Instead, it should compile to one of these, and testing suggests that `Impl2` is better
```fsharp
let helloWorldImpl1() =
    String.Format("Hello {0}", "world")
let helloWorldImpl2() =
    let sb = Text.StringBuilder()
    sb.Append("hello") |> ignore
    sb.Append(world) |> ignore
    sb.ToString()

```

## Pros and Cons 

**The advantages of making this adjustment to F# are**

1. Performance.

https://github.com/charlesroddie/BenchmarksFsharp/tree/InterpolatedStrings

| Method                    | Mean     | Error    | StdDev   | Gen0   | Allocated |
|-------------------------- |---------:|---------:|---------:|-------:|----------:|
| InterpolatedStringCurrent | 88.20 ns | 1.764 ns | 1.650 ns | 0.0219 |     184 B |
| Impl1                     | 36.03 ns | 0.757 ns | 0.632 ns | 0.0057 |      48 B |
| Impl2                     | 18.30 ns | 0.416 ns | 0.841 ns | 0.0181 |     152 B |

2. Complex generic instantiations are not surfaced, helping the size of apps when AOT compiled. We previously found that this was several MB! But would need to retest with current NativeAOT.

3. The current code requires reflection, making it harder for compilers to reason about, contributing to poor performance, contributing to 2 by bringing in more reflection data, and being incompatible with reflection-free modes.

**The disadvantages of making this adjustment to F# are** ...

None

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  

M

**Related suggestions:** (put links to related suggestions here)

https://github.com/fsharp/fslang-suggestions/issues/919
https://github.com/dotnet/fsharp/issues/13398

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [ x ] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [ x ] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [ x ] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [ x ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [ x ] This is not a breaking change to the F# language design
* [ x ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by kerams** [comment]
https://github.com/fsharp/fslang-suggestions/issues/1108
