### ISSUE TITLE
Add ofObj to Seq and Array

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#135]
**Submitted by Mark Seemann on 9/15/2016 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

The Option module defines Option.ofObj which converts a potential nullable value to an option.
Collections (Seq and array) can be null in interop scenarios, but it'd often be natural to interpret a null collection as an empty collection.
It's possible to compose such behaviour from existing building blocks, e.g. with Option.ofObj >> Option.toArray >> Array.concat
This seems like quite a roundabout way to do things, so I'd like to propose equivalent functions for Seq and Array:
// seq<'a> -> seq<'a>
Seq.ofObj
// 'a [] -> 'a []
Array.ofObj

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16092382)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16092382-add-ofobj-to-seq-and-array.md#comments)

**Comment by dsyme** [comment]
This design suggestion doesn't seem right to me. An explicit null check for this case seems better. And you can always write the proposed functions as simple helpers in your own code.
