### ISSUE TITLE
Feature request: Support JSON syntax format

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1356]
Use the keyword `json` to represent each node of a JSON object

```fs
let sample = json {
    "s" = json ""
    "d" = json 1.0
    "n" = json null
    "b1" = json true
    "b2" = json false
    "children" = json [ json {} ]
    }
```

The existing way of approaching:

```fs
let sample = Json.Object [
    "s",Json.String ""
    "d",Json.Number 1.0
    "n",Json.Null
    "b1",Json.False
    "b2",Json.True
    "children",Json.Array [ Json.Object [] ]
    ]
```

Among them, the composite structure `object` and `array` will greatly simplify writing.

object

```fs
json {} 
json { a = json "hello" }
```

The existing way of approaching

```fs
Json.Object []
Json.Object [ "a",Json.String "hello"]
```

array

```fs
json []
json [ json "hello"; json true; json null ]
```

The existing way of approaching

```fs
Json.Array []
Json.Array [ Json.String "hello";Json.True;Json.Null ]
```

We can also freely use value binding to composite JSON data:

```fs
let a = json 1.0
let b = json [ a ] // json [  json 1.0  ]

let c = 50
let d = json c // json 50
```

## Pros and Cons 

**The advantages of making this adjustment to F# are** ...

**The disadvantages of making this adjustment to F# are** ...

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  

**Related suggestions:** (put links to related suggestions here)

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [ ] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [ ] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [ ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by vzarytovskii** [comment]
I don't think it's something we're interested in. That's also probably something which can be expressed by generic code, traits, implicit yielding and some conversions.

**Comment by gimbling-away** [comment]
For the idea, a custom operator might be able to achieve a similar effect perhaps? `x => y` :)

```fs
json {
   "a" => b
   "c" => d
}
```
