### ISSUE TITLE
Allow #ParsedHashDirectives to have argument types other than strings

### ISSUE THREAD

**Issue by KevinRansom** [fsharp/fslang-suggestions#1364]
ParsedHashDirectives can currently only have string arguments.

This means that the syntax for HashDirectives is constrained to having quoted string arguments.

This makes some of the Hash directive syntax a little clunky.
````
#time "on"
(* Do lots of stuff here *)
#time "off"
````
probably would be nicer and perhaps easier to get right first time like this 
````
#time on
(* Do lots of stuff here *)
#time off
````

Similarly no warn requires numeric error numbers to be integers:
````
#nowarn "1234" "1235" "99"
````
Is probably better expressed as:
````
#nowarn 1234 1235 99
````

**Comment by abelbraaksma** [comment]
Here we go. We can keep this closed, but we can continue here (https://github.com/fsharp/fslang-suggestions/issues/1368). I hope I captured your intend properly.
