### ISSUE TITLE
Long overdue: let's rename the branch `master` ➡️ `main`, per policy

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-suggestions#1366]
I propose we rename the [`master`](https://github.com/fsharp/fslang-suggestions/tree/master) branch in the `fslang-suggestions` repository to `main`, just like we've done with virtually any other repository related to, or maintained by Microsoft products.

* GitHub [policy announcement](https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/)
* [Proposed procedure](https://dev.to/ackshaey/from-master-to-main-the-easy-guide-to-renaming-your-git-default-branch-for-a-more-inclusive-codebase-1fkg) (create new branch from master, set head, update repo settings and branch rules, delete old branch)

I'm happy to do it, it's relatively simple, and this repo is mainly for garnering issues so there's unlikely to be much disruption. However, I would like to garner approval from the community first.

/cc @vzarytovskii, @dsyme, @cartermp, @t-gro

**Comment by dsyme** [comment]
Done!
