### ISSUE TITLE
Expand on cardinality functions Seq.exactlyOne, with Seq.tryExactlyOne and add oneOrMore, zeroOrMore

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#137]
# Expand on cardinality functions Seq.exactlyOne, with Seq.tryExactlyOne and add oneOrMore, zeroOrMore [16308904]

**Submitted by Abel on 9/22/2016 12:00:00 AM**  
**7 votes on UserVoice prior to migration**  

While it is quite trivial to write these functions, I think they have merit. First of, it is good there's a Seq.exactlyOne, but it throws and if you want a non-throwing version, you'll have to write one your own. It's odd there's a creator function, Seq.singleton, but not a test-function.
Since we have Seq.exactlyOne, it should have its logical cardinality counterparts for zero-or-one and one-or-more to be available too.
I suggest we add:
Seq.tryExactlyOne
Seq.oneOrMore (throws)
Seq.zeroOrMore (throws)
Seq.tryOneOrMore
Seq.tryZeroOrMore
The reason it is better to have these in FSharp.Core is that, if one implements these by hand, it requires at least two iterations until the 2nd element. An optimized implementation may prevent this.
See also the discussion here: http://stackoverflow.com/questions/39628567/non-throwing-version-of-seq-exactlyone-to-test-for-a-singleton-sequence

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16308904)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16308904-expand-on-cardinality-functions-seq-exactlyone,-w.md#comments)

**Comment by dsyme** [comment]
I agree with the suggestion of ``tryExactlyOne``  I don't feel strongly about the others though.

**Comment by 0x53A** [comment]
I sometimes need an equivalent to LINQ ``SingleOrDefault`` - I have a collection which can contain either 0 or 1 elements, but having more than 1 represents a logical error and should never happen.


```c#
[ "1" ].SingleOrDefault() => "1"
[  ].SingleOrDefault() => null
[ "1", "2" ].SingleOrDefault() => Exception
```

I'm struggling to come up with a good name that matches the behavior, are there any precedents from other functional programming languages

```f#
[] |> Seq.emptyOrSingleton // None
[ 1 ] |> Seq.emptyOrSingleton // Some 1
[ 1; 2 ] |>  Seq.emptyOrSingleton // Exception
```

**Comment by gusty** [comment]
`Seq.toOption` ?

**Comment by gusty** [comment]
`Seq.toOption` ?

**Comment by gusty** [comment]
`Seq.toOption` ?

**Comment by gusty** [comment]
`Seq.toOption` ?

Though I'm not a big fan of partial functions (functions that throw)

**Comment by gusty** [comment]
`Seq.toOption` ?

Though I'm not a big fan of partial functions (functions that throw)

**Comment by gusty** [comment]
`Seq.toOption` ?

Though I'm not a big fan of partial functions (functions that throw)

**Comment by abelbraaksma** [comment]
> I'm struggling to come up with a good name that matches the behavior, are there any precedents from other functional programming languages

@0x53a, yes I know from other languages this is called `zeroOrOne`, which throws if it's neither zero, nor one. Same for `oneOrMore`. I think such names reveal the expected semantics pretty cleanly.

**Comment by abelbraaksma** [comment]
In the implementation-thread some more questions where raised and directed at me. I'll try to answer them as good as I can. @reed-adams,  @gdziadkiewicz, @0x53A:

```f#
exactlyOne: seq 'a -> 'a               // returns one or throws
tryExactlyOne: seq 'a -> 'a option     // returns Some for one or None
zeroOrOne: seq 'a -> seq 'a            // returns empty seq, singleton or throws
tryZeroOrOne: seq 'a -> seq 'a option  // returns Some empty seq, Some singleton or None
oneOrMore: seq 'a -> seq 'a            // returns the seq as is, or throws if it is empty
tryOneOrMore: seq 'a -> seq 'a option  // returns Some seq as is, or None if empty
```

This is also how I have currently implemented these myself and they work pretty well in practice, esp. in scenarios where cardinality is important.

**Comment by cartermp** [comment]
RFC for the `try*` variants here: https://github.com/fsharp/fslang-design/pull/343

Corresponding PR: https://github.com/Microsoft/visualfsharp/pull/5804

**Comment by cartermp** [comment]
Closing this out as it will be in FSharp.Core 4.6.0 - as the `tryExactlyOne` variants. The rest have not been approved, so if there is a strong enough desire to see them in FSharp.Core, please file a new issue
