### ISSUE TITLE
An unfold function that returns the final value: ('state -> 't * ('state option)) -> 'state -> 't seq

### ISSUE THREAD

**Issue by reinux** [fsharp/fslang-suggestions#1379]
**I propose we**
Provide another set of unfold function that can return a value on the final iteration, of the form `('state -> 't * ('state option)) -> 'state -> 't seq`.

Maybe we could call it something like `unfoldInclusive`?

**The existing way of approaching this problem in F# is** 
The current `unfold` functions use a generator of the form `'state -> ('t * 'state) option`, which means that the final iteration of the generator can't return a value.

Returning a value would seem to be a common scenario, for example, if you are retrieving items from a data source that also returns a link to the next page.

Currently, you would need to use either a mutable value or a recursive function to get this behavior.

## Pros and Cons 

**The advantages of making this adjustment to F# are** ...
- More higher-order function coverage for common loops

**The disadvantages of making this adjustment to F# are** ...
- Yet another higher-order function

## Extra information

I doubt this is an optimal implementation, but it might look something like this:

```fsharp
let unfold2 (generator: 'state -> 't * 'state option) (state: 'state) : 't seq =
  let rec loop state =
    seq {
      let result, nextState = generator state
      match nextState with
      | None -> yield result
      | Some nextState ->
        yield result
        yield! loop nextState
    }
  loop state
```  

**Estimated cost (XS, S, M, L, XL, XXL):**  
S

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [ ] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [x] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by voronoipotato** [comment]
@reinux it would be really helpful if you could provide some example uses (however contrived).

**Comment by reinux** [comment]
Upon resiviting this, I realized that this function can be expressed quite simply as

```fsharp
let unfoldInclusive generator =
  Some >> Seq.unfold (Option.map generator)
```

What a difference a good night's rest makes! Sorry for the unnecessary issue.
