### ISSUE TITLE
Allow records to be defined by using position instead of type field names

### ISSUE THREAD

**Issue by cmdoffing** [fsharp/fslang-suggestions#1385]
nstead of:
``
let dom: Domain = { 
                    DomainId = domain.DomainId;
                    ContextId = domain.ContextId;
                    DomainName = domain.DomainName;
                    DomainDoc = domain.DomainDoc;
                    DomainDeleted = domain.DomainDeleted
                  }
``
allow:
``
let dom: Domain = { 
    domain.DomainId;
    domain.ContextId;
    domain.DomainName;
    domain.DomainDoc;
    domain.DomainDeleted
}
``
## Pros and Cons 

Pro: Shorter record definitions.
Con: A bit more syntax added to F#.
 Extra compilation time, a bit.

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  
M, but I have NO INSIGHT HERE.

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [X] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [X] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [ ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by BentTranberg** [comment]
I don't see the need for this, as it's covered by [#722 - record type constructors](https://github.com/fsharp/fslang-suggestions/issues/722).

**Comment by cmdoffing** [comment]
Ok, thanks for the reply.

**Comment by brianrourkeboll** [comment]
There is actually already an approved suggestion for this: #653.

**Comment by brianrourkeboll** [comment]
> >  (something that looks very similar to) 
> 
> That's for an anonymous record.  It's not clear at first glance but, the OP example is for where the record type Domain has already been defined and an instance is being created.
> 
> 

#653 is meant to apply to both nominal and anonymous records:

> I propose we allow both records and anonymous records to imply record labels from a limited range of expressions
