### ISSUE TITLE
Allow constructor for Unit

### ISSUE THREAD

**Issue by charlesroddie** [fsharp/fslang-suggestions#1389]
**I propose we**

Unhide the `Unit()` constructor.

**The existing way of approaching this problem in C# is** ...

1. Try to use `new Unit()` and get an error `unit does not contain a constructor that takes 0 arguments`.
2. Research the internal representation of `Unit` in F# and find that it is `null`.
3. Write `null` and get an NRT error.
4. Write `null!`, i.e. claiming that the null is not null.

## Pros and Cons 

**The advantages of making this adjustment to F# are** ...

- Ability to use Unit sensibly in C#/F# interop.
- Ability to use methods of Unit without NREs.

**The disadvantages of making this adjustment to F# are** ...

If there is a phase 2 of this, to make Unit constructs always non-null (e.g. when using `()` in F#), then it may break some low-level code which depends on the existing hack.

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  

S

**Related suggestions:** (put links to related suggestions here)

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [ x ] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [ x ] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [ x ] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [ x ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [ x ] This is not a breaking change to the F# language design
* [ x ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by T-Gro** [comment]
With F# NRTs (Nullable Reference Type), symbols exposing a type with null representation at runtime are marked as if they always were nullable (because from a C# perspective, they are). This covers both Unit and Option.

If there is e.g. a function taking unit as an argument, C# should not complain when seeing null passed in - and if it does, we would need to find out which other metadata to expose for C# to understand that.


Can we please ask for a sensible consumption from C# where this happens, and where C# complains if null is passed in?
(I can imagine scenarios with generics requiring a "not null" type instance, but those should rightfully reject Unit - example being TKey in a Dictionary)

**Comment by charlesroddie** [comment]
I get an error on:
```
Unit u = null;
```

I got the error in this context:
```
// F# definition
type WrappedEmailer(emailer:IEmailer, actionOnEmail: (string * string list) -> unit) =

// C# usage
public AddNewUsers()
{
    var actionOnEmail = new Func<Tuple<string, FSharpList<string>>, Unit>(email =>
        {
            // do stuff
            return null!; // Internal F# representation of Unit. `null` gives a CS8603 error, there are no static methods on `Unit`, and attempts to access the constructor give `no constructor with 0 arguments`.
        });
    sendEmailer = new WrappedEmailer(AccountsEmailer, Microsoft.FSharp.Core.FuncConvert.FromFunc(actionOnEmail));
}
```

**Comment by vzarytovskii** [comment]
@charlesroddie would `return default` work in C#?

**Comment by voronoipotato** [comment]
Typically anywhere you would require normally returning a unit you can just "not return" in C#. While I can appreciate the explicit and more formally correct nature of the suggestion, it does feel a bit non-idiomatic for C# consumers to return "unit".
