### ISSUE TITLE
Allow fun arrows to start after a line break

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#139]
# Allow fun arrows to start after a line break [16448692] #

**Submitted by Mark Seemann on 10/1/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

As described here: https://github.com/Microsoft/visualfsharp/issues/1551

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16448692)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16448692-allow-fun-arrows-to-start-after-a-line-break.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 and we decided against it. Closing per policy not to revisit issues already considered and decided against, unless circumstances have changed.
