### ISSUE TITLE
Bug: Non-Nullable Implementation Errors

### ISSUE THREAD

**Issue by RealmPlume** [fsharp/fslang-suggestions#1391]
The following example references `Newtonsoft.Json`:
`
      use stream = new StreamReader(filename)
      use reader = new JsonTextReader(stream)
      let serializer = new JsonSerializer()
      serializer.Deserialize<'T>(reader)
`
![image](https://github.com/user-attachments/assets/4990f760-5f1b-40a8-972d-bb3906bf01b5)

I don't understand why the return type is `'T | null` instead of `'T`

`'T` not only needs to support reference types, but also needs to support reference types

The above code cannot avoid warning 3261 in F#.

but, no warning will appear when nullable is enabled in C#

**Comment by vzarytovskii** [comment]
Please create an issue in the dotnet/fsharp repo. This one is for language suggestions. I can't move it because it's in different org.
