### ISSUE TITLE
Expand constant folding

### ISSUE THREAD

**Issue by Xyncgas** [fsharp/fslang-suggestions#1397]
I can provide use case :
    I would be allowed to write a function that's called and executed and output a constant in the final compiled program
    The function can accept unions as one of its parameter
    I now can create a simple structure that takes union cases in its parameters and it calls the function I wrote
    The function now can go through the parameters I passed to it from the parameters in the constructor
    The object is now created
    The object's property was accessed to be assigned to a variable
    Everything is folded together so the variable itself is a constant

```
    [<Struct>]
    type parameters =
    | A of A : int
    | B of B : uint64
    with
        static member op_Implicit (arg :int)    = A(arg)
        static member op_Implicit (arg :uint64) = B(arg)

    let my_constexpr (args :parameters array) =
        let mutable output = 0UL
        for arg in args do
            match arg with
            | A a -> output <- output + (uint64 a)
            | B b -> output <- output + b
        output

    type s_struct =
        struct
            val integer : uint64
            new ([<ParamArray>] arg) =
                {integer = my_constexpr arg}
        end

    let client () =
        let constant = s_struct(1,2,3,4,5,1UL,2UL,3UL,4UL,5UL).integer //should be constant
        constant
```

**Comment by jwosty** [comment]
Weaker forms of arbitrary compile time expression evaluation has already been turned down: https://github.com/fsharp/fslang-suggestions/issues/804#issuecomment-1506726622

And certainly it would not be accepted when there's any kind of mutability or side effects involved like in the example given.

**Comment by vzarytovskii** [comment]
Yes, it's not considered at this time, closing as per comments in the previous suggestion.

**Comment by T-Gro** [comment]
AFAIK .NET JIT does have it and you can achieve it with NativeAOT - for constants and static expressions. I don't think F# compiler should duplicate the efforts here.

**Comment by Xyncgas** [comment]
Interesting thanks
