### ISSUE TITLE
Provide Intellisense on 'tab' key when creating 'new' classes or types.

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#141]
**Submitted by Matt on 10/3/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

I would like to have the ability to hit the "tab key" when creating a new type with a constructor that will list the types available properties.
I C# this is done nicely with classes and as you assign a value the property is no longer available in intellisense when one tabs again to select another property.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16482547)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16482547-provide-intellisense-on-tab-key-when-creating.md#comments)

**Comment by dsyme** [comment]
This is a tooling issue, not part of the language design.
