### ISSUE TITLE
1-spit Assembly code (or LLVM code) in Repl on each highlighted code piece, for visibility into debugging eg. tail calls, speed of executioa

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#142]
Spit Assembly code (or LLVM code) in Repl on each highlighted code piece, for visibility into debugging eg. tail calls, speed of executioa [16514236] #

**Submitted by Musa on 10/5/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16514236)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16514236-1-spit-assembly-code-or-llvm-code-in-repl-on-ea.md#comments)

**Comment by dsyme** [comment]
This is a tooling issue rather than language design.  Closing here.  If you can find a way to do this, please submit to the F# compiler repo
