### ISSUE TITLE
Close User Voice in favor of GitHub issues.

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#144]
# Close User Voice in favor of GitHub issues. [16529041] #

**Submitted by Krzysztof Cieslak on 10/6/2016 12:00:00 AM**  
**299 votes on UserVoice prior to migration**  

I really believe we should close UserVoice in favor of using GitHub issues (maybe separate repository for it? ). Here are few reasons for it:
* Bad UX
* Need to monitor and maintain separate communication channel
* No comment editing
* No markup for code samples
* No markdown
* Can't embed images
* No mentions and notifications
* Only 10 votes which reduce people ability to vote (especially in so old project as F# - many people already used all their votes over the years)
* No more fake accounts to workaround votes limit
* God damn this text editor (writing long message [like this] i terrible in editor showing 5 lines)
* GitHub issues can be labeled, milestones can be added, new projects feature can be used
Similar move was done by VSCode Team - https://code.visualstudio.com/blogs/2016/08/19/goodbyeuservoice - and I strongly believe we should do the same.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16529041)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16529041-close-user-voice-in-favor-of-github-issues.md#comments)

**Comment by sergey-tihon** [comment]
Sounds like a resolved issue 😄

**Comment by dsyme** [comment]
Resolved!
