### ISSUE TITLE
Better PR efforts: Write a client library to run F# code on the D-Wave quantum computers

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#145]
# Better PR efforts: Write a client library to run F# code on the D-Wave quantum computers [16710157] #

**Submitted by Alexei Odeychuk on 10/18/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

Quantum computing attracts a lot of attention from scientists and software developers.
I suggest writing a client library to run F# code on the D-Wave quantum computers in order to improve F# visibility and popularity among software developers and scientists specializing in optimization, machine learning, pattern recognition and anomaly detection, financial analysis, software/hardware verification and validation, scheduling and logistics, bioinformatics.
The world's first commercial quantum computer (D-Wave One) was built in 2010 by the D-Wave Systems Inc. (offices in Palo Alto, CA, Washington, DC, and Burnaby, British Columbia, Canada). In 2013 the D-Wave Systems Inc. shipped a 512-qubit D-Wave Two system. The D-Wave superconducting quantum computers are being used by Lockheed-Martin, Google, NASA, and USC. For example, NASA's quantum computer solved a problem 100 million times faster than a conventional computer could ( http://www.popularmechanics.com/technology/gadgets/a18475/google-nasa-d-wave-quantum-computer ). In 2015 the D-Wave Systems Inc. announced general availability of the 1000+ qubit D-Wave 2X system. In September 2016 the D-Wave Systems Inc. announced details of its most advanced quantum computing system, featuring a new 2000-qubit processor. The new processor doubles the number of qubits over the previous generation D-Wave 2X system, enabling larger problems to be solved and extending D-Wave’s significant lead over all quantum computing competitors. The new system also introduces control features that allow users to tune the quantum computational process to solve problems faster and find more diverse solutions when they exist. In early tests these new features have yielded performance improvements of up to 1000 times over the D-Wave 2X quantum computer ( http://www.dwavesys.com/press-releases/d-wave-systems-previews-2000-qubit-quantum-system ).
The D-Wave Systems Inc. is focusing on putting the quantum computers to work solving industry-scale classification, learning, and optimization problems.
Just as the classical computer world needed a software ecosystem to spur usage and development, quantum computers do as well.
The D-Wave Systems quantum computer has a web API with client libraries available for C, C++, Python and MATLAB ( http://www.dwavesys.com/software ). This interface allows THE MACHINE to be EASILY ACCESSED AS A CLOUD RESOURCE OVER A NETWORK. Using development tools and client libraries, users can write code in any language supported.
BOTTOM-LINE ISSUE: Where is a client library for F#?
I think Don Syme as an a Principal Researcher at Microsoft Research and the Microsoft F# development team (the Microsoft top management can also be asked to participate in negotiations, if needed) are able to quickly find a common language with the D-Wave Systems leadership ( http://www.dwavesys.com/our-company/leadership ), obtain source code of client libraries in C, C++ etc., open a new GitHub project and attract Microsoft and non-Microsoft (if needed) contributors, port the client library to F#, obtain network access to a quantum computer, and compile, run and test the F# client library for correctness on the real quantum machine. It would be mutually beneficial cooperation between Microsoft, D-Wave Systems Inc., and F# developers.
It may happen that such an effort would enrich F# with quantum data types, quantum programming facilities from the QCL high-level, architecture independent programming language for quantum computers ( http://www.devtopics.com/qcl-obscure-programming-language-of-the-month/ ; http://tph.tuwien.ac.at/~oemer/qcl.html ).
In any case, it would be a huge PR effort to promote F# as a modern, efficient, functional-first language for data processing on both classical and quantum computers.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16710157)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-16710157-better-pr-efforts-write-a-client-library-to-run.md#comments)

**Comment by dsyme** [comment]
Amusing, but closing :)
