### ISSUE TITLE
Enable a compiler-warning when a recursive algorithm is not tail-recursive [ RFC FS-1011 ]

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#147]
**Submitted by knocte on 3/21/2014 12:00:00 AM**  
**311 votes on UserVoice prior to migration**  

Add an TailRecursiveAttribute to enable a compiler-warning when a recursive algorithm is not tail-recursive. This should ideally also cover recursive `seq { .. }` and `async { ... }` expressions.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663074)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663074-enable-a-compiler-warning-when-a-recursive-algori.md#comments)

**Comment by dsyme** [comment]
## Response ##
** by fslang-admin on 8/3/2015 12:00:00 AM **

I am generally in favour of addressing this in F# 4.x+. I would want ``seq { .. }`` and ``async { … }`` tailcalls to also be addressed. A more detailed design is needed and some trialling would be great. Jack’s work is a great start. However, this is not an easy piece of work to do in a non-invasive way and my own experiments in this area have not yet led to something I feel confident to include in the F# language design.

An implementation and testing would need to be provided by someone in the F# community (possibly including Microsoft or Microsoft Research, though not limited to them).
Currently, initial implementations of approved language design can be submitted as pull requests to the appropriate branch of https://github.com/Microsoft/visualfsharp. See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for info on how to contribute to the F# language/core library design

I encourage you to consider continue working towards a detailed proposal and a proposed implementation. I will gladly help.

Don Syme, F# Language and Core Library Evolution

**Comment by dsyme** [comment]
RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1011-warn-on-recursive-without-tail-call.md

**Comment by cartermp** [comment]
Closing in favor of #721 which has more details
