### ISSUE TITLE
Emit `Optional;DefaultParameterValue` by default for interop between F# and C#

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#156]
**Submitted by Gustavo Guerra on 3/21/2014 12:00:00 AM**  
**20 votes on UserVoice prior to migration**  

It would be nice if the F# compiler automatically inserted `[<Optional;DefaultParameterValue(null)>]` in all optional parameters of methods declared in F# classes, so they would be easier to use from C#
It would also be nice if the constructors of records also used this for parameters of type Option<_>

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663298)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663298-improve-optional-parameter-interop-between-f-and.md#comments)

**Comment by dsyme** [comment]
** by fslang-admin on 8/3/2015 12:00:00 AM **

This proposal is “approved in principle” for F# 4.x+.  An RFC is needed.

Don Syme, F# Language and Core Library Evolution

**Comment by dsyme** [comment]
We're not going to do this by default, but you can add the attribute manually, see https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1027-complete-optional-defaultparametervalue.md

**Comment by ovatsus** [comment]
Could we reconsider doing it by default? Would there be any downside on doing it? I can prepare an RFC

**Comment by dsyme** [comment]
I think this is subsumed by #1167
