### ISSUE TITLE
Syntax for turning properties into functions

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#159]
**Submitted by Gustavo Guerra on 3/21/2014 12:00:00 AM**  
**457 votes on UserVoice prior to migration**  

When we have F# records and classes (including the ones generated by type providers), we end up having to write things like this a lot: `(fun x -> x.Name)`
It would be nice to have some shorthand for this, similar to what we can do with static members (but nicer than the Scala syntax please)

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663326)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663326-syntax-for-turning-properties-into-functions.md#comments)

**Comment by dsyme** [comment]
Closed in favour of https://github.com/fsharp/fslang-suggestions/issues/506 where active discussion is happening
