### ISSUE TITLE
Covariance/contravariance language support 

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#162]
**Submitted by Eriawan Kusumawardhono on 3/21/2014 12:00:00 AM**  
**150 votes on UserVoice prior to migration**  

Covariance/contravariance has its beginning in CLR 2.0 and also with the introduction of generics in .NET 2.0 (also in F#, C# and VB)

Then in C# 4.0 and VB 10, we have covariance/contravariance supports in the language itself. Currently we don't have support for these covariance and contravariance in F#.

I know it is a runtime feature of CLR 2.0 and 4.0 and I don't want to play catch up with C# and VB.
But this covariance/contravariance support in C# and VB are powerful to use and also have proven to provide cleaner and clearer ways to understand the code and variances in the types, especially when using parameterized generic types.

This is not the same as this feedback:
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2363794-ocaml-like-variance-annotations-a-and-a-

but we can use that OCaml syntax as well for starter.

This feature should also be constrained to only use covariance/contravariance in interfaces and delegates just like in C# and VB, but F# may provide more supports for other types such as events.
An example of this is the way F# has provided the capability to create extensions to properties and methods, not just methods only in C# and VB.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663470)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663470-provide-covariance-contravariance-language-suppor.md#comments)

**Comment by kurtschelfthout** [comment]
Is it worth creating a separate suggestion to allow just the declaration of variant delegates and interface, without changing anything else in F#? This would allow exposing such delegates and interfaces to C#/VB consumers from F# without having to go through the rigmarole of having a separate C# assembly, e.g. see https://github.com/fscheck/FsCheck/issues/296

**Comment by dsyme** [comment]
@kurtschelfthout Hmmm... I suppose we could do that.  It's reasonable to be able to declare these , e.g. an attribute.

**Comment by auduchinok** [comment]
I'd like to note that recently closed https://github.com/Microsoft/visualfsharp/issues/5277 is about not being able to consume types with such parameters, not about defining them in F#.

**Comment by vhogemann** [comment]
Been recently bitten by this. In my case I just wanted to create a simple wrapper function for declaring dependencies using SimpleInjector, like this

`let registerServiceForInterface<'I,'S when 'S :> 'I> (container:Container):Container = ...`

Ended up having to come up with a solution that uses dynamic casting... not nice.

**Comment by kunjee17** [comment]
I guess this could be issue. 

Recently I am trying to port ML.net samples and stuck at a place because of this

New dynamic api allows pipelining. But to pipe line I need to have all classes in `IEstimator<ITranformer>` type. That couldn't be possible. 

Here is code to mimic the issue. 

`public sealed class CategoricalEstimator : IEstimator<CategoricalTransform>` which implement an interface. So, I can type cast to ` IEstimator<CategoricalTransform>` but again `public sealed class CategoricalTransform : ITransformer, ICanSaveModel` is the case. So, now I can cast `IEstimator<CategoricalTransform>` into `IEstimator<ITranformer>` and because of that I am unable to create pipeline for ML sample. 

It would be great if some one can help on this. @dsyme  @cartermp 

PS: If this is not possible at all then, it would be good to create issue on ML.net library? for better F# support?

**Comment by IvanAntipov** [comment]
Here's my work around. It is ugly, but it seems to work.
```

let ldaTransform = ml.Transforms.Text.LatentDirichletAllocation(inputColumnName = text_a_fieldName, outputColumnName = ldaFeatures, numTopic = 3)

type WrapCastEstimator(estimator: IEstimator<TransformWrapper>)  =
    interface IEstimator<ITransformer>  with
        member __.Fit(input: IDataView) : ITransformer = estimator.Fit(input) :> ITransformer        
        member __.GetOutputSchema(inputSchema : SchemaShape): SchemaShape = estimator.GetOutputSchema(inputSchema)
        
let wrapCastEstimator (estimator : IEstimator<TransformWrapper>)  = WrapCastEstimator(estimator) :> IEstimator<ITransformer>

let bagOfWordEstimator = ml.Transforms.Text.ProduceWordBags(text_a_fieldName) :> TrainedWrapperEstimatorBase :> IEstimator<TransformWrapper> |> wrapCastEstimator
let pipeline = 
    (bagOfWordEstimator)
        .Append(ldaTransform)
```

**Comment by reinux** [comment]
Gotchas like this end up becoming a giant time sink. I spent several hours trying to figure out that I need to write a `cast` function, which, frustratingly, does literally nothing but makes the compiler happy anyway.

```
type PolyType = interface end
type Convex = inherit PolyType
type Concave = inherit PolyType

// No problem!
type Polygon<'t when 't :> PolyType> = Polygon of (float*float) list

// Flexible types -- cool, no problem!
let printPoly (p:Polygon<#PolyType>) = printfn "%A" p

let p : Polygon<Convex> = Polygon [0.,0.]
printPoly p

// Wait, you can't use flexible types here? Well, whatever I'll just have to cast later
//type PolyGroup = PolyGroup of Polygon<#PolyType> list

// Well, whatever, I'll just have to cast when I lift to PolyGroup
type PolyGroup = PolyGroup of Polygon<PolyType> list

// Okay... well, without flexible types, it's not much of a surprise that this won't compile
//let p : Polygon<Convex> = Polygon [0.,0.]
//PolyGroup [p]

// Wait... how am I even supposed to cast this?!
let p' : Polygon<PolyType> = match p with Polygon p -> Polygon p
PolyGroup [p']

// Okay... that's kind of ugly, but it works. Let's see if I can at least make a function to generalize this
let cast p = match p with Polygon p -> Polygon p
// It works. And cast's type is Polygon<#PolyType> -> Polygon<#PolyType>
// What...
PolyGroup [cast p]
```

**Comment by teo-tsirpanis** [comment]
Until co(ntra)variance gets natively supported by F#, anyone interested can use [Covarsky](https://github.com/teo-tsirpanis/Covarsky).

**Comment by NinoFloris** [comment]
Neat, can remove our own variance weaver from the codebase. Thanks @teo-tsirpanis

**Comment by teo-tsirpanis** [comment]
@NinoFloris, you are welcome. Let me know if everything went well with your migration, or you need some help. 🙂

**Comment by isaacabraham** [comment]
I've tried to create a simple example of one of the issues we're seeing in Farmer [here](https://gist.github.com/isaacabraham/a184e2a3f97f607ca965e7a71abb64dd).

Basically we have many concrete instances of an interface that are treated in the same way. But you need to "know about" this interface and explicitly upcast values into it whenever you work with lists. Flexible types get you some of the way but have a couple of restrictions:

1. They change the signature from a nominal type (the interface) to a generic type that happens to implement that interface.
2. The constraints don't participate into overload resolution, so you can't have multiple overloads that only differ by the interface that the flexible type is on.

You can sort of work around the lack of covariance / contravariance with flexible types but it's kind of confusing and I quickly ran into issues.

**Comment by uxsoft** [comment]
Here's another example from the wild:

```fsharp
    type IView =
        abstract member ViewType: Type with get
        abstract member Attrs: IAttr list with get
        
    type IView<'viewType> =
        inherit IView
        abstract member Attrs: IAttr<'viewType> list with get
        
    type View<'viewType> =
        { ViewType: Type
          Attrs: IAttr<'viewType> list }
        
        interface IView with
            member this.ViewType =  this.ViewType
            member this.Attrs =
                this.Attrs |> List.map (fun attr -> attr :> IAttr)
            
        interface IView<'viewType> with
            member this.Attrs = this.Attrs
```
The solution here is to declare non-generic IView and inherit that. Which gives 2x as much implementation code in many cases. 

Source: [https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI/Types.fs](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI/Types.fs)

Personally, I think F# could use covariance for generic types:
- It's very much aligned with the succinct, performant code of F#
- Increases feature parity with C#/.NET
- Help's C# developers learn F# and find features they know to behave as they expect

**Comment by dsyme** [comment]
I'm curious that this issue doesn't get more commentary or requests. 

I'm actually going to decline this, because I don't think we'll ever add this to F# and it's really not that commonly needed, and it does raise various compat issues.  I could see it possibly being included in some eventual son-of-F#  - it's not that it's inconsistent with the design.

**Comment by reinux** [comment]
> eventual son-of-F#

I've been wondering for years if this is something that's being considered. Would be really cool. Been over a decade since I studied compilers but I'd love to contribute in any way I can 😁

**Comment by baronfel** [comment]
I'd like to revisit this a bit. The lack of variance support is a contributing factor to the need to make F#-friendly wrappers for BCL types (to say nothing of the larger .NET Ecosystem). This is additional work that we push onto our community. I think the compiler should tackle this support in one place to reduce the burden on users. There are a number of BCL types that make use of variance annotations that are often quite widely used:

* There are at least [46 types with generic `out` parameters](https://github.com/search?q=repo%3Adotnet%2Fruntime+%22%3Cin+T%22+path%3Asrc%2Flibraries&type=code) in the BCL
* There are at least [26 types with generic `in` parameters](https://github.com/search?q=repo%3Adotnet%2Fruntime+%22%3Cin+T%22+path%3Asrc%2Flibraries&type=code) in the BCL

and that's just a very quick search. A few more searches across the broader GitHub corpus show more than 25k hits for each kind of variance across massively popular packages like Akka.Net, Rx.Net/Reactive, database technologies like Marten and elasticsearch, etc. It feels like the kind of rough edge that has inspired a ton of wrappers that we could potentially do away with via a single feature.

**Comment by T-Gro** [comment]
@dsyme:

What about a reduced version of this suggestion, only focused on consumption of covariant interfaces for interop scenarios?
Could it in theory be used in a way of making methods of C#-defined covariant interfaces look like they support flexible types?

**Comment by dsyme** [comment]
> What about a reduced version of this suggestion, only focused on consumption of covariant interfaces for interop scenarios?Could it in theory be used in a way of making methods of C#-defined covariant interfaces look like they support flexible types?

Yes, it's probably technically possible. It would however be a breaking change to F# type inference, making code more generic than before.  If that could be navigated somehow then co-variance could probably be added to F# proper tbh.

Contra-variance is harder as F# type inference eliminates `C :> 'T` constraints eagerly to equations. This is also why `'U :> 'T` constraints are eliminated/ignored. In both these cases, if `'T` is guaranteed to be a known nominal type (e.g. from context or an explicit type instantiation) then these could be dealt with.  However in the implementation of type inference it's quite tricky to know that `'T` is about to be instantiated that way.

**Comment by dsyme** [comment]
> Yes, it's probably technically possible. It would however be a breaking change to F# type inference, making code more generic than before. If that could be navigated somehow then co-variance could probably be added to F# proper tbh.

To be clearer: given the strong community-led dynamic for F# at the moment, I wouldn't "stand in the way" of co-variance being added if the technical problems are solved - I know the community would generally like it to be available at least for interop.  But the backwards-compat issues are signficant and would probably need an explicit opt-in.

**Comment by dsyme** [comment]
@T-Gro @baronfel Could you create a separate issue for co-variance specifically, with the above caveats? It can be pre-marked approved-in-principle.

Thanks!

**Comment by TheAngryByrd** [comment]
Adding some of my recent experience in this area.

I did some work in IcedTasks to [extract out](https://github.com/TheAngryByrd/IcedTasks/pull/34) the AsyncMethodBuilder (like [AsyncTaskMethodBuilder](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.asynctaskmethodbuilder?view=net-8.0) or [PoolingAsyncValueTaskMethodBuilder TResult](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.poolingasyncvaluetaskmethodbuilder-1?view=net-8.0)) as keeping so many version of the various ValueTask, PooingValueTask and Task builders is a lot of code.

To do this I have to use STRP to invoke some of the MethodBuilder's methods like `AwaitUnsafeOnCompleted`.

```fsharp
    static member inline AwaitUnsafeOnCompleted<'Builder, 'TAwaiter, 'TStateMachine
        when 'Builder: (member AwaitUnsafeOnCompleted:
            byref<'TAwaiter> * byref<'TStateMachine> -> unit)
        and 'TAwaiter :> ICriticalNotifyCompletion
        and 'TStateMachine :> IAsyncStateMachine>
        (
            builder: byref<'Builder>,
            awaiter: byref<'TAwaiter>,
            stateMachine: byref<'TStateMachine>
        ) =
        builder.AwaitUnsafeOnCompleted(&awaiter, &stateMachine)
```

Which corresponds to the C# signature:

```csharp
        public void AwaitUnsafeOnCompleted<TAwaiter, TStateMachine>(ref TAwaiter awaiter, ref TStateMachine stateMachine)
            where TAwaiter : ICriticalNotifyCompletion
            where TStateMachine : IAsyncStateMachine =>
```


Take notice of the `awaiter: byref<'TAwaiter>` 

I occasionally have hit some problems like:

```
error FS0041: No overloads match for method 'Using'.↔↔Known types of arguments: IAsyncDisposable * (IAsyncDisposable -> TaskBaseCode<int,int,^a>) when ^a: (member AwaitUnsafeOnCompleted: byref<Runtime.CompilerServices.YieldAwaitable.YieldAwaiter> * byref<CompilerServices.ResumableStateMachine<TaskBaseStateMachineData<int,^a>>> -> unit)↔↔Available overloads:↔ 

- member TaskBuilderBase.Using: resource: 'a * binder: ('a -> TaskBaseCode<'TOverall,'T,'Builder>) -> CompilerServices.ResumableCode<TaskBaseStateMachineData<'TOverall,'Builder>,'T> when 'a :> IDisposable // Argument 'resource' doesn't match↔ 

- member TaskBuilderBase.Using: resource: 'a * binder: ('a -> TaskBaseCode<'TOverall,'T,^Builder>) -> TaskBaseCode<'TOverall,'T,^Builder> when 'a :> IAsyncDisposable and ^Builder: (member AwaitUnsafeOnCompleted: byref<Runtime.CompilerServices.ICriticalNotifyCompletion> * byref<CompilerServices.ResumableStateMachine<TaskBaseStateMachineData<'TOverall,^Builder>>> -> unit) // Argument 'binder' doesn't match [C:\Users\jimmy\Repositories\public\TheAngryByrd\IcedTasks2\tests\IcedTasks.Tests.NS21\IcedTasks.Tests.NS21.fsproj::TargetFramework=net6.0]
```

The notable thing here is `byref<Runtime.CompilerServices.YieldAwaitable.YieldAwaiter>` is not compatible with `byref<Runtime.CompilerServices.ICriticalNotifyCompletion>`. Which I think covariance is the limit here.

**Comment by nkosi23** [comment]
@dsyme @T-Gro @baronfel has the issue been created? This would be a nice quality of life improvement.

**Comment by T-Gro** [comment]
Not yet.
Following the discussion above - if anyone wants to create a separate specific and detailed-out suggestion, it can be preapproved and moved to an RFC. Especially changes related to type inference and method resolution come to mind as important aspects to cover.

**Comment by IS4Code** [comment]
Would a weaker form of this proposal work? I.e. to have `[<Covariant>]` and `[<Contravariant>]` on parameters, and the compiler would just check if the signatures of all methods use them in a valid way. Then at least such types could be authored from F# to be used in other .NET languages.

**Comment by T-Gro** [comment]
Yes, this can approved as an interop metadata feature.
F# would then only check valid placement and would do the appropriate IL codegen.

Optionally, this could also flow via automatic generalization.
