### ISSUE TITLE
Add support for implicit operators to facilitate language interop

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#165]
**Submitted by Nelak on 3/21/2014 12:00:00 AM**  
**15 votes on UserVoice prior to migration**  

Add support for implicit operators to facilitate language interop instead of having to write an explicit operator like:

http://stackoverflow.com/questions/10719770/is-there-anyway-to-use-c-sharp-implicit-operators-from-f

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663709)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663709-add-support-for-implicit-operators-to-facilitate.md#comments)

**Comment by dsyme** [comment]
Implemented as part of https://github.com/fsharp/fslang-design/blob/main/preview/FS-1093-additional-conversions.md to the extent we're going to do this
