### ISSUE TITLE
Implement IReadOnlyCollection<'T> in list<'T>

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#181]
**Submitted by Petr Onderka on 3/21/2014 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

.Net 4.5 has a new type IReadOnlyCollection<'T> and list<'T> (a.k.a. FSharpList<'T>) fits this interface precisely, so I think it should implement it.
Original on VS uservoice: http://visualstudio.uservoice.com/forums/121579/suggestions/2902147

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5664936)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5664936-implement-ireadonlycollection-t-in-list-t.md#comments)

**Comment by dsyme** [comment]
** by fslang-admin on 7/18/2015 12:00:00 AM **

This is approved for inclusion in a future release of the F# core library subject to an implementation. An RFC is needed, please submit one if one hasn't been submitted already

Don Syme, F# Language and Core Library Evolution.

**Comment by jack-pappas** [comment]
@dsyme Why is an RFC needed for this? It's not a language change, and seems like any discussion could take place here or another issue when a PR is submitted. (I'm trying to understand this new suggestion/RFC process, I've been out of the loop for several months.)

**Comment by dsyme** [comment]
@jack-pappas An RFC is needed primarily for book-keeping, and as a place to discuss ramifications - for example AFAIK this change requires a dependency on .NET 4.5 (which is OK now, but wasn't once-upon-a-time)

**Comment by dsyme** [comment]
@jack-pappas Basically we want all publically-visible design changes to langauge and core library have matching RFCs

**Comment by dsyme** [comment]
This has been implemented
