### ISSUE TITLE
Implement monadic getters and setters

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#211]
**Submitted by Anonymous on 3/24/2014 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

The get/set syntax for F# is very cool, but it has an issue: sometimes, the property we would like to get and set is only available through a workflow/monad, like the async workflow.
Thus, I would like to alter the typechecking rules for getters and setters. This is what they are right now (pseudocode) for the Async monad:
```fsharp
Property x : Async<'a>
get : unit -> Async<'a>
set : Async<'a> -> unit
IndexedProperty x : 'k -> Async<'v>
get : 'k -> Async<'v>
set : 'k -> Async<'v> -> 'unit
```
This is what I would like to see made possible:
```fsharp
type Id<'a> = 'a
Property x : Async<'a>
get : unit -> Async<'a>
set : 'a -> Async<unit>
IndexedProperty x : 'k -> Async<'v>
get : 'k -> Async<'v>
set : 'k -> 'v -> Async<unit>
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5675548)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5675548-implement-monadic-getters-and-setters.md#comments)

**Comment by dsyme** [comment]
Closing this old issue that has seen little traction.
