### ISSUE TITLE
Disable compiler warnings per line

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#214]
# Disable compiler warnings per line [5676502]

**Submitted by Steven Taylor on 3/25/2014 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

Over time, the value of warnings get noisy and their value goes down if there's not a simple way to partition them into "as intended" and "could be a problem" buckets. Also, it would be good to ignore the "as intended" ones (is there a better way to do this than introduce an ugly pragma?).
Example: a warning pops up such as "This construct causes code to be less generic than indicated by...", you investigate, and determine that this is intentional. Normally you would not allow the way the doSomething function works, but in this case it is succinct, and you think an okay way to proceed given <insert situation & context here> .
## Response

*\* by fslang-admin on 2/3/2016 12:00:00 AM **

Close enough to being a duplicate of /archive/suggestion-6085102-allow-f-compiler-directives-like-nowarn-to-span

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5676502)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5676502-disable-compiler-warnings-per-line.md#comments)

**Comment by abelbraaksma** [comment]
This was closed at the time in favor of #278

**Comment by abelbraaksma** [comment]
This was closed at the time in favor of #278
