### ISSUE TITLE
Make .Tag and .Is* discriminated union properties visible from F#

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#222]
**Submitted by Loic Denuziere on 3/26/2014 12:00:00 AM**  
**15 votes on UserVoice prior to migration**  

The .NET class that encodes a discriminated union has `.Is* : bool` properties, for example this:

```
type Foo = A | B
```

has the following:

```
member IsA : bool
member IsB : bool
```

They are hidden from F#, but they could actually be quite useful. I regularly find myself writing something like this:

```
List.filter (function A -> true | _ -> false)
```

when I could write:

```
List.filter (fun x -> x.IsA)
```
## Response

*\* by fslang-admin on 8/3/2015 12:00:00 AM **

This proposal is “approved in principle” for F# 4.0+. It would make a good addition to F#. (I don’t think the loss of purity (e.g. wr.t. ordering of union cases) is a critical problem and I believe you can turn of the DefaultAugmentation in any case)
Some technical issues may need to be ironed out during implementation.
If this is done, the Tag properties present on these types should also be revealed, that is covered by a separate item.
An implementation and testing would need to be provided by someone in the F# community (possibly including Microsoft or Microsoft Research, though not limited to them).
Implementations of approved language design can now be submitted as pull requests to the appropriate branch of http://github.com/Microsoft/visualfsharp. See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for information on contributing to the F# language and core library..
I’d be glad to help guide people through the implementation process.
If you strongly think this should not be approved please chime in with your technical feedback.
Thanks
Don Syme, F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5683698)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5683698-make-tag-and-is-discriminated-union-properties.md#comments)

**Comment by abelbraaksma** [comment]
Looks like an RFC is being made: https://github.com/Tarmil/fslang-design/blob/7d0ec73f6720730562875633bf3d7a97384b5d25/RFCs/FS-1079-union-properties-visible.md

Note that the original discussion (link to archived uservoice discussion) leads to a 404. Would be nice to see the relevant discussion bits so that we can help comment on the design. Anybody (@cartermp?) know where the archives are? Looks like many links now lead to 404s.

Btw, I'm myself now sure about this addition. Especially newcomers might be tempted to use imperative approaches once these properties are made available.

**Comment by cartermp** [comment]
No clue. UserVoice was before my time and I don't know who owns the fslang one.

What kind of imperative code do you fear will creep up here? I generally like it because it simplifies a fairly common pattern, and already has symmetry with `IsSome` and `IsNone` members on the option type.

**Comment by rmunn** [comment]
The original UserVoice suggestion and comments can be seen here:

https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-5683698-make-tag-and-is-discriminated-union-properties.md

**Comment by jackfoxy** [comment]
I run into this situation a lot. Love that this is now an RFC.

**Comment by jkone27** [comment]
Hey guys, this would be very handy, any recent news on this (as it's open for 1 year already I see). F# is awesome 🆗 ❗ 👍

**Comment by GratianPlume** [comment]
I think FSharp’s public Tag attribute for discriminated unions is a very unsafe method, but sometimes it is very useful. Maybe a compromise method is better: the Tag attribute is accessible when the Tag value is explicitly specified. But I haven’t figured out how to explicitly specify the Tag value.

**Comment by kerams** [comment]
We can close.
