### ISSUE TITLE
Allow open in local declarations like in Standard ML and O'Caml (>= 3.12)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#227]
# Allow open in local declarations like in Standard ML and O'Caml (>= 3.12) [5690218] #

**Submitted by Anonymous on 3/27/2014 12:00:00 AM**  
**67 votes on UserVoice prior to migration**  

See e.g. http://www.mpi-sws.org/~rossberg/sml-vs-ocaml.html#localdecs

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5690218)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5690218-allow-open-in-local-declarations-like-in-standard.md#comments)

**Comment by dsyme** [comment]
Duplicate, see https://github.com/fsharp/fslang-suggestions/issues/96
