### ISSUE TITLE
Stronger type directed conversion from functions to .Net delegates [ RFC FS-1035 ]

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#248]
**Submitted by Christoph Rüegg on 4/23/2014 12:00:00 AM**  
**25 votes on UserVoice prior to migration**  

It seems in some cases type directed conversion from functions to .Net Func<_,_> delegates only works if the called method has overloads. It would be convenient if it worked the same way for methods without overloads as well.
For example:

```fsharp
open System.Linq

let even n = n % 2 = 0
let seqA = seq { 0..2..10 }

seqA.Where(even) // works
seqA.All(even) // does not work
```
http://stackoverflow.com/questions/23256355/passing-f-function-to-ienumerable-where-vs-ienumerable-all
http://stackoverflow.com/questions/12933366/f-func-type-inference-difference-between-seq-and-pseq-todictionary

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5823074)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5823074-stronger-type-directed-conversion-from-functions.md#comments)

**Comment by Regent** [comment]
I think it would be great to have this implemented because currently this inconsistency unexpectedly breaks existing code when removing method overrides. 

The following works as expected:
```f#
type Test() =
    member this.Test(x) = x + 1 |> ignore
    member this.Test(action : System.Func<int, int>) = action.Invoke(1)
let test x = x + 1
Test().Test (test)
```

Commenting one of the methods breaks use of other method:
```f#
type Test() =
    //member this.Test(x) = x + 1 |> ignore
    member this.Test(action : System.Func<int, int>) = action.Invoke(1)
let test x = x + 1
Test().Test (test)
// This expression was expected to have type
//    System.Func<int,int>
//but here has type
//    int -> int
```

**Comment by dsyme** [comment]
@Regent Yes, agreed

**Comment by smoothdeveloper** [comment]
Slightly related to this suggestion, I'm facing a case where having overloads is causing problem with type inference:

https://github.com/Microsoft/visualfsharp/issues/2503

**Comment by Regent** [comment]
Created [RFC FS-1035](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1035-consistent-delegate-type-directed-conversion.md).

**Comment by baronfel** [comment]
Would this suggestion help solve the following scenario related to function-composition-to-Func/Action-lifting?

```fsharp
open System

/// string -> unit
let print (s: string) = printfn "%s" s

/// int -> string
let stringify (i: int) = string i

/// int -> unit
let stringifyThenPrint = stringify >> print

/// int -> unit
let doit (i: int) = stringifyThenPrint i

// Action<int> -> int -> unit
let actioner (a: Action<int>) i = a.Invoke i

​(* 
   error FS: This expression was expected to have type
        'Action<int>'    
    but here has type
        'int -> unit' 
*)
let bleh = actioner stringifyThenPrint
```

**Comment by eugbaranov** [comment]
@baronfel, yes - it seems to be related to the same glitch.

**Comment by dsyme** [comment]
Closing this has been completed as part of "additional type directed conversions"

**Comment by abelbraaksma** [comment]
@dsyme, although this is closed as completed, I don't think the issue that spawned this RFC (https://github.com/dotnet/fsharp/issues/2907) is actually implemented. At least not in the current version of F#. I.e., the following (which 

```f#
type Foo =
    static member CallMe (f: Func<string, int, string>) s i =
        f.Invoke(s, i)

module Bar =
    let printInt s i = $"{s}: {i}"
    // this works, but I think that has been so for a while
    let res = Foo.CallMe printInt "The value is" 42
    // lambda DOES NOT work
    let x = Foo.CallMe (fun s i -> $"{s}: {i}") "The value is" 42
    // Curried StringFormat DOES NOT work
    let y = Foo.CallMe (sprintf "%s: %i") "The value is" 42
```

Though, to be fair, I just tried example of @baronfel, and that does work now. The `sprintf` I got from the original issue. In which case I should probably just report this as a (new) bug.

**Comment by abelbraaksma** [comment]
FWIW, the linked RFC (dead link, [it is now here](https://github.com/fsharp/fslang-design/blob/main/archived/FS-1035-consistent-delegate-type-directed-conversion.md)) was archived, and still marked "not implemented". Funnily enough, it says "as a workaround, wrap it in a lambda, works in all cases". I may be missing something, but no, it doesn't work (in all cases).

Is there another RFC that took its place? Or was it archived so it could be revisited later? (sorry for the confusion)
