### ISSUE TITLE
Add NameOf operator to follow C#/VB update

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#252]
**Submitted by amazingant on 5/8/2014 12:00:00 AM**  
**126 votes on UserVoice prior to migration**  

The Roslyn compiler currently (as of 2014-05-08) has a new NameOf operator listed as "[Planned" for both C# and VB](https://roslyn.codeplex.com/wikipage?title=Language%20Feature%20Status&referringTitle=Documentation). Pending its arrival there, it would be awesome to get something similar in F# as well.
## Response

*\* by fslang-admin on 6/17/2016 12:00:00 AM **

RFC is here: https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1003-nameof-operator.md

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5900625)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5900625-add-nameof-operator-to-follow-c-vb-update.md#comments)

**Comment by dsyme** [comment]
I'm closing this as we now have an RFC and PR for this (though the PR has not yet been accepted)

**Comment by cartermp** [comment]
Closing as this is now done

**Comment by abelbraaksma** [comment]
@cartermp, the rfc from the main issue gives a 404, and could this be linked to the PR too, for future reference?

Wasn't this still in preview, or has it been released already?

**Comment by xperiandri** [comment]
@baronfel @abelbraaksma 
https://github.com/fsharp/fslang-design/blob/master/preview/FS-1003-nameof-operator.md

**Comment by cartermp** [comment]
Completed for F# 5.
