### ISSUE TITLE
Allow "params" dictionaries as method arguments

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#260]
**Submitted by Tomas Petricek on 5/27/2014 12:00:00 AM**  
**30 votes on UserVoice prior to migration**  

When interoperating with languages that are more dynamic than F# (like Python, Matlab or R), we can often get the list of available methods/functions, but we cannot always get the names and types of parameters. For example, in R provider, you sometimes have to write:

``` fsharp
namedParams [ ("xval", days), ("yval", prices), ("another", box 1) ]
|> R.plot
```

It would be nice if I could put the "Params" attribute on a "IDictionary<string, 'T>" and let the compiler provide all additional named parameters as a dictionary:

``` fsharp
R.plot(xval=days, yval=prices, another=1)
```

This would have other uses - for example, when creating a Deedle data frame, you need to specify names of columns. We have a custom operator and function for that:

``` fsharp
frame [ "prices" => prices; "days" => days ]
```

But with the new feature, we could let you write, for example:

```
Frame.ofColumns(prices = [...], days, = [...])
```

This could really be done just by adding [Params] attribute to an IDictionary parameter. To support the R provider case, this needs to work in type providers too.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5975840)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5975840-allow-params-dictionaries-as-method-arguments.md#comments)

**Comment by dsyme** [comment]
## Response ##
** by fslang-admin on 8/3/2015 12:00:00 AM **

Updating to planned to indicate this is approved in general terms. An RFC is needed

Don Syme, F# Language and Core Library Evolution

**Comment by kurtschelfthout** [comment]
[RFC was added.](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1026-allow-params-dictionaries-as-method-arguments.md)

**Comment by dsyme** [comment]
@kurtschelfthout I'm wondering if we should retract the "approved in principle".  We've had very little call for this.  What do you think?

**Comment by kurtschelfthout** [comment]
I think this potentially helps making a dataframe API significantly more natural, but perhaps the added complexity vs the approach with operators `key => "val"` is not really worth it. 

While writing the RFC my impression was that before we add any more functionality to this part of the compiler we should probably clean up the existing overload resolution and parameter handling, esp. compiler errors. Lots of cases seems to be allowed but silently ignored.

On the other hand - is it in the way?

**Comment by dsyme** [comment]
> I think this potentially helps making a dataframe API significantly more natural, but perhaps the added complexity vs the approach with operators key => "val" is not really worth it.

Yes, I think that's the tradeoff

> On the other hand - is it in the way?

No, not in the way, was just spring-cleaning (ok, it's autumn)

**Comment by dsyme** [comment]
Labelling this as probably not, it hasn't been requested consistently.
