### ISSUE TITLE
Add string interpolation [ RFC FS-1001 ]

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#262]
**Submitted by Robert Jeppesen on 6/2/2014 12:00:00 AM**  
**179 votes on UserVoice prior to migration**  

The new language from Apple, Swift has a really nice syntax for println:
http://en.wikipedia.org/wiki/Swift_(programming_language)

```
let people = ["Anna": 67, "Beto": 8, "Jack": 33, "Sam": 25]
for (name, age) in people {
    println("\(name) is \(age) years old.")
}
```

We could steal the idea but use % instead of \ for a better fit. It would also be compatible, and combinable (is that a word?) with existing printfn syntax:

```
let name = "Robert"
printfn "Hi %(name), your age is %d"
printfn : int -> string
```

Naturally there would be compiler errors if name does not exist.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6002107)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6002107-add-string-interpolation-to-println-syntax-from.md#comments)

**Comment by dsyme** [comment]
Approved in principle (and has been for a while), please see RFC FS-1001 https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1001-StringInterpolation.md
Don Syme, F# Language Evolution

**Comment by cartermp** [comment]
Closing out as completed for F# 5.
