### ISSUE TITLE
Internationalized printf formatting of numbers

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#271]
**Submitted by Goswin on 6/17/2014 12:00:00 AM**  
**8 votes on UserVoice prior to migration**  

Most non-english speaking countries use "," as decimal separator. For example it would be nice if I could write `sprintf "%,1f" 2.222` instead of `sprintf "%.1f" 2.222` to get a comma as a decimal separator.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6063696)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6063696-internationalized-printf-formatting-of-numbers.md#comments)

**Comment by dsyme** [comment]
From the point of view of the F# language design, I would be happy to see a well-considered set of extensions to printf added to F# 4.x or later versions. An implementation and testing would need to be provided by someone in the F# community (possibly including Microsoft or Microsoft Research, though not limited to them). We would strongly welcome an implementation proposal and initial testing for this. Implementations of approved language design can now be submitted as pull requests to the appropriate branch of http://github.com/Microsoft/visualfsharp. See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for information on contributing to the F# language and core library..

Thanks
Don Syme, F# Language and Core Library Evolution

**Comment by dsyme** [comment]
Given that we now have #216 we won't do this as a printf extension - various internationalization formats are now available in numeric formatting.
