### ISSUE TITLE
Allow Object expressions to have attributes 

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#289]
**Submitted by Dave Thomas on 6/27/2014 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

In the simplest case something like this would be possible:

``` fsharp
[<MyAttribute>]
let makeResource name =
    { new System.IDisposable with 
        member this.Dispose() = printfn "%s disposed" name }
```

And then when the code is compiled the expression thats generated would also have the attribute applied to it. This would interoperability with frameworks that use declarative attributes which would otherwise require adding a full type

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6108807)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6108807-allow-object-expressions-to-have-attributes-appli.md#comments)

**Comment by dsyme** [comment]
Closing as there is a simple workaround - define a class
