### ISSUE TITLE
Allow Type Extensions and Extension Methods to Satisfy Constraints

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#29]
**Submitted by Jared Hester on 1/22/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  
## Response

*\* by fslang-admin on 1/23/2016 12:00:00 AM **

Duplicate of /archive/suggestion-5695277-allow-the-addition-of-operators-in-type-extensions

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/11543295)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-11543295-allow-type-extensions-and-extension-methods-to-sa.md#comments)

**Comment by dsyme** [comment]
Closing as sufficiently covered by https://github.com/fsharp/fslang-suggestions/issues/230 and the RFC
