### ISSUE TITLE
Add StructOption<T>

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#300]
# Add StructOption<T> [6193110]

**Submitted by Demetrios Obenour on 7/19/2014 12:00:00 AM**  
**59 votes on UserVoice prior to migration**  

Currently, whenever a new Option is created, a heap allocation is required. This comes at a performance penalty.
I suggest that a new type StructOption<T> be made available for performance.
## Response

*\* by fslang-admin on 2/4/2016 12:00:00 AM **

Approved in principle, per my comment below.
Link to RFC to follow
Don Syme, F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6193110)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6193110-add-structoption-t.md#comments)

**Comment by gsomix** [comment]
`StructOption` is also needed for fsharp/fslang-suggestions#612

**Comment by dsyme** [comment]
RFC is first part of https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1039-struct-representation-for-active-patterns.md

Implementation has been submitted
