### ISSUE TITLE
Allow "inline" keyword in the case "let f = fun a -> ..."

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#305]
# Allow "inline" keyword in the case "let f = fun a -> ..." [6237585]

**Submitted by Yusuf Motara on 7/31/2014 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

Currently, the code "let inline f = fun a -> ..." does not compile, but the code "let inline f a = ..." does compile. Since the two mean the same thing, "inline" should be allowed on both.
## Response

*\* by fslang-admin on 7/11/2016 12:00:00 AM **

This is approved for inclusion in a future release of F# subject to completion of an RFC and implementation.
An RFC can be submitted to https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs
A pull request to implement this feature will be necessary and we encourage contributors to submit one with adequate design detail and testing to http://github.com/Microsoft/visualfsharp.
Discussion of the particular version for this to be included in can be made once an implementation is available.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6237585)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6237585-allow-inline-keyword-in-the-case-let-f-=-fun-a.md#comments)

**Comment by jwosty** [comment]
I think this should also cover cases where there isn't an explicit lambda:

```
let inline f = List.map (fun x -> x + 1)
```
``

**Comment by gusty** [comment]
Maybe we can extend this suggestions to `rec` function which can't be `inline`, I always end up duplicating the function innerly being the outer function the inline and the inner the rec, it's just mechanical, but it would be nice if the compiler can save us from doing that.

**Comment by gusty** [comment]
Sure, here's an easy one, the greatest common divisor function:

```
let rec gcd a = function
    | b when b = LanguagePrimitives.GenericZero -> a
    | b -> gcd b (a % b)
```

This works for integer, but if we try to make it inline it won't compile due to the above mentioned limitation.

The solution is mechanic, wrap this function in an inline function:
```
let inline gcd x y =    
    let rec gcd a = function
        | b when b = LanguagePrimitives.GenericZero -> a
        | b -> gcd b (a % b)
    gcd x y
```

**Comment by dsyme** [comment]
I'll close this as it's easy enough (and better for some reasons) to define the inline function using normal function definition syntax
