### ISSUE TITLE
Add 'serializable' and 'blittable' constraints for types

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#317]
# Add 'serializable' and 'blittable' constraints for types [6359526]

**Submitted by Eirik George Tsarpalis on 8/28/2014 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

I think it would be a good idea to let the F# compiler reason about serializable types. This could be implemented along the lines of the 'comparison' constraint, i.e. based upon an assortment of criteria for deciding when it is satisfied.
For instance, a type could be statically deemed serializable iff
- it is primitive, string, byte array, etc.
- It is a subtype of System.Exception
- it is a managed class or struct that carries the Serializable attribute.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6359526)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6359526-add-serializable-and-blittable-constraints-fo.md#comments)

**Comment by Rickasaurus** [comment]
This seems to me like it would have to be hidden compiler magic. I'd rather some general purpose mechanism that would allow you to make/name your own new sets of composite constraints.

**Comment by teo-tsirpanis** [comment]
With [`BinaryFormatter`'s security risks and impending obsoletion](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), the `serializable` constraint is of little value. Those that need it could use `typeof<'T>.IsSerializable`.

And the proposed `blittable` constraint already exists in the form of `unmanaged`.

**Comment by dsyme** [comment]
I'm closing out these suggestions to add new minor constraints.
