### ISSUE TITLE
An CLIVirtual attribute

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#360]
**Submitted by Remko Boschker on 11/6/2014 12:00:00 AM**  
**22 votes on UserVoice prior to migration**  

Just as you can use ``CLIMutable`` to store records using Entity Framework wouldn't is be nice to be able to set an ``CLIVirtual`` attribute on a record field of an ``ICollection`` type so that Entity Framework can do lazy loading. See also http://stackoverflow.com/questions/26775760/how-to-create-a-virtual-record-field-for-entity-framework-lazy-loading

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672675)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6672675-an-clivirtual-attribute.md#comments)

**Comment by dsyme** [comment]
Is there no other way to achieve this except through a new attribute? It seems too corner case

If there really is no workaround at all please add comments to that effect and reopen

**Comment by dsyme** [comment]
Note the SO question gives a possible workaround in the answer http://stackoverflow.com/questions/26775760/how-to-create-a-virtual-record-field-for-entity-framework-lazy-loading
