### ISSUE TITLE
Add a Option.getOrDefault and other new functions to the Option module

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#361]
**Submitted by Gustavo Guerra on 11/6/2014 12:00:00 AM**  
**15 votes on UserVoice prior to migration**  

Like `List.nth`, `defaultArg` has the parameters in the "wrong order" to be able to be used in partial application. List.item is solving that problem, we should also do the same for `defaultArg`

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672880)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6672880-add-a-option-getordefault-and-other-new-functions.md#comments)

**Comment by dsyme** [comment]
Approved-in-principle to make some sensible additions to the Option module
Details about naming and exact additions will need to be finalized.
We will create an RFC for this at https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs

Don Syme, F# Language Evolution

**Comment by neoeinstein** [comment]
This has been started as [RFC FS-1007](https://github.com/fsharp/fslang-design/issues/60).

**Comment by dsyme** [comment]
Closing as covered by the RFC
