### ISSUE TITLE
Display current parameter type in tooltip for generic function

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#370]
**Submitted by TeaDrivenDev _ on 11/15/2014 12:00:00 AM**  
**11 votes on UserVoice prior to migration**  

I posted this on CodePlex (https://visualfsharp.codeplex.com/workitem/172), and Don Syme asked me to put it here as well.
The C# editor in Visual Studio displays the actual parameter types involved in the tooltips for generic class instances and method invocations. The F# editor only does that for objects and methods, but oddly not for F# types/functions; shouldn't this information be quite readily available?
Having this kind of information at hand would especially make it quite a bit easier to follow the transformation of data through pipe chains, even more so as this type of display is also completely absent for lambdas at this time.

## Response ##
** by fslang-admin on 2/4/2016 12:00:00 AM **

Not really a language item, but this should be implemented in the Visual F# Tools and the F# COmpiler Service

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6723648)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6723648-display-current-parameter-type-in-tooltip-for-gen.md#comments)

**Comment by dsyme** [comment]
Closing as this is a tooling question (really FSharp.Compiler.Service and/or Visual Studio)
