### ISSUE TITLE
Support bind (e.g. "await") in the middle of expressions, possibly using !! operator

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#374]
**Submitted by Arash Sahebolamri on 11/21/2014 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

that does the binding implicitly; so that it wouldn't be necessary to bind every monadic expression to a name. In the case of async workflows, it would behave like the C# await keyword.
With this operator, instead of this:

```fsharp
let task= tasync{
    let! response = http.GetAsync(uri)
    let! string = response.Content.ReadAsStringAsync()
    let! res = processAsync(string)
    return res
    }
```

it would be possible to write code like this:

``` fsharp
let task= tasync{ return !! processAsync(!!(!!http.GetAsync(uri)).Content.ReadAsStringAsync()) }
```

Or write this:

``` fsharp
let t= opt{ return ((!!x) + !!y) / !!z}
```

instead of this:

``` fsharp
let t= opt{
let! xx = x
let! yy = y
let! zz = z
return (xx + yy) / zz
}
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6752948)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6752948-support-bind-e-g-await-in-the-middle-of-expr.md#comments)

**Comment by Rickasaurus** [comment]
Idris has something like this and it's great, really kills a lot of the extra variable binding noise.

**Comment by michaelsg** [comment]
I've always wanted a `match!` to eliminate:
```fsharp
let! a = someAsync
match a with
...
```
but maybe better would be general purpose awaiting.
```fsharp
match !! a with
...
```

**Comment by dsyme** [comment]
I'm closing this issue for now, I don't think it's something we're going to do in F#, though I know the use cases for it.

Part of the simplicity and accuracy of F# computation expressions comes from the way that make binds sufficiently explicit to aid code readability, but in a sufficiently lightweight way.  While this does have a few pain points, there are a lot of advantages to it too.
