### ISSUE TITLE
Support .NET Core and CoreCLR

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#376]
**Submitted by Ryan Riley on 12/4/2014 12:00:00 AM**  
**377 votes on UserVoice prior to migration**  

.NET Core is the new cloud runtime model for the CLR and used in ASP.NET vNext.

## Response ##
** by fslang-admin on 8/3/2015 12:00:00 AM **

Strictly speaking this issue is not meant for https://fslang.uservoice.com, since it is about targeting a particular platform with the tooling, rather than the F# language or core library design itself.
However, I’m leaving it open for now since it’s getting so many votes. We may close it sometime soon to release the votes.

In any case, this work is planned by the Microsoft visualfsharp team and other contributors. Please contribute to the work at the http://github.com/Microsoft/visualfsharp repository and follow that repository for more details and updates.

Relevant issues: https://github.com/Microsoft/visualfsharp/issues/387 and https://github.com/Microsoft/visualfsharp/pull/499

Don Syme, F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6803533)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6803533-support-net-core-and-coreclr.md#comments)

**Comment by dsyme** [comment]
Closing as this work is underway and multi-faceted, no longer with tracking as a language suggestion
