### ISSUE TITLE
Make F# union types like "list" that have no subtypes 'sealed'

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#397]
**Submitted by Don Syme on 1/27/2015 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

The compiled form of the "list" type in F# uses a single class. This is also the case for some other F# union types, e.g. ones which are enumerations where no case carries any data. For these types, the compiled representation of the union type should be marked "sealed" in F# metadata
This is a breaking change w.r.t. hypothetical clients in other .NET languages that take advantage of this, though we know of no such instance in practice.
## Response

*\* by fslang-admin on 8/3/2015 12:00:00 AM **

Considering this approved for F# 4.x or the first possible update after this. Discussion still very welcome. Implementations of approved language design items can now be submitted as pull requests to the appropriate branch of http://github.com/Microsoft/visualfsharp. See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for information on contributing to the F# language and core library.

Don Syme, F# Language/Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7017131)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-7017131-make-f-union-types-like-list-that-have-no-subt.md#comments)

**Comment by 7sharp9** [comment]
@baronfel Whats the advantage of doing this compared to the effort?

**Comment by baronfel** [comment]
@dsyme can you clarify here? I just ported this one over and don't have the context for the suggestion.

**Comment by dsyme** [comment]
We assume that .NET Core optimizations such as devirtualization may show a perf improvement here.  But it should be verified.

**Comment by kerams** [comment]
`List`, DUs in general, records and closures are already sealed. Is there anything actionable here?

**Comment by baronfel** [comment]
Good eye @kerams - thanks for the reminder.
