### ISSUE TITLE
Add polymorphic variants (ad-hoc Discriminated Unions)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#40]
**Submitted by Jared Hester on 2/21/2016 12:00:00 AM**  
**36 votes on UserVoice prior to migration**  

Creating strongly typed data constructs with some level of heterogeneity is often accomplished with DUs so lets take the trivial case of wanting to have lists of floats & ints, ints & strings, and ints & floats & strings. We'd need the types -

``` fsharp
type IntString =
    | Int of int
    | String' of string
type FloatInt =
    | Float of int
    | Int of int

type IntFloatString =
    | Float of int
    | Int of int
    | String' of string
```

But in practice using these would require qualified access to make sure you're getting the right case from the right type and as types you want to group grow in number there's a combinatory explosion of boilerplate and verbose code necessary to put it to work. Polymorphic variants cut down the noise and increase the flexibility and expressiveness of your code.

The declaration of a polymorphic variant in OCaml is not unlike that of the single case DUs that are already commonly found in F# code Instead of -

``` fsharp
type Int = Int of int;;
> type Int = | Int of int
Int 3;;
> val it : Int = Int 3
```

OCaml and uses a preceding backtick convention for a simplified syntax-

``` fsharp
let three = `Int 3;;
> val three : [> `Int of int ] = `Int 3
let four = `Float 4.;;
> val four : [> `Float of float ] = `Float 4.
```

The `>` at the beginning of the variant types above marks the types as being open to combination with other variant types. Which means a list could be declared as such -

``` fsharp
let ls = [three; four]
> val ls : [> `Int of int | `Float of float]
```

and the type would be an ad-hoc Discriminated Union where its cases match the polymorphic variants used, this also applies to function declarations

``` fsharp
let is_positive = function
| `Int x -> x > 0
| `Float x -> x > 0.
;;
> val is_positive : [< `Float of float | `Int of int ] -> bool = <fun>
```

The `<` is there because is_positive has no way of dealing with values that have tags other than `Float of float or`Int of int.
The `<` and `>` markers are indicators of the upper and lower bounds on the tags involved.
If the same set of tags are both an upper and a lower bound, we end up with an exact polymorphic variant type, which has neither marker

``` fsharp
let exact = List.filter is_positive [three;four];;
> val exact : [ `Float of float | `Int of int ] list = [`Int 3; `Float 4.]
```

summarizing the part of [Real World Ocaml on Polymorphic Variants](https://realworldocaml.org/v1/en/html/variants.html). [Further reference](http://caml.inria.fr/pub/docs/manual-ocaml-400/manual006.html#toc36)

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12425811)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12425811-add-polymorphic-variants-ad-hoc-discriminated-un.md#comments)

**Comment by dsyme** [comment]
See also #606 and #538

**Comment by JaggerJo** [comment]
Really think F# would benefit from anonymous DUs. 

A 'pattern' I've fallen into when storing json is to map it to an anonymous record that is then stored/serialised. This drastically simplifies versioning, we can just keep the old anonymous types for deserialising old versions and map to the current type from there (It also prevents accidentally breaking thinks to a certain point).

This approach works fine until the original model contains a DU we want to represent anonymously. Personally closed DUs are more than enough for me.

```fsharp

type CarKind = 
  | `Combustion
  | `Electric

type Car =
  {| Brand: string 
      Model: string
      Kind: CarKind |}

let range (car: Car) : 'Fuel of int | `Charge of int =
  match car.Kind with
  | `Combustion -> `Fuel 60
  | `Electric -> `Charge 120  

let estimate (range: 'Fuel of int | `Charge of int) : int =
  match range with
  | `Fuel n -> 0
  | `Charge n -> 100

```

(example is bad)

**Comment by dsyme** [comment]
If we do anything in this space it would be along the lines of #538 

Closing this because of that.

**Comment by Lanayx** [comment]
A good reference https://keleshev.com/composable-error-handling-in-ocaml . This exact problem exists in F# and since there are no polymorphic variants in language - it doesn't have a good solution. I faced it when trying to implement Result monad in real-life application at work.
