### ISSUE TITLE
Please make a correct ‘modulus’ for F#

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#417]
**Submitted by Alexei Odeychuk on 3/1/2015 12:00:00 AM**  
**13 votes on UserVoice prior to migration**  

Please fix a bug in the F# compiler. Everybody needs correct values for negative numbers. The algorithm calculating a modulo should respect the existing math rules. For example, `11 % 5 = 1` (correct), but `-11 % 5` is -1 (bug), should be 4 (correct value).

For instance, `m mod n: for integers m and n, m mod n is the integer for which 0 <= r < n and m-r is a multiple of n`. For example, `11 mod 5 = 1`, and `-11 mod 5 = 4`.

Details of discussion and suggested corrections to the algorithm of the % operator are here:

1.  [http://gettingsharper.de/2012/02/28/how-to-implement-a-mathematically-correct-modulus-operator-in-f/](http://gettingsharper.de/2012/02/28/how-to-implement-a-mathematically-correct-modulus-operator-in-f/)
2. Distinctions between rem and mod: [http://mathcentral.uregina.ca/QQ/database/QQ.09.12/h/eric1.html](http://mathcentral.uregina.ca/QQ/database/QQ.09.12/h/eric1.html)

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7156040)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-7156040-please-make-a-correct-‘modulus’-for-f.md#comments)

**Comment by dsyme** [comment]
Thanks for the suggestion

While I appreciate the problem, we decided in F# 1.x to follow C# and .NET here.  According to policy, we don't revisit design decisions unless there has been a significant change of circumstance

**Comment by charlesroddie** [comment]
While the old `mod` may need to stay the same and be consistent with .Net, this definition was a mistake in .Net, and results in unanticipatable bugs unless users are aware of the problem.

There should be a `trueMod` or `fixedMod` or `absMod` and the xml doc on 'mod' should include the text `a mod b is negative when a is negative; use fixedMod for non-negative output.`.

If we don't add a new function and leave it to users to fix `mod` themselves, we should still include the "warning".

**Comment by gusty** [comment]
In F#+ there is another family of div/rem functions, ending with `E`(which stands for Euclidean) which follows that standard.

See https://github.com/fsprojects/FSharpPlus/blob/5bf7137e07febd4937ecc346c07c6caae8534470/src/FSharpPlus/Operators.fs#L817-L838

If people feel confortable with that, we can add it to F# core.
