### ISSUE TITLE
Cartesian product function for collections

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#419]
**Submitted by luketopia on 3/8/2015 12:00:00 AM**  
**7 votes on UserVoice prior to migration**  

It's often useful to compute the Cartesian product (cross join) of two collections. I always end up writing something like this:
```fsharp
let cross xs ys =
  seq {
    for x in xs do
      for y in ys ->
        x, y }
```
I think it would be useful to have this in the standard collection modules.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7184398)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-7184398-cartesian-product-function-for-collections.md#comments)

**Comment by dsyme** [comment]
I’m marking this approved-in-principle, see RFC FS-1002 https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1002-cartesian-product-for-collections.md

The function would need to be added to List, Array and Seq. I would prefer a different name – I suggest “allPairs”

**Comment by dsyme** [comment]
Completed
