### ISSUE TITLE
Override `ToString` for discriminated unions and records

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#429]
**Submitted by Vasily Kirichenko on 4/15/2015 12:00:00 AM**  
**181 votes on UserVoice prior to migration**  

It's a pain and dirty to add `override x.ToString() = sprintf "%A" x` to every type in order to make `String.Format()` happy:

```fsharp
type T1 =
  { Id: int
    Version: string }
override x.ToString() = sprintf "%A" x

type DU =
| C1 of int
| C2
override x.ToString() = sprintf "%A" x
```

I think it's very easy to teach the compiler generate this override automatically for all user types.
## Response

*\* by fslang-admin on 6/23/2016 12:00:00 AM **

Marking as planned, though we need to work out the details
Don Syme
F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7574961)**

**Comment by kurtschelfthout** [comment]
[RFC was added.](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1022-override-ToString-for-discriminated-unions-and-records.md)

**Comment by dsyme** [comment]
@kurtschelfthout I've added you as write-admin in this repo if you want to edit issue descriptions directly, thanks

**Comment by kurtschelfthout** [comment]
@dsyme, will do. Thanks!

**Comment by dsyme** [comment]
This is now covered by the RFC and has already been implemented. Thanks all!

**Comment by Porges** [comment]
Question from the sky: Is this implemented in such away that it avoids the performance penalties of `sprintf "%A"`?

**Comment by abelbraaksma** [comment]
New location of RFC: https://github.com/fsharp/fslang-design/blob/main/FSharp-4.1b/FS-1022-override-ToString-for-discriminated-unions-and-records.md.

**Comment by abelbraaksma** [comment]
@Porges see here for more info: https://github.com/fsharp/fslang-suggestions/issues/919
