### ISSUE TITLE
Make the result of the dict function implement IDictionary

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#435]
**Submitted by Richard Minerich on 5/6/2015 12:00:00 AM**  
**21 votes on UserVoice prior to migration**  

The fact that the type returned by dict doesn't implement IDictionary makes reflection difficult and inefficient, it also make this type different than all other .NET Core Dictionary implementations

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7845018)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-7845018-make-the-result-of-the-dict-function-implement-id.md#comments)

**Comment by dsyme** [comment]
This is approved for inclusion in a future release of the F# core library subject to an implementation and detailed design. Completion of the pull request to implement this feature will be necessary, see the link above.

Don Syme, F# Language and Core Library Evolution.

**Comment by dsyme** [comment]
This got done ages ago
