### ISSUE TITLE
#r #load via fsi method

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#44]
# #r #load via fsi method [12510276] #

**Submitted by Steven Taylor on 2/28/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

fsi.Load("script.fsx")
fsi.Reference("bin/debug/someDllReference.dll")
It would be very useful to be able to fsi.Load / fsi.Reference through type providers, for use by those who are designing them.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12510276)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12510276--r-load-via-fsi-method.md#comments)

**Comment by dsyme** [comment]
Programmatic loading can be done through Fsharp.Compiler.Service.
