### ISSUE TITLE
Make call syntax simpler for statically resolved member constraints [ RFC FS-1024 ]

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#440]
The idea is basically explained by the following code:

``` fsharp
// this works as expected
type Example() =
    member __.F(i) = printfn "%d" i

let inline f (x : ^a) =
    (^a : (member F : int -> unit) (x, 1))
    (^a : (member F : int -> unit) (x, 2))

f (Example())
```

The proposal is this:

``` fsharp
// this doesn't work
let inline f (x : ^a when ^a : (member F : int -> unit)) =
    // the compiler knows that there must be member F and its signature
    // so the following should be possible
    x.F(1)
    x.F(2)
```

You can also view this code highlighted at http://pastebin.com/CHMj7xQG

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/8014059)**

**Comment by dsyme** [comment]
Approved in principle. Thanks for the suggestion. We will add an RFC for this in due course, or anyone else can submit one if we don't get to it first. See https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs We will need to consider whether to simplify calls for static members as well.

**Comment by kurtschelfthout** [comment]
[RFC was added.](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1024-simplify-call-syntax-for-statically-resolved-member-constraints.md)

**Comment by Richiban** [comment]
I just wanted to check whether or not this proposal includes static member constraints too? For example:



```diff
let inline tryParse< ^a when ^a : (static member TryParse : string * ^a byref -> bool) > s =
    let r = ref Unchecked.defaultof< ^a >

---if (^a : (static member TryParse: string * ^a byref -> bool) (s, &r.contents)) 
+++if ^a.TryParse (s, &r.contents)
    then Some !r
    else None
```

**Comment by jwosty** [comment]
@Richiban post that in the RFC discussion: https://github.com/fsharp/fslang-design/issues/162

But yeah, this doesn't seem to be addressed by the RFC but I'd like to see that too.

**Comment by 7sharp9** [comment]
Haxe has a nice system for extensions in this manner:
```haxe

typedef Measurable = {
  public var length(default, null):Int;
}

static function test<T:Iterable<String> & Measurable>(a:T) { ... }

```

The constraints say that a type is compatible if

it is compatible with Iterable<String> and has a length-property of type Int.

It also allows inline definitions:

```haxe
static inline function length<T: {var length(default, null):Int }>(o:T) { ... }
```
In the above example `(default,null)` are property access modifiers which could be changed to be inline with normal F# access modifiers.  Here they have the meaning:
default: allows normal field access if the field has public visibility
null: allows access only from within the defining class.

**Comment by TheJayMann** [comment]
@7sharp9 
That suggestion in concept isn't too different from my suggestion of inline interfaces #641.  I don't want to necessarily promote one syntax over the other; rather, I wish to promote the concept in general.

**Comment by 7sharp9** [comment]
Big difference is this is approved in principle but #641 is not yet.   SRTP stuff is sufficiently popular that having a sane syntax is a must really, I have to look it up every time!

**Comment by TheJayMann** [comment]
@7sharp9 
I was referring to the Haxe syntax you were providing, not this feature in general.  Unless you are suggesting that the Haxe syntax has been approved in principle.

**Comment by 7sharp9** [comment]
@TheJayMann I just wanted discussion to occur around the simplification.  This one has been dormant for some time.

**Comment by dsyme** [comment]
Closed as completed https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1024-simplify-constrained-call-syntax.md
