### ISSUE TITLE
Add atom syntax

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#457]
**Submitted by mikero on 6/26/2015 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

Add a syntax for atoms a.k.a. keywords a.k.a. self-evaluating symbols.

```
    :foo 
    'foo or 
    #foo
```

whichever causes the least problems. Where `foo` otherwise follows the rules for an identifier, is simply turned into "foo" at compile time. (It would also be nice of '-' were also added to the list of allowable characters for the atom.)
E.g.:

```
("fido", :is-a, :pet) 
```

is of type `string*string*string`

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/8556646)**

**Comment by dsyme** [comment]
Strangely atoms like this never seem to make it into ML-family languages.  I'd appreciate people's opinions on this

**Comment by robkuz** [comment]
Maybe instead of just converting it to a string we could convert the above to a single case DU

    ("fido", :is-a, :pet)
    > it: (string, Symbol, Symbol)

and `Symbol`being

    type Symbol = Symbol of string

**Comment by robkuz** [comment]
And while we're at it what about making it even more powerful like this

    type Symbol<'a> = Symbol of string * 'a

and then using it like this

    :my-pet "fido", :is-a Dog
    > it: (Symbol string string, Symbol string Animal)

This could make for some fine DSLs

**Comment by Alxandr** [comment]
True, but you suddenly loose the ability to do

```fsharp
Map.empty
|> Map.set :pet Dog
```

**Comment by robkuz** [comment]
you're right. in a way. thou this should work

     Map.empty
     |> Map.set (:pet()) Dog

not as nice anymore. Maybe on `:` precedence could be changed so that this works

     |> Map.set :pet() Dog

**Comment by Alxandr** [comment]
@robkuz so, I get `:pet()` as opposed to `"pet"`, at that point haven't we already removed most of the gain?

**Comment by robkuz** [comment]
so you get `:pet()` as opposed to `:pet`. I don't think this is so bad.

**Comment by kspeakman** [comment]
I would like this feature. The equivalent alternative is to pre-define constant strings and reuse them. So I have to stop what I'm doing and go find the constants file and add one, then go back to where I was. These are a bit redundant to define: `[<Literal>] let MyKey = "MyKey"`. And using them feels very similar to using global vars. e.g. `Const.MyKey`. This feels bad and is more verbose than `:myKey`. Keywords could alleviate those issues normally faced with using constant keys. I think for them to really be useful they would also need some tooling support. Namely auto-completion.

**Comment by dsyme** [comment]
I have decided that we will not do this in the forms mentioned above.  

Atoms in typed languages are an interesting thing, and my feeling from TypeScript and typed Python is that it's actually now more standard to go the other way around - give string literals a special role in the type system.  This seems a more natural direction for F# too, e.g. #1166
