### ISSUE TITLE
Disable or add a warning to mutable use bindings

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#464]
**Submitted by Eirik George Tsarpalis on 7/17/2015 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

See also https://github.com/Microsoft/visualfsharp/issues/535#issuecomment-122262582

## Response ##
** by fslang-admin on 6/22/2016 12:00:00 AM **

This is approved for inclusion in a future release of F#.
PR at https://github.com/Microsoft/visualfsharp/pull/1277
No RFC is needed for this feature.
Don Syme, F# Language and Core Library Evolution.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/8909788)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-8909788-disable-or-add-a-warning-to-mutable-use-bindings.md#comments)

**Comment by dsyme** [comment]
We ended up not adding this to F# because a ``use mutable e = collection.GetEnumerator()`` is necessary when an enumerator is a mutable struct
