### ISSUE TITLE
warnon:1182 seems like a good idea, why is it off by default ?

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#47]
**Submitted by Zhen on 3/1/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

*[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12529242)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12529242-warnon-1182-seems-like-a-good-idea,-why-is-it-off.md#comments)

**Comment by dsyme** [comment]
Closing as we won't turn this on by default.
