### ISSUE TITLE
Add System.Collections.ICollection implementations to F# list/set/map

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#473]
# Add System.Collections.ICollection implementations to F# list/set/map [9183845]

**Submitted by Eirik George Tsarpalis on 8/5/2015 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

ICollection is a useful interface that inherits IEnumerable. Inputs implementing ICollection are utilized by libraries such as LINQ, Nessos.Streams and MBrace in order to optimize partitioning of data. Curiously, none of the F# collections (list/set/map) implement ICollection (however the latter two do implement ICollection<T>, which is a different interface designed for mutable collections). It is currently impossible to extract the length/count of a boxed list/map without performing some sort of reflection, which is not always desirable.
I suggest that future versions of F# core implement this.
See also https://github.com/Microsoft/visualfsharp/issues/570#issuecomment-128000307
## Response

*\* by fslang-admin on 2/5/2016 12:00:00 AM **

Approved in principle, see my comment below
We will open an RFC for this in due course.
https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9183845)**

**Comment by jack-pappas** [comment]
@eiriktsarpalis I've implemented part of this and submitted a WIP PR to visualfsharp.

**Comment by Happypig375** [comment]
Is this completed?

**Comment by Tarmil** [comment]
Oh, I didn't know this was an approved proposal -- this issue has actually bitten me recently in Bolero. Blazor virtualized components take an ICollection as input, which means you can't pass an F# list directly; I had to write [a wrapper](https://github.com/fsbolero/Bolero/blob/486c8b18c12e31984bae26ef26378e36ca93c0ed/src/Bolero/Virtualize.fs#L28) as a workaround.

**Comment by dsyme** [comment]
The implementation of the non-generic ICollection never got integrated, see the last comment in https://github.com/dotnet/fsharp/pull/2085, we ended up preferring a PR that did generic `IReadOnlyCollection<'T>`

If ICollection is still being used by UI layers then maybe we should revist it this? The PR at https://github.com/dotnet/fsharp/pull/2085 should act as a guide

**Comment by Tarmil** [comment]
Actually I misread this, what was needed by Blazor was `System.Collections.Generic.ICollection<'T>`.

**Comment by dsyme** [comment]
Closing per comments above

**Comment by jkone27** [comment]
This might still be needed useful for C# interop? 

many C# libs take ICollection<T> as input and passing F# list to those is not very handy in some cases

**Comment by jkone27** [comment]
@vzarytovskii @baronfel wdyt about this one? still struggle with this in interop scenarios
