### ISSUE TITLE
Have String.ofChars in the standard library

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#475]
# Have String.ofChars in the standard library [9324276]

**Submitted by Bang Jun-young on 8/14/2015 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

Wouldn't it be convenient if String.ofChars function was part of the standard library? The implementation is quite straightforward:
module String =
let ofSeq (seq: char seq) =
seq |> (System.Text.StringBuilder() |> Seq.fold (fun sb c -> sb.Append(c))) |> string
Currently, we have to use an inefficient chaining to convert a seq of characters to a string:
['a'; 'b'; 'c'] |> Array.ofList<char> |> System.String
which can be simplified with String.ofChars:
['a'; 'b'; 'c'] |> String.ofChars
String.ofSeq also can be handy for profiles like PCL where the String type is not regarded as seq<char>.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9324276)**

**Comment by dsyme** [comment]
Cloding this issue as it hasn't been a common request, and didn't come up in the issues discussing more functions for the String library
