### ISSUE TITLE
Allow function names to end with a question mark.

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#48]
# Allow function names to end with a question mark. [12533019] #

**Submitted by Jeff Heon on 3/1/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

I find it really elegant in some language where predicate functions can end with a question mark.
Consider `odd? 5` vs `isOdd 5` or `areRelated a b` vs `related? a b`
There might be some reason why it's a terrible idea grammar-wise or something in F#. I'm still very much a newbie I'm afraid. I apologize if it's featured in a FAQ I missed or even here and I search badly.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12533019)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12533019-allow-function-names-to-end-with-a-question-mark.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 and we decided against it.  Closing per policy not to revisit issues already decided in previous design iterations
