### ISSUE TITLE
Support custom scheduler in Async

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#485]
# Support custom scheduler in Async [9688323]

**Submitted by Lev Gorodinski on 9/9/2015 12:00:00 AM**  
**15 votes on UserVoice prior to migration**  

Some discussion here: https://github.com/Microsoft/visualfsharp/issues/581

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9688323)**

**Comment by dsyme** [comment]
Given the addition of `task { ... }` to FSharp.Core we won't do this directly - async has its advantages cut we're not going to make it a full task runtime
