### ISSUE TITLE
Produce System.Linq.Expressions more efficiently

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#487]
**Submitted by Eugene Tolmachev on 9/17/2015 12:00:00 AM**  
**30 votes on UserVoice prior to migration**  

Most of .NET query providers are written in C# and use System.Linq.Expressions. While the conversion Expr->Expression is available it introduces significant penalty: http://stackoverflow.com/questions/32592811/why-is-f-expression-tree-generation-is-much-slower-than-c-can-it-be-made-fast

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9799014)**

**Comment by dsyme** [comment]
This issue hasn't seen any traction since 2016, nor even any further requests - closing
