### ISSUE TITLE
Add a shorthand/literal syntax for creating Maps

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#49]
# Add a shorthand/literal syntax for creating Maps [12536532]

**Submitted by Brad Collins on 3/1/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

A shorthand/literal syntax or computation expression for building Maps would be nice—something like the following:
let m = map ["a",97; "b",98; "c",99]
The shorthand for dictionaries ...
let d = dict ["a",97; "b",98; "c",99]
... is nice, but while Maps implement IDictionary, dictionaries do not play well with Map module functions. One must inevitably convert a dictionary to a Map or create a Map with Map.ofArray, .ofList, or .ofSeq.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12536532)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12536532-add-a-shorthand-literal-syntax-for-creating-maps.md#comments)

**Comment by xperiandri** [comment]
I think it must be type agnostic for any type supporting `KeyValuePair`
Something similar to C# like
``` F#
let map = [
    ["key1"] = "value1"
    ["key1"] = "value1"
]

let map : ImmutableDictionary<string, string> = [
    ["key1"] = "value1"
    ["key1"] = "value1"
]
```
So that if type supports constructor or [AddRange(KeyValuePair<'TKey,'TValue> seq)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2.addrange?view=net-5.0#System_Collections_Immutable_ImmutableDictionary_2_AddRange_System_Collections_Generic_IEnumerable_System_Collections_Generic_KeyValuePair__0__1___) it will work

**Comment by jwosty** [comment]
Wouldn't ``let map = Map.ofSeq`` work for the usage that OP provided?

@xperiandri Good idea -- if we're going to make this a language suggestion, it would need to be a meaningful extension to the language like you're suggesting. However, your proposed syntax would be ambiguous (could be a bool list). Perhaps something more like the following (though I don't like the usage of naked square brackets, as there's still some ambiguity there between the list syntax):

```fsharp
let map = [
    "key1" -> "value1"
    "key2" -> "value2"
]
```

Side note: you hack something together that syntactically gets you pretty close in today's F# (weird, but fun):

```fsharp
let map = Map.ofSeq
let (=>) key value = key, value // since you can't have a -> operator
let xs = map [
    "key1" => 42
    "key2" => 43
]
```

**Comment by xperiandri** [comment]
Then maybe
``` F#
let map = [
    ["key1"] <- "value1"
    ["key1"] <- "value1"
]
```
or 
``` F#
let map = [
    .["key1"] <- "value1"
    .["key1"] <- "value1"
]
```

**Comment by xperiandri** [comment]
> if we're going to make this a language suggestion

The is a similar discussion about collections
https://github.com/fsharp/fslang-suggestions/issues/619

I suppose these can be combined into a singles suggestion that will allow initializing collections and maps using `let collection : CollectionType = []` syntax

**Comment by dsyme** [comment]
As things stand, it creates the intermediate list

**Comment by Lanayx** [comment]
This issue might we relevant to type-directed collection initialization. I'd like to see the type-directed resolutions for Map, Dictionary, Sets, IDictionary and classes that inherit from Dictionary and IDictionary as well.

**Comment by abelbraaksma** [comment]
Change from `completed` -> `not planned`

**Comment by brianrourkeboll** [comment]
Just for reference, it is possible to make a `Map<_, _>` builder that works with no intermediate collections: https://github.com/brianrourkeboll/FSharp.Collections.Builders.

As to whether such a thing should be in the core library: that depends on whether type-direction for `[…]` were ever going to support maps or dictionaries as a target. C# does seem on track to add dictionary initializer syntax, for what it's worth.

**Comment by abelbraaksma** [comment]
Yes, good points. Perhaps we should create a separate issue to collect what we currently know about type-directed collection initializers. I believe there are some other issues lying around that aren't specific to Maps.
