### ISSUE TITLE
Types local to function scope

### ISSUE THREAD

**Issue by t3dodson** [fsharp/fslang-suggestions#496]
# Types local to function scope

See my stackoverflow post which is referring to this feature http://stackoverflow.com/questions/38448502/is-it-possible-to-have-local-types-in-f

I propose we add the ability to declare types which are local to the function they are defined in. They would only be possible when the type is not used outside the function scope

The existing way of approaching this problem in F# is using a wrapper module to contain the type and function.

## Pros and Cons 

The advantages of making this adjustment to F# are that you can further encapsulate ideas within a function

The disadvantages of making this adjustment to F# are you would have to refactor a type from an inner scope to an outter scope if you want to return that value.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): ??

Related suggestions: (put links to reated suggestions here)

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
This is a duplicate - https://github.com/fsharp/fslang-suggestions/issues/150.
