### ISSUE TITLE
Custom Query Operators Shouldn't Fail at Runtime

### ISSUE THREAD

**Issue by Thorium** [fsharp/fslang-suggestions#498]
# Custom Query Operators Shouldn't Fail at Runtime

I propose we let users to extend custom query-operations

The existing way of approaching this problem in F# is to throw runtime exception.

## Pros and Cons 

The advantages of making this adjustment to F# are that users could use their custom LINQ-keywords.

The disadvantages of making this adjustment to F# are unknown.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: https://github.com/fsharp/fslang-suggestions/issues/495

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design: I assume no-one has constructed their software to ensure that the exception is thrown.
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
Hi @Thorium 

Here is a related SO question:

* http://stackoverflow.com/questions/13828703/extending-query-expressions

It would be good if you could edit your proposal to be more specific in the light of the cases covered by the above (basically IEnumerable works, IQueryable doesn't).

> The disadvantages of making this adjustment to F# are unknown.

There are always disadvantages :) implementation cost, documentation cost, "less is more and more is less", the opportunity for bugs, churn etc.
