### ISSUE TITLE
make it possible for abstract member with overloads to define parameter names

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/fslang-suggestions#500]
# Allow parameter names for abstract member with overloads

Consider this sample C# code:

```csharp
public abstract class Foo {
  public abstract int Bar(int a, int b);
  public abstract int Bar(int a, int b, int c);
}
```

There is currently no way to define the same in F# without losing ability to name the parameters, which is a problem when defining overloads.

## Syntax proposals

that syntax is the most natural to those which are used to define of abstract members or employ .fsi files
```fsharp
type Foo =
  abstract member Bar: a: int -> b: int -> int
  abstract member Bar: a: int -> b: int -> c: int -> int
```

that syntax feels the most natural to those which are used to define (non-curried) methods

```fsharp
type Foo =
  abstract member Bar(a: int, b: int) : int
  abstract member Bar(a: int, b: int, c: int) : int
```

## Pros

* F# is advertised as multiparadigm including OO, detailed signatures is important especially in context of overloads.
* F# interop in .net context is a strong selling point, but it is not easy to vend OO APIs designed in F#

## Cons

More reasons to object F#

## Extra informtion

Estimated cost: M

## Affadavit

Please tick this by placing a cross in the box:
* [x] This is not a question and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
What's wrong with this (which works today)?

```fsharp
type Foo =
  abstract member Bar : a: int * b: int -> int
  abstract member Bar : a: int * b: int * c: int -> int
```

**Comment by smoothdeveloper** [comment]
@dsyme thanks! I guess what is wrong is the user.

**Comment by dsyme** [comment]
@smoothdeveloper OK, thanks :)
