### ISSUE TITLE
Whitespace Insignificance

### ISSUE THREAD

**Issue by alrz** [fsharp/fslang-suggestions#502]
# Whitespace Insignificance

It would be nice if we have a whitespace insignificant variation of the syntax similar to [Reason's](http://facebook.github.io/reason/mlCompared.html). Basically, it addressed pain points in OCaml's syntax which are now duplicated to F#.

There exist some other suggestions on this matter like #470 which proposes to relax intention rules but I don't believe it really address the problem, specially for those who come from C-family languages like C#. This is a blocker for me myself to actually use F# in production and personal projects.

## Pros and Cons 

The advantage of making this adjustment to F# is that the language will be familiar for those coming from C-family languages. But the drawback here is that then we would have three syntax variations (along with lightweight and verbose).

## Extra information

Estimated cost: L-XL

Related suggestions: #470 

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
> This is a blocker for me myself to actually use F# in production and personal projects.

Why is this a blocker?

**Comment by dsyme** [comment]
Thank you for the suggestion.  We considered this already in the F# 1.0 design and decided against it, beyond the OCaml-compat syntax.  It is the policy of this suggestions repo to close suggestions that have already been considered in previous iterations of the F# design process.
