### ISSUE TITLE
Add shuffle method for lists and arrays

### ISSUE THREAD

**Issue by Lanayx** [fsharp/fslang-suggestions#507]
# Add shuffle method for lists and arrays

Random shuffling of data arrays is very common operation in data science which F# was designed for. So it would be very convenient to have such an operation in the language. Currently we have to use one of [these snippets](http://www.fssnip.net/search/shuffle) which is obviously not ideal.

**Comment by dsyme** [comment]
@Lanayx Please resubmit using the suggestion template, thanks
