### ISSUE TITLE
Add shuffle, sample etc. methods for lists, arrays etc

### ISSUE THREAD

**Issue by Lanayx** [fsharp/fslang-suggestions#508]
Random shuffling of data arrays is very common operation in data science which F# was designed for. So it would be very convenient to have such an operation in the language.

The existing way of approaching this problem in F# is to use one of [these snippets](http://www.fssnip.net/search/shuffle) which is obviously not ideal.

## Pros and Cons 

The advantage of making this adjustment to F# is making F# more appealing as a tool for data science development

I don't see any disadvantages of making this adjustment to F#.

## Extra information

Estimated cost (S): 

Related suggestions: http://www.fssnip.net/search/shuffle

## Affidavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
There is the general issue of the random number generator used and the predictability of its seed. At the moment nothing in FSharp.Core.dll does random number generation.

**Comment by cloudRoutine** [comment]
This seems like a better fit for a library of utility functions and extension methods entirely oriented toward data science.

**Comment by Lanayx** [comment]
The seed can be passed as a parameter and .NET Random class can be used internally still allowing developers to use shuffling in any part of the program without copying over the snippets.

**Comment by dsyme** [comment]
@Lanayx Right, though some people say System.Random's not good enough...

@cloudRoutine @Lanayx It does feel like this should be part of the set of libraries referenced by http://fslab.org.  There are an awful lot of functions and types that come under the "good for data science programming" umbrella.  We long ago decided that FSharp.Core couldn't contain all of these, which is one reason http://fslab.org came into being.  @Lanayx perhaps you would consider become a maintainer on http://fslab.org to help in this?

**Comment by Lanayx** [comment]
@dsyme For me shuffling is almost like sorting, which can be useful not only in data science. Think of playlist, puzzle, favorites shuffling. I'll add this suggestion to fslab if there is a special repository for suggestions there. For now I'm not enough experienced to be the maintainer.

**Comment by kspeakman** [comment]
A while back I put [this](https://github.com/XeSoft/Utilities/blob/master/XeSoft.Utilities/Seq.fs) on GitHub, which implements the Durstenfeld (aka Knuth, Fisher-Yates) unbiased shuffle algorithm. For RNG you can use System.Random (seeded), RNGCryptoServiceProvider, or provide your own RNG function.

I use it for shuffling questions and answers to generate an exam and key for computer-based training.

The original algorithm is imperative with (RNG) side effects, so that is reflected in the code, although the input sequence is not modified. It uses some supporting functions (and 1 class for RNGCrypto to buffer random bytes) which are also included in the repo.

Feel free to use or not. MIT license.

**Comment by Lanayx** [comment]
@kspeakman, your algorithm is basically the same as the most popular among the snippets I mentioned in the first post

**Comment by kspeakman** [comment]
@Lanayx Yeah, the first one looks ok algorithmically (I'm not an expert there) and is succinct. However, [System.Random is pretty poor randomization](https://blog.frogslayer.com/random-headaches-from-system-random/). Also, it mutates the input array, but that is fixable with Array.copy. In any case, none of them (mine included) are ideal because they internally use side effects. When you use them your code becomes non-deterministic and harder to test. And from what I've seen in F# collection functions, side effects are generally avoided (thank goodness). Probably the only kind you could get away with in the core library is a seeded shuffle since that is deterministic. (You could still call it with a random seed.)

A functionally pure version with the possibility for stronger randomization would look a bit different. It would require the result of randomization to be generated outside the shuffle function and then passed in. E.g. an array of random floats between 0 and 1. Each float can be scaled to the size of the remaining items to be shuffled. Floats have limited precision though, and are subject to slight biases according to the wikipedia article. But any numeric type (or just bytes) could be used really.

Anyway, I think the point is that it's not as simple a thing as it seems.

**Comment by Lanayx** [comment]
@kspeakman I think that the algorithm _must_ be non-pure, otherwise it will be slow. But with the details put inside the core library we won't care about it and we'll continue writing pure code as f# programmers, that's the point.

**Comment by kspeakman** [comment]
Not sure why it would have to be non-pure to perform well. You mean array mutation? As long as it doesn't modify the input collection and the results are deterministic, that's close enough to a pure function. A lot of List functions do that (convert to arrays and use mutation internally).

But I just looked through more array methods, and certain ones do mutate the source array. E.g sortInPlace. So never mind that thought.

**Comment by MaybeSacred** [comment]
The [MoreLinq](https://github.com/morelinq/MoreLINQ/blob/64cb2632dd4e9813ae2dc2c0c6ab0aa7302bd70c/MoreLinq/RandomSubset.cs#L48) library has an implementation of this, and can be used from F# like this:
`let result = MoreLinq.MoreEnumerable.RandomSubset(mySeq, mySeq.Length)`
The MoreLinq package can be installed from [NuGet](https://www.nuget.org/packages/morelinq/)

**Comment by jbeeko** [comment]
This also has applications beyond data science. For example when polling for lists of messages to processes. Shuffling before processing the list will help ensure progress is made.

**Comment by duncanworthy** [comment]
As an example of non-data-science application, I have a script that I use in a build pipeline that zips and publishes some artifacts. The zip files are password protected and the password is generated in the script.

In Python you can write something simple like this:
```
characters = list(
  ''.join(random.choice(string.ascii_uppercase) for i in range(uppercaseCount)) +
  ''.join(random.choice(string.ascii_lowercase) for i in range(lowercaseCount)) +
  ''.join(random.choice(string.digits)          for i in range(numbersCount)) +
  ''.join(random.choice(string.punctuation)     for i in range(symbolsCount)))
random.shuffle(characters)
```

**Comment by dsyme** [comment]
I think we should consider doing this in F# 7, plus a whole suite of functions that incorporate randomness, including `List.sample` for example

1. There is now a `System.Random.Shared` in .NET 6 and we could use this as our default definition of randomness for basic random-dependent functions like shuffling.
2. We can define `List.shuffleWith` to allow an arbitrary System.Random.

**Comment by dsyme** [comment]
The Python random module has these:

* `random.shuffle`
* `random.choice`
* `random.choices`
* `random.sample`
* Plus various real-valued distributions https://docs.python.org/3/library/random.html#real-valued-distributions

It's actually a bit frustrating these aren't defined in .NET as methods of System.Random - there should be no real need to have an F#-specific API for this.

Still, we could definitely add standard collection functions corresponding to these.  Loosely speaking we'd want this, though not optional/named arguments are used in Python:

* `List/Array/Seq.shuffle xs`
* `List/Array/Seq.choice xs`
* `List/Array/Seq.choices (xs, [weights=None], [cum_weights=None], [k=1])`
* `List/Array/Seq.sample(xs, k, [counts=None])`

**Comment by BashkaMen** [comment]
try this
`open System


let shuffle xs seed = 
    let rnd = Random(seed)
    xs
    |> Seq.sortBy (fun x -> rnd.Next())
    

let source = [ 1.. 10 ]
printfn "%A" source
printfn "%A" (shuffle source Environment.TickCount)
printfn "%A" (shuffle source Environment.TickCount)`

**Comment by kspeakman** [comment]
> It's actually a bit frustrating these aren't defined in .NET as methods of System.Random - there should be no real need to have an F#-specific API for this.

Don't worry, it will show up in C# sometime after this. :)

Do you see a place in the API for a deterministic shuffle? (Randomness pre-generated and passed in.) I use that for testing my logic. Tests could also be instrumented with a mock System.Random as you mentioned. And that's what most people do for unit testing. I like to use plain data myself.

Regardless, I'm willing to help.

**Comment by davidglassborow** [comment]
> t's actually a bit frustrating these aren't defined in .NET as methods of System.Random - there should be no real need to have an F#-specific API for this.

Could we request they be added to the BCL ?

**Comment by dsyme** [comment]
I'm inclined to approve this.  I don't see any really fundamental reason why there shouldn't be a global random number generator for functions like these in the F# library.

I'm not planning to work on this.  But if you'd like to please submit an RFC.

**Comment by Lanayx** [comment]
Closing issue as [RFC](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1135-random-functions-for-collections.md) was merged
