### ISSUE TITLE
Allow intrinsic type extensions for provided types

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-suggestions#509]
# Allow intrinsic type extensions for provided types

I propose we allow intrinsic type extensions for provided types

Currently a compiler error is reported if this is attempted:
```
Error FS0192: internal error: FindTypeDefBuilder: <Method> not found (FS0192) (<Application>)
```

## Usage Example

Given a generative type provider that simply creates a generated type with a method named `MyMethod` and a property name `MyProperty`, and then intrinsically extends it adding a `Foo` property.

```fsharp
type t = BasicProvider.Generative.MyType with
  member x.Foo = 42
```

or long code form:
```fsharp
type t = BasicProvider.Generative.MyType

type t with 
    member x.Foo = 42
```

The resultant type would look like this:
```fsharp
type t =
  class
    new : unit -> t
    member Foo : int
    member MyMethod : unit -> string
    member MyProperty : string
```

## Pros and Cons 

The advantages of making this adjustment to F# are provided types can have extension added to them that much like partial classes in C# are used with generated code.  This is extremely advantages to code generation mechanism involved in GUI libraries

The disadvantages of making this adjustment to F# are added testing and implementation.  The language spec would have to be amended to un-depreciate the use of `with` to override and add member to *only* provided types.  

## Extra information

Estimated cost (M): 
This has already been partial implemented in https://github.com/Microsoft/visualfsharp/pull/882

## Affadavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [x] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cloudRoutine** [comment]
@dsyme wasn't this approved?

**Comment by dsyme** [comment]
@cloudRoutine Yes, it's just really hard to implement :)

**Comment by 7sharp9** [comment]
@dsyme Was the problem simply with the mechanism being used in fsi?

**Comment by 7sharp9** [comment]
The generated code from the compiler did indeed look correct for generative types, once thing that did need to be addressed was adjusting the language spec to un-depriciate the warning of using obsolete syntax in the definition of the intrinsically extended types.

**Comment by 7sharp9** [comment]
@dsyme Is there a way we can potentially progress this?  From my experience the only issue was no one understood the relocation of types in fsi, and also removing the warnings generated due to the the use of with to override and add member to only provided types.

**Comment by realvictorprm** [comment]
If no one has time to implement it further but can collect the necessary information I'm willing to do it.

**Comment by 7sharp9** [comment]
I'll start writing the RFC as I get time...

**Comment by 7sharp9** [comment]
RFC complete: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1061-Allow-intrinsic-type-extensions-for-provided-types.md

**Comment by realvictorprm** [comment]
@dsyme you can remove the `needs rfc` label

**Comment by realvictorprm** [comment]
It would be incredible useful to have this implemented as one then can implement a type provider which adds at compile time an encode and decode function to/from json for a given type :3

**Comment by dsyme** [comment]
I have archived the RFC due to inactivity https://github.com/fsharp/fslang-design/blob/main/archived/FS-1061-Allow-intrinsic-type-extensions-for-provided-types.md

**Comment by dsyme** [comment]
I'm closing this as I now accept it as a limitation of generated provided types, and there's no current known use case where this is needed.

**Comment by 7sharp9** [comment]
>and there's no current known use case where this is needed.

Any time you need to interact with generated code, especially useful for partial type implementations which are common in C#, this is the only solution to that other than inline insert code gen.  **This was all listed in the RFC.**
