### ISSUE TITLE
Allow flexible types in default constructor constraint

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#51]
**Submitted by George on 3/1/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

This would permit,
```
let ctor<'a when 'a:(new: unit -> #IWebDriver)> : unit -> IWebDriver = ...
```
versus
```
let ctor<'a when 'a:(new: unit- > 'a) and 'a :> IWebDriver> = fun () -> new 'a() :> IWebDriver
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12546540)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12546540-allow-flexible-types-in-default-constructor-const.md#comments)

**Comment by dsyme** [comment]
This seems to corner-case to consider
