### ISSUE TITLE
With ... construct to simplify syntax when accessing members of the object or record (from VB)

### ISSUE THREAD

**Issue by financial-engineer** [fsharp/fslang-suggestions#510]
# With ... construct to simplify syntax when accessing members of the object or record (from VB)

I propose we should add a with ... construct evaluating a series of expressions that repeatedly refer to a single object or record without specifying the name of that object or record multiple times. Within a with construct, one can specify a member of the object (a field of the record) starting with a period, as if the with construct object (record) preceded it.
For example, to change multiple properties on a single object, language users have to place the property assignments inside the with... construct, referring to the specified object only once instead of once for each property assignment.

## Syntax suggested:

```fsharp
with objectExpression do
(indentation)[ expressions ]
[done]
```

where:
- objectExpression is required. An expression that evaluates to an object. The expression may be arbitrarily complex and is evaluated only once, upon entry into the with ... construct. The expression can evaluate to any data type, including elementary types. Nobody can reassign the objectExpression from within the with ... construct.
- expressions are non-mandatory. One or more expressions between the with, done keywords that may refer to members of an object that's produced by the evaluation of objectExpression. Unless the with ...  construct contains a loop, the expressions run only once. 
- the done keyword is non-mandatory. Terminates the definition of the with ... construct.

## Usage example
```fsharp
// Each with ... construct evaluates a series of expressions on a single object
open System.Collections.Generic
type Customer() =
        member val Name = "" with get, set
        member val City = "" with get, set
        member val URL = "" with get, set
        member val Comments = new List<string>() with get, set

let customer = new Customer()
with customer do
     .Name <- "John Doe"
     .URL <- "http://www.johndoe.com/"
     .City <- "Los Angeles"
     printfn "Customer's name is %s, url is %s, city is %s" .Name .URL .City 
// the done keyword is non-mandatory, so it is absent here
with customer.Comments do
     .Add("First comment.")
     .Add("Second comment.")
done
```
   
## Clarification
Within a with ...  construct, one can access the methods and properties of only the specified object without qualifying them. One can use methods and properties of other objects, but they must be qualified with their object names.

## Nested with ... constructs
One can place one with... construct within another. Within the nested with ... construct, the syntax refers to the inner object.  For example:

```fsharp
let window = new EntryWindow()
with window do
      with .InfoLabel do
           .Content <- "This is a message."
           .Foreground <- Brushes.DarkSeaGreen
           .Background <- Brushes.LightYellow
       done
       .Title <- "The Form Title"
       .Show()
done
```

One must provide a fully qualified reference to an object that's in an outer with ...  construct when the object is referenced from within an inner with ... construct in order to eliminate ambiguity. 

## Alternative design decision
If you feel the do, done keywords within the with ... construct do not suit F# design principles, please consider an alternative syntax option:

```fsharp
// like in VB
with objectExpression 
(indentation) [expressions]  
[end] [with]
```

## Existing approach to this problem
The existing way of approaching this problem in F# needs to be changed. Now, if code accesses the same object in multiple expressions, language users have to specify the name of the object again and again. Repetitive qualifying expressions worsen code readability.

## Pros and Cons 

The advantages of making this adjustment to F#" are
- language users using the with ... construct to accesses the same object in multiple expressions can make code more readable by eliminating repetitive qualifying expressions,
- language users don't need to evaluate a complex expression multiple times or assign the result to a temporary value to refer to its members multiple times,
- no new keywords are needed to implement the syntax suggested.

The disadvantages of making this adjustment to F# are 
- time is needed to implement that in the compiler.

## Extra information
Please see how it was implemented in VB: https://msdn.microsoft.com/en-us/library/wc500chb.aspx

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: no.

## Affadavit 

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  This is not a fundamental design decision that has obviously already been taken (typing discipline etc.).

Please tick all that apply:
* [x] This is not a breaking change to the F# language design. That's an addition to F# aimed at writing more simple code that follows the DRY (Don't Repeat Yourself in code) principle.
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cloudRoutine** [comment]
Expressions can have multiple bindings assigned simultaneously
```fsharp
type LexiCog = {
    mutable Alpha   : int
    mutable Beta    : int
    mutable Gamma   : int
}

let rekt & r = {Alpha=1;Beta=2;Gamma=4} 
r.Alpha <-22
r.Beta <-100
r.Gamma <-34
;;
rekt
```
```
> rekt;;
val it : LexiCog = {Alpha = 22;
                    Beta = 100;
                    Gamma = 34;}
```
> assign the result to a temporary value to refer to its members multiple times.

binding the expression allows more flexibility of usage throughout its scope

> can make code more readable by eliminating repetitive qualifying expression

If the identifier is long enough that this is an issue, binding it to an abbreviated identifier is satisfactory, but I don't think this hurts readability in the first place

> one can access the methods and properties of only the specified object without qualifying them.

This creates the ambiguous case of 
```
let woe = someObj()
with woe do 
      .method1  .propA .propB
```
where a curried method of `woe` is being called with two of `woe`'s properties

The proposed syntax increases complexity with negligible benefit.

**Comment by vasily-kirichenko** [comment]
`with` syntax has been available in Object Pascal for a couple of decades. People find it one of the worst language design mistakes because scopes are getting really messy and hard to reason about.

**Comment by AlOdeychuk** [comment]
@cloudRoutine, @vasily-kirichenko, thank you for your expert feedback, but I have to speak a few words for my suggestion (#510).

@cloudRoutine 
As to your code snippet
```
let woe = someObj()
with woe do 
      .method1  .propA .propB
```
I think everything depends on 
- Signatures of method1, propA, propB,
- How names of members and properties are indented, on which line they are written, because F# has indentation-based syntax.
- So, if method1: int -> string -> unit, propA: int with get, propB: string with get, than
-	propA returns int, propB returns string, 
-	method1, propA, propB are written on the same line, so the value computed on the last line within the with construct is returned by that construct, 
-	.method1  .propA .propB means (woe.method1 woe.propA woe.propB) and that line of code returns unit, 
-	code is compiled successfully.
- But if method1 has, for example, the following signature: int -> string -> int -> unit, than 
-	the with construct does not return unit and the compiler emits an error: FS0001: This expression was expected to have type unit but here has type int -> unit, 
-	code is not compiled.

So, I think your code snippet does not create the ambiguous case from the reader's perspective. If I misunderstood you, please explain what ambiguity could emerge in your code snippet.
As to your criticism of using the with construct for processing record fields, I admit that the with construct has the potential to be most useful when dealing with objects (especially objects with child items, most likely in WPF F# apps), not records. 

@vasily-kirichenko 
I agree with you that Object Pascal's with syntax is hard to reason about, but I believe this is due to the lack of a period before a member name of the object (record field) within the with construct. If the name of a member of the object (record field) is identical to the name of a value of another type, the Pascal-style syntax leads to ambiguity from a reader's perspective, like here: 
```
type Lexeme = {
     mutable verb : string
     mutable isRegular: bool }
let mutable verb = "greet"
let lexeme : Lexeme = { verb = "perform"; isRegular = true }
with lexeme do
      // Object Pascal-style syntax problem: Is it a reference to 
      // verb (named value) or lexeme.verb (record field)?
      verb <- "stop" 
```
I suggested borrowing syntax mainly from VB where:
- a leading period is mandatory for member names of the object used without a qualifier within a with construct. It prevents the above-mentioned ambiguity.
- a special rule exists in order to eliminate ambiguity when nesting with constructs:

> One must provide a fully qualified reference to an object that's in an outer with ... construct when the object is referenced from within an inner with ... construct.

For example,
```
let window = new EntryWindow()
with window do
      with .InfoLabel do
           .Content <- "This is a message."
           .Foreground <- Brushes.DarkSeaGreen
           .Background <- Brushes.LightYellow
           // .Title <- "The Form Title" is illegal here because it creates ambiguity 
           // (Is it window.Title or window.InfoLabel.Title?). 
           // As the rule dictates you must provide a fully qualified reference to 
           // an object that's in an outer with construct 
          window.Title <- "The Form Title" 
      done
      // .Title <- "My Title" is legal here. You do not need to provide a fully qualified reference 
      // to an object because it within "its own" with construct
      .Title <- "My Title" 
      .Show()
done
```
So, scopes remain clear in the syntax suggested.

**Comment by smoothdeveloper** [comment]
One issue is to disambiguate with method chain such as LINQ calls, which tend to be split with one call per line with a leading dot.

I'm not too fond of with in any of the languages having it, maybe a syntax inspired from constructor initializer would make sense?

**Comment by matthid** [comment]
Sorry, I couldn't resist:

```
open System.Collections.Generic
type Customer() =
        member val Name = "" with get, set
        member val City = "" with get, set
        member val URL = "" with get, set
        member val Comments = new List<string>() with get, set

// I think we already have this feature
let withDo w f = f w

// Usage
let customer = new Customer()
withDo (customer) (fun w ->
    w.Name <- "John Doe"
    w.URL <- "http://www.johndoe.com/"
    w.City <- "Los Angeles"
    printfn "Customer's name is %s, url is %s, city is %s" w.Name w.URL w.City 
)

withDo customer.Comments (fun w ->
    w.Add("First comment.")
    w.Add("Second comment.")
)

// Actually its embedded in the standard library
let (|>) w f = f w

// Usage
(customer) |> (fun w ->
    w.Name <- "John Doe"
    w.URL <- "http://www.johndoe.com/"
    w.City <- "Los Angeles"
    printfn "Customer's name is %s, url is %s, city is %s" w.Name w.URL w.City 
)

// or
(|>) (customer) (fun w ->
    w.Name <- "John Doe"
    w.URL <- "http://www.johndoe.com/"
    w.City <- "Los Angeles"
    printfn "Customer's name is %s, url is %s, city is %s" w.Name w.URL w.City 
)

```
This works in my limited testing. As you can see the syntax is a bit different, but
if you can live with the special keyword `w` in the `withDo` context everything is fine ;)

By the way scoping and nesting works as one would expected from similar features like inline lambdas.

Hope that works.

**Comment by cloudRoutine** [comment]
@matthid I'd make a minor adjustment
```fsharp
let withDo w f = f w; w

let customer = withDo (new Customer()) (fun w ->
    w.Name <- "John Doe"
    w.URL <- "http://www.johndoe.com/"
    w.City <- "Los Angeles"
    printfn "Customer's name is %s, url is %s, city is %s" w.Name w.URL w.City 
)
```

**Comment by fsoikin** [comment]
Actually, you don't even need to introduce the `withDo` function.

```
let customer = 
    let w = new Customer()
    w.Name <- "John Doe"
    w.URL <- "http://www.johndoe.com/"
    w.City <- "Los Angeles"
    printfn "Customer's name is %s, url is %s, city is %s" w.Name w.URL w.City 
    w
```

**Comment by dsyme** [comment]
Many thanks for the suggestion. We won't be adding this syntax in F# - the discussion above has captured the pros and cons well.
