### ISSUE TITLE
Make SRTP constraints work on C# properties

### ISSUE THREAD

**Issue by pirrmann** [fsharp/fslang-suggestions#512]
# Make SRTP constraints work on C# properties

I propose we allow SRTP constraints to find getters of properties on regular C# types (or types provided by generative type providers).

Today, the infered constraint by a function such as `let inline extractA (x:^t) = (^t:(member A: string) x)
` is that the type `^t`must have a `get_A` member. However, this constraint is not satisfied by the "standard" implementation of a property in C#. I think that this is because the generated method is not public and/or is marked with special name.

## Pros and Cons 

The advantages of making this adjustment to F# are that we can use SRTPs on C# types and types generated by generative type providers.

I don't see any disadvantages of making this adjustment to F#.

## Extra informtion

Estimated cost: XS

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
This seems to work for me, is there something I'm missing?
```
let inline extractA (x:^t) = (^t:(member Count: int) x)

let res = extractA (new System.Collections.Generic.List<int>())
```

**Comment by pirrmann** [comment]
You are totally right I had a typo in my C# class, so member constraint do work on C# classes.
However I still have the problem on types generated by a generative type provider, which is the root reason why I tried to see if it was working on C# classes.
I'm not using the latest version of ProvidedTypes, so I'll try update to the latest. It's most probably not a language/compiler issue, I just have to make sure that the generated type is identical to a regular "hand-written" type.
Thanks for your help.
