### ISSUE TITLE
Fix indentation ambiguities when attributes are involved

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-suggestions#514]
I propose we fix the issues that causes incorrect throwing of *FS0058 warning on incorrect indentation*, and that we accept the left-most point of a line as its indentation start-point.

Currently, if you write `[<Literal>] let x = 12`, the warning is raised on the the position *after* `[<Literal>]`, placing several literals underneath each other is therefore impossible. However, the warning itself points to the wrong position, you can indent the next line by one column to remove the warning.

For attributes that involve parameters, the FS0058 error is raised on the wrong position entirely.

### Let bindings repro

This throws FS0058 on "let"

```fsharp
module Literals =
    [<Literal>] let First = 1
    [<Literal>] let Second = 2
    //..........^.............    // location of the FS0058 warnings
```

Minimal indentation to prevent warning (which oddly suggests it is an inner let-binding, but this is not how it gets compiled)

```fsharp
module Literals =
    [<Literal>] let First = 1
     [<Literal>] let Second = 2
```
### Let bindings with parens repro

```fsharp
module Literals =
    [<CompiledName("Boolean")>]  let boolean = true
    [<CompiledName("MyString")>] let myString = "test"
    //............^..............^....................   // locations of the FS0058 warnings
```

Minimal indentation to prevent both warnings (to prevent only the second, one space is enough):

```fsharp
module Literals =
    [<CompiledName("Boolean")>]  let boolean = true
                    [<CompiledName("MyString")>] let myString = "test"
```

## Pros and Cons 

The advantages of letting the indentation position start at the `[` of the attribute is that your code becomes more legible. It also removes the ambiguity that it gets the position wrong in the warning itself.

All in all it simply creates a more orthogonal coding experience: the indentation rule is that the next line must start on the same position as the previous line (or indented if it is part of the scope of the previous line).

I don't see disadvantages at the moment, but feel free to comment on it if there are. Since it fixes an error scenario, there are no backward incompatibility issues.

## Extra information

I have to admit that I don't know the complexity of fixing this is. 

I raised this originally as a bug (and I think that in part it still is a bug) here: https://github.com/Microsoft/visualfsharp/issues/1649

**Related Suggestions**
* [Make the single-line use of [<Literal>] consistent](https://github.com/fsharp/fslang-suggestions/issues/409)
* [Allow Attributes to follow the member keyword](https://github.com/fsharp/fslang-suggestions/issues/33)

## Affidavit 

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cloudRoutine** [comment]
actually it's already possible
```fsharp
let [<Literal>] First = 1
let [<Literal>] Second = 2
```

**Comment by AlOdeychuk** [comment]
this code is much more readable and elegant
```
[<Literal>] let First = 1
[<Literal>] let Second = 2
```
I support abelbraaksma's suggestion.

**Comment by abelbraaksma** [comment]
@cloudRoutine, I know that that's an alternative syntax, but that doesn't remove the ambiguity in the current indentation rules if you don't abide by that syntax, and as @AlOdeychuk mentions, orthogonality in syntax is a good thing, and indeed more readable. 

If the ground rule is that the `let` must start on the same column, then that should apply here as well, but presently it doesn't (and I believe there is something to say for letting the column of the current statement start at the beginning of the attribute).

**Comment by cloudRoutine** [comment]
> placing several literals underneath each other is therefore impossible
@abelbraaksma this is all i was responding to

I agree regarding the indentation rule, [I've made the same point regarding generic signatures](https://github.com/fsharp/fslang-suggestions/issues/504)

**Comment by abelbraaksma** [comment]
FWIW, the warning is still there in VS2017 latest preview version:

![image](https://user-images.githubusercontent.com/16015770/29544250-139f672a-86e7-11e7-9a03-cdcafc8bf676.png)

**Comment by abelbraaksma** [comment]
@dsyme, I think this could work if the offset is not taken into account when inside a an attribute. In other words, `[<SomeAttribute>] let x` should have offset for `let` as if it is at `[`, which allows a more natural flow:

```f#
[<SomeAttribute>] let x =
    12 + 30
```

Or:

```f#
[<SomeAttribute>] let x = 12 + 30
[<SomeAttribute>] let y = 12 + 30
```

Or

```f#
[<SomeAttribute>] let x = 12 + 30
let y = 12 + 30
```

would then all be valid. I'd be interested in resolving this, but then this lang-suggestion should first get some "approved-in-principle" or the like from you or someone else at the team (@KevinRansom, @cartermp perhaps?). I am not sure it requires a full RFC, as I think the spec is currently fuzzy about the position-count in these respects, but I have no problem writing one.

Perhaps fixing this could also help me get some pointers about fixing the problems with static type constraints (this too requires far right-indent, several issues have been reported about it).

**Comment by cartermp** [comment]
IMO this feels more like a bug than anything else, though @dsyme has the final word here.

**Comment by abelbraaksma** [comment]
@cartermp, yes, and it was first reported as a bug ;). In the OP I apparently wrote (but then forgot):

> I raised this originally as a bug (and I think that in part it still is a bug) 

But I think [this summarizes](https://github.com/Microsoft/visualfsharp/issues/1649#issuecomment-256293180) the reason why @dsyme wanted to see this done through an RFC:

> I'm more referring to the risk of cascading changes to other code, which is best assessed through an RFC process I think.

**Comment by dsyme** [comment]
@cartermp It's certainly a glitch but I'm always concerned about the potential for fixes to destabilize things

**Comment by abelbraaksma** [comment]
@dsyme, talking about consistency, it currently works properly for types, but not (yet) for let-bindings. This suggests to me that the necessary machinery is already available in the parser, it just doesn't currently consider attributes, whereas it does consider them for types:

```f#
[<AutoOpen>] 
module M =      
    [<AbstractClass>] type C() = class end
    [<AbstractClass>] type D() = class end  // no indentation warning
    [<AbstractClass>] type E() = class end  // no indentation warning
    [<Literal>] let X = 3 
    [<Literal>] let Y = 3    // indentation warning
    [<Literal>] let Z = 3    // indentation warning
```

**Comment by dsyme** [comment]
Looking through the examples above, they all involve one-line `[<Attr>] let` which is really not a standard coding style.

I don't think we need to specifically do anything here.  `let [<Attr>] f ... ` is available, as is the more normal multi-line forms of these
