### ISSUE TITLE
Case study link not working

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [fsharp/fslang-suggestions#520]
I've tried to bring this to the attention of several people to no avail, so I'm posting it here!

The link to the F# case study here, is broken:

https://blogs.msdn.microsoft.com/dsyme/2010/06/28/f-case-study-banking-firm-uses-functional-language-to-speed-development/

There seems to be no centralized MS page that collects case studies together, and these are immensely useful when discussing the adoption of this language with managers and executives.

Thx

**Comment by dsyme** [comment]
@hgleaves-ncuadmin I've removed the dead link, thanks
