### ISSUE TITLE
Implement Async.StartImmediateAsTask [ RFC FS-1028 ]

### ISSUE THREAD

**Issue by OnurGumus** [fsharp/fslang-suggestions#521]
# Async.StartImmediateAsTask 
I propose we  provide a better way to interop with System.Threading.Tasks.

The existing way of approaching this problem in F# is there is no easy and proper  
way to convert an async workflow and run it as Task with true asynchronity.

Here's an example:

```
open System.Threading
open System.Threading.Tasks
open System
let convertToTask<'T> (asyn : Async<'T>) =
       let tcs1 = new TaskCompletionSource<'T>()
       let t1 = tcs1.Task
       Async.StartWithContinuations(
          asyn
          , (fun (k) -> tcs1.SetResult(k)), (fun exn -> tcs1.SetException(exn)), fun exn -> tcs1.SetCanceled())
       t1


let doSomeStuff2() =
    async {
        printfn "4- %A" (Thread.CurrentThread.ManagedThreadId)
        do! Async.Sleep 1000
        printfn "5- %A" (Thread.CurrentThread.ManagedThreadId)
        return 1
    }


let doSomeStuff() =
    async {
        printfn "2- %A" (Thread.CurrentThread.ManagedThreadId)
        do! Async.Sleep 1000
        printfn "3- %A" (Thread.CurrentThread.ManagedThreadId)
        let! z = (doSomeStuff2())
        printfn "6- %A" (Thread.CurrentThread.ManagedThreadId)
        return z
    }
    |>Async.StartAsTask  //key line
// |> convertToTask

[<EntryPoint>]
let main argv =
  //  raise(new Exception())
    Console.WriteLine( "1- {0}", (Thread.CurrentThread.ManagedThreadId))
    let z = doSomeStuff().Result
    Console.ReadLine()
    0
```

If you run this program the output is:
1- 1
2- 3
3- 4
4- 4
5- 3
6- 3

As you see we employ "async all the way" strategy but still there is a thread switch occurring after step 1,2 and 4. 
If we comment out   |>Async.StartAsTask   but comment in  |> convertToTask line then the output changes to following:
1- 1
2- 1
3- 4
4- 4
5- 4
6- 4

Now that's much better. The thread change in step 2 obviously occur as we run a Console app without a synch context. If this were a UI app or Web API then even there wouldn't be any changes at all.

I believe this is the most desired behavior. Also regardless the task conversion I also suggest a similar overload like
Async.StartImmediateAsTask

The other implementations fail to achieve the behavior.  Async.StartImmediate doesn't return a value and it causes a thread switch. 

## Pros and Cons 

The advantages of making this adjustment to F# are ...
This is a common required functionality.
The disadvantages of making this adjustment to F# are ...
Perhaps Async methods become too crowded
## Extra information

Estimated cost : S

Related suggestions: (put links to related suggestions here)
[stackoverflow](http://stackoverflow.com/questions/22784350/consuming-f-async-from-c-sharp)
## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [ x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x] This is not a breaking change to the F# language design
* [x ] I would be willing to help implement and/or test this
* [x ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
So you're proposing ``Async.StartImmediateAsTask``?  Seems reasonable.

**Comment by OnurGumus** [comment]
Yes, exactly!

**Comment by matthid** [comment]
Yes there is definitely a need for that: https://github.com/matthid/Yaaf.FSharp.Helper/blob/master/src/source/Yaaf.FSharp.Helper/Helper.fs#L192-192

I called it slightly different though.

**Comment by dsyme** [comment]
Marked as approved in principle.  Please go ahead and submit an implementation (to Microsoft\visualfsahrp) and RFC (to fslang-design)

**Comment by cartermp** [comment]
Closing as completed.
