### ISSUE TITLE
Add an either function to the Option and Result module

### ISSUE THREAD

**Issue by rexcfnghk** [fsharp/fslang-suggestions#526]
# Title of Suggestion

I propose we add an `either` function to the `Option` and `Result` module.

The existing way of approaching this problem in F# is to define it ourselves:

```f#
module Option
    let either some none = function
        | Some x -> some x
        | None -> none

module Result
    let either ok error = function
        | Ok x -> ok x
        | Error e -> error e
```

## Pros and Cons 

The advantages of making this adjustment to F# are

- It is a typical usage of `Option` and `Result` to perform branching when the result is considered 'valid' (e.g. `Some x`/`Ok x`)

The disadvantages of making this adjustment to F# are

- Extra API on both modules
- Extra tests needed

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by vasily-kirichenko** [comment]
I don't see any advantages over pattern matching here.

**Comment by rexcfnghk** [comment]
@vasily-kirichenko there is an advantage that one can partially apply `Option.either`/`Result.either` to get a default error/success handling mechanism.

**Comment by kspeakman** [comment]
I have to define or import these (particularly `Result.either`) in every project. It also is the basic building block for other functions (bind, map, tee) to support functional error handling. The `either` implementation is both simple and uncontroversial. The only issue I can see someone raising is the name "either". But it doesn't really matter what name is used as long as the name was appropriate to its function.

_vs pattern matching_

It gets to be pretty verbose boilerplate when using pattern matching for error handling.

```fsharp
match someOp input with
| Error err -> createErrorResponse err
| Ok opValue ->
    match nextOp obValue with
    | Error err -> createErrorResponse err // dupe code
    | Ok v -> createResponse v

// VERSUS

someOp input
|> Result.bind nextOp
|> Result.either createResponse createErrorResponse

// Result.bind defined as:
// let bind f = either f Error
```

**Comment by theprash** [comment]
@kspeakman That nested pattern matching example isn't quite fair because you could use the existing `Result.bind` to avoid the nesting:

```fsharp
someOp input
|> Result.bind nextOp
|> function
| Ok v -> createResponse v
| Error e -> createErrorResponse e
```

It's still not as concise as `either` but at least it's not nested.

**Comment by kspeakman** [comment]
@theprash That's a good point. I'm not using VS 2017 RC so Result doesn't exist for me, much less Result.bind.

Bottom line: `either` is useful at the end of a chain. It is also a building block to fill in other common functions that may not be defined by the F# core library. E.g. (Result.)bimap, tee, etc.

**Comment by jakubsuchybio** [comment]
I don't know if I am wrong, but I think, that this would add value in Railway oriented programming ( more here: http://fsharpforfunandprofit.com/posts/recipe-part2/ )
It's a great way for propagating error without any hassle of nested matching.
```Option``` is good, but having a message or data about the failure is sometimes critical to have.

**Comment by cartermp** [comment]
@jakubsuchybio This will be available in F# 4.1, where `Result` is a new type in FSharp.Core.

**Comment by danielo515** [comment]
This was back on 2016, is 2018 now. Is this a reality ?

**Comment by dsyme** [comment]
@danielo515 This suggestion hasn't actually been approved, and I don't think we'll be doing it

**Comment by abelbraaksma** [comment]
> This will be available in F# 4.1, where Result is a new type in FSharp.Core.

Though that part has happened meanwhile. But `either` didn't...

**Comment by cartermp** [comment]
@abelbraaksma I believe I was referring to this:

> `Option` is good, but having a message or data about the failure is sometimes critical to have.

I probably should have quoted that.

**Comment by kspeakman** [comment]
@danielo515 This is not referring to creating an Either type. Two of these already exist in ChoiceOf2 and Result. This is referring to including an `either` function on Option and Result.

On `Option` two existing functions can be combined to emulate an `either` function. Namely, `Option.map fSome >> Option.defaultValue noneValue`. But no such built-in alternative exists for `Result` to unify the Error and Ok values. You have to do a full match statement instead. I need to do such a thing, for example, at the end of a handling an HTTP request to convert the Result to an HttpResponse. The default way would be something like this:

```fsharp
handle request
|> function
    | Error error -> toHttpError error
    | Ok ok -> toHttpSuccess ok
```

I always end up copying a helper library between different solutions which includes an `either` function that I can use like this:

```fsharp
handle request
|> Result.either toHttpError toHttpSuccess
```

The suggestion is implying that this would be a useful function to have defined in the core library. In my own library, I have trivially defined it as:

```fsharp
namespace MyOwnNamespace

module Result =

    let either fError f result =
        match result with
        | Error error -> fError error
        | Ok ok -> f ok
```

I previously had the Ok function first, but as I worked with ROP, I found putting the error fn first made more sense.

**Comment by baronfel** [comment]
@kspeakman good points! I usually call this `Recover` and my use case is exactly the same as yours: unifying to a common outside serialization format.

**Comment by gusty** [comment]
I definitely find it a very convenient function. I also find convenient other functions like [option](https://github.com/fsprojects/FSharpPlus/blob/d231618b988ff993d73863511ca4a4f459d19978/src/FSharpPlus/Operators.fs#L20) which makes it very easy to "adapt" an option to a Result by specifying the error message function.

In F#+ [either is defined](https://github.com/fsprojects/FSharpPlus/blob/d231618b988ff993d73863511ca4a4f459d19978/src/FSharpPlus/Operators.fs#L18) same way as @kspeakman did but with the arguments swapped, the `fError ` doesn't come first. I think this makes more sense because normally in F# functions and types the "good case" is the first one.

**Comment by abelbraaksma** [comment]
> I always end up copying a helper library between different solutions which includes an either function that 

Isn't that the typical thing to do for just about any project? Every programmer has a set of favorite functions, for instance I do a lot with string processing and have a standard "commons" library that I include in just about any project, which simplifies string handling, matching etc in F# syntax.

Just saying that I having to copy (or make it into a nuget lib) your library between projects is generally a good thing. And as @gusty mentioned, some of your favs may already exist in extension libs like F#+.

**Comment by kspeakman** [comment]
@abelbraaksma I would appreciate a little credit in judgement. I don't contribute to github issues requesting every varied and sundry helper function I use -- only ones that I think are useful to many. Otherwise, why have a core library at all?

@gusty I did it that way at first, with the error 2nd, but as I went along I figured out that putting the error first makes it handy to partially apply the error, which is often a fixed value. Even if you don't partially apply, it also reads as though you are running the same function and putting the error stuff in front.

**Comment by kspeakman** [comment]
@gusty Yes, I can appreciate that. The main thing is that there is currently no function in the core library to extract the Result value. Whereas for Option there are two (`defaultValue` and `defaultWith`). The absence seems notable by comparison. That's the last thing I'll say about it.

**Comment by cartermp** [comment]
@kspeakman I think that's a reasonable way to look at it. Having symmetry with the `Option` module seems like something most people would expect. It seems like additions to the `Result` module are spread out over multiple issues, when I think what most people want is symmetry. At least that's what I'd consider taking into the core library (though @dsyme has the final say here).

**Comment by abelbraaksma** [comment]
@kspeakman, apologies, rereading my comment it does look rather coarse and unthoughtful. 

I do remember a discussion when Result was added to 4.1 that @dsyme wanted to get it in and leave decisions on the list of functions to be added for a later date, primarily not to delay the process too much (I don't remember the thread though).  Aligning it more with Option seems a good thing, and I reckon there must be quite some functions that should still make it into the surface area for Result.

**Comment by dsyme** [comment]
Closing as I agree with the old comment from @vasily-kirichenko that there are no advantages over pattern matching here

**Comment by kspeakman** [comment]
@dsyme I want to note that I've changed my mind on this (and probably most issues about helper functions). I used helpers extensively on exactly one project. That was enough to make me realize that, for coding logic especially, it's harder to work with and read than being more explicit.

**Comment by dsyme** [comment]
> @dsyme I want to note that I've changed my mind on this (and probably most issues about helper functions). I used helpers extensively on exactly one project. That was enough to make me realize that, for coding business logic especially, a lot of helper chaining is harder to work with and read than being more explicit.

Thanks! That's useful to know
