### ISSUE TITLE
chooseType for List, Array and Seq modules

### ISSUE THREAD

**Issue by sergey-tihon** [fsharp/fslang-suggestions#527]
# Enumerable.OfType<TResult> equivalent for List, Array and Seq modules

I propose to extend `List`, `Array` and `Seq` modules with equivalent to [Enumerable.OfType<TResult>](https://msdn.microsoft.com/en-us/library/bb360913(v=vs.110).aspx)

The existing way of approaching this problem in F# is
```fsharp
// Option 1
itemsArray |> Array.choose (function | :? 'a as x -> Some(x) | _ -> None)
// Option 2
itemsArray.OfType<TResult>() |> Seq.toArray
```
more options a mentioned on [StackOverflow](http://stackoverflow.com/questions/2521254/f-equivalent-to-enumerable-oftypea)

## Pros and Cons 

The advantages of making this adjustment to F# are:
- Improvements of code readability and succinctness
- Avoidance of the LINQ usage.

The disadvantages of making this adjustment to F# 
- ???

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by slang25** [comment]
I'd like to vote for `ofType` being defined in each module. At the moment in a lot of my projects I use this:
```fsharp
Module Seq = 
    let ofType<'a> (items: _ seq)= items |> Seq.choose(fun i -> match box i with | :? 'a as a -> Some a |_ -> None)
```
I think this makes it discoverable, and where people might expect to find it.

**Comment by ErikSchierboom** [comment]
Nice suggestion! I assume this is a relatively small feature, so could this be something that someone new to the F# compiler (like me) can pick up? If so, I'd love to give it a go.

**Comment by Happypig375** [comment]
Has this been approved yet?

**Comment by cartermp** [comment]
@Happypig375 Nope, that requires the `approved-in-principle` label.

**Comment by dsyme** [comment]
@cartermp What do you think about this?

* Historically we haven't particularly emphasized runtime-type-based classification/filtering/querying as a technique in FSharp.Core.  But it's entirely consistent with the rest of F# to do so.

* There are no downvotes, a good number of upvotes.  

So I'd say yes, we could do this, there's no real reason not to

**Comment by cartermp** [comment]
My only question would be if this is also considered valid for Fable usage, but otherwise I don't see a reason not to add this

**Comment by deviousasti** [comment]
Fable can test the run-time type limited to classes.
```
let isOfT = k :? T
```
```
export const isOfT = k instanceof T;
```

**Comment by Liminiens** [comment]
It’s reasonable to have such functions at core library when you do interop with frameworks like Xamarin, where you sometimes have to get a collection of a more concrete type. Or find first element that first satisfies some type. Example is `Effects` on a control.

**Comment by Happypig375** [comment]
RFC here: https://github.com/fsharp/fslang-design/pull/582

**Comment by Happypig375** [comment]
This should be called `chooseType` instead of `ofType` because functions starting with `of` in F# signify creation from another type which is not the case here, instead this function is more similar to `choose`.

**Comment by charlesroddie** [comment]
This is a bad addition to allow as it makes it easier to downcast. The symbol `?` in the explicit downcast operator indicates that something can go wrong, and is easy to flag in code review as a code smell. `itemsArray.OfType<TResult>() |> Seq.toArray` doesn't have anything that looks wrong about it until you investigate the type signature of OfType. An F# user that has not done this might assume that it is something safe and only allows upcasting. So it is harder to keep F# codebases clean with this addition.

If renamed to `OfTypeUnsafe` it would more clearly express the dangers and be much easier to avoid. Although really better to put this in an FSharp.Unsafe library rather than in FSharp.Core.

**Comment by Happypig375** [comment]
RFC discussion here: https://github.com/fsharp/fslang-design/discussions/581

**Comment by dsyme** [comment]
The RFC has been archived as we decided not to progress it.  I will close this suggestion as declined
