### ISSUE TITLE
Allow multiple base types/interfaces on flexible type annotation

### ISSUE THREAD

**Issue by Calogyne** [fsharp/fslang-suggestions#528]
# Multiple base types/interfaces on flexible type annotation

I propose we provide a more succinct way to write flexible type that's compatible with multiple base types or interfaces.

Currently in F#, doing so requires writing a rather tedious type constraint, for example:
```fsharp
let multipleInterfaces (x: 'a when 'a :> IEquatable<'T> and 'a :> IComparable) = ()
multipleInterfaces 1

//or hacking with type alias
type EquatableAndComparable<'T, 'a when 'a :> IEqutatable<'T> and 'a :> IComparable> = 'a
let multipleInterfaces' (x: EquatableAndComparable<'T, 'a>) = ()
multipleInterfaces' 1
```

A possible syntax could be:
```
let multipleInterfaces (x: #(IEquatable<'T> and IComparable)) = ()
```
## Pros and Cons 

Pro: This saves some extra typing.
Con: Adds a little more cost to learn the language.

## Extra informtion

Estimated cost (XS): 

See "Protocol Composition" on https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html#//apple_ref/doc/uid/TP40014097-CH25-ID267

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cartermp** [comment]
I like this idea.

**Comment by dsyme** [comment]
My feeling is that we should probably not add new syntax for this relatively rare case, mostly based on cost/benefit.  At least, it doesn't feel like a priority for the language design.    There is quite a lot of cost in testing new syntax, e.g. w.r.t. autocomplete.

That said the request is not unreasonable. If an implementation was completed and "just worked" then that would of course improve the cost/benefit ratio.  So if you you want it, please do go ahead and trial an implementation?

**Comment by smoothdeveloper** [comment]
Understandable, the type alias syntax is actually a compelling workaround.

**Comment by dsyme** [comment]
Closing this as per my comment above
