### ISSUE TITLE
Autogenerated lazy record constructors (like type alias in Elm)

### ISSUE THREAD

**Issue by gentauro** [fsharp/fslang-suggestions#533]
# Autogenerated lazy record constructors

I propose we introduced the concept (and keyword) **alias** like it's used in [Elm Type Aliases](https://guide.elm-lang.org/types/type_aliases.html). This approach would allow **records** to be lazy constructed. In the following example I will show what happens if we don't assign all the properties of a record when it's constructed:
```
type Order =
  { buyer : Person
  , seller : Person
  , shipping : (DateTime * Transport)
  }

let order = { buyer: ramon; seller: don; shipping: ... }
```
As I don't really know which shipping date or type of transport I'm going to use, I really can't initialize the record, so I have to make a modification to the design:
```
type Order =
  { buyer : Person
  , seller : Person
  , shipping : (DateTime * Transport) option
  }

let order = { buyer: ramon; seller: don; shipping: None }
```
If we had the lazy and built-in record constructors, we could maintain the initial design, and construct our record only waiting for shipping information:
```
type alias Order =
  { buyer : Person
  , seller : Person
  , shipping : (DateTime * Transport)
  }

let order = Order ramon don
(later in code)
let order' = order (date,transport)
```
The reason we mimic the alias keyword, is that we don't want this to happen for all of the records in F#, so we think of it as an ad-hoc approach, just like using the keyword **lazy** for lazy evaluated code.

The existing way of approaching to solving this issue right now in F#, is by writing a non-idiomatic (Pascal-case) function with the same name as the type or as @vivainio suggested on Twitter, by creating a curried method on the record:

```
type Order =
  { buyer : Person
  , seller : Person
  , shipping : (DateTime * Transport)
  }
let Order : Person -> Person -> (DateTime * Transport) =
  fun buyer seller shipping -> { buyer: buyer; seller: seller; shipping: shipping }

let order = Order ramon don
(later in code)
let order' = order (date,transport)
```

[Tweet with suggested idea and picture of code](https://twitter.com/genTauro42/status/826917303585472512)

Both task can be tedious and monotone and are not error-prone, so It would be ideal if a machine could perform this task.

## Pros and Cons 

The advantages of making this adjustment to F# are easy readability and usage, sound design, less code to write, therefore less errors.

The disadvantages of making this adjustment to F# are introducing a keyword would probably have to a HUGE design consideration, therefore, if there is another approach that would be welcome as well

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL). I can't evaluate this, but I would be willing to work on it :+1: 

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by isaacabraham** [comment]
I can see this also potentially having good utility when working with monadic bind e.g. set the values of each fields of a record if they are successfully parsed from a weakly-typed string. Currently you have to manually create a curryable builder function.

**Comment by Alxandr** [comment]
Can't we just get Record constructors that are curried? In which case you'd get this for free. This would also make it a lot easier to translate code from haskell which has this.

```fsharp
type Person = {
  age: int
  name: string }

// way's to construct
let p1 = { age = 2, name = "p" }
let p2 = Person 2 "p" // <- order has to be same as record name order in definition
let mkTodler = Person 2 // <- normal F# partial application
let p3 = mkTodler "p"
```

**Comment by cartermp** [comment]
@Alxandr I think that's a very good approach.  No idea how much work that would be implementation-wise, but I think it's an elegant solution.

**Comment by Alxandr** [comment]
It should just be (as you already stated) the compiler pretending that there is a function defined as

```fsharp
Person : int -> string -> Person
```

i would think?

**Comment by Alxandr** [comment]
And also, to not break compatibility, precedence should be given to any other function that already exist with the same name.

**Comment by gentauro** [comment]
> And also, to not break compatibility, precedence should be given to any other function that already exist with the same name.

@Alxandr I don't think your approach would break any code as defining a function with Pascal-case is _*bad practice*_ ... I only showed it as an example that F# actually would be able to do it.

But I really like your approach, it might be easier to get into F# :+1:

**Comment by Alxandr** [comment]
@gentauro I agree, but just because it's bad practice doesn't mean nobody's ever done it. So I just added this clause so that you guarantee backwards compatibility.

**Comment by gentauro** [comment]
Would this approach actually help `TypeProviders` to generate idiomatic `Records` instead of current .NET `Objects`? /cc @tpetricek?

**Comment by dsyme** [comment]
Thanks for the suggestion

Quite a lot of things speak against this from the language design perspective

* Introducing currying implicitly is not done elsewhere in the F# language design

* I don't see us introducing order-dependence in the record construction process at this stage in the F# language design.  In the examples shown, the last field is the last one to be filled in.  What if that were the first field?  

* Simply writing the construction function keeps things simple, clear and understandable

I'll close this issue as I don't see us doing this suggestion in its current form.  Please feel free to reopen or resubmit with more info.

Thanks
Don

**Comment by Alxandr** [comment]
> Introducing currying implicitly is not done elsewhere in the F# language design

I don't see this as "introducing currying implicitly". Currying is the default for functions in F#, and you have to be explicit if you want things not to be curried, with the only exception to this being constructors (which I always found sort of annoying, but that's another issue). Records on the other hand has no constructors (that you can call from F# anyhow). So I don't feel this is non-idiomatic at all. In fact I feel the opposite as it would allow you to use records in common patterns such as:

```fsharp
type Person = { age: int option; name: string }
let people =
  ["Foo"; "Bar"]
  |> List.map (Person None)
```

> I don't see us introducing order-dependence in the record construction process at this stage in the F# language design. In the examples shown, the last field is the last one to be filled in. What if that were the first field?

This is definitely a valid argument. The arguments in a record doesn't have order, and for all I know people could have written linters and whatnot that makes people order them alphabetically or whatnot because the order doesn't matter. That being said, it's still perfectly valid to construct record instances using the record syntax (which is order independent). As for "What if that were the first field?", that's (in my head) basically the same as asking "What if `List.map` took the list as the first argument?" The function is designed in such a way that the argument we want to leave out (for later) is the last one. If it's not, we either have a weird case (and use something like `swap` or similar), or we have wrongly designed the function/record. Do you expect to be able to pass arguments in any order to a function? No. Then why should you expect that for a function that constructs a record? Sure, the record syntax allows for that, but if that's your goal, stick with the record syntax. If you need currying then make sure the arguments are in the right order.

> Simply writing the construction function keeps things simple, clear and understandable

I'm not entirely sure I understand this statement as it's somewhat ambiguous to me. Do you mean create an explicit constructor on the record? Or do you mean do the following:

```fsharp
type Person = { age: int option; name: string }
let Person age name = { age = age; name = name }
```

Cause as this discussion started with, creating a function named ´Person` is very non-idiomatic.

**Comment by isaacabraham** [comment]
Just my two cents... there is a precent in F# for things being order-specific in a couple of places that spring to mind. First is type providers which often do exactly this i.e. create constructors for classes based on external data source, the ctor args being generated based on some arbitrary order. The second (AFAIK) is when type inference kicks in, if you have two records with a similar structure, doesn't it "select" one based on order of fields on the record?

**Comment by gentauro** [comment]
> I don't see us introducing order-dependence in the record construction process at this stage in the F# language design. In the examples shown, the last field is the last one to be filled in. What if that were the first field?

I think this is a really good point, but it has nothing to do with `currying`. As it is with curried functions, order-precedence is determined in advance. Example:
```
let foo : int -> string  = fun a b -> (string a) + b 
```
It's not possible to provide `b` before `a`. I'm guessing that's the hole point of this approach (lazy evaluate the function based on the arguments instead of writing):
```
let foo : int * string  = fun (a,b) -> (string a) + b 
```

That said, it would be ideal if we could instantiate a `record` with partially data as we do when modify them:
```
type FooBar = { foo: int; bar; float }

let partiallyfb1 = { FooBar.bar = 42. }
let partiallyfb2 = { partiallyfb1 | foo = 42 }
```

But I don't see how this possible to implement (default the other values?).

Therefore, if the suggested idea, mostly @Alxandr approach, is not complying with the overall F# design, then I will withdraw the idea. No probs.

**Comment by dsyme** [comment]
@gentauro why not this?

```fsharp
type FooBar = { foo: int; bar; float }

let partiallyfb1 foo = { bar = 42.0; foo = foo }
let partiallyfb2 = partiallyfb1 42
```

You don't get record syntax at usage points but it's easy enough to follow isn't it?

**Comment by Alxandr** [comment]
Cause you have to explicitly define it, not to mention name it. Though in response to @gentauro's suggestion, I agree that's fine, but not as a solution to this suggestion in general.

On of the pain points of F# (in my opinion) is that I tend to do the following whenever I create a new record type:

```fsharp
type Person {
  age: int
  name: string
}

module Person =
  let create age name = { age = age; name = name }
  let age p = p.age
  let name p = p.name
```

which is just a bunch of boilerplate.

**Comment by dsyme** [comment]
@Alxandr #506 would cover two of those. 

In F# the auto-generation of ``create`` just doesn't feel right, sicne the naming of the record fields is lost and the order matters so much.  It feels it would be more natural to allow the use of named arguments:

    Person(age=1,name="a") // named arguments
    Person(1, "a") // unnamed arguments

where order is relevant but at least naming is optional

**Comment by Alxandr** [comment]
What does named arguments constructor give you over the record syntax though? The point here is mostly to be able to partially apply the constructor (as in, don't feed it a tuple).

**Comment by dsyme** [comment]
> What does named arguments constructor give you over the record syntax though? 

Not much, though it would fit give first-class use

     initialValues |> List.map Person

But this comes at the very significant cost of making usage sites depend on the order of declaration of record fields (though as @isaacabraham says this is also revealed by C# interop)

> The point here is mostly to be able to partially apply the constructor (as in, don't feed it a tuple).

My feeling is that if you want to make the the order of fields significant in regular F# code (no type providers, no interop) then you should declare that explicitly, e.g. via an explicit construction function.

**Comment by Alxandr** [comment]
Can we make an attribute that enables this maybe? So it's explicit without lots of boilerplate? Take my example above for instance:

```fsharp
[<AutoMagicAttribute>]
type Person {
  age: int
  name: string
}

// I get all of this for free pls :P
module Person =
  let create age name = { age = age; name = name }
  let age p = p.age
  let name p = p.name
```

**Comment by dsyme** [comment]
@Alxandr You can always add the suggestion, but I don't think we'd do that. #506 is much more likely though.  The ``create`` method is just too simple to write to make a magic macro-like attribute

**Comment by gentauro** [comment]
Please don't introduce _**what everybody hates about records in Haskell**_ (#506) :-1: 

This will actually be so annoyin once you realize that if a `record` defines `foo` it can't be re-used anywhere else:

```fsharp
type fooBar = { foo: int; bar: float }

 (* Compile error as "foo" is already defined *)
type bazQuxFoo = { baz: string; qux: char; foo: int; }
```

and it will tend to the annoying `Haskell` `records` _**Hungarian notation**_:

```fsharp
type fooBar = { foo: int; bar: float }

type bazQuxFoo = { baz: string; qux: char; bazQuxFooFoo: int; }
```

**Comment by dsyme** [comment]
@gentauro #506 should not lead to that since the resolution of the notation is type directed (``(.P)`` is shorthand for ``fun x -> x.P``).

So 

    fooBars |> List.map (.P)
    bazQuxFoos |> List.map (.P)

would both work.  Further under that proposal you could create generic code by using line, e.g.

    let inline getPs xs = xs |> List.map (.P)

would work for list of any type with a property P

**Comment by Alxandr** [comment]
@gentauro you obviously did not read my example. It does not create functions in public scope, but in a module named the same as the class. The problem with just doing `.foo`, is that you end up with the same type resolution problems you already have with doing `fun foo x = x.foo`, in which it doesn't necessarily pick the right `.foo`. Unless you inline it ofcause.

**Comment by dsyme** [comment]
> Unless you inline it of cause.

Or you give a type annotation on ``x`` - which is really the normal thing in F# code

**Comment by Alxandr** [comment]
@dsyme I meant with the suggested `.foo` syntax. For instance, you couldn't do `let processThings = List.map .P` I'd guess, because of lack of type information. This is (one of) the reason I tend to create `Person.name` type of functions. The type is explicit*, but I don't need any parenthesises or similar to type it.
