### ISSUE TITLE
Allow for incomplete pattern matches in function definitions

### ISSUE THREAD

**Issue by robkuz** [fsharp/fslang-suggestions#540]
# Allow for incomplete pattern matches in function definitions

Allow for incomplete pattern matches when using `function` as a pattern matcher 

This could be very helpful for creating smart constructors on product types where only a subset of all possible values should be allowed but that restriction can not be expressed via the F# type system.
See the example

```fsharp
    type Country =
        | DE
        | AT
        | CH
        | UK

    type Currency = 
        | EUR
        | SFR
        | GBP

    type CC = Country * Currency
    let mkCurrencyCountry x y : CC =
        [<CompletePatternMatch>]
        function
        | DE, EUR -> DE, EUR
        | UK, GBP -> UK, GBP
        | AT, EUR -> AT, EUR
        | CH, SFR -> CH, SFR

    let willCompileFine = mkCurrencyCountry DE EUR
    //the line below will create a compile time error NOT a Runtime error
    let willCompileTimeErr = mkCurrencyCountry DE GBP
    // compile time error would be "parameter combination: 'DE' 'GBP' is not allowed"
```
The existing way of approaching this problem in F# is to fall back on a class based approach. However this is extremly noisy and requires constant up and down casts.

## Pros and Cons 

The advantages of making this adjustment to F# are smart constructors that are very well within the realm of F# functional approach and also syntactically pleasing

The disadvantages of making this adjustment to F# are lots of code or runtime checks 

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): S - there is no breaking change as far as I can see. The type checker / 
inferrer would need to check for this.

Related suggestions: See also this [discussion on SO](http://stackoverflow.com/questions/42270329/is-there-a-way-to-restrict-the-instances-of-a-possible-product-type) on how this is solved in Haskell

Maybe this could be generalised for all pattern matching?

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by smoothdeveloper** [comment]
@robkuz I like the overall intent (more static checks, expressing more with existing types/constructs) but I'm not clear about the semantics:

* Is it going to add runtime check when not using literals but variables?
* what is the outcome of failed runtime check?

If we put aside the compile time check (which can only apply when literals are used AFAIU) how is that approach beneficial versus having `mkCurrencyCountry ` return `CC option` and code at call site handling the `None` case?

Can you do some enhancements to the proposal:

* actual compile time error message
* show a case where it is runtime exception occuring, with the message
* put the markdown code block as fsharp formatting
* fix the checkboxes

**Comment by robkuz** [comment]
Why would this work only with literals? If it really only worked with literals than we can scrap the proposal. The idea is that the type checker does a non-exhaustive check in terms of the defined pattern and yields a compile time error at the call site if the combination of actual param values is not covered by that pattern match

**Comment by gmpl** [comment]
@robkuz Values can't be checked at compile time.
For example:

    let result =
      mkCurrencyCountry (parseCountry (getCountryFromInput())) (parseCurrency (getCurrFromInput()))

How can the compiler know in advance what the user will type?

Types can be checked at compile time, but since F# has no dependent types you will have to use hacks with overloading and static constraints to make it work.

**Comment by robkuz** [comment]
hmm, I see. Than this wont work
