### ISSUE TITLE
Allow application in combination with dynamic (?) operator

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/fslang-suggestions#543]
I propose we improve dynamic programming with F#. In Fable, we're almost there with the use of three operators:

- `?` dynamic operator, defined in standard F# but implemented by Fable
- `!!` dynamic casting, defined by Fable and equivalent to `unbox<'t>`
- `$` operator to apply arguments directly to an `obj` type.

With these operators you can do something like this:

```fsharp
let result: string = myObject?foo$(4, 5, 6)

// JS: var result = myObject.foo(4, 5 6)
```

> Note that Fable deconstructs the tuple literal into multiple arguments

However, the `$` operator has problems. Besides not being very nice, the precedence rules don't let you do something like `myObject?foo?bar$(4, 5, 6)`.

Fable is solving this at the moment by implementing `?` with the following signature: `obj->string->(obj->obj). This means the user can now do something like this:

```fsharp
let result: string = !!myObject?foo?bar(4, 5, 6)
```

This is very close to a dynamic experience and makes it very easy to temporarily cancel type checking when the user needs to interact with untyped code. However this _hack_ is still no ideal, there are two main problems.

- When doing `let x = myObject?foo`, users expect `x` to be of type `obj`, not `obj->obj`.
- The F# compiler creates unnecessary closures that Fable needs to track and eliminate.

It would be very useful if the F# compiler allowed directly the application of any number of arguments in combination with the `?` operator without the Fable hack. This would be similar to the currently available combination of `?` and assignment.

```fsharp
let (?<-) (o: obj) (v: obj): unit = ...

myObj?foo <- 5
```

Probably a similar syntax should be used, but I'm not sure how it should be:

```fsharp
let (?()) (o: obj) ([<ParamArray>] args: arg[]): unit = ...

myObj?foo(1, 2)
```

- **Pros**: It'd be much easier to cancel type checking in Fable if necessary
- **Cons**: Dynamic programming is always risky, but libraries will still have to implement the `?` on their own, so the risk is mitigated for _standard_ code
- **Estimated cost**: M-L 

## Affadavit (must be submitted)

* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by Rickasaurus** [comment]
I wouldn't mind having something like this kicking around, but I'd rather it wasn't in my namespace by default and would require you to open a module first.

**Comment by alfonsogarciacaro** [comment]
@Rickasaurus Absolutely! Maybe I was not clear in the description, but this is not proposing that `?` should be included in the FSharp.Core. `?` will remain unimplemented as it's now, but (if the suggestion is accepted) it will be possible for libraries to implement `?` + application (the same way it's possible to implement `?` + assignment right now).

For example, right now the `?` operator for Fable is defined in the `Fable.Core.JsInterop` module and you need to open it explicitly in order to access it.

**Comment by alfonsogarciacaro** [comment]
@dsyme The current workaround seems to be working well and I didn't get any feedback from users on this regard for years, so if it's not needed for anything else, we can close the suggestion. Thanks a lot for reviewing!
