### ISSUE TITLE
List literals (allow overloading the [] operator)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/fslang-suggestions#544]
Sometimes is useful to use the list syntax without producing a real list, e.g., when passing a list of options to a method in another language. In JS options are usually defined with an untyped plain JS object. Typescript can provide some type checking and autocompletion in these cases by using structural interfaces. But because it would be complicated to add both structural interfaces and dynamic object creation to F#, Fable solves this problem with the so-called [`KeyValueList` unions](http://fable.io/docs/interacting.html#KeyValueList-attribute). This allows for a nice syntax when interacting with a library like React:

```fsharp
    view [ Styles.sceneBackground ]
        [ text [ Styles.defaultText ] model.LocationCheckRequest.Name
          textInput [
            TextInput.TextInputProperties.AutoCorrect false
            TextInput.TextInputProperties.Style [
                FlexStyle.MarginTop 2.
                FlexStyle.MarginBottom 2.
                TextStyle.Color Styles.textColor
                ViewStyle.BackgroundColor Styles.inputBackgroundColor
              ]
            TextInput.TextInputProperties.OnChangeText (Model.LocationStatus.Alarm >> LocationCheckMsg.LocationStatusUpdated >> LocationCheckMsg >> dispatch)
          ] ""
```
> From [fable-react_native-demo](https://github.com/fable-compiler/fable-react_native-demo/blob/142d5daf24466ac45e0654fb7061dc400545a209/src/Scenes/CheckLocation.fs#L102-L125)

The main problem with this is users may build such a list (which Fable converts to a JS object) and then try to use it with any operator or function that accepts a list (like `::`, `@` or `List.map`) causing a runtime error.

I'm not sure how we could achieve this effect properly in F#, but maybe a possibility is allow overloading the `[]` operator for specific types:

```fsharp
type ITransformedOptions =
    interface end

type MyOptions =
    | OptionA of string
    | OptionB of int
    static member ([]) ([<ParamArray>] els: MyOptions array): ITransformedOptions = ...

let myOpts = [ OptionA "foo"; OptionB 5 ]
```

Note in this case `myOpts` would be of type `ITransformedOptions`, not `MyOptions list` so users cannot apply list transformation to it.

It would also be very nice if the F# compiler would produce an array literal in the typed AST instead of nested list constructors (that's the reason for `ParamArray` in the signature above).

The alternative approach would be to create the actual list and then do the conversion to a JS object in runtime with an intermediate method, but this would add a considerable overhead and prevent some AOT optimizations in React Native.

Another alternative would be to use a method/constructor with `ParamArray` arguments. Besides being less concise, the main problem is it requires double parens when combined with a curried function which is not very intuitive: `view (opts(optionA, optionB)) children`.

- **Pros**: The nice F# syntax for lists can be used for special cases without runtime overhead.

- **Cons**: It won't be possible to create standard lists of `MyOptions`, but this may be desirable.

- **Estimated cost**: M-L

## Affadavit (must be submitted)

* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#. 

* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by gmpl** [comment]
I think this will be quite complicated to implement in a nice way in the current F# compiler, mainly because ``[]`` is not an operator.

However I think an easier way to have a similar mechanism with something that fits better in the current F# spec is to extend the concept of custom literals.

Currently it's possible to define custom number literals by writing a module named ``NumericLiteralX`` where ``X`` will be the letter used after the number.

At the same time it's possible to write byte arrays using string literals like this:

    "Hello world"B
    // val it : byte [] = [|72uy; 101uy; 108uy; 108uy; 111uy; 32uy; 119uy; 111uy; 114uy; 108uy; 100uy|]

But what if these two features instead of being isolated syntax helpers become first class citizen of a compiler feature that allows to extend Numeric, String and, why not, List and Array literals as well?

**Comment by alfonsogarciacaro** [comment]
@gmpl Yes, you're right. The idea of the _operator_ came to my head when I was half writing the issue but I should have made it clear it's an abstraction over the bracket syntax.

I think your proposal makes sense if it makes the implementation in the F# compiler easier, but I'm concerned whether this would require to add a suffix to the list literal, which may hinder the desired effect of having a nice syntax for this particular case (and break existing Fable projects).

**Comment by gmpl** [comment]
@alfonsogarciacaro Yes, it will require a suffix.
I'm not familiar with Fable, but it seems to me that it will not break the existing code, worst case it will not take advantage of this optimization if the suffix is not used.

**Comment by alfonsogarciacaro** [comment]
@gmpl Unfortunately it would break existing code, as the point of this suggestion is to use the `[]` syntax to produce something else different than a list. Also, if the user is forced to use a suffix the syntax won't be much different to say, using a prefix operator, and then it would be much easier to explore that way instead of introducing changes into the F# compiler (if only prefix operators weren't so restricted).

**Comment by gmpl** [comment]
@alfonsogarciacaro Well another thing I have in mind long time ago, also related to custom literals, is a mechanism that allows you to "switch" the default module, I mean, the one that doesn't use the suffix.

This will allow us to write code for generic numbers without too much additional noise, today you need to add a suffix and/or use GenericZero/One. 

I have to find the time to work on the proposal, but it seems it will also address this suggestion for list literals.

**Comment by rmunn** [comment]
Another possible benefit to having alternate, customizable list-like literals would be to have nice syntax for creating instances of other data structures, like `PersistentVector` from FSharpx.Collections. Though that's really a very tiny benefit, because you can do this *right now* with no changes to F# syntax:

```fsharp
open FSharpx.Collections
let vec = PersistentVector.ofArray
// ... Then later on ...
let myVector = vec [| 1; 2; 3; 4 |]
```

So switching that to `let myVector = [ 1; 2; 3; 4 ]V` is barely a win at all from a readability standpoint. Really, I'd consider it a loss. So while the idea is cool, I don't see much benefit of it outside the Fable context.

Still, the idea of being able to write custom literals for types other than lists is intriguing, and maybe there's a big win there that I just haven't seen yet. Dicts? Trees? Queues?

**Comment by alfonsogarciacaro** [comment]
After thinking more deeply about this, there may be other ways to deal with the performance issue in Fable using inlining instead of requiring a big modification in the F# compiler. So I'm closing this for now to focus in other Fable-related suggestions.
