### ISSUE TITLE
Allow implementing the same interface at different generic instantiations in the same type [ RFC FS-1031 ]

### ISSUE THREAD

**Issue by 0x53A** [fsharp/fslang-suggestions#545]
Note: this is a duplicate, but the original proposal was reduced down to only enable inheritance of such types, not implementation in F#.
I would like to ask you to reconsider fully implementing this feature.

# Allow implementing the same interface at different generic instantiations in the same type

__I propose we ...__

Allow to implement the same interface multiple times with different generic instantiations.

E.g.

```F#
type I<'T> =
    abstract member M : unit -> 'T

type T() =
    interface I<int> with
        member x.M = 1
    interface I<bool> with
        member x.M = true
```

__The existing way of approaching this problem in F# is ...__

The existing workaround is to create one extra level of inheritance per instantiation.

## Pros and Cons 

__The advantages of making this adjustment to F# are ...__

Feature parity with C#.

Reduce surprise for new developers.

Remove boilerplate inheritance chains caused by the workaround.

__The disadvantages of making this adjustment to F# are ...__

Quoting from UV:

> [...] This is partly because of the way interface implementation methods are named in compiled IL (only the prefix "I" is added), and partly because the equivalent object expression form can inculde type unknowns, e.g.
> 
> { interface I<_> with ... 
> interface I<_> with ...
> 
> and we don't want to support this kind of inference, and equally don't want a non-orthogonality between object expressions and class definitions. [...]

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): _As this contains changes to code generation and type inference, this is probably __M-L__, but I am not familiar enough with the code base._

Related suggestions:

Original SO: http://stackoverflow.com/questions/1464109/implementing-the-same-interface-at-different-generic-instantiations
Original UV: https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663504
Original PR: https://github.com/Microsoft/visualfsharp/pull/18

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [ x ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [  ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate (_It __is__ a duplicate of the original suggestion_)
* [  x ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it. _(As I understand it, the previous decision was more for technical reasons, e.g. the naming of interface methods)_

Please tick all that apply:
* [ x ] This is not a breaking change to the F# language design
* [ x ] I would be willing to help implement and/or test this _(Willing yes, capable of implementation probably not. I would love to give it a try If you would be willing to hold my hand)_
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
@0x53A I agree this should be done, as long as the disadvantages tracked above are taken into account int the implementation

**Comment by 0x53A** [comment]
@dsyme when looking at how C# implements this, I noticed that apparently, Methods don't need to be named uniquely in IL:

![image](https://cloud.githubusercontent.com/assets/4236651/25072429/40a1c484-22ce-11e7-8467-96f0fa76208f.png)

![image](https://cloud.githubusercontent.com/assets/4236651/25072434/502ec3fc-22ce-11e7-9604-ab07464ea75e.png)

![image](https://cloud.githubusercontent.com/assets/4236651/25072437/574ccb02-22ce-11e7-96cd-39493f7d98e0.png)

ClassLibrary that is imported with alias=al

```C#

namespace Namespace
{
    public class Class
    {
    }
}

```

Console App:

```C#
extern alias al;

namespace Namespace
{
    public class Class
    {
    }
}


namespace ConsoleApp1
{
    public interface IA<T>
    {
        object Get();
    }

    public class MyClass : IA<int>, IA<string>, IA<al.Namespace.Class>, IA<global::Namespace.Class>
    {
        object IA<int>.Get()
        {
            return 1;
        }

        object IA<string>.Get()
        {
            return 2;
        }

        object IA<global::Namespace.Class>.Get()
        {
            return 3;
        }

        object IA<al.Namespace.Class>.Get()
        {
            return 4;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var x = new MyClass();
            System.Console.WriteLine((x as IA<al.Namespace.Class>).Get());
            System.Console.WriteLine((x as IA<global::Namespace.Class>).Get());
            System.Console.ReadLine();
        }
    }
}
```

So unless fsc itself has issues with duplicated names, it may be as easy as just removing the check.

I will try to create a prototype over the next few days / weeks / months / years =)

**Comment by 0x53A** [comment]
RFC: [under discussion](https://github.com/fsharp/FSharpLangDesign/issues/185)
prototype: [In progress](https://github.com/Microsoft/visualfsharp/pull/2867)

**Comment by MarkNicholls** [comment]
I have a wish to do this (which isnt allowed in C# due to the possibility of unification).

```
type IOr<'a,'b> = 
    abstract member Else<'c> : ('a -> 'c) -> ('b -> 'c) -> 'c

type IOr<'a,'b,'c> = 
    inherit IOr<'a,IOr<'b,'c>>
    inherit IOr<'b,IOr<'a,'c>>

```

**Comment by cartermp** [comment]
@MarkNicholls No, that is not possible in F# for the same reason.

**Comment by MarkNicholls** [comment]
@cartermp 

sorry, let me make it a bit more concrete.

C# allows this

`    interface IFoo : IEnumerable<int>, IEnumerable<string> { }
`
and F# doesnt....which shouldnt in theory be an issue (I'd hope).

C# doesnt allow this

`    interface IFoo2<A, B> : IEnumerable<A>, IEnumerable<B> { }
`

it complains

`Error	CS0695	'IFoo<A, B>' cannot implement both 'IEnumerable<A>' and 'IEnumerable<B>' because they may unify for some type parameter substitutions
`
I'm asking whether the scope of this suggestion covers the latter.
My preference is that it does, but that it rejects 

interface IBar : IFoo2<int,int> {}

i.e. it kicks the can down the road to the point where the type is constructed.

**Comment by cartermp** [comment]
`IEnumerable` is a tricky one since the rules for interface implementations are a bit difference, and you'd need to do this:

```fsharp
open System.Collections
open System.Collections.Generic

type C() =
    interface IEnumerable<int> with
        member this.GetEnumerator(): IEnumerator<int> = 
            raise (System.NotImplementedException())

    interface IEnumerable<string> with
        member this.GetEnumerator(): IEnumerator<string> = 
            raise (System.NotImplementedException())

    interface IEnumerable with
        member this.GetEnumerator() : IEnumerator =
            failwith "yeet"
```

So that shouldn't be an issue.

The example you provided previously will not work for the same reasons it doesn't work in C#. The error is:

![Uploading image.png…]()

**Comment by MarkNicholls** [comment]
Ok,

IEnumerable<> was just a convenient example of inheriting an interface...I don't actually want to do it.

So the bottom line is the scope of this doesnt extend to my latter example, hmmmm....should I open a suggestion to include that? or is that premature?

**Comment by cartermp** [comment]
I suppose it's worth adding a new suggestion.

**Comment by cartermp** [comment]
Closing out as completed for F# 5.
