### ISSUE TITLE
Remove need for brackets and comma in type definition and type specification

### ISSUE THREAD

**Issue by wallymathieu** [fsharp/fslang-suggestions#548]
[ edited by @dsyme ]

# Type parameters without the need for brackets and comma 

I propose we remove the need for brackets and comma in type definition and type specification.

For instance being able to write something like
```
type 'a 'b generic1 when 'a : equality = {
    Foo : 'a
    Bar : 'b
}

let x1 : string int generic1 = { Foo = "a"; Bar = 1 }
```

The existing way of approaching this problem in F# is:

```
type Generic1<'a, 'b when 'a : equality> = {
    Foo : 'a
    Bar : 'b
}

let x2 : Generic1<string, int> = { Foo = "a"; Bar = 1 }
```

I've reused the examples from https://github.com/fsharp/fslang-suggestions/issues/523#issuecomment-269015566

## Pros and Cons 

The advantages of making this adjustment to F# are that it would have a certain beauty and simplicity to it.

The disadvantages of making this adjustment to F# are that it might complicate the f# parser in a way that might be disadvantageous. I'm not familiar enough with the parser to know if this might be a really bad idea. Could a syntax change like this cause breaking changes? 

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [X] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by matthid** [comment]
I know a lot of people are feeling differently, but I generally like putting the generic parameters in front of the type. Therefore I support this even though I don't think the current way with comma is too bad :).

**Comment by dsyme** [comment]
@matthid I've removed this as one of the existing ways to do this, since it is deprecated in the F# syntax

```
type ('a, 'b) generic1 when 'a : equality = ...
```

I don't know why we would add another way of doing this: since F# 1.x we have preferred ``GenericType<t1,t2>``. Also your declaration syntax is now inconsistent with the use-site syntax

**Comment by dsyme** [comment]
Closing per the README.md - we considered this in F# 1.0 and decided against it.

> In general things in categories 1 and 2 won't be reconsidered unless there is a really very strong case, e.g. because of a change in circumstance. Many suggestions will thus be closed with responses like "we considered this in F# 2.0 and decided against this". The design notes for F# 2.0-3.0 are only available in email form, we will gradually try to make them available from our archives.

**Comment by wallymathieu** [comment]
Thanks! Is there a good f# style guide you prefer?
