### ISSUE TITLE
Warn when an auto-property getter is confused with a default value

### ISSUE THREAD

**Issue by TMVector** [fsharp/fslang-suggestions#549]
I propose the compiler should produce a warning when it is likely the programmer has confused the inline getter syntax for setting the intial value.

For example, consider the following class:

``` f#
type TestType() =
  // Syntax of fields and immutable auto-properties:
  let field1 = 0
  member this.prop1 = 0 // Different behaviour to `let`
  member val prop2 = 0 // This acheives the same effect as `let` but for a property

  // This difference only really matters when the property type has mutable state:
  member this.dict2 = new Dictionary<int,string>() // Returns new instance every use
  member val dict = new Dictionary<int,string>() // Initialises property, as intended
```
An unexperienced fsharper (*like me*) could very easily confuse `member _` with `member val _`, and the result will be very confusing behaviour. When the programmer attempts to add an entry to dict2, they will be frustrated to find nothing works.

I think the easiest/cleanest solution is for the compiler to issue a warning when this syntax is used, and the getter body is an object creation expression not of record or tuple type.
``` f#
type Type1() =
  member this.dict = new Dictionary<int,string>() // WARN
  member this.dict2 = Dictionary<int,string>() // WARN
```

I tentatively propose the following warning message:
``` text
  member this.dict = new Dictionary<int,string>()
--^^^^^^^^^^^^^^^^
warning:
  Did you mean to provide a getter for 'dict'? This will return a new instance each use.
  If you are trying to initialise a property, use 'member val dict = ...' instead.
```

## Pros and Cons 

The advantages of making this adjustment to F# are:
* Friendlier for people learning F# (and experienced people potentially making a mistake)

The disadvantages of making this adjustment to F# are:
* More warnings

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): S?

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
I think the place for this is FSHarpLint.  FSharpLint warnings are active by default in editors such as VSCode/Ionide so have a strong affect on the usage of the langugae
