### ISSUE TITLE
Allow basic integer numeric type names in a for loop (from Ada 2012)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#55]
# Allow basic integer numeric type names in a for loop (from Ada 2012) [12564057] #

**Submitted by Alexei Odeychuk on 3/2/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

I suggest using basic integer numeric type names (namely, sbyte, byte, int16, uint16, int (int32), uint32, int64, uint64) in a for loop meaning to try every value of the type (from Ada 2012).
For example,
let ourSequence = seq { for i in int -> i } // ourSequence : seq<int>
let ourList = [ for i in byte -> i ] // ourList : byte list
for i in sbyte do printf "%A" i
I think it's a good idea to allow basic integer numeric type names in for loops just as in Ada 2012 and treat such types by the F# compiler as types compatible with IEnumerable and having a GetEnumerator method (even if they don't). It will make the F# syntax more expressive and bolster F# competitive strengths in writing clear and concise code.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12564057)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12564057-allow-basic-integer-numeric-type-names-in-a-for-l.md#comments)

**Comment by dzmitry-lahoda** [comment]
Now I can do next:
```
let ourSequence = seq { for i in 0 .. Int32.MaxValue -> i } // ourSequence : seq
let ourList = [ for i in 0uy .. Byte.MaxValue -> i ] // ourList : byte list
for i in 0y .. SByte.MaxValue do printf "%A" i   
```
I could put `n .. max` into other `seq` or `array` builder, I hope. And give them nice names `int32.range` or `byte.rang` or `sbyte.range`, I hope extensions could that.  And get same performance as manual typing. If will not get same performance, than kind of such possibility in similar situations could make sense or some language mechanics to allow write such things in default performance should be possible.

Meanwhile, I found (inconsistency?):
```
        for i = 0L to index do
          e.MoveNext()
        for i in 0L .. index do 
          e.MoveNext()
```
One of these lines fails to compile with
```
This expression was expected to have type
    'int'    
but here has type
    'int64'
val index : int64
```
What line is it?

**Comment by abelbraaksma** [comment]
> What line is it?

Didn't the compiler tell you? But from the docs it's clear, the `to` syntax requires 32 bit integers. You didn't show the declaration of `index`, but I assume it's declared as `int64`. 

Generally it's better to file a bug on its own in the visualfsharp repro, instead of ik the language suggestions repro, and to include all code that is needed to reproduce the bug. That said, I don't think there is a bug.
