### ISSUE TITLE
List's exists2 inconsistent with Seq's exists2

### ISSUE THREAD

**Issue by eacasanovaspedre** [fsharp/fslang-suggestions#550]
## Description
I propose we change the behavior of List.exists2 to be consistent with Seq.exists2 because:

The expected outcome of List.exists2 when the two lists supplied are not the same length is not consistent with the Seq's exists2 version. It is also not consistent with the [documentation](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.exists2%5b't1,'t2%5d-function-%5bfsharp%5d). For example:

`> List.exists2 (fun a b -> false) [1;2] [3];;`
Produces:
`System.ArgumentException: The lists had different lengths.
Parameter name: list2`

And
`> Seq.exists2 (fun a b -> false) [1;2] [3];;`
Produces:
`val it : bool = false`

In F# interactive as well as in compiled assemblies.

The expected and most useful behavior is that when reached the end of either of the two lists the value returned should be false since it would be consistent with sequences, it avoid the ugly exception handling or checking beforehand if the lists are the same length. It's also more intuitive.
`> List.exists2 (fun a b -> false) [1;2] [3];;`
Should return `val it : bool = false`

In the code, the function that does this is the following:
`let rec exists2aux (f:OptimizedClosures.FSharpFunc<_,_,_>) list1 list2 =`
`            match list1,list2 with `
`            | [],[] -> false`
`            | h1::t1, h2::t2 ->f.Invoke(h1,h2)  || exists2aux f t1 t2`
**`            | _ -> invalidArg "list2" (SR.GetString(SR.listsHadDifferentLengths))`**

It is explicitly done, so it seem like there was a time when that was the desired behavior, maybe it is still so. If that's the case it is still inconsistent from my point of view.
It could be easily fixed also.

## Pros and Cons 

The advantages of making this adjustment to F# are ...
1- Consistency
2- Simpler and more intuitive usage
3- In case it does not meet the disadvantage 1 it is compatible
The disadvantages of making this adjustment to F# are ...
1- Maybe some code that relies on catching an exception in case the two lists have different length might brake. Which is in most cases a bad code already and I think it should not be common. 

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): XS or S

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Edit:**
It's the same with List.forall2 and maybe the other List.xxx2 functions. I'm now wondering if there is some clear explanation that I missed at some point.

**Comment by gmpl** [comment]
I think this inconsistency between List and Seq is consistently inconsistent between all 2s functions, also ``zip``. But I agree it would be nice to use the 'use shorter' criteria, instead of throwing exceptions.

**Comment by dsyme** [comment]
This is a design decision we made in F# 2.x and I think we need to stick with it at this point.
