### ISSUE TITLE
Type Provider Parameter (String) Colorization

### ISSUE THREAD

**Issue by matthid** [fsharp/fslang-suggestions#556]
I propose that the type provider API has some way of telling the compiler how to colorize the static parameter string. This information can be delegated to the IDE in some way.

The existing way of approaching this problem in F# is: Strings look like strings, even if they are SQL Statements, Regexes or other data.

## Pros and Cons 

The advantages of making this adjustment to F# is a way for type providers to tell the compiler something about the structure of the strings and use if from the IDE colorization.

The disadvantages of making this adjustment to F# is that it might be quite complex to capture this information, considering the wide range of different type providers.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): L / XL (guessing)

Related suggestions: did not found anything.

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Not sure about the last point

Please tick all that apply:
* [x] This is not a breaking change to the F# language design (I think)
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

Not sure if I'm able to contribute, but I was just curious what people think.

**Comment by cartermp** [comment]
This seems like an issue to have on VisualFSharp since it's tooling-related.  Would you mind creating any issue there as well?  I'll defer to @dsyme on if this should be closed.

**Comment by matthid** [comment]
@cartermp I kind of agree that this could be improved in the tooling as well. But this issue is really about considering if this could be added to the language itself:
Like having a new API where the TP can tell the compiler some additional information about the structure of its static parameters (especially strings obviously). This information can then flow right into the IDEs.
Obviously this means TP implementations would have to use this API and IDEs would have to implement it.

**Comment by cartermp** [comment]
Ah, so you're looking for a specific API on Type Providers themselves?  AFAIK we could accomplish all of this with FCS changes, though I'm not sure if the _best_ place is in FCS or as an API on TPs themselves.

**Comment by matthid** [comment]
Yes: The problem is that we have lots nice and useful TPs but they kind of look still alien to the language.
So they give you an exact error location if you fail to provide a valid parameter but they look like a regular string.

IMHO we could either tackle this one by one in the IDE by adding support for the most used TPs or find a general solution to the problem (where TP implementation can hook into if they want). This issue is about thinking how a general solution COULD look like (because sadly I have no idea).

We "might" be able to use FCS as kind of a playground but the problem is that all TPs we update will probably not work with the `real` compiler afterwards...

I think we first need to figure out `if` this is possible and `if yes` how a solution could look like...

**Comment by cloudRoutine** [comment]
@matthid the first thing that comes to mind is setting it up to work as a special case of semantic colorization that accepts a `tokenize` function that maps a string to set a list of `range * FSharpSemanticClassification`(might be the wrong type name) and during the get semantic colorization call it applies this alternative match across the range of the TP parameter string.

Possibly the at TP type could have a `[<Tokenizer>]` or some other attribute applied to a member function so the language service knows what function to use if a TP has been loaded.

I don't have any good ideas on how to work the `FSharpGlyph` colors into it as well, but if the special colorization were based around mapping those constructs to the set of constructs you want colorized in the string then we could probably enable this feature in any editor/IDE that uses the language service to get its colors.

(btw these are the new FCS features I've been trying to update FSharp.Formatting to use)

**Comment by nikonthethird** [comment]
Additionally, it would be nice to be able to tell the tooling which part of the static parameter is in error so not the whole type provider usage is underlined and you have to hover over it to get a more detailed error message.

**Comment by matthid** [comment]
@nikonthethird definitely, good point, that's probably even simpler to start with
@cloudRoutine Yeah, maybe we should even think further: Intellisense/QuickFixes? The type provider can provide some "language service" to the compiler? The F# compiler than only needs to do some conversations regarding the escaping?

**Comment by dsyme** [comment]
@matthid I like the suggestion.  But I don't know where this stops - do we also provide autocomplete APIs in the string?

**Comment by matthid** [comment]
Yeah, why stop at all? One after the other. Or starting and evaluating how it feels...

**Comment by voronoipotato** [comment]
yes this is a fantastic idea. It would drastically improve the ease of use of TP's.

**Comment by voronoipotato** [comment]
If we do work this I presume @Krzysztof-Cieslak would need to be involved in some way.
