### ISSUE TITLE
Provide an Async conversion function for `structural awaiters`

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#559]
I propose we provide functions on the `Async` module that provide conversions to `Async<T>` for so-called `structural awaiters`, meaning types that have a member `GetAwaiter: unit -> #awaiter<T>`, where `#awaiter` is a flexible type representing the following constraints:

- implements one of `INotifyCompletion` or `ICriticalNotifyCompletion`,
- has a boolean property getter `IsCompleted`, and
- has a member `GetResult () -> T`, where `T` can be `void`

This will help with interop situations where C# library developers have rolled custom awaiters instead of using `Task` and `Task<T>` derivatives, for example in the [Microsoft Bot Framework](https://docs.botframework.com/en-us/csharp/builder/sdkreference/d9/d4e/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_i_awaitable.html).

There is a snippet at [stackoverflow](http://stackoverflow.com/a/28354189/433393), but proper code review/hardening would be nice.

## Pros and Cons 

The advantages of making this adjustment to F# are easier more natural library interop.

The disadvantages of making this adjustment to F# are having to either hand-roll such a function, which may be easy to mess up considering SynchronizationContexts, etc, or accept blocking on GetResult.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by baronfel** [comment]
Additional notes: how would this interact with _TaskLike\<T\>_ which exist now in C#. These are arbitrary awaitable things that specify a builder that knows how to construct them. Is that proposal a (sub)(super)set of this behavior?  see [this](https://github.com/dotnet/roslyn/issues/10902#issuecomment-242428870) and [that](https://github.com/dotnet/roslyn/issues/10902#issuecomment-242833132) discussion on the roslyn repo for more detail

**Comment by dsyme** [comment]
@baronfel I'd be interested to see a complete proposal and proto implementation for this, with examples of use - the linked example looks a bit thin to get the full idea and practical utility

**Comment by dsyme** [comment]
See also https://github.com/dustinmoris/Giraffe/blob/master/src/Giraffe/Tasks.fs#L266 for a guide for how to do this for the ``task { ... }`` computation expression

**Comment by baronfel** [comment]
The task computation expression has moved, and it has a very nice generic binder here: https://github.com/rspeele/TaskBuilder.fs/blob/master/TaskBuilder.fs#L80

This binder seems to replicate the targeting criteria I was mentioning in the submission, and might be worth trying to replicate on async directly (via propagating the continuations)

**Comment by jnm2** [comment]
> or accept blocking on GetResult.

One thing I discovered was that there is no requirement for custom C# awaitables to block in their GetResult implementation. It's not expected in general (unless you know something special about a specific type like `TaskAwaiter`) that GetResult will event be called unless IsCompleted is true or after OnCompleted invokes continuation. [(spec)](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#awaitable-expressions)

To achieve actual blocking until complete awaitables over than TaskAwaiter, something like this is needed (sorry for the C#):

```cs
var awaiter = awaitable.GetAwaiter();

if (!awaiter.IsCompleted)
{
    using (var completed = new ManualResetEventSlim())
    {
        awaiter.OnCompleted(completed.Set);
        completed.Wait();
    }
}

var result = awaiter.GetResult();
```

**Comment by dsyme** [comment]
Note this functionality is available for `task { ... }`.

**Comment by abelbraaksma** [comment]
For posterity, this was closed as ‘completed’, and yes, it exists to some extend in `task` now, but remaining and related issues are in #840, which is still open.
