### ISSUE TITLE
Transparent single-case Discriminated Unions

### ISSUE THREAD

**Issue by Soldalma** [fsharp/fslang-suggestions#568]
# Transparent single-case Discriminated Unions

I propose allowing single-case Discriminated Unions be optionally transparent to the underlying type.

This example illustrates the proposal:

```fsharp
let s = "ABC"
let s1 = s.Chars 1 // Ok, s1 = 'B'

type MyString = | MyString of string
let (x: MyString) = MyString "ABC" 
let x1 = x.Chars 1 // Fails: "The file or constructor 'Chars' is not defined"
```

My proposal:

```fsharp
[< Transparent <] // this would create a transparent single-case DU
type MyString = | MyString of string
let (x: MyString) = MyString "ABC" 
let x1 = x.Chars 1 // Ok, X1 = 'B'
```

One could use the match command to convert x1 to a string object, but that is cumbersome.

## Pros and Cons 

The advantage of making this adjustment to F# is that transparent single-case DUs could be used to catch programming errors at compile time. 

For example, one could have two strings, one containing a customer first name, the other containing the customer last name:

```fsharp
let firstName = "Fernando"
let lastName = "Saldanha"
```

If one has a record

```fsharp
type Name = { FirstName: string; LastName: string }
```

then nothing prevents one from doing

```fsharp
{ FirstName = lastName; LastName = firstName } // uncaught error
```
Under the proposal one would declare 

```fsharp
[< Transparent <]
type FirstName = | FirstName of string
let (firstName: FirstName) = FirstName "Fernando" 
[< Transparent <]
type LastName = | LastName of string
let (lastName: LastName) = LastName "Saldanha"
type Name = { FirstName: FirstName; LastName: LastName }
```

and the compiler would catch the mistake:

```fsharp
{ FirstName = lastName; LastName = firstName } // Error
{ FirstName = firstName; LastName = lastName } // Ok
```
As above, methods of the string type would be accessible:

```fsharp
let f1 = firstName.Chars 1 // Ok, f1 = 'e'
```
I don't see any disadvantages in making this adjustment to F#. However, there was a similar suggestion (#564) that proposed transparency:

"I propose we add accessors for all properties that are common among all cases in a discriminated union at the type level." 

The proposal got two comments, but I am not aware it has been denied. My proposal is less ambitious and avoids some of the problems raised in the comments.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by cartermp** [comment]
@Soldalma Could you [format your code snippets](https://help.github.com/articles/creating-and-highlighting-code-blocks/) with `fsharp` as the specified language?  Thanks!

**Comment by Pauan** [comment]
This reminds me a lot of https://github.com/fsharp/fslang-suggestions/issues/563

**Comment by neoeinstein** [comment]
Several questions which I think we would need to flesh out before this becomes a full proposal. Some have semi-obvious answers, but I think it would be good to think them through and spell out the implications.

* How would transparent types work with added methods or extensions?
* Is the DU erased at runtime, or is it an actual wrapping type?
* If we can add members to the DU, how do we resolve a name collision between the DU member and the member on the wrapped type?
* Can the data constructor for the transparent DU be private?
* If it is, does [<Transparent>] still allow direct access to the wrapped type's members?
* Would extending units of measure to all types (as in #563) make this proposal redundant?
  * What does this add that isn't provided there?
  * On the other hand, if we select one or the other to do, why should this proposal be accepted over the units of measure proposal?

I'm interested to think through how this would work with my more pressing interest of having erased DUs, which would not automatically promote all of the wrapped type's members to the wrapper. But, having an `[<Erase>]` and `[<Transparent>]` DU might make working with wrapped types nicer. Having them as separate concepts allows for a more `newtype`-like functionality with just `[<Erase>]`.

**Comment by Thorium** [comment]
I would rather see refactoring tools to give automatic (rename-like) refactoring option to convert a type to single-case-DU or single-case-DU back to basic type. The whole point of single-case-DU is that it can't be messed with basic type.

```fsharp
type MyString = | MyString of string
let (x: MyString) = MyString "ABC" 
let x1 = x.Chars 1
let x2 = "ABC"
let ok = (x = x2) // what would this be?
```

**Comment by voronoipotato** [comment]
I don't understand why you wouldn't just use a type alias here. There's an entire group of people who rely on the single case DU not being treated like the underlying type.

**Comment by abelbraaksma** [comment]
> `[< Transparent <] // this would create a `

@Soldalma, I hope you weren't suggesting to change the way attributes are declared? Can you update, there are several occurrences. It should be `[<Transparent>]`.

Personally, I don't see the advantage here. Single case DU's are meant to shield the underlying value. It's very common to have a property on the type, `this.Value = match this with MyString v -> v`, or a static `get` function: `static member get (MyString v) = v`. Using such approach is common, and makes your code clearer than when it's suddenly as transparent as a type alias.

**Comment by dsyme** [comment]
Superseded by https://github.com/fsharp/fslang-suggestions/issues/1098
