### ISSUE TITLE
Allow let bindings scoped to an interface implementation

### ISSUE THREAD

**Issue by 0x53A** [fsharp/fslang-suggestions#573]
# Allow let bindings scoped to an interface implementation

I propose we allow let bindings scoped to an interface implementation.

The existing way of approaching this problem in F# is to move the let binding to the top of the type.

## Example:

__Before:__

```F#
type MySuperCoolType() =

    let wasDisposed = ref 0
    // imagine a few hundred lines of other members and other interface implementations

    interface IDisposable with
        member x.Dispose() =
            if 0 = System.Threading.Interlocked.CompareExchange(wasDisposed, 1, 0) then
                clear() // do the stuff
                GC.SuppressFinalize(x)
```
__After:__

```F#
type MySuperCoolType() =

    // imagine a few hundred lines of other members and other interface implementations

    interface IDisposable with
        let wasDisposed = ref 0
        member x.Dispose() =
            if 0 = System.Threading.Interlocked.CompareExchange(wasDisposed, 1, 0) then
                clear() // do the stuff
                GC.SuppressFinalize(x)
```

## Pros and Cons 

The advantages of making this adjustment to F# are: it would be possible to scope variables closer to where they are used, reducing the need to navigate through the class and making it easier to see what is accessed globally and what is just accessed locally.

The disadvantages of making this adjustment to F# are: let bindings can now be scattered in multiple places, making it harder to see all local state at a glance.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment]
I feel this disadvantage is decisive:

> The disadvantages of making this adjustment to F# are: let bindings can now be scattered in multiple places, making it harder to see all local state at a glance.

If we were going to do this I would prefer an addition that is expression-oriented and encourages composability, i.e. #132

**Comment by dsyme** [comment]
I will close this in favour of #132 per my comment
