### ISSUE TITLE
Curry on: an extension to format

### ISSUE THREAD

**Issue by sgtz** [fsharp/fslang-suggestions#575]
The functions: sprintf, kprintf, bprintf use currying and compiler magic to allow the sprintf "%s" magic to happen. If you partially apply a formatter, then the magic abruptly stops (see example below). It'd be nice if currying continued, and you could commute the formatter further down a function chain. For example, kprintf gets curried in the F# compiler source code to produce sprintf. It **looks** like this should be the behaviour elsewhere, too. It's not, though. Alas.

```
let toLinuxFileSysLiteral s = 
  System.Text.RegularExpressions.Regex.Escape(s)
  |> (fun x->x.Replace(@"\.", "."))

let mkdir fmt = 
  sprintf "mkdir %s" << (toLinuxFileSysLiteral << sprintf fmt)

let mkdir2 (fmt : Printf.StringFormat<'T>)  = 
  sprintf "mkdir %s" << (toLinuxFileSysLiteral << Printf.kprintf id fmt)

let mkdir3 (fmt : Printf.StringFormat<'T>)  = 
  sprintf "mkdir %s" << (Printf.kprintf toLinuxFileSysLiteral fmt)

mkdir "a/%s/c" "b"          // success

mkdir "a/%s/c/%s" "b" "d"   // fail

mkdir2 "a/%s/c" "b"          // success

mkdir2 "a/%s/c/%s" "b" "d"   // fail

mkdir3 "a/%s/c" "b"          // success

mkdir3 "a/%s/c/%s" "b" "d"   // fail

```

note: the difference between mkdir 1 .. 3 is just an experiment to see if the way we compose our functions makes a difference. It does not. They are all equivalent for this behaviour.

The existing way of approaching this problem in F# is ...

Just don't do it. Yes it works for one argument, but it's not a productive to do that. 

workaround -- alias the formatter, like this:

let sf = sprintf

... and pass a string henceforth, instead. 

## Pros and Cons 

The advantages of making this adjustment to F# are ...

1. combinators working with streams become more flexible. Then efficiencies due to streams/buffers in bprintf, fprintf kick it.

2. One more rough edge shaved off. F# behaves in a friendly way when you come up with an idea.

3. a neat tutorial on currying, explained in terms of extending one way that F#, itself, uses currying (which everybody already knows about) in the Printf module, works as expected. A little too recursive an explanation, perhaps, but people start thinking, "Such a powerful concept. Such a powerful concept." It's easy to take things for granted, or even, for the cautious, to mentally place things in "no-go" areas. Removing friction rewards curiousity.

The disadvantages of making this adjustment to F# are ...

All functions involving strings in some code bases start using a formatter instead, and then... some kind of implosion gets triggered.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S    :)

Related suggestions: (put links to related suggestions here)

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [ X ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ X ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ X ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.
  NB. how could you exhaustively know that without being on the design team?

Please tick all that apply:
* [ X ] This is not a breaking change to the F# language design
* [ X ] I would be willing to help implement and/or test this
* [partial ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this
  ... I'd be willing to contribute time to work on this.

**Comment by cartermp** [comment]
@sgtz Could you format the code sample using triple backticks and `fsharp`?  E.g.

```
```fsharp
```

Thanks!

**Comment by sgtz** [comment]
@cartermp: done!

**Comment by dsyme** [comment]
@sgtz You can do this:
```
let mkdir fmt = 
 Printf.ksprintf (fun res -> toLinuxFileSysLiteral ("mkdir " + res)) fmt

mkdir "a/%s/c" "b"          // success

mkdir "a/%s/c/%s" "b" "d"   // success
```

**Comment by sgtz** [comment]
Thanks. I came up with other ways to do it, too. The mechanism employed in ksprintf is cool... at the time I was seeing other uses of this device. However, instead of that stuff just kicking in fluidly in a partial-application kind of way, I'd need to do workarounds. That's the difference between building using a native F# style/device and just using it piecemeal, I guess. The partial way feels more natural. Maybe I'm being lazy. Probably not a big deal either way. This would be convenient and ultra elegant in some specific cases. On ksprintf specific, the worst thing about it is when you start wanting it in other languages.

**Comment by mvkra** [comment]
I know this issue is closed but I hit this recently and was wondering if this scenario was handled currently rather than raising another issue. I have cases like this all too often hence I searched for this ; usually because when I partially apply something I also want to cache the intermediary. This way other method invocations of the partially applied function don't have to run the inner function more than once. Note that with interfaces it is possible because unlike F# Func's the generic type parameters can be defined at the method level not the class level. 

A very contrived example following a similar shape to the problem:

```fsharp
let evaluate arg1 arg2 = 
    let cachedImmutableReusableResult = functionFromElsewhere arg1 arg2 // This line doesn't need the 3rd line to evaluate and could use this cached result for all partial completions
    fun (arg3: 't) -> runOtherFunc cachedImmutableReusableResult arg3
```

With no generic's this pattern is indeed possible and easy. The only workaround I've seen is making "functionFromElsewhere"  public and having the user evaluate that (not always possible) OR using an interface rather than a closure as the return type:

```fsharp
let cachedImmutableReusedResult = functionFromElsewhere arg1 arg2
runOtherFunc cachedReusedResult arg3
```
OR something like

```fsharp
let evaluate arg1 arg2 = 
    let cachedImmutableReusedResult = functionFromElsewhere arg1 arg2 // This line doesn't need the 3rd line to evaluate and could use this cached result for all partial completions
    { new IFunc with member __.Apply<_>(arg3: 't) = runOtherFunc cachedReusedResult arg3 }
```

**Comment by dsyme** [comment]
@mvkra @sgtz I don't quite understand the actual suggestion here.  Could you elaborate? Thanks

**Comment by mvkra** [comment]
I can try @dsyme. Bascially if I parially complete a function right now and it closes over some state I can't use the partially applied function with different type arguments. Maybe another example might help?

```fsharp
let evaluateAndMakeTuple f  = 
    let memorisedValue = f() // Note I only want this to run once
    fun s -> (memorisedValue, s)

let partialAppliedFunc = evaluateAndMakeTuple (fun () -> 2)
// Line below works
let result1 = partialAppliedFunc "2" // Returns (2, "2")
// Does not work - argument should be "string" but is "int" - should return (2, 3)
let result2 = partialAppliedFunc 3
```
Previously I've worked around this by returning an interface with an "Apply" method rather than a function in the "evaluateAndMakeTuple" function. What I ideally would like is if there was a mechaism where the second function assigned to "result2" would also "just work". Or if there is a method called "Apply" on an interface allow that to be used as syntactic sugar similar to Scala.

**Comment by abelbraaksma** [comment]
I know it is a while ago but I didn't want to leave your question hanging in case somebody else lands on this page. You wrote:

>    let partialAppliedFunc = evaluateAndMakeTuple (fun () -> 2)
>    // Line below works
>    let result1 = partialAppliedFunc "2" // Returns (2, "2")
>    // Does not compile - argument should be "string" but is "int" - should return (2, 3)
>    let result2 = partialAppliedFunc 3

This doesn't work because `partialAppliedFunc` is itself a value. Automatic generalizations work only with functions. You can fix that in a variety of ways, the simplest being to repeat at least one of the function arguments so that it doesn't become constant:

    let partialAppliedFunc x = evaluateAndMakeTuple (fun () -> 2) x

Another one being to introduce a dummy unit argument:

    let partialAppliedFunc () = evaluateAndMakeTuple (fun () -> 2)

There are also other ways you can generalize this, but what you are encountering is by design.

**Comment by sgtz** [comment]
in my case, I was able to push constructed formatters further so long as they were the last thing to fall out of the function. 

```
let toEscaped s = 
  System.Text.RegularExpressions.Regex.Escape(s)
  |> (fun x->x.Replace(@"\.", "."))

let mkdir2eg a fmt = 
  Printf.ksprintf (fun res -> toEscaped (a + "mkdir " + res)) fmt

mkdir2eg "title -- " "a/%s/c" "b"          // success
mkdir2eg "title -- " "a/%s/c/%s" "b" "d"          // success
```

Probably this is to do with some ILGen going on (I think that's correct?). The use of composition operators (<< and >>) likely murkied the water too. See ([the implemenation] (https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/printf.fs) for more hints . 

The original idea was to use kfprintf and kbprintf (or a stream version of these) in a certain style that made sense at a higher level.

**Comment by mvkra** [comment]
@sgtz In the end I just used a one method interface as passed around interfaces despite being objects still allow generic method invocation after instantiation. It just seems peculiar that I'm defining a one-method interface that's called IFunc with a generic method to do what a function intuitively should allow.

@abelbraaksma was always aware of F# functions being values. a more detailed version of the problem can be seen in this SO question (https://stackoverflow.com/questions/42598677/what-is-the-best-way-to-pass-generic-function-that-resolves-to-multiple-types). In this example they are using a "Wrapper" interface.

**Comment by abelbraaksma** [comment]
@mvkra, that's a nice reference, esp Gustavo's suggestion (2nd answer presently) to solve it using inline and a binding operator to defer inference resolution. Not sure it can be made working with printf style functions though.

**Comment by sgtz** [comment]
@mvkra thanks for the nudge towards the pragmatic. 

... the potential of a formatted stream getting written to a socket/*anywhere*, yet lets pause for a moment at string builder for argument sake, through layers of partial application. I get tripped up sometimes looking at this from the algebraic nature that FP enables/encourages. Sometimes you've just got to take it back a step from an ideal, yet we're still in a pretty good place.
