### ISSUE TITLE
Allow converting empty strings to options.

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/fslang-suggestions#578]
I propose we add support for converting empty strings to options.

The existing way of approaching this problem in F# is to manually write a function that wraps around `String.IsNullOrWhitespace` and matches against the result, returning either Some x or None.

## Pros and Cons 

The advantages of making this adjustment to F# are removes boilerplate required, reduces chances of someone accidentally using `Option.ofObj` against a string and getting e.g. `Some "   "` back etc.

The disadvantages of making this adjustment to F# are that it could theoretically cause confusion as to when to use `Option.ofObj` instead of `Option.ofString`.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS
Draft RFC is [here](https://github.com/fsharp/fslang-design/blob/master/drafts/FSS-0001-option-of-string.md) and PR is [here](https://github.com/Microsoft/visualfsharp/pull/3135).

Related suggestions: (put links to related suggestions here)

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [x] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by rmunn** [comment]
The RFC suggests that strings that are null or whitespace-only would become `None`, but this would be surprising to me: I would expect `Option.ofString` to convert strings that were either `null` or **empty** to a `None`. In other words, the RFC wants `IsNullOrWhiteSpace` semantics, but I would expect `IsNullOrEmpty` semantics. I propose a quick poll:

- Please **UPvote** this comment if you think that `Option.ofString` should have `IsNullOrEmpty` semantics. In other words, `null` -> `None`, `""` -> `None`, `" "` -> `Some " "`, `"foo"` -> `Some "foo"`
- Please **DOWNvote** this comment if you think that `Option.ofString` should have `IsNullOrWhiteSpace` semantics. In other words, `null` -> `None`, `""` -> `None`, `" "` -> `None`, `"foo"` -> `Some "foo"`

And if you just want to say "Nice comment", please do **NOT** use the thumbs-up reaction. Use the "Hooray" or "heart" emoticons for that instead. :-)

**Comment by theprash** [comment]
I was thinking about a more general approach that hopefully would still be concise and readable. What about function(s) that take a predicate:

```fsharp
module Option =
    let where    f x = if f x then Some x else None
    let whereNot f x = if f x then None   else Some x

open System

""   |> Option.whereNot String.IsNullOrEmpty      // None
" "  |> Option.whereNot String.IsNullOrEmpty      // Some " "
" "  |> Option.whereNot String.IsNullOrWhiteSpace // None

" "  |> Option.where (not << String.IsNullOrWhiteSpace) // None
"a"  |> Option.where (String.exists ((=) '/'))          // None
```

This way is quite general (see the last example) and quite explicit.

I'm not sure about including the `whereNot`, just because F# usually doesn't include the negative version of functions that take a predicate.

@isaacabraham Would this cover your use case adequately?

**Comment by theprash** [comment]
By the way, to me personally it's completely expected for `Option.ofObj ""` to be `Some ""`, and `Option.ofObj " "` to be `Some " "`

**Comment by dsyme** [comment]
> By the way, to me personally it's completely expected for Option.ofObj "" to be Some "", and Option.ofObj " " to be Some " ", and not obvious why a function called Option.ofString would behave differently. I would need to read its documentation.

I agree with this.

**Comment by piaste** [comment]
@theprash 

I agree with your proposal. In my utils I call that function `Option.ofPredicate`, to keep with the pattern that the module uses.

**Comment by isaacabraham** [comment]
Perhaps a rename then to Option.ofNonEmptyString? Don't know. Option.ofObj would be the basic reference type; this would do the null or whitespace check.

**Comment by rmunn** [comment]
After thinking it over, I'm changing my opinion on this proposal, and am now :-1: on it. It's a useful function, but I just don't think there's enough use case for it to belong in FSharp.Core. It's easy enough to write (and will become even easier once `String.isEmpty` and/or `String.isBlank` show up in FSharp.Core), so anyone who needs it can easily implement it. But I'm not persuaded that the demand is widespread enough for this to belong in FSharp.Core.

**Comment by dustinmoris** [comment]
I personally think there was one option missing to vote and that is the option where only a null string would be `None` and everything else would be `Some ...`. An empty string is still a perfectly valid string and therefore `Some` IMHO.

**Comment by rmunn** [comment]
@dustinmoris - I left that option off my "informal vote" comment because it already exists: it's called `Option.ofObj`. See https://github.com/fsharp/fslang-suggestions/issues/578#issuecomment-307366974 where it's (briefly) discussed.

**Comment by isaacabraham** [comment]
Sounds like there's not a great need for this then within FSharp.Core :-( @theprash perhaps open a proposal for the IsPredicate one? That's something that's more flexible and might be of more general use.

@dsyme Any objection to closing this and the related PR and RFC?

**Comment by dsyme** [comment]
@isaacabraham I'm happy with leaving suggestions open a long time to see if they attract alternative perspectives.   Different usage domains of F# can drive different patterns of expectation of what the core library does/doesn't support (e.g. culture sensitive v. culture invariant; or strings-as-simple-data-type v. strings-as-human-oriented-data)

**Comment by dsyme** [comment]
@isaacabraham We should probably close the RFC since I think we're some distance off an agreed design proposal

**Comment by xperiandri** [comment]
So is there some work on `Option.ofPredicate`, `Option.ofInversePredicate` going?

**Comment by isaacabraham** [comment]
Isn't that just `Option.filter`?
