### ISSUE TITLE
More granular CLIMutable

### ISSUE THREAD

**Issue by Regent** [fsharp/fslang-suggestions#580]
I propose we make `CLIMutableAttribute` more granular.

Currently `CLIMutable` can only be applied on a the entire record type making all properties settable from the CLI world, e.g.
```F#
[<CLIMutable>]
type User = { Id : string
              Name : string
              Email : string }
```

I would like more granular control over that, allowing opting in for setter only specific fields, e.g.
```F#
type User = { [<CLIMutable>]Id : string
              Name : string
              Email : string }
```
## Pros and Cons 

The advantages of making this adjustment to F# is giving more control over mutability.

Can't think of any obvious disadvantages of making this adjustment to F#.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

## Affidavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by s952163** [comment]
It`s interesting but you could just handle it with a class and then it will be even clearer. Just not a big fan of using attributes left and right.

**Comment by Regent** [comment]
Well, generally I find it clearer and easier to use records. True, with classes you can have any custom logic you like but it will also allow changing properties from your F# code. `CLIMutable` in this instance allows you to stay functional in F# yet allowing CLI code to modify some properties.

**Comment by dsyme** [comment]
There has been a long running history of "beef up records to do more class-like things".  In general we do not go in this direction unless the use-cases are really compelling - just use a class instead as mentioned above.

As a result I will close this suggestion (thanks for making it though)
