### ISSUE TITLE
Random jotting on table expressions

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#583]
This is a random set of jottings and wishful thinking after reading http://orgmode.org/worg/org-tutorials/org-spreadsheet-lisp-formulas.html

The overall question: is it realistic or even technically possible to support some kind of "table expressions" in a strongly typed language. Think list/array comprehension comprehensions on triple steroids suitable for data frame operations too.  Also think "cut and paste from Excel" 

I'm not saying this is at all a good idea :) It is likely technically too difficult in a strongly typed language, and any F# variation on this would have to look quite different to anything below, just to disambiguate everything

Please provide links to related work (apart from Excel....) if you know of it.

This could also be more suitable for something like TheGamma.

This might depend extensively on any or all of type providers, anonymous records, ...

##### Table expressions:

```fsharp
let table1 = table
  | Student  | Maths | Physics |
  |----------+-------+---------|
  | Bertrand |    13 |      09 |
  | Henri    |    15 |      14 |
  | Arnold   |    17 |      13 |
```
Here the token ``table`` (or whatever we used) would have some kind of status where all indented text after it would form part of the spec of the table.  Whether that's as a string or is actually parsed (perhaps by a type-provider like plugin mechanism) I don't know.

Maybe this desugars to

```fsharp
table.Build< "Student"; "Maths"; "Physics" >
    [| {| Student="Bertrand"; Maths=13; Physics=9 |}
       {| Student="Henri"; Maths=15; Physics=14 |}
       {| Student="Arnold"; Maths=17; Physics=13 |} |]
```

##### Adding columns. 
```fsharp
let table1 = table
  | Student  | Maths | Physics | Mean |
  |----------+-------+---------+------|
  | Bertrand |    13 |      09 |   average($2..$3) |
  | Henri    |    15 |      14 |      |
  | Arnold   |    17 |      13 |      |
```
Here ``$2`` must be a kind of comprehension syntax that refers back to the table itself.

Also ``average($2..$3)`` applies to the entire column below it

Maybe this desugars to
```fsharp
table.Build< "Student"; "Maths"; "Physics" >
    ([| {| Student="Bertrand"; Maths=13; Physics=9 |}
        {| Student="Henri"; Maths=15; Physics=14 |}
        {| Student="Arnold"; Maths=17; Physics=13 |} |])
    .AddComputedColumn<"Mean">(fun x -> Array.average [ x.Item2;  x.Item3 ])
```

##### Naming columns
```fsharp
let table1 = table
  | Student  | Maths | Physics | Mean |
  |----------+-------+---------+------|
  | Bertrand |    13 |      09 |   average($Maths..$Physics) |
  | Henri    |    15 |      14 |      |
  | Arnold   |    17 |      13 |      |
```
Here ``$Maths`` must be a kind of comprehension syntax that refers back to the table itself.

##### Augmenting tables:
```
let table2 = table
  | table(table1) | Mean                       |
  |---------------+----------------------------|
  |               |  average($Maths..$Physics) |
```

Maybe this desugars (strongly typed) to
```fsharp
table1.AddComputedColumn<"Mean">(fun x -> Array.average [ x.Maths;  x.Physics ])
```

##### Strongly named augmentations of provided tables

```fsharp
let table1 = table
  | table(data<"http://wikipedia.org/a/b.html">) | Mean                       |
  |-----------------------------------------------+----------------------------|
  | ...                                           |  average($Maths..$Physics) |
```

## Pros and Cons 

Con: complicated

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XL

Related suggestions: (put links to related suggestions here)

**Comment by panesofglass** [comment]
This would provide tremendous value, in my opinion. It reminds me of [dee (for Python)](http://www.quicksort.co.uk), a relational model based on the work of Date and Darwen's Third Manifesto. The ability to use and manipulate relational data within the language and according to a relational model would be very powerful. I know that is not an immediate design consideration, but I would assume it could be added as a result of this work.

**Comment by piaste** [comment]
This is interesting. My first thought is that this feels closer in scope to computation expressions than to mere list comprehension, due to all the potential features you could want (computed columns, joins, and so on).

As a starting point -- with custom CE tokens, something like this ought to be, if not already possible, 
pretty close to possible: 

```f#
type Student = Student of name : string * maths : int * physics : int

// table1 : table<Student>
let table1 = table {  
  // a function (constructor) with signature ('a * 'b * ... -> 't) gives strong typing
  columnsOf Student
  row ("Bertrand" , 13, 09)
  row ("Henri"    , 15, 14)
  row ("Arnold"   , 17, 13)
}

// alternatively you can just list the column names and work with raw tuples
// table2 : table<string * int * int>
let table2 = table {
  columns ("Name"      , "Maths", "Physics")
  row     ("Friedrich" ,      13,        09)
  row     ("Niels"     ,      19,        02)
  row     ( "David"    ,      12,        11)
  addComputedColumn "Mean" (fun _ m p -> Math.avg m p)
}

// you could combine it like this
let table3 = table {
   merge! table1
   merge! table2
   addComputedColumn "Best" (fun _ m p -> Math.max m p)
}
```

Obviously the CE syntax isn't great here - it's not easy to scan at a glance, and definitely doesn't play well with paste-from-Excel.

So, might it be conceptually simpler to increase the flexibility of custom CE operators?

```f#
// ! is a combinator for 'columns'
// % is a combinator for 'addComputedColumn'
// - is ignored
// | is a combinator for 'row'
let table2 = table {
  ! "Name"      ! "Maths" ! "Physics"  % ("Mean", fun _ m p -> Math.avg m p)
  -------------------------------------------------------------
  | "Friedrich" |     13  |        09
  | "Niels"     |     19  |        02
  | "David"     |     12  |        11
}
```

I'm sure this could be wildly abused in the same way that custom operators can be abused, but I also see it providing extra utility beyond this particular case.

**Comment by panesofglass** [comment]
Following @piaste's comment, might this include the joinads extension?

**Comment by panesofglass** [comment]
Additional thoughts on proposed syntax:
1. I like the basic design.
2. Should column references be 0 or 1 based?
3. I am not as thrilled with the augmentations. I would prefer something akin to list comprehensions, perhaps more like the de-sugared form.
4. I prefer the de-sugared form generally.
5. Some way of applying constraints would be useful.
6. Joins would be a very welcome. How might this work with a query CE? Would it be possible to produce new tables?
7. Are nested (grouped) tables in view? For example, could I apply a group by operation and see a nested table output?

**Comment by panesofglass** [comment]
For the desired syntax, it does seem like adding custom CE operators or a type provider would be useful. If that's all that's desired, it seems either would suffice.

When I saw this proposal, I immediately thought of the work done in dee (python) and rel (ruby) re: relational models added to a language. Thinking through it more, I suppose anonymous records + `query` expressions solve most of the issues. I may play with this idea some more. @dsyme, have you started any work on this?

**Comment by dsyme** [comment]
> @dsyme, have you started any work on this?

No, it was just a random note based on seeing the feature in another setting

**Comment by dsyme** [comment]
> Why not use a type provider for this? and an external lib? A lot easier to evolve..

I agree with this.  Will close this as a language suggestion
