### ISSUE TITLE
Stop producing warning FS0009 on legitimate uses of StructLayout

### ISSUE THREAD

**Issue by ForNeVeR** [fsharp/fslang-suggestions#596]
# Stop producing warning FS0009 on legitimate uses of StructLayout

Consider the following code:

```fsharp
[<StructLayout(LayoutKind.Sequential)>]
[<Struct>]
type SP_DEVINFO_DATA =
    val mutable cbSize : uint32
    val mutable ClassGuid : Guid
    val mutable DevInst : uint32
    val mutable Reserved : nativeint
```

Currently it will produce the following warning:

```
Native.fs(21,6): warning FS0009: Uses of this construct may result in the
 generation of unverifiable .NET IL code. This warning can be disabled using '--nowarn:9' or '#nowarn "9"'. 
```

[Connect Issue](https://connect.microsoft.com/VisualStudio/feedback/details/643668/f-structlayout-attribute-always-produces-a-possibleunverifiablecode-warning) suggests that the code using `StructLayout` is only "unverifiable" if it uses `LayoutKind.Explicit` and the object references in the structure overlap with any other objects or references.

ECMA-335 seems to agree with that, see [II.10.7. Controlling instance layout](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf#page=179).

I wasn't able to reproduce the warning with C# compiler.

I propose that we don't issue the warning FS0009 in cases where `LayoutKind.Explicit` is not used. Probably we could even check whether any references overlaps with anything else, but it would be enough to just disable the warning for `LayoutKind.Auto` and `Sequential`.

## Pros and Cons 

The advantage of making this adjustment to F# is that writing P/Invoke code will become less annoying.

The disadvantage of making this adjustment to F# is slightly more complex analysis of `StructLayout` attribute before issuing a warning FS0009.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): **S**.

Related suggestions: none.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate, **although I found the [linked Connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/643668/f-structlayout-attribute-always-produces-a-possibleunverifiablecode-warning)**
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
That makes total sense.  Marking as approved-in-principle, please feel free to just submit a PR for this (it barely needs an RFC though we can add one for it)

**Comment by realvictorprm** [comment]
@dsyme is this now solved with the referenced commits and PR's?

if so, can we close it then 👍 ?

**Comment by dsyme** [comment]
Yes, thanks!
