### ISSUE TITLE
Proposal: Compact way to change priority

### ISSUE THREAD

**Issue by kogoia** [fsharp/fslang-suggestions#598]
# Compact way to change priority

I propose we can simplify the syntax of creating nested classes, I will try explain what I mean:

Imagine we have some classes in C#:

```cs
new ExecutedCommand(
    new InsertSQLCommand(
         new ParsedXML(
                new XMLFile("path"),
                new SomeClass1()
         ),
         new SomeClass2()
    )
).Status();
```
and equivalent of this code in F#:

```fs
 ExecutedCommand(
     InsertSQLCommand(
          ParsedXML(
                 XMLFile("path"),
                 SomeClass1()),
          SomeClass2())).Status()
```
That if we could write like this

```fs
 ExecutedCommand
     InsertSQLCommand
          ParsedXML
                 XMLFile "path"
                 SomeClass1
          SomeClass2
 .Status()
```
Make it possible to change the priority of execution via NewLine.
This makes it possible to remove the parentheses.

## Pros and Cons 

The advantages: nice syntax

The disadvantages: I should think

Express your opinion, I would like to see this in F#

**Comment by TheJayMann** [comment]
In both examples, reversing the order and using the pipe forward operator is already supported, and, I would argue, is easier to read.
```fsharp
XMLFile "path"
|> ParsedXML
|> InsertSQLCommand
|> ExecutedCommand
```
```fsharp
let result x =
  div3 x
  |> prod2
  |> add1
```

**Comment by kogoia** [comment]
But what if class expects two parameters
```cs
 ExecutedCommand
     InsertSQLCommand
          ParsedXML
                 XMLFile "path"
                 SomeClass1
          SomeClass2
 .Status()
```

**Comment by scrwtp** [comment]
It feels very situational to me, but even more so, this change is at odds with current syntax on a very fundamental level. 

Take this snippet for instance:
```
          ParsedXML
                 XMLFile "path"
                 SomeClass1
```
This is already valid F# for `ParsedXML: 'a -> string -> 'b -> 'c`, so you'd introduce ambiguity here.

What's more, one of the tenets of F# syntax is that a non-curried function applied to _n_ arguments (in this case, ParsedXML constructor) is indistinguishable on a syntactic level from a curried function applied to an _n_-tuple.  Your proposal would make for a weird and inconsistent departure from that rule.

**Comment by kogoia** [comment]
ParserXML is class in this case, for classes it will be very nice, I think so

**Comment by Pauan** [comment]
@kogoia If it expects two parameters, you'd just do this:

```fsharp
XMLFile "path"
|> ParsedXML (SomeClass1())
|> InsertSQLCommand (SomeClass2())
|> ExecutedCommand
|> Status
```

In my opinion, using currying and the `|>` notation completely solves this problem. It's the idiomatic way of doing things in F#.

Also, it's pretty rare to use classes in F#, it's better to use functions (functions have many advantages, including allowing you to use the `|>` syntax).

----

If you're trying to use an existing API which uses classes, you can convert the classes into functions:

```fsharp
let xmlFile path = XMLFile(path)
let parsedXML a path = ParsedXML(path, a)
let insertSQLCommand a b = InsertSQLCommand(b, a)
let executedCommand a = ExecutedCommand(a)
let status a = a.Status()
```

Because they are functions, they now work much better with F#.

It's important that the arguments are swapped (e.g. `parsedXML` has `path` as the last argument, but `ParsedXML` has `path` as the first argument). This is what allows you to use `|>` syntax:

```fsharp
xmlFile "path"
|> parsedXML (SomeClass1())
|> insertSQLCommand (SomeClass2())
|> executedCommand
|> status
```

**Comment by dsyme** [comment]
I'm closing this as it is reopening decisions already made in F# 1.x
