### ISSUE TITLE
Diagnostics: warn if a with-operation updates all values

### ISSUE THREAD

**Issue by 0x53A** [fsharp/fslang-suggestions#603]
# Diagnostics: warn if a with-operation updates all values

__I propose we ...__ warn if a with-operation updates all values.

Consider the following snippet:

```F#
type MyRecord = { A : int list ; B : string list }
let combine a b = { a with A = a.A @ b.A ; B = a.B @ b.B }

combine { A = [ 1 ] ; B = [ "2" ] }  { A = [ 1 ] ; B = [ "2" ] }
```

If I now update the type ``MyRecord`` and add a third field, the compiler will guide me to adapt the two constructors, but will NOT guide me to adapt ``combine``.

```F#
type MyRecord = { A : int list ; B : string list ; C : char list }
let combine a b = { a with A = a.A @ b.A ; B = a.B @ b.B } // <- C is missing

combine { A = [ 1 ] ; B = [ "2" ] ; C = [] }  { A = [ 1 ] ; B = [ "2" ] ; C = [ '3' ] }
```

Using a ``with`` doesn't really make sense in this situation, because all values are updated anyway, but __I have often seen this pattern in the wild!__ So I would want this warning to make later refactorings easier. Note that this warning would not be issued _after_ adding the third field, because by that time, the ``with`` would no longer update all fields.

~The existing way of approaching this problem in F# is ...~

## Pros and Cons 

_The advantages of making this adjustment to F# are ..._

Makes it easier to find places to adapt after adding a record field.

_The disadvantages of making this adjustment to F# are ..._

Perfectly fine code may produce this diagnostic, but the fix is easy and will improve the code base.
Any additional warning may break code that currently compiles if warn-as-errors is enabled. I think it would be worth it.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS-S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* Any additional warning may break code that currently compiles if warn-as-errors is enabled. I think it would be worth it.
* [x] I or my company would be willing to help implement and/or test this

**Comment by 0x53A** [comment]
Note: I strongly assume that this is the root cause of https://github.com/fsprojects/Paket/pull/2687, so this does actually cause bugs to slip-through.

**Comment by matthid** [comment]
@0x53A note that https://github.com/fsprojects/Paket/pull/2687 has nothing to do with your suggestion. I was only asking if there might be another bug (but not https://github.com/fsprojects/Paket/pull/2687 itself).

I like the suggestion and think it is sound. However I also think that people use the `with` syntax to guide type inference...

**Comment by dsyme** [comment]
Seems reasonable, even for the compiler (rather than FSharpLint)

**Comment by dsyme** [comment]
Note adding this diagnostic doesn't need an RFC

**Comment by matthid** [comment]
That was a fast approved, now we only need a PR ;)

**Comment by Rickasaurus** [comment]
We use the pattern `{ MyType.Default with ... }` quite a lot and I think this change would be rather annoying for us.

**Comment by 0x53A** [comment]
This warning would only trigger if you updated all 10+ fields in the same with expression, and then MyType.Default would not really do anything anyway. It would not affect the normal usage case where you only update a few fields.

**Comment by dsyme** [comment]
@Rickasaurus Yes, I think if you're replacing all the fields then you'd always want a warning to that effect

**Comment by Rickasaurus** [comment]
So, when adding a field to a large record, We now may need to make a change far up in the file to avoid a warning. Something additional to worry about in a merge that's really just noise. 

Would make for a nice suggestion refactoring in an IDE for sure.

**Comment by dsyme** [comment]
> So, when adding a field to a large record update we now may need to make a change far up in the file to avoid a warning. Something additional to worry about in a merge that's really just noise.

@Rickasaurus Only if you were actually not making a record update at all, but actually replacing **all** values in the record.  Why wouldn't you want a warning when all the information in the original record in ``{a with ... }`` is effectively being lost/replaced?  We give warnings in F# when other information is thrown away

**Comment by Rickasaurus** [comment]
I don't think we've ever had an issue stem from this. 

Let me paint out the scenario that worries me. We have a lot of record-only nuget packages for communicating with our databases. Let's say some field gets removed because we decide we want to do this thing a different way in the database and it wasn't used in most places anyway. Now we see meaningless warnings in all 50 some odd downstream projects and tests where we were using `MyType.Default with`  for convenience. Suddenly we have a big cleanup effort because we like warning-free builds.

**Comment by vasily-kirichenko** [comment]
@Rickasaurus So you don't want to clean up your code?..

**Comment by Rickasaurus** [comment]
I don't consider this particularly dirty. In some ways it's cleaner as it keeps the diffs minimal.

**Comment by 0x53A** [comment]
Even if this is added, you could just suppress the warning globally and go back to the previous status quo.

**Comment by dsyme** [comment]
Yes,you'd just have to suppress the warning :)

**Comment by kerams** [comment]
Is higher warning level an option? Fewer people would be annoyed, but, by the same token, fewer people would discover this.
