### ISSUE TITLE
lambda sugar: books |> Array.map(fun'.Name)

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#604]
# Title of Suggestion

I propose we ... (describe your suggestion here)
need a lambda sugar.
The existing way of approaching this problem in F# is ...
`books |> Array.map(fun book -> book.Name)`
## Pros and Cons 
too long to read or wrtite
The advantages of making this adjustment to F# are ...
`books |> Array.map(fun'.Name)`
it is so simple, and also if you change your mind, then you can backspace `fun x -> x...`
The disadvantages of making this adjustment to F# are ...
`fun'.` will be a keyword, i want to nobody have used it as identity.
## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
XS
Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by xuanduc987** [comment]
Related https://github.com/fsharp/fslang-suggestions/issues/506

**Comment by dsyme** [comment]
I think this should be part of the #506 discussion - we wouldn't do both of these :)
