### ISSUE TITLE
Running compiler on project files containing FSX scripts

### ISSUE THREAD

**Issue by stishkin** [fsharp/fslang-suggestions#609]
Allowing compilation step of a project file with FSX scripts to verify that scripts do not have any errors. Currently I have to ether run the script or open it in Visual Studio editor (or VSTS editor). If I have a big corpus of scripts, it would be great to run compiler over them to see which ones have errors and need fixing.

## Pros and Cons 

The advantage of making this adjustment to F# that it enables better scripting exeperience.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
Why not just run ``fsc.exe`` on the scripts one by one?  Why would we build that capability into the F# compiler when it can be done easily via a script?

**Comment by realvictorprm** [comment]
@dsyme I instead suggest to add this for editors as option instead of adding it to the compiler.

**Comment by dsyme** [comment]
@realvictorprm I think you can just add an MSBuild task to do it.  Or a few lines of Unix scripting?

**Comment by matthid** [comment]
@dsyme While I fully agree that `fsc.exe` is the correct solution here, I think there are some edge cases where a fully valid script doesn't actually compile with `fsc.exe` (because of compiler directives only valid in Scripting environments or different behaviors). So it is a "mostly works" solution at the moment.

**Comment by realvictorprm** [comment]
Is this considered as bug @matthid?  
If so then we can fix it, if not I suggest to @stishkin to open a proposal for this.

**Comment by dsyme** [comment]
I'm closing this as it is a tooling issue.  If there's some way to just improve ``dotnet build`` or new-style F# project files to handle this case nicely then we should just do it in the F# compiler repo.
