### ISSUE TITLE
Usual .NET constructors for Discriminated Unions

### ISSUE THREAD

**Issue by DjArt** [fsharp/fslang-suggestions#615]
# Usual .NET constructors for Discriminated Unions
I propose we add usual constructors for discriminated unions for interop F# to C#. Now, we must to use functions, like "type".New"case"(params). But, F# generates classes for this cases, may be they should releases constructors?

* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

* [x] This is not a breaking change to the F# language design

**Comment by dsyme** [comment]
Note that F# doesn't always generate classes for union cases, e.g. it doesn't generate a class for unary alternatives, nor for struct unions. So the choice to use ``New`` was about giving F# room to make choices like this

As a result I will close this suggestion
