### ISSUE TITLE
Type annotation for set method of Indexed Properties 

### ISSUE THREAD

**Issue by DjArt** [fsharp/fslang-suggestions#618]
# Title of Suggestion

I propose we allow to define type of value, that will use set method of property. It's not a problem, when value is used evidently, but in some situations that not so.

Below I show example of code, that has this problem:
```
type public Matrix<'T>(rows : int, columns : int) =
    let mutable _RowsCount = rows
    let mutable _ColumnsCount = columns
    let mutable _Store : 'T[] = Array.zeroCreate(rows * columns)
    member this.RowsCount with get() = _RowsCount
    member this.ColumnsCount with get() = _ColumnsCount
    member this.Item
        with get(row : int, column : int) = _Store.[row * _ColumnsCount + column]
        and set(row : int, column : int) value = _Store.[row * _ColumnsCount + column] <- value
    member this.RowAt
        with get(index : int) =
            match index < _RowsCount with
            | true -> _Store.[index * _ColumnsCount .. (index + 1) * _ColumnsCount - 1] :> IEnumerable<'T>
            | false -> raise(ArgumentOutOfRangeException())
        and set(index : int) value =
            let FIX : IEnumerable<'T> = value //Without that I can't define a type of value
            match value.Count() = _ColumnsCount && index < _RowsCount with
            | true -> for i0 in 0 .. _ColumnsCount - 1 do _Store.[index * _ColumnsCount + i0] <- value.ElementAt(i0)
            | false -> raise(ArgumentOutOfRangeException())
```

## Pros and Cons 

The advantages of making this adjustment to F# are better syntax.

The disadvantages of making this adjustment to F# are... Hmm, they doesn't exist.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by realvictorprm** [comment]
I might be very wrong but can't you specify the type of the value in the declaration?

```fsharp
and set(index : int) (value:'a IEnumerable) =
```

**Comment by realvictorprm** [comment]
If this is not possible I'm wondering why :smile:

**Comment by DjArt** [comment]
Really, thanks, I was can't find documentation about it.

**Comment by realvictorprm** [comment]
Sure no problem at all, glad that I could help.

Well it's a declaration so everything which is allowed for such also is for properties if not specified otherwise.
