### ISSUE TITLE
Map and `dict` should implement `IReadOnlyDictionary<'Key,'Value>`

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#622]
# Support `IReadOnlyDictionary<'Key,'Value>` on `dict` and Map types

I propose we extend the types/functions above to implement `IReadOnlyDictionary` to provide an easy way to abstract across those types from C# code and still provide the non-mutable semantics we expect from those types.

The existing way of approaching this problem in F# is to turn either of those types into a `Dictionary<,>` and then cast to `IReadOnlyDictionary`

## Pros and Cons 

The advantages of making this adjustment to F# are being more clear on the intended semantics of core types and helper functions.

The disadvantages of making this adjustment to F# are potentially having to conditionally compile the implementation if the compiler targets a version of .Net that doesn't include the interface (.Net Framework < 4.5 I believe).

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
Labelling as approved

**Comment by saul** [comment]
Done: https://github.com/Microsoft/visualfsharp/pull/4014

**Comment by dsyme** [comment]
Closing in favour of #624 which can cover this too
