### ISSUE TITLE
Implement IReadOnly interfaces on relevant F# collections throughout FSharp.Core [ RFC FS-1041 ]

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#624]
I propose we implement `IReadOnly*` interfaces on F# collections throughout FSharp.Core.  This is an issue on VisualFSharp as well: https://github.com/Microsoft/visualfsharp/issues/3999

## Pros and Cons 

The advantages of making this adjustment to F# are ...

* They make sense, given that F# collections (sans Array) are immutable.
* This is really just something that's "missing" from FSharp.Core in general.

The disadvantages of making this adjustment to F# are ...

* It's code churn

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: #181

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
Labelled as approved

**Comment by saul** [comment]
Done: https://github.com/Microsoft/visualfsharp/pull/4014

**Comment by dsyme** [comment]
RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1041-ireadonly.md

**Comment by saul** [comment]
Can we use this issue to discuss the fact that `dict` cannot be modified to return an `IReadOnlyDictionary` as the types are incompatible.

I suggest we add a `readOnlyDict` top-level operator that takes the same pair sequence as `dict`, but returns an `IReadOnlyDictionary` instead.

**Comment by PatrickMcDonald** [comment]
There's a suggestion https://github.com/fsharp/fslang-suggestions/issues/619 to create an Immutable Array. The name given to the readOnlyDIct function should be consistent with any constructor function chosen for ImmutableArray (or vice versa)

**Comment by cartermp** [comment]
This is now completed.
