### ISSUE TITLE
Make "ModuleSuffix" the default if a type has the same name even if it's generic

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/fslang-suggestions#627]
This suggestion has already been implemented in F# 4.1 (see #113 and RFC https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1019-implicitly-add-the-module-suffix.md). However in the cases where the type is generic this doesn't happen. For example:

```fsharp
type Foo<'a> =
   { value: 'a }

module Foo =
   let add (x: Foo<'a>) (y: Foo<'a>) = { value = x.value + y.value }
```

This makes sense because the compiled name of the type is "Foo`1" so it doesn't conflict with the module, however it doesn't look consistent. My main problem is in Fable we don't add the number of generic parameters to the type name (this is to improve readability of the generated JS code) and because of this the sample above will do conflict. Before F# 4.1 devs were just used to add the "ModuleSuffix" attribute, but after that they are not using it anymore and when Fable complains the type and the module have the same public name they get surprised. See for example https://github.com/fable-compiler/Fable/issues/1231

This problem can be solved by adding the attribute but the user experience for Fable would be much better as it wouldn't differ from _standard_ F#.

## Pros

- Consistent behavior of adding Module suffix when there's a type and a module with the same name, no matter if the type is generic.
- Removing the need of adding the attribute only when compiling with Fable

## Cons

- For more savvy users, adding the Module suffix in this case could actually be unexpected (as they know names don't conflict in compiled .NET code)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S, probably just removing the generic param number suffix to the current check.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by ijsgaus** [comment]
Then we need alternative mechanism for don't use suffix in generic case

**Comment by cartermp** [comment]
@ijsgaus What scenario are you concerned about?  The module suffix isn't necessary in F# 4.1 in cases aside from what @alfonsogarciacaro mentions above, and with his suggestion the picture is completed.

**Comment by 0x53A** [comment]
Doesn't this break binary compatibility?

If I compile the snippet in the op with fsc vCurrent, then it emits a type ``Foo``. But if I then compile the exact same source with fsc vNext, it will emit a different type, and all my consumers break.

Therefore I have voted the issue down, even though I actually like the suggestion.

**Comment by alfonsogarciacaro** [comment]
@0x53A This wouldn't change the name of the **type** `Foo`, it would just add the `-Module` suffix to the **module** `Foo`. Exactly the same thing as happens now if type `Foo` wasn't generic.

@ijsgaus Please note the `-Module` suffix is transparent to the user, it only affects compiled code.

**Comment by 0x53A** [comment]
@alfonsogarciacaro Yes, I was talking about the static type that represents the module.

If the name of that type changes from ``Foo`` to ``FooModule``, I would expect a TypeLoadException at runtime.

**Comment by 0x53A** [comment]
I already really don't like the automatic feature that is already implemented for the same reason. As I understand it __adding__ a _type_ __changes__ the compiled name of the _module_.

**Comment by alfonsogarciacaro** [comment]
Closing. Latest Fable does add a mark to the name of generic types (we needed this also to avoid conflicts with other types with the same name), so this is not an issue anymore. Please feel free to reopen if it's necessary for another use case.
