### ISSUE TITLE
Code succinctness: Relax syntax rules for the else branch of an if expression (from Ada 2012)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#63]
# Code succinctness: Relax syntax rules for the else branch of an if expression (from Ada 2012) [12805656] #

**Submitted by Anonymous on 3/4/2016 12:00:00 AM**  
**0 votes on UserVoice prior to migration**  

For the sake of code succinctness, I suggest relaxing syntax rules for the else branch of an if expression in two special cases:
1) When there is no else branch in an if expression and the type of the if expression is inferred to be bool, then the F# compiler should treat the absent else branch as equal to false, type bool (like in Ada 2012 for if expressions).
2) When there is no else branch in an if expression and the type of the if expression is inferred to be option, then the compiler should treat the absent else branch as equal to None, type option.
Now, when there is no else branch written in an if expression, the type of the absent else branch is inferred to be unit, and the F# compiler emits an error: FS0001: This expression was expected to have type unit but here has type... .
New syntax. Example # 1:
[<Measure>]
type GBP
let status = false
// money = None here
let money = if status then Some(100<GBP>)
Example # 2:
let cashAvailable = false
let accountCorrect = true
// status = false here due to cashAvailable = false
let status = if cashAvailable && accountCorrect then true
elif not accountCorrect then false
These changes in the F# language syntax will not affect existing codebase. The if constructs with no else branch are allowed in Java, C#, Ada 2012, C++, VB.NET, just to name a few. I think this syntax will help remove an unnecessary burden from F# users (who have to write "else false", "else None" in their if expressions) and improve succinctness of F# code.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12805656)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12805656-code-succinctness-relax-syntax-rules-for-the-els.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 and we decided against it.  Closing per policy not to revisit issues already decided in previous design iterations
