### ISSUE TITLE
Add Option.ofDefault

### ISSUE THREAD

**Issue by cmeeren** [fsharp/fslang-suggestions#630]
I propose we add a function to the Option module that returns `None` if the input value is the default of its type:

```f#
/// Returns None if the input is equal to the default uninitialized value
/// of its type.
let ofDefault value =
  if value = Unchecked.defaultof<_> then None else Some value
```

This is useful in contexts where you call non-F# code (or non-idiomatic F# code) and need to convert values like `null`, `DateTime.MinValue`, etc. to an Option.

The existing way of approaching this problem in F# is to simply write

```f#
if value = Unchecked.defaultof<_> then None else Some value
```

wherever you need it, or alternatively more specific stuff like

```f#
if value = DateTime.MinValue then None else Some value
```

*Note:* This could also be combined with implementing a corresponding `toDefault` function, which could be useful in the same circumstances but would of course be considered generally unsafe.

## Pros and Cons 

The advantages of making this adjustment to F# are simplicity in using the option type when interfacing with non-F# (and non-idiomatic F#) codebases.

The disadvantages of making this adjustment to F# are, as far as I can see, none, though there may be some caveats with `Unchecked.defaultOf` that I don't know about.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  XS

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
I'm fairly happy with this suggestion. But should it have a companion ``Option.toDefault : 'a option -> 'a``?  

    let toDefault x = match x with None -> Unchecked.defaultof<_> | Some x -> x

That would however be an "unchecked" operation (like ``Array.zeroCreate``)

**Comment by cmeeren** [comment]
Was that a suggestion or a question? Because I already mentioned it in the proposal.

**Comment by dsyme** [comment]
> Because I already mentioned it in the proposal.

@cmeeren Ah yes, I didn't see it! my apologies

**Comment by cmeeren** [comment]
I'm in favor of including `toDefault`. I could see both of these being useful when interfacing with non-F#(-idiomatic) code.

**Comment by realvictorprm** [comment]
Thumbs up! Good idea :-)

Am 06.12.2017 10:28 vorm. schrieb "Christer van der Meeren" <
notifications@github.com>:

**Comment by cmeeren** [comment]
Since `ofDefault` and `toDefault` are more general, perhaps they can deprecate `toObj` and `ofObj`?

Or perhaps `toObj` and `ofObj` could serve as aliases for `ofDefault` and `toDefault`? I'm guessing this would not be a breaking change, though there might be some reflection stuff I don't know about that depends on the `null` type constraint of `toObj` and `ofObj`.

**Comment by enricosada** [comment]
> Since ofDefault and toDefault are more general, perhaps they can deprecate toObj and ofObj?

they cannot. a `DateTime` is not the same as a `Nullable<DateTime>`, and the minvalue is a valid value too.

why `0 |> Option.ofDefault` should be zero? `0` is a valid int.

the only strange case afaik is `DateTime`.

Adding an additional function with a non obvious meaning make things more complicated, not less.

If `DateTime` is the issue (probably is the only one), is possibile to add an extension method to DateTime for that.

**Comment by Rickasaurus** [comment]
Do we really need a special function for something that most people shouldn't do any time? What's wrong with `val |> Option.defaultValue Unchecked.defaultof<_>`?

**Comment by enricosada** [comment]
@cmeeren what is an example of another type who need this?

- `DateTime` because `MinValue`..
- reference types and nullable already work with `null` using `Option.ofObj`

- ... ? other examples? what is your interop scenario?

**Comment by cmeeren** [comment]
`DateTime` and `DateTimeOffset` are the only ones I've needed this for. I agree it doesn't necessarily make much sense for primitive values, but it's relevant for all struct types since they can't be null.

**Comment by voronoipotato** [comment]
Old vb code frequently has default value to mean null, yes its bad and I hate it but this might be helpful for people making the leap from VB.Net to F#.

**Comment by dsyme** [comment]
I think in balance this is rare enough and subtle enough that we shouldn't include it in FSharp.Core.

It can be programmed explicitly by users who need it easaily enough
