### ISSUE TITLE
Open up Microsoft.FSharp.Collections.IEnumerator

### ISSUE THREAD

**Issue by Rickasaurus** [fsharp/fslang-suggestions#633]
# Open up Microsoft.FSharp.Collections.IEnumerator

I propose we allow access to the Microsoft.FSharp.Collections.IEnumerator functions in FSharp.Core

The existing way of approaching this problem in F# is make your own, or nest Seqs which is slower.

## Pros and Cons 

The advantages of making this adjustment to F# are having combinators to cleanly handle IEnumerator

The disadvantages of making this adjustment to F# are that you'd probably have to wrap them in more checks, and maybe want to pull out the shared functionality with Seq so the checks wouldn't be done twice. It also encourages using mutable stuff, but I feel we're way past this being an issue in F#.

## Extra information

Estimated cost (M): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by davidglassborow** [comment]
@Rickasaurus do you have a link to what the Microsoft.FSharp.Collections.IEnumerator functions are ?

**Comment by rmunn** [comment]
@davidglassborow It's found in two files in the F# source: the first one is [`seqcore.fs`](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/seqcore.fs), and the second one is [`seq.fs`](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/seq.fs).

**Comment by Rickasaurus** [comment]
If we wanted to keep away the beginners we could put it in a submodule like Microsoft.FSharp.Collections.Mutable.

**Comment by dsyme** [comment]
@Rickasaurus Why wouldn't we ask users to simply create a separate library for this?  Using IEnumerator directly is not a particularly common use-case, and tends to be quite error prone

**Comment by Rickasaurus** [comment]
For the record I'm just talking about the combinators in seq.fs.

@dsyme I agree it's not frequently used and for good reason but it's in there though, because it's fast and makes for good primitives. These are tried and true features and could be used to make some existing nasty fast code much nicer. 

Sorry for the silly question, but do we have access to OptimizedClosures.FSharpFunc<_,_,_,_>.Adapt and such in libraries?

**Comment by dsyme** [comment]
> Sorry for the silly question, but do we have access to OptimizedClosures.FSharpFunc<_,_,_,_>.Adapt and such in libraries?

Yes

> @dsyme I agree it's not frequently used and for good reason but it's in there though, because it's fast and makes for good primitives. These are tried and true features and could be used to make some existing nasty fast code much nicer.

I'd definitely recommend a separate library for these rather than cracking open more internals and expanding the surface area of FSharp.Core.

**Comment by davidglassborow** [comment]
Also having it as a separate library would make people more aware of the features (I'd never looked at seq.fs before)

**Comment by gusty** [comment]
@Rickasaurus I think it will be a great addition for [F#+](https://github.com/gusty/FSharpPlus)

**Comment by dsyme** [comment]
Closing as we won't open this up in FSharp.Core
