### ISSUE TITLE
SharpFormat

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fslang-suggestions#637]
# Formatting Tool 

I propose we implement a formatting tool which runs either manually or after a successful compilation.

The existing way of approaching this in F# is not existent. 

## Pros and Cons 

The advantages of making this adjustment to F# are that we solve the "Indentation breaks copy and paste" and to appear standardized.

The Elm, Go, Elixir and other communities can tell maybe more about potential Pros.

There is not a single disadvantage, so far as I am concerned. 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
Well, I am a newbie, so this is up to you. 
Fill in whatever you decide to let it cost you ;)

Related suggestions: (put links to related suggestions here)
https://github.com/avh4/elm-format
https://blog.golang.org/go-fmt-your-code

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by enricosada** [comment]
An existing tool already exists, [dungpa/fantomas](https://github.com/dungpa/fantomas)

There is a PR to integrate fantomas in FCS https://github.com/Microsoft/visualfsharp/pull/3542

as a note, this require https://github.com/fsharp/fslang-suggestions/issues/637 to allow to reformat comment in the right location

**Comment by ShalokShalom** [comment]
This is 637? What do you mean with "reformat comment in the right location"?

**Comment by wallymathieu** [comment]
Looks like they have some things that needs to be fixed before merging.

**Comment by ShalokShalom** [comment]
Now I got the sentence.
