### ISSUE TITLE
Add units of measure for standard type aliases

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#64]
**Submitted by Friedrich von Never on 3/5/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

Currently there is a support for `float<cm>`, but not `double<cm>`; I should call it `float32<cm>`. Almost in every other position `float` and `double` are completely equivalent (and some programmers prefer `double` over `float`). Shouldn't it be the case for units of measure support?
Also, it seems that units of measure are not supported for unsigned types at all. Was it a design decision? I suggest adding these.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12814485)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12814485-add-units-of-measure-for-standard-type-aliases.md#comments)

**Comment by pblasucci** [comment]
This can probably be closed now. It was addressed by the work done to address #901
