### ISSUE TITLE
Simplify the build process (even more)

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fslang-suggestions#640]
# Go-like build process

I propose we provide a build process similar to that one in Go.
The existing way of approaching this challenge in F# is to use makefiles (and more). 

## Pros and Cons 

The advantages of making this adjustment to F# are it becomes easier to deploy software.

## Extra information

https://golang.org/doc/articles/go_command.html

I am aware that this means probably a huge task and might even appear as unsuitable for the current implementation. 

The Go resource mentions that this language is designed from scratch to simplify this process which they achieve since its enough to send one single command in order to result in an executable. 

Much fun 😄 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
What specifically did you have in mind?

**Comment by ShalokShalom** [comment]
One command for the deployment.

**Comment by cartermp** [comment]
`dotnet publish -o outputdir -c release` doesn't do that for you on .NET Core? It's just like [go's own command in terms of configuration](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies), it's just that Golang has no notion of a debug build (or a debugger, really) so there's no `-c` switch there.

What kinds of deployments did you have in mind? Is there a specific `go` command which does precisely what you want without any configuration? What is your definition of configuration?

**Comment by ShalokShalom** [comment]
This is new to me, thanks. Why does anyone still write FAKE files?

**Comment by baronfel** [comment]
Even FAKE scripts often call `dotnet build`/`dotnet publish`. There's more around build that just bundling assets. You often have version stamping, building of other, non-code assets like static files, creation and publishing of NuGet packages.

FAKE scripts are often used to consolidate all those other things too. In all of mine the actual `build` part of the script is normally only like 2 lines out of a hundred or so.

**Comment by ShalokShalom** [comment]
Thanks a lot, this is solved.
