### ISSUE TITLE
Remove error FS0597 - allowing for High Precedence Application function invocation

### ISSUE THREAD

**Issue by amieres** [fsharp/fslang-suggestions#644]
Error FS0597
```
Successive arguments should be separated by spaces or tupled, and arguments involving function or method applications should be parenthesized
```

... happens when trying to call a function with a single argument in parenthesis from within a call to another function. Here are some examples and workarounds:
```
printfn "%d"    f()                  // FS0597: clear to humans but compiler complains
printfn "%d"   (f())                 // ok, but too many parentheses, not clean

printfn "%s"    name.ToUpper()       // FS0597: clear to humans but compiler complains
printfn "%s"   (name.ToUpper())      // ok, but too many parentheses, not clean

printfn "%s"    name.Substring(2,4)  // FS0597: clear to humans but compiler complains
printfn "%s"   (name.Substring(2,4)) // ok, but too many parentheses, not clean

let x = -5
let y =  3
printfn "%d"    abs( x + y)          // FS0597: clear to humans but compiler complains
printfn "%d"    abs (x + y)          // ERROR: two separate arguments not one
printfn "%d"   (abs( x + y))         // ok = 2 but too many parentheses, not clean
printfn "%d"   (abs  x + y )         // wrong = 8
abs(x + y)   |> printfn "%d"         // idiomatic, but ...
x + y |> abs |> printfn "%d"         // also idiomatic, but ...
printfn "%d" <| abs( x + y)          // not as clean or clear as: printfn "%d" abs(x + y)
```
This a typical occurrence since functions that receive a single parameter are pervasive in F# and in .Net (usually tupled).

# High Precedence Application

**It is important to know that this request does not change anything on how the language currently works or in the specification of the language.** See more below:

When an identifier is immediately followed by a parenthesis it is called **"High Precedence Application"**(*Section 15.2 FSharp specification*), the compiler already recognizes this and treats it as a special case.
This is what allows us to chain calls to functions, methods and record fields without having to put extra parentheses that would otherwise be necessary: 
```
let v = getName().Trim().ToUpper().Substring(3, 10) 
// instead of
let v = (((getName()).Trim()).ToUpper()).Substring(3, 10)
```

This also means that in F# **whitespaces are already significant**, for example: 
```
let a = getName().Trim() // this is ok
let b = getName ().Trim() // ERROR: The field, constructor or member 'Trim' is not defined."
``` 
Thus **this proposal would not introduce anything new to the language**, no changes whatsoever.

Section _15.2 High Precedence Application_  of the FSharp specification says

> Although the grammar and these precedence rules technically allow the use of high-precedence
application expressions as direct arguments, an additional check prevents such use. Instead, such
expressions must be surrounded by parentheses. For example,
`f e.Meth1(arg1,arg2) e.Meth2(arg1,arg2)`
must be written
`f (e.Meth1(arg1,arg2)) (e.Meth2(arg1,arg2))`

So, as the specification says, an additional check prevents it, there is no technical reason for this to be an error message. It is more like a strongly enforced guideline to (I can only assume) avoid the possible confusion between:
- `f g(n)` 
- `f g (n)` 

which look similar but have different meanings (`f` receives one argument in the former and two in the latter). I think most people would have no trouble seeing the difference between the two cases as it is very intuitive.

I propose we remove it. ~~turn it into a warning so users can use their discretion and decide if they want to:~~
- ~~a) keep it as a warning~~
- ~~b) disable it (using  `#nowarn "0597" or --nowarn 0597`)~~
~~or~~
- ~~c) turn it back into an error (using `--warnaserror+ 0597`).~~

## Pros and Cons 

Pros: 
- Cleaner code with less parenthesis
- Intuitive for newcomers to the language as it is the standard in many languages

Cons:
- None

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

It only requires flagging it as a warning instead of an error.

Related:

https://stackoverflow.com/questions/23848191/why-should-successive-arguments-involving-method-application-be-parenthesized

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by rmunn** [comment]
This suggestion would make whitespace significant:

```fsharp
printfn "%A" abs(5 + 3)  // Has one meaning
printfn "%A" abs (5 + 3) // Has a different meaning
```

I have a feeling that this has already been decided, and that Don Syme's decision was "I won't allow `abs(5+3)` to mean something different from `abs (5 + 3)`." I haven't been able to find *where* that decision was, though, so I'm not surprised that you didn't find it either. :-) But I think this is something that has already been considered and rejected.

**Comment by dsyme** [comment]
I need to double check but by memory the reasoning is called out in the language spec on "high precedence application"

**Comment by amieres** [comment]
Here is another similar "discussion", I suspect that every newcomer to the language has had to grapple with this issue, I know I do every time I'm forced to add the extra parentheses. It breaks the natural elegance and cleanliness of the F# syntax, and it seems so unnecessary: 

https://stackoverflow.com/questions/7556982/high-precedence-application-expressions-as-arguments

I agree with Daniel where he states 
"That doesn't seem like a problem in a language where whitespace is so significant." 

White spaces are a key element of F# syntax and is what makes it so clean and easy to read.
Currently, F# implicitly uses white spaces as parameter separator when identifiers are involved.
This proposal would increase the significance of that role for white spaces.

---

> I won't allow abs(5+3) to mean something different from abs (5 + 3).

Here we need to make a distinction, because even if FS0597 were to be eliminated `abs(5+3)` would still mean the same as `abs (5 + 3)`, what would change is that `f abs(5+3)` would mean something different to `f abs (5 + 3)`, and that is exactly the proposal that I feel needs to be considered.

Note that the fact that `f abs(5+3)` is different to `f abs (5 + 3)` would not lead to programmer's confusion because eventually the compiler would solve any ambiguity with the message `This value is not a function and cannot be applied.`.

**Comment by amieres** [comment]
Section 15.2 High Precedence Application

says

> Although the grammar and these precedence rules technically allow the use of high-precedence
application expressions as direct arguments, an additional check prevents such use. Instead, such
expressions must be surrounded by parentheses. For example,
`f e.Meth1(arg1,arg2) e.Meth2(arg1,arg2)`
must be written
`f (e.Meth1(arg1,arg2)) (e.Meth2(arg1,arg2))`
 

It mentions the additional check (FS0597) but there is no explanation or reasoning for it. 
I think we should evaluate Pros and Cons and gauge the opinion of the people. 
I understand that depending on a persons background they may see it differently, those that come from languages like Ocaml or Haskell may naturally interpret `f g(5)` as f called with 2 parameters where as those from imperative languages would interpret it as f called with 1 parameter. But then again maybe not, maybe naturally most people would interpret it as the latter.

**Comment by matthid** [comment]
> I understand that depending on a persons background they may see it differently, those that come from languages like Ocaml or Haskell may naturally interpret f g(5) as f called with 2 parameters where as those from imperative languages would interpret it as f called with 1 parameter.

Yes that. I think it is good to have FS0597 as either interpretation is bogus for some people.
Also it is inconsistent for the following code:

```fsharp
let f a b c d = a + b + c + d;;
f (12)(1)(4)(3);;
// val it : int = 20
```

Where "no space" means multiple arguments. What about function calls returning a function? Should that continue with `f e.Meth1(meth1)(meth2)`.
And also I don't want people to use tupled args in the language just to use this new "design".

**Comment by amieres** [comment]
> What about function calls returning a function? Should that continue with `f e.Meth1(meth1)(meth2)`.

It would not continue, according to the definition of "High Precedence Application":
"identifiers that are followed immediately by a left parenthesis without intervening whitespace"
So the second parenthesis does not fall in that case and is interpreted as another parameter.

> I don't want people to use tupled args in the language just to use this new "design".

I guess that is a "danger" that depends on individual preference. In any case that should be addressed with a style guideline: http://fsharp.org/specs/component-design-guidelines/

**Comment by matthid** [comment]
> So the second parenthesis does not fall into that case and is interpreted as another parameter.

Yes my argument is that this is inconsistent, so the same syntax means different things - even if the types are matches - just because of different syntax elements.

> I guess that is a "danger" that depends on individual preference.
In the end that is what FS0597 seems to boil down to: a preference in coding style.

I like F# a bit because it guides the code-style. So it should be a design decision and not left to users entirely (at least such consideration is important here)

**Comment by amieres** [comment]
Alternatively FS0597 could be turned into a warning, that way people could decide if they want to disable it using (`#nowarn "0597"` or `--nowarn 0597`) or turning back into an error using (`--warnaserror 0597`).

That way, instead of an imposition it would be more of a suggestion.

**Comment by amieres** [comment]
I have made several changes to the original proposal to clarify and address the concerns expressed in the commentaries.

**Comment by amieres** [comment]
I would like this proposal to be reconsidered in view of the new facts obtained. I think it is a worthy proposal and should be non controversial as it does not change anything at all in how the language works and just allows for a cleaner syntaxis with less parenthesis.

**Comment by dsyme** [comment]
@amieres Just to mention that there's a strong bias in the language design (and likewise in other languages) against optional features which effectively turn the language into a slightly different language ("bifurcate the language").  

There are many social reasons  for avoiding such optional features - e.g. when you code review code, or have two programmers meeting in a team and having to decide on standards - it's one thing to have to decide on coding conventions and design idioms, it's another to have to turn the knobs and dials on the language to select what's allowed.

I should mention this in the guidelines in the readme

**Comment by dsyme** [comment]
OK, added some text on that, see https://github.com/fsharp/fslang-suggestions/commit/91f2d591da608a58c4db5ba715de1e36ac01711e

**Comment by amieres** [comment]
Would a change like this turn the language into a slightly different language?
Seems like such a minor change.

> turn the knobs and dials on the language to select what's allowed.

There are two knobs here `nowarn` and `warnaserror`, they already exist.
I wonder how many would use the second one.
Should I not mention them in the proposal?

**Comment by amieres** [comment]
So, should I rename the proposal back to: "Remove error FS0597"?

**Comment by zanaptak** [comment]
I am in favor of allowing high precedence application (HPA) in argument position, which seems to be the original request here. (Barring that, as a second choice I would also support at least changing it from an error to a warning.)

I do not find the counter-arguments about whitespace significance or confusion to be convincing. Argument spacing is already significant with respect to chaining. And there is current inconsistency based on whether we are in argument position and whether we are chaining a property or method (`name.Length` works in argument position, `name.Trim()` doesn't). This inconsistency was confusing to me initially and still trips me up from time to time, and I feel it is a worse state of inconsistency/confusion as-is than any potential confusion over HPA.

It seems to me the supposed confusion primarily arises around what would be considered poorly-written code. That is, it occurs when curried arguments are applied without spaces, which does not seem to be the recommended style. The F# style guide [recommends spaces in function definitions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#surround-function-arguments-with-white-space) (I didn't see a corresponding recommendation about application but I assume it's the same) and I don't see much example code that omits spaces between arguments. So, applying HPA seems like it would inconvenience some edge case code that is discouraged anyway, and would convenience many more common/natural scenarios like method calls.

I also think I've observed in recent times that there has been more emphasis on conveying the suitability of F# for things like object programming, interoperability with C#/.NET libraries, and attracting newcomers from other languages. I feel HPA is the better default for all of those. Object programming and C# mean lots of methods, and it is annoying and feels clunky to have to frequently add extra parentheses around method calls. My intuition is also that newcomers would predominantly expect HPA to apply. [This comment about a user study](https://github.com/dotnet/fsharp/issues/5475#issuecomment-488773890) is I think very strong evidence of this.

**Comment by cartermp** [comment]
> And there is current inconsistency based on whether we are in argument position and whether we are chaining a property or method (name.Length works in argument position, name.Trim() doesn't).

Hmm, I don't find this inconsistent, just that the modality of `()` can look and feel a little different:

* `()` is a value being passed to an argument
* `()` signifies a function or method invocation

Even though these two things _are_ the same, they can often feel different. And that's where I think people get tripped up. I don't think that has to do with accessing a property though.

FWIW I'd be in favor of deprecating this behavior, since it is confusing. In some cases we now have a quick fixer that'll add the parentheses, but the best tooling is "no tooling needed", after all!

**Comment by amieres** [comment]
Thank you @zanaptak, I think is worth bringing the referenced comment:
> cartermp commented on May 2, 2019
>
> Some notes after doing some user studies and seeing this come up multiple times:
> ...
> printfn "%s" arg.Reverse()
>
> Also hugely confusing for people, so far not a single person was able to deduce that they needed to wrap with parentheses

**Comment by dsyme** [comment]
I'm grateful for the feedback on this, however I don't see any fundamental reason here to revist the original decision on this.  

See for example explanation here: https://github.com/fsharp/fslang-suggestions/issues/644#issuecomment-362566818
