### ISSUE TITLE
SRTP compiler errors messages 

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fslang-suggestions#646]
# Title of Suggestion

I propose we improve the messages for SRTPs

## Pros and Cons 

Estimated cost (XS, S, M, L, XL, XXL): 
M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [] I or my company would be willing to help implement and/or test this

Copied from Slack channel:

SRTPs tend to break sometimes at totally unexpected places with very weird compiler error. I had some code like this not long ago

```
x
|>> doSomething a b
|> doSomethingElse c d
>>= againSomethingDifferent
>>= SomeOtherCall d
|>> preFinalCall e f
|>> finalCall g
```

which broke with some strange error
Only when I split up that piping into

```let y = 
  x
  |>> doSomething a b
  |> doSomethingElse c d
  >>= againSomethingDifferent

y
>>= SomeOtherCall d
|>> preFinalCall e f
|>> finalCall g```

2 sub expressions it compiled.

**Comment by gusty** [comment]
For that particular case I would prefer to get mini-repro because it might be a limitation of the compiler itself, then instead of adding a specific error message I would try to fix the compiler.

**Comment by ShalokShalom** [comment]
So should we move this error?

**Comment by robkuz** [comment]
@ShalokShalom I am on the same page as @gusty here. This for sure looks more like a compiler bug than anything else

**Comment by realvictorprm** [comment]
Unfortunately this is the wrong place, please move this to the visualfsharp repository and close this issue @ShalokShalom. Thank you :-)

**Comment by ShalokShalom** [comment]
I opened it here: https://github.com/fsharp/fsharp/issues/824

@robkuz Would be awesome if you could provide the details. 
Sorry for jumping in, wanted to avoid that this gets lost. 

Paste me the info where ever you want.

**Comment by realvictorprm** [comment]
Thanks for engagement @ShalokShalom :-)
