### ISSUE TITLE
Extensible unions

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#647]
This is to record one idea with regard to extensible unions and polymorphic variants.

Let's imagine we have an app with multiple components which exchange messages (e.g. navigation).  There are various approaches to this but all involve having the components combined their messages into one overall message type, e.g.

```fsharp
module Part1 = 
    type Msg = | Load | Save | GoToPart2
    let init ... = ... 
    let update ... = ... 
    let view ... = ... 

module Part2 = 
    type Msg = | Login | Logout | GoToPart1
    let init ... = ... 
    let update ... = ... 
    let view ... = ... 
```
It is common that a combined message type has to be composed from these, e.g.
```fsharp
module App = 
    type Msg = Page1 of Page1.Msg | Page2 of Page2.Msg
    let init ... = ... 
    let update ... = ... 
    let view ... = ... 
```
The book keeping with projecting in/out of the combined messages type can be non-trivial.

One alternative might be to explicitly allow extensible **nominal** union types, extensible within a single assembly so:

```fsharp
type Msg = | ... // The ... indicates an extensible union type

module Part1 = 
    type Msg with | Load | Save | GoToPart2
    let init ... = ... 
    let update ... = ... 
    let view ... = ... 

module Part2 = 
    type Msg with | Login | Logout | GoToPart1
    let init ... = ... 
    let update ... = ... 
    let view ... = ... 
```
In this case there is no need to make a combined messages type.  Somehow this is just much simpler with less structural burden in composition.

That said, such a feature has many technical challenges. Here are some notes:

* The labels `Part1.Load`, `Part2.Login` etc. would be distinct.  One label from one module would not be the same as another label in another module even if they have the same name. The declaration of a new union case would thus be generative (anonymous union labels would be a separate issue)

* There is the (important-but-technical) question of when/if checks for exhaustiveness in pattern matching can be made.  Neither Part1.update nor Part2.update would process all message types.  The question is whether the type system would track which message types they do process, and if there is any way of sealing the extensible union type.  For example, one could consider all union types sealed at the assembly boundary

* Related to this is whether it is possible to select out a subset of messages in a match.  For example, I could see people wanting to write

```fsharp
module App = 
    type Msg with | Reload
    let update msg state = 
        match msg with 
        | Part1._ -> Part1.update msg state
        | Part2._ -> Part2.update msg state
        | Reload -> originalState
 ```

## Pros 

Pro: It results in fairly intuitive code. The other alternative is to do composition manually.  However this can be tedious.

Con: it's a non-trivial feature

Pro: The `with` syntax is fairly natural form of type extension, and that most parts of the implementation would be straight-forward.

Con: There is no corresponding feature for record extension, e.g.

```fsharp
type Model = { ... } // ... indicates extensible record type

module Part1 = 
    type Model with { Document: string }
    let init() = { Document = "def.txt" } // would this be allowed? It only partially initializes a record!?  What would it compile to?

module Part2 = 
    type Model with { User: string }
    let init() = { User = "abc" } // would this be allowed? It only partially initializes a record!?  What would it compile to?

module App = 
    let init = { Part1.init(); Part2.init() } // what would be allowed here?
 ```
And as soon as you start thinking about extensible records, there are a vast number of issues that come into play, esp. with the relationship to the object system, anonymous records etc.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XL

Related suggestions: (put links to related suggestions here)
* https://github.com/fsharp/fslang-suggestions/issues/40
* https://github.com/fsharp/fslang-suggestions/issues/538
* https://github.com/fsharp/fslang-suggestions/issues/606
* https://github.com/fsharp/fslang-suggestions/issues/121

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Rickasaurus** [comment]
I'm probably not being all that imaginative, but I can't think of where I would have used this if it had been available. How would methods and properties work on such a thing? Would it be possible to make use from C# reasonable? How would you ensure that all of the namespaces/modules are open and covered for a given message you might receive? 

Extensible record types, now there's a feature I would use the crap out of :).

**Comment by ReedCopsey** [comment]
I've found that building the "combined message types" is almost never as straightforward as this example in practice. In reality, the update that handles the combination of messages typically isn't trying to expose _all_ of the "submessages", but rather handle some, map some to some other type, and pass through some to the parent levels.

My worry is that this will lead to exposing more than should be exposed, as it makes it easier to just expose everything in the top level union type vs selectively exposing what needs to actually be there - in other words, this seems like a common "lead to a pit of failure vs pit of success" feature.

> There is the (important-but-technical) question of when/if checks for exhaustiveness in pattern matching can be made.

If there isn't a way to handle exhaustiveness, this would be a big 👎 from me. A huge benefit of elmish and similar designs, which seems to be the inspiration for this, comes from exhaustive message type checking in the update functions.

**Comment by cartermp** [comment]
Are typical Elmish (or message-based UI) apps constantly duplicating labels in message types?

**Comment by ReedCopsey** [comment]
It definitely seems pretty common to do. Navigation related things are definitely a good example - navigation, almost by definition, has to be handled in an abstraction layer "outside" of the piece creating the message - so the layer above can coordinate between the pieces it manages. This tends to mean that messages have to get propagated upwards frequently, and you get this type of scenario.

In Gjallarhorn, I separated out the navigation into a separate set of messages (so it's not part of the normal update loop, and can be handled platform specific), which helps - but before I was doing that, I found myself doing what Don's describing frequently. 

That being said, I would find that each "layer" would not map _all_ of the messages from subcomponents up, which is where I worry that this will end up abused. This feature would make it far easier to expose all of the messages from every subcomponent vs selectively mapping things upwards, which has the disadvantage of bloating the API as well as exposing things that really should stay hidden.

**Comment by dsyme** [comment]
Yes, it's absolutely navigation messages/commands between composed components in the Elmish samples (both Fable and Elmish.XamarinForms) I've been looking at that motivate this.  The addition of explicit navigation messages adds complexity. 

For a Fable example, if you look at https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/pages/WishList.fs#L100 then the tiny `f` parameter and the `Cmd.map f` are there to embed the WishList messages into larger message/command types.  The `update` function thus becomes generic.  It's a form of manual column polymorphism. 

Likewise [here](https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/pages/Login.fs#L66) the `f` and `onSuccess` parameters explain to the component's update function how to talk to the rest of the application in terms of the composed message/command types.  It's a clever pattern but may be counter-intuitive.

Similar things happen in Elmish.XamarinForms.

I agree with most of @ReedCopsey's concerns - exhaustiveness matching is key - and the feature quickly leads to having the logic of the type system understand subsets of tags, which will lead to complex types.

**Comment by cartermp** [comment]
Okay, so I think I agree with this in principle given that there are actual duplication problems that people experience in the real world. I do wonder if this could result in a little bit of abuse by creating mega-update functions, but I suppose that's better than the current way to do it in Elmish with `Cmd.map f` at the end in just one place so that it can conform to the rest of the function.

I generally feel that a little duplication is fine, but given that it leads to this and what @dsyme mentioned it seems like a good change. Exhaustiveness does seem like a requirement for this, though.

**Comment by dsyme** [comment]
> I suppose that's better than the current way to do it in Elmish with Cmd.map f at the end in just one place so that it can conform to the rest of the function.

Oh, I'm not at all sure it's better :)

**Comment by kspeakman** [comment]
I like the idea behind this. Here are the places I can think of where Msg is used (to examine what it would be like to use this):

* from Init, effects which generate a msg
* from Views, where UI elements trigger them
* from Updates where messages are handled,  and effects which may generate a msg
* in all of these cases, messages may be issued to local, parent, or siblings

Regarding mega-update functions, that is already a common tactic. In the current state of things you choose your annoyance between: a) abstraction friction like maintaining msg mapping code (and implement an OutMsg pattern for msgs to other "components") or b) one Msg with cases like `[Section]ThingHappened` and Ctrl-F to find things in your update function. A helper function (lens) per section makes the latter quite usable and straight-forward, but cluttered.

This proposal could be a mitigation for both tactics. Reducing mapping and allowing mega updates to be split.

**Comment by dsyme** [comment]
Some more thought on this

There has already a suggestion to add adhoc structural type-tagged union types where
* each type of (A|B|C|...) is distinct and non-overlapping, e.g. 
* such types are erased to `object`
* Introducing such a union value would need to be either explicit (e.g. using some new operator like `Typed`) or type-directed or both

See https://github.com/fsharp/fslang-suggestions/issues/538 for original proposal. e.g. this would allow some or all of these:

    let generateValue1 () : Typed(int | string)) = if Monday then 2 else "4"

    let generateValue2 () = if Monday then Typed 2 else Typed "4"

    let eliminateValue (x : Typed(int | string)) = ...
        match x with 
        | :? int as i ->  ...
        | :? string as s -> ...
    let eliminateValue2 x = ...
        match x with 
        | Typed(i : int) ->  ...
        | Typed(s; string) -> ...
    type Allowed =  Typed(int | string)


Such a construct already has utility in the context of Fable, since it corresponds pretty closely to Typescript unions and how JS treats values.  It also has lots of applications in F# programming, especially if the use of `Typed` can be inferred in many cases.

Now, this construct automatically gives a structural union message type , e.g.

    type MsgA = MsgA of int * int
    let update1 () = Typed (MsgA (3,4))

    type MsgB = MsgB of int * int
    let update2 () = Typed (MsgB (3,4))

    val update1 : unit -> Typed MsgA 
    val update2 : unit -> Typed MsgB

and a combination of update1 and update2 would give

    let update = combine update1 update2 

    val update : unit -> Typed (MsgA | MsgB)

Column-polymorphism would likely be needed. 

The context is that one pattern in Elmish is to have a closed model of internal messages and a more open model of external messages.  For example:

```
let External x = Typed x
module MyPage1 = 
    type Model = { State: string }
    type Msg = A | B
    type Logout = Logout
    type Login = Login of string

    let update msg model = 
        match msg with 
        | A -> { model with State = "A" }, External Logout
        | B -> { model with State = "B"}, External (Login "user")

module MyPage2 = 
    type Model = { State: string }
    type Msg = C | D
    type AddToCart = AddToCart of string
    type RemoveFromCart = RemoveFromCart of string

    let update msg model = 
        match msg with 
        | C -> { model with State = "C" }, External (AddToCart "c")
        | D -> { model with State = "D"}, External (RemoveFromCart "d")
```
where the external messages indicate the unreconciled external actions that are to do with other components in the larger application.  It's these external messages that are particularly prone to be unioned on composition (the others are completely internal)

The type system would of course track which components introduced which "external" messages and would keep these external messages distinct (if each component chooses to declare a distinct type for each external message), and check that all the different external message types have been reconciled/eliminated during composition.

(You can already do this today with multiple external message types, you just have to manually compose/eliminate)

As an aside, this would also motivate an even shorter syntax for introducing single-case tagged unions
```
let External x = Typed x
module MyPage1 = 
    type Model = { State: string }
    type Msg = A | B
    type Logout
    type Login of string

    let update msg model = 
        match msg with 
        | A -> { model with State = "A" }, External Logout
        | B -> { model with State = "B"}, External (Login "user")

module MyPage2 = 
    type Model = { State: string }
    type Msg = C | D
    type AddToCart of string
    type RemoveFromCart of string

    let update msg model = 
        match msg with 
        | C -> { model with State = "C" }, External (AddToCart "c")
        | D -> { model with State = "D"}, External (RemoveFromCart "d")
```

Anyway, the point is that an open type-tagged union construct gets you what you need here, and is a well-known language construct corresponding to what other languages already have, and has wide utility.

**Comment by boloutaredoubeni** [comment]
It's already possible to extend DU's by having them implement a common interface and match over that interface. Maybe we should add syntax to make them easier to use?

```fsharp
type ImAnInterface = interface end

type T1 = A | B of int interface ImAnInterface

type T2 = B of int | C | D of int interface ImAnInterface

let f (t: ImAnInterface) =
    match t with
    // | T1.B | T2.B -> ()
    | :? T1 as t ->
        match t with
        | T1.B _ | _ -> ()
    | :? T2 as t ->
        match t with
        | T2.B _ | _ -> ()
    | _  -> ()

let (|T1'|_|) (t: ImAnInterface) =
    match t with
    | :? T1 -> Some (t :?> T1) 
    | _ -> None

let (|T2'|_|) (t: ImAnInterface) =
    match t with
    | :? T2 -> Some (t :?> T2) 
    | _ -> None

let g (t: ImAnInterface) =
    match t with
    | T1' (T1.B _)
    | T2' (T2.B _) -> ()
    | _ -> ()

/// Possible syntax?
let h (t: ImAnInterface) =
    match t with
    | ?T1.B _ | ?T2.B _ | _ -> ()
```

**Comment by jwosty** [comment]
@boloutaredoubeni I don't know if that'd lead to very good code. I try to avoid runtime casts/typechecks as much as possible, as a static solution would be far better (performance wise, AND static analysis-wise). I don't think we should be helping people write that code.

Though I can't think of another alternative.

**Comment by dsyme** [comment]
Closing this in favour of https://github.com/fsharp/fslang-suggestions/issues/538

**Comment by jwosty** [comment]
For what it's worth, OCaml has extensible unions (https://v2.ocaml.org/manual/extensiblevariants.html). I'm not sure that anonymous type-tagged unions are entirely equivalent; perhaps something like anonymous name-tagged unions would be closer?

I think it still wouldn't quite be equivalent though, since full-blown extensible variants allow for a level of dynamism due to the fact that it's truly more like an OO hierarchy (open subtyping) - for example a plugin system. However the downside in OCaml's version (from what I can tell) is the need to always have a wildcard case. It would be really awesome if someone devised a system where that isn't always necessary, but that may be a very large task.

**Comment by abelbraaksma** [comment]
This was not completed, but closed as duplicate, fixing state.
