### ISSUE TITLE
Make tuple defined DU cases more consistent with tuple

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#65]
# Make tuple defined DU cases more consistent with tuple [12820011] #

**Submitted by Gauthier Segay on 3/5/2016 12:00:00 AM**  
**9 votes on UserVoice prior to migration**  

It is possible to pattern match tuples in a flexible way:
let a = 1,2
match a with
| 1, _ -> ()
| _ -> ()
but it's not possible to do this on tuple defined DU cases, one has to write this:
match pat with
| SynPat.LongIdent(_, _, _, _, _, _) -> ()
| ...
which breaks whenever the case definition change (even at place where we don't care of the contents)
while supporting this would be friendlier / more resilient to DU case change:
match pat with
| SynPat.LongIdent _ -> ()
or even
match pat with
| SynPat.LongIdent foo -> () // can deconstruct foo like a normal tuple

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12820011)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12820011-make-tuple-defined-du-cases-more-consistent-with.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 and we decided against it.  Closing per policy not to revisit issues already decided in previous design iterations
