### ISSUE TITLE
Add iter, iterError, contains, and orElse to the Result module in FSharp.Core

### ISSUE THREAD

**Issue by boloutaredoubeni** [fsharp/fslang-suggestions#650]
# Add iter, iterError, contains to the Result module in FSharp.Core

I propose we add iter, iterError, contains, orElse and orElseWith to the Result module in FSharp.Core to increase feature parity with the Option module

The existing way of approaching this problem in F# is implementing it manually

```fsharp
let iter action = function Ok x -> action x | Error _ -> ()

let iterError action = function Error e -> action e | Ok _ -> ()
```

## Pros and Cons 

The advantages of making this adjustment to F# are that we have library functions to iterate over the Result type and check the contents of a Result value.

Some cons, some functions in the Option module don't mean the same thing when translated to the Result module. 
## Extra information

Estimated cost (*XS*, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)
#623 
## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x] This is not a breaking change to the F# language design
* [ x] I or my company would be willing to help implement and/or test this

**Comment by jwosty** [comment]
What would the signatures for orElse and orElseWith be?

**Comment by jwosty** [comment]
Also, I’d rather call “contains” something else, like “is”

**Comment by boloutaredoubeni** [comment]
This is what I had in mind

```fsharp
[<CompiledName("OrElse")>]
val orElse: ifError:Result<'T, 'TError> -> result:Result<'T, 'TError> -> Result<'T, 'TError>

[<CompiledName("OrElseWith")>]
val orElseWith: ifErrorThunk:(unit -> Result<'T, 'TError>) -> result:Result<'T, 'TError> -> Result<'T, 'TError>
```

**Comment by gusty** [comment]
The signature for `orElse` is not a mystery but what is not that obvious is how it would behave when both arguments are Errors:


1. Takes the first error
2. Takes the last error
3. Combine both errors

`1` and `2` seems to be very arbitrary and unusable at the same time.
`3` it's the most appealing but it requires an operation to combine both errors, the most obvious is `(+)` which also makes me think that a variant of `orElse` could take a combine function as an argument and the fisrt name for that function that comes to my mind is `orElseWith` :)

**Comment by abelbraaksma** [comment]
@gusty, from the semantics of the words 'or else', it implies for me 'take the first if it's not an error, or else, take the second', which implies that the second is not inspected at all. It's similar to the 'orElse' on options, I think.

**Comment by abelbraaksma** [comment]
@gusty, for me, the 'or' applies to the first argument. If it's an error, it's ignored and the second argument is taken. I find that semantically sound. 

Though I do understand your point as well. A typical map would probably do the opposite, and keeps the first (if it's an error, the map doesn't execute further). But then the 'or' would have no meaning. For me, orElse translates to 'take me if I'm not an error, or else take the other and ignore me'. 

Maybe another name could make this clearer?

**Comment by gusty** [comment]
Ok, I see your point.

I'm thinking more on different scenarios, normally you can define a function like `Result.choose`, based on `orElse` so you can select between many alternatives from a list.

In many cases it might be a but unexpected to take the last error, imagine a Validation, normally you want to see the first thing that failed, not the last.

But since your point is also valid, it's not clear which was is the right way.

**Comment by dsyme** [comment]
I'm not that keen on adding these to FSharp.Core, partly because I don't think code that uses these functions is particularly clearer than explicit matching.
