### ISSUE TITLE
Pattern matching enums: print names of enum cases that are not covered by a pattern match

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-suggestions#654]
# Pattern matching enums: print names of enum cases that are not covered by a pattern match

(related to but not to be confused with #652)

I propose that when matching over an enum, the incomplete pattern match warning message should include the name of the example enum case that is not covered by the match when possible. Currently, the compiler behaves like so:

```fsharp
type MyEnum = | A = 0 | B = 1
let f =
    function
    // warning FS0025: Incomplete pattern matches on this expression. For example, the value 'enum<MyEnum> (1)' may indicate a case not covered by the pattern(s).
    | MyEnum.A -> "A"
```

In a case like this, the compiler should say "For example, the value `MyEnum.A` may indicate a case not covered by the pattern(s)." This proposal does not touch the message produced when the example value does not fall within the enum's set of values. This message is much clearer and should not be too difficult, provided the work I have been doing to implement #652.

## Pros and Cons 

Pros: Better compiler warnings.

Cons: None. It's all sunshine and rainbows for this one

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by realvictorprm** [comment]
We need more suggestions with those cons :D!

Am 15.03.2018 6:06 vorm. schrieb "John Wostenberg" <notifications@github.com

**Comment by TIHan** [comment]
There are cons to this: **It's work**. :)

**Comment by jwosty** [comment]
@Tihan well yeah, but it’s trivial work :) besides, I feel like saying that is slightly pointless because everything is work

**Comment by jwosty** [comment]
*closed because this is merged*
