### ISSUE TITLE
Hide Obsolete warnings on record initializer not using the obsolete field.

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#66]
**Submitted by Matthias Dittrich on 3/6/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

Basically the compiler emits a warning even when a obsolete field is not used directly in the source code. Here is a code example showing what I mean:

``` fsharp
type TestRecordV2 =
    { Field1 : string
      [<Obsolete("Use Field2 instead")>]
      Feild2 : string }
    static member Emtpy =
      { Field1 = null
        Feild2 = null }

let v2var1 = { TestRecordV2.Emtpy with Field1 = "field1" } // no warning should be reported!!
```

**Comment by dsyme** [comment]
This seems a reasonable change.

**Comment by Happypig375** [comment]
The funny thing is, the code will still need to be updated to change `Emtpy` to `Empty`.

**Comment by edgarfgp** [comment]
@dsyme is this ```approved-in-principle``` as has been labeled as ```good-first-issue```?

**Comment by dsyme** [comment]
@edgarfgp It's basically just a bug fix tbh, should be easy to do, doesn't need language design tracking (even if I said before it does), could be tracked in dotnet/fsharp.

**Comment by dsyme** [comment]
@edgarfgp I'm trying to cut down the approved-in-principle a bit - there are quite a few "little niggle" issues that have been labelled that way.  It's hard to do though, I think I've reached the limit.

**Comment by edgarfgp** [comment]
Thanks for doing this . Will help a lot when trying to find one to work on

**Comment by cartermp** [comment]
@dsyme do you have permissions to transfer between orgs to dotnet/fsharp? I'd prefer to have this tracked there than here if it's going to be considered a bug,

**Comment by vzarytovskii** [comment]
> @dsyme do you have permissions to transfer between orgs to dotnet/fsharp? I'd prefer to have this tracked there than here if it's going to be considered a bug,

I don't think it's possible cross-org, is it?

**Comment by dsyme** [comment]
Given the PR has already been submitted we can close this here
