### ISSUE TITLE
Put access specifier before member keyword

### ISSUE THREAD

**Issue by moonPtr** [fsharp/fslang-suggestions#664]
Personally I find [static] member [access] quite awkward to read and write, I would like to propose changing the syntax to [access] [static] member and/or [static] [access] member as it's less awkward and also easier to remember for people coming from C# / Java / etc

**Comment by smoothdeveloper** [comment]
The compiler gives a reasonable error message:

> Accessibility modifiers should come immediately prior to the identifier naming a construct

Also, in F# there is only a single place the visibility modifier comes (before the identifier) which enforces consistency while in C# / Java those can be intermixed.

Isn't it better to have only a single way so long the error message points to it?

**Comment by rmunn** [comment]
It would be nice if F# tooling could offer a quick fix (i.e., the light bulb icon) for this, which would automatically reorder `internal member this.Foo` to `member internal this.Foo`.

**Comment by realvictorprm** [comment]
Funnly allowing this wouldn't require many changes 😄 
Besides... I think this is definitely personal preference.
