### ISSUE TITLE
Don't require a space before SRTP type parameter

### ISSUE THREAD

**Issue by moonPtr** [fsharp/fslang-suggestions#668]
![image](https://user-images.githubusercontent.com/32428601/39529555-43ea60ee-4e27-11e8-8f94-7f1a386c4f3d.png)

This makes a space between the opening angle bracket and the type variable necessary, which is inconvenient at best, ugly at worst.

(Was told to move this here from https://github.com/Microsoft/visualfsharp/issues/4794)

**Comment by abelbraaksma** [comment]
I thought I had this reported as bug somewhere but I can't find it back. I think the F# spec actually allows this syntax, but the parser sees `<^` as operator. Also, I thought there was an issue on allowing the type parameters on multiple lines, but without the impossibly wide indenting (must be after `<`.)

I'd certainly welcome this if this syntax is going to be allowed.

**Comment by realvictorprm** [comment]
It's a miialbug or issue, would it be possible to get a decision on this?

**Comment by abelbraaksma** [comment]
@dsyme, @cartermp, any thoughts on this? Should this be moved and reclassified as a bug instead of a lang suggestion?

**Comment by cartermp** [comment]
I see this primarily as a compiler bug, since we _should_ be able to disambiguate between a type definition and an operator usage, but I'm not sure how feasible that is.

**Comment by dsyme** [comment]
I'm fine with someone fixing this.  I regard it as a glitch in the language definition (but it's in there and thus by design) which could be improved.

**Comment by abelbraaksma** [comment]
@dsyme if you still agree, could you tag this approved-in-principle? Maybe someone will pick it up and open a PR.

**Comment by cartermp** [comment]
RFC is written.

**Comment by abelbraaksma** [comment]
For ease of browsing, it's here: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1083-srtp-type-no-whitespace.md

**Comment by Happypig375** [comment]
Also there is
```fs
Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> {|T=typeof<int>|};;

  {|T=typeof<int>|};;
  ----------------^

stdin(39,17): error FS0010: Unexpected symbol '}' in expression

> [|typeof<int>|];;
val it : System.Type [] =
  [|System.Int32
      {Assembly = mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;
       AssemblyQualifiedName = "System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089";
```
(Output below omitted)

**Comment by edgarfgp** [comment]
@vzarytovskii i think this will by https://github.com/fsharp/fslang-suggestions/issues/1151

**Comment by vzarytovskii** [comment]
I think this is covered in IWSAMs @dsyme

**Comment by abelbraaksma** [comment]
@vzarytovskii there was actually an RFC for this: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1083-srtp-type-no-whitespace.md.

Maybe we should update that with a link to the implementation, as being part of the awesome #1151 work. I didn't check if this also solves the issue by @Happypig375 [above](https://github.com/fsharp/fslang-suggestions/issues/668#issuecomment-868341303), which is related, but not the same.

**Comment by abelbraaksma** [comment]
@vzarytovskii I've prepared marking this completed: https://github.com/fsharp/fslang-design/pull/714.
