### ISSUE TITLE
allow "use _ = ..." 

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#67]
**Submitted by Gauthier Segay on 3/7/2016 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

In C#, one can use using(CreateSomeDisposable()) without binding the expression to a name.
Same construct in F# is not allowed, forcing a workaround such as

```
use __ = CreateSomeDisposable()
```

allow to make it like this:

```
use CreateSomeDisposable()
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12838449)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12838449-allow-use-to-not-bind-the-expression-to-a-name.md#comments)

**Comment by dsyme** [comment]
Thanks for the suggestion.  We won't be making this specific change in F#

I'm ok with the current language design forcing the use of a valid identifier, and encouraging things like ``use _disposer = ...``
