### ISSUE TITLE
Remove warning about explicit type parameters when it's a single one

### ISSUE THREAD

**Issue by gusty** [fsharp/fslang-suggestions#672]
I propose we remove this warning when there is only one type parameter (which is in my experience 95% of the cases) :

    warning FS0686: The method or function 'myFunc' should not be given explicit type argument(s) because it does not declare its type parameters explicitly

Here's a small sample code demonstrating some scenarios where this problem is encountered

    open System
    let inline f s x = match x with true, value -> Ok value | _ -> Error (sprintf "Not a valid %s" s)

    type TryParse = TryParse with
        static member ($) (_:decimal, TryParse) = Decimal.TryParse >> f "decimal" : _ -> Result<decimal, string>
        static member ($) (_:float  , TryParse) = Double.TryParse  >> f "float"   : _ -> Result<float  , string>
        static member ($) (_:int    , TryParse) = Int32.TryParse   >> f "int"     : _ -> Result<int    , string>

    let inline tryParse (x: string) : Result<'t, string> = (Unchecked.defaultof<'t> $ TryParse) x

    let x : Result<int, string> = tryParse "5"
    // but it's shorter to write ...

    let y = tryParse<int>
    // ~vsD980.fsx(14,13): warning FS0686: The method or function 'tryParse' should not be given explicit type argument(s) because it does not declare its type parameters explicitly

The existing way of approaching this problem in F# is either to add explicit type parameters at the definition which sometimes becomes really tricky,

    // this doesn't even compile
    let inline tryParse2< ^t  when ( ^t or TryParse) : (static member ( $ ) :  ^t * TryParse ->
                                                      string ->
                                                        Result< ^t,string>)> (x: string) : Result< ^t,string> = (Unchecked.defaultof<'t> $ TryParse) x

... or at client code add the corresponding nowarn, but it will also remove the warning for functions with more than one type argument, and it's also a bit annoying having to ask the client of the code to add a nowarn.

The advantages of making this adjustment to F# are: this warning is very useful when functions with more than one generic parameter are not declaring them explicitly, so it's easy to get them in the wrong order. But if there is only one generic parameter there's no point in showing this warning.

The disadvantages of making this adjustment to F# are ... I can't think of any disadvantage, I don't think it's too much work, I think I can submit a PR that does this fix.

## Extra information

XS

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by abelbraaksma** [comment]
I have never seen this warning (lucky me or maybe I'm doing something wrong..) can you add a small snippet to what cases it solves?

**Comment by gusty** [comment]
A very illustrative case is when using Fleece to deserialize Json.

The function `ofJson` is generic, depending on the output parameter.

So, in absence of further context:

    let x = ofJson

You'll need to annotate:

    let (x:Choice<Person, string>) = ofJson

However, is way more convenient to just write:

    let x = ofJson<Person>

It also reads much better.

There's nothing wrong when there's only one generic parameter, there's no other possibility. If you have more than one, the order matter so it makes sense to require to be declared explicitly.

**Comment by dsyme** [comment]
Well, you can suppress the warning.  Or if authoring the library you can just declare the type parameters of `ofJson` explicitly in the library?

**Comment by gusty** [comment]
Yes, those are the workarounds I stated.

But having to ask the users to suppress the warning is a bit odd and unnecessary.

Regarding declaring the type parameter explicitly, it's not always possible. In functions like this the parameter has to be automatically inferred. If you write the same constraint by hand (before F# 4.1 wasn't even possible) it doesn't compile the same constraints. Of course this is probably another bug to go to the list of SRTP oddities.

But independent of that, I think the warning is not needed if there's only one generic parameter.

**Comment by dsyme** [comment]
>  @gusty 

Could you give details?  I'm curious

**Comment by gusty** [comment]
Sure !

Here's a generic `tryParse` functions defined as:

    let inline tupleToOption x = match x with true, value -> Some value | _ -> None

    open System
    open System.Text
    open System.Globalization

    type TryParseClass = TryParseClass with

        static member TryParse (_:decimal       , TryParseClass) = fun x -> Decimal.TryParse (x, NumberStyles.Any, CultureInfo.InvariantCulture) |> tupleToOption : option<decimal>
        static member TryParse (_:float         , TryParseClass) = fun x -> Double.TryParse  (x, NumberStyles.Any, CultureInfo.InvariantCulture) |> tupleToOption : option<float>
        static member TryParse (_:int           , TryParseClass) = fun x -> Int32.TryParse   (x, NumberStyles.Any, CultureInfo.InvariantCulture) |> tupleToOption : option<int>
        static member TryParse (_:string        , TryParseClass) = fun x -> Some x                             :option<string>
        static member TryParse (_:StringBuilder , TryParseClass) = fun x -> Some (new StringBuilder(x:string)) :option<StringBuilder>
        static member TryParse (_:DateTime      , TryParseClass) = fun x -> DateTime.TryParseExact       (x, [|"yyyy-MM-ddTHH:mm:ss.fffZ"; "yyyy-MM-ddTHH:mm:ssZ"|], null, DateTimeStyles.RoundtripKind) |> tupleToOption : option<DateTime>
        static member TryParse (_:DateTimeOffset, TryParseClass) = fun x -> DateTimeOffset.TryParseExact (x, [|"yyyy-MM-ddTHH:mm:ss.fffK"; "yyyy-MM-ddTHH:mm:ssK"|], null, DateTimeStyles.RoundtripKind) |> tupleToOption : option<DateTimeOffset>

        static member inline Invoke (value:string) =
            let inline call_2 (a:^a, b:^b) = ((^a or ^b) : (static member TryParse: _*_ -> _) b, a)
            let inline call (a:'a) = fun (x:'x) -> call_2 (a, Unchecked.defaultof<'r>) x :'r option
            call TryParseClass value

    type TryParseClass with
        static member inline TryParse (_:'R, _:obj) = fun x ->
            let mutable r = Unchecked.defaultof< ^R>
            if (^R: (static member TryParse: _ * _ -> _) (x, &r)) then Some r else None

        static member inline TryParse (_:^t when ^t: null and ^t: struct, _:IComparable<_>) = id
        static member inline TryParse (_:'R, _:IComparable<_>) = fun x -> (^R: (static member TryParse: string -> 'R option) x)



    /// Converts to a value from its string representation. Returns None if the convertion doesn't succeed.
    let inline tryParse (* < ^a when (TryParseClass or  ^a) : (static member TryParse :  ^a * TryParseClass -> string -> ^a option) > *)  (value:string) = TryParseClass.Invoke value

Now, if you compile this snippet you'll see exactly the code comment in the inferred signature.

However if you uncomment it, compilation will fail with:

```
~vsB4BB.fsx(33,146): error FS0071: Type constraint mismatch when applying the default type 'obj' for a type inference variable. No overloads match for method 'TryParse'. The available overloads are shown below. Consider adding further type constraints
Possible overload: 'static member TryParseClass.TryParse :  ^R * IComparable<'a> -> (string ->  ^R option) when  ^R : (static member TryParse : string ->  ^R option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    ''a'    
.
Possible overload: 'static member TryParseClass.TryParse :  ^t * IComparable<'a> -> ('b -> 'b) when  ^t : null and  ^t : struct'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    ''a'    
.
Possible overload: 'static member TryParseClass.TryParse :  ^R * obj -> ('a ->  ^R option) when  ^R : (static member TryParse : 'a * byref< ^R> -> bool)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    ''a'    
.
Possible overload: 'static member TryParseClass.TryParse : DateTimeOffset * TryParseClass:TryParseClass -> (string -> DateTimeOffset option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'DateTimeOffset'    
.
Possible overload: 'static member TryParseClass.TryParse : DateTime * TryParseClass:TryParseClass -> (string -> DateTime option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'DateTime'    
.
Possible overload: 'static member TryParseClass.TryParse : StringBuilder * TryParseClass:TryParseClass -> (string -> StringBuilder option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'StringBuilder'    
.
Possible overload: 'static member TryParseClass.TryParse : string * TryParseClass:TryParseClass -> (string -> string option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'string'    
.
Possible overload: 'static member TryParseClass.TryParse : int * TryParseClass:TryParseClass -> (string -> int option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'int'    
.
Possible overload: 'static member TryParseClass.TryParse : float * TryParseClass:TryParseClass -> (string -> float option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'float'    
.
Possible overload: 'static member TryParseClass.TryParse : decimal * TryParseClass:TryParseClass -> (string -> decimal option)'. Type constraint mismatch. The type 
    'obj'    
is not compatible with type
    'decimal'    
.
```

Also notice, that even if this bug was solved it's a bit verbose to write that signature.

**Comment by gusty** [comment]
I added a small sample in the top comment.

Also there, if you copy the inferred constraints and make them explicit, it stops compiling:

    let inline tryParse< ^t  when ( ^t or TryParse) : (static member ( $ ) :  ^t * TryParse ->  string ->  ^t option)> (x: string) : option<'t> = (Unchecked.defaultof<'t> $ TryParse) x
    //~vsD980.fsx(9,168): error FS0043: A type parameter is missing a constraint 'when ( ^t or TryParse) : (static member ( $ ) :  ^t * TryParse ->  ^_arg3)'

**Comment by dsyme** [comment]
OK, thanks.  FWIW here's a smaller repro:
```fsharp
open System.Text

type TryParseClass = TryParseClass with

    static member TryParse (_:string        , TryParseClass) = fun x -> Some x                             :option<string>
    static member TryParse (_:StringBuilder , TryParseClass) = fun x -> Some (new StringBuilder(x:string)) :option<StringBuilder>

    static member inline Invoke (value:string) =
        let inline call_2 (a:^a, b:^b) = ((^a or ^b) : (static member TryParse: _*_ -> _) b, a)
        let inline call (a:^a) = fun (x:'x) -> call_2 (a, Unchecked.defaultof<'r>) x :'r option
        call TryParseClass value


/// Converts to a value from its string representation. Returns None if the convertion doesn't succeed.
let inline tryParse  (value:string) = TryParseClass.Invoke value
let inline tryParse2< ^a when (TryParseClass or  ^a) : (static member TryParse :  ^a * TryParseClass -> string -> ^a option) >  (value:string) : ^a option = TryParseClass.Invoke value
```

**Comment by dsyme** [comment]
@gusty Just to note that the repro I last listed has been fixed in recent versions.

I think I'll close this, I don't think we'll lift the warning for this particular case
