### ISSUE TITLE
Efficient access to entry for singleton Map

### ISSUE THREAD

**Issue by dmbarbour** [fsharp/fslang-suggestions#673]
# Efficient Access to Entry for Singleton Map

I propose a function is added to the Map module that can directly access the MapOne value from the tree. Something like this:

    let tryMapOne (m:Map<'K,'V>) : ('K * 'V) option =
        match (m.tree) with
        | MapOne r -> Some r
        | _ -> None

Currently, to test and access single-entry maps has a lot of unnecessary overhead, e.g. we create a seq then test whether it's empty, take Seq.head, then test also whether the tail is empty.

Why would we test for single-entry maps? Well, my current use case is to maintain invariant structure of a radix tree, where I'm currently using a Map to represent the set of children. Upon removing a child, I need to know whether I have a singleton (no longer a split point in the trie). If so, I may need to recombine tree nodes. But I'm certain there are other use cases, much as we frequently test for single-entry lists.

## Pros and Cons 

Adding this function would improve performance for a niche use case. It won't break existing code, and the implementation is trivial. The only con I can think of is adding a little to the documentation.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: Maybe add to Set as well. 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by 0x53A** [comment]
If https://github.com/fsharp/fslang-suggestions/issues/625 (target typed collection expression) were implemented, then you could use

```F#
let tryMapOne (m:Map<'K,'V>) : ('K * 'V) option =
    match (m.tree) with
    | [ r ] -> Some r
    | _ -> None
```

and the compiler would (hopefully) be smart enough to NOT construct a throwaway map just to compare it but instead directly check ``m``.

**Comment by dsyme** [comment]
The implementation of Map has changed sufficeintly that I'm not sure this is still relevant.

I will close this as a result.
