### ISSUE TITLE
Add a multi-value equality check

### ISSUE THREAD

**Issue by EBrown8534** [fsharp/fslang-suggestions#675]
# Add a multi-value equality check

I propose we add a multi-value equality-check, similar to `IN` for SQL, for example. The idea is that one could do something similar to:

    x in {1; 4}

Which could be rewritten (behind the scenes, so-to-speak) to:
```fsharp
x = 1 || x = 4
```
While there are alternatives (see below), none of these make the intent completely obvious, or create more complexity and cause for errors. (Easy enough to accidentally do `x = 1 || y = 4` and miss the second comparison.) This suggestion would add another layer of safety to F#. I purposely chose the syntax with the sequence-style initiator as it makes the most sense: we're comparing `x` with a sequence of values, and only care that it matches one.

As, the `in` keyword already has meaning in F# it's likely we'd want to find an alternative. (Maybe `{1; 4} has x`, et al.) I'm simply proposing the idea here, to help create a more succinct manner of matching a set of elements together.

The existing way of approaching this problem in F# is to create multiple `x = a` expressions, or pattern-matching, such as:
```fsharp
x = 1 || x = 4
```
Or:
```fsharp
match x with | 1 | 4 -> true | _ -> false
```
There is also an alternative using `.exists`, but I think it starts hiding intent:
```fsharp
List.exists ((=) x) [1; 4]
```
One can also write this trivially with some sort of function:
```fsharp
let ``in`` s x = Seq.exists ((=) x) s
```
This complicates the use a bit, and it's easiest to do with `List` or `Array` types, but it still makes sense:
```fsharp
x |> ``in`` [1; 4]
```
I'm sure there are others, but the point is we already have several longer, less-direct ways of testing for this.

## Pros and Cons 

The advantages of making this adjustment to F# are a more fluid short-hand for comparing direct equality against multiple values, and it can make the intent more clear. ("I want to make sure `x` is _specifically_ `1` or `4`.") Obviously a `match` can do the same, but is substantially longer and starts obscuring intent with the extra noise.

The disadvantages of making this adjustment to F# are an additional keyword of some-sort, and it will increase compilation complexity. I suspect that there will have to be specific rules for what values can be used here, otherwise it would very-likely substantially increase the work on the compiler. I.e. any type of dynamic-expression in the `in` clause would create significantly more work, and I assume there are other cons that I have not yet investigated..

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): Unsure, but my limited knowledge assumes `L` or larger.

Related suggestions: N/A

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by theprash** [comment]
There are also the `contains` functions:

```fsharp
[1; 4] |> Seq.contains x
```

**Comment by EBrown8534** [comment]
Aye, I knew I missed something.

**Comment by EBrown8534** [comment]
@jwosty Thanks, I have already included an example of aliasing for this in my original request. That doesn't make it ideal, and it also doesn't make it quick: performance on `Seq.contains` or `Seq.exists` (et. al.) will most certainly be much less than a compiler rewrite. I think it would be a great move for F# in the "Forward" direction, especially with Enumerations:

    {Status.Completed; Status.Cancelled} includes x

**Comment by abelbraaksma** [comment]
If you add equality you should think about inequality too, and perhaps the magnitude comparisons. And when you allow the right hand side to take a list, why not taking it one step further and allow lists or sequences on both sides? 

I didn't try it, but I'd assume this can be done by creating an operator that operates on two lists, say `.=` and `.<>` (overloading the default operators here is discouraged).

**Comment by EBrown8534** [comment]
@abelbraaksma That's a fair point, does F# support `a < x < b` syntax yet? If not, this is a good opportunity, and I'm willing to make a new request for it. Not sure it would make sense to do them like this specific scenario, but I'm not a language designer or anything so I leave that decision to the pros.

The inequality could be done via `not ({1; 4} includes x)`, but it would be nice if the `not` could go before `includes`.

**Comment by abelbraaksma** [comment]
The more common approach to inequality of sets or sequences is that inequality is true of at least one item of set one is unequal to at least one item of set two, since this is the inverse of equality ( which is true of at least one item compares true). 

F# doesn't have a notion of overloaded operators (as opposed to redefined), and doesn't have a notion of ternary operators, so the 'between' syntax will not be a light hearted change to the language, if it's even considered (the syntax you gave is valid, but will raise a type exception as Booleans do not have magnitude relationships with integers). You can have multiple arguments though, but then you'd need to write something like `x !>> y z` assuming that's your operator.

**Comment by EBrown8534** [comment]
Interesting, @abelbraaksma.

I'm not a 'functional-' anything, so I defer to your better judgment. I don't know that I'm as interested in set-to-set comparison as I am item-to-set comparisons, which are the more frequent use-case (for me). Ideally, I'd probably think that in the case of `{1; 4} includes x`, the `{1; 4}` would be a compile-time list, not a variable. (I.e. `let compVals = {1; 4}; compVals includes x` would be invalid, as the left side of the `includes` should be a fixed set, not a variable set.

This would move towards my purpose: a rewrite to `x = 1 || x = 4`. As it stands, the suggested "bind a new function" will not have nearly the performance of the rewrite, and my particular use-case is in a loop that happens many thousands of times, so it'd be nice if we could filter it out cleanly. (As it stands, we do `Seq.filter (fun x -> x <> 1 && x <> 4)`, but with the `includes` syntax we could `Seq.filter (includes {1; 4} >> not)`, which seems much more clear. Of course, now it's treated differently and a more complex rewrite would need to happen because there's only one argument.

I'm starting to think this might be fruitless, because we'd especially want composition support, and that substantially complicates implementation.

**Comment by Nhowka** [comment]
Probably would be better if made it to be somewhat limited but very good at its job. If the set has the `comparison` constraint, compile it in a way that the number of comparisons is logarithmic. If just `equality` then rewrite it naively as a sequence of `||`. You could pass the result to `not`, but having another syntax for another usage that is not as friendly would make it worse for reading the code.

**Comment by pavelbraginskiy** [comment]
Perl 6 sort-of has a syntax for this like `if (42 == 30 | 42 | 100 ) { ... }`. 

Hmm, F# already has something like this: `match 42 with 30 | 42 | 100 -> ... | _ -> ()`.

That's a bit long though. I think that a more useful feature, that covers the usecases of this proposal and potentially many others, would just be a shorthand syntax for checking if a value matches a single pattern, e.g. `if 42 =~ 30 | 42 | 100 then ...`, to borrow Perl's match operator.

**Comment by Tarmil** [comment]
@pavelbraginskiy Not sure if it's a good thing, but if we had #705, then this would be writable as

```fsharp
if let (30 | 42 | 100) = 42 then
```

**Comment by jannesiera** [comment]
Another option that's currently possible that hasn't been mentioned yet is the following.

```
let oneOf1 x1 value = value = x1
let oneOf2 x1 x2 value = value = x1 || value = x2
let oneOf3 x1 x2 x3 value = value = x1 || value = x2 || value = x3

let x = 10
let testA = x |> oneOf1 10
let testB = x |> oneOf2 10 11
let testC = x |> oneOf3 10 11 13
```

This has little less syntactic clutter since you don't need to create a list. The tradeoff is that there is a need to indicate how many elements you are trying to compare since method overloading is not supported for curried functions.
