### ISSUE TITLE
Add union match patterns to Expr

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-suggestions#681]
# Add union match patterns to `Expr`

I propose we add matched union patterns to `Expr`.  Currently there is no way to encode a matched union case into

The existing way of approaching this is to encode the match as a boolean construct (`Expr.UnionCaseTest`) which is then wrapped in `Expr.IfThenElse`  This means the resulting encoding of the following expression:

```fsharp
type t =
  | One of int * float
  | Two of string * int

<@@ match t with
    | One(x,y) -> printf ""
    | Two(z,w) -> printf "" @@>
```

Is really encoded like this:

```
  IfThenElse (UnionCaseTest (PropertyGet (None, t, []), Two),
    Let (z, PropertyGet (Some (PropertyGet (None, t, [])), Item1, []),
        Let (w,
             PropertyGet (Some (PropertyGet (None, t, [])), Item2, []),
             Call (None, PrintFormat,
                  [Coerce (NewObject (PrintfFormat`5, Value ("")),
                       PrintfFormat`4)]))),
    Let (y, PropertyGet (Some (PropertyGet (None, t, [])), Item2, []),
         Let (x,
             PropertyGet (Some (PropertyGet (None, t, [])), Item1, []),
             Call (None, PrintFormat,
                  [Coerce (NewObject (PrintfFormat`5, Value ("")),
                       PrintfFormat`4)]))))
```

What I suggest is that we add the ability to encode this into `Expr` so that we could write the above in a similar fashion to the underlying F# ast which actually looks like this with match and clause constructs:

```
Match
    (SequencePointAtBinding
        (10,8--10,20) IsSynthetic=false,
    Ident t,
    [Clause
        (LongIdent
            (LongIdentWithDots ([One],[]),None,None,
            Pats
            [Paren
                (Tuple
                    ([Named (Wild, x,false,None);
                    Named (Wild, y,false,None)]))],
            None),
        None,
        App
            (NonAtomic,false,Ident printf,
            Const (String (""))),  SequencePointAtTarget);
    Clause
        (LongIdent
            (LongIdentWithDots ([Two],[]),None,None,
            Pats
            [Paren
                (Tuple
                    ([Named (Wild, z,false,None);
                    Named (Wild, w,false,None)]))],
            None),
        None,
        App
            (NonAtomic,false,Ident printf,
            Const (String (""))), SequencePointAtTarget);
    Clause
        (LongIdent
            (LongIdentWithDots ([Three],[]),None,None,
            Pats
            [Paren
                (Named (Wild,l,false,None))],
            None),
        None,
        App
            (NonAtomic,false,Ident printf,
            Const (String (""))), SequencePointAtTarget)],false)
```

Possibly something like this:

```fsharp
member __.MatchUnion(instance : Expr, unionCases : (UnionCaseTest * Expr) list)
```

Possibly an even a more involved type of match expression could be formulated rather than just union cases.

## Pros and Cons 

The advantages of making this adjustment to F# are quotatins become closer to feature parity with F#'s own syntax, the ideal situaltion would be a quoted literal could round trip back to the syntax of the language rather tha loosing information along the way.

The disadvantages of making this adjustment to F# are the work has to be carried out, extra complexity in quotations.

## Extra information

Estimated cost (S/M): 

Related suggestions: (put links to related suggestions here)

## Affidavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [?] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by jwosty** [comment]
Isn't this a breaking change, if it were to just replace the existing behavior? I.e. the behavior of quotations would be changed. Unless I'm just misunderstanding something. Is it something could be turned on and off somehow?

**Comment by 7sharp9** [comment]
To be fair Im not sure, it could possibly be half implemented in such a way that only programmatic implementation of `Expr.UnionMatch` would be implemented and it produces the `IfThenElse (UnionCaseTest` blocks, a sort of helper block.  e.g. no change to quotation representation just additional API so theres away to construct the clauses. 

I mean that would not be useful in my use case as I would like to have quotation representing F# syntax without loss of information.

**Comment by 7sharp9** [comment]
It could be that what would be the most useful if an additional language feature was implemented that allowed you to quote F# in a typed ast fashion to allow full transpilation and generation of code tailored to function language output.  I know from the original design quotation were not intended to be used like this although a lot more usage of quotation have happened with the advent of type providers.

**Comment by wallymathieu** [comment]
Sounds like a nice thing to have. You could do some really interesting meta programming with more expression information.

**Comment by Rickasaurus** [comment]
It seems like this could break a lot of existing quotations code that depends on pattern matches turning into if statements. The fragility in building on this stuff is quickly becoming apparent to me.

**Comment by 7sharp9** [comment]
@Rickasaurus The problem is quotations are only really good at half the things they should be, to put it another way they are only good for languages that only have if statements, I believe meta constructs like quotations should fully represent the F# language, or there is a another construct available that does this.

**Comment by dsyme** [comment]
I've labelled this as "probably not"

Per conversation on slack :

> @dsyme says My feeling is that we will not do that - or at least I ould not work on it.  Adding "variations" on quotations where some information is/isn't encoded has only a few limited use cases.

**Comment by voronoipotato** [comment]
I think one of the big questions at least to me would be how would the change to AST affect the fable team and the FShade / Aardvark team, and whether those changes would be positive, negative or neutral. 

@Rickasaurus Well that's true for any API change where you're adding a thing. A simple library that translates AST matches to ifs doesn't sound perilous. A less lossy representation of our AST probably is good.
