### ISSUE TITLE
Add the ability to quote code as an abstract syntax tree

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-suggestions#682]
# Add the ability to quote code as an abstract syntax tree

I propose we add the ability to quote code as an abstract syntax tree.

A new operator pair could be introduced that would allow fragments of F# code to be quoted as actual F#, perhaps `<< ... >>` or similar.

```
let code = << let test = fun x -> x * x  >>
```

The resulting code being an ast fragment like this:
```
[Let
           (false,
            [Binding
               (None,NormalBinding,false,false,[],
                PreXmlDoc
                  (Range+pos,  Ast+XmlDocCollector),
                SynValData
                  (None,
                   SynValInfo
                     ([[SynArgInfo ([],false,Some x)]],
                      SynArgInfo ([],false,None)),None),
                Named
                  (Wild
                     quotedCode.fs IsSynthetic=false,
                   test,false,None,
                   quotedCode.fs IsSynthetic=false),
                None,
                Lambda
                  (false,false,
                   SimplePats
                     ([Id
                         (x,None,false,false,false,
                          quotedCode.fs IsSynthetic=false)],
                      quotedCode.fs IsSynthetic=false),
                   App
                     (NonAtomic,false,
                      App
                        (NonAtomic,true,Ident op_Multiply,Ident x,
                         quotedCode.fs IsSynthetic=false),
                      Ident x,
                      quotedCode.fs IsSynthetic=false),
                   quotedCode.fs IsSynthetic=false),
                quotedCode.fs IsSynthetic=false,
                NoSequencePointAtLetBinding)],
            quotedCode.fs IsSynthetic=false)],
        false,
        quotedCode.fs IsSynthetic=false)],
    PreXmlDoc
      (Range+pos, Ast+XmlDocCollector),[],None,
    quotedCode.fs IsSynthetic=false)],
(true, true)))
```

The existing way of approaching this problem in F# is to use quotations along with type providers which is too limited and also lacks the ability to represent the F# language without a loss of information, see #680 / #681 for two such issues.

## Pros and Cons 

The advantages of making this adjustment to F# are a vast improvement to F# meta programming capability, the compilers API (FCS) already takes an abstract syntax tree as input so this is increasing the usage of that capability. 

The disadvantages of making this adjustment to F# are the time taken to do the work, the added complexity to the language.

## Extra information

Estimated cost (M/L): 

Related suggestions: (put links to related suggestions here)

## Affidavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by zpodlovics** [comment]
Take a look at OCaml PPX for inspiration: http://ocamllabs.io/doc/ppx.html

**Comment by 7sharp9** [comment]
We can currently do parts of what PPX can do, what I would like is better integration into the compiler chain like adding quoted literals, splicing etc.   I have a program now which does what `dumpast` does in PPX etc.

 I wanted this language suggestion to act as a starting point for a discussion on that, I didn't want to describe anything too deeply incase this suggestion gets closed.

**Comment by zpodlovics** [comment]
I would love to have more metaprogramming story for F#. And at the end to have language level integration - something like Lightweight Modular Staging for Scala. 

It seems that some kind of code specialization and partial staging would be possible with your proposal, am I right? Would it be possible to also control when the ast transformation should happen eg.: runtime / compilation time?

**Comment by 7sharp9** [comment]
The first step is to allow the quoting of code to ast fragments, after that holes could be defined and other fragments could be spliced into place, I would propose that this all happens at compile time.

Finally there could be an integration of quoted fragment so that the staged ast quotation is incorporated with the current one during compilation.

**Comment by Rickasaurus** [comment]
@7sharp9 I really like this idea, but it does have the downside of making any changes to the F# AST break pretty much all users of this.

**Comment by 7sharp9** [comment]
Any new feature alters the AST, like Span added to the AST recently.

**Comment by cartermp** [comment]
Adding shouldn’t really be an issue. Modifying might be, though

On Fri, Jul 27, 2018, at 09:04, Dave Thomas wrote:
> Any new feature alters the AST, like Span added to the AST recently.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/fsharp/fslang-suggestions/issues/682#issuecomment-408464326

**Comment by dsyme** [comment]
Just commenting on the above:

> as far as I know industrial users mostly avoid TP because it makes their life lot harder in real-world (unpredictability, performance issues, weird errors, etc).

This is not the case - some people certainly run into problems using TPs, but I consistently meet many people who use them in production scenarios.  Those who run into problems are much more vocal of course.

The same is true of F# quotations, or Rosyln analyzers... Indeed OCaml meta-programming has/had many issues and I saw many examples of them being used/unused.  I actually think all meta-programming solutions have problems like this: they solve various kinds of problems but are frequently misused or run into tooling issues
