### ISSUE TITLE
create an fsi.RegisterPrintTransformer method

### ISSUE THREAD

**Issue by sgtz** [fsharp/fslang-suggestions#690]
during fsi sessions, it can be useful to use alternate views of an object, but the default view then becomes inaccessible.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

convenience. However, most power users will still find their way around okay.

## Workaround

the programmer could create their own Session singleton, which their transformer then references to find out which view is currently active. The default (no transformer) still seems to be out of reach, though. Maybe there's a nice way to do this, but still, a remove method would be handy.

## Examples

    fsi.AddPrintTransformer(PrettyPrinting.f >> (fun x->"\n" + x) >> toObj)  // nice

    fsi.AddPrintTransformer(fun (x:Table)->x:>obj) // failed attempt to reinstate default without fsi environment reset

    fsi.AddPrintTransformer(fun (x:Table)->x.ToString():>obj) // etc

    fsi.AddPrintTransformer(fun (x:Table)->null) // etc

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
I'm fine with making sure there's some way to remove these things (e.g. RegisterPrintTransformer returning an IDisposable)

No RFC needed, it should just be done in vlsualfsharp repo
