### ISSUE TITLE
Use on multiple binding (`let x, y = ...` compiles, but `use x, y = ..` not)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fsharp/fslang-suggestions#693]
# Use on multiple binding (`let x, y = ...` compiles, but `use x, y = ..` not)

I propose to have multi `use`.

Call to `public static void CreateWithSwapChain(DriverType driverType, DeviceCreationFlags flags, SwapChainDescription swapChainDescription, out Device device, out SwapChain swapChain)` as 
```
    let device, swapChain = SharpDX.Direct3D11.Device.CreateWithSwapChain(DriverType.Hardware, SharpDX.Direct3D11.DeviceCreationFlags.None, chainSwapDescription)
    device.Dispose()
    swapChain.Dispose()
```

replaced with 
```
use device, swapChain = SharpDX.Direct3D11.Device.CreateWithSwapChain(DriverType.Hardware, SharpDX.Direct3D11.DeviceCreationFlags.None, chainSwapDescription)
```

The existing way of approaching this problem in F# is `use' bindings must be of the form 'use <var> = <expr>'` error.

## Pros and Cons 

The advantages of making this adjustment to F# are better coding to `SharpDX` and similar complex native code wrappers, `use` to support more of `let`.

The disadvantages of making this adjustment to F# is that case can be to narrow to support.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
I think this would be a good and sensible addition. Speaking with @jaredpar, this sounded like something that would also be supported in the corresponding C# feature proposal.

**Comment by jaredpar** [comment]
CC @chsienki

The corresponding C# proposal is pattern based dispose. It would essentially allow `using var x` to be allowed whenever `x.Dispose()` would be a legal expression.  That could be combined with tuples in the following way:

``` csharp
public static void Dispose<T1, T2>(ref this (T1, T2) tuple) 
  where T1 : IDisposable
  where T2 : IDisposable { 
  tulpe.Item1.Dispose();
  tuple.Item2.Dispose();
}
```

Such a method would then allow tuples, where the items were `IDisposable` to be usable in a `using` statement or block.

**Comment by dsyme** [comment]
Don't you think it's easier to just use a helper? Baking this into the compiler gives a more complex translation of `use` which feels awkward, given the workaround is so simple

```fsharp
    use device, swapChain = Dispose2(SharpDX.Direct3D11.Device.CreateWithSwapChain(DriverType.Hardware, SharpDX.Direct3D11.DeviceCreationFlags.None, chainSwapDescription))
```

**Comment by dsyme** [comment]
Closing this for reasons described above.
