### ISSUE TITLE
ValueOption parity with options

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#703]
# Title of Suggestion

I propose we:

* Add equivalent module-bound functions for `ValueOption` so that it has parity with [regular options](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/option.fs).
* Add further properties to the ValueOption type to match what exists in Option
* Add the same debugger display as options

The existing way of approaching this problem in F# is to write these functions and/or type extensions yourself.

## Pros and Cons 

The advantages of making this adjustment to F# are:

* Makes `ValueOption` feel more first-class
* Resolves an awkwardness where there is a lot more utility with the `Option` type than the `ValueOption` type

The disadvantages of making this adjustment to F# are:

* It's more API surface area to build and test
* If we ever add some way to write code that is generic over "option-shaped" types, we'll have needless code duplication

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestion: https://github.com/fsharp/fslang-suggestions/issues/612

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
Approving as per "703 seems OK to do" from @dsyme in slack 🙂

**Comment by cartermp** [comment]
Closing this out as it is committed and shipping

**Comment by Thorium** [comment]
What is the preferred way to map option to value-option? With lists there are Seq.toList and Map.ofArray etc but I can't see ValueOption.ofOption or Option.ToValueOption or anything like that

**Comment by brianrourkeboll** [comment]
I'll just note here for posterity that https://github.com/fsharp/fslang-suggestions/issues/703#issuecomment-1165336456 was addressed via an addendum to the RFC for this feature in https://github.com/fsharp/fslang-design/pull/779, implemented in https://github.com/dotnet/fsharp/pull/17436.
