### ISSUE TITLE
Introduce a clean mechanism to delay SRTP overload resolution

### ISSUE THREAD

**Issue by realvictorprm** [fsharp/fslang-suggestions#707]
# I propose we add a clean mechanism to delay SRTP overload resolution.

The existing way of approaching this problem in F# is to introduce in SRTP calls unrelated type parameters as support.

See this example:

One just wants to create an SRTP call which decides at full application (all parameter types are solved) which overload should be called.

```fsharp
type Tuple =
    static member inline TupleMap ((a, b),          _ : Tuple) = fun f -> (f a, f b)
    static member inline TupleMap ((a, b, c),       _ : Tuple) = fun f -> (f a, f b, f c)
    static member inline TupleMap ((a, b, c, d),    _ : Tuple) = fun f -> (f a, f b, f c, f d)
    
    static member inline Map f (x: 'Tin) : 'Tout =
        let inline call_2 (a: ^a, b : ^b) = (^a : (static member TupleMap : ^b * _ -> ^t) (b, a))
        call_2 (Unchecked.defaultof<Tuple>, x) f
```

However this code will fail because, although the parameter `x` is still generic and not further specified, with an overload resolution error. To solve this problem people will introduce another (unrelated/confusing) type parameter as support of the SRTP call.
```fsharp
    static member inline Map f (x: 'Tin) : 'Tout =
        let inline call_2 (a: ^a, b : ^b) = ((^a or ^b) : (static member TupleMap : ^b * _ -> ^t) (b, a))
        call_2 (Unchecked.defaultof<Tuple>, x) f
```
Which in fact delays the overload resolution because at that point the parameter `x` isn't fully solved yet.

To change this I would propose to be able to add a keyword `delayed` which tells that as soon as not all parameters of the functions haven't been fully solved yet the overload resolution may be delayed.
In our example:
```fsharp
    static member inline Map f (x: 'Tin) : 'Tout =
        let inline call_2 (a: ^a, b : ^b) = (delayed ^a : (static member TupleMap : ^b * _ -> ^t) (b, a))
        call_2 (Unchecked.defaultof<Tuple>, x) f
```

My syntax proposal here is open for discussion. One could also write it like this:
```fsharp
(^a : (delayed static member TupleMap : ^b * _ -> ^t) (b, a))
```

## Pros and Cons 

The advantages of making this adjustment to F# are:

- people stop creating super weird SRTP expressions which are just because they want delayed overload resolution

The disadvantages of making this adjustment to F# are:

- Another keyword to learn and understand!

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: None I think

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
A new keyword just to get around a limitation of a design doesn't feel right at all. Especially when it's less typing to apply the workaround. Additionally, I do not believe that many F# programmers are interested in "delayed overload resolution", and creating a brand-new language feature just for that feels awfully niche. I'm not in favor of this.

**Comment by realvictorprm** [comment]
I found a better solution to this problem

**Comment by realvictorprm** [comment]
I mean, I've something better in mind which does not require this proposal :)

**Comment by gusty** [comment]
Can you share it?

**Comment by abelbraaksma** [comment]
@realvictorprm, what idea did you come up with? I'd be most curious!
