### ISSUE TITLE
Add Map.count

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#71]
**Submitted by Zhen on 3/10/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

Implement Map.count

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12880398)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12880398-add-map-count.md#comments)

**Comment by dsyme** [comment]
This has been implemented, thanks for the suggestion https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/map.fsi#L257
