### ISSUE TITLE
GetSlice should use ValueOptions in addition to reference options

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#714]
# Title of Suggestion

I propose we extend the implementation of the slicing functionality( `my_instance.[start_option..end_option]`) to use an overload of `GetSlice` that accepts ValueOptions if one is present.  This would allow for opt-in usage of slicing in non-allocating pathways where types opt in to it, for example on `Memory<'t>` and `Span<'t>` types where zero- or low-allocation programming is encouraged.  The order of resolution could be changed, for example, to prefer the valueoption member when found, otherwise defaulting to the reference-option member.

The existing way of approaching this problem in F# is to manually use the appropriate Slicing members exposed on the types directly, without syntax support.

## Pros and Cons 

The advantages of making this adjustment to F# are more universal support for existing language features and idioms in a way that is coherent with the language but also observant of recent trends towards performance/memory usage.

The disadvantages of making this adjustment to F# are a greater test surface area around the slicing feature, and a commensurate increase in the complexity of the overload-resolution feature of the slicing feature.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: None found

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design (being an expansion of the existing 
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
As I mentioned on twitter, If you inline the GetSlice methods the options will always be eliminated at any particular callsite https://twitter.com/dsyme/status/1086594247288152064

This my the recommended way of doing things, we should really document it

**Comment by baronfel** [comment]
It sounded too good to be true so I made a [sharplab](https://sharplab.io/#v2:DYLgZgzgPg9DAEAVArgJwHbwC4AsCm8A9slgA4naHwDkAwgMTXwCG6AJvBHgToQO7Z8nYAEsAxnggtUBEelHo8HOViq48AWABQcFqVKpCBkcywFj6LGHhzBBNnjGEAtqRHAl8AG55UEEYSYfPiYcgqyUshcbNraRniYAMoAnhBmztpYyaQEAJLycngAFACU8AC82vDV8M54zgBGvjYFioIiEAB0AOJ4WImiEkVpzKhY+Q4AHiAtWESkWAHoADTwCWwTeNOz84uBZZVaNTXOpmI4nFij4+xbq+ubk/B8IrhVx/BQ8ABygXirvzaAFoAHzwCxWTAAInQVAaxHYECh72OX0B/3giRcBAIoPBqBUYGhnU6AFI2FC1iial8sXVOAC/vA8RCifAoeSSZSINTqrTsQzMQLcWDWdDOWSKZwqVpMtkCL9UKdgKUKvBqXVGs1cB0en0BuJiiMxo8Zipdkt7uxTTsjHt0AdebUzhdjTcplaNrcni83kcPmi/ozgaKCZY2TC4Qi2EinYHFKs6TjmaHCcTJZTNP7UUL6RBgyL8Wn2RLuXHcwR8xW1imi+HxWwSeTuTLtB45q96mr8uFSrEtJ3nJ0ANoABhJAEZR9OALraQcjyfT0dzgfpEfjzqrtt9GzpABMasVyr7a/q+43S9n84Pi86U+vZ+cF7HJNXQA==) to see it in action.  Very nice!

**Comment by cartermp** [comment]
Closing this out and I'll open a docs bug

**Comment by cartermp** [comment]
ergh there isn't event an article on it, time to have more fun

**Comment by cartermp** [comment]
Issue here: https://github.com/dotnet/docs/issues/10073

**Comment by cartermp** [comment]
PR here: https://github.com/dotnet/docs/pull/10090

**Comment by baronfel** [comment]
So my other question then is should the existing GetSlice implementations be changed to `inline`? In addition, though we support slicing for strings and arrays, those GetSlice implementations can not be inlined in this way and so always will allocate. Is there a way around that?
