### ISSUE TITLE
Record-like member constraints

### ISSUE THREAD

**Issue by cannorin** [fsharp/fslang-suggestions#717]
# Record-like member constraints

I propose we allow record-like syntax sugar for member constraints:

```fsharp
let inline f (x: ^TX when ^TX :> {| X: ^X; Y: ^Y1 -> ^Y2 |}) = ...
```
instead of

```fsharp
let inline f (x: ^TX when ^TX: (member X: ^X) and ^TX: (member Y: ^Y1 -> ^Y2)) = ...
```

## Pros and Cons 

Pros:

* It makes member constraints easier to read and write, especially when we have many member constraints to one type.

* Combined with (anonymous) records, it can emulate structural subtyping with clean syntax:

```fsharp
let inline getX (x: ^TX when ^TX :> {| X: ^X |}) = ...

getX {| X = 0 |}
getX {| X = 1; Y = "foo" |}
...
```

Cons:

* It's very confusing with some existing features.
  * It uses the same syntax with anonymous records and type constraints.
    * maybe we should add some prefix like `^TX :> interface {| X: ^X |}` or  `^TX :> shape {| X: ^X |}`
    * or borrow the syntax proposed in #483: `^TX : #{| X: ^X |}`
  * Although it resembles (anonymous) records, it can actually be used to arbitrary types i.e. classes.
* It is nearly useless unless we have #440. We still have to write `(^TX: (member X: ...) x)` to access the fields and methods, which itself is enough to assert the required member constraint.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S

Related suggestions: (put links to related suggestions here) #440 #641 #483

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I  would be willing to help implement and/or test this

**Comment by realvictorprm** [comment]
If we could combine this with the possibility to use record update syntax on the record this would be incredible helpful for data transformation pipelines.

**Comment by dsyme** [comment]
We won't be adding this, at least not without a total revamp of constraints to include many many other things.
