### ISSUE TITLE
Make Set.count O(1)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#72]
# Make Set.count O(1) [12880410] #

**Submitted by Zhen on 3/10/2016 12:00:00 AM**  
**3 votes on UserVoice prior to migration**  

Seems easy to track items when they are added and removed

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12880410)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12880410-make-set-count-o-1.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 (and OCam supports positional arguments) but we decided against it then.  Per policy closing so as not to revisit design decisions unless there's been a significant change in circumstances
