### ISSUE TITLE
Copy and Update Record Lambdas

### ISSUE THREAD

**Issue by TheJayMann** [fsharp/fslang-suggestions#723]
# Copy and Update Record Lambdas

I propose we add a new syntax to create a lambda function which copies and updates a record.
```fsharp
{ with Name; Age}
```
This would be syntactic sugar which would be translated as follows.
```fsharp
fun r name age -> { r with Name = name; Age = age }
```

Also, some record fields can be set directly.

```fsharp
{ with Name; Age; UpdatedAt = System.DateTime.UtcNow }
fun r name age -> { r with Name = name; Age = age; UpdatedAt = System.DateTime.UtcNow }
```
I've also considered the possibility of assigning the value of fields to that of other fields, though I'm unsure whether it would be better to assign the same value or the previous value, if it should be implemented at all.
```fsharp
{ with Name; Age; Nickname = Name }
// option 1, same value
fun r name age -> { r with Name = name; Age = age; Nickname = name }
// option 2, previous value
fun r name age -> { r with Name = name; Age = age; Nickname = r.Name }
```

Assuming that the record lambda needs to be qualified, the record name could be added to the expression.

```fsharp
{ Person with Name; Age }
```

Also, if necessary, the `fun` keyword could be used to ensure we are using a record lambda and not a record expression.
```fsharp
{ fun with Name; Age }
```

I have not considered the possibility of applying this to nested copy and update syntax, but I'm not against the idea if it can be implemented without too much complexity.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S - M

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help ~~implement and/or~~ test this

**Comment by dsyme** [comment]
I was wondering the other day about a whole swathe of similar improvements to the copy-and-update feature which would sort-of- align with this, and sort-of- conflict with it e.g.

```           
           { state with Count.Increment();  } 
```
becomes
```
           { state with Count= state.Count.Increment() } 
```
and
```
           { state with Count |> increment } 
```           
becomes
```
           { state with Count = state.Count |> increment }
```
(allowing both pipelined and OO notation)

I'm not saying we should do this, just was idly thinking about it
