### ISSUE TITLE
Allow undentation for constructors

### ISSUE THREAD

**Issue by charlesroddie** [fsharp/fslang-suggestions#724]
It's good to be able to move 4 characters to the right to get to the next level and leads to smart code where lines generally start at a indentation which is a multiple of 4. This works well with tooling (Tab/shift-tab).

However in constructors, full indentation is required. So when defining types, the length of the type name determines how far to the right inputs must be positioned:

```fsharp
open System
type SixAccessViolations(a:AccessViolationException,
                         b:AccessViolationException,
                         c:AccessViolationException,
                         d:AccessViolationException,
                         e:AccessViolationException,
                         f:AccessViolationException) =
    class end
```

Undentation is not allowed:

```fsharp
type SixAccessViolations(a:AccessViolationException,
        b:AccessViolationException, c:AccessViolationException,
        d:AccessViolationException, e:AccessViolationException,
        f:AccessViolationException) =
    class end
```
Function inputs allow undentation (and it's explicitly in the F# spec):
```fsharp
let sixAccessViolations =
    SixAccessViolations(accessViolation,
        accessViolation, accessViolation,
        accessViolation, accessViolation,
        accessViolation)
```

**Comment by cartermp** [comment]
I would like to see this done if possible.

**Comment by dsyme** [comment]
Marked as approved.  I'll try to look at this today

**Comment by dsyme** [comment]
This suggestion is implemented in https://github.com/Microsoft/visualfsharp/pull/6314

@charlesroddie Any chance you could write up a brief RFC?  @cartermp has broken his arm so can't type fast :)

**Comment by charlesroddie** [comment]
Travelling at the moment but I will give it a go in a few days.

**Comment by cartermp** [comment]
Thanks @charlesroddie

**Comment by dsyme** [comment]
@cartermp You're not meant to be typing!

**Comment by FunctionalFirst** [comment]
@dsyme Only asking because I haven't seen an example of this. Will undentation of the first input be allowed? E.g.,
```fsharp
type SixAccessViolations(
    a:AccessViolationException,
    ...) =
```

**Comment by charlesroddie** [comment]
@FunctionalFirst Yes and that will be a very common way to format. That's how it works with functions at the moment.

**Comment by dsyme** [comment]
> @dsyme Only asking because I haven't seen an example of this. Will undentation of the first input be allowed? 

We should double check - the test cases in the PR doesn't cover this yet https://github.com/Microsoft/visualfsharp/pull/6314/files#diff-d652333102a65f9f23289cb1d40938bbR249

**Comment by charlesroddie** [comment]
@dsyme Sorry: I didn't have enough time/internet/power to look at the RFC while I was away.

This proposal was for constructors, which tend to have a lot of inputs and long names.
What do you think about extending it to other functions?

```fsharp
// The proposal currently is to allow undentation in constructors and static members.
// Currently: warning FS0058: Possible incorrect indentation
// Proposed: OK
type EightCalculator(
        irrelevantNumber1:int,
        irrelevantNumber2:int) =
    member t.Eight = 8

// Should undentation in other functions be allowed too?
// Currently: warning FS0058: Possible incorrect indentation
// Proposed: OK?
let nineCalculator(
        irrelevantNumber1:int,
        irrelevantNumber2:int)
    = 9

let irrelevantNumber1 = 1
let irrelevantNumber2 = 2

// OK: undentation allowed when calling constructors
let eight =
    let ec =
        EightCalculator(
            irrelevantNumber1,
            irrelevantNumber2)
    ec.Eight

// OK: ... and other functions
let nine =
    nineCalculator(
        irrelevantNumber1,
        irrelevantNumber2)
```

**Comment by dsyme** [comment]
Completed
