### ISSUE TITLE
`System.Type` should support “comparison” constraint

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#725]
`System.Type` should be value equality, instead of reference equality. for example:
```f#
"".GetType() = typeof<string>
```
will return `true`. so it could be as `set`'s elements or `dict`'s keys. but will be error:
```F#
let likePrimitives = set [typeof<string>;typeof<DateTime>]
```
FS0001:“Type” don't support “comparison” constraint.

so, I suggest that `System.Type` support “comparison” constraint.

**Comment by abelbraaksma** [comment]
I think there's always only one instance of any particular type in memory, which means that reference equality should suffice.

That said, I'm surprised to see that sets etc don't support a collection of Types, that seems to me to be an omission. But I think the underlying reason is that types aren't ordered, and sets in F# are ordered sets. How would one order Types?

**Comment by xp44mm** [comment]
order is less useful. i just want to *equality*. actually, i just want to put type into `set` and as dict's keys. for example:
```F#
let testLikePrimitive () =
    let likePrimitives = set [typeof<string>;typeof<DateTime>]
    let someObj = box ""
    likePrimitives.Contains <| someObj.GetType() 
```
i expected it return `true`.

**Comment by xp44mm** [comment]
if you have some people in a set. how you order them？ by age? by name? by beautiful?
the answer depends on why you look for. you maybe for young. for super star. for a ator. you must order them. but in goverment database, the order may be is their id code.
 
in this topic. the order of members of a set is just for performance. order self no any means.

and every two things can be compared. and must be in order by some one rule. even the rule make no sence.

**Comment by PatrickMcDonald** [comment]
The comparison constraint is not going to go unfortunately, so the F# Set  is not going to work for you. You could consider using HashSet<T> or a List instead

**Comment by cartermp** [comment]
Changing how we interpret `System.Type` would be a breaking change, as would changing the Set type. I don't think this could be done.

**Comment by dsyme** [comment]
That's correct
