### ISSUE TITLE
Selective Type Provider Error Highlighting

### ISSUE THREAD

**Issue by voronoipotato** [fsharp/fslang-suggestions#729]
I propose we add selective error highlighting for type providers that permits the type provider to add red squiggles to any part of the string instead of strictly the entire string.
```fsharp
do
    use cmd = new SqlCommandProvider<"
        SELECT TOP(@topN) FirstName, LastName, SalesYTD 
        _FRMO_ Sales.vSalesPerson
        WHERE CountryRegionName = @regionName AND SalesYTD > @salesMoreThan 
        ORDER BY SalesYTD
        " , connectionString>(connectionString)
    cmd.Execute(topN = 3L, regionName = "United States", salesMoreThan = 1000000M) |> printfn "%A"
```
in this example the whole SqlCommandProvider would be red in how it works now instead of simply highlighting "FRMO" which should be "FROM". 

The existing way of approaching this problem in F# is to make the whole string red.
## Pros and Cons 

The advantages of making this adjustment to F# are ...

It makes existing usages of type providers more user friendly. It also goes well with this proposal. https://github.com/fsharp/fslang-suggestions/issues/556

The disadvantages of making this adjustment to F# are ...

   more work
## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
S
Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by smoothdeveloper** [comment]
I tend to move those into separate .sql (or .json, whatever it is) files.

Editing the .sql file will show the error. 

What would be amazing is if the type provider could report resources (uris for example) to the tooling, so an error in the resource would show as a link to edit the faulty file.

Having that feature in F# + TP SDK is indeed a first step in that direction and perfectly blends with what has been driving the TP so far. +1.

**Comment by voronoipotato** [comment]
yes being able to refer to other resources as well as specific regions of text in the TP would be good.
