### ISSUE TITLE
Code clarity: To change the default value returned by function Unchecked.defaultof<string> to "" from null

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#73]
# Code clarity: To change the default value returned by function Unchecked.defaultof<string> to "" from null [12882690] #

**Submitted by Alexei Odeychuk on 3/10/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

I suggest changing the default value returned by function Unchecked.defaultof<string> to "" from null. I think the function should return a value of type string indicating an empty string "" as expected by a majority of language users who writes string processing code.
Null indicates that there is no value at all.
I am inclined to think from my own experience that null returned by Unchecked.defaultof<string> leads to unnecessary complications in the code dealing with value names of type string, namely in the form of mandatory checks both for "" and null, instead of a check for "" only in situations when you expect to encounter an empty string.
The change suggested in the F# language will allow writing more simple and clear code for string processing.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12882690)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12882690-code-clarity-to-change-the-default-value-returne.md#comments)

**Comment by dsyme** [comment]
This would be a breaking change.  Closing
