### ISSUE TITLE
Change all links of "Archived UserVoice comments" in migrated issues to point to the commit before archive deletion instead

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#735]
I propose we change the links of "Archived UserVoice Comments" to point to the file in the commit d48c35ce216e2bff148937ec028ad61e5c273fdf instead of `master` because those files are deleted in https://github.com/fsharp/fslang-suggestions/commit/da13a85d0e01746d54fc7b5de12d6a501885b770.

The existing way of approaching this problem in fslang-suggestions is to change the `master` in links to point to d48c35ce216e2bff148937ec028ad61e5c273fdf manually.

e.g. Click "Archived UserVoice Comments" in https://github.com/fsharp/fslang-suggestions/issues/18. It brings up the [404 Not Found page](https://github.com/fsharp/fslang-suggestions/tree/master/archive/suggestion-10973943-char%5B%5D-literals.md).

This is because that link points to master where the archive is gone. If we change `master` to d48c35ce216e2bff148937ec028ad61e5c273fdf, [we can read the comments successfully.](https://github.com/fsharp/fslang-suggestions/tree/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-10973943-char%5B%5D-literals.md)

## Pros and Cons 

The advantages of making this adjustment to fslang-suggestions are
1. Links are not dead!
2. In case UserVoice is down, people can still view comments.
3. No need to search the commit history only to find out the archive is deleted, and need to relocate the comments again.

The disadvantage of making this adjustment to fslang-suggestions is the work needed to update links.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: Nope

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on fslang-suggestions](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Change the syntax to C#") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design obviously
* [x] I would be willing to help test this

**Comment by abelbraaksma** [comment]
Thanks for pointing me to this. Perhaps instead of changing everything, maybe we can just undelete them? Why were they deleted in the first place?

**Comment by abelbraaksma** [comment]
@cartermp, @KevinRansom, this pops up from time to time, the quick fix is to just put the archive back to where it was.

We ask people that do language suggestions to do research into old suggestions. That's currently not possible, or at least quite hard, which may lead to people asking for the same thing again and again. If we fix and/or redirect as @Happypig375 suggests in this issue people can at least find the "why was this rejected" reasons back.

If we can't put them back, we should probably fix the links in each issue, but that's way more work.

**Comment by cartermp** [comment]
@baronfel could the tool you used to initially create these issues be used to update the links to just point to the files in this tree? https://github.com/fsharp/fslang-suggestions/tree/d48c35ce216e2bff148937ec028ad61e5c273fdf

Separately there's no real value in linking to "the comments" since they're already a part of the file that contains the suggestion

**Comment by baronfel** [comment]
For reference, the tool is over at https://github.com/dsyme/fsharp-lang-suggestions-scripts.

It's just using the github API to create new issues. What we could do with another script/tool is to scrape all issues in this repo, find the Archive links in the issue submission, and rewrite them from master to d48c35ce216e2bff148937ec028ad61e5c273fdf as suggested.

**Comment by abelbraaksma** [comment]
I wouldn't mind putting in the work and learn a bit about the github api in the process, but I (obviously) don't have that kind of access level to other people's posts.

**Comment by baronfel** [comment]
I you want to work on a tool I'd gladly help test/run it. I've got editing rights to the issues on this repo, so as long as your tool is able to accept a user-supplied github API token it would be easy to replicate.

**Comment by abelbraaksma** [comment]
> is able to accept a user-supplied github API token it would be easy to replicate.

Since I've yet to make it anyway, I can bake that in :). I might not get around to it right away, playing with another F# issue on performance right now, but I'll put it on my TODO list.

**Comment by Happypig375** [comment]
#920 is another case for this:
> However, since the links are dead, and the issue was quite a while ago, I was hoping it would be okay to bring this up for discussion again.

**Comment by dsyme** [comment]
Closing this old discussion - by all means go ahead and make the changes

**Comment by Happypig375** [comment]
@dsyme What's the reasoning for deleting the archive anyways? And I don't have editing permissions either.

**Comment by dsyme** [comment]
TBH I can't recall - I guess it was to prevent confusion in search.
