### ISSUE TITLE
Decorate automatically implemented properties with CompilerGenerated attribute

### ISSUE THREAD

**Issue by AdhemarVandamme** [fsharp/fslang-suggestions#736]
The C# en F# compiler differ in their CIL bytecode ouput of automatically implemented properties.

First, the C# compiler uses a backing field `ClassName::'<PropertyName>k__BackingField'` whereas the F# compiler uses a backing field `ClassName::PropertyName@`. That’s not the problem.

Second, and this is what this feature request is about: the C# decorates both the `get` and the `set` methods of automatically implemented properties with a `System.Runtime.CompilerServices.CompilerGeneratedAttribute`.

This means both
`.method public hidebysig specialname instance PropertyType get_PropertyName() cil managed`
and
`.method public hidebysig specialname instance void set_PropertyName(PropertyType 'value') cil managed`
start off with
`.custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )`

Currently, the F# compiler doesn’t.

I propose that the F# compiler also decorates both the `get` and the `set` methods of automatically implemented properties with a `CompilerGeneratedAttribute`.

## Pros and Cons 

The advantage of making this adjustment to the F# compiler is to make the F# compiler behave like the C# compiler in this regard.

[Realm (.NET)](https://github.com/realm/realm-dotnet) is a project where the appearance of a `CompilerGeneratedAttribute` (at least on the `get` method) makes a difference. Without the attribute, Realm doesn’t really work on F# types, even if their properties are automatically implemented. There’s an [open issue](https://github.com/realm/realm-dotnet/issues/1691) on [Realm (.NET)](https://github.com/realm/realm-dotnet) to work around this , but arguably the cleaner fix is to make the F# compiler behave like the C# compiler in this regard.

The only disadvantage of making this adjustment to the F# compiler that I can think of, is that the CIL output is a few bytes larger.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question, and I have searched [stackoverflow](http://stackoverflow.com) for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously “already been decided” in previous versions of F#.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

This is not even a change to the F# language design; but a change to the F# compiler.

**Comment by realvictorprm** [comment]
Correct me if I'm wrong but if I remember correctly this is actually a bug and should already be the case

**Comment by AdhemarVandamme** [comment]
@realvictorprm I suppose this issue could be considered a bug (in the compiler) rather than a feature suggestion/request. Does this mean I should report this someplace else?

**Comment by voronoipotato** [comment]
🤷‍♂

**Comment by realvictorprm** [comment]
cc @dsyme. Simple to answer this question from your point.

**Comment by dsyme** [comment]
This is now donw
