### ISSUE TITLE
Map.change

### ISSUE THREAD

**Issue by Frassle** [fsharp/fslang-suggestions#742]
I propose we add an Update method to the Map type.
`Map.Update: (key : 'Key) -> (updater : ('Value option -> 'Value) -> Map<'Key, 'Value>`

It's a fairly common operation to need set the values in a map based on values already present, using the current public API this always requires two traversals thorough the tree structure of the map (TryFind then Add).

```
map.TryFind key |> updater |> map.Add key
```

As a built in (with access to the tree structure) this can be done in one tree traversal.

## Pros and Cons 

The advantages of making this adjustment to F# are a built in function for a common operation that is more performant than is possible to write currently.

The disadvantages of making this adjustment to F# are an increase to API area. Relatedly possible contention over exactly how this method should look (e.g. should the updater be `'Key -> 'Value option -> 'Value`, should it be a voption or option, etc)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Proposed implementation: https://github.com/dotnet/fsharp/pull/6876

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by 7sharp9** [comment]
You can use an indexer which acts like an update.

**Comment by KevinRansom** [comment]
@7sharp9 the indexer is a getter only:  https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/map.fsi#L46
````
   member Item : key:'Key -> 'Value with get
````

**Comment by 7sharp9** [comment]
Doh it was late at night, I meant Add is the same as update.

**Comment by Frassle** [comment]
Add is the same as update in that it allows you to set a key already set. If they new value doesn't depend on the old value that's fine. If you want to do something like "add 1 to current value, or set to 0" you need to TryGetValue then Add which is two traversals. With Update you can do that operation with only one traversal through the tree (`map.Update (Option.map (+1) >> Option.defaultValue 0) key`)

**Comment by 7sharp9** [comment]
@Frassle Sure, that clarifies the intent.

**Comment by cartermp** [comment]
In general I'm in favor, would like @dsyme's take

**Comment by Tarmil** [comment]
Maybe not worth it because it's a much rarer use case, but a more feature-complete function would be:

```fsharp
Map.Update : 'Key -> ('Value option -> 'Value option) -> Map<'Key, 'Value>
```

which would also allow you to remove a value.

**Comment by Frassle** [comment]
That's not a bad idea. Will await any input from dsyme and others but happy to work that in if it's agreed.

**Comment by dsyme** [comment]
I'm not yet 100% sold.

* What about lists, arrays, sets?  Should they have an index-based functional update operator?  Would it have the same signature (I don't think it would, as the index would need to be in-bounds).

* Perhaps `updateWith` is a better name.

**Comment by Frassle** [comment]
> Perhaps updateWith is a better name.

Sure that matches other core functions well.

> What about lists, arrays, sets? Should they have an index-based functional update operator? Would it have the same signature (I don't think it would, as the index would need to be in-bounds).

Could do, I think the only difference would be the input would always be a `'Value` not a `'Value option`.
Could still do @Tarmil idea of allowing removal though. Maybe too complex but could also allow the index one past the end to allow updateWith to grow the array/list (would need input to be an option again in this case)

Not sure about Sets, there aren't any other index based functions for sets, the key is the value so updateWith would be `'Value -> ('Value option -> 'Value option) -> Set<'Value>`, which is certainly doable if we want it for consistency but because you've already got hold of the value it's no better than just calling Add/Remove yourself.
```
Set.UpdateWith set key updater =
    match updater key with
    | Some v -> set.Add v
    | None -> set.Remove key
```
---
From the PR thread:
> Would also like to see this performance-tested

Is there a standard for doing this? Do we add perf test to corelib tests anywhere?

**Comment by cartermp** [comment]
@Frassle About perf, generally we'd like to see a BenchmarkDotNet run with this compared to the current pattern you described in your PR. So you could have a baseline member that does the `tryFind` -> `add` operation and the other that calls into this.

**Comment by Frassle** [comment]
So I ran a test that fills a map with keys 0 to Length and then updates each key from 0 to Length * 2 with the the current value (or zero) + the key. 
```
|   Method | Length |            Mean |          Error |         StdDev | Ratio |
|--------- |------- |----------------:|---------------:|---------------:|------:|
| Original |      1 |        304.4 ns |       2.104 ns |       1.865 ns |  1.00 |
|      New |      1 |        243.5 ns |       2.349 ns |       1.834 ns |  0.80 |
|          |        |                 |                |                |       |
| Original |     10 |      5,974.3 ns |      45.702 ns |      42.749 ns |  1.00 |
|      New |     10 |      5,148.2 ns |      22.191 ns |      20.758 ns |  0.86 |
|          |        |                 |                |                |       |
| Original |    100 |    110,567.9 ns |     548.183 ns |     512.770 ns |  1.00 |
|      New |    100 |     94,833.8 ns |     362.864 ns |     321.670 ns |  0.86 |
|          |        |                 |                |                |       |
| Original |   1000 |  1,711,008.3 ns |  10,470.529 ns |   9,794.139 ns |  1.00 |
|      New |   1000 |  1,434,082.9 ns |  11,840.721 ns |  11,075.817 ns |  0.84 |
|          |        |                 |                |                |       |
| Original |  10000 | 25,077,143.9 ns | 156,197.020 ns | 146,106.790 ns |  1.00 |
|      New |  10000 | 21,608,700.6 ns | 199,693.517 ns | 166,753.131 ns |  0.86 |
```

So update was about 15% faster for this case. I'd guess so much cost is just allocating new map nodes the efficiency of only traversing the tree once instead of twice doesn't save half the total time.

**Comment by cartermp** [comment]
@Frassle Is the code sharable? Would also like to see `MemoryDiagnoster` added to look at allocations.

**Comment by Frassle** [comment]
I'm away from home for a week but can share it when I'm back, as well as getting memory stats

**Comment by Frassle** [comment]
With MemoryDiagnoser (https://gist.github.com/Frassle/684ae1ca4b8a1f90fdd830755b17c067)
```
|   Method | Length |            Mean |         Error |        StdDev | Ratio |     Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|--------- |------- |----------------:|--------------:|--------------:|------:|----------:|---------:|---------:|-----------:|
| Original |      1 |        280.9 ns |      1.808 ns |      1.692 ns |  1.00 |    0.1712 |        - |        - |      360 B |
|      New |      1 |        238.5 ns |      1.506 ns |      1.335 ns |  0.85 |    0.2060 |        - |        - |      432 B |
|          |        |                 |               |               |       |           |          |          |            |
| Original |     10 |      5,777.7 ns |     27.553 ns |     25.773 ns |  1.00 |    2.2812 |        - |        - |     4800 B |
|      New |     10 |      4,888.2 ns |     20.315 ns |     19.002 ns |  0.85 |    2.5253 |        - |        - |     5304 B |
|          |        |                 |               |               |       |           |          |          |            |
| Original |    100 |    104,326.4 ns |    270.872 ns |    226.191 ns |  1.00 |   35.4004 |        - |        - |    74256 B |
|      New |    100 |     82,219.7 ns |    383.111 ns |    358.362 ns |  0.79 |   37.5977 |        - |        - |    79080 B |
|          |        |                 |               |               |       |           |          |          |            |
| Original |   1000 |  1,588,858.5 ns |  8,979.609 ns |  7,960.190 ns |  1.00 |  498.0469 |        - |        - |  1046928 B |
|      New |   1000 |  1,397,718.7 ns | 12,285.938 ns | 11,492.274 ns |  0.88 |  521.4844 |        - |        - |  1094952 B |
|          |        |                 |               |               |       |           |          |          |            |
| Original |  10000 | 24,381,160.1 ns | 79,151.444 ns | 74,038.310 ns |  1.00 | 4500.0000 | 343.7500 | 156.2500 | 13708752 B |
|      New |  10000 | 20,842,929.8 ns | 64,685.572 ns | 54,015.382 ns |  0.85 | 4656.2500 | 343.7500 | 156.2500 | 14188776 B |
```

The extra allocations are the cost of allocating a closure on each loop. Could try another benchmark with a fixed closure.

**Comment by cartermp** [comment]
@Frassle That would be great! Though I think the additional allocations are probably fine. They're proportional which is what matters. When one approach starts to scale faster we get worried, but this doesn't seem to be the case here.

@dsyme @tihan any additional thoughts?

**Comment by dsyme** [comment]
> @dsyme @TIHan any additional thoughts?

I do think the more complicated signature (which includes removal) makes this too hard to use in the most common case (updating an existing key to a new key).

What are the corresponding operations in `ImmutableCollections`?

**Comment by Frassle** [comment]
There's no similar method in ImmutableCollections. The closest thing in the core libraries is ConcurrentDictionary AddOrUpdate (https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate?view=netframework-4.8)

That would be `'key -> 'value -> 'value` (or `'key -> 'value -> 'arg -> 'value`, which I assume is for minimising closure allocations).

@cartermp, I did another benchmark run such that only one FSharpFunc needed to be allocated and that resulted in a fixed 24 bytes extra allocated vs TryFind/Add for all the benchmark sizes.

**Comment by dsyme** [comment]
From the OCaml docs:

```
val change : ('k, 'v, 'cmp) t ->

       'k -> ('v option -> 'v option) -> ('k, 'v, 'cmp) t

change map key f updates the given map by changing the value stored under key according to f. Thus, for example, one might write:

    change m k (function None -> Some 0 | Some x -> Some (x + 1))

to produce a new map where the integer stored under key k is incremented by one (treating an unknown key as zero).
```

I'm somehow inclined to use the OCaml name and signature directly?

**Comment by cartermp** [comment]
I think I do prefer the OCaml name to `Update`.

**Comment by Frassle** [comment]
Updated the PR. Renamed it to Change and made the function option to option to allow removal as well as modification.

Getting late here so will double check it over tomorrow.

**Comment by Frassle** [comment]
For anyone who want's a method with this signature today you can use the following. It's not as efficient as when it's built in but it has made some of our code nicer to write.

```
let change key f map =
  Map.tryFind key map
  |> f
  |> function
     | Some v -> Map.add key v map
     | None -> Map.remove key map
```

**Comment by cartermp** [comment]
@dsyme any resolution here?

**Comment by Frassle** [comment]
@cartermp @dsyme any chance of resolving this, I've still got https://github.com/dotnet/fsharp/pull/6876 open to add this which I can update to what ever is the latest target branch.

**Comment by abelbraaksma** [comment]
Yeah, this would be great to have, the benefits in preformance and simplicity in the call are worth adding it :+1:

**Comment by cartermp** [comment]
I think this addition is for @dsyme to give 👍 or 👎 . I'm personally in favor

**Comment by dsyme** [comment]
My apologies for the long delay on this, mea culpa.  Please do @dsyme ping me (in theory I get notifications for those) and also ping me on twitter

Approved.  

I would to see updaters for list, array, seq but let's do those separately. Maybe:

      List.changeAt:  int -> ('T option -> 'T option) -> 'T list -> 'T list
      Array.changeAt:  int -> ('T option -> 'T option) -> 'T[] -> 'T[]
      Seq.changeAt  int -> ('T option -> 'T option) -> seq<'T> -> seq<'T>

where List/Array have the invariant that 'int' must be in `[-1..N]` (allowing prepend/append)?

All of these look useful TBH.  I'd also like to see the simpler

      List.replaceAt:  int -> 'T -> 'T list -> 'T list
      Array.replaceAt:  int -> 'T -> 'T[] -> 'T[]
      Seq.replaceAt:  int -> 'T -> seq<'T> -> seq<'T>

      List.insertAt:  int -> 'T -> 'T list -> 'T list
      Array.insertAt:  int -> 'T -> 'T[] -> 'T[]
      Seq.insertAt:  int -> 'T -> seq<'T> -> seq<'T>

      List.removeAt:  int -> 'T list -> 'T list
      Array.removeAt:  int -> 'T[] -> 'T[]
      Seq.removeAt:  int -> 'T -> seq<'T> -> seq<'T>

and possibly even these:

      List.insertManyAt:  int -> 'T list -> 'T list -> 'T list
      Array.insertManyAt:  int -> 'T[] -> 'T[] -> 'T[]
      Seq.insertManyAt:  int -> 'T -> seq<'T> -> seq<'T>

      List.removeMany:  int -> int -> 'T list -> 'T list
      Array.removeMany:  int -> int -> 'T[] -> 'T[]
      Seq.removeMany:  int -> int -> 'T -> seq<'T> -> seq<'T>
