### ISSUE TITLE
Allow record types to be defined as having all the properties of another type (

### ISSUE THREAD

**Issue by rjwpope** [fsharp/fslang-suggestions#744]
# Records Types based on other Record Types

I propose we provide a syntax which allows for defining a record type which has all the properties of another record type and some additional properties

I often find my self in a situation where I want to have a type which is logically an extension of another type and should have all the same properties but need not have any technical inheritance. e.g.
```
type Request ={
    Title: string
    User: UserId
   Details: ...
}

type AcceptedRequest = {
    Title: string
    User: UserId
    Details: ...
    AcceptedBy: UserId
    AcceptedAt: Dateime
}
```

I propose a syntax using the `with` keyword which would alow the above to be written as:
```
type Request ={
    Title: string
    User: UserId
   Details: ...
}

type AcceptedRequest = {
    Request with
        AcceptedBy: UserId
        AcceptedAt: Dateime
}
```

I propose that this be a syntax change only and that the types `Request` and `AcceptedRequest` in this example should have no inheritance relationship thus keeping the current situation of Records being sealed types.

The existing way of approaching this problem in F# is either:
1. Copy and paste all the properties to each of the logical extensions (maintenance headache)
2. Have each of the logical extensions have a property which contains the original type which causes taller tree structures and can cause an API to become confusing when the properties all logically belong to the same entity

## Pros and Cons 

The advantages of making this adjustment to F# are
It would simplify creation and maintenance of types of this nature

The disadvantages of making this adjustment to F# are 
It may add confusion for those expecting an inheritance relationship

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): (Unknown)

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
>can cause an API to become confusing when the properties all logically belong to the same entity

An `AcceptedRequest` contains `Accepted` and `Request`. You should be able to extract the `Request` from an `AcceptedRequest`. What's wrong?

**Comment by cartermp** [comment]
> I propose that this be a syntax change only and that the types `Request` and `AcceptedRequest` in this example should have no inheritance relationship thus keeping the current situation of Records being sealed types.

What's written as the suggestion here is record inheritance, otherwise you wouldn't be able to access any of the fields defined within `Request` from an instance of `AcceptedRequest`.

Closing as per #100 which has been denied. There's a big can of worms to consider with record inheritance (ever wondered why records aren't in C# yet? 😉), and given that we discourage inheritance in F# I doubt this will be reconsidered.

**Comment by Happypig375** [comment]
This use case is now covered by [spread operator](https://github.com/fsharp/fslang-suggestions/issues/1253).
