### ISSUE TITLE
Allow optional members to be inferred as part of signature when appropriate

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#745]
# Allow optional members to be inferred as part of signature when appropriate

I propose we allow optional members to be inferred as part of inferred signature for member calls.

The existing way of approaching this problem in F# is writing wrapper functions.

```fs
type C() = static member M x = ()
let x = 1 |> C.M //ok
```
```fs
type C() = static member M ?x = ()
let x = 1 |> C.M //proposed to allow, currently error FS0001: This expression was expected to have type 'int' but here has type 'unit'    
```
```fs
type C() = static member M ?x = ()
let x = 1 |> (fun x -> C.M x) //ok, but ugly workaround
```
```fs
type C() = static member M (x : int, ?y : int) = printfn "%A, %A" x y
C.M 1 //prints "1, <null>"
1 |> C.M //prints "1, <null>"
C.M(1, 2) //prints "1, Some 2"
(1, 2) |> C.M //error currently, will print "1, Some 2"
```

The current proposal will provide no way to specify `?x = Some 1` like in member calling.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. reduced boilerplate
2. better uniformity between member calling and pipelining
3. reduce surprises when trying to pipeline

The disadvantage of making this adjustment to F# is added complexity.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S~M

Related suggestions: Nope

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
This is already decided in F# 1.0, in the sense that using `C.M` as a first-class value includes its optionals as non-optional, and these are not available transitively, that is, optionality is not propagated through type inference.
