### ISSUE TITLE
Float32 literals without the numeric dot

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#750]
# Float32 literals without the numeric dot

I propose we allow float32 literals without the numeric dot.

The existing way of approaching this problem in F# is having that extra dot when typing float32 literals with that extra, ugly dot. Consider the beautiful decimal literals:
```fs

Microsoft (R) F# Interactive version 10.4.0 for F# 4.6
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 750m;;
val it : decimal = 750M

> 750M;;
val it : decimal = 750M

> 750f;;

  750f;;
  ^^^^

stdin(3,1): error FS1156: This is not a valid numeric literal. Valid numeric literals include 1, 0x1, 0b0001 (int), 1u (uint32), 1L (int64), 1UL (uint64), 1s (int16), 1y (sbyte), 1uy (byte), 1.0 (float), 1.0f (float32), 1.0m (decimal), 1I (BigInteger).

> 750.f;;
val it : float32 = 750.0f
```

## Pros and Cons 

The advantages of making this adjustment to F# are consistency between literals: `750.` is float, `750m` is decimal, and `750f` is float32.

The disadvantage of making this adjustment to F# is implementation complexity.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: https://github.com/dotnet/fsharp/issues/6992

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by 7sharp9** [comment]
Having to put the dot is rather annoying.

**Comment by Happypig375** [comment]
I proposed `ff` and `FF` for floats at https://github.com/fsharp/fslang-suggestions/issues/737#issuecomment-489321141 but single-character suffixes would be more appropriate.

**Comment by cartermp** [comment]
Generally I'd be supportive of this, since the decimal case is already supported.

**Comment by realvictorprm** [comment]
If this is approved I can take care of the implementation. It's rather simple to implement, just a change in the parse&lexer I guess.

**Comment by dsyme** [comment]
Yes, this is reasonable. Marking as approved

**Comment by abelbraaksma** [comment]
@gdziadkiewicz, nice to see you working on this. Are you also doing the RFC? I know it's a small language change, but I believe we should always have an RFC in place to cover language feature changes.

I can make one, I'm just holding off in case we would both be working on it ;).

**Comment by gdziadkiewicz** [comment]
If you are willing to create the RFC then please do so - I didn't start working on it yet :)

**Comment by abelbraaksma** [comment]
@Happypig375, could you give this suggestion a more meaningful title please? Something like 'Allow literal integers to be float when they have a suffix "f" '?

**Comment by abelbraaksma** [comment]
@gdziadkiewicz, I totally forgot, thanks for doing the work! :100:

**Comment by dsyme** [comment]
closing as this has been completed, see the RFC

**Comment by abelbraaksma** [comment]
@dsyme, yes it is, but there's small gotcha though, I reported it here: https://github.com/dotnet/fsharp/issues/9338 (though I think it's too minor to warrant a fix before F# 5).
