### ISSUE TITLE
new System.IO.MemoryStream // Now without parentheses!

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#753]
# new with partial application

I propose we support new with partial application.

The existing way of approaching this problem in F# is having that ugly closure AND parentheses surrounding it.

Consider
```fs
x
|> System.Convert.FromBase64String
|> (fun x -> new System.IO.MemoryStream(x))
```
The following should all be supported:
```fs
x
|> System.Convert.FromBase64String
|> (fun x -> new System.IO.MemoryStream x)
```
```fs
x
|> System.Convert.FromBase64String
|> (new System.IO.MemoryStream)
```
```fs
x
|> System.Convert.FromBase64String
|> new System.IO.MemoryStream
```
```fs
x
|> (System.Convert.FromBase64String >> new System.IO.MemoryStream)
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Beauty
3. Consistency
4. Ease of understanding

The disadvantage of making this adjustment to F# is the implementation effort required.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by yatli** [comment]
It doesn't look like a "partial application" because the constructor is tuple-based.
Will cause confusion in some cases, e.g:

```F#

type Foo() =
    new Foo(x: int)

let a = new Foo
let b = new Foo()
```

in the example, `a` ends up being a method group without actually calling the constructor, or resolving the correct overload.

**Comment by Happypig375** [comment]
If all type information are present, then the correct overload should be inferred. Error otherwise.

**Comment by yatli** [comment]
hmm, looks like it's already possible now:

![image](https://user-images.githubusercontent.com/20684720/59502059-768f7b80-8ecf-11e9-9dde-4a5eac72236e.png)

**Comment by yatli** [comment]
the warning though, is about not using `new`, and aligns with your proposal.

**Comment by charlesroddie** [comment]
Conciseness is a minor issue here.

A larger issue is how to keep track of disposables.

`new` is used on construction, but a function that returns a new IDisposable isn't called with `new`.
Not sure if there is in theory any way to track when a new IDisposable is created and output when calling a function and then needing to be marked with new to avoid a warning.

(Related work: color https://github.com/dotnet/fsharp/issues/4618)

**Comment by dsyme** [comment]
I don't see the value in this - the aim of forcing `new` is to force people to be a bit more explicit for exactly where IDisposable values are created. Allowing currying in this case just isn't of great value and undermines that explicitness
