### ISSUE TITLE
Special inline active patterns that have an effect on exhaustiveness warnings

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#755]
I propose we let simple inline active patterns have an effect on exhaustiveness, through an `[<ExhaustionAnalysis>]` attribute.

Consider:
```fs
type DU = DU1 | DU2 | DU3
let inline (|DU1or2|_|) x = match x with DU1 | DU2 -> Some DU1or2 | _ -> None
let du = match System.Random().Next 3 with 0 -> DU1 | 1 -> DU2 | _ -> DU3
match du with
| DU1or2 -> printfn "1 or 2"
| DU3 -> printfn "3"
```
```fs
  match du with
  ------^^
warning FS0025: Incomplete pattern matches on this expression. For example, the value 'DU1' may indicate a case not covered by the pattern(s).
```

Compare with:
```fs
type DU = DU1 | DU2 | DU3
[<ExhaustionAnalysis>]
let inline (|DU1or2|_|) x = match x with DU1 | DU2 -> Some DU1or2 | _ -> None
let du = match System.Random().Next 3 with 0 -> DU1 | 1 -> DU2 | _ -> DU3
match du with
| DU1or2 -> printfn "1 or 2"
| DU3 -> printfn "3"
// No warnings
```

The existing way of approaching this problem in F# is copying the active pattern everywhere. It's hard to update them.

## What is allowed?

In line with the current exhaustion analysis, aka
- Function body only contains a match
- No when
- The match doesn't call other non-inlined functions
- No mutation
- No non-match expressions
- Patterns only

So, these will not be considered:
```fs
[<ExhaustionAnalysis>]
let inline (|Nope|_|) x = match x with DU1 | DU2 -> if ExternalBoolean then Some Nope else None | _ -> None
//error at if
```
```fs
[<ExhaustionAnalysis>]
let inline (|Nope2|_|) x = match x with DU1 | DU2 when false -> Some Nope2 | _ -> None
//error at when
```
```fs
[<ExhaustionAnalysis>]
let inline (|Nope3|_|) x = match x with DU1 | DU2 -> printf "Hi"; Some Nope3 | _ -> None
//error at printf
```
```fs
[<ExhaustionAnalysis>]
let (|Nope4|_|) x = match x with DU1 | DU2 -> Some Nope4 | _ -> None
//error at let, inline must be declared
```
and all other stuff that cause exhaustion analysis to be indeterminate.
This will be fine:
```fs
[<ExhaustionAnalysis>]
let inline (|DU1or2|_|) x = match x with DU1 | DU2 -> Some DU1or2 | _ -> None
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. More uses of exhaustion analysis along with active patterns
2. No need for unnecessary exception-raising branches
3. Increased quality of life of developers - the compiler does the heavy lifting

The disadvantage of making this adjustment to F# is the huge amount of effort this would probably require.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): L ~ XL

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by smoothdeveloper** [comment]
Do we actually need a specific attribute or this could be added without breaking changes?

Existing warning on currently exhaustive checks (similar to sample) would disappear, is there anything else?

Somehow related #731

**Comment by Happypig375** [comment]
#731 us not really related. #731 modifies the DU itself, this modifies active patterns. However, both influence exhaustive checks.

**Comment by Happypig375** [comment]
For instance, this can be possible as well:
```fs
[<ExhaustionAnalysis>]
let inline (|RecordContainsTrue|_|) x = match x with { X = true } -> Some RecordContainsTrue | _ -> None
match { X = SomeBoolean } with
| RecordContainsTrue -> printfn "true"
| { X = false } -> printfn "false"
//No warnings.

**Comment by smoothdeveloper** [comment]
@Happypig375 what would be the cons of having this work as is without the attribute (assuming we are fine with incorrect exhaustivity warnings currently showing eventually going away)?

**Comment by Happypig375** [comment]
Unpredictability - how would you be sure that your active pattern does affect exhaustivity? Surely the compiler cannot tell if all active patterns are pure. Some might call impure functions and suddenly unexhausted match warnings pop up everywhere.

That is the single reason that the attribute should be required.

**Comment by dsyme** [comment]
This topic was really decided in F# 1.0 - exhaustion analysis is indeed lost when you start using active patterns to cover a subset of cases.  But the complexity of any feature to try to recover it in such cases is just too high and difficult ot drive/learn, and likely creates many many problems.  Better just to make the extra unreachable case explicit or find another way to deal with the problem

**Comment by Happypig375** [comment]
@dsyme Would this also be a valid reason for https://github.com/fsharp/fslang-suggestions/issues/996 ?

**Comment by dsyme** [comment]
@Happypig375 No, I don't think so. Raising `failwith "unreachable"` is totally fine, since exception stack traces and debugging report the source code location of the exception being raised.  The fact that MatchFailureException records this information is just a quirk related to how it was done in OCaml

**Comment by Happypig375** [comment]
@dsyme We can't just assume that these failures won't happen in production as a result of programmer error.

**Comment by dsyme** [comment]
Yes, I understand, but having a special construct for this is just this case is not of particular interest.  `failwith "unreachable"` or any variation on that is good enough, and if you want it to be more explicit you can program that up using normal means.

**Comment by Happypig375** [comment]
What about a function within FSharp.Core? It can make use of optional parameters with `CallerMemberName`, `CallerFilePath`, and `CallerLineNumber` to provide a descriptive message.
