### ISSUE TITLE
add a keyword for module-local construction but public deconstruction of types

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#76]
**Submitted by Adnan Gazi on 3/12/2016 12:00:00 AM**  
**5 votes on UserVoice prior to migration**  

Similar to dependant types, except you wouldn't enforce the predicate on which the type is dependant on to be defined WITH the type.

This keyword could stop clients of a module from constructing the type, but would allow them to 'see' that it exists, and therefore allow them to deconstruct it for their own use.
For example, if you want a string constrained to 50 chars, you could have

```
type String50 = constrained String50 of string
let createString50 s = if String.length s <= 50 then Some s else None
where 'createString50' is a constructor.
```

Correct me if I am mistaken, but it seems to be a lot less complicated than dependant types since the dependancy is implicit, and therefore wouldn't be as difficult for the type inference

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12913179)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12913179-add-a-keyword-for-module-local-construction-but-p.md#comments)

**Comment by dsyme** [comment]
There are lots of ways to implement constrained types already, e.g. by a class definition, or by a record/union type with a private/internal representation (basically an Abstract Data Type).   Adding more ways to do the same thing is thus not the right thing to do.
