### ISSUE TITLE
Allow to use delegate constructors as functions

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#760]
Similar to the suggestion [Allow to use struct constructors as functions](https://github.com/fsharp/fslang-suggestions/issues/455), it would be nice if we use constructors of delegates as functions.

The existing way of approaching this problem in F# is creating wrapper functions.

```fs
let x = System.Converter<_, _> string // ok
let y = string |> System.Converter<_, _> // FS0805: Invalid use of a delegate constructor. Use the syntax 'new Type(args)' or just 'Type(args)'.
let z = string |> (fun x -> System.Converter<_, _> x) // ugly
```
This is especially useful for making `Action`s and `Func`s explicitly.

## Pros and Cons 

The advantages of making this adjustment to F# are consistency, conciseness, blah, blah

The disadvantage of making this adjustment to F# is none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions:
Class constructors as functions - #158
Struct constructors as functions - #455

Both were completed for F# 4.0.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by charlesroddie** [comment]
These things are very rare and at the outer reaches of the type system, so while this feature would hurt no-one, it may cost more characters to implement than it would end up saving in avoiding `fun x -> ... x`.

**Comment by cartermp** [comment]
I think this makes sense from a consistency perspective. I don't have a good sense for how often F# developers use delegates - no telemetry in either the compiler or standard library :)

**Comment by Happypig375** [comment]
I hit this while trying to work around #248.

**Comment by 7sharp9** [comment]
In my experience they are only used when necessary, e.g. retro C# libs.

**Comment by dsyme** [comment]
I will decline this, I think it's not necessary to allow piping and so on for these constructs, delegates are primarily for interop.
