### ISSUE TITLE
regex literal 

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#763]
regex literal like a lot of other langs.  as follow:
```javascript
let re = /xyz\r\n/i
```
regex has already very complexed itself, and use string literal that need escape into `Regex` ctor become more difficult to read.

**Comment by Happypig375** [comment]
https://github.com/fsprojects/FSharp.Text.RegexProvider

**Comment by Happypig375** [comment]
http://fsprojects.github.io/FSharp.Text.RegexProvider/

**Comment by Happypig375** [comment]
Typed regexes are better than using the .NET regexes. They provide better type safety.

**Comment by Happypig375** [comment]
For reference, the compiler itself checking for validity of regexes probably will not be implemented for C#: https://github.com/dotnet/csharplang/issues/371#issuecomment-350601503

**Comment by 7sharp9** [comment]
You can use portacode to check external code validity, I do this in a
branch of myriad.

**Comment by 0x53A** [comment]
> For reference, the compiler itself checking for validity of regexes probably will not be implemented for C#: dotnet/csharplang#371 (comment)

They did add an analyzer: https://github.com/dotnet/roslyn/pull/23984

![image](https://user-images.githubusercontent.com/4236651/60506298-d8205a00-9cc5-11e9-8dbe-6bd30e296771.png)

**Comment by Happypig375** [comment]
Thus the suggestion for a whole new language syntax for regexes is implicitly rejected.

**Comment by 0x53A** [comment]
yes, but the analyzer + editor tooling solves 95% of the issues.

A type provider in F# can't - for example - provide coloring or reference highlighting.

It would be great to have this: https://github.com/fsharp/fslang-suggestions/issues/556

**Comment by xp44mm** [comment]
string regex have another level escape:
```js
let re = Regex ("^\"[^\"]*(\"\"[^\"]*)*\"",RegexOptions....)
===
let re = /^"[^"]*(""[^"]*)*"/
```

**Comment by Happypig375** [comment]
Use triple quoted strings.

**Comment by cartermp** [comment]
I think this is more of a tooling concern than language concern. Even if we had a regex string literal type, unless you had editor tools that could easily distinguish things, it'd be just as hard to use.

The tooling side is tracked here, but the actual mechanism may require some work before it's ready to be exposed on the VS side of things: https://github.com/dotnet/roslyn/issues/34979

**Comment by xp44mm** [comment]
@Happypig375 do you see the last `"`? this char result in no work triple quoted string.

**Comment by Happypig375** [comment]
`"""^"[^"]*(""[^"]*)*" """.TrimEnd()`
