### ISSUE TITLE
Allow static local functions

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#765]
# Title of Suggestion

I propose we allow for the declaration of static local functions:

```fsharp
// Do nothing, but more static-y!
let f() =
    static let g () = ()
    g ()
    ()
```

This would allow the use of inner/local functions and types like `Span`, which is not allowed today.

## Pros and Cons 

The advantages of making this adjustment to F# are

* Allows for passing `byref` or `byref`-like structs (such as `Span<'T>`) to a local function
* Allows for trivial refactoring into a separate function - just copy/paste and remove the `static`

The disadvantages of making this adjustment to F# are

* Another way to write inner functions: `let`-bound functions, `fun`-declared lambdas, and now `static let`-bound functions

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by charlesroddie** [comment]
This seems interesting. What do I need to know to understand this suggestion?  In classes, static means not depending on the instance. Does static here also mean that g doesn't depend on something?

**Comment by cartermp** [comment]
It's akin to static local functions in C#, so it's effectively correct to say that `g` doesn't depend on something. Basically, it's a completely isolated F# function embedded within another function. You can only enforce this by convention today, since any inner function has access to values in its enclosing scope:

```fsharp
let multByTwo x = 
    let g y = x + y
    g x
```

This has tremendous upside as a programming technique. However, it comes at a cost: parameters passed to `g` cannot be guaranteed to live on the stack. This means that if you're working with a byref-like struct such as `Span<'T>`, you have to factor that inner function out into a "normal" function.

If `g` where a static inner function, it could not access `x` unless `x` was declared as a parameter to it:

```fsharp
let multByTwo x = 
    static let g x y = x + y
    g x x
```

The primary motivator here is allowing the use of types like `Span<'T>`. It can also simplify refactoring: just copy/paste and remove the `static` keyword, and it's always going to work.

**Comment by dsyme** [comment]
Why not just factor out the function to a helper?

Note there is an interaction with the existing `static let` in a class.  For a generic class, this is static w.r.t. the type variables, so 

    type C<'T>() =
        static let mutable x = ...

results in a different `x` for each `T`.  Would that also apply here?  It would be odd if it did, and odd if it didn't.

Additionally, one reason we don't support this is that inlining a function implementation is no longer as intuitive - if `multByTwo` is used in two places you can't inline it into each.  That's not a technical problem - we could restrict inlining - but it indicates that the feature may add a kind of cognitive dissonance to F#.  Personally I believe I would find it harder to think and reason about code containing `static` constructs - I would always be wondering "are they really necessary", "is this for performance", "can I remove this 'static' safely" and so on.

**Comment by Happypig375** [comment]
What about disallowing static values but only permitting static functions?

**Comment by dsyme** [comment]
> What about disallowing static values but only permitting static functions?

I guess it's technically feasible.  But the problem is that this is all feature leak:

1. C#/.NET supports `Span` for performance, but it is not orthogonal with other language features, so leads to all sorts of odd rules

2. Because these odd rules exist, we start pushing new constructs into the language which extend the places where you can use those odd things

3. Those constructs themselves are not orthogonal to other language features

I'd prefer to keep non-orthogonal features like `Span` "in their cage" rather having them spread their roots through the language design.  If part of this is that `Span` code gets written using either helper functions or `static let` in classes then that's fine

**Comment by cartermp** [comment]
I think part of the issue with "keeping features like `Span` 'in their cage'" is that `Span` is now fundamental to .NET that is fully proliferated across the stack. While it's not used directly by most programmers, I think it's fair to say that anyone who _must_ drop down to use it would expect it to work well everywhere (subject to its limitations of being stack-bound). The pattern of "declare an inner function to do the work instead of a `private` function above" is highly-used in F# and it is also highly surprising to programmers that `Span` is not allowed there.

An alternative to this would be to optimize local functions that only use values explicitly passed to them. This would imply compiler analysis in two ways:

1. **Function only acts on its parameters nothing** - if a `byref` is already being passed, and the programmer attempts to access a value outside its scope, an error is given either on the captured value or the `byref` parameter
2. **Function accesses a value outside it scope** - if the programmer attempts to add a `byref` parameter, it is an error like today

Existing analysis to prevent first-class use of that function would still apply

**Comment by dsyme** [comment]
> I think part of the issue with "keeping features like Span 'in their cage'" is that Span is now fundamental to .NET and it is fully proliferated across the stack.

If this is truly the case then it is a disaster for .NET - there is no chance of .NET being  approachable for entry-level programmers if they regularly encounter Span, let alone a bunch of Span-related language weirdness.   However I haven't noticed it be as bad as you mention.  

I honestly think we don't want to go down this route.  The use can and should just lift this code out to helper code.  The over-use of inner functions can lead to real code-comprehension problems in any case, and even more so when these interact with odd language rules.  

> , I think it's fair to say that anyone who must drop down to use it would expect it to work well everywhere (subject to its limitations of being stack-bound). 

> An alternative to this would be ... local functions that only use values explicitly passed to them...

Yes, it would be reasonable to extend the existing "byref" rules to allow non-capturing locally defined functions to be used with the `Span` type - and then to guarantee to represent those functions as new methods taking only those arguments (we do actually apply this optimization for optimized code, and it would be easy enough to implement for other code).  But I wouldn't want this to correspond to a `static let` extension complexifying the core language outside the `Span`/`byref` use case.

**Comment by cartermp** [comment]
Okay, that seems fair. I'll close this out and file an issue on dotnet/fsharp then, since this seems more like extending compiler analysis than a language suggestion.

**Comment by dsyme** [comment]
> Okay, that seems fair. I'll close this out and file an issue on dotnet/fsharp then, since this seems more like extending compiler analysis than a language suggestion.

I guess strictly speaking it's part of the language design, but yes, I think it can be seen as a refinement to the Span/byref RFC
