### ISSUE TITLE
Improve interop to `Nullable` optional parameters

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#774]
I propose we improve interop to C#-defined `Nullable`-typed optional parameters

Consider a C# definition 
```fsharp
        public int SomeMethod(int? channels = 0, int? ratio = 1)
```
The compiled form of this uses `Nullable` typed values for the parameters with default value `nullref`.  

We do not recognise this in F# and when calling and providing a value we require
```fsharp
    C.SomeMethod(channels = Nullable 3)
    C.SomeMethod(channels = Nullable 3, ratio = Nullable 3)
    C.SomeMethod(ratio = Nullable 3)
```

Alternatives that achieve the same effect are 

1. to allow auto-conversion from `T` to `Nullable<T>` at method calls.  Indeed this is probably the best solution.

2. some even more aggressive auto-conversion rule for `T` to `Nullable<T>`

## Pros and Cons 

The advantages of making this adjustment to F# are interop with modern C# becomes smoother. 

The disadvantages of making this adjustment to F# are 
* another implicit conversion rule is added.
* we have to be careful this is not a breaking change

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
There is also this case when interoperating with C#-defined optionals, where the use of an F# `Some` value doesn't work as expected:

![image](https://user-images.githubusercontent.com/7204669/61872264-cc960c80-aeda-11e9-8a11-aba301e8d836.png)

Here the compiled form is:
```
.method public hidebysig static class Tensorflow.Tensor 
        'add'(class Tensorflow.Tensor x,
              class Tensorflow.Tensor y,
              [opt] string name) cil managed
{
  .param [3] = "Add"
```
and the C# form is 
```csharp
        public static Tensor add (Tensor x, Tensor y, string name = "Add")
        {
            var dict = new Dictionary<string, object>();
            dict["x"] = x;
            dict["y"] = y;
            var op = _op_def_lib._apply_op_helper("Add", name: name, keywords: dict);
            return op.output;
        }
```

**Comment by dsyme** [comment]
Working on test cases related to this here https://github.com/dotnet/fsharp/pull/7276

Implementation will follow in same PR

**Comment by dsyme** [comment]
@cartermp We have a compatibility problem with this 

Given this:
```
        public int SomeMethod(int? channels = 0, int? ratio = 1)
```

We currently require `Nullable`:

```fsharp
    C.SomeMethod(ratio = Nullable 3)
```
However the natural and "morally correct" thing is to require non-nullable, e.g.
```fsharp
    C.SomeMethod(ratio = 3)
```

The problem is that, if the method is not overloaded, we use a "strong" assumption of Nullable, e.g.
```fsharp
let f x = C.SomeMethod(ratio = x)
```
will infer `Nullable<int>` for the type of `x`.  

I'm not really sure what to do about this.  The current strong assumption of `Nullable` is *not* what we want long term.  I don't mind a type-directed rule of "if the argument has type Nullable than accept it anyway", but such a rule would *not* kick in for cases like the one I mention above.

What do you think our position should be on this?  Should we consider an actual breaking change ("language fix") that would switch to using a type-directed rule instead of the current strong-type-assumption rule? My gut feeling is that the type-directed rule would be adequate (people could adjust there code) but that there would, somehow, be cases where this change would affect real-world code.

**Comment by cartermp** [comment]
My main concern here, though I think this is worth doing, is that usage of this kind of code is much more widespread than I thought. It'd be good to get opinions from folks like @thorium and others on this.

**Comment by Thorium** [comment]
Initially I have more questions than opinions:

So you mean implicit conversion from `T` to `Nullable<T>`, but not from `Nullable<T>` to (like in&out in C#, the covariance/contravariance rules)?

So far the standard F#-type for maybe-monad has been `Option<T>`, and I don't like the way the maybes are multiplying (Option, ValueOption, Nullable, what next). So could they interop somehow better with each other, rather than implicit conversions to the base types?

In C#, null breaks SOLID principles by playing two roles:

1. the special case pattern (GoF/Fowler), 
2. the un-initialized variable (on purpose or by accident)

Which one is this solution focusing to?

Will this cause backward compatibility issues?

**Comment by dsyme** [comment]
> So you mean implicit conversion from T to Nullable<T>, but not from Nullable<T> to T (like in&out in C#, the covariance/contravariance rules)?

No, this is not about a conversion but about proper treatment of nullable-typed optionals coming from C# code.

**Comment by Thorium** [comment]
Ok, I know mostly about SqlProvider, which is pure F#, not using C# Nullables, maybe other Sql tools are affected more.

**Comment by xp44mm** [comment]
Nullable let me confusion:
```F#
let x = Nullable(3)
let ty = x.GetType()

Assert.NotEqual(typeof<Nullable<int>>,ty)
Assert.Equal(typeof<int>,ty)
```
this is Contrary to intuition. may i get the right type?

**Comment by cartermp** [comment]
Closing out as completed for F# 5.

**Comment by abelbraaksma** [comment]
> those is auto drop the Nullable, Contrary to intuition. may i get the right type Nullable<int> from object x?

@xp44mm, I know it’s been two years, but for posterity and others interested: this is just how `GetType()` works in .NET. Use `IsGenericType` and iterate over the type parameters to get the full definition. Here’s one way to get the ‘friendly name’ you seem to be after: https://stackoverflow.com/questions/4185521/c-sharp-get-generic-type-name
