### ISSUE TITLE
Top-down programming support 

### ISSUE THREAD

**Issue by niltok** [fsharp/fslang-suggestions#778]
# Top-down programming support 

(Sorry for my poor English writing)

As the complex `let` binding is hard to read, it’s common to refactor with `let` binding inside the previous binding. Just like this:

```fsharp
let calc arg1 arg2 =
    let x = ...
    let y a = ...
    let z a b =
        let q c = ...
        ...
    ...
```

But if the `let` binding body is really really long, it’s hard to find the main expression of the `let` binding immediately. You need to scroll and scroll. If there is a top-down key word, it would be easier to read. I give a example here using `where` as keyword.

```fsharp
let calc arg1 arg2 = ...
    where z a b = ...
        where q c = ...
    where y a = ...
    where x = ...
```

Thus, the main expression is placed just after the `let` definition. Just read the first line of the binding to know what it returns. Also, with the top-down keyword we can write a function from top to the bottom. Just write the main expression and then write what the dependencies. It’s obviously that human does better on destruction than construction. So it’s easier to write & read functions this way.

## Extra information

Estimated cost: M

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by orthoxerox** [comment]
Something like http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#where-clauses?

**Comment by goldimax** [comment]
@orthoxerox Yeah, my friend told me that both Idris and Coq can do this.

**Comment by Happypig375** [comment]
Visual Studio has collapsible code sections, you can collapse them if you wish to scroll faster.

**Comment by Happypig375** [comment]
Also, you can use ` let ... and ... ` to write these.
```fs
let calc arg1 arg2 = ...
and z a b = ...
and q c = ...
and y a = ...
and x = ...
```
You just need to disable the warning about recursive objects on `x`.

**Comment by goldimax** [comment]
@Happypig375 But `let rec...and` cannot catch the context and you can call the function defined by `and`. This idea is great but not enough.

**Comment by shawn-martin** [comment]
This is somewhat analogous to the requests to remove requirements for types being defined before being used and the knock-on effects on file order in F#. I like the current behavior. When learning Haskell and playing with Idris, the "where" syntax annoyed me. It's just another way to accomplish almost the same thing as let, but differently. I prefer the simplicity of "let" syntax only and I like that I know where to find the result of an expression every time without thinking (at the bottom). I'm curious to see if other people share this opinion.

**Comment by Happypig375** [comment]
You can still collapse code blocks in Visual Studio.

**Comment by cartermp** [comment]
This touches upon the following decision criteria:

> whether this gives multiple ways to achieve the same thing

Which I think would rule this out unless there were more you could accomplish with it than you can today with inner `let-`bound functions. Though I know the pain of large functions with many inner functions declared within, I doubt any alternative syntax for inner functions would be done.

**Comment by Luiz-Monad** [comment]
An easier solution would be just using a syntax highlighter that changes the colour of the let keyword. I have one for parenthesis, its the same syntactical problem, you can solve this at the syntax level with tooling.

**Comment by 7sharp9** [comment]
👿 🥑 
Once you get to the stage where its hard to navigate because the let binding is really really long it's probably time to refactor anyway which would simplify the code and obviate the issue .
