### ISSUE TITLE
allow defining function with generic type parameter within another function

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#78]
# allow defining function with generic type parameter within another function [12940554] #

**Submitted by Gauthier Segay on 3/15/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

I encounter cases where I'd like to define a function taking a generic type parameter within another functions.

```fsharp
type Foo = {Bar: int option; Baz: string option}
let doSomething () =
(**)let writer = Console.Out
(**)let writeOption o =
(* *)match o with
(* *)| Some v -> writer.Write(string v)
(* *)| None -> writer.Write("")
(**)writeOption foo.Bar
(**)writeOption foo.Baz
```

It's not possible to do that right now and even if I define the function outside at module level (with extra writer parameter), I can't curry it to avoid passing the context (writer) parameter I'm trying to elide to keep my code concise.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12940554)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12940554-allow-defining-function-with-generic-type-paramet.md#comments)

**Comment by dsyme** [comment]
This seems to be too corner-case - inner generic functions can be defined, but not with explicit type parameters
