### ISSUE TITLE
Relax RequireQualifiedAccess for record expressions

### ISSUE THREAD

**Issue by debugnik** [fsharp/fslang-suggestions#780]
I propose we relax the rules for record types with `RequireQualifiedAccess` so only one record field needs to be qualified in record expressions.

We can already omit their field qualifiers when the type can be inferred, and a single qualifier is already enough to disambiguate between regular record types too. Thus, asking for every single field to be qualified here seems too verbose.

Short example:
```F#
[<RequireQualifiedAccess>]
type Foo = { A: int; B: int; C: int }

let zero = { Foo.A = 0; B = 0; C = 0 } // This would work
let setAB a b foo = { foo with Foo.A = a; B = b } // This would work too
```

## Pros and Cons 

The advantage of making this adjustment to F# is more ergonomic record expressions when using `RequireQualifiedAccess`. This may make F# codebases less likely to shy away from them as a tool to introduce records without "polluting" field resolution.

The disadvantage of making this adjustment to F# is implementation cost.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S? (We already have this for regular records)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by charlesroddie** [comment]
There is overlapping motivation with https://github.com/fsharp/fslang-suggestions/issues/722 : being explicit about types. That would help with the first example (`let zero = Foo(0, 0, 0)`). But `with` support would be missing: `let setAB a b (foo:Foo) = Foo(a, b, foo.C)`.

**Comment by dsyme** [comment]
The recommendation is this:
```
[<RequireQualifiedAccess>]
type Foo = { A: int; B: int; C: int }

let zero : Foo = { A = 0; B = 0; C = 0 } // This would work
let setAB a b foo : Foo = { foo with A = a; B = b } // This would work too
```

That seems adequate
