### ISSUE TITLE
Relax indentation rules on anonymous records

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#786]
# Relax indentation rules on anonymous records

I propose we relax indentation rules on anonymous records.

The existing way of approaching this problem in F# is indenting code blocks further, leaving wasted space.

```fs
let f x = x
let a = f [
    2 // List: OK
]
let b = [|
    2 // Array: OK
|]
type X = { X : int }
let c = f {
    X = 2 // Record: OK
}
let d = f {|
    X = 2 (* FS0058	Possible incorrect indentation:
this token is offside of context started at position (12:11).
Try indenting this token further or using standard formatting conventions. *)
|}
let e = f {|
            X = 2 // Indenting further is needed
        |}
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Parity
2. Convenience
3. Effective use of space
4. Clarity

The disadvantages of making this adjustment to F# are none.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
I agree with this since we've made it a precedent to relax indentation like this in the past few releases.

**Comment by dsyme** [comment]
Completed in preview https://github.com/dotnet/fsharp/pull/11772
