### ISSUE TITLE
Allow tupled returns and outrefs in functions outputs

### ISSUE THREAD

**Issue by alexandrehtrb** [fsharp/fslang-suggestions#787]
I propose we allow outrefs in function parameters to be outputted with return statements in tupled form, as it already works with methods.

Example that it works, with methods:

```
type ClassA() =
    member this.CountAs(s: string, found: outref<bool>): int =
        let num = s.Count(Func<char, bool>((=) 'a'))
        found <- num > 0
        num

let numAs, found = ClassA().CountAs("abcde")
```

Example that does not work, with functions:

```
let countAs(s: string, found: outref<bool>): int =
    let num = s.Count(Func<char, bool>((=) 'a'))
    found <- num > 0
    num

let numAs, found = countAs("abcde")
```

## Pros and Cons 

The advantage of making this adjustment to F# is more predictability in using tupled outputs with returns and outrefs, because I do not see a reason for this currently only be available for methods, and not functions.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
I wouldn't say I'm against this in principle, though the current behavior with methods is rooted in interop with a .NET pattern that isn't very common in purely F# code.

**Comment by kspeakman** [comment]
Do you have a specific use case in mind? The example you gave can easily be written as a pure function with the same input/output, and has no advantages compared to that.

```fsharp
let countAs (s: string) =
    let num = s.Count(fun c -> c = 'a')
    let found = num > 0
    num, found

let numAs, found = countAs("abcde")
```

And if you want compatibility with C#, you can return a struct tuple.

```fsharp
let countAs ... =
    ...
    struct(num, found)
```

**Comment by alexandrehtrb** [comment]
The use case I have in mind is that in F#, the values can be used in tuples, and in C#, the values can be returned via out parameters. This can be an option, if the programmer chooses not to use tuples in C#.

**Comment by Happypig375** [comment]
If you define a function like this, it's not like the C# version can choose to use tuples anyways. Better to return a struct tuple so that both C# and F# versions return a tuple that is natural to use.

**Comment by dsyme** [comment]
Will track via https://github.com/fsharp/fslang-suggestions/issues/151
