### ISSUE TITLE
Make F# classes compiled together with C# and VB.NET classes

### ISSUE THREAD

**Issue by alexandrehtrb** [fsharp/fslang-suggestions#788]
# Make F# classes compiled together with C# and VB.NET classes

I propose we make F# classes compiled together with C# and VB.NET classes.

Currently, a .NET project needs to be language exclusive, that is, only F#, or only C#, or only VB.NET.

But, this could change to allow `.fs`, `.cs` and `.vb` files to be compiled together in a same project.

An example of that is in Java projects, that can have Kotlin classes in them and both Java and Kotlin are compiled together.

The existing way of approaching this problem in F# is separate F# files in F# projects, C# files in C# projects, and VB.NET files in VB.NET projects.

## Pros and Cons 

The advantages of making this adjustment to F# are easier insertion of F# code in C# and VB.NET code, and vice-versa.

The disadvantage of making this adjustment to F# is the need for compilers architectures changes.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XXL

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
This isn't something that can be done at the language level. All .NET tooling would need to support this as a concept.

**Comment by smoothdeveloper** [comment]
Can this be achieved by compilation into netmodule (both csc and fsc has support for it) and a custom build pipeline?

**Comment by cartermp** [comment]
If you could find a way to do it, possibly, but this isn't something we'd ever support.
