### ISSUE TITLE
Enable wildcard self identifiers for members with accessibility modifiers

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#790]
# Enable wildcard self identifiers for members with accessibility modifiers

I propose we enable wildcard self identifiers for members with accessibility modifiers.

The existing way of approaching this problem in F# is using the double underscore like the old days.
```fs
type A() = member _.X = 1 // OK
type B() = member private _.X = 2 // error FS0010: Unexpected symbol '_' in member definition. Expected identifier, '(', '(*)' or other token.
type C() = member private __.X = 3 // OK
```
## Pros and Cons 

The advantages of making this adjustment to F# are
1. Reducing confusion of why wildcard self identifiers are not allowed in this case
2. Feature parity
3. Concise and shorter code

The disadvantages of making this adjustment to F# are none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
This is implemented and we'll strive to push it in the next patch fix for the compiler.
