### ISSUE TITLE
Relax bound checking behavior on collection slicing

### ISSUE THREAD

**Issue by nelson-wu** [fsharp/fslang-suggestions#795]
This suggestion is for relaxing bound checking on collection slicing, so any slice that extends past collection boundaries will be snapped to the bounds. Any invalid slice will return empty collection instead of throwing errors. 

Detailed design, pros and cons, and implementation details at https://github.com/nelson-wu/fslang-design/blob/3690b10ebaddda40614d51143f0651e863ccbc2f/RFCs/FS-1077-tolerant-slicing.md

**Comment by cartermp** [comment]
Example in the RFC: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1077-tolerant-slicing.md#sample-use-case

**Comment by dsyme** [comment]
This was completed in F# 5.0
