### ISSUE TITLE
Inlined default argument values

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#80]
# Inlined default argument values [12998517] #

**Submitted by Vasily Kirichenko on 3/17/2016 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

Instead of
```fsharp
member __.Foo(?a: int) =
    let a = defaultArg a 2
```
it would be great to write it C#-slyle:
```
    member __.Foo(?a: int = 2)
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/12998517)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-12998517-inlined-default-argument-values.md#comments)

**Comment by dsyme** [comment]
I will close this since there is already a way to do this.  Adding the inline syntax has pros and cons.
