### ISSUE TITLE
Simplify usage of resx files by generating the source code similar to c# but with f# semantics

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-suggestions#802]
I propose we create a code file generator similar to `ResXFileCodeGenerator` used by C# projects, but that creates a `Designer.fs` file. And giving the nature of F# to have magic strings, I suggest we return properties that behave similar to `sprintf`, i.e. that have signature `Printformat<'T> -> 'T`.

An alternative is to use a resx type provider, but that doesn't have the benefit of recognizing `printf`-style format strings.

Example:

```xml
<data name="InputError" xml:space="preserve">
  <value>Wrong input '%s', expected maximum %i characters.</value>
</data>
```

This would translate to:

```f#
/// Returns a localized string similar to "Wrong input '%s', expected maximum %i characters."
let InputError = sprintf """Wrong input '%s', expected maximum %i characters."""
```

Which could be called something like this:

```f#
let maxChars = 20
let inputStr = Console.ReadLine()
if inputStr.Length > maxChars then
    InputError inputStr maxChars
```

Some conderations:

* The proposal as-is is tied with the resx file, that is, changes in the resource file only have effect if the generated code is also recompiled. This is slightly different with C#, where the code creates `ResourceManager.GetString(...)` calls. We could (and perhaps should) do the same, but that means that creating the `printf`-style functions becomes trickier
* let-bound functions in a module may not be the best way to go as that may lead to a hit on the JIT compiler the moment you access one of those functions, and the infamous call on `StartupCode$.XXX` cctors. With large resources that can be significant. There are several ways to ease this pain, if it is indeed significant
* Since as written, the literal texts become a `designer.fs` file, the need for embedding the resource itself may be lessened.
* We could extend this to allow methods for non-string resources as well

---- 

The existing way of approaching this problem in F# is to use a C# project to do the heavy lifting.

## Pros and Cons 

The advantages of making this adjustment to F# are:

* Simpler project management
* Clear separation of resources and code (existing code in F# tends to have many inline strings in `printf`-like functions which should better go in resources)
* Resources become part of the project where they are supposed to be part of
* Type safety for usages of resource strings that take parameters like `%s` or `%i`
* Intrinsic support of format strings right out of the box
* Simpler transition from C# to F# for new programmers

The disadvantages of making this adjustment to F# are

* Existing resource files will not translate properly if they have `{0}` in the strings (they would not be recognized)
* Added complexity in the project system
* Introduction of auto-generated files (currently we don't have that out of the box)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Questions and suggestions of this nature have existed before, but I think this version is simple enough to be picked up (I hope ;).

On SO this has been asked before and caused confusion:

* https://stackoverflow.com/questions/41620531/strong-named-resources-in-f
* https://stackoverflow.com/questions/2689446/how-to-manage-resources-in-an-f-project
* https://stackoverflow.com/questions/17606017/properties-resources-xxxx-namespace-or-module-not-defined

And on Github:

* https://github.com/dotnet/fsharp/issues/4591
* https://github.com/dotnet/cli/issues/8697
* http://fsprojects.github.io/FSharp.Configuration/ResXProvider.html (existing type provider for resx)
* This is how the fsharp prj does it itself (which looks like it could benefit from this suggestion as well): https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Build/FSharpEmbedResXSource.fs

## Affidavit

* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
I'll leave this open but feels like a  tooling suggestion?

**Comment by dsyme** [comment]
I don't think this should be part of core F# tooling.  It can by all means be a separate community tool
