### ISSUE TITLE
suggest: `valueof` operator to eval expression at compile time

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#804]
fsharp have added `nameof` operator in recent version. it is just a syntax sugar. but people like it. I propose we should be to do further more.

for example:
```F#
let name = "abc"
let length = 3 // value of name.length
```
maybe, we can do this:
```F#
let name = "abc"
let length = valueof name.Length
```
this code will be translated into previous code at compile time. it will reduce people a lot of typos. and more readable code.

maybe, we can get an inference:
> purity function that take arguments that are all constant return constant result.

**Comment by abelbraaksma** [comment]
You can already do this, `Length` is a valid property on a string.

```f#
let name = "abc"
let length = name.Length  // gives 3
```

**Comment by xp44mm** [comment]
@abelbraaksma 
but `nameof` or `valueof` will be calculated once at compile time. it's will be calculated zero times at runtime.

**Comment by abelbraaksma** [comment]
Ah, you mean you want some way of writing expressions that evaluate to literals (aka constants), in other words, you want to introduce a macro language, something like C++ has?

Maybe you can clarify that in your original text,and add use cases and more examples that are resolved (take a look at the template). It may also help to emphasize the constant nature, like: `let <Literal> len = valueof x.Length` or something. 

It could be powerful, but I wouldn't be surprised if there's already a suggestion hanging around with a similar idea.

**Comment by xp44mm** [comment]
fsharp should be able to inference that some values are constants actually in logical. it will be reduced a lot of boilerplate codes.

**Comment by yatli** [comment]
In F#, const variables are marked with `[<Literal>]`.
To my knowledge there's only partial support for C++ `constexpr`-style values, because objects like arrays are always run-time objects, and cannot be declared `[<Literal>]`

Adding support for real `constexpr`-style compile-time evaluation would be a big effort.

**Comment by xp44mm** [comment]
@yatli 
`[<Literal>]`并不是重点，有更好，没有也无伤大雅。

it's no important, infer out `[<Literal>]` not very much improvement.

编译时推算全局不变量确实是一个艰巨的任务。能够推算一些简单的计算，比如`1+1`，就很高兴了。

compile-time evaluation some `let` binding as global immutable contant indeed is a big effort. if be able to recongnize very simple, `1+1`, that it is very good .

**Comment by Happypig375** [comment]
```fs
> let (+) x y = printfn "Hi~"; x - y
let a = 1 + 1
let b = 3 + 2;;
Hi~
Hi~
val ( + ) : x:int -> y:int -> int
val a : int = 0
val b : int = 1

> let [<Literal>] a' = 1 + 1;;

  let [<Literal>] a' = 1 + 1
  ---------------------^^^^^

stdin(13,22): error FS0267: This is not a valid constant expression or custom attribute value
```

`[<Literal>]` cannot be inferred here.

**Comment by yatli** [comment]
@Happypig375 

I think @xp44mm would want something like this:

```F#
[<Literal>]
let ( + ) x y = x - y

[<Literal>]
let a = 1 + 1
```

As long as we keep `printf` not `[<Literal>]` we will be fine. :)

**Comment by Happypig375** [comment]
What about `"".Length`? Should that be made a `[<Literal>]`? That is a part of the .NET BCL, we would have to make a whitelist here.

**Comment by yatli** [comment]
Strings are a little bit special already because of the private implementations. A string is an object, and yet it's not mutable as arrays/lists, and could just sit in the data section.

**Comment by Happypig375** [comment]
https://github.com/fsharp/fslang-suggestions/issues/804#issuecomment-550128725
There are signs of arrays-as-literals too.

**Comment by yatli** [comment]
What do you mean? Arrays can only be `static readonly` at best.

**Comment by yatli** [comment]
If we want to support constexpr for any type, a potential way is to keep the initialization bytecode in the assembly -- so when another assembly references it, it can run the initializer again at compile time..

**Comment by yatli** [comment]
@xp44mm recommend to update the title to something more truly reflects the intent. :)

**Comment by yatli** [comment]
One of the C# discussions on this topic:

https://github.com/dotnet/roslyn/issues/15079

**Comment by xp44mm** [comment]
@yatli @Happypig375 

i just want to F# recongnize some `let` binding virtually is literal. is **NO** relationship to `[<Literal>]`

```F#
let abc = "abc"
let chars= abc.ToCharArray()
let len = abc.Length
```

the compiler will evaluate it to as:

```F#
let abc = "abc"
let chars= [|'a';'b';'c'|]
let len = 3
```

**Comment by Happypig375** [comment]
Isn't that the current state? The let binding is evaluated only once.

**Comment by xp44mm** [comment]
@Happypig375 
no! compiler will replace the source code with literal. the `len` in the file is `3`, instead of `abc.Lengh`, it need not to calculate even once.

**Comment by Happypig375** [comment]
How will you know that `Length` will not modify state?

**Comment by xp44mm** [comment]
@Happypig375 
abc is a literal `"abc"`, so it Length property should be literal `3` also. this issue just for performence.

**Comment by Happypig375** [comment]
```fs
> let r = System.Random()
type System.String with
    member _.Length' = r.Next()
let a = "123".Length'
let b = "123".Length';;
val r : System.Random
type String with
  member Length' : int
val a : int = 20296113
val b : int = 36580259
```
abc is a literal `"abc"`, but its `Length'` property `abc.Length'` is not constant.

**Comment by xp44mm** [comment]
@Happypig375 
`abc.Lengh` property is constant ==| `abc.AnyProperty` is constant.
`abc.SomeProperty` is not constant ==| `abc.Length` is not constant.

the property or function need is pure function. purity function that take arguments that are all constant return constant result.

**Comment by Happypig375** [comment]
You cannot determine whether `string.Length` is a pure function. There is no indication of this.

**Comment by xp44mm** [comment]
no effect itself, && no call no pure function, is pure function.

**Comment by Happypig375** [comment]
How can this be checked?

**Comment by xp44mm** [comment]
first, provide some basic pure function as seed. 
and no effect itself, && just call known pure function, is pure function.

**Comment by Happypig375** [comment]
>some basic pure function as seed

Which?

**Comment by xp44mm** [comment]
operator, arith +-*/, Math operator, relation operator, string operator, compare operator. maybe so. Excel function most in.

**Comment by Happypig375** [comment]
Operators only?

**Comment by xp44mm** [comment]
operator is safe collection. other function may be pure function. can manual mark also:
```F#
[<CompileAsLiteral>]
let len = abc.Length // -> let len = 3
```

**Comment by Happypig375** [comment]
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAxgPYB2AzgC7oCW7XgA10AXnSoA3IyZE2XXsFYBXAEYAbAKboAmmPQBWaUlnF5PdErVb0AQX16A9OhjHTcjhasbtAIX32AFQSbu7miio+OPoiAGQuoabhlpE2ACIB6M6+ibLJ3jYAovpwAAzoAKToabksnhHW2gBi+tQC3LS4ADxd6G2CtDq1ZvX8gugA4vpSWY4ARACGqsxzAHQAMprsAObcABbDRFBwAJzUQrSHmKfUOpcyssdntvcm7k/Uvq/u12fY3+8bmkAaYPoUQY8bk0IUwPhMIQBfZAIoA

Operators can be interpreted as constant, evidenced by the C# compiler. Even so, it cannot infer `string.Length` as constant.

**Comment by xp44mm** [comment]
i admired you, The length of "abc" is 3, 3 is literal, literal is constant, any wrong?

**Comment by Happypig375** [comment]
Because `string.Length` is a member on string, not an operator.

**Comment by Happypig375** [comment]
If `string.Length` is interpreted as constant, then we will have to keep a whitelist on .NET BCL types. Not sure this is worthwhile.

**Comment by Happypig375** [comment]
If this is just an optimization, then this is a micro-optimization and you should focus on better places to optimize.

**Comment by xp44mm** [comment]
if too dificult to determine pure function. just transpile the manual mark `[<TranspileToLiteral>]`, that is very good also.

**Comment by Happypig375** [comment]
`string.Length` is not written in F#. You cannot mark it as `[<TranspileToLiteral>]` in F# code.

**Comment by xp44mm** [comment]
```F#
[<TranspileToLiteral>]
let len = abc.Length // -> let len = 3
```
just mark let binding left, whatever equal sign right is. right will be eval at compile time, tranpile to literal.

**Comment by Happypig375** [comment]
This duplicates `[<Literal>]`.

**Comment by xp44mm** [comment]
`[<Literal>]`  no work. can not to compile. it must mark equal right side is real literal. it just use for pattern match.

**Comment by Happypig375** [comment]
It is not used just for pattern matching. Active patterns can do much more. Instead, it reduces duplicate information in attributes so the value can be changed easily. Anyways, it is not for optimizations.

**Comment by xp44mm** [comment]
right! a different attribute.

**Comment by Happypig375** [comment]
Back on topic, how would you classify "pure functions"? If `string.Length` is one, then what is the rule?

**Comment by xp44mm** [comment]
length is pure function, because it is char array's count, it call +. and without effect itself.

**Comment by Happypig375** [comment]
How can the F# compiler know this?

**Comment by xp44mm** [comment]
array.map, array.reduce, is pure function.

**Comment by yatli** [comment]
- Seed functions
- Rule of transitivity

**Comment by Happypig375** [comment]
What will be in the whitelist?

**Comment by Happypig375** [comment]
>array.map, array.reduce, is pure function.

Will this be the result of attributes or transitivity?

**Comment by yatli** [comment]
I don't think `Array.map` is constexpr at all.

**Comment by xp44mm** [comment]
i think whilelist can very long. when you find some rule, then to shorten whilelist.

**Comment by yatli** [comment]
Another approach is that, transitivity is only a constraint within a function (to check one declared `[<ConstExpr>]` is really pure or not)

**Comment by xp44mm** [comment]
amost all of Excel function is pure function. can in whilelist.

**Comment by Happypig375** [comment]
https://support.office.com/en-us/article/RAND-function-4CBFA695-8869-4788-8D90-021EA9F5BE73

**Comment by xp44mm** [comment]
@yatli 
manual mark pure function is good idea.

**Comment by Happypig375** [comment]
Then the code in the first post will not work. Please update.

**Comment by xp44mm** [comment]
the excel function random, now row, column, address, caller is effect function. just several.

**Comment by abelbraaksma** [comment]
> amost all of Excel function is pure function. can in whilelist

There's nothing in F# that should be compared to Excel. Excel is not even a programming language. 

The problem in this discussion is one of definition. I think the OP wants auto-magic constants, where a let binding 'transpiles' to a constant.

But this can never, ever work, because a constant in the .NET world is replaced by its value when consumed. That means, if a.dll has a constant, and b.dll consumes this, and we now change the value in a.dll, it will not be reflected in b.dll until you recompile it.

Therefore, magically changing existing let bindings into constants is a no-go. 

There is, however, something to say for constant evaluation of expressions, provided that the compiler can infer this. This isn't as hard as it looks and there's already a proposal somewhere for F#. We can just use `Literal` for it. Or a special operator or function that takes an expression and evaluates it at compile time (cannot be `valueof`, as that is not reserved).

> array.map, array.reduce, is pure function.

They are not. They can change state by virtue if the mapper or folder function you use. Besides, their output is never constant (remember that compile time constants can only ever be the built in value types that are not structs, and strings).

I agree that to pre-calculate one time evaluations can be valuable, but if they are expensive calculations, you should reconsider your design. If they aren't expensive, the benefit is minimal, as all given examples from the OP are already valid code. I like the idea of an expression that forces compile time evaluation, but by virtue of the limits of CLR, this will have a very limited set of allowed functions (and let's be fair, if you know beforehand that the length of a string in your code is constant for eternity, you can micro optimize yourself by replacing it with a constant, I think we need better use cases).

**Comment by abelbraaksma** [comment]
It took me a moment to find it, but the proposal for allowing expressions in literals already exists and is approved. It just needs someone to work on it: https://github.com/fsharp/fslang-suggestions/issues/539

**Comment by xp44mm** [comment]
@abelbraaksma 
regex is an use case: it can be precompiled  to action table, and never changed if regex no changed.

**Comment by xp44mm** [comment]
>But this can never, ever work, because a constant in the .NET world is replaced by its value when consumed. That means, if a.dll has a constant, and b.dll consumes this, and we now change the value in a.dll, it will not be reflected in b.dll until you recompile it.

this do not matter. because the `length` value be infered form `"abc"`, if length be updated. then "abc" must be updated, so anyway, the source .dll must be recompiled.

**Comment by abelbraaksma** [comment]
> i think literal more than constant, literal include constant you metioned and also include tuple literal list ....

Actually, no. In F#, a literal, declared with the `[<Literal>]` attribute, or inlined as a literal expression, [**is a constant**](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/literals). I mean, what other languages like C#, VB, C++ call constants, is called a _Literal_ in F#.

And constants, or literals, by their very definition, cannot be reference types (the exception being strings and byte arrays). So your example of regex won't work, not even if you allow calculations of function calls in literals that are to be evaluated at compile time. The only operators presently allowed are `|||` on numbers and `+` on strings. But have a look at[ the proposal on expanding the set of allowed operators](https://github.com/fsharp/fslang-suggestions/issues/539), as I mentioned before. It would be a good starting point.

To get what you want with regexes, you can actually use the methods available from `System.Text.RegularExpressions`, like [`CompileToAssembly`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.compiletoassembly?view=netframework-4.8).

Wanting to allow a "constant" like that, i.e., a whole object, or in this case an actual assembly, to be pre-compiled and stored in your DLL or EXE would mean that somehow the compiler needs to serialize and deserialize the data that you you pre-computed. That's far from trivial, there are books written on that subject alone, and likely not going to happen (but I'm not the one who decides, if there's a reasonable proposal and it gets traction, and you're willing to implement it, they may accept it).

An alternative you might consider is using a `RESX` file. Create an auxiliary project that can do the pre-calculations that you want. Store them in a (binary) file. Read this in into the resx file as resources and access them directly from your code just like with C# projects. That is the proper way to go about resources (or "constants") that extend the realm of the expressive power or usefulness of `Literal` bindings in F#.

About regexes in particular, a good tool that I use is this [Regular Expression Library Builder,](https://www.codeproject.com/Articles/10603/Regular-Expression-Library-Builder) which can do exactly what you suggest and create "constant", that is, DLL assemblies, of your compiled regular expressions.

**Comment by xp44mm** [comment]
@abelbraaksma 
thank you! actually i can work aroud it, the simplest is:
```F#
let Length = 3 // abc.Length
```
or i can test it:
```F#
Assert.equal(3,abc.Length)
```

**Comment by abelbraaksma** [comment]
> this do not matter. because the length value be infered form "abc", if length be updated in a.dll. then "abc" must be updated also in a.dll, so anyway, the b.dll must be recompiled.

I'm not sure you understand how literals, or constants work. I don't understand what you mean with "infer" here. Let's say you have:

```f#
// a.dll
let [<Literal>] SomeString = "John"

// b.dll
let [<Literal>] LengthSomeString = SomeString.Length

// c.dll
let [<Literal>] DoubleLength = LengthSomeString * 2
```

If one company created `a.dll` another one `b.dll` and another one `c.dll`, if the first changes the name, and you have some code depending on this length, then everything falls apart (for instance, say you have code that iterates over all characters `for i=0 to LengthSomeString do ...` this will horribly fail).

This can also happen with actual constants and is a well documented fact and cause of confusion for C# developers. Allowing arbitrary expressions is potentially going to wreak havoc.

I still think there's value in an expression like `valueof` taking an argument that is evaluated at compile time, but it should be severely restricted. A current workaround, btw, is using generated files or something like `Fody` for weaving, or Cecil, which all allow much of what you are after and more. But each comes with their own caveats.

**Comment by cartermp** [comment]
I would think the function could only apply to things that you could also apply the `[<Literal>]` attribute to. Would that be unexpected, since it's so restrictive?

**Comment by abelbraaksma** [comment]
@cartermp, I think it should be allowed everywhere where we allow literals to appear (like `"a string"`, `123y` etc). Technically that's the same as bindings marked with `Literal`, as they simply get replaced inline, as opposed to referenced.

A large part of the discussion was about the confusion of what the OP wanted, which frankly, I'm still unsure about, but taken as a compile time evaluation of a valid F# expression that yields a .NET Framework allowed literal, I think it has merit.

**Comment by xp44mm** [comment]
@abelbraaksma 
yes! dependent on constant in another assembly, and fixed it to result value is dangous. maybe outdated. so i must sure another assembly is never absolutely no changed for example PI.

**Comment by xp44mm** [comment]
@abelbraaksma 
regex is reference type in implement, but it is some immutable data in logic. so can resolve it in advance.

another use case: reflection is some immutable data, it represent source code, never changed at runtime. it can be resolved in advance at compiler.

**Comment by abelbraaksma** [comment]
> regex is reference type in implement, but it is some immutable data in logic. so can resolve it in advance.

Sorry, still not sure what you mean, as this is simply not possible. I'm afraid you may not understand what the purpose, usages and limits of literals are, which is fine, but then I suggest you read [the article I referenced earlier](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/literals). The types there are the types any literal is limited to by the .NET Framework. So whatever your proposal, it has to be within those limits, or you would have to make your suggestion to Roslyn in stead.

**Comment by xp44mm** [comment]
hi! maybe this can spark your idea:
https://babeljs.io/docs/en/babel-plugin-minify-constant-folding

**Comment by abelbraaksma** [comment]
Constant folding already happens (try 10 + 32), empty functions are optimized away, small functions are inlined, either by F# or by CLR. Is there a specific case where you don't see it happen and you would like it improved? I'm sure improvements are possible, but we'll need concrete use cases.

**Comment by Swoorup** [comment]
I think one approach to this would be marking functions as `constfn` and the compiler processes only a limited set of IL code, ie `constfn` function can't make call to non-const functions. Also when marking a variable as literal, it can only invoke `constfn` whose parameters are also literals.

**Comment by abelbraaksma** [comment]
> but embed the value when compiling.

@Swoorup That currently happens if you mark something as `Literal`, though I assume you mean to extend the set of allowed operations inside a literal expression?

I believe IL limits what's allowed as constants: primitives, string, guid, type, byte array. Of these, F# doesn't support `Type` iirc. And I've read somewhere that decimals are soon to be allowed as constants too, at least in C#.

Any set of functions that is going to be allowed in constant folding operations must be limited to taking and returning said types, cannot have side effects and cannot use currying. Anything else should probably go through a user defined precompilation step. 

This is just my take on this to keep it simple, though technically these limitations could be lifted to some extend. For one, it would be nice if struct DU and records were allowed here.

**Comment by abelbraaksma** [comment]
Considering what C# allows: I was wrong, only strings are reference types that are allowed. Arrays, guids and Types are not (though they are allowed by the IL, after all, you can use them in attributes).

**Comment by Swoorup** [comment]
@abelbraaksma That sounds similar to the approach rust takes with the exception of proc macros.

**Comment by dsyme** [comment]
I'm closing this, as arbitrary compile-time evaluation like in the OP isn't planned to be part of F#
