### ISSUE TITLE
Introduce an initial Option for async computation expressions

### ISSUE THREAD

**Issue by giuliohome** [fsharp/fslang-suggestions#808]
# An Option transformer for async functions

I propose we have a new member for `Option` so that we can mark an `async` function as returned by the server, instead of being an initial value.

The existing way of approaching this problem in F# is to write a type extension for `Option`

```fsharp
 type Option<'a> with
     static member toSomeAsync<'a> (f: unit -> Async<'a>) 
         : unit -> Async<'a option>  = 
         fun () -> 
             async {
                 let! (res : 'a) = f ()
                 return Some res
             }
```

## Pros and Cons 

The advantages of making this adjustment to F# are:

1. a standard way of wrapping the Option inside an async workflow (it would vaguely look like the equivalent of a monad transformer) 
2. a quick way to mark an `async` function returning a computed value as distinct from an initial, non computed value

I'm not aware of any disadvantages of making this adjustment to F#.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
This should really be `Async.toOption`.

**Comment by giuliohome** [comment]
@Happypig375 You are 100% right, agreed, thank you.

**Comment by giuliohome** [comment]
There is also another error in my initial definition, because we don't need to include a specific function with input of type `unit` but we must generalize to any input function. So, it should be:

```fsharp
type Async<'a> with
    static member toOption<'a> (f: Async<'a>) 
        : unit -> Async<'a option>  = 
        fun () -> 
            async {
                let! (res : 'a) = f 
                return Some res
            }

```

**Comment by dsyme** [comment]
If we do this we would add `Async.map` and `Async.toOption`:

```fsharp
module Async = 
     let map f (computation: Async<'a>) =
             async {
                 let! (res : 'a) = computation
                 return f res
             }

     let toOption computation = map Some computation
```

The `unit` play no role since `Async` are delayed and started explicitly, not implicitly

**Comment by giuliohome** [comment]
@dsyme thank you very much for the clarification about the `unit`! This morning I tried something like that but the input arguments of my input function were immediately evaluated (fyi the input to the computation was a websharper var value corresponding to a date from a date picker) so I deleted my comment because I had to use a `fun () -> ...`  I think I understand what you mean (in terms of comparing F# async to C# task, if I get it right), so I will try again later ... my only point is that the computation should be a function whose input arguments should be evaluated at the delayed moment when the async is executed. Sorry for the confusion anyway I'll try again without the `unit`. Thank you again

**Comment by giuliohome** [comment]
Maybe is an `apply` more powerful than a `map` ?

**Comment by giuliohome** [comment]
Well, I don't know how to explain, but my issue is that arguments are eagerly evaluated, so if `Async` module is defined as 

```fsharp
module Async = 
    let map f xAsync = async {
        // get the contents of xAsync 
        let! x = xAsync 
        // apply the function and lift the result
        return f x
        }

    let retn x = async {
        // lift x to an Async
        return x
        }

    let apply fAsync xAsync = async {
        // start the two asyncs in parallel
        let! fChild = Async.StartChild fAsync
        let! xChild = Async.StartChild xAsync

        // wait for the results
        let! f = fChild
        let! x = xChild 

        // apply the function to the results
        return f x 
        }

    let bind f xAsync = async {
        // get the contents of xAsync 
        let! x = xAsync 
        // apply the function but don't lift the result
        // as f will return an Async
        return! f x
        }
```

and you add a

```fsharp
    let toOption computation = map Some computation
```

I'll have to define a `delay computation` (is the name `delay` appropriate?)

```fsharp
    let delay computation = 
        bind computation (retn ())
    let bindOption computation = 
        delay computation
        |> toOption
```

because in the following example

```fsharp
open System

[<EntryPoint>]
let main argv =
    let mutable test = DateTime.UtcNow
    let computation date = 
        async {
            return string date
        }
    let mappedDoc = 
        computation test
        |> Async.toOption 
    let boundDoc = 
        fun () -> computation test
        |> Async.bindOption 
    test <- test.AddDays(1.)
    let mapped = 
        mappedDoc 
        |> Async.RunSynchronously
        |> Option.toObj
    let bound =
        boundDoc
        |> Async.RunSynchronously
        |> Option.toObj

    sprintf "mapped = %s vs bound = %s" mapped bound
    |> System.Diagnostics.Debug.WriteLine
    0
```

I really need the `bound` (and delayed, I don't know how to call it) result instead of the `mapped` one

**Comment by cartermp** [comment]
@giuliohome in this case I think the resolution would be that you write and use your own library function.
