### ISSUE TITLE
Average of collection functions should support more numeric types

### ISSUE THREAD

**Issue by mvkara** [fsharp/fslang-suggestions#812]
I propose we allow Seq.average, Array.average and friends to work on a wider variety of numeric data types (e.g int, int64, etc.). Currently only data types with a static member of "DivideByInt" are supported. 

## Pros and Cons 

The advantages of making this adjustment to F# are:
- Calculating an average of a collection is more intuitive to a newcomer of the language (i.e. it just works as expected for any number type).
- More efficient performance wise than converting your numbers to another data type before calculating the average.

The disadvantages of making this adjustment to F# are:
- It changes the type constraints of functions like Seq.average and may break consumers.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Notes

The existing way of approaching this problem in F# would be to hand roll your own function to do this. e.g. 

```
let inline average s = 
  let mutable sum = LanguagePrimitives.GenericZero
  let mutable items = LanguagePrimitives.GenericZero
  for i in s do
    sum <- sum + i
    items <- items + LanguagePrimitives.GenericOne
  sum / items
```

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by gusty** [comment]
It's not clear to me what is the signature of `average` you are suggesting. It's also not obvious which one should be.

Your sample function gives you a signature of `s:seq< ^a> ->  ^e` but in fact `^a` and `^e` are the same type when they are resolved.

I can think of 2 possibilities:

1. `s:seq< ^a> ->  ^a` in which case if you work with big numbers you'll be able to get a big number as result. But if you work with small numbers and you have a big number of elements your divisor won't be able to express the number of elements.

2.  `s:seq< ^a> ->  ^b`  where `ˆb` is inferred by the result type. The cons here are that if ˆb is not defaulted to `int` you'll get ambiguity errors, also it will move to the user the responsibility to use the appropriate result type.

**Comment by mvkra** [comment]
@gusty Its a good question. My makeshift code example was more that I saw a pretty typical use case that to a newcomer to the language should "just work" without having to understand SRTP errors. In my case I had a list of timings (in milliseconds of type int64) in a collection that I wanted to get the average of. [LINQ in C#](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.average?view=netframework-4.8) has overloads for a variety of different primitive number types. This means if I do a .Average() on a sequence of numbers usually "it just works" in that language. For newcomers to the language it isn't intuitive why it doesn't just work; or what the error message "int does not support the operator DivideByInt" means.

The current behavior (tested in FSI) that assumes the input type and return type are the same unless specified seems like a good default to me but I could be naive about some detail. 

```
open LanguagePrimitives

let inline average s = 
  let mutable sum = GenericZero
  let mutable items = GenericZero
  for i in s do
    sum <- sum + i
    items <- items + GenericOne
  sum / items

let int64Average = average [ 1L; 10L ] // 5L
let decimalAverage = average [ 1M; 2M ] // 1.5M
let floatAverageWithDecimalInput : float = average [ 1.0M; 20.0M ] // does not compile
```

**Comment by abelbraaksma** [comment]
Perhaps just have an `averageBy` function, where the first argument is the division function?

There was a reason that the function requires that member (same as with several other core functions), since it's noon trivial how to get the average of, say, a sequence of bytes, or ints: what do you do with the remainder (they aren't floats, would you accept a potential huge rounding error? That's why they leave it up to the user), and how to deal with overflow?

For F# 5.0 I believe it is planned that extension methods can be used with SRTP, which would make this much simpler to solve.

**Comment by rmunn** [comment]
> Perhaps just have an `averageBy` function, where the first argument is the division function?

There's [already](https://msdn.microsoft.com/visualfsharpdocs/conceptual/seq.averageby%5b%27t%2c%5eu%5d-function-%5bfsharp%5d) an `averageBy`, where the first argument is a projection function. Perhaps `averageWith` might work as a name instead? Though I'm not really sold on it: if you saw `averageWith`, would you assume its first argument had to be a division function? That's not necessarily the first thing that would spring to mind for me.

**Comment by abelbraaksma** [comment]
@rmunn, you're right, I didn't check at before u posted. Thinking about this again, wouldn't `averageWith` be nothing more than a glorified fold function?

Also, I'm a little worried about dividing each term, on long ranges, this will lead to rounding errors. Not sure if that's currently already the case though.

**Comment by cartermp** [comment]
TBH I'm not quite sure why these resolve to `DivideByInt`, which is implemented here: https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L2449

Feels like a very unnecessary restriction

**Comment by gusty** [comment]
They were implemented with `DivideByInt` most likely because a list index is an int.

I think in some extreme cases it could be an `int64`, so it would require a `DivideByInt64`.

**Comment by dsyme** [comment]
Closing out this old issue. As mentioned above the DivideByInt is there for a reason - to make sure the remainder is taken into account.
