### ISSUE TITLE
Add `uint` type abbreviation to FSharp.Core

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#818]
# Title of Suggestion

I propose we add the following type abbreviation:

```fsharp
type uint = uint32
```

The existing way of approaching this problem in F# is to:

* Write the abbreviation yourself
* Use `uint32` directly

## Pros and Cons 

The advantages of making this adjustment to F# are:

* Consistency with `int`, which is similarly abbreviated to `int32`
* Probably helps with the principal of least surprise - if `int` exists, why not `uint`?

The disadvantages of making this adjustment to F# are that it's work.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by abelbraaksma** [comment]
Considering that C# also has `uint` I think this serves the principle of least surprise to add it in.

Note that the F# cheatsheet already assumed that `uint` exists: https://github.com/tomi/fsharp-cheatsheet, apparently it comes natural to think it does.

Apart from the type abbreviation, for parity, I suggest we also allow the type-cast function `val uint32 : value:'T -> uint32 (requires member op_Explicit)` to be aliased as  `val uint : value:'T -> uint (requires member op_Explicit)`. 

Btw, while we're at it, we have aliases for `double` vs `float`, but not for `int64` vs `long` and `uint64` vs `ulong`, however the type suffixes suggest long and ulong (`L` vs `UL`). Perhaps we could pair them in the same go? For people coming from C# this would certainly help.

**Comment by abelbraaksma** [comment]
Funny, even the F# error messages assume `uint` exists!

![image](https://user-images.githubusercontent.com/16015770/70447978-ee65e980-1a9f-11ea-8b03-3a400a3e32d8.png)

**Comment by cartermp** [comment]
@abelbraaksma Yes, there are some pre-existing assumptions in the codebase that it exists. Looking at the github history, the lack of `uint` type abbreviation starts when the code was imported to GitHub, so if there is a bug, it is from a bygone era 😄

**Comment by Swoorup** [comment]
For some reason I read the whole RFC as ~uint~unit

**Comment by dsyme** [comment]
Do we really want this?

* `uint` really gets confusing with `unit`

* We'd right a need `uint` conversion function as well, Also in Nullable operators.

I'm not really convinced...  :-)

**Comment by abelbraaksma** [comment]
For reference, the PR was completed and merged. I think this issue can be closed.
