### ISSUE TITLE
provide counter example for total active patterns that are not exhaustively matched

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/fslang-suggestions#823]
Given

```fsharp
let (|PA|PB|) x = match x with Some _ -> PA | _ -> PB
let f = function | PA -> ()
```

it currently produces

```
  let f = function | PA -> ();;
  --------^^^^^^^^
warning FS0025: Incomplete pattern matches on this expression.
```
I'd like the compiler to provide counter example of `PB` the same way it does with normal pattern matching on discriminated unions or concrete values.

## Pros and Cons 

Pros:
* reinforces the "compiler has my back" feeling
* consistency with regular pattern matching
* it may involve fixing some not yet reported bug (Look at Free Monad implementation from @gusty producing a faulty warning: https://github.com/fsprojects/FSharpPlus/blob/c17698e3d75bf852ee791b65515be4b05a6808cb/src/FSharpPlus/Free.fs#L107)

Cons:
* PatternMatchCompilation.fs gets a bit bigger
* some more work to produce the current warning, unsure if it is just missing to show the counter examples or if constituting the list is significant extra work, I assume not since it currently compiles to a `ChoiceXofY` and it is able to produce the warning

## Extra information

Estimated cost: M

## Affidavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by gusty** [comment]
Or maybe make it work instead !

I think if the check occurs at the call site it should work.

**Comment by abelbraaksma** [comment]
Would be a great addition to the heuristics, but it may be tricky if the active pattern matches are mixed with other active patterns, normal patterns in the same match statement.

Perhaps if we'd only implement the trivial case (one active pattern used in the match clauses, provided it's 'total') it'd be not too hard to do.

**Comment by charlesroddie** [comment]
> I'd like the compiler to provide counter example of PB

I would have thought that `None`, not `PB`, is the right counterexample and your suggestion of `PB` could be due to how a strangeness in the current inference.

```fsharp
let (|PA|PB|) = function Some() -> PA | None -> PB
let f(x:unit option) =
    match x with
    | PA -> ()
    // | None -> () : if this is added, then "Incomplete pattern matches on this expression."
    // PB -> () : if this is added, the compiler is happy.
```
The compiler does seem to have special logic checking completeness for complete active pattern cases. This seems fairly brittle for settings where active and other patterns are included in a match.

An implementation of this suggestion might need to expand the match, substituting the patterns, and do a completeness check (expanding `PA` to `Some()` and `PB` to `None` in this case) on that.

**Comment by smoothdeveloper** [comment]
Thanks for the comments, active patterns can be mixed and total active patterns aren't an exception; I totally overlooked that while making the suggestion,

Would it make sense to update the suggestion so that it applies for match expression when existing clauses are solely members of the active pattern definition, aka unmixed?

```fsharp
let (|PA|PB|) x = match x with Some _ -> PA | _ -> PB
let f =
    function
    | PA -> ()
    | None -> ()
```
would remain unchanged (warning without counter example, despite being a false positive)

If the exhaustiveness check could be handled as @charlesroddie explains it would be even better, but the restricted case intended for this suggestion maybe has better chance to be implemented.

**Comment by abelbraaksma** [comment]
> but the restricted case intended for this suggestion maybe has better chance to be implemented.

I agree. I think catching the general case is a good thing to have. Typically, one would use complete (or closed) active patterns to use them as a whole, so that the compiler only needs to call the active pattern function once. It seems to me that the available cases (internally, these are `ChoiceXofY` I believe) are transparent to the compiler and can be reasoned about during exhaustiveness checks.

**Comment by cartermp** [comment]
I think I will close this and recommend that it be filed as a compile warning enhancement in dotnet/fsharp: https://github.com/dotnet/fsharp

There is some nuance in deciding what the suggestion should be, but I do not think that it implies changes to the language design.
