### ISSUE TITLE
Don't erase source information for inline functions

### ISSUE THREAD

**Issue by marklam** [fsharp/fslang-suggestions#824]
I propose we stop erasing the debugging sequence points for functions which have been inlined by the compiler.

The existing state is that code which has been inlined has no source file or line information. This has the effect that:
* code coverage tools are unaware that the function has been covered, leading to [incorrectly low coverage statistics](https://github.com/dotnet/fsharp/issues/3579) ([example repo](https://github.com/marklam/CoverageExample))
* automated unit test runners (such as NCover, and presumably Rider and Visual Studio Enterprise Live Unit Testing) do not re-run tests when the function implementation changes  ([example repo](https://github.com/marklam/FsInlinesCoverage)). 

The second is more dangerous, and can lead to tests showing as passing when in fact recent edits should have broken them. 

This screenshot shows two functionally identical tests giving different results because one implementation was inlined. ![Ncrunch coverage results](https://github.com/marklam/FsInlinesCoverage/raw/master/OutdatedTests.png)

## Pros and Cons 

The advantages of making this adjustment to F# are 
* coverage reports will be more accurate, and uncovered code can be detected.
* automated test runners will be less likely to miss tests which need to be re-run

The disadvantages of making this adjustment to F# are
* Debugging an inlined function [may be confusing](https://github.com/dotnet/fsharp/issues/3579#issuecomment-329458556) (currently it's impossible)
* Cross-assembly inlining [may be a problem ](https://github.com/dotnet/fsharp/issues/3579#issuecomment-329525327) when the assembly came from somewhere other than the same solution.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS -> M, depending on [whether an option would be required](https://github.com/dotnet/fsharp/issues/3579#issuecomment-329472453) and whether cross-assembly inlining causes a problems.

Related suggestions:
Discussion thread: https://github.com/dotnet/fsharp/issues/3579

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help ~~implement and/or~~ test this

**Comment by abelbraaksma** [comment]
I've discussed this to some length with @dsyme a few years back and if I recall, he said it would be possible in principle, but far from trivial to implement.

> I have searched both open and closed suggestions on this site and believe this is not a duplicate 

I think there are several request out there, and maybe even some that are approved already, I'll have a look.

**Comment by marklam** [comment]
I generally run coverage reports in the debug build for that reason, but having at least some support in a release build could be useful for profiling tools (which is a possible 'pro' I had forgotten about in the suggestion).

**Comment by dsyme** [comment]
> I've discussed this to some length with @dsyme a few years back and if I recall, he said it would be possible in principle, but far from trivial to implement.

I need to think through the details, but in principle the core change is very very simple - remove the use of `remarkExpr` in Optimizer.fs and perhaps a couple of other places.

The problem may be in other places, e.g. what happens when we beta-reduce a lambda application after copying, or what goes wrong with other debugging generally.

Anyway if you want to play around with these that's where to begin I think

**Comment by dsyme** [comment]
@abelbraaksma Do you have a record of that discussion we had?

**Comment by TysonMN** [comment]
This behavior also why I can't hit a breakpoint that I set on a line of an linined function?

**Comment by Liminiens** [comment]
This suggestion would greatly help to debug heavily inlined code

**Comment by dsyme** [comment]
> This behavior also why I can't hit a breakpoint that I set on a line of an linined function?

Yes, though one of the concerns of allowing it is that the breakpoints may became non-unique.  We should just trial it and see.

**Comment by ForNeVeR** [comment]
They're already non-unique for some cases, and this isn't an F#-only precedent, and has already been in other managed languages. Here're two particular cases I'm familiar with:

1. Single point in the source code leads to multiple different IL instructions in case of C++/CLI template (not generic!) functions applied to managed types.
2. Debug information for single line of F# code may point to different IL instructions in case when single line of CE is compiled to participate in multiple methods internally (this is why VS/Rider debuggers will sometimes hit the same line inside of CE workflow multiple times).

**Comment by dsyme** [comment]
This is tracked by https://github.com/dotnet/fsharp/issues/12263.

We looked at making this change but it didn't work out well, and made the debugging/stepping worse in important cases
