### ISSUE TITLE
Enable langversion switch to control warnings about preview library functions.

### ISSUE THREAD

**Issue by KevinRansom** [fsharp/fslang-suggestions#825]
# Enable langversion switch to control warnings about preview library functions.

I propose ... the F# compiler supports an ExperimentalAttribute (doc'd [Here](https://msdn.microsoft.com/visualfsharpdocs/conceptual/core.experimentalattribute-class-%5bfsharp%5d).  This attribute is used to tag values that are part of an experimental library feature.

We can use this attribute to mark new APIs added to FSharp.Core and adjust the compiler so that it doesn't issue a warning when the compiler is executed with the preview switch.

The existing way of approaching this problem in F# is ...
use nowarn switch or pragma to disable the warning.  When displayed by the compiler.

With the switch the warning would appear if the compiler is run without langversion:preview speciifed

## Pros and Cons 

We can preview library features alongside language features, without the developers having to understand whether the warning was scary or not.

The disadvantages of making this adjustment to F# are ...
RTM Libraries will ship with preview APIs, potentially encouraging developers to depend on these preview APIs that may change shape or go away.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ x] This is not a breaking change to the F# language design
* [ x] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
Closing out as this has been implemented and will ship in the first F# 5 previews.
