### ISSUE TITLE
Pattern matching with Generics

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#828]
# Pattern matching with Generics

I propose we permit pattern matching on generic types.
```fs
type Packet() = class end
type KeepalivePacket() = inherit Packet()
let send<'T when 'T :> Packet>(packet:'T) =
    match packet with
    | :? KeepalivePacket as keepalive -> ()
        // Do stuff with keepalive
```
```
error FS0008: This runtime coercion or type test from type
    'T    
 to 
    KeepalivePacket    
involves an indeterminate type based on information prior to this program point. Runtime type tests are not allowed on some types. Further type annotations are needed.
```
The existing way of approaching this problem in F# is to change it to an if-statement on type objects.

[This was already implemented in C# 7.1](https://github.com/dotnet/csharplang/issues/154). We should do so too.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. [I couldn't find any mention of unsupported pattern matching with generic parameters/variables in the design notes/blog posts.](https://github.com/dotnet/roslyn/issues/16195#issue-198409834)
2. [If intended I do hope that this is a limitation that could be removed in the future as I see your use case as one that wouldn't be all that uncommon.](https://github.com/dotnet/roslyn/issues/16195#issuecomment-270128402)
3. [Looks like a bug.](https://github.com/dotnet/roslyn/issues/16195#issuecomment-270236828)
4. [It seems strange to me that the language specification is defined such that no (explicit) conversion exists here. We'll look at what we can do about that.](https://github.com/dotnet/roslyn/issues/16195#issuecomment-270522052)
5. [This is a very surprising limitation. It severely limits the usefulness of pattern matching in generic code, making many of the changes I was hoping to make to my code base impossible.](https://github.com/dotnet/csharplang/issues/154#issuecomment-285867275)
6. [Cases where pattern-matching should "obviously" be permitted currently fail to compile.](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/generics-pattern-match.md#motivation)

The disadvantages of making this adjustment to F# are none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions:
https://github.com/dotnet/roslyn/issues/16195
https://github.com/dotnet/roslyn/issues/16993
https://github.com/dotnet/csharplang/issues/154
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/generics-pattern-match.md

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by charlesroddie** [comment]
> The existing way of approaching this problem in F# is to change it to an if-statement on type objects.

I would consider (at least outside the compiler) matching on types and downcasting to be a code smell, and the extra difficulty of using if-statements on type objects here may provide a good deterrent. Do others consider this type of code to be proper?

**Comment by Happypig375** [comment]
Matching on DU-like hierarchies from C# is a valid scenario and this proposal, along with #830, can help create concise and correct code.

**Comment by charlesroddie** [comment]
OK that's a good example!

**Comment by jwosty** [comment]
There is a workaround:

```
match (packet :> obj) with
| :? KeepalivePacket as keepalive -> ()
```

**Comment by abelbraaksma** [comment]
Note that the compiler can do this statically, but it requires a hidden switch (I forgot which it was), that would allow you to match over types in an SRTP way. An example is the current `string` implementation, but there are many more.

The simpler workaround is to just use boxing.

**Comment by jwosty** [comment]
> 
> 
> Note that the compiler can do this statically, but it requires a hidden switch (I forgot which it was), that would allow you to match over types in an SRTP way. An example is the current `string` implementation, but there are many more.
> 
> The simpler workaround is to just use boxing.

Isn't it the switch that's used to compile the core library? i.e. the one that's used to make the (+) operator work with all number types

**Comment by abelbraaksma** [comment]
@jwosty, yes, I think so, though the way I understand it, it's essentially an extension to SRTP. One option would be to allow that syntax outside the compiler, but I've experimented in the past with that hidden compiler switch. At least it used to work, but had some limitations.
