### ISSUE TITLE
Allow all expressions except tuples in property initializers to be unparenthesized 

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#829]
# Title of Suggestion

I propose we allow all expressions in property initializers to be unparenthesized, no matter whether the expression contains `<`, `=`, `>`, `&` or `|`.
```fs

type T = T with static member M(x: int, y: bool, z: int seq) = ()
let inline ($) a b = a + b

T.M(
    y = true, z = [],
    x = 5 $ 4 // Fails
)

T.M(
    y = true, z = [],
    x = 5 + 4 // Works
)

T.M(
    y = true, x = 5,
    z = seq { yield 5 }  // Works
)

T.M(
    y = true, z = [],
    x = seq { yield 5 } |> Seq.head  // Fails due to the `>` symbol in the pipe
)


T.M(
    x = 5, z = [],
    y = 4 < 3  // Fails
)

T.M(
    x = 5, z = [],
    y = true & false  // Fails
)
T.M(
    x = 5, z = [],
    y = 4 = 3  // Fails
)
T.M(
    x = 5, z = [],
    y = false || false  // Fails
)
T.M(
    x = 5, y = true,
    z = [] :> int seq  // Fails
)
T.M(
    x = 5, y = true,
    z = ([] :> int seq)  // Works
T.M(
    x = 5, y = true,
    z = seq { 1 } :?> int seq  // Fails
)
T.M(
    x = 5, y = true,
    z = (seq { 1 } :?> int seq)  // Works
```
All the above fails are due to `FS0691: Named arguments must appear after all other arguments`.
The existing way of approaching this problem in F# is to parenthesize the expressions. This should be changed to be valid.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Convenience
2. Meeting expectations of users

The disadvantages of making this adjustment to F# are none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: https://stackoverflow.com/questions/45137074/f-assigning-inherited-property-values-in-inherited-constructors-parameter-list

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by abelbraaksma** [comment]
I'm not sure these are called 'property initializers', though I also don't know what the correct term would be otherwise ;). 

From the look of it, it appears to me to be a bug in the parser that some infix operators work and others don't. In fact, I'm a bit surprised that an expression like `1 + 2` is fine, but `true || false` isn't.

**Comment by smoothdeveloper** [comment]
With this suggestion, how is this handled?

```fsharp
open System.Runtime.InteropServices
type A () =
    static member A(a:int,b:int,c:bool,[<Optional>]d) = a,b,c
    
let d = true
let c = true

A.A(a=5|||4, b= 4&&&5, c = d, d = c,c)
```

Isn't there cases with lambda also where it would lead to similar inconsistency?

@abelbraaksma 
> I'm not sure these are called 'property initializers',

you are right, I'd call those _named method arguments_, and it also has something to do with methods returning types that have setable properties (that can be set with extra named arguments), this applies to constructor and method alike AFAIK.

**Comment by Happypig375** [comment]
A tuple expression should still be parenthesized. Let me edit this.

**Comment by Happypig375** [comment]
@smoothdeveloper 
```fs
A.A(a=5|||4, b= 4&&&5, c = d, d = c)
```
is equal to
```fs
A.A(a=(5|||4), b= (4&&&5), c = d, d = c)
```

Iirc, boolean expressions cannot appear directly in method arguments as they are interpreted as named arguments. They have to be parenthesized.

**Comment by Happypig375** [comment]
```fs
type C() =
    member this.M(x:bool) = ()
    member this.N() =
        let y = 1
        this.M(y = 1)
        // error FS0495: The member or object constructor 'M' has no argument or settable return property 'y'. The required signature is member C.M : x:bool -> (unit -> bool).
        this.M(1 = y) // Works

**Comment by Happypig375** [comment]
@smoothdeveloper 
According to [the docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#named-arguments), normal methods do not have "Assigning values to properties at initialization".

**Comment by smoothdeveloper** [comment]
@Happypig375 AFAIK, it just works the same as constructors, and is really convenient (in real code).

Short sample:

```fsharp
type A() =
    let mutable v = 0
    member this.V 
      with get () = v
      and set (value) = v <- value

type B = 
  static member B () = A()


let a = B.B(V=3)
printfn "%i" a.V
```

**Comment by dsyme** [comment]
I don't feel this leads to clearer code - and it would probably cause parser ambiguities.  There are advantages to requiring parantheses in some situations such as these

**Comment by Happypig375** [comment]
At least have a better error message here rather than `FS0691: Named arguments must appear after all other arguments`.
