### ISSUE TITLE
Add (^%) f = f to core library

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#83]
# Add (^%) f = f to core library [13134246] #

**Submitted by Dax Fohl on 3/25/2016 12:00:00 AM**  
**2 votes on UserVoice prior to migration**  

This allows method chaining with sequences etc need no parens:
http://stackoverflow.com/questions/36220283/anything-else-similar-to-haskells-in-f-other-than
Optionally call it ^$ for Haskell users, though it's not exactly the same as Haskell's $. ^% is (imo) the nicest on the fingers.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13134246)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13134246-add-^%-f-=-f-to-core-library.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 2.0 but we decided against it then.  Per policy closing so as not to revisit design decisions unless there's been a significant change in circumstances
