### ISSUE TITLE
Consider renaming repositories to "fsharp/suggestions" and "fsharp/design"

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#832]
I guess this is more of a meta-suggestion.

I like these URLs more:

https://github.com/fsharp/suggestions
https://github.com/fsharp/design

The "fslang-" name feels too heavy. Since GitHub handles redirects, it wouldn't be a technical issue. Thoughts?

**Comment by Swoorup** [comment]
Does that mean suggestions now imply all suggestions related to the languages, ecosystem, tooling?

**Comment by Happypig375** [comment]
>Does that mean suggestions now imply all suggestions related to the languages, ecosystem, tooling? 

Isn't that already the case? [Library RFCs](https://github.com/fsharp/fslang-design/tree/master/FSharp.Core-4.7.0) and [Tooling RFCs](https://github.com/fsharp/fslang-design/tree/master/tooling) are already in fslang-design.

**Comment by cartermp** [comment]
Tooling suggestions are typically done in dotnet/fsharp. If people file an issue in the incorrect place, we'll just close and point them to the right place to file an issue. It's rare enough that it shouldn't be a problem.

**Comment by dsyme** [comment]
I think I like the current names tbh - it means I know what the repos are if I see a fork of them

**Comment by cartermp** [comment]
Makes sense - will close.
