### ISSUE TITLE
Report less than zero on unsigned types as an error/warning

### ISSUE THREAD

**Issue by et1975** [fsharp/fslang-suggestions#834]
# Report less than zero on unsigned types

I propose the compiler reports the uses of unsigned types when comparing to 0 (constant):
`if/when x < 0uy` will never match.

## Pros and Cons 

The advantages of making this adjustment to F# are:
more user-friendly.

The disadvantages of making this adjustment to F# are:
none that I can think of.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
We do have a precedent for checking literals (e.g., match on string literals), but I'm not sure if there are custom ones like this in the compiler aside from null value checking. I'm certainly not opposed in theory, though I wonder if this is more valuable as an analysis service in the language service rather than a new compiler warning.

**Comment by jwosty** [comment]
This echoes of #661. I would argue its in the same philosophical direction; #661 just goes much further.

**Comment by dsyme** [comment]
My inclination is to decline this and instead you should add the check to FsLint
