### ISSUE TITLE
Add a "with" syntax for patterns

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#84]
**Submitted by Vasily Kirichenko on 3/30/2016 12:00:00 AM**  
**26 votes on UserVoice prior to migration**  

See detailed OCaml RFC https://github.com/ocamllabs/compiler-hacking/wiki/Add-a-%22with%22-syntax-for-patterns

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13218072)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13218072-add-a-with-syntax-for-patterns.md#comments)

**Comment by dsyme** [comment]
F# active patterns seem to cover this.  I don't think this extension really fits with the F# language design.
