### ISSUE TITLE
Allow using nameof as a constant in pattern matching

### ISSUE THREAD

**Issue by Tarmil** [fsharp/fslang-suggestions#841]
# Allow using nameof as a constant in pattern matching

I propose we allow using `nameof x` in pattern matching, like we would use a string literal.

This came up for me when serializing a union type from EventStore. Each event has a type, which is a string, and data, which is binary data. It would be quite natural to do the following:

```fsharp
/// Simplified version of EventStore's API
type RecordedEvent = { EventType: string; Data: byte[] }

/// My concrete type:
type MyEvent =
    | A of AData
    | B of BData

let deserialize (e: RecordedEvent) : MyEvent =
    match e.EventType with
    | nameof A -> A (JsonSerializer.Deserialize<AData> e.Data)
    | nameof B -> B (JsonSerializer.Deserialize<BData> e.Data)
    | t -> failwithf "Invalid EventType: %s" t
```

The existing way of approaching this problem in F# is to either:

* use string literals (and risk typos or mismatch with actual union names)

* use `if e.EventType = nameof A then ... elif e.EventType = nameof B then ...` which is repetitive.

## Pros and Cons 

The advantages of making this adjustment to F# are a small simplification for some metaprogramming code.

The disadvantages of making this adjustment to F# are N/A

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: N/A

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
The existing way of approaching this problem in F# can also be
```fs
let [<Literal>] NameofA = nameof A
let [<Literal>] NameofB = nameof B
let deserialize (e: RecordedEvent) : MyEvent =
    match e.EventType with
    | NameofA -> A (JsonSerializer.Deserialize<AData> e.Data)
    | NameofB -> B (JsonSerializer.Deserialize<BData> e.Data)
    | t -> failwithf "Invalid EventType: %s" t

**Comment by Tarmil** [comment]
Good point! It's verbose, but worth mentioning.

**Comment by abelbraaksma** [comment]
I think the suggestion makes sense, since `nameOf` compiles essentially to a constant.

But considering how much work implementing `nameOf` has been, and considering that that the compiler 'sees' `nameOf` as a function, I'm not sure it'll be trivial to implement. I don't even know if @Happypig375's suggestion works (haven't tried it),it could fail for the same reasons (meaning: literals are rather limited at the moment, though there are proposals to widen the allowed expressions).

**Comment by Happypig375** [comment]
@abelbraaksma 
```fs

Microsoft (R) F# Interactive version 10.7.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let A = 3;;
val A : int = 3

> let [<Literal>] NameofA = nameof A;;
val NameofA : string = "A"

> match "A" with NameofA -> "ayy" | _ -> "no";;
val it : string = "ayy"

>

**Comment by Tarmil** [comment]
> considering that that the compiler 'sees' `nameOf` as a function, I'm not sure it'll be trivial to implement.

I think it should be possible to special-case its parsing in pattern position without affecting its handling as an expression.

**Comment by abelbraaksma** [comment]
@Happypig375, thanks, I didn't have a computer to verify, I should've done that prior to posting ;). @Tarmil, with Happy's example to show that the compiler already considers an expression with `nameOf` constant, I agree, it shouldn't be so hard.

**Comment by cartermp** [comment]
@dsyme @Tihan this would be a great enhancement to the feature

**Comment by TIHan** [comment]
I think it's reasonable. If `nameof` can be used inside of attributes, it's effectively an expression that can be used in places that want literals.

**Comment by Tarmil** [comment]
So it is indeed easy to implement. [4 lines of code (plus moving a function to be able to call it)](https://github.com/Tarmil/visualfsharp/commit/012d84b137aa13865214580738497c2e59f55440) 😄

**Comment by bartelink** [comment]
Quite the red herring (this is obv useful in the language) but...
the [TypeShape UnionEncoder also offers a solution](https://eiriktsarpalis.wordpress.com/2018/10/30/a-contract-pattern-for-schemaless-datastores/) in this space (And FsCodec [leans](https://github.com/jet/FsCodec/blob/3bd04116a6086c504ffdb4426c31d01540d44a66/src/FsCodec.SystemTextJson/Codec.fs) on that )

**Comment by dsyme** [comment]
Marking approved-in-principle

**Comment by cartermp** [comment]
@Tarmil would you also be interested in taking a stab at an RFC?

**Comment by Tarmil** [comment]
@cartermp [Done 😊](https://github.com/fsharp/fslang-design/pull/450)

**Comment by cartermp** [comment]
Closing out as completed for F# 5.

Thanks for the design and initial implementation, @Tarmil!
