### ISSUE TITLE
Code clarity: Remove ... to|downto ... do ... loops from the language

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#85]
**Submitted by Alexei Odeychuk on 4/4/2016 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

The for ... to|downto ... do ... loop appears to be a mechanical carry-over from OCaml rather than a genuinely F#-specific construct. The for ...to|downto ... do ... loops do not lend themselves to use with sequences and other core F# types supporting IEnumerable interface. It is rarely if ever used in pro-level apps. More F#-typical construction is already available in the language with the for ... in ... do ... loop that has much better readability and expressiveness.

Example # 1:
```
// it provides equivalent behavior to: for i = 1 to 100 do ...
for i in 1 .. 100 do ...
// it provides equivalent behavior to: for i = 100 downto 1 do ...
for i in 100 .. -1 .. 1 do
```
Example # 2: Clear advantage in using the for … in … do … loop compared to the for … to|downto … do … loop in expressiveness
```
// some complicated expression to generate a sequence
let sq = seq { 1 .. 2 .. 999 }
(_........_)|> Seq.filter (fun item -> item <= 199 || item >= 501)
// simply try each item of the sequence supporting
// IEnumerable interface
for s in sq do …
```
Removing the for .. to|downto ... loops would simplify the language. The value added of this construct is limited and I believe its gradual removal from F# should be seriously considered.

### Alternative to be considered:

Not removing the for ... to|downto ... do ... loop from F#, losing the opportunity to streamline the language and discard an unneeded control flow item.

### Approach suggested:

I suggest that the for ... to|downto ... do ... loop be deprecated in F# vNext and removed entirely in F# vNext vNext.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13302753)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13302753-code-clarity-remove-object-pascal-style-for.md#comments)

**Comment by cartermp** [comment]
This would be a source breaking change (even if there is unlikely to be much F# source code out there that does this). It's one thing to break something in favor of making it's use first-class/in line with how things need to be done (e.g., byrefs) but it's another to simply remove things entirely.
