### ISSUE TITLE
new liberary function: `Set.differenceBy`

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#857]
# new liberary function: Set.differenceBy

I propose we add a new function `Set.differenceBy` to fsharp liberary.

```F#
set [2;3]
|> Set.differenceBy (set[1;2])
```

The existing way of approaching this problem in F# is ...

```F#
set [2;3]
|> fun ns -> Set.difference ns (set[1;2])
```

**Comment by Happypig375** [comment]
Or you can just...
```fs
set [2;3]
|> Set.difference <| (set[1;2])
```

**Comment by FunctionalFirst** [comment]
Or, even shorter
```f#
set [1; 2; 3] - set [1; 2; 4]
```

**Comment by yatli** [comment]
More of a general currying order problem than a specific library function.
```f#
let swapCurry f = fun a b -> f b a
```

**Comment by Happypig375** [comment]
@yatli That is equivalent to #620

**Comment by cartermp** [comment]
Thanks for the suggestion, but I don't think this will be implemented given that the `-` operator accomplishes the same task and the `Set.difference` function also exists. I think `-` would be preferred in most cases since it's nice and succinct:

```
> set [2;3]
- |> fun ns -> Set.difference ns (set[1;2]);;
val it : Set<int> = set [3]

> set [2;3] - set [1;2];;
val it : Set<int> = set [3]
```

> `|> Set.difference <| set [1;2]`

 🚓 🚔 👮 👮‍♀ Tie fighter operator use spotted! 🚓 🚔 👮 👮‍♀

**Comment by Happypig375** [comment]
@cartermp 🙅‍♂️Nah🙅‍♀️, 👉it is👉 👈the👈 🦋butterfly🦋 ♥️operator♥️ ➕and➕ 👨‍👩‍👧‍👦we all👨‍👩‍👧‍👦 🙇should🙇‍♀️ 📦bring📦 🔢some more🔢 🌱nature🌳 📩into📲 ✍️code📝.
