### ISSUE TITLE
Add the do .. while loops to the language (from Java, C, C++, C#)

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#86]
# Add the do .. while loops to the language (from Java, C, C++, C#) [13306077]

**Submitted by Alexei Odeychuk on 4/4/2016 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

I suggest adding the do .. while loops to F#. This feature would improve the expressiveness of the language and facilitate the migration of large codebases to F# from imperative languages such as Java, C, C++, C#.
I suggest using time-tested and popular syntax from Java, C, C++, C# (TIOBE TOP 4 languages as of March 2016), but with F#-style indentation instead of {}:
do
(\* indentation to indicate the body of the loop *) body-expression
while test-condition
The difference between the do .. while loop and the already existing in F# while .. do loop is that do .. while evaluates its test expression at the bottom of the loop instead of the top. Therefore, the body of the loop is always evaluated at least once before the condition is tested. If the test condition is true, the flow of control jumps back up to do, and the body of the loop evaluates again. This process repeats until the given test condition becomes false. Indentation indicates which expressions are in the loop, so code is clear and easy-to-understand.
It's good that F# is not pure functional language. I like that F# is a functional-imperative programming language suitable for writing real-world applications. So, it would be nice if F# would be fully developed language in terms of imperative programming features. It certainly would boost the F# popularity and facilitate the migration of existing code from C, C++, C#, Java.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13306077)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13306077-add-the-do-while-loops-to-the-language-from-j.md#comments)

**Comment by BentTranberg** [comment]
I am frequently struggling with this particular omission in F# when translating source from C# or one of the other old languages, and would really appreciate not having to jump through hoops and loops whenever I encounter the do-while construct. Workarounds produce ugly code, which often requires more testing, which is why this should be fixed ASAP.
