### ISSUE TITLE
Support XML documentation on end of line

### ISSUE THREAD

**Issue by breyed** [fsharp/fslang-suggestions#860]
# Support XML documentation on end of line

Triple-slash code comments like this is currently supported:

``` f#
/// The ratio of a circle's circumference to its diameter
let pi = 3.14
```

This proposal is that triple-slash code comments also be allowed at the end of a line:

``` f#
let pi = 3.14 /// The ratio of a circle's circumference to its diameter
```

## Pros and Cons 

End-of-line comments keep the code easy to read when there are many lines, each with short comments. Examples include constants and structure members.

Syntax coloring keeps the comments easy to read even when they aren't visually aligned.

A downside of end-of-line comments that they don't scale well to more than a quick sentence or two. But that's OK, use traditional line-above comments instead.

This is technically a breaking change, since currently the end-of-line comments apply to the next definition:

``` f#
let a = 1 /// This comment will be applied to b
let b = 2
```

But who does this on purpose? The change would only affect documentation, not running code, and would probably fix far more documentation than it breaks.

## Extra information

Google protobuf supports end-of-line comments in its .proto files, which it carries over to its generated code.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment]
I'd generally be in favor of this even though it is technically a breaking change. I agree that some of the current behavior isn't what people would expect.

**Comment by dsyme** [comment]
I'm not in favour - we should encourage well documented code using one established style (One Way To Do Things).   For people working in teams this is important.

The end-of-line style encourages short descriptions and shorter identifier names. I think it's not good style.

**Comment by breyed** [comment]
@dsyme I also value consistency, but the needs of different projects are sometimes just too great for one size to fit all. For example, public frameworks tends to have verbose documentation, with remarks, examples, etc. that are entirely impractical for single-line comments. However, line-of-business apps often have internal data structures that are largely self-explanatory with few or no comments. These include the kind of data structures that you see in protobuf files, with the same rationale for supporting end-of-line comments that Google used.

A key advantage of end-of-line comments is that you save 3 times the screen real estate: 1 line vs 3 lines per identifier. With before-line comments, you have the comment line and a blank line above. The blank line isn't technically required, but without it you lose visual coupling of the comment and its identifier. When working with complex line-of-business apps, being able to grok a good chunk of data structures at once is super productive.

> shorter identifier names
There may be a psychological bias of longer-comments -> longer identifier names. But there also may be a bias of less-room-for-comments -> feel a need for really good identifier names. Overall, good naming is just a skill of good developers, and I don't expect comment placement would have a noticeable impact.

**Comment by abelbraaksma** [comment]
I'd like support for xml documentation by itself, it has been broken since half way VS2017. Yes, you can use `///`, but the doc xml is not interpreted for tooltips anymore.

**Comment by dsyme** [comment]
Closing as this is not planned
