### ISSUE TITLE
Please add waitAfter function(tentatively) to MailBoxProcessor 

### ISSUE THREAD

**Issue by GratianPlume** [fsharp/fslang-suggestions#861]
# Please add `waitAfter` function to MailBoxProcessor 

As I know, the implementation of `MailBoxProcessor.scan` is to check for messages in the `inBox` and `arrivals` queues, and then wait for new messages for a while.

But when I use the MailBoxProcessor , I feel that the scene we often encounter is to do some operations (ex: respond to the last message), and then start waiting for a expected message. So that the message is not the one we have received, but  in the future will be received. Using `scan` to deal with this problem is not only a waste of performance, but may also get wrong results. So I hope there is a `waitAfter` function(tentatively): it will temporarily lock the queue to execute one specified function, and push all messages to inBox, and then wait a matching messages for some time.

The existing way of approaching this problem in F# is to add a field to the messages, in order to identify whether it is from the past. But it may increase communication costs and  the trouble.

## Pros and Cons 

I hope MailBoxProcessor will come in handy in this scenario. However, when the function is called then the queue is locked, and it will block the reception, so it can only be a fast return operation.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
- [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
- [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
- [x] This is not a breaking change to the F# language design
- [x] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
Why "tentatively"? Why include a feature that is "not fully worked out" or "not fully agreed upon"?

**Comment by dsyme** [comment]
Closing as the motivations for this are not fully explained, and there hasn't been support for it.
