### ISSUE TITLE
Ability to pass ownership of an IDisposable to caller

### ISSUE THREAD

**Issue by njlr** [fsharp/fslang-suggestions#862]
I propose we provide a mechanism for passing ownership of an `IDisposable` to the caller in computation expressions, particularly `async`. 

One approach would be: if a variable is declared with `use` but that variable is returned, then `Dispose` should not be called. If the workflow throws, then `Dispose` should be called as usual.

Some examples with the new approach:

```fsharp
async {
  use foo = new Foo ()
  return foo // foo.Dispose is not called
}

async {
  use foo = new Foo ()
  use bar = new Bar ()
  return bar // foo.Dispose is called, but bar.Dispose is not called
}

async {
  use foo = new Foo ()
  return 1 // foo.Dispose is called
}

async {
  use foo = new Foo ()
  failwith "Error!" // foo.Dispose is called
  return foo
}

async {
  use! foo = 
    async {
      use foo = new Foo ()
      return foo // foo.Dispose is not called
    }
  do! foo.Stuff ()
  return 1 // foo.Dispose is called
}
```
This enables us to do some work with an `IDisposable` and return it without using `let` with manual clean-up.  It looks like RAII from the C++ world. 

_Without the proposed change we need to do this:_ 

```fsharp
let createFooWithStuff = 
  async {
    let foo = new Foo ()

    try
      do! foo.Stuff ()
      return foo
    with exn ->
      foo.Dispose () 
      raise exn
  }
```

_With the proposed change we can do this:_

```fsharp
let createFooWithStuff = 
  async {
    use foo = new Foo ()
    do! foo.Stuff ()
    return foo
  }
```

## Pros and Cons 

The advantages of making this adjustment to F# are...

 * Much less error prone handling of `IDisposable`
 * (Arguably) more intuitive behaviour 

The disadvantages of making this adjustment to F# are...

 * Changes the semantics of existing code (although I'm not sure why you would return a disposed object anyway)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by jwosty** [comment]
>  This is not a breaking change to the F# language design

I just want to point out that the the outlined approach unfortunately is a breaking change. It's changing existing well-defined behavior (perhaps for the better).

**Comment by yatli** [comment]
I can think of one possible use case, where one has created multiple `IDisposable`, and want to return one of them programmatically.

How about an intrinsic function `unuse: IDisposable -> IDisposable`?

**Comment by njlr** [comment]
> > This is not a breaking change to the F# language design
> 
> I just want to point out that the the outlined approach unfortunately is a breaking change. It's changing existing well-defined behavior (perhaps for the better).

You are right, the exact approach I suggested would be breaking. However, it could also be implemented without changing existing code, for example with a new keyword (`give`?)

**Comment by Tarmil** [comment]
>     * (Arguably) more intuitive behaviour

I honestly don't see how a `use` that doesn't call `Dispose()` would be more intuitive :/

**Comment by abelbraaksma** [comment]
If you want the responsibility for the caller, why not making it an argument to a function?

**Comment by 0x53A** [comment]
I would *love* to have something like this in F#, but I am not sure if this is something that can be retrofitted.

If you haven't already, take a look at the ownership and borrowing mechanics of Rust.

**Comment by smoothdeveloper** [comment]
I like the idea of `unuse` or `give` (if I understand those correctly), it would be great if such value would create a warning if the value is bound (without `use`) to a local member at call site.

```fsharp
let produce () =
  let disposeSomeOtherPlace = new SomethingDisposable()
  give disposeSomeOtherPlace 

let consume () =
   let produced = produce ()  // warning: IDisposable value bound locally without the 'use' keyword
   ()

type Consumer () =
  let mutable disposable = null
  member x.Foo () = x.disposable <- produce () // no warning
```
The proper escape analysis though would be non trivial, probably akin to what is being done for nullable reference types, or going all the way to rust borrow checker.

**Comment by njlr** [comment]
> I like the idea of `unuse` or `give` (if I understand those correctly), it would be great if such value would create a warning if the value is bound (without `use`) to a local member at call site.
> 
> ```fsharp
> let produce () =
>   let disposeSomeOtherPlace = new SomethingDisposable()
>   give disposeSomeOtherPlace 
> 
> let consume () =
>    let produced = produce ()  // warning: IDisposable value bound locally without the 'use' keyword
>    ()
> 
> type Consumer () =
>   let mutable disposable = null
>   member x.Foo () = x.disposable <- produce () // no warning
> ```
> 
> The proper escape analysis though would be non trivial, probably akin to what is being done for nullable reference types, or going all the way to rust borrow checker.

I think your `produce` function should also be `use` instead of `let`. `give` should only be used in conjunction with `use`:

```fsharp
let produce () =
  use disposeSomeOtherPlace = new SomethingDisposable()
  give disposeSomeOtherPlace 
```

**Comment by dsyme** [comment]
From what I understand of this, this would be a breaking change as discussed above, and it also feels inconsistent with what exists.
