### ISSUE TITLE
Make 'enum' an alias of 'LanguagePrimitives.EnumOfValue'

### ISSUE THREAD

**Issue by cmeeren** [fsharp/fslang-suggestions#865]
# Make `enum` an alias of `LanguagePrimitives.EnumOfValue`

I propose we make `enum` an alias of `LanguagePrimitives.EnumOfValue`. That way, `enum x` works for any enum, not just `int`-based enums:

```f#
type MyByteEnum =
  | A = 1uy
  | B = 2uy

// The below is required today
match LanguagePrimitives.EnumOfValue 1uy with ...

// The below will work if this proposal is implemented
match enum 1uy with ...
```

The existing way of approaching this problem in F# is to simply use `LanguagePrimitives.EnumOfValue`.

To be clear, I think this proposal is as simple as replacing the current implementation of FSharp.Core's `enum` with 

```f#
let enum x = LanguagePrimitives.EnumOfValue x
```

(Perhaps it should be `inline`; others will know that better than me.)

## Pros and Cons 

The advantages of making this adjustment to F# are:
* Shorter
* More consistent
* More general

The disadvantages of making this adjustment to F# are:
* None

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: None

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this
  * Not checked because I don't think there is much to get involved with (AFAIK it's a single-line transparent, non-breaking change with only positive effects), and therefore, the effort for me to ramp up on FSharp.Core development would be orders of magnitude larger than if someone already working on FSharp.Core implement this.

**Comment by dsyme** [comment]
`enum` already exists, and non-integer enums are just very rare, and the user code required is just one line.   So I feel this is something decided in in F# 1.0.

**Comment by cmeeren** [comment]
Hm, I figured changing the implementation of `enum` was backwards compatible, but I guess it's actually a binary breaking change?

As for "very rare": I use them all the time in DB mapping code (for DB columns of type `TINYINT`). But of course, I may be a minority.

**Comment by charlesroddie** [comment]
I like non-int enums for similar reasons but agree that it's rare and `LanguagePrimitives.EnumOfValue` is OK. I prefer to define my own function so that I can enforce a type argument. Since `LanguagePrimitives.EnumOfValue(1uy)` appears to be applying a function but the output type is unknown (without reading ahead and doing some type inference).

**Comment by Tarmil** [comment]
It's not just a binary change, it's also a source change when using explicit type parameters. Currently you can do `enum<MyEnum> 42`, with this change you'd have to do `enum<_, MyEnum> 42`.
