### ISSUE TITLE
Add short form for operators used in mutable assignment

### ISSUE THREAD

**Issue by varon** [fsharp/fslang-suggestions#867]
# Add short form for operators used in mutable assignment

In C#, dealing with mutable data is syntactically nice and terse:
`myLongVariableName  += 1`.
in F#, we need to write this out in the highly repetitive 'long form':
`myLongVariableName  <- myLongVariableName  + 1`.

While F#'s assignment operator is different to C#, I can see no reason this familiar and widespread pattern cannot be applied to our code, such as:

`myLongVariableName  +<- 1`

This would greatly reduce the repetition and improve code clarity for tasks involving mutable data.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

Improved ergonomics and ease of use in writing lower-level code.

The disadvantages of making this adjustment to F# are ...

This would introduce 'new' operators.

## Extra information

Ideally this should function with any operator present, from `^^^` for bitwise-XOR to `/` on DateTime.

Estimated cost (XS, S, M, L, XL, XXL): 

XS

Related suggestions: 

## Affidavit

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by realvictorprm** [comment]
I'm in favour of this especially for places which require a lot of mutation for efficient implementations e.g. game development

**Comment by jwosty** [comment]
`incr` exists, but you can only use it a) to increment and b) on `ref` values, not `byref`. However it is possible to define a useful user-defined function:

```
let inline (+<-) (var: byref<'a>) (incValue: 'a) = var <- var + incValue
let mutable x = 10
let mutable y = 0.5
&x +<- 1
&y +<- 0.25
```

**Comment by varon** [comment]
@jwosty While a decent approximation, that doesn't work on properties.
`stdin(3,1): error FS3236: Cannot take the address of the value returned from the expression. Assign the returned value to a let-bound value before taking the address.`

**Comment by abelbraaksma** [comment]
There's an issue out there that allows implicit variables, in which case one could write:

```f#
let mutable myvar = 1
myvar <- _ + 42
```

I don't really like the idea of adding a large set of hard-to-read operators, even more so since mutability is comparatively rare. I do second the awkwardness of repetition though, which is unfortunate. But perhaps using implicit arguments this problem would be sufficiently alleviated.

**Comment by Happypig375** [comment]
@abelbraaksma Imagine this with #506, now we can finally write four underscores with different meanings in one line!
```fs
let f _ : _ = sequence <- _.SelectMany(_.Children)
```

**Comment by cartermp** [comment]
I think this one is pretty unlikely to happen. I can certainly appreciate wanting it to be simpler (having written hundreds of these in the F# compiler codebase). And making things less surprising for those with a C-style language background isn't bad. But it's also not very inconvenient.

But a common criticism of F# is the amount of "weird operators", so if this were to be done it would be `+=`/`-=`. Which would then be confused with `:=` at some point, which already goes down the unfortunate, confusing path of reference cells vs. mutable values. At least with distinct syntax today, there's very clear lines.

**Comment by varon** [comment]
@cartermp  - Thanks for the realistic assessment.

Is there anything we can do to make this type of operation less painful?

**Comment by abelbraaksma** [comment]
> Is there anything we can do to make this type of operation less painful?

@varon It is, of course, always possible to define your own `+=`, `-=` etc. And with the onset of extension members becoming visible to trait constraints, it may even be possible to create some kind of library that leverages a set of static inline extension methods to get this working in a wide array of scenarios. Perhaps the feature is a good candidate to add to the F#+ libraries (also on github), to allow wider adoption.

Though, since the main use case is probably mutable variables, if you'd limit it to that, their definition is rather straightforward. For a while I used it in my own projects, but I used it so rarely that I removed them eventually.

**Comment by varon** [comment]
@abelbraaksma - Unfortunately none of the library-level solutions work on properties or indexers, that's the major sticking point to doing custom approaches.

**Comment by abelbraaksma** [comment]
@varon, you're right, I thought something was possible with SRTP and `set_Item`, but although it is indeed possible to get the member, apparently F# doesn't let you use it (let alone turning the function into some useful operator syntax):

```f#
> let inline test i x array =
    ( ^a : (member set_Item : int -> obj -> unit) array, i, x);;

      ( ^a : (member set_Item : int -> obj -> unit) array, i, x);;
  ----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning FS0077: Member constraints with the name 'set_Item' are given special status by the F# compiler as certain .NET types are implicitly augmented with this member. This may result in runtime failures if you attempt to invoke the member constraint from your own code.

val inline test :
  i:int -> x:'a -> array: ^a0 -> unit
    when  ^a0 : (member set_Item :  ^a0 * int * obj -> unit)

> test 1 (box 2) [|1;2;3|];;
System.NotSupportedException: Dynamic invocation of set_Item is not supported
   at <StartupCode$FSI_0138>.$FSI_0138.main@()
Stopped due to error
> 
```

This leaves reflection, but that'll never get you to write `foo.[3] += 12` as you cannot get to the structure on the lh side (apart from reflection shouldn't be used for this anyway).

**Comment by smoothdeveloper** [comment]
> Unfortunately none of the library-level solutions work on properties or indexers,

> This leaves reflection, but that'll never get you to write foo.[3] += 12 as you cannot get to the structure on the lh side (apart from reflection shouldn't be used for this anyway).

Could this lay room for handling properties like how events are exposing `Add`, `Subscribe` and other methods. 

In essence, making properties first class objects from standpoint of F# compiler, possibly in a zero cost abstraction manner (I'm not sure this is the case for events).

for example, turning
```fsharp
foo.[3] += 12
```

into
```fsharp
let p : propref<int> = foo.[3].GetProperty ()
p.SetValue (p.GetValue() + 12)
```

**Comment by abelbraaksma** [comment]
@smoothdeveloper, I'm not sure I follow. Do you mean to expose the construct on the lh-side of an operator, such that it's possible to assign? Somehow, you'd need to be able to distinguish between indexers, properties, mutable fields, mutable variables, reference cells etc.

**Comment by smoothdeveloper** [comment]
@abelbraaksma I believe right now that the operator could be defined by calling into static overloaded methods in same fashion F#+ is implemented.

In current version of compiler, those overloads may be defined for:
* events
* byrefs

I'm unsure it would work for mutable locals/fields, but possibly picked up by the byref and just work.

For properties, it would require F# compiler to have some infrastructure towards properties similar to how events are exposed as an object API to F# code, while underlying, it doesn't work that way in CLR / C#.

Not sure if that clarifies.

**Comment by realvictorprm** [comment]
@smoothdeveloper is there even something like a `propref` ?

**Comment by dsyme** [comment]
This is in the category of things already decided since F# 1.0 and I don't see particular reasons to revisit that core decision.

Thanks for the suggestion and please keep them coming in.
