### ISSUE TITLE
Relax indentation rules on mutually recursive functions when using with CE

### ISSUE THREAD

**Issue by Swoorup** [fsharp/fslang-suggestions#868]
# Fix indentation rules on mutually recursive functions when using with CE

Its common to write F# async workflow in the following style:
```fsharp 
let doSth () = async {
...
}
``` 

I propose we allow writing recursive function as follows with CE at the same line as let/and definition:
```fsharp
let rec async1 () = async {
  return! async2 ()
}
and async2 () = async {
  return 1
}
```

Currently the compiler gives the error: `The value or constructor 'async2' is not defined.`

The existing way of approaching this problem in F# is to change the style so that async keyword appears in the next line after the let bindings.

```fsharp

let rec async1 () =
  async { return! async2 () }
and async2 () =
  async { return 1 }
```

## Pros and Cons 

The advantages of making this adjustment to F# are, consistent with the first example. 

The disadvantages of making this adjustment to F# are none.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S-M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
Yes, this is ok, I'd be happy if we can make this relaxation

**Comment by dsyme** [comment]
Completed (in preview)
