### ISSUE TITLE
Discriminated Unions Tag Name Conflicts

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#869]
i have two DU types in same namespace:
```F#
type Align = Left | Center | Right
type Justify = Bottom | Center | Top
```
and i use them:

```F#
let aligns = [Left ; Center ; Right]
let justifies = [Bottom; Center; Top]
```
the `aligns` will araise error: the `Center` is `Justify.Center`.

may i use some methods to resolve it?

```F#
open Align
let aligns = [Left ; Center ; Right]
open Justify
let justifies = [Bottom; Center; Top]
```

or

```F#
let aligns:Align list = [Left ; Center ; Right]
let justifies:Justify list = [Bottom; Center; Top]
```

those two answers is failed to resolve the problem.

**Comment by kerams** [comment]
You need to qualify the cases when there are conflicts
```
let aligns = [Align.Left ; Align.Center ; Align.Right]
let justifies = [Justify.Bottom; Justify.Center; Justify.Top]
```

Please use Slack or Twitter for questions like this next time. This repo is for language suggestions.

**Comment by xp44mm** [comment]
i know your method. this is just for example to  illution the issue. i suggest to assign once at parent level, instead of every local place to asign element's type name.

**Comment by abelbraaksma** [comment]
@xp44mm, in F#, when you declare a DU type, all its members are in scope, regardless whether you open the type. Changing this behavior in any way would be a major backwards compat issue.

This type of inference conflict is fairly common. The ways to work around it are numerous, here are a few: you can use unique case names, hide the type in a module and open that (which would basically be what you suggest), change the order of `open` (last one wins), or to save typing on long names, use a type alias.

There have been suggestions to change this behavior in the past, they all boiled down to: too complex to implement (type inference is a very crucial, and tricky part of the compiler), or backwards incompatible, or introducing new syntax that essentially complicates things further.

I'm not saying nothing can be done, but you'll need a good proposal that deals with all these issues. 

Iirc, one is "approved in principle" that takes the known type from the first case in a block and uses that info to infer the rest. But I can't readily find the language suggestion back.

**Comment by xp44mm** [comment]
@abelbraaksma thank you! DU cases are subclasses of DU type, for let me knowning it!

**Comment by xp44mm** [comment]
@abelbraaksma maybe DU can implement like this:
```F#
{|
Kind = "Center";
Top = Some top;
Center = Some center;
Bottom = Some bottom;
|}
```

**Comment by abelbraaksma** [comment]
>  DU cases are subclasses of DU type,

No, I was talking about inference and that cases come in scope once the type is in scope. DU's are internally implemented with hidden nested classes, but that's magic that the F# compiler does. DU's are sealed types and cannot be inherited from.

> maybe DU can implement like this: 

I don't understand this. You show an example of an anonymous record. Records hold more than one field, DU's represent one and only one of a set of possible fields. They are somewhat similar, though certainly not the same, to the C++ overlapping `union` type.

> avoid use inherit is a rule for functional. 

That's a general rule and indeed, that's what's often used by functional programmers. Though F# can mix, and does support inheritance on normal classes. But not on F# specific types like records, discriminated unions, tuples, functions.

**Comment by xp44mm** [comment]
thank you very much. i run out of this topic. this is just spark a idea from DU implement method. but  i get your golden idea behind about internal F# implement method with my sand idea. it's valuable. i got a lot of instructions.

**Comment by Swoorup** [comment]
You can enforce qualified access like

```fsharp
[<RequireQualifiedAccess>]
type Align = Left | Center | Right
[<RequireQualifiedAccess>]
type Justify = Bottom | Center | Top
```

**Comment by dsyme** [comment]
Closing as this was more of a question than a suggestion
