### ISSUE TITLE
Add AST to string transformation to the compiler

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-suggestions#871]
# Add AST to string transformation to the compiler

I propose we add functions to transform the F# AST to strings.  Functions such as `ToString`, `ToFullString`, and `WriteTo`.  These would mirror the accompanying functions that exist in [Roslyn](https://docs.microsoft.com/pl-pl/dotnet/api/microsoft.codeanalysis.syntaxnode?view=roslyn-dotnet).  Languages like Scala and C# have this built into the compiler and as a result have better meta-programming and refactoring capabilities.

The existing way of approaching this problem in F# is to use some of the functionality in Fantomas, which is not ideal is it's not the fastest process taking 4 seconds for a 800 line file.  Myriad currently uses this functionality in Fantomas but this should be a feature of the compiler  and would allow further meta-programming and refactoring capability to come to fruition.  

## Pros and Cons 

The advantages of making this adjustment to F# are better support for refactoring in IDE's and code transformation/meta-programming features.

The disadvantages of making this adjustment to F# are the time to complete the work.

## Extra information

Estimated cost (S/M): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Krzysztof-Cieslak** [comment]
Bunch of use cases we (FSAC/Ionide) have for AST->string (we currently implement them with string writer 😭):
* generate interface stub
* generate record stub
* generate pattern matching stub.

Also, I imagine this could be useful for any kind of refactorings like `extract binding` or `lock type signature`, that we could potentially implement in the future.

**Comment by Thorium** [comment]
Meanwhile the idea is generally good, I hope this wouldn't encourage users to move towards string parsing.

**Comment by 7sharp9** [comment]
@Thorium The idea is about producing a string from an AST not parsing or splicing strings etc.

**Comment by yatli** [comment]
mind if I tag along? this is cool.

**Comment by dsyme** [comment]
This is a tooling suggestion but entirely reasonable  It overlaps somewhat with Fantomas and will depend on syntax trivia to get a high-quality syntax printing back out.  It's probably best prototyped as part of Fantomas?

**Comment by Krzysztof-Cieslak** [comment]
@dsyme

>  It's probably best prototyped as part of Fantomas?

Fantomas is already providing `AST -> string` API that we use in FsAST/Myriad, but it seems to be slower than expected according to @7sharp9's tests.
Also, I'd assume this suggestion includes adding missing trivia information to the AST - something that Fantomas works around by doing multiple passes and marshalling newly generated code with trivia from old files (probably one of the reasons for observed slowness?)

**Comment by 7sharp9** [comment]
Perfomance is due to trivia having to be re folded back into the AST.  I have opened an issue in Fantomas to get to the bottom of it.

**Comment by 7sharp9** [comment]
Full disclosure:  I use this in Falanx and Myriad.  Myriad uses a AST to string conversion where as Falanx used a Quotation to AST to string conversion.  

For obvious reasons the quotation to AST to string is not high quality output :-). Still entirely usable just not necessarily idiomatic code like you would get from Myriad.

**Comment by nojaf** [comment]
> Performance is due to trivia having to be refolded back into the AST.

Trivia is only involved if you have source code, so I'd really like to have some more details here.
If you create AST with the FSharpChecker and try to format that with Fantomas the argument of trivia doesn't stand. 

I encourage everyone to open issues at the Fantomas repository with their non-optimal performing use-case. Provide enough details and I'm confident we can improve the situation together. Fantomas performance is not beyond saving.

**Comment by 7sharp9** [comment]
In this instance I was talking about the performance of formatting code within VSCode or Rider.  800 lines taking 4 seconds.
