### ISSUE TITLE
Scoped type aliases in functions/classes

### ISSUE THREAD

**Issue by Swoorup** [fsharp/fslang-suggestions#875]
I propose we allow type aliases inside functions or types or classes, solely as a language feature. 

The existing way of approaching this problem in F# is not present.

## Pros and Cons 

The advantages of making this adjustment to F# are clear readability. For instance, interfaces serve as a boundary of communication between functions. And we as developers intend to make it self documentating as much as possible. Take for example the following sample code: 

Current:
```fsharp
type IWorkerService<'key, 'result when 'key :> IConsistentHashable> =
  abstract member CreateJob: 'key -> Async<Job<'key, 'result>>
  abstract member GetJobs: unit -> Async<Job<'key, 'result> list>
  abstract member GetJobById: 'key -> Async<Job<'key, 'result> option>
  abstract member GetJobResultById: 'key -> Async<'result option>
```

With this suggestion:
```fsharp
type IWorkerService<'key, 'result when 'key :> IConsistentHashable> =
  type Job = Job<'key, 'result>
  
  abstract member CreateJob: 'key -> Async<Job>
  abstract member GetJobs: unit -> Async<Job list>
  abstract member GetJobById: 'key -> Async<Job option>
  abstract member GetJobResultById: 'key -> Async<'result option>
```
It is obvious that in the first example type signatures are difficult to read when there are multiple generic arguments involved, making the developer hand-write each one of them. The type signatures of each member in the second one is obviously much more sensible to read at a glance. 

This should apply to classes, records, including unions. I saw discussion around having nested classes, but have omitted out for this suggestion.

The disadvantages of making this adjustment to F# are (TBD). 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M-L

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
We will track this by https://github.com/fsharp/fslang-suggestions/issues/150
