### ISSUE TITLE
"clamp" function

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-suggestions#879]
# `clamp` function

I propose we add a `clamp` function to the F# core library, defined as (or behaving as if defined as):

```
let inline clamp minimum maximum value = value |> max minimum |> min maximum
```

The existing way of approaching this problem in F# is to simply define this function yourself, or to use the ``min``/``max`` functions directly.

## Pros and Cons 

This suggestion makes a very commonly useful function easier to use and increases visibility of such a function (other F#-ers have admitted to using this functionality but not knowing there is a name for it). This function is already present in .NET as [System.Math.Clamp](https://docs.microsoft.com/en-us/dotnet/api/system.math.clamp?view=netcore-3.1). I argue that it is almost just as ubiquitous ``min`` and ``max``. Additionally, if in the future the implementation were to work with the JIT to take any [clever optimizations](https://stackoverflow.com/questions/427477/fastest-way-to-clamp-a-real-fixed-floating-point-value) into account, code using a standard F# ``clamp`` function would automatically benefit without any extra effort. This may be a potential concern when dealing with tight loops that process lots of data (like for example in audio processing). I haven't any concrete data on this; someone would have to bring this up again later.

Increased FSharp.Core complexity.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by Happypig375** [comment]
I would say that in addition to Clamp, F# should have equivalents for all methods in [System.Math](https://docs.microsoft.com/en-us/dotnet/api/system.math?view=netcore-3.1).

**Comment by dsyme** [comment]
I'm trying to judge whether people really think such a simple function to author needs to go in FSharp.Core.  

At the moment I'd say "no" - it's easy to write this yourself.

**Comment by dsyme** [comment]
Closing as there are now hundreds of standard math functions (e.g. `relu` and all the other activation functions) - we can't add them all the the F# pervasives
