### ISSUE TITLE
Language level built-in documentation browsing

### ISSUE THREAD

**Issue by kMutagene** [fsharp/fslang-suggestions#882]
# Built-in documentation browsing

I propose a feature for F# that is similar to R's [browseVignettes](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/browseVignettes) function, that opens documentation for a nuget package in the browser. 

I imagine it looking something like this:

```
#r "nuget: SomePackage"

SomePackage.BrowseDocumentation()

or

browseDocumentation somePackage
```

Most nuget packages contain already some link to either a docs page or the source directory on github:

![image](https://user-images.githubusercontent.com/21338071/84566627-10079c80-ad73-11ea-9802-40f99167198d.png)

Opening these links directly from your scripting environment would be a great addition, especially for data scientist that use F# from a notebook environment and don't have access to features that some IDEs may provide to solve this problem. 

## Pros and Cons 

The advantages of making this adjustment to F# are:
 - Faster access to documentation directly from the scripting environment
 - This feature could as well be good for all other .Net languages and be generalized (i dont know if the word 'easily' is of good use here, but once it works for F# i would imagine generalizing it would be not as hard as the implementation itself)

The disadvantages of making this adjustment to F# are:
 -  I cant see any

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): L, 
One would have to crawl nuget packages for links and dynamically generate some kind of extension or member for packages. Alternatively one could crawl nuget.org and build a documentation index?

## Affidavit (please submit!e.g.)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [?] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by toburger** [comment]
This suggestion fits well into the F# 5 focus of better interactive programming.

Especially in environments where no auto completion is available (e.g. Jupyter Notebooks) such introspection functionality is very useful and a lot of dynamic languages define those introspection capabilities.

I suggest to go even further with the capabilities and expose a couple of introspection functions. Clojure for example has a bunch of very useful introspection functions which help a lot in introspecting a REPL session. The most prominent are:

* [``doc``](https://clojuredocs.org/clojure.repl/doc)
* [``dir``](https://clojuredocs.org/clojure.repl/dir)
* [``apropos``](https://clojuredocs.org/clojure.repl/apropos)
* [``find-doc``](https://clojuredocs.org/clojure.repl/find-doc)
* [``source``](https://clojuredocs.org/clojure.repl/source) this one is tricky when using for libraries without source link tough

The functions return data structures that can be filtered and transformed in the REPL.
This behavior deviates from the original issue where a browser window should open, but this could be made possible with a utility function and the combination with ``doc`` where doc not only returns the documentation string but also the URL to the original documentation:

```fsharp
max |> doc |> browse
```

Optionally to make sure those functions are only used in an interactive environment (and to avoid ambiguity) they could be made available from the `fsi` binding (e.g. `fsi.Dir`, `fsi.Apropos`).

```fsharp
max |> fsi.Doc |> fsi.Browse
```

And to ease the above case:

```fsharp
max |> fsi.BrowseDoc
```

**Comment by kMutagene** [comment]
@toburger that would be awesome! I agree that the more one can do in this context without ever leaving the interactive environment, the better. 

While i really like your additions to the suggestion, I think stuff like 

```F#
max |> doc
```

can only realistically work with the FSharp.Core library if i understand this correctly. Every other nuget package can have basically any kind of documentation, so we would have to enforce a documentation style for this feature to work with third party libraries. 

```F#
Library.Namespace.functionName |> doc
``` 

would not work if the creator of `Library` didn't add functionality to support `doc` (I guess one could always return "no documentation found for Library.Namespace.function" though).

This can work with XML/Markdown comments (inline documentation) though, so there would be a possibility to display them without intellisense. 

The reason why (for starters at least) i thought about opening the link that is indexed on nuget.org is that i think this is the most common and easy way one could access docs for packages in the nuget ecosystem.

**Comment by toburger** [comment]
> While i really like your additions to the suggestion, I think stuff like
> 
> ```fsharp
> max |> doc
> ```
> 
> can only realistically work with the FSharp.Core library if i understand this correctly. Every other nuget package can have basically any kind of documentation, so we would have to enforce a documentation style for this feature to work with third party libraries.

Maybe @Krzysztof-Cieslak can help here. He has created an Ionide feature called "Info Panel" which provides introspection functionality inside of Visual Studio Code. 🤔 

![image](https://user-images.githubusercontent.com/728782/85305717-beb38780-b4ad-11ea-89a9-ede5c8fbc407.png)

**Comment by Krzysztof-Cieslak** [comment]
> Every other nuget package can have basically any kind of documentation

That's not really true - there is a single format of documentation metadata created by either F# and C# compilers - XML documentation. `///` documentation used in F# is basically syntactic sugar around it - it puts all content into `<summary>` section of XML doc.
As such it's possible to provide documentation for any .NET library (that includes XML documentation in NuGet package).

Most of the things displayed in the info panel are based on reading this XML documentation - that's the main, middle section on the screen above. Header (function signature) and footer (additional details) are generated using Symbols API in FCS.

---

In general, I'm against this feature. As @dsyme said in https://github.com/fsharp/fslang-suggestions/issues/599#issuecomment-320420094 F# scripts should always be created in the context of rich F# editor tooling - and we have this documentation information inside our tooling. Rich REPL experience some of the other languages have is caused by the fact their editor tooling is insufficient for normal development, we don't have this problem.

**Comment by kMutagene** [comment]
> Every other nuget package can have basically any kind of documentation
> 
> That's not really true - there is a single format of documentation metadata created by either F# and C# compilers - XML documentation.

To clarify: With documentation I was in the original proposal referring to the documentation website that the authors of nuget packages as indicated by screenshots, and making these 'browsable' from the F# REPL. Sites like [this](https://fake.build/) or [this](https://muehlhaus.github.io/FSharp.Plotly/index.html)

> As @dsyme said in #599 (comment) F# scripts should always be created in the context of rich F# editor tooling

I agree when using F# inside of editors such as VS/VSCode. This proposal mainly addresses using F# in a notebook environment, which seems to be a selling point for F#5 for doing all kinds of Datascience, and in that regard i disagree that you should be forced using IDEs. I also dont' get the same feeling from the comment you mentioned, which simply points out that at the time (2017), most if not all F# was being used inside an IDE, which may have been true back then but i think with the advent of notebooks that might change, at least in academic use.

The last time i used dotnet interactive notebooks, it was not even possible to autocomplete FSharp.Core functions. I agree if we would get the same level of tooling in dotnet interactive as we get in IDEs, making XML docs browsable is unnecessary, but i am not aware of a feature that covers what i mentioned in my original proposal, and still think it would be usefull. What could be true is that the whole proposal itself is better fitting for a tooling library/ tooling for dotnet interactive.

**Comment by toburger** [comment]
> > As @dsyme said in #599 (comment) F# scripts should always be created in the context of rich F# editor tooling
> 
> I agree when using F# inside of editors such as VS/VSCode. This proposal mainly addresses using F# in a notebook environment, which seems to be a selling point for F#5 for doing all kinds of Datascience, and in that regard i disagree that you should be forced using IDEs. I also dont' get the same feeling from the comment you mentioned, which simply points out that at the time (2017), most if not all F# was being used inside an IDE, which may have been true back then but i think with the advent of notebooks that might change, at least in academic use.

That's also my experience when using Jupyter Notebooks. There exists at least a very basic auto completion now, but it is far from being useful/usable. I ended up writing my scripts in Ionide and then porting them to Notebooks which is not the most pleasuring experience.
But I'm quite sure this will change. Visual Studio Code has basic support for Jupyter Notebooks integration (https://code.visualstudio.com/docs/python/jupyter-support) and maybe there will be some Visual Studio Code integration into Notebooks itself?

Still there are circumstances when no rich editor is available, where such REPL helpers are useful.

I agree, maybe this is better fitting into a tooling package eventually specific to Jupyter Notebooks with nice output formatting.

**Comment by dsyme** [comment]
I can't see us building this into the language. It's a great idea and can be added to any of the F# tooling such as Ionide or notebooks
