### ISSUE TITLE
[Breaking] Deprecate UseNullAsTrueValue and remove it from Option

### ISSUE THREAD

**Issue by charlesroddie** [fsharp/fslang-suggestions#884]
## Problems of `UseNullAsTrueValue`

F# allows the `UseNullAsTrueValue` attribute on DUs mainly used by `Option`. Problems created:

1. `.ToString()` results in a NRE in the relevant DU case. E.g. `None.ToString()`.
2. [baroque special compilation rules are needed for opt.HasValue](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md#interaction-with-usenullastruevalue)
3. `string` becomes different from `ToString()`, giving F# multiple string methods. I.e. this makes representing objects as strings difficult if they contain DUs. This makes it harder to get compile-time string methods and results in the current situation where typical F# code doesn't work with AOT or linkers.
4. Users are often exposed to `null` in tooling and are confused. Questions about this get [asked](https://stackoverflow.com/questions/41337310/f-method-returns-null-instead-of-option) [all](https://stackoverflow.com/questions/52827260/why-none-change-to-null-automatically-in-f) [the](https://stackoverflow.com/questions/11959321/why-is-none-represented-as-null) [time](https://stackoverflow.com/questions/8552283/fsharp-options-and-null) on StackOverflow and slack.
5. `Option` can't implement IEnumerable becaue it would fail on `None`.
6. `UseNullAsTrueValue` creates [extra work](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md#interaction-with-usenullastruevalue) for implementing NRTs in F#.

Point 1. puts F# options behind C# NRTs in terms of type safety (but not expressiveness).

## Now is the time

**Libraries are [adapting to NRTs](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/)**. Removing `UseNullAsTrueValue` fits in as a small piece within this migration.

**Struct DUs and NRTs** mean that the possible small performance ~~/memory~~ advantage of `UseNullAsTrueValue` when using nulls is not needed now. For example, instead of `[<CompilationRepresentation (CompilationRepresentationFlags.UseNullAsTrueValue)>] type T = A | B of int
`, you can use a struct `[<Struct>] type T = A | B of int` or an NRT `type T = int?`.

## Changes needed in user code.

1. Where `UseNullAsTrueValue` is used directly, this will need to be removed or replaced with a `[<Struct>]` annotation or a NRT as appropriate. This is very rare as direct use of `UseNullAsTrueValue` is very rare.
2. C# libraries referencing F# code may need to be adjusted if they use `== null` rather than `FSharpOption<_>.IsNone`. We'd need to make sure that there is an appropriate warning or suggestion on use of this code. You might get an unnecessary check warning on `==null` on a non-NRT. If that's not enough we could use more drastic methods like depreciating `.Value` or changing this to give an NRT. We will need to encourage these changes anyway in order to use NRTs to allow sensible use of F# options from C#.

No work should be needed in F# code around options, although hypothetically there are some terrible ways you could write code in F# which would break if None stops being represented as `null`.

**Comment by Tarmil** [comment]
Yeah there are a ton of considerations to have before doing such a change. A few that come to mind:

* Code that uses reflection may break. I'll have to check, but I think that my own `FSharp.SystemTextJson` currently assumes that `None` is `null`.

* `None` being represented as `null` allows F# optional arguments (with `?arg` syntax) to be easily compiled in such a way that they are also optional for a C# caller. The compiled form is essentially equivalent to `Option<T> arg = null` in C#. This obviously becomes incorrect if `None` is not `null` anymore. I think the only way to keep this working would be to automatically insert the IL equivalent of `if (arg == null) { arg = None; }` at the beginning of the method.

* On the plus side, while you mention the memory advantage of using `null`, it seems like an obvious problem but actually it's not much at all. Representing `None` as a proper value doesn't mean allocating on every use of `None`. All `None`s of the same type can be represented by the same static value. That's exactly how the empty list is already handled:

    ```fsharp
    > obj.ReferenceEquals(([]: int list), ([]: int list));;
    val it : bool = true
    ```

**Comment by charlesroddie** [comment]
> I think the only way to keep [optional arguments] working would be to automatically insert the IL equivalent of if (arg == null) { arg = None; } at the beginning of the method.

I think this is doable. It would mean specifying an NRT `FSharpOption<T>?` in C# code when used as an optional argument. I think that does make sense. Optional arguments will need to be redone anyway because of NRTs. There's some interesting stuff we could do with your approach in future, like allowing default values in parameters without the restriction that they should be strings/null/structs.

> Code that uses reflection may break. I think that my own FSharp.SystemTextJson currently assumes that None is null.

I don't quite see this. Worth checking. A quick search in your library suggests to me that you don't match or encode F# code using null, but do put some nulls into Json objects for Options and separately for other things with UseNullAsTrueValue. So without changing the code, Options would stay the same and encode as Json Null, but DU types which remove UseNullAsTrueValue would see the Json representation change.

> Representing None as a proper value doesn't mean allocating on every use of None.

Great point. I'll edit my post to adjust for this.

**Comment by abelbraaksma** [comment]
This is an interesting proposal, and I do see some merits, but if I'm understanding this correctly, this would break binary compatibility. Any existing library that expects an option or other type with `UseNullAsTrueValue` will break when called with a newer program that has this feature. That would inevitably lead to F# library vendors having to maintain two versions of their code.

The binary compat issue may also lead to problems with marshaling, as the size of members changes, and this could already play a role when you simply pin an object: it used to be "just null" in a certain state and now becomes something different.

It's also not necessarily smaller or faster, that really depends on the algorithm and the given set. I've seen that with `ValueOption`, which sometimes improves, sometimes worsens performance. 

Maybe a way forward would be to make this an opt in feature? Either per file as a pragma, or as a commandline switch?

There's also a related proposal out there to make `Option` type-directed to be automatically either a value or a reference type option.

**Comment by charlesroddie** [comment]
> this would break binary compatibility. Any existing library that expects an option or other type with UseNullAsTrueValue will break when called with a newer program that has this feature. That would inevitably lead to F# library vendors having to maintain two versions of their code.

That doesn't sound right to me. Option: both pieces of code need to be using the same FSharp.Core but that is a normal requirement. Other type with UseNullAsTrueValue: an existing dll called by a new code will not break as UseNullAsTrueValue will function as befo

**Comment by Tarmil** [comment]
>     * Option: both pieces of code need to be using the same FSharp.Core which is a normal requirement.

Well, no. They both need to be *compiled against* the same FSharp.Core, which must also be the one referenced at runtime, and that is definitely not a normal requirement. Right now I can take a library I compiled 10 years ago and run it in a program referencing FSharp.Core 4.7. With this change, I won't be able to. When that library receives a `None` from my code, it will check it against `null` and think it's a `Some`.

**Comment by abelbraaksma** [comment]
Also, a lot of code can be auto inlined, even if you don't specify it. That can be done by fsc, an external optimizer like Warp, or if you use prejitted libraries.

> an existing dll called by a new one will not break as UseNullAsTrueValue will function as before, 

I thought the idea was to disallow this functionality completely, so that fsc can use new optimizing paths. I now understand that both functionalities remain, albeit deprecated. But since the nullifying of a type is a very strong feature, esp with options, wouldn't a better path be to retain this for existing types, and deprecate or for new ones, if we find it that it's more efficient in a given case? Add to that the type directed approach (which would allow any function that takes or returns an option to take either a value option or normal option without extra work), wouldn't we then have the best of both worlds?

**Comment by charlesroddie** [comment]
I see so the nulls go into compiled code. Do we need an intermediate FSharp.Core that reduces this exposure of implementation details?

@abelbraaksma Option is 99% of this. It might be nice to have Option mean ValueOption, but that would be very hard, a lot harder than this proposal. The only language request I can see is [this](https://github.com/fsharp/fslang-suggestions/issues/874), and while I like it merely makes some of the naming for ValueSome/ValueNone shorter in a few places.

**Comment by Tarmil** [comment]
> Do we need an intermediate FSharp.Core that reduces this exposure of implementation details?

I don't think so. Changing the compiler so it emits `FSharpOption.None` instead of `null` when creating or pattern-matching an option might actually be enough.

**Comment by Rickasaurus** [comment]
I'd really appreciate some mitigation option for this, even a compiler flag we can manually set to buy us time. We have a huge amount of reflection machinery over F# types and I expect this will break multiple aspects of our product.

**Comment by NinoFloris** [comment]
@Rickasaurus it's just a suggestion up to this point, I don't think anything drastic like this is going to be accepted ;)

**Comment by ItPutsTheLotionInTheBasket** [comment]
I would also want to know what the performance differences are, particularly with respect to tight loops.

**Comment by dsyme** [comment]
This would be a breaking change, per the conversation above. 

I understand the desire to make the change and the frustration with UseNullAsTrueValue.  However if we did a breaking change in this area it would I think be to make Some/None be ValueOption.
