### ISSUE TITLE
Support attributes on anonymous record fields

### ISSUE THREAD

**Issue by Arshia001** [fsharp/fslang-suggestions#886]
I propose we support adding attributes to anonymous record fields:

``` fsharp
member me.Login(request: {| [<Required>] emailAddress: string; [<Required>] password: string |}) = ...
```

The above piece of code doesn't compile.

(The existing way of approaching this problem in F# is ...) To the best of my knowledge there is no way to work around this. Instead, a full record type must be used:

``` fsharp
type LoginRequest = {
    [<Required>] emailAddress: string
    [<Required>] password: string
}

member me.Login(request: LoginRequest) = ...
```

## Pros and Cons 

The advantage of making this adjustment to F# is that anonymous records can be used in more places than they can be today, for example as input to ASP.Net Core controller actions or (de)serializers. I believe this is exactly why anonymous records were added to the language in the first place: as a way to avoid giving a name and separate declaration to a type that's only used once. This may be the case when deserializing a JSON data structure returned by a remote service that's only invoked in once place. Inputs to ASP.Net Core controllers are also likely to be unique.

(The disadvantages of making this adjustment to F# are ...) I can't think of any.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: fsharp/fslang-suggestions#712

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by jwosty** [comment]
I like the concept, especially if it allows more interop usages of anonymous record. How should these attributes factor into type checking? If the caller doesn't specify any attributes, but the callee does, should this compile?

**Comment by ronaldschlenker** [comment]
I too had that issue and ended up writing an explicit type (which I usually do anyway in most cases)...When you have 2 or more places where instances of the same nominal anonymous type are created, how do you deal with different attributes? Will they be merged, will they have to be redundant in each place, should there only be one single place that can have attributes? 

My use case was a datatype that should be displayed in a table, so I needed column annotations. It was in a data exploration project using f# interactive. For those cases, the feature might be useful.

**Comment by ronaldschlenker** [comment]
I too had that issue and ended up writing an explicit type (which I usually do anyway in most cases)...When you have 2 or more places where instances of the same nominal anonymous type are created, how do you deal with different attributes? Will they be merged, will they have to be redundant in each place, should there only be one single place that can have attributes? 

My use case was a datatype that should be displayed in a table, so I needed column annotations. It was in a data exploration project using f# interactive. For those cases, the feature might be useful.

**Comment by Arshia001** [comment]
@ronaldschlenker 

> When you have 2 or more places where instances of the same nominal anonymous type are created ...

To the best of my knowledge, F# already creates many different types for the same set of (similarly named and similarly typed) properties. It depends where you create them and whether the compiler can infer them to need to be the same type, among other things.

For example, if I have this code in assembly `A`:

``` fsharp
let func (x: {| foo: int |}) = ...
```

and this code in assembly `B`:

``` fsharp
let val = {| foo = 1 |}
```

`val` will be of the type declared inside assembly `A` only if it's later fed into `func`.

I think new types will have to be created for each set of different attributes. This will lead to situations where you can't feed a similar anonymous record somewhere else:

``` fsharp
let f1 (x: {| [<Attr>] foo: int |}) = ...

let f2 (x: {| foo: int |} = f1 x // Uh-oh!
```

While I believe writing such code is not good practice (if a type is used many times, it should probably have a name), it may cause headaches to the unsuspecting programmer. To improve the situation, similar anonymous records could probably be coerced to the type with the most specific attributes as long as the attributes on other records are a subset of the attributes on the most-specific one:

``` fsharp
let f1 (x: {| [<Attr1, Attr2>] foo: int |}) = ...
let f2 (x: {| [<Attr1>] foo: int |}) = f1 x // OK
let f3 (x: {| foo: int |}) = f1 x // Also OK
let f4 (x: {| [<AnotherAttr>] foo: int |}) = f1 x // Not OK
```

-----------

@jwosty 

> If the caller doesn't specify any attributes, but the callee does, should this compile?

I hadn't really considered placing attributes inside literals, I was only considering attributes in type definitions (e.g. `{| x = 1 |}` vs `{| x: int |}`, in case I got the names "literal" and "type definition" wrong). However, attributes inside literals may also have their (narrower) use cases.

One example that comes to mind is `Newtonsoft.Json`'s [DeserializeAnonymousType](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_DeserializeAnonymousType__1.htm) method, which takes as input an instance of an anonymous and uses its type to deserialize its input. However, I also believe that method exists solely because C# has no way to write an anonymous type's definition, only the literals, so my only example of why attributes inside literals could be useful *may* be invalid.

Whether or not a literal and definition match can probably be subject to the same rules I mentioned above, so `{| foo = 1 |}` would be compatible with `{| [<Attr>] foo: int |}`, and attributes on the caller side would not be mandatory.

**Comment by dsyme** [comment]
My feeling is that if this is required then an explicit record type should be used.  The verbosity of the inline attributes is just too much - switching makes sense at this point.
