### ISSUE TITLE
Compiler directive for environment variables

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#89]
**Submitted by Lenne on 4/6/2016 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

It would be nice to have a compiler directive for environment variables which can be used in string literals.
This way we can pass different parameters to type providers on a build server.
```fsharp
[<Literal>]
let ConnectionString = #env "MY_DB_CONNECTIONSTRING"
let cmd = new SqlCommandProvider<"...", ConnectionString>()
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13335678)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13335678-compiler-directive-for-environment-variables.md#comments)

**Comment by dsyme** [comment]
This can be implemented as part of a type provider, with full static checking.  Specifically I suggest adding this feature to the FSharp.Configuration type provider. https://fsprojects.github.io/FSharp.Configuration/
