### ISSUE TITLE
Allow implicit conversions for F# intrinsic buffers to span for members and constructors

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-suggestions#896]
I propose we allow implicit conversions for common buffer types:

* Strings
* Arrays
* Something else intrinsic to FSharp.Core that makes sense?

Into spans for method calls. This would be similar to our implicit conversions for Nullable Value Types in https://github.com/fsharp/fslang-suggestions/issues/774.

Consider the following function (found in the F# compiler):

```fsharp
let isOperator (name: string) =
    name.StartsWithOrdinal("( ") && name.EndsWithOrdinal(" )") && name.Length > 4
        && name.Substring (2, name.Length - 4) 
           |> String.forall (fun c -> c <> ' ' && not (Char.IsLetter c))
```

In the F# compiler, this function (and many others like it) are on various hot paths in tooling. For example, when generating a completion list we check every item in the list. In another place in tooling, we "fix up" a span of text (represented as a string) for every span of text in a document when we colorize it.

Depending on what you measure, F# tooling generates an enormous amount of duplicate strings (easily 50% or more are duplicates when measuring a VS session with a tool like [String Theory](https://github.com/drewnoakes/string-theory)). These kinds of functions contribute to that, and finding ways to remove the string generation in favor of working on spans can improve performance and reduce allocations.

To "spannify" this function with this suggestion in place, the code could look like this:

```fsharp
let isOperator (name: string) =
    let name = name.AsSpan()
    name.StartsWithOrdinal("( ") && name.EndsWithOrdinal(" )") && name.Length > 4
        && ReadOnlySpan.forall (fun c -> c <> ' ' && not (Char.IsLetter c)) (name.Slice(2, name.Length - 4))
```

This is still not as "fluent F#" as the non-span version due to https://github.com/fsharp/fslang-suggestions/issues/688, but it's pretty close.

However, we can't call `StartsWithOrdinal` and `EndsWithOrdinal` like this because in F#, a string is not implicitly convertable to a span for method calls. The code would instead need to look like this:
```fsharp
let isOperator (name: string) =
    let name = name.AsSpan()
    name.StartsWithOrdinal("( ".AsSpan()) && name.EndsWithOrdinal(" )".AsSpan()) && name.Length > 4
        && ReadOnlySpan.forall (fun c -> c <> ' ' && not (Char.IsLetter c)) (name.Slice(2, name.Length - 4))
```

There are now numerous APIs that take Span overloads in the .NET Core libraries, and other high-performance oriented libraries that similarly accept and return spans. It's quite common for the buffers one works with to either be arrays or strings when you care about performance. Lacking the ability to implicitly convert means a lot of noise an F# programmer needs to write.

Furthermore, there are many more functions that package up substrings and sub-arrays for latter processing in the F# compiler. "spannifying" those is more work, but this feature would help with those cases as well.

### F# functions would not offer this implicit conversion

Implicit conversions are simply not a thing with F# functions, and this proposal honors that. If an F# programmer has a string and needs to call an F#-defined function that takes a span, they still need to explicitly convert it.

This proposal is scoped only to methods, such as those found in the BCL.

### Aside - helpers
The `StartsWithOrdinal` and `EndsWithordinal` functions are helpers defined internal to the F# compiler. They are equivalent to the .NET methods that pass in a `StringComparison` enum. The equivalent functionality to these and `String.forall`  would also have to be available, probably via an internal compiler unless we allow for use of Spans (via System.Memory) in FSharp.Core APIs. This is how they would likely look:

```fsharp
open System
open System.Runtime.CompilerServices


module ReadOnlySpan =
    let inline forall f (sp: ReadOnlySpan<'T>) =
        let mutable res = true
        let mutable idx = 0

        while res && idx < sp.Length do
            if f sp.[idx] then
                res <- false
            idx <- idx + 1

        res
    
[<Extension>]
type SpanExtensions =
    [<Extension>]
    static member inline StartsWithOrdinalSpan(text: ReadOnlySpan<char>, sp: ReadOnlySpan<char>) =
        text.StartsWith(sp, StringComparison.Ordinal)

    [<Extension>]
    static member inline EndsWithOrdinalSpan(text: ReadOnlySpan<char>, sp: ReadOnlySpan<char>) =
        text.EndsWith(sp, StringComparison.Ordinal)

```

If https://github.com/fsharp/fslang-suggestions/issues/887 were allowed, then `forall` could could look just like the string version:

```fsharp
module ReadOnlySpan =
    let forall predicate (sp: ReadOnlySpan<'T>) =
        if sp.IsEmpty then
            true
        else
            let rec check i = (i >= sp.Length) || (predicate sp.[i] && check (i+1)) 
            check 0
```

## Pros and Cons 

The advantages of making this adjustment to F# are:

* Cleaner interop with core functionality in .NET / Working with common buffers like strings and arrays in hot paths where you need to operate on APIs exposing spans is easier
* It is simpler to "spannify" the F# compiler, which could significantly improve tooling performance if done thoroughly

The disadvantages of making this adjustment to F# are:

* Another implicit conversion enters the fold
* Lacking support for F# functions further distinguishes methods/constructors from functions, though they are already quite distinct when you consider optional, named, and now nullable value-typed parameters

## Extra information

A microbenchmark shows pretty unambiguous improvements for performance with little utility functions like this, and since many of them are called all of the time in F# tooling, "spannifying" them would improve things a lot.

<table>
<thead><tr><th>  Method</th><th>    Job</th><th>Runtime</th><th> name</th><th>Mean</th><th>Error</th><th>StdDev</th><th>Ratio</th><th>RatioSD</th><th>Gen 0</th><th>Gen 1</th><th>Gen 2</th><th>Allocated</th>
</tr>
</thead><tbody><tr><td>IsOperator</td><td>.NET 4.7.2</td><td>.NET 4.7.2</td><td>( @@ )</td><td>35.08 ns</td><td>0.676 ns</td><td>0.723 ns</td><td>1.00</td><td>0.00</td><td>0.0134</td><td>-</td><td>-</td><td>56 B</td>
</tr><tr><td>IsOperatorSpan</td><td>.NET 4.7.2</td><td>.NET 4.7.2</td><td>( @@ )</td><td>41.91 ns</td><td>0.097 ns</td><td>0.086 ns</td><td>1.19</td><td>0.03</td><td>-</td><td>-</td><td>-</td><td>-</td>
</tr><tr><td>IsOperator</td><td>.NET Core 5.0</td><td>.NET Core 5.0</td><td>( @@ )</td><td>30.84 ns</td><td>0.559 ns</td><td>0.495 ns</td><td>1.00</td><td>0.00</td><td>0.0134</td><td>-</td><td>-</td><td>56 B</td>
</tr><tr><td>IsOperatorSpan</td><td>.NET Core 5.0</td><td>.NET Core 5.0</td><td>( @@ )</td><td>13.57 ns</td><td>0.278 ns</td><td>0.260 ns</td><td>0.44</td><td>0.01</td><td>-</td><td>-</td><td>-</td><td>-</td>
</tr><tr><td>IsOperator</td><td>.NET 4.7.2</td><td>.NET 4.7.2</td><td>@@+-+@@</td><td>48.39 ns</td><td>0.947 ns</td><td>1.013 ns</td><td>1.00</td><td>0.00</td><td>0.0153</td><td>-</td><td>-</td><td>64 B</td>
</tr><tr><td>IsOperatorSpan</td><td>.NET 4.7.2</td><td>.NET 4.7.2</td><td>@@+-+@@</td><td>41.11 ns</td><td>0.377 ns</td><td>0.314 ns</td><td>0.85</td><td>0.02</td><td>-</td><td>-</td><td>-</td><td>-</td>
</tr><tr><td>IsOperator</td><td>.NET Core 5.0</td><td>.NET Core 5.0</td><td>@@+-+@@</td><td>45.77 ns</td><td>0.628 ns</td><td>0.557 ns</td><td>1.00</td><td>0.00</td><td>0.0153</td><td>-</td><td>-</td><td>64 B</td>
</tr><tr><td>IsOperatorSpan</td><td>.NET Core 5.0</td><td>.NET Core 5.0</td><td>@@+-+@@</td><td>14.09 ns</td><td>0.244 ns</td><td>0.228 ns</td><td>0.31</td><td>0.01</td><td>-</td><td>-</td><td>-</td><td>-</td>
</tr></tbody></table>

Source: https://gist.github.com/cartermp/da23761991bd1cf0f179edfe1d00b737

Estimated cost (XS, S, M, L, XL, XXL): S-M

Related suggestions:

https://github.com/fsharp/fslang-suggestions/issues/774

(These aren't related to implicit conversions, but they do make span-like programming far easier in F#)
https://github.com/fsharp/fslang-suggestions/issues/688
https://github.com/fsharp/fslang-suggestions/issues/887
https://github.com/fsharp/fslang-suggestions/issues/712

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
@cartermp The F# 6 support for `op_Implicit` seems to have covered these use cases, given that `Span` has a few `op_Implicit` on it https://docs.microsoft.com/en-us/dotnet/api/system.span-1.op_implicit?view=net-6.0

This now works:
```
open System
open System.Runtime.CompilerServices

module ReadOnlySpan =
    let inline forall f (sp: ReadOnlySpan<'T>) =
        let mutable res = true
        let mutable idx = 0

        while res && idx < sp.Length do
            if f sp[idx] then
                res <- false
            idx <- idx + 1

        res

[<Extension>]
type SpanExtensions =
    [<Extension>]
    static member inline StartsWithOrdinal(text: ReadOnlySpan<char>, sp: ReadOnlySpan<char>) =
        text.StartsWith(sp, StringComparison.Ordinal)

    [<Extension>]
    static member inline EndsWithOrdinal(text: ReadOnlySpan<char>, sp: ReadOnlySpan<char>) =
        text.EndsWith(sp, StringComparison.Ordinal)

let isOperator (name: string) =
    let name = name.AsSpan()
    name.StartsWithOrdinal("( ") && name.EndsWithOrdinal(" )") && name.Length > 4
        && ReadOnlySpan.forall (fun c -> c <> ' ' && not (Char.IsLetter c)) (name.Slice(2, name.Length - 4))
```

**Comment by cartermp** [comment]
Oh wow, fantastic! I'll probably submit a PR to use this in the compiler :)

**Comment by cartermp** [comment]
Heh, it appears you rewrote the routine in question some time ago anyways, and that rewrite does zero string duplication. Yeehaw!
