### ISSUE TITLE
Anonymous record subtyping

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#898]
# Record subtype 

Would be nice to have a simple way to define a function that receives any record with some member of the specific type.

The idea is with this my functions are more interested in the shape of the data instead of the type name.

I think with a type annotation that resembles anonymous records would be ok 

something like this:

```fsharp
let bar = {| A = "data"; B = 42 |}
let foo (x: {| _ with A: string |} ) = // note the `with`
     x.A + "!"

foo bar // this should be valid now
```

Today I think the only way to do this without having to implement an interface is with member constraints 

```fsharp
let inline foo x  = 
     let a = (^T : (member A: string) x)
     a + "!"
```
## Pros and Cons 

The advantages of making this adjustment to F# are
 - A more simple and concise way to deal with data with the same shape, 
 - The syntax of member abstractions is not clear or intuitive

The disadvantages of making this adjustment to F# are 
 - Structure typing is not a thing in F#, so it can be too much disruptive

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
 I really don't know, if someone helps me to understand how hard it could be would be nice

## Affidavit (please submit!)
Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
> Today I think the only way to do this is with member constraints

For nominal records (not anonymous records) you can do this with interfaces. A record can implement any interface.

**Comment by lucasteles** [comment]
@abelbraaksma  yes, I forgot to mention interfaces

**Comment by cartermp** [comment]
I think this suggestion as-is would be a no, as per the design goals stated for anonymous records here: https://github.com/fsharp/fslang-design/blob/master/FSharp-4.6/FS-1030-anonymous-records.md#design-principle-no-structural-subtyping

Given that you can accomplish this to a degree with SRTP, I don't think this will be accepted. In theory, if nominal records supported structural subtyping then this could work, but since structural subtyping isn't really a thing in .NET it seems unlikely to happen. if any subtyping were to be supported it would probably be via inheritance.

**Comment by atsapura** [comment]
@lucasteles you can implement structural typing with SRTP and make it easier with active patterns like so:
https://gist.github.com/atsapura/fd9d7aa26e337eaa2f7f04d6cbb58ef6

**Comment by cartermp** [comment]
@atsapura has a great example listed. Here's a smaller one that does a few less fancy things but demonstrates some of the utility across different types too:

```fsharp
module M =
    let inline private (|HasName|) x = (^a : (member Name: string) x)

    let inline printName (HasName name) = printfn $"{name}"

type Person1 = { Name: string; Age: int }
type Person2 = { Name: string; Age: int; IsFunny: bool }

type Name(name) =
    member _.Name = name

let p1 = { Name = "Phillip"; Age = 30 }
let p2 = { Name = "Phillip"; Age = 30; IsFunny = false }
let nm = Name "Phillip"

M.printName p1
M.printName p2
M.printName nm
```

That said, you can get into the weeds with SRTP when you start to try and Generalize All The Things. I would recommend using some of the utilities from FSharpPlus if you're looking to do more than just code like I or @atsapura posted.

**Comment by lucasteles** [comment]
Just thinking about this, I feel the `SRTP` syntax is a bit cumbersome and hard to remember/follow. This proposal could be turned into just a simplified way to define this kind of SRTP


```fsharp
let bar = { A = "data"; B = 42 }

```fsharp
let inline foo x  = 
     let a = (^T : (member A: string) x)
     a + "," + a
```
as the same as
```fsharp
let inline foo (x: {member A: string})  = 
     a.A + "," + x.A
```

wdyt?

**Comment by cartermp** [comment]
I wouldn't really want to look into this kind of syntactical simplification unless there were a broader desire to improve SRTP wholesale. I don't believe that this is an objective of F# vNext aside from completing some work (namely FS-1043) that's already been started.

**Comment by vzarytovskii** [comment]
> This proposal could be turned into just a simplified way to define this kind of SRTP

There's already an existing proposal for simplifying SRTP syntax: https://github.com/fsharp/fslang-suggestions/issues/440 and RFC has been merged: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1024-simplify-constrained-call-syntax.md

**Comment by dsyme** [comment]
Closing per @cartermp 's comment here: https://github.com/fsharp/fslang-suggestions/issues/898#issuecomment-671404504
