### ISSUE TITLE
Add triple-questionmark not yet implemented operator (???) from Scala

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#90]
# Add triple-questionmark not yet implemented operator (???) from Scala [13345104] #

**Submitted by Anonymous on 4/7/2016 12:00:00 AM**  
**11 votes on UserVoice prior to migration**  

In Scala, there is an operator `???`, which is used as a "Convenient as a placeholder for a missing right-hand-side of a method." This is defined as follows:
```
def ??? : Nothing = throw new NotImplementedError
```
In F# I would imagine that we'd define it something like:

```
[<GeneralizableValue>]
let ???<'a> = raise (NotImplementedException())
```

Unfortunately, ??? is not a valid name, which is why a library solution won't solve this problem. The major merit of including this in F#, is that it provides a standardized way to declare incomplete parts of the code, allowing users and tooling to detect this.

You can read the original reasoning by Martin Odersky here at http://www.scala-lang.org/old/node/11113.html

Finally, an article offering more explanation as to it's value and usage can be found here:
http://alvinalexander.com/scala/what-does-three-question-marks-in-scala-mean

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13345104)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13345104-add-triple-questionmark-not-yet-implemented-opera.md#comments)

**Comment by dsyme** [comment]
You can define this in one line in your own code.  This is the recommended form:

```
let nyi<'T> : 'T = raise (NotImplementedException())
```

**Comment by mardukbp** [comment]
In #1275 there is an improved definition by [vzarytovskii](https://github.com/vzarytovskii):

```fsharp
open System
open System.Runtime.CompilerServices

[<CompilerMessage("Not yet implemented", 10003, IsError = false)>]
[<NoDynamicInvocation; MethodImpl(MethodImplOptions.AggressiveInlining)>]
let inline ___<'a> : 'a = raise(NotImplementedException("Not yet implemented"))
```

Then you get a nice inline warning in your IDE :)
