### ISSUE TITLE
Extend Units of Measure to Include Unsigned Integers

### ISSUE THREAD

**Issue by pblasucci** [fsharp/fslang-suggestions#901]
# Extend units of measure to include unsigned integers

I propose we include unsigned integers in the family of unit-annotated primitive types. Specifically, the target types are: 8-bit, 16-bit, 32-bit, and 64-bit intergers (as provided by the BCL).

The existing way of approaching this problem in F# is to use signed integers -- or simply do without unit tags. 

## Pros and Cons 

The advantages of making this adjustment to F# are safer numerical coding, more expressive domain modeling, and less surprises for newcomers.

The disadvantages of making this adjustment to F# are someone has to do the work.

## Extra information

Open questions:

- As there is some overlap with multiple type aliases, a decision needs to be taken on which aliases to extend (e.g. `byte` and/or `uint8`).

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: 

https://github.com/fsharp/fslang-suggestions/issues/563

(n.b. this suggestion is much simpler and of smaller scope than the above-linked)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment]
This is related, though covers a different subject where people feel pain when dealing with trivial tasks involving UoM: https://github.com/fsharp/fslang-suggestions/issues/892. 

@cartermp, I think allowing UoM on all primitive types (it's trivial to make that change, as these cannot be generic in any other way, which stands in the way of parts of #563) should be considered in tandem with #892. 

I'd even argue that together they make a small enough, and rewarding, nice new feature to still be eligible for F# 5.0, provided we get it ready and stable in time. I'm willing to help implement both.

**Comment by kerams** [comment]
I'd just prefer to have all types supported, rather than it being hard-coded for a tiny set.

Also linking to [UMX](https://github.com/fsprojects/FSharp.UMX) for good measure.

**Comment by abelbraaksma** [comment]
@kerams, UoM is like generic, an existing generic type cannot be also generic for UoM. Baking that into the language as a universal means, while maintaining compatibility, is not simple, to say the least, see also the referring thread.

Expanding to existing sealed non generic types, specifically value types, is much simpler to do.

**Comment by pblasucci** [comment]
I'm generally in favor of the goals expressed in #892. But I view the work as largely separate from this issue (if for no other reason, it keeps the efforts small and focused... which hopefully means a faster path to success). In fact, I'd expect several different, small RFCs to come out of #892. And while I'm not strictly opposed to #563, I think there's still a lot of unanswered questions and possible directions there.

**Comment by abelbraaksma** [comment]
@pblasucci, I agree, a few smaller RFCs would be a good idea.

**Comment by pblasucci** [comment]
Current status of the implementation PR:

+ unsigned integers now support units of measure
+ where a primitive numeric type (signed, unsigned, or real) has multiple abbreviations: 
    + each abbreviation now supports units of measure
    + abbreviations for the same type can be used interchangeably
    + _inferred_ measurable types will, in some instances, "default" to a single well-know type (e.g. an expression which mixes `int<_>` with `int32<_>` will infer a type if `int<_>`); this is consistent with normal use of abbreviations and is "fixable" with an explicit type signature

Things I'd still like to do:

1. Add support for native integers
2. Add more/better test coverage
3. Explore the possibility of being able to put units on "CLR" types (e.g. `SByte<m>`) ... but I consider this very low-priority and not critical to anything.

**Comment by pblasucci** [comment]
Annnnd everything is borked in CI  :frowning:  _sigh_ ... weirdly, I don't see these errors locally. Guess I need to do some more digging.

**Comment by pblasucci** [comment]
Should this be closed, given that the RFC is in Preview?
