### ISSUE TITLE
Implement implicit casts for yield

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#91]
# Implement implicit casts for yield [13361034]

**Submitted by Francois Brodeur on 4/8/2016 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

As described here: https://github.com/fsharp/fsharp/issues/545#event-620769998

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13361034)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13361034-implement-implicit-casts-for-yield.md#comments)

**Comment by Happypig375** [comment]
Hasn't this been implemented? This is omitting `upcast` in `yield`s.

**Comment by dsyme** [comment]
Yes, it has been done

**Comment by cartermp** [comment]
@dsyme is there a corresponding RFC?

**Comment by dsyme** [comment]
https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1055-subsumption-for-yield-in-sequence-expression.md is it, correct?

**Comment by cartermp** [comment]
Aha, yes.
