### ISSUE TITLE
Pattern Matching in function declaration.

### ISSUE THREAD

**Issue by Seng-Jik** [fsharp/fslang-suggestions#913]
# Pattern Matching in function declaration

We may need this syntax for pattern matching on the parameter list

```fsharp

let f (Some 1: int option) (Ok x: Result<int,_>) : int = 1 + x
and f (Some x) (Ok y) = x + y
and f _ _ = failwith ""

```

## Pros and Cons 

The advantages of making this adjustment to F# are:
   * It can provide more powerful pattern matching ability.

The disadvantages of making this adjustment to F# are:
   * May conflict with the keyword "and" in current version?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by pblasucci** [comment]
I'm willing to be wrong here, but... I feel fairly certain this falls under

> something which has obviously "already been decided" in previous versions of F#

**Comment by Seng-Jik** [comment]
> I'm willing to be wrong here, but... I feel fairly certain this falls under
> 
> > something which has obviously "already been decided" in previous versions of F#

I searched issues, but didn't find anything about "pattern matching on functions"? I only found a similar "pattern matching on member declaration". This issue has been rejected. I don't know whether it is a duplicate of this issue.

**Comment by pblasucci** [comment]
Fair enough. Some of the aspects of the language that are _very foundational_ (i.e. have been present since the earliest MSR days) don't have explicit issues around them (because they're so entrenched). But I'm sure Don or Phillip or someone will weigh in on this sooner or later.

**Comment by cartermp** [comment]
I'd like @dsyme to confirm but I think the answer here would be "probably not" since it offers a different way to do the same thing. In Haskell, this kind of pattern matching is idiomatic. But in F# and other MLs it's not, and a `match` expression inside a single function is the way to do it.

**Comment by dsyme** [comment]
This has been proposed a few times, I'm not certain there's an issue for it in fslang-suggestions.  But yes, this won't be added to F#, it was removed from the design of core ML by OCaml and we followed that.   To me it's a form of "false elegance" that means duplicating the name of the function multiple times (encouraging short cryptic function names among other things).
