### ISSUE TITLE
single command (rather than compound) to execute dotnet fsi on mac/linux

### ISSUE THREAD

**Issue by jbtule** [fsharp/fslang-suggestions#921]
# single command (rather than compound) to execute dotnet fsi on mac/linux

Even though fsi is now available on standard dotnet installs, it's not making unix scripting easier because it requires a compound call to execute.

I propose we have a additional single command to execute fsi on mac and linux, so that shebang support for fsx scripts can be restored, which makes it easy to execute scripts by ``./<scriptname>.fsx``

The existing way of approaching this problem in mono was
`#!/usr/bin/env fsharpi`

The way to make this work on **Mac** with `dotnet fsi` is `#!/usr/bin/env dotnet fsi`, 

However this will **not** work on **Linux**, you'll receive an error:
```bash
/usr/bin/env: ‘dotnet fsi’: No such file or directory
```
To make this work on **mac and linux** you *can* do this:
```
#!/bin/sh
#if run_with_bin_sh
    exec dotnet fsi $0 $*
#endif
```
However, it won't work in (admittedly less common) shells like [fish](https://github.com/fish-shell/fish-shell)

While using the path directly to dotnet will technically work, it's not a portable solution. since dotnet is installed in different locations on different unix platforms by default even (Mac:` /usr/local/share/dotnet/dotnet`. Ubuntu: `/usr/share/dotnet/dotnet` -- `env` for path resolution is necessary.

## Pros and Cons 

The advantages of making this adjustment to F# are make fsharp scripts nice and expected on unix.

The disadvantage of making this adjustment to F# is having to add something else to the unix path in deployment.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  XS

Related suggestions: 
[Shebang support for upcoming F# interactive and future interpreters](https://github.com/dotnet/fsharp/issues/4917)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
On a recent enough Linux you can use `-S` to make `env` itself do the splitting:

```shell
#!/usr/bin/env -S dotnet fsi

printfn "Hello, world!"
```

I don't know if MacOS's `env` supports this though.

**Comment by jbtule** [comment]
@Tarmil how recent? It works on my mac...but not my ubuntu (admittedly it's not very recent 16.04 EOL 2021). If the most recent LTS ubuntu that works on WSL supports it, I'll close this issue.

**Comment by jbtule** [comment]
Since 
```bash
#!/usr/bin/env -S dotnet fsi
```
should work in recent linux distros with coreutils 8.30 <=, and BSD variants like mac os x for over a decade. Closing this suggestion.

**Comment by alexei-matveev** [comment]
This would work, but seems to require .fsx extensions:

$ cat a2.fsx 
#!/usr/bin/dotnet fsi

printfn "Hello, world!"

**Comment by jbtule** [comment]
@alexei-matveev the downside is that isn't portable. Without env it wouldn't work for different standard (not to mention custom) locations on different platforms. But new Linux versions supporting `env -S` fixed the issue providing compatibility with BSD and Mac.

**Comment by cnmade** [comment]
It works perfect on Linux, but how to let it works on windows. I need the same way to run easily on windows. like Double click the file `hello.fsx` to run FSharp script.
