### ISSUE TITLE
Indexed enumeration in for loops

### ISSUE THREAD

**Issue by pkese** [fsharp/fslang-suggestions#923]
# Indexed sequence enumeration in for loops

*Aka: add python like `enumerate` functionality to provide indexed for-loop enumeration*

It's common to at for-loop index inside the for loop body.  
Since this is not standardized, people are coming up with ad hoc workarounds that may be error prone:

```fsharp
let mutable i = 0
for x in ['a'..'z'] do
    printfn "%d: %c" i x
    i <- i+1
```

To circumvent such patterns, Python has a function `enumerate` (in F# world, closest semantic match would be `iteri`) that takes a sequence and renders pairs of `(index,item)`, which reduces the above code to:

```fsharp
for i,x in enumerate(['a'..'z']) do
    printfn "%d: %c" i x
```
I'd suggest to add a similar function to F# as well,  
either in form of a global `enumerate` function, or as `Seq.enumerate`

A possible solution could be:  
```fsharp
let inline enumerate xs = xs |> Seq.mapi (fun i x -> i,x)
```  
... but I believe we could make this more lightweight without extra allocations and sequence conversions.

Of course the name `enumerate` could be changed to anything else (e.g. `iteri`). I referred to it as `enumerate` due to familiarity with Python.

## Pros and Cons 

The advantage of making this adjustment to F# are:
- to have a common, safe and efficient pattern of how to index-iterate through items in for loops
- people with Python background are already familiar with this pattern.

The disadvantages of making this adjustment to F# are:
- possible global namespace pollution (if we decide to introduce it as a global identifier)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by kerams** [comment]
There's already this, though it will of course create a new collection.

```fsharp
for i,x in List.indexed ['a'..'z'] do
    printfn "%d: %c" i x
```

**Comment by cartermp** [comment]
Yeah, this exists already in the form of the `indexed` functions on list, sequence, and array.

Note that there are also the `iteri` functions on all 3 for when you want to iterate with an index at the end of a pipeline.
