### ISSUE TITLE
Write flexible types in types

### ISSUE THREAD

**Issue by Swoorup** [fsharp/fslang-suggestions#925]
# Allow flexible type syntax in Type declarations

I propose we allow writing flexible types in types. This does not mean that that flexible types syntax can be used in constraint in types. 

For example: 

```fsharp 
type IEvent = interface end

type ProjectionOffer<'TState, #IEvent> =
  | FromEvents of EventEnvelope<#IEvent> list
  | FromSnapshot of 'TState

type LoadProjectionOffer<'TState, #IEvent> = ProjectionId -> ProjectionOffer<'TState, #IEvent>
```

The existing way of approaching this problem in F# is ...

```fsharp
type ProjectionOffer<'TState, 'TEvent when 'TEvent :> IEvent> =
  | FromEvents of EventEnvelope<'TEvent> list
  | FromSnapshot of 'TState

type LoadProjectionOffer<'TState, 'TEvent when 'TEvent :> IEvent> = ProjectionId -> ProjectionOffer<'TState, 'TEvent>
```

## Pros and Cons 

The advantages of making this adjustment to F# are able 
* Consistency with methods using flexible types. 
* Syntactic sugar, less typing.
* Discoverability of flexible type syntax 

The disadvantages of making this adjustment to F# are
* Multiple ways to achieve the same thing

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S-M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
In the proposal we can't know that each `#IEvent` refers to the same type variable.  So I don't think this really adds up as a proposal, e.g. when multiple `#` are used

**Comment by Swoorup** [comment]
I started this due to lack of Anonymous type-tagged unions, which now accepted will likely void the need for this.

```fsharp
type ProjectionOffer<'TState, 'TEvent> =
  | FromEvents of EventEnvelope<'TEvent> list
  | FromSnapshot of 'TState

type LoadProjectionOffer<'TState, 'TEvent> = ProjectionId -> ProjectionOffer<'TState, 'TEvent>

type Event = JoinEvent | LeaveEvent | MessageEvent
type JoinLeaveEvent = JoinEvent | LeaveEvent
type JoinLeaveProjection<'TState> = ProjectionOffer<'TState, JoinLeaveEvent>
```
