### ISSUE TITLE
Just keep Aggregation operations In Seq module, and remove Aggregation operations in other collection modules

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#928]
# Title of Suggestion

I propose we ... (describe your suggestion here)

there is aggregation operations in any collection types. they is compatible with `#seq<'a> -> 'b` . so maybe we should Just keep Aggregation operations In `Seq` module, and remove Aggregation operations in other collection types.

The existing way of approaching this problem in F# is ...

there is aggregation operations in any collection types.

## Pros and Cons 

The advantages of making this adjustment to F# are ...

just need only one ducument in Seq Module. there is no need to document aggregation operations in Array, List modules.

The disadvantages of making this adjustment to F# are ...

maybe the impelement in respective collection module is different, the performance will to be poor a little.

## Extra information

Estimated cost (**XS**, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

aggregation operations include:

```F#
Seq.
average   : source:seq<(^T)> -> ^T 
averageBy   : projection:('T -> ^U) -> source:seq<'T>  -> ^U 
compareWith: comparer:('T -> 'T -> int) -> source1:seq<'T> -> source2:seq<'T> -> int
contains: value:'T -> source:seq<'T> -> bool
exists: predicate:('T -> bool) -> source:seq<'T> -> bool
exists2: predicate:('T1 -> 'T2 -> bool) -> source1:seq<'T1> -> source2:seq<'T2> -> bool
find: predicate:('T -> bool) -> source:seq<'T> -> 'T
findBack: predicate:('T -> bool) -> source:seq<'T> -> 'T
findIndex: predicate:('T -> bool) -> source:seq<'T> -> int
findIndexBack: predicate:('T -> bool) -> source:seq<'T> -> int
fold<'T,'State> : folder:('State -> 'T -> 'State) -> state:'State -> source:seq<'T> -> 'State
fold2<'T1,'T2,'State> : folder:('State -> 'T1 -> 'T2 -> 'State) -> state:'State -> source1:seq<'T1> -> source2:seq<'T2> -> 'State
foldBack<'T,'State> : folder:('T -> 'State -> 'State) -> source:seq<'T> -> state:'State -> 'State
foldBack2<'T1,'T2,'State> : folder:('T1 -> 'T2 -> 'State -> 'State) -> source1:seq<'T1> -> source2:seq<'T2> -> state:'State -> 'State
forall: predicate:('T -> bool) -> source:seq<'T> -> bool
forall2: predicate:('T1 -> 'T2 -> bool) -> source1:seq<'T1> -> source2:seq<'T2> -> bool
head: source:seq<'T> -> 'T
tryHead: source:seq<'T> -> 'T option
last: source:seq<'T> -> 'T
tryLast: source:seq<'T> -> 'T option
exactlyOne: source:seq<'T> -> 'T
tryExactlyOne: source:seq<'T> -> 'T option
isEmpty: source:seq<'T> -> bool
item: index:int -> source:seq<'T> -> 'T
iter: action:('T -> unit) -> source:seq<'T> -> unit
iteri: action:(int -> 'T -> unit) -> source:seq<'T> -> unit
iter2: action:('T1 -> 'T2 -> unit) -> source1:seq<'T1> -> source2:seq<'T2> -> unit
iteri2: action:(int -> 'T1 -> 'T2 -> unit) -> source1:seq<'T1> -> source2:seq<'T2> -> unit
length: source:seq<'T> -> int
max     : source:seq<'T> -> 'T
maxBy  : projection:('T -> 'U) -> source:seq<'T> -> 'T
min     : source:seq<'T> -> 'T
minBy  : projection:('T -> 'U) -> source:seq<'T> -> 'T
nth: index:int -> source:seq<'T> -> 'T
pick: chooser:('T -> 'U option) -> source:seq<'T> -> 'U 
reduce: reduction:('T -> 'T -> 'T) -> source:seq<'T> -> 'T
reduceBack: reduction:('T -> 'T -> 'T) -> source:seq<'T> -> 'T
sum   : source:seq<(^T)> -> ^T 
sumBy   : projection:('T -> ^U) -> source:seq<'T>  -> ^U 
tryFind: predicate:('T -> bool) -> source:seq<'T> -> 'T option
tryFindBack: predicate:('T -> bool) -> source:seq<'T> -> 'T option
tryFindIndex : predicate:('T -> bool) -> source:seq<'T> -> int option
tryItem: index:int -> source:seq<'T> -> 'T option
tryFindIndexBack : predicate:('T -> bool) -> source:seq<'T> -> int option
tryPick: chooser:('T -> 'U option) -> source:seq<'T> -> 'U option

```
## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
> just Obsolete operators in other collection modules.

* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
No. These are useful for type inference.

**Comment by abelbraaksma** [comment]
I don't understand the suggestion. Do you mean you want all collections to be treated as sequences? Because the three main collections (array, list, seq) are fundamentally different and treating each collection like lazy eval collections would be a fierce performance degradation.

Still, you already have that ability: you can, if you want, use seq for everything. 

If you mean instead to create overloads, that's not possible in modules.

Besides, it would be very confusing to do `Seq.head` etc when you have a list. And I don't see how such radical change can be applied without causing severe backward compatibility issues.

**Comment by Happypig375** [comment]
@abelbraaksma The suggestion is to deprecate
```fs
average   : source:seq<(^T)> -> ^T 
averageBy   : projection:('T -> ^U) -> source:seq<'T>  -> ^U 
compareWith: comparer:('T -> 'T -> int) -> source1:seq<'T> -> source2:seq<'T> -> int
contains: value:'T -> source:seq<'T> -> bool
exists: predicate:('T -> bool) -> source:seq<'T> -> bool
exists2: predicate:('T1 -> 'T2 -> bool) -> source1:seq<'T1> -> source2:seq<'T2> -> bool
find: predicate:('T -> bool) -> source:seq<'T> -> 'T
findBack: predicate:('T -> bool) -> source:seq<'T> -> 'T
findIndex: predicate:('T -> bool) -> source:seq<'T> -> int
findIndexBack: predicate:('T -> bool) -> source:seq<'T> -> int
fold<'T,'State> : folder:('State -> 'T -> 'State) -> state:'State -> source:seq<'T> -> 'State
fold2<'T1,'T2,'State> : folder:('State -> 'T1 -> 'T2 -> 'State) -> state:'State -> source1:seq<'T1> -> source2:seq<'T2> -> 'State
foldBack<'T,'State> : folder:('T -> 'State -> 'State) -> source:seq<'T> -> state:'State -> 'State
foldBack2<'T1,'T2,'State> : folder:('T1 -> 'T2 -> 'State -> 'State) -> source1:seq<'T1> -> source2:seq<'T2> -> state:'State -> 'State
forall: predicate:('T -> bool) -> source:seq<'T> -> bool
forall2: predicate:('T1 -> 'T2 -> bool) -> source1:seq<'T1> -> source2:seq<'T2> -> bool
head: source:seq<'T> -> 'T
tryHead: source:seq<'T> -> 'T option
last: source:seq<'T> -> 'T
tryLast: source:seq<'T> -> 'T option
exactlyOne: source:seq<'T> -> 'T
tryExactlyOne: source:seq<'T> -> 'T option
isEmpty: source:seq<'T> -> bool
item: index:int -> source:seq<'T> -> 'T
iter: action:('T -> unit) -> source:seq<'T> -> unit
iteri: action:(int -> 'T -> unit) -> source:seq<'T> -> unit
iter2: action:('T1 -> 'T2 -> unit) -> source1:seq<'T1> -> source2:seq<'T2> -> unit
iteri2: action:(int -> 'T1 -> 'T2 -> unit) -> source1:seq<'T1> -> source2:seq<'T2> -> unit
length: source:seq<'T> -> int
max     : source:seq<'T> -> 'T
maxBy  : projection:('T -> 'U) -> source:seq<'T> -> 'T
min     : source:seq<'T> -> 'T
minBy  : projection:('T -> 'U) -> source:seq<'T> -> 'T
nth: index:int -> source:seq<'T> -> 'T
pick: chooser:('T -> 'U option) -> source:seq<'T> -> 'U 
reduce: reduction:('T -> 'T -> 'T) -> source:seq<'T> -> 'T
reduceBack: reduction:('T -> 'T -> 'T) -> source:seq<'T> -> 'T
sum   : source:seq<(^T)> -> ^T 
sumBy   : projection:('T -> ^U) -> source:seq<'T>  -> ^U 
tryFind: predicate:('T -> bool) -> source:seq<'T> -> 'T option
tryFindBack: predicate:('T -> bool) -> source:seq<'T> -> 'T option
tryFindIndex : predicate:('T -> bool) -> source:seq<'T> -> int option
tryItem: index:int -> source:seq<'T> -> 'T option
tryFindIndexBack : predicate:('T -> bool) -> source:seq<'T> -> int option
tryPick: chooser:('T -> 'U option) -> source:seq<'T> -> 'U option
```
in the `List` and `Seq` modules because
> just need only one ducument in Seq Module. there is no need to document aggregation operations in Array, List modules.

**Comment by cartermp** [comment]
Thanks for the suggestion, but this won't be done. A massively breaking change like this is not the sort of thing we'd ever accept.

**Comment by Happypig375** [comment]
@xp44mm This suggestion will never be implemented. Removing [entire features](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.0/ListSeqArrayAdditions.md) just because of "no need to document" is simply not how language development works.

**Comment by abelbraaksma** [comment]
@Happypig375, thanks for the pointers, I didn't realize this was only to simplify documentation, which could be simplified, if need be, in a different way, for instance by allowing doc comments to include snippets from elsewhere (though I doubt it's worth the effort).

**Comment by xp44mm** [comment]
It's because those Aggregation features is too similar, for eliminates duplication, and maintains integrity. just like database, it's should keep data in fewer tables, no many lots of views.

**Comment by xp44mm** [comment]
@Happypig375 
> No. These are useful for type inference.

the type inference of Aggregation operators is not very useful. for example:

```F#
["xxx";"yyy"]
|> String.concat ","
```

this feature is a aggregation. the average, sum, maybe move to:
```F#
[1;2;3]
|> Int32.sum
```

and the Seq, Array, List super big.

**Comment by Happypig375** [comment]
> and the Seq, Array, List super big.

You're just moving functions around to break existing usages.

**Comment by xp44mm** [comment]
@Happypig375 

moving and merging replicated features. it will make more sense.

**Comment by Happypig375** [comment]
Having these "aggregation functions" ensure that when you're working with arrays, lists, or seqs, you can find all the functions you will need in their corresponding modules.
> the average, sum, maybe move to: `Int32.sum`

You're introducing even more duplication across new modules of `Int32`, `Int16`, `Int8`, `Int64`... And you cannot replace generic functions with specialized functions as existing functions work with any type with `(+)` defined.

**Comment by xp44mm** [comment]
The example I'm citing is not appropriate and leads to another problem, mainly that it's a solution for replicated features, preferably only in the Seq module or in a similar `Aggregation` module.

**Comment by Happypig375** [comment]
It's not about duplication, it's about user experience - The `List` module contains every function you will need when interacting with lists, and the `Array` module contains every function you will need when interacting with arrays. It makes the most sense.

**Comment by xp44mm** [comment]
@Happypig375 

After the collection is aggregated, the collection is independent of the specific type of the collection.

**Comment by Happypig375** [comment]
Aggregation operations are part of what you can do with arrays, lists, and sequences.

**Comment by xp44mm** [comment]
The key is that the aggregation operation is the end of the data chain, not the middle part. The end point is significantly different from the middle part, and the end point does not need to distinguish between the specific types of the collection. The current api forces the user to give input type parameters that the function does not need.

**Comment by abelbraaksma** [comment]
You're free to just use the aggregates if `Seq` for every collection type. This is already possible.

But doing this forced, ie by deprecating or removing functions from List, Array, Set, Map would mean that we'd lose performance. For instance, `Array.sum` can be 10x faster than `Seq.sum` on the same data. 

But as said before, changing the public surface area (the functions) is breaking each and every code out there. Plus the utter surprise that when working with lists, the function you need is suddenly not in `List` anymore. Discoverabilty would degrade and code becomes less readable. 

What you should instead focus on is support for higher kinded types, so that we can create a single `sum` function that has specific implementations for each type. Such a suggestion is already out there.

**Comment by xp44mm** [comment]
@abelbraaksma 

We can use reflection to improve performance.

```F#
let sum (sq:#seq<'a>) =
   if sq.GetType() = typeof<Array> then
         Array.sum (convertArray sq)
   elif ... then
         ...
    else
        Seq.sum sq
```

**Comment by abelbraaksma** [comment]
> We can use reflection to improve performance.

Reflection decreases performance and prevents certain jit optimizations. And your suggestion, while implemented differently, is already used in quite a few seq cases. But that still makes them slower (and the more types you support, the slower it gets), and certainly doesn't improve discovery.

`String.concat` is for strings, not for generic collections, and is nothing more than a helper to the same named library function. It doesn't really fit in this discussion.

I'll check for that other suggestion on higher kinded types.

**Comment by abelbraaksma** [comment]
Searching for _[higher kinded types](https://github.com/fsharp/fslang-suggestions/search?q=higher+kinded+types&type=issues)_ shows several discussions, I guess the most relevant ones are https://github.com/fsharp/fslang-suggestions/issues/175 and https://github.com/fsharp/fslang-suggestions/issues/179.
