### ISSUE TITLE
Make the inline get_Zero hack official

### ISSUE THREAD

**Issue by njlr** [fsharp/fslang-suggestions#929]
# Make the inline get_Zero hack official

Various parts of F# (e.g. `Seq.sum`) are built on types that implement `get_Zero` as a static member. I _think_ this is supposed to be implemented as a C# style property with a getter:

```fsharp
type Foo =
  {
    X : int
  }
  with
    static member Zero
      with get () = { X = 0 }

let f : Foo = LanguagePrimitives.GenericZero 
```

However, we cannot do this for the generic inline case:

```fsharp
type Foo<'t> = 
  {
    X : 't
  }
  with
    static member inline Zero
      with get () = { X = LanguagePrimitives.GenericZero } // Assumes Foo<int>
      
module M = 

  let p : Foo<int> = LanguagePrimitives.GenericZero
  
  let q : Foo<float32> = LanguagePrimitives.GenericZero
```

Compiler error:

```
    error FS0001: Type mismatch. Expecting a
        'Foo<float32>'    
    but given a
        'Foo<int>'    
    The type 'float32' does not match the type 'int'
```

The existing way of approaching this problem in F# is to leverage the fact that the compiler generates a method for getter properties and match that name:

```fsharp
type Foo<'t> = 
  {
    X : 't
  }
  with      
    static member inline get_Zero () = 
      { 
        X = LanguagePrimitives.GenericZero 
      }

module M = 

  let p : Foo<int> = LanguagePrimitives.GenericZero
  
  let q : Foo<float32> = LanguagePrimitives.GenericZero

```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgExAGoAfAFwE8AHGAAgDEIIAeAcnID46BeOgWABQdOgG8hIkQA06IOhwl0AvooDuAS3IALSZMUjc5AIbl1YOgFsYF4DCh11AOwxP6AcxjkA+gC07EOgAKAEpeAWFdMXDIyRk+ABkjRzcAVyMPAAUodQtNdQA3GFwAOgBxGEc7Mz8oAP1JFQiReuamvUELCAIUjHoAWTChRV7yOmpZRmYWJy4wxOS0zOzc00KS8srssBqIRWHPOgBHCaZWbAwIEwBmACZuBKTU9JgsnLy1soqq7f8hwSA==

I propose we enable `inline` on the `get` member of properties. 

## Pros and Cons 

The advantages of making this adjustment to F# are ...

 * We shouldn't be abusing a compiler detail for this behaviour

The disadvantages of making this adjustment to F# are ...

 * I am unsure. Perhaps code generation would be more complex?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): ?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by En3Tho** [comment]
Do you mean this one? https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1043-extension-members-for-operators-and-srtp-constraints.md

**Comment by abelbraaksma** [comment]
I think this is just a case where automatic generalization doesn't kick in for gettor properties. It has nothing do to with `get_Zero` per se. The following example has the same issue, though this time the compiler warns you that it generalized to `int` already:

```f#
type Foo<'t> =
    {
        X : 't
    }
    static member Zero
        with inline get () = Unchecked.defaultof<Foo<_>>
      
module M = 
  let p : Foo<int> = Foo.Zero   // warning  
  let q : Foo<float32> = Foo.Zero
```

I tried some combinations, incl. specifically specifying the statically resolved type parameters, but that doesn't help here. If anything, I think this is an oversight in how the compiler treats inline gettors and settors.

**Comment by cartermp** [comment]
This feels more like a bug than a language suggestion to me, I would expect this to "just work", but @dsyme could confirm

**Comment by dsyme** [comment]
This is actually by design.  

Consider this:
```fsharp
type Foo<'t> = 
  {
    X : 't
  }
  with      
    static member inline get_Zero () = 
      { 
        X = LanguagePrimitives.GenericZero 
      }

```

The inferred type is:

```fsharp
type Foo<'t> =
  { X: 't }
  with
    static member
      get_Zero : unit -> Foo< ^a> when  ^a : (static member get_Zero : ->  ^a)
  end
```

Note the `^a` is different to the `'t`.  This allows `get_Zero` to be generalised and used with the SRTP constraint.

Generic inference variables in properties can't be generalised independently of their declaration on the enclosing type definition.  

This means generic `get_` method definitions can be more general than properties

**Comment by abelbraaksma** [comment]
@cartermp, @dsyme I think that's a perfect explanation, @njlr, I think this can now be closed?

**Comment by njlr** [comment]
Is this `static member inline get_Zero` considered the correct approach to this?

If so, happy to close.

**Comment by dsyme** [comment]
> Is this static member inline get_Zero considered the correct approach to this?

Yes it is
