### ISSUE TITLE
Add Async.CatchResult to FSharp.Core

### ISSUE THREAD

**Issue by brettrowberry** [fsharp/fslang-suggestions#930]
# Add Async.CatchResult to FSharp.Core

I propose we add `Async.CatchResult` to FSharp.Core.

The existing way of approaching this problem in F# is write async exception handling code manually

## Pros and Cons 

The advantages of making this adjustment to F# are reduced friction writing functions returning `Async<Result>`

The disadvantages of making this adjustment to F# are confusion as to why there is both an `Async.Catch` and an `Async.CatchResult`.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)
I filed this https://github.com/dotnet/fsharp/issues/10304 and I think it's supposed to be in this repo instead.
## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
Seems like a reasonable request to me, the only lame thing being that there are two options now. The design and implementation would be pretty simple I think.

**Comment by pblasucci** [comment]
Random thoughts:

Would `Async.Catch` then be deprecated?

Would a different name help with awkwardness? Possible suggestions: `Async.TryCatch`, `Async.Attempt`, `Async.Trap` (n.b. I'm not wild about any of these).

Does using ```FSharpResult`2``` here confuse things when folks are modelling failure using types other than `exn` sub-classes?

Would the implementation be sensitive to the difference between `Async<Result<_, exn>>` versus `AsyncResult<_, exn>` (when the latter is _not_ implemented as a simple alias)?

I should clarify: I'm not opposed to this suggestion. I'm just thinking through possible realizations of it.

**Comment by brettrowberry** [comment]
At first I thought `tryCatch` wasn’t a good name - now it’s my favorite.

I was planning to 
- copy and paste the existing function
- give the new function a new name
- swap Choice for Result
- add a Deprecated attribute to the existing function

@pblasucci I haven’t processed your last two paragraphs yet. 

Perhaps I should open a PR to make the proposal more concrete.

**Comment by dsyme** [comment]
I think this is too minor as an improvement, and it's easy to define CatchResult in terms of the existing Catch.  Just write the appropriate helper function'/methods.
