### ISSUE TITLE
Pattern Matching of Discriminated Unions with succinct Case-only pattern (minor cosmetic suggestion - FS0019)

### ISSUE THREAD

**Issue by snuup** [fsharp/fslang-suggestions#932]
# Restrict FS0019 and allow succinct expression of matches on discriminated unions, by naming the case only, ignoring the payload.

Currently I use F# 4.7 and write pattern matches succinctly without naming the case payload:

    type DU =
        | Cat of int
        | Dog of string

    let filterCats =
        function
        | Cat -> true // write case "Cat" only, since only the distinction between A and B matter
        | Dog -> false // only the case 

Apparently this is no longer valid, now **FS0019** is raised on the code above and cases must be written as

    let filterCats =
        function
        | Cat _ -> true // write case "Cat" only, since only the distinction between A and B matter
        | Dog _ -> false // only the case 

## Pros and Cons 

The benefit is more concise code. I prefer the succinct form.

On the other hand, the required "_" communicates that the case has a payload, so maybe the language urges clarity and the new behavior is better anyway. Then the issue should be closed.

## Affidavit

Please tick this by placing a cross in the box:
* [x ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate (searched "discriminiated union match")
* [ x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x ] This is not a breaking change to the F# language design
* [x ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
> Apparently this is no longer valid

Correct, it was a regression that was fixed recently. It was only allowable for a short period of time during the regression period.

I don't see us requiring this, since it would likely have been allowed and not treated as a regression.

**Comment by snuup** [comment]
thank you for clarifying phillip.
f# language + team is amazing.
