### ISSUE TITLE
Add `Map.maxBinding` and `Map.minBinding` functions

### ISSUE THREAD

**Issue by sangkilc** [fsharp/fslang-suggestions#933]
# Add `Map.maxBinding` and `Map.minBinding` functions

I propose we add those functions in the Map module. I know we have similar functions (`maxElement` and `minElement`) in `Set`, but not in `Map`. These functions will be extremely useful in many scenarios.

For example,  we often want to get an element from a map with the largest key. With the current version of F#, one needs to enumerate all the keys in the map in order to get the largest key (or the corresponding value).

For completeness, we may want to add `tryMaxBinding` and `tryMinBinding` too.

## Pros and Cons 

I cannot think of any cons by adding these functions.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

OCaml has similar functions, such as `min_binding`, `max_binding`, etc. See https://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.Make.html.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Frassle** [comment]
Would minKey maxKey be better given the names of other methods for F# maps?

**Comment by sangkilc** [comment]
Actually, I would prefer to have a function that returns a key-value pair because if we only have `minKey`/`maxKey`, then we should use `Map.find` to get the corresponding value.

Maybe, we can have two sets of functions for retrieving a key and a value, respectively, e.g., `minKey`/`maxKey` and `minValue`/`maxValue`?

**Comment by Frassle** [comment]
Oh that's a good point, so you want like `Map.maxBinding : Map<'k, 'v> -> ('k * 'v)`. 
Not sure there's much point in adding a min/max value function, it couldn't do any better than just enumerating all values while keys could look up quicker via the tree structure.

**Comment by sangkilc** [comment]
> Not sure there's much point in adding a min/max value function, it couldn't do any better than just enumerating all values while keys could look up quicker via the tree structure.

Actually what I meant by `minValue` was to find the corresponding value of the smallest key. Sorry for the confusion, it was a bad name. On second thought, I prefer having min/max Binding functions.

**Comment by cartermp** [comment]
Do you have a use case in mind for this feature? I'm not opposed in theory, just that  OCAML having this feature isn't particularly compelling to me.

**Comment by sangkilc** [comment]
Suppose we create a Map<Address, byte>, where Address is an int64 number representing an address in memory. So, we want to use this map for emulating a process memory.

Say, we now want to allocate a large memory chunk. The simplest way to do so is by finding the maximum address used in the memory and append the chunk right after it. In this case, our allocator needs to enumerate all the bindings in the Map in order to find the maximum allocated addr.

Well, this may not be the best example to illustrate the need, but I found that lacking this feature is inconvenient in writing some program analysis algorithms that I am working on, including [this](https://github.com/B2R2-org/B2R2).

**Comment by cartermp** [comment]
Thanks! Makes sense to me. Could you perhaps add a quick hypothetical code same in the issue just so it's quick to others what code in this use case looks like?

I think these additions would make sense. Any thoughts @dsyme?

**Comment by sangkilc** [comment]
Sure! Will this be enough?

```fsharp
(* Memory *)
let mem: Map<uint64, byte> = Map.empty

let writeByteToMem mem addr b = Map.add addr b mem

let findLastFreeChunkAddress mem =
  (* Hypothetical example usage of Map.maxBinding *)
  let maxAddr = Map.maxBinding mem |> fst
  maxAddr + 1UL

let main () =
  (* Write some random values in the memory *)
  let mem = writeByteToMem mem 0x1000UL 1uy
  let mem = writeByteToMem mem 0x2000UL 2uy
  let mem = writeByteToMem mem 0x3000UL 3uy
  let mem = writeByteToMem mem 0x4000UL 4uy
  (* Find the last free chunk address *)
  findLastFreeChunkAddress mem |> printfn "%x"
```

**Comment by charlesroddie** [comment]
What is a binding?

**Comment by sangkilc** [comment]
Binding is a key-value pair. BTW, I am not advocating the name "Binding" here. Maybe `maxKeyValue`/`minKeyValue` are better.

**Comment by cartermp** [comment]
Thanks, good example. So yes, `maxKeyValue`/`minKeyValue` would be the names I'd most prefer. Now we just need @dsyme to weigh in on this. I think it would be a good addition.

**Comment by dsyme** [comment]
Yes I'm fine with adding this

**Comment by cartermp** [comment]
@sangkilc would you be willing to submit an RFC and/or proposed implementation?

**Comment by sangkilc** [comment]
Yes I will.

**Comment by uxsoft** [comment]
Just thinking out loud, the collection types have `Seq.max` and `Seq.maxBy`. What about adding the same methods for consistency?
Then `Map.maxKeyValue` would be just `Map.maxBy fst |> fst`

**Comment by Frassle** [comment]
@uxsoft the point of the proposed methods is they use the tree structure of the map to quickly return the min or max key based on the keys comparison ordering. Map.maxBy can't do any better than Seq.maxBy and has to iterate every item in the map.

**Comment by uxsoft** [comment]
Ok, good point about the maxBy, minBy as we can just use the Seq variant. 

What about Map.max and Map.min as an alternative name for Map.maxKeyValue?

Personally, I like it more because it's consistent with the Seq etc. options, shorter and in my opinion clearer. MaxKeyValue is implying that we're somehow comparing the whole keyvalues not just the key. But that might just be me.

Anyway, I see the RFC was accepted on Jan 13 so it's probably an irrelevant thought from my side. Was this implemented already? If not I'm happy to help with the implementation.

**Comment by zanaptak** [comment]
maxBinding/maxKeyValue/max don't indicate what is being compared. I think `maxByKey` would better convey the meaning as it is similar in form to `maxBy fst`.

**Comment by dsyme** [comment]
This is implemented, see links here https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1096-map-min-max-keyvalue.md
