### ISSUE TITLE
for SRTP: could these be a stable feature? 

### ISSUE THREAD

**Issue by GratianPlume** [fsharp/fslang-suggestions#935]
I wrote a simple `Never` type:
```
    [<Struct; NoComparison; NoEquality>]
    type Never = 
        |Never
        static member inline NoneNeverId(_: Never ) = (); 
        static member inline NoneNeverId(x: int ) = x
        static member inline NoneNeverId<'t> (x: 't) = x

    let inline nnid x =
        let inline fob(_:^t) x = ((^t or ^x or ^r): (static member NoneNeverId: ^x -> ^r) x)
        fob Never x

    let inline safe (x) = 
        if true then 
            x
        else 
            Unchecked.defaultof<_> |> nnid
```
when `x` is a value of `Never`, `safe` function could pass a error to Caller.

I wrote this because some times I want to refuse a few data of type to pass in.
for example, forbidding some body write `return()` in computation expressions.
when he type `return()`, IDE tips: `FS0043`
```
    type ValueMap =
        static member inline Return(x: Never) = x     // Placeholder
        static member inline Return(_: unit) = Never // **throw it into Never**
        static member inline Return(x) = ValueSome x    // Normal
```
This is unit test:
```
    let inline squeeze< ^t, ^r> f: ^r  = f Unchecked.defaultof< ^t>

    let inline wrap x =
        let inline fob(_:^t) x = ((^t or ^x or ^r): (static member Return: ^x -> ^r) x)
        (squeeze<ValueMap, _> fob) x

    
    let inline addToSet x  = 
        x |> wrap |> safe 

    let inline foo(x: unit) = addToSet x // FS0043

```
By now, it works fine. 
I wonder that,  could these be a stable feature in the future?
All these is depanded on the core function `nnid`.
I am worry because I don’t understand how it works
Some times, by another way of writing, `static member inline NoneNeverId<'t> (x: 't) = x` is chose.

**Comment by charlesroddie** [comment]
Please give this issue a title which indicates the feature.
I would also adjust "simple" to "extremely complex" in the first line of the issue.

**Comment by abelbraaksma** [comment]
> I am worry because I don’t understand how it works

I mean, you have a piece of code, but you don't understand it? Isn't that better asked on a forum like SO? I don't see the benefit of adding something that's supposed to never happen (as your code suggests) to the compiler. 

However, it appears that your referring to a programming paradigm where you have a bunch of branches, and for completeness, you add the branch that can never happen. A case quite common with standard enums. Some proposals are underway to tackle that as an addition to completeness checking. 

Likewise there's an effort underway to allow functions to accept a specific DU case, as opposed to the containing type, and the compiler will write the necessary boilerplate. 

However, when it comes to dynamic data, it's common to have a "never" branch that simply does `failwith "impossible"` or something similar. I don't see the need of using something of the given complexity which, as you point out, is hard to understand.

**Comment by cartermp** [comment]
I believe that this is a request to offer a form of ensuring that a particular branch or construct can't be hit or created?

**Comment by greatim** [comment]
> I believe that this is a request to offer a form of ensuring that a particular branch or construct can't be hit or created?

thank you for understand.
I sure it work fine now, but ,if it just a `Undefined Behavior`, it maybe change in next or next next version.

**Comment by Swoorup** [comment]
Do you mean never types, as in something like following?

```fsharp
let a: Result<int, !> = Ok 1;;
match a with 
| Ok succ -> printfn $"{succ}"
// no need to handle Error as its never type
```

**Comment by greatim** [comment]
> Please give this issue a title which indicates the feature.
> I would also adjust "simple" to "extremely complex" in the first line of the issue.

@charlesroddie @Swoorup 
First look this:
```
    type Limit =
        | Limit

        static member Foo(x: unit option) = ()

        static member Foo(x: int option) = x

        static member Foo(x: 'T option) = x


    let inline fob(_:^t) x = ((^t or ^x or ^r): (static member Foo: ^x -> ^r) x)

    let inline sid() = fob Limit Unchecked.defaultof<_>

```
Do you understand? 
When you type ` let test(): int option = sid()`， It's OK.
And then you type `let test2(): unit option = sid()` It raise a error by compiler: `FS0043`
Please think about it, This is the cornerstone of all what next happening.

Next to do some packaging:
```
    let inline sid2 x =         
        if true then 
            x
        else            
            fob Limit Unchecked.defaultof<_>
```

When you type `let test3 (x: string option ) = sid2 x`, It's OK, it return the original `x` .
And then you type `let test4 (x: unit option ) = sid2 x` error `FS0043` is raised.

 At last,  and look these:
```
    let inline finalTest x =
        let x = sid2 x
        () // do something
```

What happen? A funtion `finalTest ` is build. It accepts all `'T option`，but no `unit option`.

This is the feature what is said on beggining, building on some implicit rules, I call it `type subtraction`.

We can use this feature without worrying about it being changed one day, after confirmation.

**Comment by gusty** [comment]
Just send a PR to the F# compiler, adding it as a test.

**Comment by greatim** [comment]
After the core of this function, and one extention has been completed
@gusty 
@abelbraaksma 
@cartermp 

```
module TypeRegulate =


    // Type for can't show up
    [<Struct; NoComparison; NoEquality>]
    type Never = 
       | Never
         static member NoneNeverId(_: Never) = (); 
         static member NoneNeverId(x: int) = x
         static member NoneNeverId<'t>(x: 't) = x

    // checked if param is `Never`, when `Never` a error should raise
    let inline nnid x = 
        let inline fob(_:^t) x = ((^t or ^x or ^r): (static member NoneNeverId: ^x -> ^r) x)
        if true then x
            else (fob Never) Unchecked.defaultof<_>


    // A Goup function for setting type range: the type should belong to `TBelong`, but not `TAgainst`
    type TypeDiffer<'TBelong, 'TAgainst> =
            
        static member Assign(x: 'TBelong) = x
        static member Assign(_: 'TAgainst) = Never 

        static member inline Id x =     
            let inline assign(_:^t) x = ((^t or ^x or ^r): (static member Assign: ^x -> ^r) x)
            (assign Unchecked.defaultof<TypeDiffer<'TBelong, 'TAgainst>>) x
```

And then I use a few examples to explain what is the its work：

```

module NeverTypeTests =
    open TypeRegulate
// Usage: I set `x` must belong to option<_>，but not `int option' or `unit option'

    let inline assertType (x) = 
          x |> TypeDiffer<_ option, int option>.Id
            |> TypeDiffer<_ , unit option>.Id
            |> nnid


(**************************************
    Test 1: `FS0043`
        option<int> is disallowed         *)

    let foo(x: int option) = assertType x 


(*************************************
    Test 2: `FS0043`
        option<unit> is disallowed         *)

    //let foo1(x: unit option) = assertType x



(**************************************
    Test 3: OK
        `option<string>` is allowed. *)

    let foo2(x: string option) = assertType x



(**************************************
    Test 4: OK
        `option<T>` is explicitly specified as generic, it is OK too, *)
    let foo3(x: 'T option) = assertType x



(**************************************
    Test 5: `FS0043`
        because it's not explicitly specified as generic *)

    let bindType(x: 'T option) = ()
    let foo4 x = 
        assertType x
        bindType x
```
So it can effectively prevent prohibited types from being sneaked in.

What do you think of it？`nnid` + `Never` work like a bottom type in srtp. 
And `TypeDiffer` can be widely used as type restrictions.

**Comment by abelbraaksma** [comment]
If I understand this proposal correctly, the suggestion here is to introduce a bottom type. Note that this has been considered and per @dsyme and @cartermp comments, won't be added https://github.com/fsharp/fslang-suggestions/issues/349.

I've made a few suggestions in that thread, as have others, to come close to the behavior of a bottom type. Perhaps the discussion here is another way of doing it. 

These are good discussions and considering that it comes back from time to time, maybe someone can write a nice blog post about it? I doubt the original decision will be revisited.

**Comment by dsyme** [comment]
I'm going to close this out per @abelbraaksma 's comment above. Agreed a blog post on this would be nice.
