### ISSUE TITLE
Allow printfn to support repeated arguments

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#94]
# Allow printfn to support repeated arguments [13393365] #

**Submitted by Dave Thomas on 4/12/2016 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

Rather than:
printfn "%i %x %A" mySecretNumber mySecretNumber mySecretNumber
Perhaps an index argument could be added
printfn "%[1]i %[1]x %[1]A" mySecretNumber

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13393365)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13393365-allow-printfn-to-support-repeated-arguments.md#comments)

**Comment by dsyme** [comment]
This was considered in F# 1.0 (and OCam supports positional arguments) but we decided against it then.  Per policy closing so as not to revisit design decisions unless there's been a significant change in circumstances
