### ISSUE TITLE
Add keyword `and`  into object expression

### ISSUE THREAD

**Issue by GratianPlume** [fsharp/fslang-suggestions#947]
# Add keyword `and`  into object expression
In the following code, I have two points of confusion.
```
   type Ah<'T>() =
      [<DefaultValue>]val mutable Data: 'T  

   let foo() = 
         {
            new Ah<bool>() with
               member __.ToString() = ""
            
            interface IDisposable with
               member __.Dispose() = 
                  let __ = unbox<Ah<bool>> __
                  if not __.Data then
                     __.Data <- true

         }
```
1. Why does the object have to override something when using the mode `object + interface`. I had to override `ToString` for the the syntax requirements.

2. And the public field of the object cannot be accessed in the interface branch, so I have to unbox it

I suggest adding the keyword `and`, so that it can be written as
```
   let foo() = 
         {
            new Ah<bool>()            
            and interface IDisposable with
               member __.Dispose() =  
                  if not __.Data then
                     __.Data <- true

         }
```
And we can set the rule: when `and` using,  the first type is the display type.

For [this issue(944)](https://github.com/fsharp/fslang-suggestions/issues/944), it is also a solution

**Comment by dsyme** [comment]
We won't be using `and` like this.  Allowing the removal of ToString is covered by other suggestions
