### ISSUE TITLE
Half-closed interval for array slice syntax

### ISSUE THREAD

**Issue by yatli** [fsharp/fslang-suggestions#949]
# Half-closed interval for array slice syntax

Existing:

```F#
let a = [| 1; 2; 3; 4; 5; |]
let s = "hey"
let b = a.[0 .. s.Length - 1]
```

Proposed:

```F#
let a = [| 1; 2; 3; 4; 5; |]
let s = "hey"
let b = a.[0 .. s.Length)
```

## Pros and Cons 

Off-by-one problems vs. freaked out parsers (incl. humans)

## Extra information

Estimated cost (M): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by BentTranberg** [comment]
Why would this be important?

For the syntax, I suggest this instead `let b = a.[ 0 .. s.Length >]` which I think is easier to read, easier to tell apart from the normal case, and I think also doesn't conflict or become confused that easily with parenthesis. Note that the de facto standard for formatting is to have spaces where you see I've put them, and this helps the compiler see `>]` as a single symbol.

**Comment by yatli** [comment]
> Why would this be important?

For example:

```F#
  let load_dsp_segs f =
    let bin = File.ReadAllBytes(f)
    let mutable i = if bin.[0] = 3uy then 6 else 0
    i <- if bin.[i] = 4uy then i+6 else i
    let out = ResizeArray()
    out.Add bin.[0..i-1]
    while bin.[i] < 3uy do
      let len = concat_3 bin (i+6)
      out.Add bin.[i..i+8+len*3]
      i <- i+9+len*3
    out.Add bin.[i..i+5]
    out
```
I really wish I can reduce cognitive load to only have 0, 3, 6, 9 in mind, not 2, 5, 8.
Too many things can go wrong in late night cyber archeology already.

**Comment by greatim** [comment]
The mismatched parentheses make the code read hard.

**Comment by dsyme** [comment]
> The mismatched parentheses make the code read hard. And too many approximate expressions can also cause confusion.

Agreed with this.

I will close this suggestion. Thanks
