### ISSUE TITLE
Allow internal/private types to fulfill SRTP constraints

### ISSUE THREAD

**Issue by cmeeren** [fsharp/fslang-suggestions#950]
[Initially asked on SO](https://stackoverflow.com/questions/65574700/can-srtp-use-internal-members)

I propose we allow internal/private types to fulfill SRTP constraints.

I know that the _implementation_ of `inline` code can't use internal/private code. That makes sense, since the code, when inlined, may not have access to the internal/private code, and the compiler doesn't know about all usages of the inlined code (they may be in other projects).

However, it also seems, surprisingly to me, that I can't pass internal types _as arguments_ to inlined functions using SRTP.

Consider this:

```f#
type internal A = { A: int }

let inline f (x: ^a) =
  (^a: (member A: _) x)

let a = { A = 0 }

let x = f a
```

It fails with a compile error on the last `a`:

![image](https://user-images.githubusercontent.com/7766733/104358992-70c8a480-550f-11eb-9daf-0fa2386446d8.png)

It seems to me that this is an unnecessary restriction. Intuitively, it seems the compiler should be able to fairly easily figure out that the members of the type `A` are accessible to the code that will be inlined on the last line. However, there may of course be compiler implementation details that make this prohibitively complex.

## Pros and Cons

The advantages of making this adjustment to F# are: Ability to hide implementation details while still using SRTP.

The disadvantages of making this adjustment to F# are: None

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): No idea

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
This is effectively covered by https://github.com/fsharp/fslang-suggestions/issues/230 and RFC 1043
