### ISSUE TITLE
Allow byref structs to be static type parameters if the code after inlining does not violate byref struct safety

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#952]
# Allow byref structs to be static type parameters if the code after inlining does not violate byref struct safety

This proposal can allow e.g. `nameof Unchecked.defaultof<Utf8JsonReader>.GetBoolean` and `typeof<Span<int>>`.

The existing way of approaching this problem in F# is via workarounds, e.g. using `nameof (Utf8JsonReader().GetBoolean)` and `typeof<Memory<int>>.Assembly.GetType(nameof Span<_>).MakeGenericType(typeof<int>)`. However, this is more verbose and not conforming to patterns used for other types. Moreover, this is not always possible if the inline function is not in the standard library.

The errors related to byref struct safety should point out the result after inlining violates byref struct safety instead of only mentioning the type instantiation.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Allowing more parity with C#. C# can do `typeof(Span<int>)` and `default(Utf8JsonReader)` just fine.
2. Reduce the need for workarounds just because byref structs are used.

The disadvantage of making this adjustment to F# is more work in the compiler to ensure that byref struct safety is not violated.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M to L

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by NinoFloris** [comment]
Duplicate of https://github.com/fsharp/fslang-suggestions/issues/688

**Comment by Happypig375** [comment]
@NinoFloris Thanks, it didn't come up during search.

**Comment by IS4Code** [comment]
So, the duplicate was closed, but the issue remains. Could we at least get `defaultof` and `typeof` special-cased so that they are usable with any type?

**Comment by T-Gro** [comment]
This is doable and for strictly reviewed fslib code, I could imagine this adding the "allows ref struct" anti-constraint e.g. based on a new attribute.

(this wasn't that straightforward before. Now with F# 9, we did have to add the understanding ability for "allows ref struct" because of C# interop)



However, that will likely bring us to "Now I want this for my own library as well" suggestion.
Are indeed the biggest pains with fslib code at the moment, and even a limited form of support would help?

**Comment by IS4Code** [comment]
@T-Gro For me, yes; a lot of C# keywords (`typeof`, `default`, `stackalloc`) are realized as normal functions in F#, so in some situations they are simply unusable with byref structs.

In my case `Unchecked.defaultof` is the blocker, so I would definitely appreciate a fix.

**Comment by IS4Code** [comment]
Related: dotnet/fsharp#10426
