### ISSUE TITLE
Allow nameof(int seq)

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#953]
# Allow `nameof(int seq)`

Just seems like an inconsistency to allow `nameof(seq<int>)` but not `nameof(int seq)`.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
I don't think this is a language suggestion as a PR could be merged to address this without the need for a language suggestion.

**Comment by dsyme** [comment]
I will mark it approved in principle.

**Comment by dsyme** [comment]
I'm actually going to close this as the workaround is just so clear, and the use of suffix notation for type constructors rare (let alone with `nameof`)
