### ISSUE TITLE
Allow typeof as attribute argument to be unparenthesized

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#954]
# Allow `typeof` as attribute argument to be unparenthesized

```fs
type A(x) = inherit System.Attribute()
[<A 1; Measure>] type B // OK
[<A(typeof<int>); Measure>] type C // OK
[<A typeof<int>; Measure>] type D // error FS0010: Unexpected identifier in attribute list
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Less noise!
2. Consistency!
3. Conciseness!
4. Less typing!

The disadvantages of making this adjustment to F# are nonexistent.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
Same for literals:

```fsharp
type A(x:int) = inherit System.Attribute()
[<A 1>] type B = class end // OK
let [<Literal>] One = 1
[<A(One)>] type C = class end // OK
[<A One>] type D = class end // error FS0010: Unexpected identifier in attribute list
```

**Comment by jwosty** [comment]
@Tarmil what?? How is that not allowed? Wow!

**Comment by dsyme** [comment]
Attributes require parentheses.  I don't see us lifting that restriction.

It comes as a surprise that some cases without parentheses are allowed such as this:
```fsharp
type A(x:int) = inherit System.Attribute()
[<A 1>] type B = class end // OK
```
However we won't be extending these cases

**Comment by auduchinok** [comment]
> It comes as a surprise that some cases without parentheses are allowed such as this:

It seems the most of the common cases don't currently require parens, and requiring it only on a few cases like `typeof` feels very inconsistent. The best option would it to either always require parens or newer require them. Something in between just doesn't feel right.

**Comment by bartelink** [comment]
Please don't make me put them back into all my Argu consumption, which IMO is [cleaner without](https://github.com/jet/propulsion/blob/master/tools/Propulsion.Tool/Args.fs#L162) the parens, vs [the noise with]( https://github.com/jet/propulsion/blob/master/tools/Propulsion.Tool/Args.fs#L94).
+1 on consistently requiring or not requiring though
