### ISSUE TITLE
Allow omitting the | between `type ... = ` and the attribute for the first union case

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#958]
# Allow omitting the `|` between `type ... = ` and the attribute for the first union case

```fs
type A = A // OK
type B = | [<Experimental "Let's add an attribute!">] B // OK
type C = [<Experimental "Attribute not allowed here?">] C // FS0565 Attributes are not allowed here
```

The existing way of approaching this problem in F# is being forced to add that `|`.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency
2. Convenience
3. Less noise

The disadvantages of making this adjustment to F# are (none)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
I think treating `type A = | ...` as the canonical form for DUs is good. Currently there is a quasi-ambiguity around `type A = B` where B is an already defined type. It's rightly resolved as a type alias but it's a slight inconsistency that it doesn't resolve as a DU. As a result I believe starting DUs with `|` is good practice and so adding functionality to the non-| form isn't needed.

**Comment by dsyme** [comment]
> I think treating type A = | ... as the canonical form for DUs is good. Currently there is a quasi-ambiguity around type A = B where B is an already defined type. It's rightly resolved as a type alias but it's a slight inconsistency that it doesn't resolve as a DU. As a result I believe starting DUs with | is good practice and so adding functionality to the non-| form isn't needed.

Yes, this is the design intention.

As a result I will close this because "already decided in F# 1.0" rule applies.
