### ISSUE TITLE
Provide a function to stringify System.Type in an F# style

### ISSUE THREAD

**Issue by Frassle** [fsharp/fslang-suggestions#959]
# Provide a function to stringify System.Type in an F# style

I propose we add a way to get the F# string representation of a System.Type. This is often useful for messages intended for F# programmers, rather than printing "System.Collections.Generic.List<System.Int32>" it could print "int ResizeList".

It would probably need some optional configuration, such as "UsePrefixTypeArguments", "UseNamespaces", "UseKeywords" etc.

`stringify : System.Type -> StringifyOptions -> string`

The existing way of approaching this problem in F# is rolling your own.

## Pros and Cons 

The advantages of making this adjustment to F# are more consistent emitting of F# style types in messages and other uses. 

The disadvantages of making this adjustment to F# are this might clash with other ideas of stringifying AST objects. If this comes first hopefully the AST stringification could just reuse this. 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: #871 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by xp44mm** [comment]
Invite you to try this open source library：

```
> Install-Package FSharp.Literals
```

to print F# types and values using the syntax of F# source code.

**Comment by dsyme** [comment]
This should be done in a package, as discussed above
