### ISSUE TITLE
Add cons and snoc for List, Seq and Array

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#960]
# Add `cons` and `snoc` for List, Seq and Array

Must we write a `fun x -> seq { yield! xs; x }` every time we want to pipe into a snoc?
Must `fun x -> x::xlist` be written every time we want to pipe into a cons?

Why can't we add equivalents to `System.Linq.Enumerable.Prepend` (cons) and `System.Linq.Enumerable.Append` (snoc) to the core library?

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Optimization for less code
2. More analogies to LINQ without having to allocate more
3. Beautiful piping

The disadvantages of making this adjustment to F# are (none)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Frassle** [comment]
Not sure cons and snoc would be appropriate for Array and Seq (compared to Prepend, Append) and then given that maybe it's better to just use Prepend/Append everywhere. But having these for piping would be nice.

**Comment by cartermp** [comment]
Could you give some motivating examples where piping is used in these scenarios?

> The disadvantages of making this adjustment to F# are (none)

Not necessarily. The terminology may not be appropriate as @Frassle says. Then there is the question of if we want people to be using these kinds of operations extensively. consing onto a list is really kind a singly linked list kind of thing, not something you really do much with arrays. Sequences is an interesting outlier here to me.

**Comment by Happypig375** [comment]
@cartermp Yes, I originally made this for `seq`s, but looking at F# 4.0's changes to unify Seq, List, and Array functions, it would make sense to continue to align them.

**Comment by Happypig375** [comment]
On terminology, we all desire short names. We chose `block` for a reason after all. On top of that, `cons` is already a well-recognized name while `append` is already used for `System.Linq.Enumerable.Concat` while `concat` is already used for `System.Linq.Enumerable.SelectMany`.

**Comment by Happypig375** [comment]
If there is a better name than `snoc` and is already in use, then it can be considered.

**Comment by dsyme** [comment]
The recent addition of `insertAt` just makes me think these are not the right addition for FSharp.Core.  I understand that `insertAt arr.Length` requires getting the length but still it's not such a bad solution.

I will close this out

**Comment by Happypig375** [comment]
@dsyme Not applicable to Seq.

**Comment by dsyme** [comment]
Right but you can Seq.append + Seq.singleton at the end. And we would always prefer a sequence expression in any case.
