### ISSUE TITLE
apply named arguments to call curried function

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#961]
# apply named arguments to call curried function

I propose we to Design a kind of approaching to call a function with named arguments. the syntactic statement is:

```F#
apply <function expression> ! <record expression>
```

The existing way of approaching this problem in F# is relying on argument position. When the parameters are of the same type, it is difficult to remember the order of the arguments.

Let's say we have a function that collects different units of length and sums them up.

```F#
let sum km m dm cm mm = 1000000*km + 1000*m + 100*dm+10*cm+mm
```

The existing way of approaching:

```F#
let res = sum 1 2 3 4 5
```

using named arguments:

```F#
let res = apply sum ! {km=1;m= 2;dm= 3;cm= 4;mm= 5}
```

Keyword `apply` and operator `!` may not be appropriate, but this is just an example.

## Pros and Cons 

The advantages of making this adjustment to F# are  named arguments is often much more readable and maintainable more than code relying on argument position.

The disadvantages of making this adjustment to F# are It is equivalent to deconstructing the first level of record data to match the name of the function definition, possibly using reflection.

**Comment by Happypig375** [comment]
Just use an anonymous record!!

**Comment by xp44mm** [comment]
Anonymous records to modify function definition will lose the benefits of powerful curry functions

**Comment by cartermp** [comment]
This kind of implicit conversion from a record where the labels map to named arguments to a function feels very much out of line with the generally explicit nature of F#. I highly doubt we'd ever do this.

**Comment by dsyme** [comment]
Yes this specific version of named arguments for curried functions is not going to happen.

We could consider allowing named arguments within immediate applications of curried functions, but where correct curried ordering is still required, e.g. 

    let sum (km,m) dm cm mm = 1000000*km + 1000*m + 100*dm+10*cm+mm
    let res = sum (m=2, km=1) (dm=3) (cm= 4) (mm= 5)

Here named arguments mainly serve for code clarity.   I'm not in favour of allowing changed ordering of curried parameters.

There is enough metadata for this and practically speaking I think the backwards compat issues would not be too problematic (existing code passing booleans would be allowed).

**Comment by xp44mm** [comment]
We like named parameters, no matter what style of named parameters.

**Comment by Tarmil** [comment]
@xp44mm `!` brings another ambiguity though, because it could be an operator. OCaml uses `~`, which is not otherwise usable as the first character of an operator.
