### ISSUE TITLE
Clarify the use of the `void` keyword

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#962]
# Allow `typeof<void>`

The existing way of approaching this problem in F# is `typeof<obj>.Assembly.GetType("System.Void")`

Btw, where even can the keyword `void` be used currently??

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Interoperability
2. Calling more functions easily
3. Fixing a case where F# can't supply an argument to an attribute while C# can

The disadvantages of making this adjustment to F# are none!

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Tarmil** [comment]
You can actually do `typeof<System.Void>`. But being able to do `typeof<void>` would still be nice 🙂

**Comment by charlesroddie** [comment]
> You can actually do `typeof<System.Void>`

Suggest closing as resolved

**Comment by Happypig375** [comment]
Hmmm. I'm surprised that `void` and `System.Void` are different. Under C# rules, they are the same. I imagine that the F# `void` keyword cannot be used anywhere to remind people coming from C# to learn `unit` instead? This is not mentioned anywhere and should be clarified, whether by making `void` equivalent to `System.Void` or having the error message suggesting to use `unit` instead.

**Comment by cartermp** [comment]
`void` is a keyword (not a type or function) used for extern definitions, see here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/external-functions

I don't see much value in `typeof<void>` when there is already `typeof<System.Void>`.

**Comment by dsyme** [comment]
Closing per @cartermp 's comment above
