### ISSUE TITLE
`new` as a function

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#970]
# `new` as a function

I propose we allow `new` as a function, i.e. a target-typed new expression.

```fs
let f (x:System.Collections.Generic.Dictionary<int, string>) = ()
let x = f <| new() // Type information flows from left to right. |> will result in an error.
```

This aligns with the `new(args) = constructor_body` syntax for defining secondary constructors.

The existing way of approaching this problem in F# is spelling out the long-long names for constructing arguments.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Consistency between constructor definitions and using them

The disadvantage of making this adjustment to F# is that this is one more way to do the same thing. However, it is just a short-hand to reduce typing.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions: C#'s target-typed `new`

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
This isn't something we need to do, it's just obfuscating code.

**Comment by gusty** [comment]
@Happypig375 I think you can define it like this:

```
> let inline New (x: 't)  = (^R : (new : 't -> ^R) x) : 'R ;;
val inline New : x:'t ->  ^R when  ^R : (( .ctor ) : 't ->  ^R)
```

Unfortunately, it doesn't work for unit types, so you need a separate one:

```
> let inline NewUnit ()  = (^R : (new : ^R) ()) : 'R ;;
val inline NewUnit : unit ->  ^R when  ^R : (( .ctor ) : ->  ^R)
```

**Comment by Happypig375** [comment]
@gusty I intended it to be C#'s target-typed new thus will support arbitrary arguments.

**Comment by cartermp** [comment]
The biggest motivator to do this on the C# side was the allow less typing for field declarations, since you can't use `var` there. Explicit fields (that is, not the private, `let`-bound class values) are super rare in F# code. It also has other benefits when it comes to things like collection initialization, but it's also not the same situation since collection initialization is usually pretty lightweight in F# when compared to C# as well.
