### ISSUE TITLE
`System.Type` and `System.ReadOnlyMemory<primitive>` [<Literal>]s, and allow `System.ReadOnlyMemory<primitive>` to be supplied into attributes

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#971]
I propose we allow `System.Type` and `System.ReadOnlyMemory<primitive>` [\<Literal>]s, and allow `System.ReadOnlyMemory<primitive>` to be supplied into attributes.

```fs
let [<Literal>]  t = typeof<int>
let [<Literal>] ts : System.ReadOnlyMemory<Type> = [|typeof<int>;typeof<obj>|]
type [<SomeAttribute(t, ts)>] C = class end
```

Since `System.Type` is allowed as attribute arguments, they should be allowed as [<Literal>] s as well.

Moreover, `primitive[]` can be attribute arguments, but to enforce immutability, the [<Literal>] version should accept `System.ReadOnlyMemory<primitive>`. Attribute arguments should allow this type too.

The existing way of approaching this problem in F# is repeating attribute arguments over and over. Defining new attributes and supplying to properties is not always possible due to [<Sealed>] and exact type lookups. Moreover, defining entire new attributes for each  result in the attribute arguments being located far away from their usage. 

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Consistency between constructor definitions and using them

The disadvantage of making this adjustment to F# is that this is one more way to do the same thing. However, it is just a short-hand to reduce typing.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions: #847 Decimal, nativeint and unativeint literals

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
My understanding is the .NET CLI attribute format will not support this?   Is there some change to that format that would allow this?

* If so, we can support it

* If not, we should close as its not technically feasible.

**Comment by Happypig375** [comment]
I know that attribute arguments accept `System.Type` and single-dimensional arrays of primitive types. Is this not the case?

**Comment by dsyme** [comment]
The questions are what literals are supported, and what expressions can be used in attribute parameter expressions.

From the C# spec: 
```
A constant expression must be the null literal or a value with one of the following types: sbyte, byte, short, ushort, int, uint, long, ulong, char, float, double, decimal, bool, object, string, or any enumeration type. Only the following constructs are permitted in constant expressions:
```

So my understanding is C# literals do not include System.Type, unless there's been a recent change.

For attribute parameter expressions, my understanding is this doesn't include ReadOnlyMemory - arrays and nothing else.

So unless there's a change in the CLI spec I don't think we should change anything here.

**Comment by Happypig375** [comment]
From https://stackoverflow.com/a/42734285/5429648, at least `System.Type` supports being initialized through binary data in IL, which means that it can be a constant value. For arrays, if we can't use `ReadOnlyMemory<'T>`, then maybe we can trust user code to not assign? That is the sole reason for wanting to use `ReadOnlyMemory<'T>`.

**Comment by dsyme** [comment]
Sorry I don't understand what you're proposing.

`ReadOnlyMemory` cannot be used in attributes parameter expressions.  It is not usable as a C# const and hence is not usable as an F# literal.   

`Type` can be used in attributes parameter expressions - that is supported in both F# and C# today.  However AFAIK it is not usable as a C# const and hence is not usable as an F# literal.   

> For arrays, if we can't use ReadOnlyMemory<'T>, then maybe we can trust user code to not assign? That is the sole reason for wanting to use ReadOnlyMemory<'T>.

AFAIK it's not technicall populate attributes via `ReadOnlyMemory<'T>`.  So I don't know why we're continuing to discuss it.

Unless you can link me a change in the CLI spec for attributes or the C# spec for literals this is not going to happen.

**Comment by dsyme** [comment]
Yup

I'll close this for now
