### ISSUE TITLE
a kind of record construct expression

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#973]
# record construct expression

I propose we try a kind of record construct expression

```F#
type Point2d = {
    x:int
    y:int
}

type Point3d = {
    x:int
    y:int
    z:int
}

let p2d = {x=3;y=4;}
let z = 0

// record construct expression usage:
let p3d = record<Point3d> {
    yield! p2d
    yield z
}

>> {x=3;y=4;z=0}
```

The existing way of approaching this problem in F# is ...

```F#
let p3d = {
    x = p2d.x
    y = p2d.y
    z = z
}
```

**Comment by cartermp** [comment]
Labeling but I don't think we'd do this. It would require a form of record polymorphism to even be a possibility as well.

**Comment by dsyme** [comment]
I'll close this out as agreed it's not something we'll do
