### ISSUE TITLE
Add function! (function-bang) keyword to computation expressions

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#974]
# Add function! (function-bang) keyword to computation expressions

I propose we extend computation expressions with a new keyword, function! (function-bang), that functions a match!  For example, instead of writing:

```fsharp
let createResult = 
    connection  |> createEntityAsync entity
 
match! createResult with
| Error msg -> ..
| Ok _ -> ...
```

```fsharp
connection
    |> createEntityAsync entity
    |> function!
       | Error msg -> ...
       | Ok _ -> ...
```

## Pros and Cons 

Pros: Aids code readability in specialized cases.

Cons: increases complexity.

## Extra information

First suggested [here](https://github.com/fsharp/fslang-suggestions/issues/572#issuecomment-565713917) 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by jwosty** [comment]
Interestingly enough, the implementation of ``match!`` actually desugars to ``let!`` followed by a ``function`` instead of ``match``, which is also exactly what this suggestion would do. So this would be pretty easy.

**Comment by dsyme** [comment]
I am generally not in favour of extensive use of `function` - very occasionally, but it should be rare.  So in all cases I would prefer an explicit  `match!`.  

For this reason, I will close this.
