### ISSUE TITLE
Chained comparisons

### ISSUE THREAD

**Issue by yatli** [fsharp/fslang-suggestions#976]
# Chained comparisons

I suggest we support chained comparison, concerning built-in operators `<,<=,=,>=,>`
This allows fluent range expressions, e.g.
```F#
if 0x00300000 <= location < 0x00700000 then ...
```

The existing way of approaching this problem in F# is to combine multiple comparison expressions with `&&`:
```F#
if 0x00300000 <= location && location < 0x00700000 then ...
```

## Design details
Total order is mandated in the chain. That means only one direction is allowed in a single chain, either
`a < b <= c = d < e ...` -or-
`a = b > c >= d ... `, so partially ordered expressions like `3 >= x <= 5` are not allowed (which is different from some languages, e.g. Python)
Note that inequality `<>` is not considered here, because it's supposed to be non-transitive.

The compiler should desugar the chain into nested binding contexts, for example, `a < b < c < d` should be desugared to:
```F#
let t1,t2 = a,b
in t1 < t2 && let t3 = c
              in t2 < t3 && let t4 = d
                            in t3 < t4
```
This guarantees 1) strict eval order + proper shortcutting 2) progressive value capturing, so each expression in the chain is evaluated at most once.

## Pros and Cons 

The advantages of making this adjustment to F# are:
- Fluent range checks
- Convenient for linear comparison chains, e.g. `1.0 < x < y < 3.0`
- Chained equality checks, e.g. `x = y = z`

The disadvantages of making this adjustment to F# are:
- It is, at first sight, not obvious that there's implicit short-cutting and value capturing
- Tupled chains like `(1,1) < (x,y) < (3,3)` and `(1,3) < (x,y) < (3,5)` have counterintuitive semantics. Nevertheless this can be mitigated by wrapping the tuple in a proper type and overload the comparison, e.g. `TopLeft(1,1) < Point(x,y) < BottomRight(3,4)` (which benefits from value capturing that each instance is constructed at most once)
- If the overloaded comparison does not define a total order, then the comparison chain is ill-formed :(
- A newcomer may find `let a=b=c=d` confusing. (But we already have `let a=b=c` now)

## Related proposals

#675 proposes multi-value equality check, that the first operand is equal to at least one of the following operands.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
  * As @kevmal points out, currently true > false > false is true and with this change it would be false.
  * All nested boolean comparison expressions are affected. Some will be invalid (`x>y<z`), some behaviors will change (`x=y=z`).
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
Related issue: https://github.com/fsharp/fslang-suggestions/issues/675

I think it would be quite unexpected from the user's perspective if we did this but disallowed something like `3 >= x <= 5`.

**Comment by kevmal** [comment]
If I'm reading this correctly this would be a breaking change, currently `true > false > false` is `true` and with this change it would be `false`.

**Comment by yatli** [comment]
@kevmal noted, thanks!
I've updated the proposal.

**Comment by yatli** [comment]
@cartermp thanks, I've updated the proposal to relate #675.

"Jagged" comparison chains are indeed more powerful, because it is a superset of the unidirectional chain.
For example, `1 < x > y < 1` cannot be expressed in one unidirectional chain.
Plus this:
```F#
// Not a problem for Python...
let f<'T> _ = "bazinga"
type T = | Foo
let x = 0
let y = 1
let T = 2
printfn "%A" (f<T>y)
// bazinga!
```

Although more powerful, I personally find "jagged" chains counterintuitive.
Nevertheless, after a quick search, I gather this table about the support of similar features:

|Language|Chain|Jagged|
----------------------------
|Broader C family|No|No|
|Go|No|No|
|Rust|In discussion||
|Pascal family|No|No|
|Python|Yes|Yes|
|Ruby|Yes|Yes|
|Perl|Yes|Yes|
|Broader ML family|No|No|
|Lisp family|Yes (naturally)|No|
|Mathematica|Yes|Yes(!)|

**Comment by Happypig375** [comment]
This is a championed C# feature: https://github.com/dotnet/csharplang/issues/4108

**Comment by dsyme** [comment]
I'm not totally opposed to this feature but it doesn't really feel like it fits into F#.  The table above makes for interesting reading though!
