### ISSUE TITLE
the name of the type-annotation's component

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#977]
# the name of the type's component

I propose we Whether we can give the name of the type's component, and the IDE has the ability to prompt the name of the type's component. 

You can think of a type annotation as a tree, and each node in the tree is another type annotation. Is it possible to allow any node in the tree to be named?

Such as:

```F#
let symbols = ConcurrentDictionary<input:Set<rule:string list>, output:Set<symbol:string>>(HashIdentity.Structural)
```

The existing way of approaching this problem in F# is 

```F#
/// rules -> symbols
let symbols = ConcurrentDictionary<Set<string list>, Set<string>>(HashIdentity.Structural)
```

## Pros and Cons 

The advantages of making this adjustment to F# are to Make the program more semantically meaningful. 

A very useful advantage is that it is possible to replace a record type with a tuple type, giving a tuple type the semantics of a record without the restriction of a record type. For example, find the polar coordinates of an imaginary number:

```F#
polar:(x:float) -> (y:float) -> (length:float) * (angle:float)

// instead of:
polar:(x:float) -> (y:float) -> {| length:float; angle:float|}
```

The disadvantages of making this adjustment to F# are that Type declarations are more complex.

## Extra information

Estimated cost (**XS**, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
As mentioned in https://stackoverflow.com/questions/7487551/no-argument-names-in-abstract-declaration, the correct resolution here is removing the parentheses surrounding `(center:Point)`.

Also, you should rename this suggestion to "Allowing parentheses to surround abstract member parameters".

**Comment by xp44mm** [comment]
@Happypig375 Thank you. Perfect solution to my problem.

**Comment by cartermp** [comment]
@xp44mm Looking at the edits, this now has a very different sample and it's unclear if the request is to allow something like so:

```fsharp
abstract member PutChar : (x:int) * (y:int) * (c:char) * (flag:Background) -> unit
```

or this:


```fsharp
let symbols = ConcurrentDictionary<input:Set<rule:string list>, output:Set<symbol:string>>(HashIdentity.Structural)
```

Both are distinct changes to the language so we'd want to track them separately.

**Comment by charlesroddie** [comment]
The current version of this issue is about named generic type arguments, and I assume it means to use the actual names of the arguments.
```fsharp
let symbols = ConcurrentDictionary<TKey = Set<rule:string list>, TValue = Set<symbol:string>>(HashIdentity.Structural)
```
I wouldn't use this feature but it does seem theoretically possible to implement.

**Comment by yatli** [comment]
I think @xp44mm is proposing arbitrary name bindings to type parameters, rather than the names as in the prototype/definition.

The example contains both `Set<rule:string list>` and `Set<symbol:string>`

Some sort of temporary type aliasing.
Could be handy for complex type expressions, e.g.
`(System.Collections.Concurrent.ConcurrentDictionary<int,int> as 't in 't * 't * Set<'t>)` vs.
`(System.Collections.Concurrent.ConcurrentDictionary<int,int> * System.Collections.Concurrent.ConcurrentDictionary<int,int> * Set<System.Collections.Concurrent.ConcurrentDictionary<int,int>>)`

**Comment by xp44mm** [comment]
> Maybe I'm giving an example without explaining the intent, add another example to illustrate the usage, and update the first comment.

The most significant advantage is that it is possible to replace a record type with a tuple type, giving a tuple type the semantics of a record without the restriction of a record type. For example, find the polar coordinates of an imaginary number:

```F#
polar:(x:float) -> (y:float) -> (length:float) * (angle:float)

// instead of:
polar:(x:float) -> (y:float) -> {| length:float; angle:float|}
```
