### ISSUE TITLE
Currying constructors

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#978]
I propose we allow:
```fs
type Class1 x = class end // 1. Omitting parentheses for the single argument in a primary constructor
type Class2 x y = class end // 2. Curried primary constructors
let c = Class2 1 // 3. Partial application of curried primary constructors
type Class3 =
    // new x = { } // Omitting parentheses for the single argument in a secondary constructor is already allowed
    new x y = { } // 4. Curried secondary constructors
    new x y z = { } // Error FS0439 - Constructors with curried arguments cannot be overloaded
let d = Class3 2 // 5. Partial application of curried secondary constructors
type Class4 x = // Overloading here is totally fine just like overloading members with tupled arguments
    new(x, y) = new Class4 x // 6. Omitting parentheses for calling a constructor with "new"
    interface System.IDisposable with member _.Dispose() = ()
let e = 3 |> new Class4 |> id // 7. Piping into a constructor with "new"
let f = new Class4 // 8. Defining a function as a constructor with "new"
type 'T Class5 x y z = do () // Unambiguous even when using prefix-style generic definitions
let g<'X> = new ('X Class5) // Equivalent to `let g<'X> = fun x y z -> new ('X Class5)(x, y, z)`
```
To encode curried constructors, we can just slap `CompilationArgumentCountsAttribute`s on constructors with curried arguments.

The existing way of approaching this problem in F# is writing unnecessary curried functions to aid in partial application.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Consistency between members and constructors with regards to currying
2. Consistency between calling constructors with and without `new`
3. Less unnecessary parentheses - less noise
4. Less unnecessary curried functions just to partially apply arguments

The disadvantages of making this adjustment to F# are the extra learning required.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions: This suggestion is a strict superset of https://github.com/fsharp/fslang-suggestions/issues/753.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
> The disadvantages of making this adjustment to F# are the extra learning required.

To be honest, the fact that members can be curried is - to me - kind of a wart in the language design today. There's something nice about being in "function world" vs. "object world" when it comes to using curried vs. tupled parameters. But from an orthogonality perspective I suppose this would be fine to do if it's possible.

**Comment by pblasucci** [comment]
> There's something nice about being in "function world" vs. "object world" when it comes to using curried vs. tupled parameters.

For what it's worth, after many, many years of introducing the language at several different shops, and guiding multiple teams with medium-to-large codebases in production environments, it's definitely emerged as a "recommended practice" to limit curried parameters to module/local functions (i.e. use tupled form with methods). In fact, if it were possible to prevent currying on methods (I know it isn't), that would be even better. Just sayin' 😉

**Comment by charlesroddie** [comment]
The current behaviour fits the name "constructor" and keeps things simple: takes an input and returns an object of that type. A "curried constructor" might be called a "constructor generator" since it takes an input and returns either a lower order constructor generator or a constructor.

**Comment by Happypig375** [comment]
@cartermp I suppose 1, 6, 7, and 8 can still be done separately from 2, 3, 4, and 5.

**Comment by charlesroddie** [comment]
Those are separate from curing constructors. I think it would be good to omit `new`. It was always a strange marker of IDisposability and the coloring of IDisposables we have now is superior.

**Comment by dsyme** [comment]
TBH I'm not inclined to any these.  

1. For this
```fsharp
type Class1 x = ....
```
The thing is, implicit constructors are sufficiently unusual and new for many programmers that I'm really comfortable with making the parameterization obvious 
```fsharp
type Class1(x) = ...
```

2.3.4.5.. For currying I agree with comments above - constructors have a special status and the distinction of "is a partially applied constructor still a constructor" is not a place I want to go.

6,7,8.  For `new Class4 x ` etc I agree with @charlesroddie that the norm is more and more to omit `new` and that it's only there for a highly explicit form to give clarity - whether IDisposable or otherwise.  In this case there's no value in implicit versions of this construct, sine they water down the explicitness it's there for.

**Comment by dsyme** [comment]
I will close this, as I'm certain we're not going to do it.  The suggestions are not wrong as such and it's good to have them recorded.

@Happypig375 I'm really really grateful for all the suggestions you're making, even if I'm closing ones like this.  I appreciate it takes a huge amount of time to make these suggestions and to go over the design of the language with a fine toothcomb as you're doing.  What you're doing is of huge value to the community and I really appreciate it.

**Comment by Happypig375** [comment]
Kudos to you and the F# team's daily work as well.

**Comment by dsyme** [comment]
https://mobile.twitter.com/dsymetweets/status/1537555321010409472 🤗🤗🤗
