### ISSUE TITLE
Pattern match `Array`, `Set`, `Map` in the same way as `list`

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#979]
# Pattern match `Array`, `Set`, `Map` in the same way as `list`

I propose we Deconstruct `Set`, `Array`, `Map` in the same way as `list`.

deconstruct array:
```F#
match<int[]> arr with
| [] -> ....
| hd::tail -> ....
```

deconstruct set:
```F#
match<Set<int>> st with
| [] -> ....
| hd::tail -> ....
```
deconstruct map:
```F#
match<Map<int,string>> mp with
| [] -> ...
| (key,value)::tail -> ....
```

The angle brackets following `match` are type arguments because type inference does not distinguish from lists, arrays, sets, and maps.

The existing way of approaching this problem in F# is to use `if` statement:

deconstruct array:
```F#
match arr with
| [||] -> ....
| [|x|] -> ....
```

deconstruct set:
```F#
if Set.isEmpty st then
...
elif st.Count = 1 then
  let hd = Set.minElement st
elif ... then
else
```
deconstruct map:
```F#
if Map.isEmpty mp then
...
elif mp.Count = 1 then
....
elif ... then
else
```

## Pros and Cons 

The advantages of making this adjustment to F# are that Deconstructing code is more intuitive and flexible. It can be integrated into other deconstructed code.

The disadvantages of making this adjustment to F# are Type inference does not distinguish between the above list types.

## Extra information

Estimated cost (XS, S, M, **L**, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by gusty** [comment]
List is a DU, that's why you can naturally de-construct it.
Your proposal doesn't specify if you want to make those types a DU or if you want to special-case them in the compiler to be able to deconstruct it.

My feeling is that Active Patterns is the way to go here.

**Comment by dsyme** [comment]
Closing per comments by @gusty above
