### ISSUE TITLE
Positional specifiers and custom formats for printf formats

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#981]
# Positional specifiers for printf formats

I propose we add the [`$` specifier for printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html).

```fs
printf "%d %1$d %d %2$d %d\n" 11 22 33 // 11 11 22 22 33
printf $"{11} %1$d {22} %2$d {33}\n" 11 22 33 // 11 11 22 22 33
```

The existing way of approaching this problem in F# is to specify the arguments multiple times. However, with positional arguments, we can curry more effectively:
```fs
let printDate format =
    printf <|
        match format with
        | ISO -> "%d-%d-%d"
        | UnitedStates -> "%2$d/%3$d/%1$d"
        | Europe -> "%3$d/%2$d/%1$d"
        | _ -> "%3$d.%2$d.%1$d"
```
has considerably less repetition than
```fs
let printDate format year month day =
    match format with
    | ISO -> printf "%d-%d-%d" year month day
    | UnitedStates -> printf "%d/%d/%d" month day year
    | Europe -> printf "%d/%d/%d" day month year
    | _ -> printf "%d.%d.%d" day month year
```

# Custom formats for printf formats

I propose that we add:
```fs
printf "%{n}O" <| System.Guid.NewGuid() // 724ae5e24bea4518b1531154600a181d
printf $"%{n}O{System.Guid.NewGuid()}" // 4b569b082ac6446f98a150fb3891d25d
```
The `{n}` contains the custom format for `System.IFormattable`s, and in this case is the `n` format for `System.Guid`.
This is analogous to C# `System.Console.WriteLine($"{System.Guid.NewGuid():n}");`.

If `{`s or `}`s are to be included in custom formats, they must be duplicated just like in C#.
If the object does not implement `System.IFormattable`, then just like in C#, the custom format is ignored.

The existing way of approaching this in F# is to call `ToString()` on each application which is bad for currying.
```fs
let write a b c (d:System.Guid) = printf $"""%d{a} %d{b} %d{c} %s{d.ToString "n"}"""
```
vs
```fs
let write = printf "%d %d %d %{n}O"
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Less repetition, more reuse

The disadvantages of making this adjustment to F# are
1. It takes time to be familiar with the formats, however, it can also be said so for other existing formats.
2. Multiple ways to do the same thing - Didn't we add interpolated strings despite printf formats?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: https://github.com/fsharp/fslang-suggestions/issues/271#issuecomment-257098660
> From the point of view of the F# language design, I would be happy to see a well-considered set of extensions to printf added to F# 4.x or later versions. An implementation and testing would need to be provided by someone in the F# community (possibly including Microsoft or Microsoft Research, though not limited to them). We would strongly welcome an implementation proposal and initial testing for this.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
I think this is too niche, and that it is actually quite hard to understand what's going on with positional specifiers.  I don't want F# programmers to have to know this when there are other more explicit ways to code it that make the code easier to comprehend.
