### ISSUE TITLE
Very tentative ideas around soft annotations

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-suggestions#986]
This is not particularly well thought-out, and it is a large design space, very tentative and unlikely to happen at all.

I propose we consider adding some kind of soft annotation syntax to F#. For example optionally soft annotating types carrying tensors with shape information, so given this:

```
    let createAttentionMask(text: TextBatch) : Tensor =
        <expr>
```

you can mark the types as accepting optional soft annotations:
```fsharp
    [<SoftAnnotationsAccepted>]
    type Tensor() = ...

    [<SoftAnnotationsAccepted>]
    type TextBatch() = ...
```
and then supply soft annotations:
```fsharp
    let createAttentionMask(text: TextBatch[BatchSize,MaxLength]) : Tensor[BatchSize,MaxLength,MaxLength] =
        <expr>
```
or maybe
```fsharp
    let createAttentionMask(text: TextBatch<'BatchSize, 'MaxLength>) : Tensor<'BatchSize, 'MaxLength, 'MaxLength> =
          <expr>
```

where "SoftAnnotationsAccepted" would presumably mean the type accepts an arbitrary length of soft annotations `<...>` after any actual generic parameters.

Soft annotations would not be checked by the F# compiler but rather by optional tooling at compile-time or runtime such as the proposed [F# analyzers](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1033-analyzers.md)

To make the information available for F# analyzers and other F# tooling, we would emit them as attributes in generated code, thus making the soft annotation information available at both compile-time and runtime for a variety of tooling. These attributes would also be available to F# analyzers via the F# Compiler Service API:

This might look something like this:
```
    [<SoftAnnotation("text", 0, "BatchSize")>]
    [<SoftAnnotation("text", 1, "MaxLength")>]
    [<SoftAnnotation(Return=true, 0, "BatchSize")>]
    [<SoftAnnotation(Return=true, 1, "MaxLength")>]
    [<SoftAnnotation(Return=true, 2, "MaxLength")>]
    let createAttentionMask(text: TextBatch[BatchSize,MaxLength]) : Tensor[BatchSize,MaxLength,MaxLength] =
        AssertSoftAnnotation(text, "[BatchSize,MaxLength]")
        let res = <expr>
        AssertSoftAnnotation(res, "[BatchSize,MaxLength,MaxLength]")
        res
```

Note this injects the information both at compile-time (`SoftAnnotationAttribute`) and runtime (`AssertSoftAnnotation`) - the runtime assertions would be debug-only presumably.   Exactly how `AssertSoftAnnotation` would work would be TBD, probably type directed so `TextBatch.AssertSoftAnnotation(text, "[BatchSize,MaxLength]")`, but it's unclear.

One existing way of approaching this problem in F# is either just not to give soft annotations, or to use attributes, e.g.

```
    [<Shape("BatchSize, MaxLength", ReturnShape="BatchSize,MaxLength,MaxLength")>]
    let createAttentionMask(text: TextBatch) : Tensor =
        <expr>
```

This is used in prototypes of DiffSharp shape checking.

There are many questions about this, e.g. 

- syntax, e.g. should soft annotations be optional soft generic type annotations 

- other use cases? In fable? 

- potential confusion with type checking

- interaction with IDE tooling (would IDE tooling show any soft annotations)

- is it better to make type checking more and more extensible

- what data/expressions could be used in soft annotations. For example tensor shapes require "N*M" and "N+1" and so on.

- would we have done units of measure this way, indeed would we change units of measure to work like this?  Is that a litmus test?

## Pros and Cons 

The advantages of making this adjustment to F# are extensible checking that associates well with F# idioms

The disadvantages of making this adjustment to F# are complexity, a plethora of use cases (slippery slope), checking relying on additional tooling addins.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): L

Related suggestions: 

* [F# Analyzers](https://github.com/fsharp/fslang-design/discussions/508)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment]
Dependent types pog?

**Comment by dsyme** [comment]
> Dependent types pog?

No.

**Comment by dsyme** [comment]
Closing this half-baked idea

**Comment by Happypig375** [comment]
@dsyme You can close issues as "not planned" now, instead of showing them as "completed".
![image](https://user-images.githubusercontent.com/19922066/173623198-a37b7186-a351-46b2-87d7-752e1d324b16.png)
