### ISSUE TITLE
Add compiler flag to default to struct representation of single case and valueless discriminated unions

### ISSUE THREAD

**Issue by iriri** [fsharp/fslang-suggestions#987]
# Add compiler flag to default to struct representation of single case and valueless discriminated unions

I propose we add a flag to opt into struct representation of discriminated unions by default in these two cases where there is practically no advantage to boxing. The only scenario in which performance gets worse with a value type is `type Boxed = Boxed of MyHugeValue` where you implicitly rely on your single case union to avoid copying, which I would argue is both very niche and bad practice.

The existing way of approaching this problem in F# is to just write `[<Struct>]` all the time. This is, to put it lightly, not obvious or appealing for beginners.

```fsharp
// Wastes a line
[<Struct>]
type Foo = Foo of int

// (Subjectively) ugly
type [<Struct>] Bar =
   | A
   | B
   | C
```

## Pros and Cons 

The advantage of making this adjustment to F# is that we can opt into better defaults. Furthermore, there are a lot of questionable solutions to this problem out there, possibly due to the poor discoverability of attributes.
- [Swapping type-safety for high performance using compiler directives](https://fsharpforfunandprofit.com/posts/typesafe-performance-with-compiler-directives) was written before struct discriminated unions were added to the language and explores using the preprocessor in combination with an active pattern to achieve an unboxed representation in release builds. One commenter remarks many years later that applying the `[<Struct>]` attribute is now a better solution and another states that he did not know that this was possible.
- [Writing high performance F# code](https://bartoszsypytkowski.com/writing-high-performance-f-code) suggests using units of measure. This feels somewhat like a hack, does not prevent mistakes like the division of two unrelated types, and most importantly can only be done with floats and signed integers.

The disadvantages of making this adjustment to F# are that it introduces another knob (but an easy one, in my opinion) and some work will have to be done.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions:
- https://github.com/fsharp/fslang-suggestions/issues/813 proposes a flag to make struct tuples the default, which has many more downsides than this idea.
- https://github.com/fsharp/fslang-suggestions/issues/563 proposes extending units of measure to support more types, largely in service of achieving similar functionality to single case discriminated unions. As discussed above, units of measure do not seem like the best tool for this job.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by kerams** [comment]
> This is, to put it lightly, not obvious or appealing for beginners.

I really doubt there are many beginners who obsess about boxing and high performance scenarios.

Wouldn't it make more sense to take another approach that goes one step further in your two cases and completely erase the unions (a la `Option`)? The first would be reduced to an integer and the second to an integer (int16, byte where possible) tag. On second thought, there's probably good reason why this hasn't been done before or why it's too late to do now.

**Comment by iriri** [comment]
>I really doubt there are many beginners who obsess about boxing and high performance scenarios.

I don't think it's a good experience for beginners to find out many months later that `type Foo = Foo of int` is not a "zero cost abstraction", especially when (zero cost) newtypes are very popular in some other languages.

> Wouldn't it make more sense to take another approach that goes one step further in your two cases and completely erase the unions (a la `Option`)? The first would be reduced to an integer and the second to an integer (int16, byte where possible) tag.

Not really, because this suggestion isn't about getting the best possible performance in some specific case but rather about not paying a the fairly steep cost of a heap allocation in the general case where single case and valueless discriminated unions are used. I still want to be stopped from using a `Foo of int` in place of a `Bar of int` and I still want my matches to be checked for exhaustiveness. Both are lost by switching to integers.

> On second thought, there's probably good reason why this hasn't been done before or why it's too late to do now.

Struct discriminated unions were only added to the language in F# 4.1. It's a breaking change to make them the default for these cases without a flag and I wouldn't be surprised if this suggestion were to still be considered a breaking change with a flag.

**Comment by kerams** [comment]
> I don't think it's a good experience for beginners to find out many months later that type Foo = Foo of int is not a "zero cost abstraction", especially when (zero cost) newtypes are very popular in some other languages.

I'll simply have to disagree with you here, that has to be extremely rare.

> because this suggestion isn't about getting the best possible performance in some specific case but rather about not paying a the fairly steep cost of a heap allocation in the general case where single case and valueless discriminated unions are used.

To me, your suggestion also reads exactly like getting the best possible performance (removing the allocation) in the SPECIFIC case of single case and valueless unions :).

> I still want to be stopped from using a Foo of int in place of a Bar of int and I still want my matches to be checked for exhaustiveness. Both are lost by switching to integers.

Neither would be lost. I am talking about runtime erasure - options work like that today. The only "naughty" thing you'd be able to do is pass `Foo of int` to a function expecting `Bar of int` by using reflection. Just like you can pass `string option` to a function expecting a string.

**Comment by cartermp** [comment]
In generally we really, really want to avoid compiler switches like this, which I would say is a pretty large negative.

**Comment by iriri** [comment]
Yeah, that makes sense. I forgot to reference https://github.com/fsharp/fslang-suggestions/issues/727 and I honestly don't consider `type ReallyLongName = ReallyLongName of int` to be horrible syntax but if newtyping becomes common enough practice it may be worth it to combine these two suggestions an offer a dedicated syntax for unboxed newtypes.

**Comment by zpodlovics** [comment]
"Please note struct option is NOT a drop-in replacement for reference option types. And please do NOT try to replace automatically it with the compiler, it will create a gigantic mess. There are lot's of things that you can do with references but you cannot do with structs eg.: volatile / atomic operations, you cannot write more than pointer sizes atomically in .NET (the x86_64 CMPXCHG16B instructions allows 16 byte CAS but not yet exposed in .NET)"

fsharp/fslang-design#230
https://github.com/fsharp/fslang-suggestions/issues/874#issuecomment-640226035

**Comment by iriri** [comment]
Agreed that value types are not a drop-in replacement for reference types under most circumstances. But `type Foo = A | B | C` is (on 64 bit architectures) an 8 byte pointer to a 24 byte heap allocation while `type [<Struct>] Bar = D | E | F` is 4 bytes on the stack. And `type Baz<'a> = Baz of 'a` is similarly wasteful in the overwhelmingly common case where `'a` is either a reference type or a small value type like `int`.

**Comment by zpodlovics** [comment]
So we can agree if not a drop-in replacement it will change the program semantics. The program will no longer works in a way as before.

0) How the safety and correctness issue will be resolved?

1) How the (64bit) long use cases solved targeting netstandard2.0 with AnyCPU and part of the users / customers executed on a 32bit .NET Framework  / other part of the users / customers executed on a 64bit .NET Framework / .NET Core would be solved? 

It seems this could render a completly correct and working application / library before (long / generic is not atomic on a 32bit machine) to a broken one. 

2) How the generic case when your type may or may not larger than the pointer size (even on 64 bit machine) or part of the cases are smaller part of the cases would be solved?

3) How small is a small value type exactly? How small is a small value exactly in a constrained environment (iot devices, microcontrollers, etc)?

4) How the principle of least suprise will be solved? A developer change a multi-case union to single case or a single case union to multi case and there will be cases when a a completly correct and working application / library than suddenly have issues?

Safety and correctness first. The developers can (and should) make these decisions explicitly, especially those who target performance.

**Comment by charlesroddie** [comment]
Both cases of "disciminated unions" mentioned here are trivial cases which don't hold disciminated data. So it's best not to use discriminated unions for this.

This suggestion could become:

```fsharp
// syntactic sugar
type container A of b:B

// equivalent to:
[<Struct>]
type A(b:B) = member _.Value = b

// syntactic sugar
enum Bar = A | B | C

// equivalent to:
type Bar =
   | A = 0
   | B = 1
   | C = 2
```

> @iriri I still want my matches to be checked for exhaustiveness. Both are lost by switching to integers.

Enum matches are exhaustiveness checked.

**Comment by iriri** [comment]
>0. How the safety and correctness issue will be resolved?

The suggestion is to add a compiler flag to opt into a new default. Existing code can continue to rely on existing behavior. If an existing program enables the feature it will be met with compilation errors if it is no longer correct. But yes, Phillip has raised a good point about wanting to avoid such switches so I am mostly just trying to argue that the proposed default is indeed the correct one if an opportunity to switch arises (new sugar, etc.).

>1. How the (64bit) long use cases solved targeting netstandard2.0 with AnyCPU and part of the users / customers executed on a 32bit .NET Framework / other part of the users / customers executed on a 64bit .NET Framework / .NET Core would be solved? It seems this could render a completely correct and working application / library before (long / generic is not atomic on a 32bit machine) to a broken one.

I assume (since we already covered CAS earlier) that this is in reference to `type Foo = Foo of int64` being atomically readable and writable on 32 bit architectures due to being a reference type, while the struct version is not. I think this is niche as this type of programming is typically done with integers, but you're right that this is a silent breakage with the new default. However, I would argue that the ultimate culprit is [the F# specification](https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf) for tying its guarantees here to architecture-specific properties:

>F# value types map to a corresponding CLI value type that has corresponding fields. Reads and writes of sizes less than or equal to one machine word are atomic."

In contrast, [the C# specification](https://www.ecma-international.org/wp-content/uploads/ECMA-334_5th_edition_december_2017.pdf) only guarantees atomicity for a specific set of types up to 32 bits in size:

>Reads and writes of the following data types shall be atomic: bool, char, byte, sbyte, short, ushort, uint, int, float, and reference types. In addition,reads and writes of enum types with an underlying type in the previous list shall also be atomic. Reads and writes of other types, including long, ulong, double, and decimal, as well as user-defined types, need not be atomic.

I think this is a small defect in both specifications that makes it trickier than it should be to write portable concurrent programs (but less so in the case of C# as at least 32 bit loads and stores are atomic on every(?) architecture for which there is a CLR implementation).

>2. How the generic case when your type may or may not larger than the pointer size (even on 64 bit machine) or part of the cases are smaller part of the cases would be solved?
>3. How small is a small value type exactly? How small is a small value exactly in a constrained environment (iot, mobile, etc)?

Again, the suggestion is to change the default. I am not saying that the compiler should implement some heuristic for "small" and use this to determine the memory representation of a type. With the proposed behavior, if you define a single case discriminated union with a value type it would be up to you to specify, if desired, that it should be boxed. I think this is reasonable as the case of relying on a union to box some large value type is likely much less common than the case of the single case discriminated union with either a small value type or *any reference type*. (I'm assuming a similar conclusion was reached when deciding to make `Result` a value type despite having two generic type parameters with storage laid out sequentially in memory.)

>This suggestion could become: ...

The syntax from https://github.com/fsharp/fslang-suggestions/issues/727 seems good enough and, in my opinion at least, unions are easier to use in F# than classes. But, as mentioned above, I don't think sugar is necessary or desirable unless it also comes with improved semantics.

>Enum matches are exhaustiveness checked.

Your quote is from an exchange that was based on a misunderstanding where they were talking about representation while I was talking about semantics. That said, enums are not equivalent to valueless discriminated unions. Enums require qualified access, unions do not. An invalid enum can easily be created with the `enum` operator. The usual bevy of compiler-generated code is not generated for enums meaning they do not currently implement the generic equality/comparison interfaces.

My impression is that unions are preferred over enums in F# code and enums primarily exist for bitflags and interop so if some kind of sugar is added, struct unions, which have the same memory representation as enums, seem like the better choice. However, `type Foo = A | B | C` is already about as short as can be and there is a cost to having too many ways of doing the same thing, hence this proposal to add a way to change the default (again, acknowleding that the general policy is to not to do knobs like this).

**Comment by dsyme** [comment]
Closing for this reason: https://github.com/fsharp/fslang-suggestions/issues/987#issuecomment-791525609

I understand the suggestion and it's good to have it tracked - and it may have been reasonable to make this the original default for F# - but we won't be adding this kind of "change the defaults of the language" switch, or at least not for this case.
