### ISSUE TITLE
Where can I follow status for new language features and design thinking 

### ISSUE THREAD

**Issue by leandromoh** [fsharp/fslang-suggestions#989]
I am a C# developer learning F#. 

C# language repository offers pages to follow [implementation status for language features](https://github.com/dotnet/roslyn/blob/main/docs/Language%20Feature%20Status.md) as well [Language Design Meetings](https://github.com/dotnet/csharplang/tree/main/meetings) and I think it is very cool because I know what is comming in next language versions, as well that language is not stagnant; there is a team working on it and giving visibility about it for community.

Does something similar for F#? I really miss it.

**Comment by cartermp** [comment]
I recommend reading the README for this repository, as it outlines the process and general considerations for features. There aren't any plans to do status updates on things. The design process does not follow the LDM process that C# does. All designs are in the design repo here: https://github.com/fsharp/fslang-design
