### ISSUE TITLE
Support [<SkipLocalsInit>]

### ISSUE THREAD

**Issue by kerams** [fsharp/fslang-suggestions#990]
# Support `[<SkipLocalsInit>]`

I propose we support the [SkipLocalsInit attribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.skiplocalsinitattribute?view=net-5.0) introduced in .NET 5. A clear and succinct description of the feature including performance analysis is [here](https://www.meziantou.net/csharp-9-improve-performance-using-skiplocalsinit.htm), Roslyn feature design [here](https://github.com/dotnet/roslyn/blob/main/docs/features/skiplocalsinit.md).

Right now, the attribute is [present in the IL](https://sharplab.io/#v2:DYLgZgzgNALiCWwA+BtAPAZQJ4RgUwFsA6AJQFcA7GeAvIgYQHsCAHRPAJw04Dd4BjPBCIYA1vBYAZRvwCGwCAEkK8GAEEYMDvABGZfAD4AugFgAUMDwwABAA9rACgCU1gLznrn65Zv3X1gCIICFkAokk8CgBzGAALDy97AGprACZrACo7IA), but `.locals init` is still emitted. [An equivalent C# method](https://sharplab.io/#v2:C4LglgNgPgAgzAAhgJgQYQQbwLACgEEIDaMAjAHQBKArgHbBgC2ApuWgPaMAOkzATgGV+ANzABjZgGdyAgNZguAGXZiAhhEkBJWmGABdPISSIw9BAFkAFAEosho4WGq+CAB4IAvAgBEkyau9yRWZaAHNgAAsAbnsHJAB2NwQAagRUACo3GPxCAF88XKA) only contains `.locals`.

## Pros and Cons 

The advantages of making this adjustment to F# are
- Parity with C#
- Being able to reap the performance benefits of the attribute in very specific scenarios

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
Approved.

Indeed we could likely emit this attribute by default on nearly all F# functions and methods since F# almost never accesses locals before initialization (there are some places we rely on zero-init of locals to get a zero default value for a value type).

We could trial this in the compiler itself first to see what difference it makes for performance

**Comment by vzarytovskii** [comment]
Do we need an RFC for that?

**Comment by dsyme** [comment]
Hmmm I don't think so really, though a tiny short one can't hurt for tracking purposes

**Comment by abelbraaksma** [comment]
I thought I already made this request some time ago, but can't find it back, thanks for putting it out here! It's kinda in the same realm as the nonzeroing of array and struct memory, but I believe that wasn't completed for .NET 5.

**Comment by vzarytovskii** [comment]
I'm gonna to experiment a bit with not emitting it in the compiler and see results, probably gonna create an RFC for it.

**Comment by kerams** [comment]
@vzarytovskii, does that also entail the original suggestion, i.e. supporting the attribute in user code? I was thinking of having a little looksie at that.

**Comment by vzarytovskii** [comment]
> @vzarytovskii, does that also entail the original suggestion, i.e. supporting the attribute in user code, or are you only concerned with init skipping internally in the compiler? I was thinking of having a little looksie at that.

@kerams I mostly wanted to experiment around removing init in the compiler and see where do we rely on it. 

So, feel free to poke around the attribute :)
