### ISSUE TITLE
Make Event's AddHandler/RemoveHandler thread-safe

### ISSUE THREAD

**Issue by gsomix** [fsharp/fslang-suggestions#992]
# Make Event's AddHandler/RemoveHandler thread-safe

For now subscribing to `Event<'T>` might silently fail in concurrent context, because [`AddHandler` and `RemoveHandler` are not atomic operations](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/event.fs#L129-L133). It's hard to debug in production code and might be confusing since [C# generates additional code](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYYCmAbqQHYAu6AopbQBICGVwANqQE7oCyAT0bUaAbkLE0mACwCAFAEp8kogF9kaoA==) for events to achieve thread-safety. 

I propose to make similar changes to `FSharp.Core` event types.

The disadvantage of making this adjustment to F# is performance cost (relatively low!) of Compare-and-swap loop. It might affect a lot of existing code.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment]
I think this is a reasonable addition. @dsyme?

**Comment by baronfel** [comment]
From what I can tell, this wouldn't even be a language change as much as it would be a change to FSharp.Core, because the contention comes from the mutable assignment of the multicast field in event/delegate base classes in [event.fs](https://www.github.com/dotnet/fsharp/tree/main/src%2Ffsharp%2FFSharp.Core%2Fevent.fs). Is that a correct reading of the situation?

**Comment by dsyme** [comment]
Marked as approved - yes it can be a bug fix

**Comment by gsomix** [comment]
OK, I will prepare PR.
