### ISSUE TITLE
Convenience method for self-removing event handlers

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#993]
# Convenience method for self-removing event handlers

I propose we add the following to FSharp.Core:
```fs
// Two possible ways to implement
[<System.Runtime.CompilerServices.Extension>]
type EventExtensions =
    [<System.Runtime.CompilerServices.Extension>]
    static member AddRemove(e:IEvent<_>, handler) = // Less boilerplate on use site
        let mutable h = Unchecked.defaultof<_>
        h <- Handler<_>(handler (fun () -> e.RemoveHandler h))
        e.AddHandler h
    [<System.Runtime.CompilerServices.Extension>]
    static member AddRemove2(e:IDelegateEvent<_>, handler) = // Works with more delegate types
        let mutable h = Unchecked.defaultof<_>
        h <- handler (fun () -> e.RemoveHandler h)
        e.AddHandler h
```
Use:
```fs
let ev = Event<System.EventArgs>()
do ev.Publish.AddRemove <| fun remove sender e ->
    printfn "hey"
    remove()
do ev.Publish.AddRemove2 <| fun remove -> Handler<_>(fun sender e ->
    printfn "heya"
    remove())
do ev.Trigger(System.EventArgs())
do ev.Trigger(System.EventArgs())
do printfn "eyyy"
```

The existing way of approaching this problem in F# is
```fs
let ev = Event<System.EventArgs>()
let rec handler = Handler<_>(fun sender e ->
    printfn "hey"
    ev.Publish.RemoveHandler handler) // warning FS0040: This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions. This warning may be suppressed by using '#nowarn "40"' or '--nowarn:40'.
do ev.Publish.AddHandler handler 
do ev.Trigger(System.EventArgs())
do ev.Trigger(System.EventArgs())
```

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Convenience
2. Conciseness
3. Write correct code without being warned

The disadvantage of making this adjustment to F# is having one extra method to learn.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment]
This is rare enough that I don't see it going into FSharp.Core.  They can be added by the user in convenience code.
