### ISSUE TITLE
Friendlier attribute syntax

### ISSUE THREAD

**Issue by lambdakris** [fsharp/fslang-suggestions#994]
# Friendlier attribute syntax

I propose we introduce a friendlier attribute syntax more in line with Python, JavaScript, and TypeScript. Instead of `[<target:attribute-name(arguments)>]`, I think something like `@target:attribute-name(arguments)` would be more approachable and ergonomic. I think this would be particularly valuable given how prevalent the use of attributes has become in the .NET ecosystem, as well as F#'s affinity with Python and JavaScript.

#### ML.NET
```fsharp
...
type ProductSalesData = {
    @LoadColumn(0)
    Month: string
    @LoadColumn(1)
    NumSales: float
}

type ProductSalesPrediction = {
    @VectorType(3)
    Prediction: double []
}
...
```

#### Azure Functions
```fsharp
...
@FunctionName("FanOutFanIn")
let run (@OrchestrationTrigger context: IDurableOrchestrationContext) =
    ...
...
```
#### ASP.NET Core
```fsharp
...
@ApiController()
@Route("api/[controller]")
type TodoItemsController()
    inherit ControllerBase()
    ...
    @HttpPost()
    this.PostTodoItem (todoItem: TodoItem) =
        ...
...
```

#### EF Core
```fsharp
...
@CLIMutable
@Table("Item")
type Item = {
    @Key()
    @Column("ItemId")
    Id: int
}

type Db() =
    inherit DbContext()

    member val Items = base.Set<Item>()
...
```
### Variations
Inline Attributes
```fsharp
type @CLIMutable() Item = {
    @Key Id: int
}
```
Multiple Attributes
```fsharp
type @(CLIMutable(),Table("Item")) Item = {
    @(Key(),Column("ItemId")) Id: int
}
```

## Pros and Cons 

The advantages of making this adjustment to F# are:
1. An attribute syntax that requires less characters making it easier to read and write
2. An attribute syntax similar to other popular languages that have an affinity with F# which might make it more approachable or attractive

The disadvantages of making this adjustment to F# are:
1. It introduces more than one way of doing the same thing
2. I imagine it might be slightly more complex for the compiler to parse since it doesn't have an ending tokens
3. Perhaps it will clash with the use of the `@` symbol for list concatenation and verbatim strings

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: Did not find any

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by vzarytovskii** [comment]
Personally, I find existing attributes  syntax much more readable (and much easier to distinct).

It is also similar to both C# and VB, thus - easier to understand for someone coming from those languages.

I, personally, don't think we should change/add it.

**Comment by smoothdeveloper** [comment]
@lambdakris would you adjust your post to use fsharp colorization?

I'm ambivalent on more readable, I'd say more typeable, readbility wise, I concur with @vzarytovskii that they currently stand out.

The concern about their bulkiness and typeability isn't too much of a deal, as to having two syntaxes, but I'm sure the C# users have negative reaction to F# syntax, having a one character advantage through this suggestion may reduce this sentiment a tiny bit, and `@` is also familiar to all the other languages you mention.

I'm personally having a strong opinion that outside dotnet runtime and compiler stuff, the APIs with attributes tend to be overusing them and they very very (never) rarely expose the same same features in more rudimentary OO fashion (since this is all runtime type inspection).

This always irked me about those attributes fangled APIs.

Are there many F# APIs that rely on this type of design?

**Comment by lambdakris** [comment]
Yeah, I won’t deny that the heavier attribute usage tends to only appear when interfacing with the more standard .NET libs. For me in particular, I find it a bit taxing to work with F# and ML.NET and still prefer Python for data work, but I think slimming down the attribute syntax would really make a difference.

**Comment by cartermp** [comment]
I think we'd be highly unlikely to allow for an alternative attribute syntax. There are some .NET APIs that make heavy use of attributes, but others don't, and most F#-first APIs don't either. For example, FSharp.Stats is a great alternative to ML.NET for several statistical methods and it has a much friendlier API.

**Comment by xperiandri** [comment]
It is less readable

**Comment by l3m** [comment]
I feel that having multiple ways to achieve the same thing is a clear negative. 

And why would you choose one syntax over the other? I feel the answer is mainly 'personal preference'...

**Comment by dsyme** [comment]
I'll close this as the syntax was chosen in v1.0
