### ISSUE TITLE
`match?` and `function?` - optional matching with reduced syntax.

### ISSUE THREAD

**Issue by chillitom** [fsharp/fslang-suggestions#995]
# `match?` and `function?` - optional matching with reduced syntax.

I propose we introduce a new `match`/`function` mode for cases where the return value is an option.  In the default case we automatically return `None`.  All matched cases are automatically wrapped in `Some`.

```fsharp
let getChoice1Of2 = function Choice1Of2 a -> Some a | _ -> None
```
would become

```fsharp
let getChoice1Of2 = function? Choice1Of2 a -> a
```

Another example, used as an inline function when mapping over lists.

```fsharp
xs |> List.choose (function? Choice1Of2 a -> a)
```

A similar `match?` syntax would exist `match? x with Choice1Of2 a -> a`

Here's an example before and after for some code from the compiler:

*Before*
```fsharp
        | SynExpr.IfThenElse (guardExpr, thenComp, elseCompOpt, spIfToThen, isRecovery, mIfToThen, mIfToEndOfElseBranch) ->
            match convertSimpleReturnToExpr varSpace thenComp with
            | None -> None
            | Some (_, Some _) -> None
            | Some (thenExpr, None) ->
                let elseExprOptOpt  = 
                    match elseCompOpt with 
                    | None -> Some None 
                    | Some elseComp -> 
                        match convertSimpleReturnToExpr varSpace elseComp with
                        | None -> None // failure
                        | Some (_, Some _) -> None // custom op on branch = failure
                        | Some (elseExpr, None) -> Some (Some elseExpr)
                match elseExprOptOpt with 
                | None -> None
                | Some elseExprOpt -> Some (SynExpr.IfThenElse (guardExpr, thenExpr, elseExprOpt, spIfToThen, isRecovery, mIfToThen, mIfToEndOfElseBranch), None)

```
*After*
```fsharp
        | SynExpr.IfThenElse (guardExpr, thenComp, elseCompOpt, spIfToThen, isRecovery, mIfToThen, mIfToEndOfElseBranch) ->
            match? convertSimpleReturnToExpr varSpace thenComp with
            | Some (thenExpr, None) ->
                let elseExprOptOpt  = 
                    match elseCompOpt with 
                    | None -> Some None 
                    | Some elseComp -> 
                        match? convertSimpleReturnToExpr varSpace elseComp with
                        | Some (elseExpr, None) -> Some elseExpr
                match? elseExprOptOpt with 
                | Some elseExprOpt -> (SynExpr.IfThenElse (guardExpr, thenExpr, elseExprOpt, spIfToThen, isRecovery, mIfToThen, mIfToEndOfElseBranch), None)
```

## Pros and Cons 

The advantages of making this adjustment to F# are.
1. reduces boilers plate
2. great for single line matches

The disadvantages of making this adjustment to F# are ...
1. two new keywords
2. might be surprising when first encountered

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by smoothdeveloper** [comment]
The fact that it is specific to `FSharpOption` is the first thing that comes to me as bothering.

I think it also challenges some of the explicitness design choices in F#, this is likely going to be a though battle if you want this to land in the language 🙂.

I've faced many situations where I changed such `match` to return an option value, and it would be just a `?` (and potentially a type annotation) away with a feature similar to this suggestion. I'm currently not too bothered being explicit when I face that situation, not enough to upvote the suggestion.

Could you expand on how a similar suggestion could work for other types than just `FSharpOption` or why it wouldn't feel relevant to consider this upfront for such a feature?

**Comment by laenas** [comment]
How do you envision this working alongside `match!` syntax in CEs?

**Comment by vzarytovskii** [comment]
While, as you mentioned, it can reduce the boilerplate code, but at a cost of adding more implicit behaviour, which, in my opinion may be quite confusing.

**Comment by chillitom** [comment]
> How do you envision this working alongside `match!` syntax in CEs?

This is not something I had considered but I would imagine it working along the same lines as `match!`.. it is simply a special case where the result is `Option<'t>` (or some equivalent).  If `match!` were implemented in a custom computation expression it might be possible to auto-implement `match?!`. I admit the syntax could look a bit dodgy though `?!` hehe..  I'm not wed to the syntax.. more keen to see if there's a way that we could reduce the amount of wrapping/unwrapping that a developer needs to do.

**Comment by gusty** [comment]
I think #766 would cover this in a more generic and consistent way.

Instead of `let getChoice1Of2 = function? Choice1Of2 a -> a` you'll simply write something like `(|Choice1Of2|_|)`

**Comment by chillitom** [comment]
> I think #766 would cover this in a more generic and consistent way.
> 
> Instead of `let getChoice1Of2 = function? Choice1Of2 a -> a` you'll simply write something like `(|Choice1Of2|_|)`

Thanks @gusty, that's a nice lang suggestion and would certainly reduce a lot of the same boiler plate in many cases, I've upvoted it.  I see that @charlesroddie has actually made the exact same suggestion as I have here and I think he nails the Pros and Cons.  With the approach here you can destructure more complicated types and multiple cases as with a normal match.

**Comment by dsyme** [comment]
I see the suggestion but I don't think the additional complexity it brings to the language design is worth the gain in succinctness. 

Part of this is that it is tied to Option, as described above.

I'll close this as we won't be doing this in the language
