### ISSUE TITLE
The `matchFail` intrinsic

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#996]
# The `matchFail` intrinsic

Currently, for [unreachable cases](https://github.com/dotnet/fsharp/blob/6b1af129b798d0b3b7c296b27e8c2a5ad4f1dad8/src/fsharp/AttributeChecking.fs#L166) in match expressions, we must add a `failwith` which does not contain helpful information when the supposedly unreachable case was reached. Moreover, the more we want to add information, the more boilerplate we need.

I propose we add the `matchFail` intrinsic:
```fs
match System.Console.ReadLine() |> int with
| 2 -> ()
| _ -> matchFail
```
Now we can indicate unreachableness with a standardised way.

Upon reaching this intrinsic, a `MatchFailureException` will be raised just like if we didn't add a branch at the end. However, the error message would be improved:
```
Microsoft.FSharp.Core.MatchFailureException: The value '1' resulting from the expression as defined in "input.fsx" starting at line 1 character 6 failed to match a case.
```
compared to
```
Microsoft.FSharp.Core.MatchFailureException: The match cases were incomplete
```
Currently, the code generation for
```fs
match System.Console.ReadLine() |> int with
| 2 -> ()
```
is
```cs
switch (LanguagePrimitives.ParseInt32(Console.ReadLine()))
{
    case 2:
        return;
}
throw new MatchFailureException("_.fs", 1, 6);
```
which indicates that the three arguments to `MatchFailureException` are file, line and character respectively.

However, the value is not stored in this exception! How can we add it so that the new exception message can be generated?

I propose that we modify this generation to:

```cs
switch (LanguagePrimitives.ParseInt32(Console.ReadLine()))
{
    case 2:
        return;
    case var x:
        throw new MatchFailureException("_.fs", 1, 6) { Data = { ["Value"] = x } };
}
```
such that we can use the value to generate the new exception message. The presence of this entry can also determine if the new exception message should be used?

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience

The disadvantage of making this adjustment to F# is that it may not be obvious which `match` `matchFail` refers to. However, this can be remedied by highlighting and treating it like a keyword as done with `nameof`.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (none)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment]
What about making the change to the exception type you suggest, and using an annotation instead of an explicit `matchfail`:

```fsharp
[<SuppressIncompletenessWarning>]
match System.Console.ReadLine() |> int with
| 2 -> ()
```

**Comment by Happypig375** [comment]
That's no different from a local #nowarn which may suppress unintendedly. Also, it's not as flexible as it can't
```fs
match System.Console.ReadLine() |> int with
| "2" -> matchFail // The keyboard filters out 2s automatically
| x -> f x
```

**Comment by Frassle** [comment]
More general than matchFail it would be good to just have an "unreachable" expression, that could do something more specific in a match clause.

**Comment by jwosty** [comment]
> 
> 
> More general than matchFail it would be good to just have an "unreachable" expression, that could do something more specific in a match clause.

Sounds like #349 - Bottom type.

**Comment by dsyme** [comment]
I don't understand why the user can't program up a `matchFail` as they like, if necessary including value etc. (which they pass as an argument), nor do I particularly understand why they'd want to make it explicit.   It's not a lot of bolierplate is it?

**Comment by Happypig375** [comment]
It's like `Option.get` - we know that it will match and failing to match indicates a programming bug. If `Option.get` gets a shorthand, why can't `matchFail`? We implicitly record file and line information as well using `__SOURCE_FILE__` and `__LINE__` which are also boilerplate themselves. The improvement for MatchFailureException which is independent of `matchFail` cannot be done by the user as well.

**Comment by dsyme** [comment]
For well-written F# programs, we basically expect no incomplete matches to exist in completed code.  That's the point of the warning.  I don't see the point in allowing the user to hand-write incomplete match exceptions when the aim is to not have any of them. Allowing them to do that is more like `Unchecked.defaultof<_>` - a hole in your program - and I don't think we need to add a new kind of hole :)

**Comment by Happypig375** [comment]
This is useful in e.g. code for tests where we expect a known output and we want to fail descriptively when encountering something else.

**Comment by dsyme** [comment]
I don't see us adding this to the F# programming model.

The MatchFailureException isn't really something we want user code to be deliberately raising - it represents a very specific condition that a match-incompleteness warning was ignored and if it ever happens you really have to go back and look at why you were ignoring those at all.

If the user explicitly adds wildcards then they should reveal those cases using their own exceptions and diagnostics.
