### ISSUE TITLE
Allow operators as active patterns

### ISSUE THREAD

**Issue by gusty** [fsharp/fslang-suggestions#998]
# Allow operators as active patterns

I propose we allow to define operators as active patterns, so we'll be able to write code like this:

```fsharp
match x with
| a ++ b -> ...
```

or 

```fsharp
let (a ++ b) = x
```

This can be defined like `let (| ++ |) x = ...`

## Pros and Cons 

The advantages of making this adjustment to F# are:

 - More symmetry with operators used for construction.
 - Consistency with list pattern matching for list-like and tuple-like things.
 - More identifiers available for active patterns

The disadvantages of making this adjustment to F# are

 - Possible complications in updating F# parser

## Extra information

Estimated cost XS / S: 

Related suggestions: none that I know

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by 7sharp9** [comment]
What would happen to the existing pattern match operators `|`, `&` in that context?

**Comment by Tarmil** [comment]
@7sharp9 `|` is already not a valid custom operator, and `&` gives a warning that it shouldn't be used, so I guess it would be reasonable to forbid both of them as custom pattern operators.

**Comment by 7sharp9** [comment]
I meant during the match, as &/| are already allowed.

**Comment by smoothdeveloper** [comment]
It is hard for me to comment without understanding more about code where you'd use it. 

It would help me if you'd had samples of before/after added to the suggestion.

On the syntax, if the semantics are the same as active patterns, I suggest this:

```fsharp
let (|a ++ b|) = x
```

**Comment by vzarytovskii** [comment]
Closing all `probably not` issues.
