### ISSUE TITLE
Sooth fluent API pain with a first class construct / `ignore ()` / `|> ignore` / `let _ =`

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/fslang-suggestions#999]
In the whole of dotnet libraries / codebases, fluent API (through chained member calls) have become popular, to the point of reaching some of the frameworks shipping with dotnet and popular libraries.

F# has quite a few ways to deal with this

The existing way of approaching this problem in F# is

```fsharp
let _ =
  thing
    .Foo()
    .Bar()
    // ...
```

```fsharp
ignore (
    thing
      .Foo()
      .Bar()
      // ...
)
```

```fsharp
thing
  .Foo()
  .Bar()
  |> ignore
```

```fsharp
ignore <|
  thing
    .Foo()
    .Bar()
```

```fsharp
#nowarn "20"
thing
  .Foo()
  .Bar()
```

the warning is very valuable, and a core aspect of F# language, yet, it can get in the way of readability since there are at least three ways of doing the same thing idiomatically, and they all feel tedious / clunky when the intent is to deal with a fluent API (which are widespread). 

The first one doesn't work as the last expression of a block.

The last one is not to be used, but I mention it because it technically addresses this concern.

I don't want to orient on the proper syntactic solution, but I had those coming to mind:

```fsharp
discard
  // anything under it as a block won't generate the FS0020 warning
  thing
    .Foo()
    .Bar()
```

```fsharp
ignore
  // anything under it as a block won't generate the FS0020 warning
  thing
    .Foo()
    .Bar()
```

```fsharp
do ignore
  // anything under it as a block won't generate the FS0020 warning
  thing
    .Foo()
    .Bar()
```

I'm looking for other suggestions or getting confirmation that people are fine with how it is as of F# 5.

The tooling could propose to refactor when it detects the idiom.

## Pros and Cons 

The advantages of making this adjustment to F# are that consuming fluent API will have a first class construct in the language, superseding the current approaches.

The disadvantages of making this adjustment to F# are more keywords / contructs, another standard to do what the suggestion is about.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by theprash** [comment]
I just thought of this but I'm not sure if you would consider it a helpful alternative:

```fsharp
type System.Object with
    member _.Ignore = ()
```

Usage:

```fsharp
thing
  .Foo()
  .Bar()
  .Ignore
```

**Comment by smoothdeveloper** [comment]
@theprash, this is an excellent solution to the fluent API pain! so much that it could prompt me to close the suggestion 🙂 

I'll try it and see if there are negative reactions in code review.

The reasons I posted it is that I encounter couple of times people asking about *any better than |> ignore* and I was dealing with writing some more of those at end of fluent API chain.

The concern that for C# developers, they initially see this as a smell and only later on, if they stick with the language, gain appreciation for the warning, yet the `|> ignore` stands out a bit.

I think one distinction I'd see with the suggestion, is that it could allow to address the issue in a block, but this is minor if F# codebases using lots of fluent API standardise on `System.Object.Ignore(d)` type extension.

@Happypig375 I'm lost in translation, your code sample doesn't show fluent API call chain, and the issue you point about is about type coercion in context which I don't connect to the concern with the suggestion. Feel free to expand if me missing your point is a concern.

**Comment by TheJayMann** [comment]
I was thinking a solution similar to this, but, rather than call it `Ignore`, I think it would look better if it was called `Done`.  Ultimately, the name doesn't matter much, so long as it is able to convey the meaning of the code properly, and, given that this is, more or less, a per project solution, the name can be changed to whatever suits the individual best.

**Comment by smoothdeveloper** [comment]
> Ultimately, the name doesn't matter much

what matter to me would be that the F# codebases align, even if the extension is just defined as adhoc extension in codebases here and there (that decreases the chance for alignment, versus say, baking the extension under FSharp.Core.Fluent in FSharp.Core assembly).

That, and the smaller concern of having the ability to "discard" the warning for a whole block.

**Comment by Happypig375** [comment]
We can also borrow the assignable discard from C#: `_ <- x`

**Comment by smoothdeveloper** [comment]
@Happypig375, in such case, `let _ =` is as good to me.

I am generally not too excited about changing the compiler to avoid few characters in very particular use cases (fluent API are popular, but fluent API consuming code is not an idiom represented in a big share of codebase).

I'm currently thinking that @theprash solution, if we could bake it in FSharp.Core, is all we need if a "discard" block construct is rejected on some grounds.

**Comment by Happypig375** [comment]
```fs
ignore <|
    x
    .Y
    .Z()
```
?

**Comment by smoothdeveloper** [comment]
Adding it to the suggestion, but it often fails the "F# code @dsyme love" criteria.

**Comment by olivercoad** [comment]
I think I'm fine with how it currently is as of F# 5 but I don't tend to use fluent APIs very often.

However, If this were implemented, I think something like `do ignore` would make sense.  
Actually (I'm sure there are probably a hundred reasons it's a bad idea) why not even just `do`? If the purpose of explicitely using the `do` keyword is to document that you're not interested in the value, then why should you also need to explicitely ignore the value?
  
Also here is another proposed solution using operators https://github.com/fsharp/fslang-suggestions/issues/711#issuecomment-629633122

**Comment by smoothdeveloper** [comment]
@olivercoad, thanks for the feedback (and pointing to example which exhibits well `|> ignore` turning noisy.

Regarding repurposing `do` itself to discard the warning, my concern is that I do use it for scoping some code in long methods, and it can be nested, it may feel right on the surface but I don't like the idea of discarding the warning in all existing `do` blocks.

I'm also not sure how they translate in the AST: https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYVYABQBKMAF4AOgCcJyCNFbTZECNz4APcUOFK5Kkbt0QARrADmKIyrVhNY7VYgGZe2MmiQQAXyA but they don't seem to be easily distinguishable from `begin/end` pairs as of now (not that this would technically block anything, but worth considering as it impacts consumers of the AST if going with a block construct).

**Comment by Happypig375** [comment]
Please, `ignore <|` is the same length as `do ignore` and is usable today. Although @dsyme dislikes `<|`, he also dislikes multiple ways to do the same thing.

**Comment by dsyme** [comment]
Closing this as user-defined `.Ignore` appears to be a perfectly good solution to this problem 

Please open a new suggestion if you've like to propose adding `.Ignore` to FSharp.Core
